geotools/geotools

- modules/extension/xsd/xsd-wfs/src/main/java/org/geotools/wfs/v2_0/bindings/FeatureTypeTypeBinding.java
- modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/bindings/FeatureTypeTypeBindingTest.java
Backport of https://github.com/geotools/geotools/pull/2973
-duplicate entries in Other SRS list of a feature type described in WFS
2.0.0 document removed.
> [Backport-22.x][GEOT-6620] OTHER_SRS list has duplicate entries for WFS 2.0.0

- modules/plugin/epsg-postgresql/src/main/java/org/geotools/referencing/epsg/postgresql/ThreadedPostgreSQLEpsgFactory.java
- pom.xml
Update the PostgreSQL jdbc driver from 42.2.5 to 42.2.14, resolves CVE-2020-13692 (PostgreSQL JDBC Driver (aka PgJDBC) before 42.2.13 allows XXE) .
fix deprecated method use in `ThreadedPostgreSQLEpsgFactory `
see also:
- https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.13
- https://osgeo-org.atlassian.net/browse/GEOT-6626 …
> [GEOT-6626] Update PostgreSQL driver to 42.2.14

- modules/plugin/epsg-postgresql/src/main/java/org/geotools/referencing/epsg/postgresql/ThreadedPostgreSQLEpsgFactory.java
- pom.xml
backport #2992 
Update the PostgreSQL jdbc driver from 42.2.5 to 42.2.14, resolves CVE-2020-13692 (PostgreSQL JDBC Driver (aka PgJDBC) before 42.2.13 allows XXE) .
fix deprecated method use in `ThreadedPostgreSQLEpsgFactory`
see also:
https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.13
https://osgeo-org.atlassian.net/browse/GEOT-6626
> [Backport-23.x][GEOT-6626] Update PostgreSQL driver to 42.2.14

- modules/plugin/epsg-postgresql/src/main/java/org/geotools/referencing/epsg/postgresql/ThreadedPostgreSQLEpsgFactory.java
- pom.xml
backport #2992 
Update the PostgreSQL jdbc driver from 42.2.5 to 42.2.14, resolves CVE-2020-13692 (PostgreSQL JDBC Driver (aka PgJDBC) before 42.2.13 allows XXE) .
fix deprecated method use in `ThreadedPostgreSQLEpsgFactory`
see also:
https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.13
https://osgeo-org.atlassian.net/browse/GEOT-6626
> [Backport-22.x][GEOT-6626] Update PostgreSQL driver to 42.2.14

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/ExtendedRandomIter.java
- modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java
- modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/RasterAsPointCollectionProcessTest.java
- modules/unsupported/process-raster/src/test/resources/org/geotools/process/raster/test-data/arrows.sld
This pull request fixes nodata values being converted to zero when using a raster to vector rendering transformation across the dateline by setting the background of the Border operation to be the same as the nodata value when resampling a coverage with a nodata value. …
> [GEOT-6636] Raster to Vector rendering transformations can lose nodata values when crossing the dateline

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDumper.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureWriter.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDumperTest.java
- modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dumper/MultiTypeEmpty.properties
Went a bit further and checked all types of empty geometries are correctly handled. Since the shapefile has no notion of "empty", went for replacing those with null geometries (that's a legit geometry type in shapefile, and the only one that can be mixed with other geometry types in the same file).
Submitting the PR does not require you to check all items, but by the time …
> [GEOT-6643] Shapefile write fails when encountering MULTIPOLYGON EMPTY geometries

- modules/library/main/src/main/java/org/geotools/renderer/crs/WrappingProjectionHandler.java
- modules/library/main/src/test/java/org/geotools/renderer/crs/WrappingProjectionHandlerTest.java
This PR introduces a fix for WrappingProjectionHandler::accumulate method allowing mixed Geometry types use cases.  It also adds a test for the fixed function.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-6648
> [GEOT-6648] WrappingProjectionHandler::accumulate method doesn't support a mixed Geometry typed GeometryCollection

- modules/library/main/src/main/java/org/geotools/renderer/crs/WrappingProjectionHandler.java
- modules/library/main/src/test/java/org/geotools/renderer/crs/WrappingProjectionHandlerTest.java
This PR introduces a fix for WrappingProjectionHandler::accumulate method allowing mixed Geometry types use cases. It also adds a test for the fixed function.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-6648
Submitting the PR does not require you to check all items, but by the time it …
> [23.x backport][GEOT-6648] WrappingProjectionHandler::accumulate method doesn't support a mixed Geometry typed GeometryCollection

- modules/library/main/src/main/java/org/geotools/renderer/crs/WrappingProjectionHandler.java
- modules/library/main/src/test/java/org/geotools/renderer/crs/WrappingProjectionHandlerTest.java
This PR introduces a fix for WrappingProjectionHandler::accumulate method allowing mixed Geometry types use cases. It also adds a test for the fixed function.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-6648
Submitting the PR does not require you to check all items, but by the time it …
> [22.x backport][GEOT-6648] WrappingProjectionHandler::accumulate method doesn't support a mixed Geometry typed GeometryCollection

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/AbstractWFSStrategy.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/URIs.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/BuildURLTest.java
JIRA : https://osgeo-org.atlassian.net/browse/GEOT-6654
Issue : https://github.com/geosolutions-it/C061-2019-COWI-GS-ENH/issues/47
-added tolerance to system charset for GetFeature requests in WFS-NG
Submitting the PR does not require you to check all items, but by the time it gets merged, they …
> [GEOT-6654] WFS-NG GetFeature GET request URL encoding breaks with ISO-8859-1 strings

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/AbstractWFSStrategy.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/URIs.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/BuildURLTest.java
backport of https://github.com/geotools/geotools/pull/3053
-added tolerance to system charset for GetFeature requests in WFS-NG
> [23.x backport][GEOT-6654] WFS-NG GetFeature GET request URL encoding breaks with ISO-8859-1 strings

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/AbstractWFSStrategy.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/URIs.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/BuildURLTest.java
backport of https://github.com/geotools/geotools/pull/3053
-added tolerance to system charset for GetFeature requests in WFS-NG
> [Backport 22.x][GEOT-6654] WFS-NG GetFeature GET request URL encoding breaks with ISO-8859-1 strings

- docs/user/extension/mbstyle/spec/layers.rst
- modules/extension/mbstyle/src/main/java/org/geotools/mbstyle/expression/MBExpression.java
- modules/extension/mbstyle/src/main/java/org/geotools/mbstyle/expression/MBLookup.java
- modules/extension/mbstyle/src/main/java/org/geotools/mbstyle/layer/BackgroundMBLayer.java
- modules/extension/mbstyle/src/main/java/org/geotools/mbstyle/layer/FillMBLayer.java
- modules/extension/mbstyle/src/main/java/org/geotools/mbstyle/layer/LineMBLayer.java
- modules/extension/mbstyle/src/main/java/org/geotools/mbstyle/layer/SymbolMBLayer.java
- modules/extension/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBFilter.java
- modules/extension/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBFunction.java
- modules/extension/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBObjectParser.java
- modules/extension/mbstyle/src/test/java/org/geotools/mbstyle/expression/MBLookupTest.java
- modules/extension/mbstyle/src/test/java/org/geotools/mbstyle/parse/MBFilterTest.java
- modules/library/cql/src/main/java/org/geotools/filter/text/commons/ExpressionToText.java
The filter support used by GeoTools has been moved to "Legacy - Other filter":
```
filter: [">", "scalerank", 2]
```
This has been replaced with the use of expressions:
```
filter: [">", ["get","scalerank"], 2]
```
This means we can no longer use style examples available online.
See https://osgeo-org.atlassian.net/browse/GEOT-6589 for details.
> Support mbstyle filter expressions [GEOT-6589] 

- modules/extension/xsd/xsd-core/pom.xml
- pom.xml
This commit reverts the change from https://github.com/geotools/geotools/pull/3072, we found that the xsd dependency included transitive dependencies allowing it to be used as an eclipse plugin.
It is unclear if the `xsd` library is still published, or is only under active development as an eclipse plugin!
* [Use of XSD as a library, avoiding transitive dependencies](https://bugs.eclipse.org/bugs/show_bug.cgi?id=565408)
> [GEOT-6664] Revert to use of xsd as library

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/ExtendedRandomIter.java
- modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java
- modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/RasterAsPointCollectionProcessTest.java
- modules/unsupported/process-raster/src/test/resources/org/geotools/process/raster/test-data/arrows.sld
22.x backport for [GEOT-6636] Raster to Vector rendering transformations can lose nodata values when crossing the dateline
> [22.x][GEOT-6636] Raster to Vector rendering transformations can lose nodata values when crossing the dateline

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/ExtendedRandomIter.java
- modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java
- modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/RasterAsPointCollectionProcessTest.java
- modules/unsupported/process-raster/src/test/resources/org/geotools/process/raster/test-data/arrows.sld
23.x backport for [GEOT-6636] Raster to Vector rendering transformations can lose nodata values when crossing the dateline
> [23.x][GEOT-6636] Raster to Vector rendering transformations can lose nodata values when crossing the dateline

- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticAttribute.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticDataStore.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticFeatureReader.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticFeatureTypeBuilder.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/FilterToElastic.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticAttributeTest.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFilterTest.java
Updates the `dateFormat` field of `ElasticAttribute`s to be a List of Strings, rather than a single String. Because Elasticsearch can serve back multiple valid date formats, separated by `||`, we need to have a way to handle multiple different possible date formats.
An important note: this update breaks previously existing data stores due to changing the underlying attributes. I'm not sure the proper way to do a data store migration for a change like this,
Coincides with GeoServer PR: https://github.com/geoserver/geoserver/pull/4270
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles …
> [GEOT-6577] Allow plugin to handle multiple valid date formats from elastic

- docs/developer/procedures/release.rst
It has been some time since CITE test results were available.
> Determine revision to release from geoserver binary download VERSION.txt

- modules/library/main/src/main/java/org/geotools/geometry/jts/CircularRing.java
- modules/library/main/src/main/java/org/geotools/geometry/jts/CircularString.java
- modules/library/main/src/main/java/org/geotools/geometry/jts/CompoundCurve.java
- modules/library/main/src/main/java/org/geotools/geometry/jts/CompoundRing.java
- modules/library/main/src/test/java/org/geotools/geometry/jts/CurvedGeometryTest.java
- modules/library/metadata/src/test/java/org/geotools/util/factory/GeoToolsTest.java
- modules/library/render/src/main/java/org/geotools/renderer/label/LineStringCursor.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/SimpleGeometryFactory.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoGeometryBuilder.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/shp/JTSUtilitiesTest.java
- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/ClipProcess.java
- pom.xml
This pull request upgrades to JTS 1.17.1 release:
* Performance improvement for CoordinateArraySequence required use of CoordianteArrays.enforceConsitency in GeoTools ClipProcess (previously the constructor enforced consistency)
* The unintended problems method visibility of Geometry reverse and reverseInternal methods introduced in JTS 1.7.0 have been addressed.
See https://osgeo-org.atlassian.net/browse/GEOT-6688
The following are required only for core and extension modules (they are welcomed, …
> Upgrade to JTS 1.17.1 [GEOT-6688]

- modules/plugin/imagemosaic-jdbc/src/test/java/org/geotools/gce/imagemosaic/jdbc/MySqlOnlineTest.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDataStoreFactory.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLTestSetup.java
- pom.xml
Backports the **driver update only** from #3128 to 23.x
> [23.x backport][GEOT-6692] Update MySQL jdbc driver to current version (8.0.x)

- modules/library/main/src/main/java/org/geotools/filter/visitor/SimplifyingFilterVisitor.java
- modules/library/main/src/test/java/org/geotools/filter/visitor/SimplifyingFilterVisitorTest.java
when simplifying negations
"not(a between 10 and 20)" results in "a < 10 or a > 20", but it should be "a < 10 or a > 20 or a is null" in SimplifyingFilterVisitor
> [GEOT-6270] SimplifyingFilterVisitor does not account for null values

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/GeometryColumnEncoder.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGIS3DOnlineTest.java
This pr fixes a bug occuring when rendering 3D geometry, that was leading to aWKB exception due missing ST_Force2D postgis function.
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6373
> [GEOT-6373] Error in geoserver 2.16.0:  "org.geotools.data.DataSourceException: An exception occurred while parsing WKB data"

- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
The intention of this PR is to fix the problem with a lost precision while preserving backward-compatibility where possible. Mapping between Java classes and SQL types has been modified from:
```
// Saving:
Float.class -> REAL
Double.class -> REAL
// Reading:
FLOAT -> Double.class (implicit by JDBC read value)
DOUBLE -> Double.class
REAL -> Double.class (implicit by JDBC read value)
```
into:
```
Saving:
Float.class -> FLOAT
Double.class -> DOUBLE
Reading:
FLOAT -> Double.class (explicit)
DOUBLE -> Double.class
REAL -> Double.class (explicit)
```
According to the GeoPackage specification http://www.geopackage.org/spec/ there is no difference between `DOUBLE` and `REAL` types - both can be used interchangeably (Table 1. GeoPackage Data Types).  Moreover, SQLite types are only hints and …
> [GEOT-6722] Fix lost precision bug when saving a Double to GeoPackage

- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
> [23.x backport] [GEOT-6722] Fix lost precision bug when saving a Double to GeoPackage

- modules/extension/tile-client/src/main/java/org/geotools/tile/Tile.java
- modules/extension/tile-client/src/test/java/org/geotools/tile/impl/osm/OSMTileTest.java
Reverts geotools/geotools#2954 - as in combination with https://osgeo-org.atlassian.net/browse/GEOT-6618 it sends a double user-agent header which breaks some servers,
> Revert "[GEOT-6608] Fix user-agent for OSM tiles"

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
Back port fix for https://osgeo-org.atlassian.net/browse/GEOT-6679 to 24.x
> [GEOT-6679] Not filter visitor doesn't map property name

- docs/pom.xml
- modules/ogc/net.opengis.wfs/pom.xml
- pom.xml
This resolves Maven telling us thinks are not A-OK:
```
└─ $ ▶ mvn clean verify -Dall
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.geotools.ogc:net.opengis.wfs:jar:25-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: junit:junit:jar -> duplicate declaration of version (?) @ line 41, column 17
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.geotools:gt-elasticsearch:jar:25-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-checkstyle-plugin is missing. @ line 227, column 14
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for …
```
> Resolve various Maven warnings

- modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/GranuleStore.java
- modules/library/main/src/main/java/org/geotools/data/DataStore.java
- modules/library/main/src/main/java/org/geotools/data/FeatureStore.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLTransactionOnlineTest.java
> Fix typos in several DataStore classes

- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/GroupCandidateSelectionProcess.java
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/GroupCandidateSelectionProcessTest.java
- modules/unsupported/process-feature/src/test/resources/org/geotools/process/vector/test-data/featuresToGroupWithNullValues.properties
Fix a bug causing npe when operationAttribute propertyName returns null in GroupCandidateSelection vectorProcess.
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6732
> [GEOT-6732] GroupCandidateSelection RT throws NPE if operation attribute return null

- modules/plugin/jdbc/jdbc-sqlserver/pom.xml
- pom.xml
All of these have had some patch releases, so they should be upgraded.
```
com.oracle.database.jdbc:ojdbc8 ................. 19.7.0.0 -> 19.8.0.0
org.postgresql:postgresql ......................... 42.2.14 -> 42.2.18
com.microsoft.sqlserver:mssql-jdbc .......... 8.2.2.jre8 -> 8.4.1.jre8
```
also move SQL Server drivers into `dependencyManagement` section
resolves https://osgeo-org.atlassian.net/browse/GEOT-6737
backports #3207 to 24.x
> [24.x backport][GEOT-6737] Update PostgreSQL (to 42.2.18), Oracle (to 19.8.0.0) and MS SQL Server (to 8.4.1.jre8) JDBC drivers

- modules/plugin/jdbc/jdbc-sqlserver/pom.xml
- pom.xml
All of these have had some patch releases, so they should be upgraded.
```
org.postgresql:postgresql ......................... 42.2.14 -> 42.2.18
com.microsoft.sqlserver:mssql-jdbc .......... 8.2.2.jre8 -> 8.4.1.jre8
```
also move SQL Server drivers into `dependencyManagement` section
resolves https://osgeo-org.atlassian.net/browse/GEOT-6737
backports #3207 to 23.x (note that the oracle driver is not upgraded for 23.x as it was never upgraded to ojdbc8 in 23.x to begin with)
> [23.x backport][GEOT-6737] Update PostgreSQL (to 42.2.18) and MS SQL Server (to 8.4.1.jre8) JDBC drivers

- modules/library/main/src/main/java/org/geotools/filter/function/AndFunction.java
- modules/library/main/src/main/java/org/geotools/filter/function/OrFunction.java
- modules/library/main/src/main/resources/META-INF/services/org.opengis.filter.expression.Function
- modules/library/main/src/test/java/org/geotools/filter/AndFunctionTest.java
- modules/library/main/src/test/java/org/geotools/filter/OrFunctionTest.java
This PR adds two new functions And and Or and provides capabilities to manage logical operators on FilterFactory.
e.g
```
IF AREA(geomFromWKT('POLYGON ((150 330, 220 330, 220 230, 150 230, 150 330))'))>0 and 'string1'='string1' THEN 10 ELSE -1"
```
can be translated to  : 
```java
FilterFactoryImpl ff = new FilterFactoryImpl();
Function geom = ff.function("geomFromWKT", ff.literal("POLYGON ((150 330, 220 330, 220 230, 150 230, 150 330))"));
Function geom_area = ff.function("area",geom);
Function equalsTo_left = ff.function("greaterThan", geom_area, ff.literal(0));
Function equalsTo_right = ff.function("equalTo", ff.literal("string1"), ff.literal("string1"));
Function andFunction = ff.function("and", equalsTo_left, equalsTo_right);
Function if_then_elseFunction = …
```
> [GEOT-6733] Add new expression functions to support And && Or operators

- .travis.yml
- .travis/setup-mysql.sh
- .travis/start-mysql.sh
- docs/developer/conventions/test/online.rst
- docs/user/library/jdbc/mysql.rst
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDataStoreFactory.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDialect.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDialectBasic.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDialectPrepared.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLFilterToSQL.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLAggregateTestSetup.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLDataStoreAPITestSetup.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLDataStoreAutoEnhandedSpatialSupportTest.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLDataStoreFactoryTest.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLDataStoreManualEnhandedSpatialSupportTest.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLEmptyTestSetup.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLJoinTestSetup.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLNoPrimaryKeyTestSetup.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLTestSetup.java
- pom.xml
backports #3191 to 24.x
Brings support for MySQL 8 (which now has some sort of Geography datatype)
- [GEOT-6690](https://osgeo-org.atlassian.net/browse/GEOT-6690) - support MySQL 8
- [GEOT-6692](https://osgeo-org.atlassian.net/browse/GEOT-6692) - upgrade driver
> [24.x backport] [GEOT-6690] [GEOT-6692] MySQL 8 support and upgrade MySQL driver to 8.0.22

- modules/library/main/src/main/java/org/geotools/filter/visitor/PostPreProcessFilterSplittingVisitor.java
- modules/library/main/src/test/java/org/geotools/filter/visitor/PostPreProcessFilterSplittingVisitorTest.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6746
Fix a bug in PostPreProcessingFilter visitor caused by the usage of the wrong variable to retrieve Functions' parameters
> [GEOT-6746] PostPreProcessingFilter indexOutOfBoundsException

- .github/PULL_REQUEST_TEMPLATE.md
Removes reference to travis-ci. Also fixes some trivial markdown lint issues.
- [N/A] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [N/A] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [N/A] New unit tests have been added covering the changes
- [N/A] Documentation has been updated accordingly.
Submitting the PR does not require you to check all items, but …
> minor PR template updates

- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
If just the font fill and font size are set the CSS parser returns a null Font object and no labels are drawn.
See https://osgeo-org.atlassian.net/browse/GEOS-9808 for more detail
> [GEOT-6752] CSS Styles don't change the size of a label unless `font-style` is set

- pom.xml
Batik has resolved CVE-2019-17566 (a SSRF vulnerability)
backports #3267 to 24.x, resolves resolves [GEOT-6765](https://osgeo-org.atlassian.net/browse/GEOT-6765) for 24.2
> [24.x backport][GEOT-6765] Update Batik libraries from 1.10 to 1.13

- pom.xml
Batik has resolved CVE-2019-17566 (a SSRF vulnerability)
backports #3267 to 23.x, resolves resolves [GEOT-6765](https://osgeo-org.atlassian.net/browse/GEOT-6765) for 23.5
> [23.x backport][GEOT-6765] Update Batik libraries from 1.10 to 1.13

- pom.xml
The sqlite-jdbc team fixed a number of vulnerabilities in the native code parts (see https://github.com/xerial/sqlite-jdbc/issues/501) in version 3.32.3.
Also support for the new Apple Silicon (M1) was added in 3.32.3.3 as wel as some Arm Cortex improvements
see also: https://github.com/xerial/sqlite-jdbc/blob/master/README.md#news
backports #3268 to 24.x, resolves resolves [GEOT-6766](https://osgeo-org.atlassian.net/browse/GEOT-6766) for 24.2
> [24.x backport][GEOT-6766] Update sqlite-jdbc from 3.31.1 to 3.34.0

- pom.xml
The sqlite-jdbc team fixed a number of vulnerabilities in the native code parts (see https://github.com/xerial/sqlite-jdbc/issues/501) in version 3.32.3.
Also support for the new Apple Silicon (M1) was added in 3.32.3.3 as wel as some Arm Cortex improvements
see also: https://github.com/xerial/sqlite-jdbc/blob/master/README.md#news
backports #3268 to 23.x, resolves resolves [GEOT-6766](https://osgeo-org.atlassian.net/browse/GEOT-6766) for 23.5
> [23.x backport][GEOT-6766] Update sqlite-jdbc from 3.30.1 to 3.34.0

- modules/unsupported/mbtiles/pom.xml
- pom.xml
In the Jackson project the following CVE-2020-25649 was fixed, as well as various other bugfixes.
backports #3266 to resolve [GEOT-6767](https://osgeo-org.atlassian.net/browse/GEOT-6767) for 24.2
> [24.x backport][GEOT-6767] Update Jackson 2 libraries from 2.10.1 to 2.10.5 / 2.10.5.1

- modules/unsupported/mbtiles/pom.xml
- pom.xml
In the Jackson project the following CVE-2020-25649 was fixed, as well as various other bugfixes.
backports #3266 to resolve [GEOT-6767](https://osgeo-org.atlassian.net/browse/GEOT-6767) for 23.5
> [23.x backport][GEOT-6767] Update Jackson 2 libraries from 2.10.1 to 2.10.5 / 2.10.5.1

- modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/ReadResolutionCalculator.java
- modules/library/coverage/src/test/java/org/geotools/coverage/grid/io/ReadResolutionCalculatorTest.java
Support the max oversampling factor on read resolution computation.
> [GEOT-6789]:limit read resolution on oversampling factor

- docs/developer/procedures/stable.rst
See https://osgeo-org.atlassian.net/browse/GEOT-6791
This PR documents the inclusion of major dependency upgrades in the definition of an API change for the purposes of backporting, to avoid breaking downstream projects when upgrading the minor version of a stable GeoTools branch.
I've also documented that additive only API changes may be documented after one month on master, since as far as I'm aware, this is implicitly permitted, but not documented anywhere in GeoTools (only in GeoServer), and made a few minor improvements to the rest of the "stable branch" documentation.
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to …
> [GEOT-6791] Include dependencies in definition of API change when backporting

- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/shp/ZMHandlersTest.java
This is small change that should fix annoing exceptions which show up occasionally while running tests on shapefile plugin. The PR does nothing more than dispose the shapefile store after test.
Typical exception looks like the following after running `mvn -pl modules/plugin/shapefile clean test`:
```
[INFO] Running org.geotools.data.shapefile.shp.ZMHandlersTest
java.lang.IllegalArgumentException: Expected requestor org.geotools.data.shapefile.dbf.DbaseFileReader@cb4df892 to have locked the url but it does not hold the lock for the URL
```
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do so by completing the following items. Feel free to …
> Fix accidental exceptions on shapefile locking while running tests

- modules/extension/app-schema/app-schema/pom.xml
- modules/extension/complex/pom.xml
- modules/extension/complex/src/main/java/org/geotools/data/complex/util/EmfComplexFeatureReader.java
- modules/unsupported/wfs-ng/pom.xml
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlComplexFeatureParser.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlFeatureParser.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlSimpleFeatureParser.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/v1_1/XXEProtectionTest.java
- modules/unsupported/wps/pom.xml
- modules/unsupported/wps/src/main/java/org/geotools/data/wps/response/ExecuteProcessResponse.java
- pom.xml
Remove dependency on xpp3 and use the standard StAX API instead.
[xpp3](https://mvnrepository.com/artifact/xpp3/xpp3) is an XML pull parser. Last released version is 14 years old. The
JRE comes with a standard StAX pull parser since Java 1.6.
Submitting the PR does not require you to check all items, but by the time it gets merged, they …
> [GEOT-6829] Remove dependency on xpp3, use standard StAX API

- modules/library/opengis/src/main/java/org/opengis/feature/simple/SimpleFeature.java
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>
This PR reverts the change to `SimpleFeature.setAttributes` to accept varargs. This is to prevent subtle errors when calling the method from scala, where instead of expanding an array via varargs, a length 1 array is passed with a nested array inside it. …
> [GEOT-6840] Revert change to varargs in SimpleFeature

- modules/extension/xsd/xsd-sld/src/main/java/org/geotools/sld/bindings/SLDRasterSymbolizerBinding.java
- modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDMockData.java
- modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDRasterSymbolizerBindingTest.java
- modules/library/xml/src/main/java/org/geotools/xml/styling/SLDParser.java
- modules/library/xml/src/test/java/org/geotools/xml/styling/SLDParserTest.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6848
* [GEOT-6848] Vendor options in RasterSymbolizer are not parsed
* review feedback applied …
> [24.x backport][GEOT-6848] Vendor options in RasterSymbolizer are not parsed (#3404)

- modules/extension/xsd/xsd-sld/src/main/java/org/geotools/sld/bindings/SLDRasterSymbolizerBinding.java
- modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDMockData.java
- modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDRasterSymbolizerBindingTest.java
- modules/library/xml/src/main/java/org/geotools/xml/styling/SLDParser.java
- modules/library/xml/src/test/java/org/geotools/xml/styling/SLDParserTest.java
jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6848
* [GEOT-6848] Vendor options in RasterSymbolizer are not parsed
* review feedback applied …
> [25.x backport][GEOT-6848] Vendor options in RasterSymbolizer are not parsed (#3404)

- modules/library/render/src/main/java/org/geotools/renderer/lite/ZGroupLayer.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/ZOrderTest.java
…over 1000 features using VendorOption sortBy
This is fix of Jira ticket opened in Geoserver Jira https://osgeo-org.atlassian.net/browse/GEOS-9748
Fix rendering error in case the rendered dataset size is over 1000 features and uses SLD xml element sld:VendorOption sortBy.
Unit tests extended to test with both MarkFeatureIterator implementations (memory and disk) by setting max memory sort limit to default value and low to use DiskMarkFeatureIterator during rendering ZOrder testing.
For …
> [GEOT-6880] Rendering process fails if vendor option sortByGroup is used

- modules/library/main/src/main/java/org/geotools/filter/visitor/CapabilitiesFilterSplitter.java
- modules/library/main/src/test/java/org/geotools/filter/visitor/CapabilitiesFilterSplitterFunctionTest.java
Fix for an `IndexOutOfBoundsException` thrown at
`CapabilitiesFilterSplitter.visit(Function,...)` when the post-stack
size is bigger than the number of function arguments.
---
> [GEOT-6717] IndexOutOfBoundsException at CapabilitiesFilterSplitter.visit(Function,...)

- modules/library/main/src/main/java/org/geotools/filter/visitor/CapabilitiesFilterSplitter.java
- modules/library/main/src/test/java/org/geotools/filter/visitor/CapabilitiesFilterSplitterFunctionTest.java
Backport of #3444 to `25.x`.
Fix for an `IndexOutOfBoundsException` thrown at
`CapabilitiesFilterSplitter.visit(Function,...)` when the post-stack
size is bigger than the number of function arguments.
---
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not …
> [25.x backport][GEOT-6717] IndexOutOfBoundsException at CapabilitiesFilterSplitter.visit(Function,...)

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java
- modules/library/main/src/main/java/org/geotools/feature/visitor/UniqueCountVisitor.java
- modules/library/main/src/test/java/org/geotools/feature/visitor/UniqueCountVisitorTest.java
early backport request [here](https://sourceforge.net/p/geotools/mailman/message/37271370/)
jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6874?searchSessionId=5bc8449d-6233-45c8-adb6-83320063fa83&searchObjectId=53789&searchContainerId=10001&searchContentType=issue
Submitting the PR does not require you to check all items, but by …
> [25.x backport] [GEOT-6874] Add support for count distinct aggregations in gt-jdbc

- modules/library/render/src/main/java/org/geotools/renderer/lite/ZGroupLayer.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/ZOrderTest.java
backport of bugreport
Fix rendering error in case the rendered dataset size is over 1000 features and uses SLD xml element sld:VendorOption sortBy.
Unit tests extended to test with both MarkFeatureIterator implementations (memory and disk) by setting max memory sort limit to default value and low to use DiskMarkFeatureIterator during rendering ZOrder testing.
The following are required only for core and extension modules (they are welcomed, but not required, for …
> [GEOT-6880] Rendering process fails if vendor option sortByGroup is used (25.x)

- .github/workflows/mysql_online.yml
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCTemporalFilterOnlineTest.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLTemporalFilterOnlineTest.java
- pom.xml
override `JDBCTemporalFilterOnlineTest#assertDatesMatch(...)` so we can use LocalDateTime instead of Date for the comparisons. Since MySQL jdbc driver returns LocalDateTime as of 8.0.23.
resolves [GEOT-6821](https://osgeo-org.atlassian.net/browse/GEOT-6821)
Submitting the PR does not require you to check all items, but by the time it gets …
> [GEOT-6821] Update JDBC drivers: MySQL (to 8.0.24)

- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/RasterAsPointCollectionProcess.java
- modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/RasterAsPointCollectionProcessTest.java
[![GEOT-6885](https://badgen.net/badge/JIRA/GEOT-6885/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6885) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR changes RasterAsPointCollectionProcess to use the WGS84 Y coordinate to determine the hemisphere rather than the coordinate of the coverage CRS north axis.
https://osgeo-org.atlassian.net/browse/GEOT-6885
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do so by completing …
> [GEOT-6885] RasterAsPointCollectionProcess hemisphere error with some projections

- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/RasterAsPointCollectionProcess.java
- modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/RasterAsPointCollectionProcessTest.java
[![GEOT-6885](https://badgen.net/badge/JIRA/GEOT-6885/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6885) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
24.x backport for https://github.com/geotools/geotools/pull/3498 …
> [24.x][GEOT-6885] RasterAsPointCollectionProcess hemisphere error with some projections

- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/RasterAsPointCollectionProcess.java
- modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/RasterAsPointCollectionProcessTest.java
[![GEOT-6885](https://badgen.net/badge/JIRA/GEOT-6885/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6885) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
25.x backport for https://github.com/geotools/geotools/pull/3498
- X] Confirm you have read the …
> [25.x][GEOT-6885] RasterAsPointCollectionProcess hemisphere error with some projections

- modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffWriter.java
- modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffWriterTest.java
- pom.xml
[![GEOT-6891](https://badgen.net/badge/JIRA/GEOT-6891/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6891) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
https://osgeo-org.atlassian.net/browse/GEOT-6891
The following are required only for core and …
> [GEOT-6891]: GeoTiffWriter writing on ImageOutputStream wrapped within an OutputStream

- modules/unsupported/gml-geometry-streaming/pom.xml
- modules/unsupported/gml-geometry-streaming/src/main/java/org/geotools/gml/stream/GML.java
- modules/unsupported/gml-geometry-streaming/src/main/java/org/geotools/gml/stream/XmlStreamGeometryReader.java
- modules/unsupported/gml-geometry-streaming/src/test/java/org/geotools/gml/stream/XmlStreamGeometryReaderParameterizedTest.java
- modules/unsupported/gml-geometry-streaming/src/test/resources/org/geotools/gml/stream/curve.gml
- modules/unsupported/gml-geometry-streaming/src/test/resources/org/geotools/gml/stream/multisurface_curve.gml
- modules/unsupported/gml-geometry-streaming/src/test/resources/org/geotools/gml/stream/multisurface_curve2.gml
[![GEOT-6893](https://badgen.net/badge/JIRA/GEOT-6893/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6893) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Adds support for a `gml:Curve` with `gml:LineStringSegment` and `gml:Arc` segments (3 control points) to (unsupported) **gt-gml-geometry-streaming**. Supported in a top-level geometry element, in a `gml:MultiCurve` or in the `gml:exterior` and `gml:interior` of a `gml:MultiSurface` or `gml:Polygon`.
Also added a flag to the parametrized test whether the WKT of the parsed geometry should be compared with the WKT from a Geometry …
> [GEOT-6893] Add support for gml:Curve with gml:Arc segments to gml-geometry-streaming

- modules/unsupported/gml-geometry-streaming/src/main/java/org/geotools/gml/stream/GML.java
- modules/unsupported/gml-geometry-streaming/src/main/java/org/geotools/gml/stream/XmlStreamGeometryReader.java
- modules/unsupported/gml-geometry-streaming/src/test/java/org/geotools/gml/stream/XmlStreamGeometryReaderParameterizedTest.java
- modules/unsupported/gml-geometry-streaming/src/test/java/org/geotools/gml/stream/XmlStreamGeometryReaderTest.java
[![GEOT-6896](https://badgen.net/badge/JIRA/GEOT-6896/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6896) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Supports elements in the `http://www.opengis.net/gml/3.2` namespace without any other changes to the parsing of the `http://www.opengis.net/gml` namespace. Based on OGC document "[OGC 07-061: Revision Notes for OpenGIS® Implementation Specification: Geographic information - Geography Markup Language Version 3.2.1](https://portal.opengeospatial.org/files/?artifact_id=26765)" I conclude that is the only difference between these …
> [GEOT-6896] Add support for GML 3.2 namespace to gml-geometry-streaming

- docs/user/welcome/upgrade.rst
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStoreFactory.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileWithCpgTest.java
[![GEOT-2972](https://badgen.net/badge/JIRA/GEOT-2972/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-2972) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This is enhancement of #3405 with regards of #3497. It adds the following:
- introduce system property that allows turn on/off charset autodetection from CPG file;
- the property set to "true" by default, turning autodetection on. Setting it to "false" brings old behavior back.
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small …
> [GEOT-2972] Character set from CPG files - add "enable feature" switch

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTile.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTileService.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/ESRIWMTSServerOnlineTest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/OrdnanceSurveyOnlineTest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/WMTSTransparentTileOnlineTest.java
[![GEOT-6894](https://badgen.net/badge/JIRA/GEOT-6894/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6894) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
When a WMTS service are using its own special query parameters within the url, for instance as authentication. They were omitted when asking for getFinalURL. This had the consequence that a GetTile request failed with a 403.
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do so …
> [GEOT-6894] WMTS fails when initial url contains query parameters

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapeFileIndexer.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileIndexerBoundsHelper.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/index/quadtree/QuadTree.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapeFileIndexerStressTest.java
[![GEOT-6900](https://badgen.net/badge/JIRA/GEOT-6900/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6900) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Use a strategy object (`BoundsReader`) to assist `ShapeFileIndexer` in speeding up the 
`QuadTree` optimization  phase, providing quick access to each shapefile
record envelope, potentially avoiding an immense amount of random disk I/O calls through
`ShapefileReader`, as the quad tree internal nodes get split/shrank.
Since the `QuadTree` leaf nodes hold only the shapefile record ids, and not their
bounds, the tree layout …
> [GEOT-6900] Shapefile quadtree build performance improvements

- modules/plugin/shapefile/pom.xml
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/IndexManager.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapeFileIndexer.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/IndexManagerTest.java
[![GEOT-6899](https://badgen.net/badge/JIRA/GEOT-6899/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6899) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Shapefile quadtree index building is triggered on each calling thread,
eventually exhausting available CPU/Memory resources.
Acquire a write lock on the QIX file before building the quad-tree, and
check for stale-ness right after acquiring the lock, to avoid building
the same quad-tree concurrently and/or unnecessarily.
Before:
After:
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus …
> [GEOT-6899] Resource (CPU/Heap) starvation building shapefile spatial index

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTile.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTileService.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/ESRIWMTSServerOnlineTest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/OrdnanceSurveyOnlineTest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/WMTSTransparentTileOnlineTest.java
[![GEOT-6894](https://badgen.net/badge/JIRA/GEOT-6894/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6894) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backporting to 25.x
* [GEOT-6894] WMTS fails when initial url contains query parameters
* Fixed the failing tests
* Fixed the formatting
* Using variable separator instead of skipFirst
* Fixed formatting
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do so by completing the …
> [Backport 25.x] [GEOT-6894] WMTS fails when initial url contains query parameters 

- modules/library/render/src/test/java/org/geotools/renderer/lite/gridcoverage2d/RasterSymbolizerTest.java
[![GEOT-6909](https://badgen.net/badge/JIRA/GEOT-6909/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6909) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Break `RasterSymbolizerTest:contrastEnhancementMethods()` into individual test methods
Break down the 970-lines long method
`RasterSymbolizerTest:contrastEnhancementMethods()` into individual test
cases:
* contrastEnhancement_Histogram_SLD()
* contrastEnhancement_Histogram_StyleBuilder()
* contrastEnhancement_Hyperbolic_SLD()
* contrastEnhancement_Hyperbolic_StyleBuilder()
* contrastEnhancement_Logarithmic_SLD()
* …
> [GEOT-6909] 500+ lines method: RasterSymbolizerTest:contrastEnhancementMethods()

- modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffWriter.java
- modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffWriterTest.java
- pom.xml
[![GEOT-6891](https://badgen.net/badge/JIRA/GEOT-6891/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6891) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backporting [GEOT-6891] to 25.x
> [Backport-25.x][GEOT-6891]: GeoTiffWriter writing on ImageOutputStream wrapped within an OutputStream

- modules/library/referencing/src/main/java/org/geotools/referencing/CRS.java
- modules/library/referencing/src/main/java/org/geotools/referencing/factory/OrderedAxisAuthorityFactory.java
- modules/plugin/epsg-hsql/src/test/java/org/geotools/referencing/HSQLCRSTest.java
[![GEOT-6916](https://badgen.net/badge/JIRA/GEOT-6916/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6916) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket.
The following are required only for core and extension modules (they are welcomed, but …
> [GEOT-6916] "WGS 84 / UPS South (N,E)" is rendered with flipped axis

- docs/user/library/referencing/crs.rst
- docs/user/library/referencing/transform.rst
- modules/library/referencing/src/main/java/org/geotools/referencing/CRS.java
- modules/plugin/epsg-hsql/src/test/java/org/geotools/referencing/factory/epsg/hsql/OperationFactoryTest.java
[![GEOT-6920](https://badgen.net/badge/JIRA/GEOT-6920/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6920) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Add two new method to `CRS` to allow users to find possible transformations on a coordinate transformation and to request a transform using a specific one.
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if …
> [GEOT-6920] Make it easier to specify which transformation to use when selecting a coordinate system transform

- docs/src/main/java/org/geotools/tile/TileViewer.java
- modules/extension/tile-client/src/main/java/org/geotools/tile/TileFactory.java
- modules/extension/tile-client/src/main/java/org/geotools/tile/impl/bing/BingTileFactory.java
- modules/extension/tile-client/src/main/java/org/geotools/tile/impl/osm/OSMTileFactory.java
- modules/extension/tile-client/src/test/java/org/geotools/tile/impl/bing/BingTileFactoryTest.java
- modules/extension/tile-client/src/test/java/org/geotools/tile/impl/osm/OSMTileFactoryTest.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTile.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTileFactory.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/client/WMTSTileFactory4326Test.java
[![GEOT-6915](https://badgen.net/badge/JIRA/GEOT-6915/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6915) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
TileFactory should have a create method so that each sub factory could call it's own constructor. Without having to duplicate all the methods. This will also make the foundation for a new approach for caching in TileService.
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do so …
> [GEOT-6915] Add method create in TileFactory

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/PullParserFeatureReader.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/v2_0/StrictWFS_2_0_Strategy.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/WFSTestData.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/AbstractWfsDataStoreOnlineTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/KartverketStedsnavnDataStoreOnlineTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/WFSOnlineTestSupport.java
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/KartverketNo/DescribeFeatureType_sted.xsd
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/KartverketNo/GetCapabilities.xml
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/KartverketNo/GetFeature_sted.xml
[![GEOT-6906](https://badgen.net/badge/JIRA/GEOT-6906/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6906) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
… defined globally
As explained in JIRA StrictWFS_2_0_Strategy.getServerSupportedOutputFormats doesn't look for Parameter-elements within the element OperationsMetadata.
The rest of the PR is concerned with adopting AbstractWfsDataStoreOnelineTest for the WFS server with this capabilities problem. The main issues are that CRS should be COMPLIANT, and that a GetFeature request returning everything is massive.
Reviewing is a …
> [GEOT-6906] WFS DescribeFeatureType doesn't account for outputFormats defined globally

- modules/library/metadata/src/main/java/org/geotools/util/GrowableInternationalString.java
- modules/library/metadata/src/test/java/org/geotools/util/GrowableInternationalStringTest.java
[![GEOT-6923](https://badgen.net/badge/JIRA/GEOT-6923/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6923) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This pr:
-  changes the Map<Locale,String> implementation of GrowableInternationalString from HashMap to LinkedHashMap
- create a constructor accepting a generic InternationalString as parameter.
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as …
> [GEOT-6923] Improvement to GrowableInternationalString

- modules/library/jdbc/src/main/java/org/geotools/jdbc/MetadataTablePrimaryKeyFinder.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCPrimaryKeyFinderViewOnlineTest.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCPrimaryKeyFinderViewTestSetup.java
- modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2PrimaryKeyFinderViewTest.java
- modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2PrimaryKeyFinderViewTestSetup.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisPrimaryKeyFinderViewOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisPrimaryKeyFinderViewTestSetup.java
[![GEOT-6921](https://badgen.net/badge/JIRA/GEOT-6921/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6921) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The previous code was blindly querying the GT_PK_METADATA table, thus resulting in error logs on the database side if the table did not exist. The new code looks at database metadata to check if the table GT_PK_METADATA exists.
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do …
> [GEOT-6921] GeoTools primary key finder always query the table gt_pk_metadata even if it doesn't exists

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
[![GEOT-6937](https://badgen.net/badge/JIRA/GEOT-6937/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6937) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This pr fixes a bug in JdbcMultipleValue in AppSchema avoiding that primary key column names are encoded two times when building select query.
Test coverage provided in this pr https://github.com/geoserver/geoserver/pull/5143.GS App-schema postgis integration test will not fail with the linked pr modifications.
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to …
> [GEOT-6937] AppSchema JdbcMultipleValue will fill wrong values if targetColumn is a PK

- modules/library/metadata/src/main/java/org/geotools/util/GrowableInternationalString.java
- modules/library/metadata/src/test/java/org/geotools/util/GrowableInternationalStringTest.java
[![GEOT-6947](https://badgen.net/badge/JIRA/GEOT-6947/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6947) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This pull request adds the possibility to have a null value to copy constructor.
> [GEOT-6947] Copy Constructor not adding null Locale

- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/CropCoverage.java
- modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/CropCoverageTest.java
[![GEOT-6949](https://badgen.net/badge/JIRA/GEOT-6949/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6949) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket for description
> [GEOT-6949] CropCoverage should retain the ROI information

- modules/library/http/src/main/java/org/geotools/http/SimpleHttpClient.java
- modules/library/http/src/test/java/org/geotools/http/HTTPClientFinderTest.java
[![GEOT-6959](https://badgen.net/badge/JIRA/GEOT-6959/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6959) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
* [GEOT-6959] SimpleHttpClient does support proxy
Backport to 25.x
> [Backport 25.x] [GEOT-6959] SimpleHttpClient does support proxy (#3606)

- modules/library/xml/src/main/java/org/geotools/gml/producer/CoordinateFormatter.java
- modules/library/xml/src/test/java/org/geotools/gml/producer/CoordinateFormatterTest.java
[![GEOT-6960](https://badgen.net/badge/JIRA/GEOT-6960/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6960) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
I submitted a patch earlier, which was [deficient](https://github.com/geotools/geotools/pull/3607#discussion_r692428442), I believe, because it always rounded towards positive infinity.  This version rounds down below 0, and up above 0.  I added a unit test to demonstrate the updated behaviour of the truncate(double x) method.
cc @jodygarnett 
> [GEOT-6960] Amend condition in which force decimals will be applied

- pom.xml
Upgrading to latest imageio-ext-1.3.10 which includes support for TIFF ZSTD compressed 
> Upgrading to imageio-ext-1.3.10 supporting TIFF ZSTD decompression

- pom.xml
[backport to 25.x]Updating to imageio-ext 1.3.10 for ZSTD support
> [Backport 25.x]Updating to imageio-ext 1.3.10 for ZSTD decompression support

- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerFilterToSQL.java
- modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerBooleanOnlineTest.java
[![GEOT-6410](https://badgen.net/badge/JIRA/GEOT-6410/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6410) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
backports #3594 to 25.x
* [GEOT-6410] Conversion from boolean true/false in geoserver to SQL Server bit 0/1, is broken
* [GEOT-6410] add testcase for boolean conversion on insert
Co-authored-by: Mark Prins <1165786+mprins@users.noreply.github.com>
> [25.x backport][GEOT-6410] Conversion from boolean true/false in geoserver to SQL Server bit 0/1, is broken

- modules/plugin/mongodb/pom.xml
[![CVE-2021](https://badgen.net/badge/JIRA/CVE-2021/0052CC)](https://osgeo-org.atlassian.net/browse/CVE-2021) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The MongoDB project resolved CVE-2021-20328 (a MITM vulnerability in the database driver)
> [GEOT-6982] Update Mongo DB driver to 4.0.6 to mitigate CVE-2021-20328

- build/build.xml
- release/README.md
- release/pom.xml
jars incuded explicitly as a transitive dependency from gt-docs were incorrectly being excluded from binary downoad
No documentation changes are required.
Signed-off-by: Jody Garnett <jody.garnett@gmail.com>
> Include commons-io and other required dependences in binary release bundle

- docs/user/welcome/upgrade.rst
use a `parsed-literal` instead of a `code-block` because substitution of the `|release|` token does not work in a `code-block` and use a whitespace escape to make the substitution work.
Before:
After:
unfortunately this looses the XML formatting, but it seems it is impossible to have both a formatted code block _and_ substitution (within that block).
see eg. https://stackoverflow.com/questions/8821511/substitutions-inside-sphinx-code-blocks-arent-replaced or https://stackoverflow.com/questions/27392934/sphinx-variable-substitution-in-code-blocks
> [docs] fix version token substitution in upgrade doc

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileSizeException.java
The passes in exception message was accidentally discarded. Discovered thanks to https://github.com/google/error-prone/commit/691836e92aa01837865e0d4e0e7ecad0f4666424
> Fix a bug in ShapefileSizeException

- modules/library/main/src/main/java/org/geotools/feature/visitor/MaxVisitor.java
- modules/library/main/src/main/java/org/geotools/feature/visitor/MinVisitor.java
- modules/library/main/src/test/java/org/geotools/feature/visitor/MaxVisitorTest.java
- modules/library/main/src/test/java/org/geotools/feature/visitor/MinVisitorTest.java
[![GEOT-6998](https://badgen.net/badge/JIRA/GEOT-6998/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6998) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
An IllegalStateException is thrown instead of NullPointerException. Somewhat unclear how the null came into the variable in the first place. Maybe this will clear things up.
> [GEOT-6998] MinVisitor and MaxVisitor avoid NullPointerException

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WebMapTileServer.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTile.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTileService.java
[![GEOT-7013](https://badgen.net/badge/JIRA/GEOT-7013/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7013) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Removing some functions that were deprecated in 26.
> [GEOT-7013] Remove deprecated functions from gt-wmts

- docs/src/main/java/org/geotools/wfs/ReadWFSKommuner.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlComplexFeatureParser.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/parsers/XmlComplexFeatureParserTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/KartverketStedsnavnDataStoreOnlineTest.java
[![GEOT-7001](https://badgen.net/badge/JIRA/GEOT-7001/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7001) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
When accessing a WFS with a complex structure a single feature shouldn't have properties with names other than those reported by a call to getSchema().
That is the basic of my added test in KartverketStedsnavnDataStoreOnlineTest.
Unfortunately a lot of tests were based on the wrong assumption about how to name complex attributes.
> [GEOT-7001] XmlComplexFeatureParser gives wrong name for ComplexAttribute

- docs/src/main/java/org/geotools/wfs/ReadWFSKommuner.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlComplexFeatureParser.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/parsers/XmlComplexFeatureParserTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/KartverketStedsnavnDataStoreOnlineTest.java
[![GEOT-7001](https://badgen.net/badge/JIRA/GEOT-7001/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7001) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
(#3654)
* [GEOT-7001] XmlComplexFeatureParser gives wrong name for ComplexAttribute
* Example code in docs
> [Backport 26] [GEOT-7001] XmlComplexFeatureParser gives wrong name for ComplexAttribute

- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSourceTest.java
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/KartverketNo/cache/no/geonorge/wfs/skwms1/wfs.administrative_enheter.161e2708f54bc4bf058256a8ea569fa6.xsd
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/KartverketNo/cache/no/geonorge/wfs/skwms1/wfs.stedsnavn.196d7b04d92a7fbfdcfd8bb26d9b2969.xsd
[![GEOT-7001](https://badgen.net/badge/JIRA/GEOT-7001/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7001) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fix for the broken build.
One test had to be ignored for now.
> [GEOT-7001] - ComplexFeatures - failed online test

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSource.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSContentComplexFeatureCollection.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlComplexFeatureParser.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlFeatureParser.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSourceTest.java
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/KartverketNo/cache/no/geonorge/wfs/skwms1/wfs.administrative_enheter.161e2708f54bc4bf058256a8ea569fa6.xsd
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/KartverketNo/cache/no/geonorge/wfs/skwms1/wfs.stedsnavn.196d7b04d92a7fbfdcfd8bb26d9b2969.xsd
This is a back port of some earlier work on WFS Complex features. It is this PR that caused the resent troubles with server errors causing trouble in the build.
I've also included the commits that solved those troubles.
> Backport 26 [GEOT 6961] - WFSContentComplexFeatureSource.getFeatures must use correct namespace

- modules/library/main/src/main/java/org/geotools/renderer/crs/OrthographicProjectionHandlerFactory.java
- modules/library/main/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java
- modules/library/main/src/main/resources/META-INF/services/org.geotools.renderer.crs.ProjectionHandlerFactory
- modules/library/main/src/test/java/org/geotools/renderer/crs/OrthographicProjectionHandlerFactoryTest.java
[![GEOT-7020](https://badgen.net/badge/JIRA/GEOT-7020/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7020) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport from main, see also https://github.com/geotools/geotools/pull/3670
> [GEOT-7020] Add ProjectionHandler for orthographic (25.x)

- modules/library/main/src/main/java/org/geotools/renderer/crs/OrthographicProjectionHandlerFactory.java
- modules/library/main/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java
- modules/library/main/src/main/resources/META-INF/services/org.geotools.renderer.crs.ProjectionHandlerFactory
- modules/library/main/src/test/java/org/geotools/renderer/crs/OrthographicProjectionHandlerFactoryTest.java
[![GEOT-7020](https://badgen.net/badge/JIRA/GEOT-7020/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7020) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport from main, see also https://github.com/geotools/geotools/pull/3670
> [GEOT-7020] Add ProjectionHandler for orthographic (26.x)

- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/wps/GeoPackageProcessRequest.java
- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/wps/xml/GPKG.java
- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/wps/xml/GPKGConfiguration.java
- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/wps/xml/Geopkgtype_tilesBinding.java
- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/wps/xml/ParameterBinding.java
- modules/plugin/geopkg/src/main/resources/org/geotools/geopkg/wps/xml/gpkg.xsd
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/wps/xml/ParameterBindingTest.java
[![GEOT-7024](https://badgen.net/badge/JIRA/GEOT-7024/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7024) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7024] Extend GeoPackage process XSD definition to support arbitrary request parameters for tile layers

- modules/library/referencing/src/main/java/org/geotools/referencing/factory/DeferredAuthorityFactory.java
- modules/library/referencing/src/main/java/org/geotools/referencing/factory/epsg/ThreadedEpsgFactory.java
- modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffCRSFactoryDeadlockTest.java
[![GEOT-7022](https://badgen.net/badge/JIRA/GEOT-7022/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7022) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7022]: Referencing factories deadlock prevention

- pom.xml
This was an oversight when introducing nexus, wagon is no longer needed (was used to transfer files to previous webdav maven repository).
> wagon extension no longer needed as we use repo.osgeo.org

- modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/GeoHashGridProcess.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridProcessTest.java
[![GEOT-7031](https://badgen.net/badge/JIRA/GEOT-7031/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7031) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket
> [GEOT-7031] Elasticsearch geohash process can fail with NPE in invertQuery

- modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java
- modules/library/coverage/src/test/java/org/geotools/image/ImageWorkerTest.java
A lot of my data is raster data with alpha-channel. About 2% fail when serving them through the tile server at some resolutions.  I can't produce a small, self-contained example, unfortunately. But I have tracked it down and it seems the alpha-channel is rendered separately from the rest of the image and is "allergic" to 0-size tile-width. This is the way I fixed it in 21.1 (verified in my environment). If necessary, I can give you the stack trace from the logs, the AWT class doesn't like 0.
I wasn't able to create a Jira issue, because the Attlassian license limit was reached, or so it said. The issue was discussed on the mailing list a few weeks ago, Jody Garnett was involved. If you need a signed contribution agreement, I can forward that, but I consider …
> Fix for ImageWorker

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCDataStoreOnlineTest.java
- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDialect.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLDataStoreOnlineTest.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/jndi/MySQLDataStoreOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostgisDataStoreOnlineTest.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDialect.java
- modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerDataStoreOnlineTest.java
[![GEOT-7035](https://badgen.net/badge/JIRA/GEOT-7035/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7035) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket
> [GEOT-7035] Add ability to provide the desired database type name when creating a schema in JDBC stores

- pom.xml
[![GEOT-7042](https://badgen.net/badge/JIRA/GEOT-7042/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7042) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Dependency upgrade from 2.6.0 to 2.6.0.1.
See http://www.jdom.org/news/index.html for the list of changes.
The key users of this dependency are app-schema and netcdf.
> [GEOT-7042] Upgrade jdom dependency

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WMTSHelper.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WMTSSpecification.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WebMapTileServer.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTileService.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/map/WMTSCoverageReader.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/GetTileRequest.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/response/GetTileResponse.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/map/WMTSCoverageReaderTest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/LantmaterietWMTSServerOnlineTest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/RestWMTSOnlineTest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/WebMapTileServerOnlineTest.java
- modules/library/http/src/test/java/org/geotools/http/MockHttpClient.java
[![GEOT-7028](https://badgen.net/badge/JIRA/GEOT-7028/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7028) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
I've added a function issueRequestForTileResponse to org.geotools.ows.wmts.WebMapTileServer. The name isn't in accordance with the usual OWS server instances, but that's because of the original issueRequest that returns a Set of Tile's. This is unfortunate, but before we can deprecate and change the return, we must find an alternative solution. This signature is also used within GeoServer.
In addition I've changed …
> [GEOT-7028] - GetTile request's in WMTS represents one single tile, not a set

- docs/developer/conf.py
- docs/user/conf.py
Noticed user guide was masking common external link settings. This is a documentation, non functional change helping sphinx-build environment to be easier to maintain.
> avoid masking common.py settings

- build/build.xml
- build/release/build_release.sh
- docs/developer/procedures/release.rst
This change must be backported (as it contains modification to build_release.sh script).
> Change ant target to release for build_release.sh use (previously rename)

- docs/build.xml
- docs/common.py
- docs/index/index.rst
- docs/web/about.rst
- docs/web/getinvolved.rst
Signed-off-by: Jody Garnett <jody.garnett@gmail.com>
Fix some build warnings and double check index and website page links; some minor updates (such as no longer mentioning "patches" as a contribution method).  I did update the about page to list upcoming latest / stable / maintenance branches. Ideally I would like to pull this from the environment somehow.
This is a non functional documentation change so no test case has been provided.
> Double check links on website and index page

- docs/user/extension/ysld.rst
- modules/extension/ysld/src/main/java/org/geotools/ysld/encode/RuleEncoder.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/parse/RuleParser.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeCookbookTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseCookbookTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
- modules/extension/ysld/src/test/resources/org/geotools/ysld/sld/point/rule-option.sld
[![GEOT-7030](https://badgen.net/badge/JIRA/GEOT-7030/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7030) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport of https://github.com/geotools/geotools/pull/3694
> [26.x backport][GEOT-7030] Missing YSLD support for rule vendor options

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Crop.java
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/CropTest.java
[![GEOT-7049](https://badgen.net/badge/JIRA/GEOT-7049/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7049) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket.
> [GEOT-7049] Crop operation should preserve the ROI among the coverage properties

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Crop.java
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/CropTest.java
[![GEOT-7049](https://badgen.net/badge/JIRA/GEOT-7049/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7049) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7049] Crop operation should preserve the ROI among the coverage properties (25.x)

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Crop.java
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/CropTest.java
[![GEOT-7049](https://badgen.net/badge/JIRA/GEOT-7049/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7049) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7049] Crop operation should preserve the ROI among the coverage properties (26.x)

- pom.xml
[![GEOT-7048](https://badgen.net/badge/JIRA/GEOT-7048/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7048) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Reverts geotools/geotools#3728
Due to WCS netcdf-out build failures. See details in relevant GS Revert PR:
https://github.com/geoserver/geoserver/pull/5584
> Revert "[GEOT-7048] Upgrade NetCDF to 4.6.19"

- modules/extension/transform/src/main/java/org/geotools/data/transform/TransformFeatureCollection.java
- modules/extension/transform/src/test/java/org/geotools/data/transform/TransformFeatureCollectionTest.java
[![GEOT-7053](https://badgen.net/badge/JIRA/GEOT-7053/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7053) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket.
> [GEOT-7053] TransformFeatureCollection visitor delegation can result in infinite recursion

- docs/developer/procedures/release.rst
Update developer guide procedure to use github release page to publish release notes publicly (as generated from Jira which is no longer public).
> github release notes

- docs/build.xml
- docs/user/library/coverage/netCDF.rst
- docs/user/welcome/upgrade.rst
- docs/web/about.rst
Fix extlink warnings for geotools user docs, this should be backported.
> Fix user docs and website extlink errors caused by upgrade to sphinx-build

- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-7011](https://badgen.net/badge/JIRA/GEOT-7011/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7011) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This is a port of a fix proposed here https://github.com/geoserver/geoserver/pull/5558 for the geopackage output format. 
Feedback from @groldan indicated the fix could be better applied directly in the GeoPackage API.
> [GEOT-7011] GeoPackage.add(FeatureEntry, SimpleFeatureCollection) forced to XY order

- docs/user/library/data/geopackage.rst
Follow up to https://github.com/geotools/geotools/pull/3740 with some improvements to geopackage documentation.
> Some small improvements to geopackage documentation

- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/ContourProcess.java
- modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/ContourProcessTest.java
[![GEOT-7051](https://badgen.net/badge/JIRA/GEOT-7051/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7051) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR updates ContourProcess to extract the NoData property from the input GridCoverage2D.
> [GEOT-7051] ContourProcess doesn't extract GridCoverage2D NoData properties

- modules/ogc/net.opengis.wcs/src/net/opengis/wcs10/impl/DescribeCoverageTypeImpl.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerRequest.java
- modules/plugin/jp2k/src/main/java/org/geotools/coverageio/jp2k/RasterLayerRequest.java
- modules/unsupported/geojsonstore/src/main/java/org/geotools/data/geojson/GeoJSONReader.java
- modules/unsupported/swing/src/test/java/org/geotools/swing/dialog/JFileImageChooserTest.java
Hi
I have found some lines of codes with a double semicolon at the end. No impact on baseline
ciao
matteo
> Removed double semicolon at the end of line

- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/ContourProcess.java
- modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/ContourProcessTest.java
[![GEOT-7051](https://badgen.net/badge/JIRA/GEOT-7051/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7051) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
26.x backport for https://github.com/geotools/geotools/pull/3736
> [26.x][GEOT-7051] ContourProcess doesn't extract GridCoverage2D NoData properties

- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/ContourProcess.java
- modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/ContourProcessTest.java
[![GEOT-7051](https://badgen.net/badge/JIRA/GEOT-7051/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7051) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
25.x backport for https://github.com/geotools/geotools/pull/3736
> [25.x][GEOT-7051] ContourProcess doesn't extract GridCoverage2D NoData properties

- modules/library/metadata/src/main/java/org/geotools/util/GrowableInternationalString.java
- modules/library/metadata/src/test/java/org/geotools/util/GrowableInternationalStringTest.java
[![GEOT-7061](https://badgen.net/badge/JIRA/GEOT-7061/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7061) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
`GrowableInternationalString.getLocales():Set<Locale>`
will always return the values it had when it was first called,
regardless of having called
`GrowableInternationalString.add(Locale, String)` afterwards.
This is because the set of Locales is held in an instance variable
initialized when `getLocales()` is first called, and never updated.
Moreover, it doesn't even make sense to cache them.
> [GEOT-7061] GrowableInternationalString.getLocales() is fixed to the values of its first invocation

- .github/workflows/linux_jdk11.yml
- .github/workflows/linux_jdk17.yml
- .github/workflows/linux_jdk8.yml
- .github/workflows/macos.yml
- modules/unsupported/pom.xml
- modules/unsupported/vsi/pom.xml
- modules/unsupported/vsi/src/main/java/org/geotools/vsi/VSIDataset.java
- modules/unsupported/vsi/src/main/java/org/geotools/vsi/VSIFormat.java
- modules/unsupported/vsi/src/main/java/org/geotools/vsi/VSIFormatFactory.java
- modules/unsupported/vsi/src/main/java/org/geotools/vsi/VSIProperties.java
- modules/unsupported/vsi/src/main/java/org/geotools/vsi/VSIReader.java
- modules/unsupported/vsi/src/main/java/org/geotools/vsi/VSIUtils.java
- modules/unsupported/vsi/src/main/resources/META-INF/services/org.geotools.coverage.grid.io.GridFormatFactorySpi
- modules/unsupported/vsi/src/test/java/org/geotools/vsi/VSIDatasetTest.java
- modules/unsupported/vsi/src/test/java/org/geotools/vsi/VSIFormatFactoryTest.java
- modules/unsupported/vsi/src/test/java/org/geotools/vsi/VSIPropertiesTest.java
- modules/unsupported/vsi/src/test/java/org/geotools/vsi/VSIUtilsTest.java
[![GEOT-7050](https://badgen.net/badge/JIRA/GEOT-7050/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7050) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR adds support for VSI Virtual File Systems available through GDAL. The intent is to allow provide a GeoServer data store type that can access remote data in a cloud-agnostic way. It works by converting remote spatial data to a VRT format and leveraging the existing VRT reader to do the rest.
> [GEOT-7050] VSI Virtual File System support

- docs/src/main/java/org/geotools/wfs/ReadWFSKommuner.java
- docs/src/main/java/org/geotools/wmts/WMTSCoverage.java
- docs/src/main/java/org/geotools/wmts/WMTSDownloader.java
- docs/src/main/java/org/geotools/wmts/WMTSMapViewer.java
- docs/user/extension/wmts/index.rst
[![GEOT-7058](https://badgen.net/badge/JIRA/GEOT-7058/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7058) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Based on input of @jodygarnett 
Changed headers and using literalinclude for code examples
> [GEOT-7058] WMTS documentation and examples - updates

- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDialectTest.java
[![GEOT-7073](https://badgen.net/badge/JIRA/GEOT-7073/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7073) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket
> [GEOT-7073] GeoPackage store fails to use spatial indexes when multiple BBOX filters are used at the same time

- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDialectTest.java
[![GEOT-7073](https://badgen.net/badge/JIRA/GEOT-7073/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7073) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7073] GeoPackage store fails to use spatial indexes when multiple BBOX filters are used at the same time (25.x)

- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDialectTest.java
[![GEOT-7073](https://badgen.net/badge/JIRA/GEOT-7073/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7073) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport from main 
> [GEOT-7073] GeoPackage store fails to use spatial indexes when multiple BBOX filters are used at the same time (26.x)

- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSBooleanBinding.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSDateBinding.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSDateTimeBinding.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSDecimalBinding.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSDoubleBinding.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSFloatBinding.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSIntegerBinding.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSLongBinding.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSTimeBinding.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xs/TestSchema.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xs/bindings/XSBooleanStrategyTest.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xs/bindings/XSDateTimeStrategyTest.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xs/bindings/XSDecimalStrategyTest.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xs/bindings/XSDoubleStrategyTest.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xs/bindings/XSFloatStrategyTest.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xs/bindings/XSIntegerStrategyTest.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xs/bindings/XSLongStrategyTest.java
[![GEOT-7072](https://badgen.net/badge/JIRA/GEOT-7072/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7072) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Allow empty string element value for parsing simple types in gt-xsd to avoid NumberFormatException.
gt-xsd version of [GEOT-3350](https://osgeo-org.atlassian.net/browse/GEOT-3350), an old bug report over gt-xml.
Non-conformant WFS implementations tend to emit empty elements for null values, instead of the appropriate GML  Nil/Null, or omitting the xml element.
> [GEOT-7072] Allow empty string element value for parsing simple types in gt-xsd to avoid NumberFormatException

- modules/library/jdbc/src/main/java/org/geotools/jdbc/SessionCommandsListener.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/SessionCommandListenerTest.java
[![GEOT-7076](https://badgen.net/badge/JIRA/GEOT-7076/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7076) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
[GEOT-7076] Enable to use curly brackets out of env variable definitions in sql start/release scripts
There is a bug in stored start/stop session custom sql script. When the script has a closing bracket char '}' out of a env variable definition, the script is treated as invalid and then it cannot use the db connection at all.
This commit reverts such a limitation and adds some more test cases for valid/invalid sql start/stop …
> [GEOT-7076] Enable to use curly braces out of env variable definition

- modules/extension/complex/src/test/java/org/geotools/filter/attribute/extractor/FilterAttributeExtractorTest.java
- modules/library/main/src/main/java/org/geotools/filter/FilterAttributeExtractor.java
[![GEOT-7074](https://badgen.net/badge/JIRA/GEOT-7074/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7074) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
[GEOT-7074] SLD or CSS filter rules using a non existent attribute named 'type' causes a generic ClassCastException instead of a specific exception with the right message
> [GEOT-7074] SLD or CSS filter rules using a non existent attribute named 'type' causes a generic ClassCastException

- modules/extension/complex/src/test/java/org/geotools/filter/attribute/extractor/FilterAttributeExtractorTest.java
- modules/library/main/src/main/java/org/geotools/filter/FilterAttributeExtractor.java
[![GEOT-7074](https://badgen.net/badge/JIRA/GEOT-7074/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7074) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backported from #3797
SLD or CSS filter rules using a non existent attribute named 'type' causes a generic ClassCastException instead of a specific exception with the right message
> [GEOT-7074] SLD or CSS filter rules using a non existent attribute named "type" 26.x

- modules/library/jdbc/src/main/java/org/geotools/jdbc/SessionCommandsListener.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/SessionCommandListenerTest.java
[![GEOT-7076](https://badgen.net/badge/JIRA/GEOT-7076/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7076) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backported from #3798
> [GEOT-7076] Enable to use curly braces out of env variable definitions in sql start/release scripts 26.x

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/IndexManager.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureSource.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileSetManager.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileReader.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/fid/IndexedFidReader.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/index/quadtree/fs/FileSystemIndexStore.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/ShapefileReader.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDescriptorLeakTest.java
[![GEOT-7088](https://badgen.net/badge/JIRA/GEOT-7088/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7088) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR fixes file descriptor leaks when reading shapefiles with invalid files for certain file formats.  Some debug logging was added for cases where exceptions from invalid files were being swallowed even when there was no leak.  This PR also fixes read locks on QIX files not being properly tracked so GeoTools wouldn't report the QIX files as being open even though they were still open.
> [GEOT-7088] Fix shapefile resource leaks

- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/v2_0/storedquery/ParameterTypeFactoryTest.java
[![GEOT-7087](https://badgen.net/badge/JIRA/GEOT-7087/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7087) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
I discovered some test failures in gt-wfs-ng as a consequence of the change of default locale in the number_format function. This will only be visible when using a locale with a different decimal separator.
> [GEOT-7087] Followup to number_format change

- pom.xml
Simple ImageIO-Ext dependency version upgrade for better support for S3 URLs
https://github.com/geosolutions-it/imageio-ext/issues/256
> Updating GT to imageio-ext-1.4.1 (better support for S3 urls)

- modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/DateParser.java
- modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/DateParserTest.java
[![GEOT-7105](https://badgen.net/badge/JIRA/GEOT-7105/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7105) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The GeoJSON parser attempts to parse incoming data as a date, and is meant to skip data it can't parse. WHen it encounters a string that is a integral number that is bigger than an int, but fits in a long, it instead fails with an exception.
> [GEOT-7105] Handling NumberFormatException in DateParser for GeoJSON parser.

- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticDataStoreFactory.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticFeatureSource.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticRequest.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/FilterToElastic.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/GeohashUtil.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/ElasticBucketVisitor.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/GeoHashGrid.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/GeoHashGridProcess.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticTestSupport.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticViewParametersFilterIT.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/GeohashUtilTest.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridProcessIT.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridProcessTest.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridTest.java
A few changes to make ES grid generation more convenient, less prone to security dodging attacks, and have it better align on screen, especially when using tiled displays:
* [[GEOT-7118](https://osgeo-org.atlassian.net/browse/GEOT-7118)] Allow GeoHashGridProcess to default the grid aggregation definition
* [[GEOT-7119](https://osgeo-org.atlassian.net/browse/GEOT-7119)] Clean up GeoHashGridProcessParameters, make it work properly with tiling
> ElasticSearch dynamic grid enhancements

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WMTSSpecification.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java
[![GEOT-7125](https://badgen.net/badge/JIRA/GEOT-7125/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7125) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
I've discovered a bug within creating url for GetSingleTileRequest.
> [GEOT-7125] GetSingleTileRequest doesn't include TIME in url

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/map/WMTSCoverageReader.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/map/WMTSMapLayerTest.java
[![GEOT-7124](https://badgen.net/badge/JIRA/GEOT-7124/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7124) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
I would like to see a more robust method to determine whether the coordinate reference system is supported natively by the server.
> [GEOT-7124] WMTSCoverageReader isNativelySupported should check for equality in CRS rather than SRS

- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/PullParser.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/parsers/AbstractGetFeatureParserTest.java
[![GEOT-7132](https://badgen.net/badge/JIRA/GEOT-7132/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7132) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR disables external entities in PullParser which is used by the WFS store.
> [GEOT-7132] Disable external entities in PullParser

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/map/WMTSCoverageReader.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/map/WMTSMapLayer.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/map/WMTSCoverageReaderTest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/LantmaterietWMTSServerOnlineTest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/WMTSMapLayerOnlineTest.java
- modules/extension/xsd/xsd-wmts/src/main/java/org/geotools/wmts/bindings/TileMatrixLimitsBinding.java
[![GEOT-7093](https://badgen.net/badge/JIRA/GEOT-7093/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7093) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
A little rewrite of previous PR that introduced a lot of instance variables and public getters that are related to a single request. Even though this class would easily been used to serve several requests. Maybe even in parallel.
> [GEOT-7093] WMTSCoverageReader shouldn't have instance variables for single requests

- modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java
- modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderTest.java
[![GEOT-7141](https://badgen.net/badge/JIRA/GEOT-7141/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7141) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket for details.
> [GEOT-7141] GeoTIFF mask/overview lookup should default to GeoTIFF format

- modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java
- modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderTest.java
[![GEOT-7141](https://badgen.net/badge/JIRA/GEOT-7141/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7141) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7141] GeoTIFF mask/overview lookup should default to GeoTIFF format (27.x)

- modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java
- modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderTest.java
[![GEOT-7141](https://badgen.net/badge/JIRA/GEOT-7141/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7141) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7141] GeoTIFF mask/overview lookup should default to GeoTIFF format (26.x)

- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCDataStoreAPIOnlineTest.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCDataStoreOnlineTest.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCFeatureSourceExposePkOnlineTest.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCFeatureSourceOnlineTest.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGeneric3DOnlineTest.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGeographyOnlineTest.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCTestSupport.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgFeatureSourceOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGIS3DOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISFeatureSourceExposePkOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISFeatureSourceOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreAPIOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGeographyOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisViewOnlineTest.java
[![GEOT-2063](https://badgen.net/badge/JIRA/GEOT-2063/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-2063) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-2063] PostGIS xy axis order

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostGISPSTestSetup.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostgisDataStoreOnlineTest.java
[![GEOT-6888](https://badgen.net/badge/JIRA/GEOT-6888/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6888) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
backports #3893 to 27.x
> [GEOT-6888] PostGIS - fixed columns lengths when using prepared statements (27.x)

- pom.xml
Bumping up to ImageIO-Ext 1.4.5 for better support of COG S3 (IAM Roles)
> Updating to imageio-ext-1.4.5

- modules/library/main/src/main/java/org/geotools/geometry/jts/WKTWriter2.java
- modules/library/main/src/test/java/org/geotools/geometry/jts/WKTWriter2Test.java
[![GEOT-7149](https://badgen.net/badge/JIRA/GEOT-7149/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7149) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Added setting to DecimalFormat for Norwegian locale (and other's).
And also a test that is somewhat hard to run. The existing tests are failing for me in a JDK >8 without the change.
> [GEOT-7149] WKTWriter2 failing with negative numbers in some locales

- .github/workflows/linux_jdk11.yml
- .github/workflows/linux_jdk8.yml
- docs/common.py
[![GEOT-7154](https://badgen.net/badge/JIRA/GEOT-7154/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7154) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7154] Sphinx build failure with extlinks (new warnings in Sphinx build) (26.x)

- modules/plugin/jdbc/jdbc-h2/src/main/java/org/geotools/data/h2/H2DialectBasic.java
- modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2LinkedTableTest.java
[![GEOT-7157](https://badgen.net/badge/JIRA/GEOT-7157/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7157) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR add support to linked table on H2 db plugin.
> [GEOT-7157] Support linked table for H2 database

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
[![GEOT-7064](https://badgen.net/badge/JIRA/GEOT-7064/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7064) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR proposes to add a new method on SQLDialect to retrieve a java type when the static mapping fails.
This PR is related to the issue [GEOT-7064](https://osgeo-org.atlassian.net/browse/GEOT-7064).
Feel free to comments.
> [GEOT-7064] H2GIS 2.0.0

- modules/library/main/src/main/java/org/geotools/feature/AttributeTypeBuilder.java
- modules/library/sample-data/src/main/java/org/geotools/test/OnlineTestCase.java
- modules/plugin/csv/src/test/java/org/geotools/data/csv/parse/CSVLatLonStrategyTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java
[![GEOT-7150](https://badgen.net/badge/JIRA/GEOT-7150/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7150) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Removed the setName call. Now the name of AttributeType would either be explicitly set, or it will be the name of the binding class.
The functions buildDescriptor shouldn't been a part of AttributeTypeBuilder rather they should have their own AttributeDescriptorBuilder.
There were just two tests that was written based on wrong type names.
> [GEOT-7150] Name of type in AttributeDescriptor are wrong

- modules/library/coverage/src/main/java/org/geotools/coverage/grid/RenderedSampleDimension.java
[![GEOT-7171](https://badgen.net/badge/JIRA/GEOT-7171/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7171) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Clean up the creation method. RectIterator is never used. remove it.
> [GEOT-7171]: Remove iterator from Create (Since it's not used)

- modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/RenderableFeatureTest.java
[![GEOT-7170](https://badgen.net/badge/JIRA/GEOT-7170/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7170) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7170] StreamingRenderer might throw NPE with complex features when no default Geometry attribute is set

- modules/library/main/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope.java
- modules/library/referencing/src/main/java/org/geotools/referencing/DefaultAuthorityFactory.java
- modules/library/referencing/src/main/java/org/geotools/referencing/factory/ManyAuthoritiesFactory.java
- modules/library/referencing/src/main/java/org/geotools/referencing/factory/ThreadedAuthorityFactory.java
- modules/plugin/epsg-extension/src/test/java/org/geotools/referencing/epsg/esri/EpsgFallbackTest.java
[![GEOT-7165](https://badgen.net/badge/JIRA/GEOT-7165/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7165) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The main change is within the function createFallbacks where I split Citations with more than one Identifier (Like ESRI, EPSG) into singular Citations. That will make them reachable for both ESRI and EPSG.
Added some logging to dispose which crs is being used in each situation.
Fixed an assertion within a test that I mean is counterintuitive.
> [GEOT-7165] Failing to find CRS factory for ESRI:102017 with gt-epsg-extension at classpath

- modules/extension/app-schema/app-schema/pom.xml
[![GEOT-7179](https://badgen.net/badge/JIRA/GEOT-7179/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7179) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Test dependency upgrade.
See ticket. Supercedes https://github.com/geotools/geotools/pull/3957
> [GEOT-7179] Upgrade app-schema Jetty test dependency to 9.4.48.v20220622

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFilterSplitter.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterSplitterTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java
[![GEOT-5911](https://badgen.net/badge/JIRA/GEOT-5911/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-5911) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
FIXED GEOT-5911 and some others, mongodb splitter bug
3 existing unit tests did invalid checks, and fixing the splitter made them fail:
e.g. testEqualToFilter:  The result contained points 0 1 2 but should only contain 2 as the test does equals to "two"
Let me know if you want this
Sorry this is wrong and I don't seem to manage  to get it fixed.  github newby :-(
A second commit appeared when I …
> [GEOT-5911] MongoDB CQL_Filter not working anymore (and some other issue)

- modules/extension/wms/src/main/java/org/geotools/ows/wms/xml/WMSComplexTypes.java
- modules/extension/wms/src/test/java/org/geotools/ows/wms/xml/test/WMSComplexTypesTest.java
- modules/extension/wms/src/test/resources/org/geotools/ows/wms/xml/test/test-data/1.3.0Capabilities_EmptyOnlineResource.xml
[![GEOT-7185](https://badgen.net/badge/JIRA/GEOT-7185/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7185) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Signed-off-by: mtcarto <morgan.thomps@gmail.com>
Parsing of an WMS 1.3.0 capabilities document  containing an empty OnlineResource element can cause a MalformedUrl error to be thrown when parsing. 
> [GEOT-7185] Tolerate empty Online Resource in Service definition

- modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONReader.java
- modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/PagingFeatureCollection.java
- modules/unsupported/stac-store/src/main/java/org/geotools/stac/client/STACClient.java
- modules/unsupported/stac-store/src/main/java/org/geotools/stac/client/STACGeoJSONReader.java
- modules/unsupported/stac-store/src/main/java/org/geotools/stac/client/STACPagingFeatureCollection.java
- modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/STACDataStore.java
- modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/STACDataStoreFactory.java
- modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/STACFeatureSource.java
- modules/unsupported/stac-store/src/test/java/org/geotools/stac/store/STACFeatureSourceTest.java
- modules/unsupported/stac-store/src/test/resources/org/geotools/stac/maja10.json
- modules/unsupported/stac-store/src/test/resources/org/geotools/stac/maja20.json
See tickets:
* https://osgeo-org.atlassian.net/browse/GEOT-7190
* https://osgeo-org.atlassian.net/browse/GEOT-7191
I think the first one could be of general interest, also for an eventual GeoJSONDataStore improvement, if the GeoJSON were to be placed online, or as a pattern to reuse on OGC clients fetching lots of data.
> Improve usablity of STAC store for GetMap usage

- modules/unsupported/stac-store/src/main/java/org/geotools/stac/client/AbstractDocument.java
- modules/unsupported/stac-store/src/main/java/org/geotools/stac/client/STACClient.java
- modules/unsupported/stac-store/src/main/java/org/geotools/stac/client/STACLandingPage.java
- modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/STACFeatureSource.java
- modules/unsupported/stac-store/src/test/java/org/geotools/stac/STACOfflineTest.java
- modules/unsupported/stac-store/src/test/java/org/geotools/stac/client/STACClientOfflineTest.java
- modules/unsupported/stac-store/src/test/java/org/geotools/stac/store/STACFeatureSourceTest.java
- modules/unsupported/stac-store/src/test/resources/org/geotools/stac/collectionsAu.json
- modules/unsupported/stac-store/src/test/resources/org/geotools/stac/landingPageAu.json
- modules/unsupported/stac-store/src/test/resources/org/geotools/stac/majaNone.json
Harden store against corner cases, make the STAC client a bit more tolerant against the wild variety of servers out there.
> Assorted small STAC store improvements

- modules/library/main/src/main/java/org/geotools/filter/expression/SimpleFeaturePropertyAccessorFactory.java
- modules/unsupported/geojson-core/src/main/java/org/geotools/filter/expression/geojson/JSONNodePropertyAccessorFactory.java
- modules/unsupported/geojson-core/src/main/resources/META-INF/services/org.geotools.filter.expression.PropertyAccessorFactory
- modules/unsupported/geojson-core/src/test/java/org/geotools/filter/expression/geojson/JSONNodePropertyAccessorFactoryTest.java
- modules/unsupported/geojson-core/src/test/java/org/geotools/filter/expression/geojson/JSONNodePropertyAccessorTest.java
[![GEOT-7203](https://badgen.net/badge/JIRA/GEOT-7203/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7203) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Refactor package
org.geotools.filter.expression -> org.geotools.filter.expression.geojson
> [GEOT-7203] Split package introduces in gt-geojson-core

- pom.xml
[![GEOT-6384](https://badgen.net/badge/JIRA/GEOT-6384/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6384) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Bumps [EJML](https://github.com/lessthanoptimal/ejml) from 0.34 to 0.41.
- [Release notes](https://github.com/lessthanoptimal/ejml/releases/tag/v0.41)
- [Changelog](https://github.com/lessthanoptimal/ejml/blob/v0.41/change.txt)
- [Commits](https://github.com/lessthanoptimal/ejml/compare/v0.34...v0.41)
This should fix
```
java.lang.NoSuchMethodError: 'void org.ejml.dense.row.CommonOps_DDRM.mult(org.ejml.data.DMatrix1Row, …
```
> [GEOT-6384] Update EJML from 0.34 to 0.41

- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaFilterToSQL.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaBBOXFilterOnlineTest.java
[![GEOT-7207](https://badgen.net/badge/JIRA/GEOT-7207/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7207) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
When adding a BBOX filter to a query, the HANA plugin will hard-code the
coordinates of the bounding box instead of using parameters (?) in the
generated query.
When executing the same query repeatedly with only a different bounding
box, the database cannot reuse a plan from the SQL plan cache due to the
changed hard-coded bounding box values, but has to generate a new plan.
This can be costly, especially if the query is …
> [GEOT-7207] Use parameters instead of hard-coded values for BBOX filters

- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaDialect.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaColumnWoSridConstraintOnlineTest.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaColumnWoSridConstraintTestSetup.java
[![GEOT-7186](https://badgen.net/badge/JIRA/GEOT-7186/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7186) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
If a column does not have an SRID constraint, ``HanaDialect#getGeometrySRID()`` did not return the correct SRID, but 0 instead.
As the ST_GeometryColumns view does not specify the SRID, we select a geometry from the column now to detect the SRID.
> [GEOT-7186] SRID of geometries in columns w/o SRID constraint not detected properly

- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaBBOXFilterOnlineTest.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaEscapingOnlineTest.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaEscapingTestSetup.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaTestUtil.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/ci/CIBase.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/ci/CISetup.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/ci/CITeardown.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/metadata/CommandLineArgumentsTest.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/wkb/HanaWKBTest.java
[![GEOT-7211](https://badgen.net/badge/JIRA/GEOT-7211/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7211) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
There are some suppressed PMD warnings in gt-jdbc-hana that can be fixed. Furthermore, some files are missing the file header comment.
> [GEOT-7211] Fix suppressed PMD warnings and add missing file headers in gt-jdbc-hana

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java
- pom.xml
[![GEOT-7222](https://badgen.net/badge/JIRA/GEOT-7222/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7222) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7222] Image Mosaic excessive memory usage when mosaicking many little images (26.x backport)

- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShpFilesStreamTest.java
[![GEOT-7225](https://badgen.net/badge/JIRA/GEOT-7225/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7225) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The fails on JDK 11, because of the assertion that isLocal will return false. For JDK 8 and earlier that was true, because the url would be jar:file... That has changed and the url will now be file:/.......jar!shapes/statepop.shp.
I don't see the need for that check, so I'm removing it.
I'm also renaming the file, so that the suffix of the class will be Test.
> [GEOT-7225] Assertion in ShpFilesTestStream depends on environment

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/map/WMTSCoverageReader.java
[![GEOT-7177](https://badgen.net/badge/JIRA/GEOT-7177/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7177) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
A little change to make it more clear which tileset being used when reprojecting a WMTS tile request.
> [GEOT-7177] Remove randomSupportedCRS from WMTSCoverageReader

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/model/WMTSCapabilities.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/model/WMTSCapabilitiesTest.java
- modules/extension/wmts/src/test/resources/test-data/nasa.getcapa.xml
[![GEOT-7229](https://badgen.net/badge/JIRA/GEOT-7229/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7229) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The constructor of WMTSCapabilities will throw an exception if a Layer has a MatrixTileSetLink that points to a MatrixTileSet that isn’t specified among the MatrixTileSet’s of the same document.
I've copied the Layer-element into nasa.getcapa.xml. Therefore I had to change one of the expectations in a different test. 
> [GEOT-7229] WMTSCapabilities throws NPE for misconfigured capabilities

- modules/library/main/src/main/java/org/geotools/geometry/jts/coordinatesequence/CoordinateSequences.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiLineHandler.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiPointHandler.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PointHandler.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PolygonHandler.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/shp/ZMHandlersTest.java
Page 2 of the [Shapefile spec](https://support.esri.com/en/white-paper/279) says:
>  Floating point numbers must be numeric values. Positive infinity, negative infinity, and Not-a-Number (NaN) values are not allowed in shapefiles. Nevertheless, shapefiles support the concept of "no data" values, but they are currently used only for measures.  Any floating point number smaller than –10^38 is considered by a shapefile reader to …
> GEOT-7231: Z values shapefiles don't handle NaN M values correctly

- modules/extension/xsd/xsd-gml3/pom.xml
- modules/library/main/src/main/java/org/geotools/geometry/jts/coordinatesequence/CoordinateSequences.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiLineHandler.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiPointHandler.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PointHandler.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PolygonHandler.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/shp/ZMHandlersTest.java
Page 2 of the [Shapefile spec](https://support.esri.com/en/white-paper/279) says:
>  Floating point numbers must be numeric values. Positive infinity, negative infinity, and Not-a-Number (NaN) values are not allowed in shapefiles. Nevertheless, shapefiles support the concept of "no data" values, but they are currently used only for measures.  Any floating point number smaller than –10^38 is considered by a shapefile reader to …
> GEOT-7231] Z values shapefiles don't handle NaN M values correctly

- modules/unsupported/ogcapi-client/src/test/java/org/geotools/ogcapi/QuickTileViewer.java
[![GEOT-7237](https://badgen.net/badge/JIRA/GEOT-7237/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7237) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Just a fix for a compile error in an unsupported module.
> [GEOT-7237] Compile error in gt-ogcapi-client

- modules/library/metadata/src/main/java/org/geotools/metadata/math/XMath.java
- modules/library/metadata/src/main/java/org/geotools/util/Arguments.java
- modules/library/metadata/src/main/java/org/geotools/util/Java6.java
- modules/library/metadata/src/main/java/org/geotools/util/package.html
[![GEOT-7235](https://badgen.net/badge/JIRA/GEOT-7235/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7235) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Just added a Deprecated. Even though the Javadocs states that changes to the API might happen.
> [GEOT-7235] Deprecate org.geotools.util.Java6

- modules/unsupported/s3-geotiff/pom.xml
Reverts geotools/geotools#3966
because the original PR did not comply with the QA: https://github.com/geotools/geotools/actions/runs/2679353957/jobs/4176462298
/cc @ianturton @aaime
> Revert "Bump aws-java-sdk-s3 from 1.11.36 to 1.12.261 in /modules/unsupported/s3-geotiff"

- modules/extension/ysld/src/main/java/org/geotools/ysld/encode/RasterSymbolizerEncoder.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/parse/RasterParser.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeCookbookTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseCookbookTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
- modules/extension/ysld/src/test/resources/org/geotools/ysld/sld/raster/band-selection-expression.sld
[![GEOT-7208](https://badgen.net/badge/JIRA/GEOT-7208/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7208) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR allows YSLD styles to use raster channel name expressions, which was added for SLD styles a while ago.
> [GEOT-7208] Missing YSLD support for channel name expressions

- docs/user/extension/ysld.rst
- modules/extension/ysld/src/main/java/org/geotools/ysld/parse/RootParser.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
[![GEOT-7210](https://badgen.net/badge/JIRA/GEOT-7210/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7210) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR updates the YSLD parser to set the name of the NamedLayer so that YSLD styles can be used with GeoServer's WMS dynamic styling.  The style name was unnecessarily being set twice.
> [GEOT-7210] YSLD styles do not set the layer name

- docs/user/extension/ysld.rst
- modules/extension/ysld/src/main/java/org/geotools/ysld/encode/RootEncoder.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/parse/RootParser.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
- modules/library/main/src/main/java/org/geotools/styling/SLD.java
[![GEOT-7210](https://badgen.net/badge/JIRA/GEOT-7210/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7210) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Previously the encoder relied on utility method to extract the first style and did not have any referenced to named layer to user layer. I am preserving the limitation of only encoding one style (as YSLD is more accurately a representation of Symbology Encoding and has not previously had the concept of SLD NamedLayer.
This pull request completes the work started by https://github.com/geotools/geotools/pull/4000 
For core and …
> [GEOT-7210] YSLD does not encode layer name

- modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java
- modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
[![GEOT-7246](https://badgen.net/badge/JIRA/GEOT-7246/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7246) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
A GeoJSON feature with no geometry should not throw a NPE. 
From the GeoJSON spec 
> A Feature object has a member with the name "geometry".  The value
of the geometry member SHALL be either a Geometry object as
defined above or, in the case that the Feature is unlocated, a
JSON null value.
> [GEOT-7246] Correctly handle null geometries in GeoJSON

- docs/user/library/jdbc/hana.rst
- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaDataStoreFactory.java
- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaDialect.java
- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaJNDIDataStoreFactory.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaSelectHintOnlineTest.java
[![GEOT-7230](https://badgen.net/badge/JIRA/GEOT-7230/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7230) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This pull request adds a new "SELECT Hint" parameter to the HANA JDBC plugin.
`SELECT Hint`s are appended to SELECT queries, embedded in the string
```
WITH HINT( <SELECT Hints> )
```
Setting `SELECT Hint`s enables a user to configure HANA specific query hints that will be considered during query plan generation.
> [GEOT-7230] Implement a HINT parameter as part of the HANA plug-in

- docs/user/welcome/upgrade.rst
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSFeatureReader.java
[![GEOT-7240](https://badgen.net/badge/JIRA/GEOT-7240/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7240) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Removing a deprecated function.
> [GEOT-7240] Remove deprecated constructor from WFSFeatureReader

- modules/library/coverage/src/main/java/org/geotools/coverage/grid/GridGeometry2D.java
- modules/library/coverage/src/test/java/org/geotools/coverage/grid/GridGeometryTest.java
[![GEOT-7244](https://badgen.net/badge/JIRA/GEOT-7244/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7244) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The constructor was added prior to this PR.
This PR will fix a problem were the crs of the incoming userRange was omitted.
> [GEOT-7244] Constructor GridGeometry2D(Rectangle, Rectangle2D) looses CRS

- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/v2_0/Capabilities200ServiceInfoOnlineTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/AbstractWfsDataStoreOnlineTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/v2_0/Capabilities200ServiceInfoOnlineTest.java
[![GEOT-6324](https://badgen.net/badge/JIRA/GEOT-6324/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6324) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Made AbstractWfsDataStoreOnlineTest subclass of OnlineTestSupport.
Added a fixture "wfs" to run those test cases that extended AbstractWfsDataStoreOnlineTest, and added an individual check for availability using HTTPClient instead on url.openStream().
Ignoring the test Capabilities200ServiceInfoOnlineTest because it didn't extend AbstractWfsDataStoreOnelineTest nor OnlineTestSupport, and because the url was wrong.
For core and …
> [GEOT-6324] WFS-NG online tests don't extend OnlineTestSupport

- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDialect.java
- modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerDateOnlineTest.java
- modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerDateTestSetup.java
[![GEOT-7220](https://badgen.net/badge/JIRA/GEOT-7220/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7220) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7220] Support datetime2 and datetimeoffset in JDBC SQL Server (28.x backport)

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSource.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSourceTest.java
[![GEOT-7261](https://badgen.net/badge/JIRA/GEOT-7261/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7261) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Using same approach as WFSFeatureSource:
Return the bounds specified in the capabilities. If a crs is given in the query, we will retroject. For any other filter than All we will return null.
> [GEOT-7261] WFSContentComplexFeatureSource.getBounds will end up in StackOverflowException

- .github/workflows/mssql_online.yml
2022 was released this week, adding it to the test matrix. We could drop 2019 from the matrix if things take too long (though currently these mssql tests only take 4 min.)
> Add MS SQL Server 2022 to online tests

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSource.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSourceTest.java
[![GEOT-7238](https://badgen.net/badge/JIRA/GEOT-7238/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7238) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Included two test's that are accessing the real url. That might have been the reason for the Ignore.
Will be fixed by [GEOT-7239](https://osgeo-org.atlassian.net/browse/GEOT-7239)
> [GEOT-7238] WFSContentComplexFeatureSource.getFeatures(Filter) creates a wrong Query

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WMTSSpecification.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WebMapTileServer.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTile.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/map/WMTSCoverageReader.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/map/WMTSMapLayer.java
[![GEOT-7276](https://badgen.net/badge/JIRA/GEOT-7276/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7276) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Removing deprecated function's and instance variables not in use.
> [GEOT-7276] Remove deprecated from gt-wmts

- modules/library/http/src/test/java/org/geotools/http/MockHttpClient.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSource.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentDataAccess.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/ComplexGetFeatureResponse.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSContentComplexFeatureCollection.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/AbstractGetFeatureResponseParserFactory.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/ComplexGetFeatureResponseParserFactory.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/GetFeatureResponseParserFactory.java
- modules/unsupported/wfs-ng/src/main/resources/META-INF/services/org.geotools.data.wfs.internal.WFSResponseFactory
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSourceTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/WFSClientTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/KartverketStedsnavnDataStoreOnlineTest.java
[![GEOT-7239](https://badgen.net/badge/JIRA/GEOT-7239/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7239) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR fixes two bug's that prevented WFSContentDataAccess to work when using POST as HTTP transport.
- Within WFSContentDataAccess.getSchema() we were using client.createDescribeFeatureTypeRequest to get a url that was used in SchemaParser. When using POST that url would be incomplete.
- WFSContentComplexFeatureCollection we were using the GetFeatureRequest.getFinalUrl to get an URL for GetFeature request. When using POST …
> [GEOT-7239] WFSContentDataAccess will fail when using HTTP POST

- pom.xml
[![GEOT-7283](https://badgen.net/badge/JIRA/GEOT-7283/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7283) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Updates Batik dependencies to 1.16. We currently have 1.14. The changes are basically bug fixes, as noted at https://xmlgraphics.apache.org/batik/
> [GEOT-7283] update Batik to 1.16

- modules/library/xml/src/main/java/org/geotools/xml/transform/TransformerBase.java
[![GEOT-7284](https://badgen.net/badge/JIRA/GEOT-7284/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7284) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This solves the following error which occurs in version 27.2 when using Saxonica's Saxon instead of Apache's Xalan on JDK 8.
```
Caused by: net.sf.saxon.trans.XPathException: The SAX2 parser org.geotools.xml.transform.TransformerBase$XMLReaderSupport does not support setting the 'namespaces' feature to true
at net.sf.saxon.event.Sender.configureParser(Sender.java:557)
at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:305) …
```
> [GEOT-7284] Support for Saxon Transformer

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaDialect.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaVirtualTableHintOnlineTest.java
[![GEOT-7286](https://badgen.net/badge/JIRA/GEOT-7286/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7286) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
So far, ``JDBCDataStore`` does not add select-hints to queries on virtual tables. This makes sense for some ``SQLDialect``s, but not for all.
This change adds a new method ``applyHintsOnVirtualTables()`` to the ``SQLDialect`` class that allows the concrete ``SQLDialect`` to control whether hints are added to queries on virtual tables. The default implementation of ``applyHintsOnVirtualTables()`` returns ``false`` to keep the …
> [GEOT-7286] Let SQLDialect decide whether to apply hints on virtual tables

- modules/plugin/jdbc/jdbc-h2/pom.xml
[![GEOT-7293](https://badgen.net/badge/JIRA/GEOT-7293/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7293) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The problem in question is addressed in a new version of hatbox, but geodb seems to be lacking progress.
> [GEOT-7293] java.sql package used in different modules

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
[![GEOT-7248](https://badgen.net/badge/JIRA/GEOT-7248/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7248) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
test: https://github.com/geoserver/geoserver/pull/6400
> [GEOT-7248] fix query for multiple columns

- modules/extension/app-schema/app-schema/pom.xml
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
- modules/extension/app-schema/app-schema/src/test/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSourceTest.java
[![GEOT-7148](https://badgen.net/badge/JIRA/GEOT-7148/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7148) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7148] Bug in JoiningJDBCFeatureSource / FilterToSQL creates invalid SQL

- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaDataStoreFactory.java
- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaDialect.java
- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaJNDIDataStoreFactory.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaDisableSimplificationOnlineTest.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaDisableSimplificationTestSetup.java
[![GEOT-7294](https://badgen.net/badge/JIRA/GEOT-7294/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7294) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This change adds an option to the HANA plugin that allows disabling geometry simplification by the database.
> [GEOT-7294] Geometry simplification cannot be disabled in HANA plugin

- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/wkb/HanaWKBParser.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/wkb/HanaRingPatchingTest.java
[![GEOT-7295](https://badgen.net/badge/JIRA/GEOT-7295/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7295) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
HANA allows the creation of polygons consisting of two points only, e.g. POLYGON((1 2, 1 2)). Especially, this can be the result of a geometry simplification (calling ST_Simplify()). Those polygons are then rejected by other geometry frameworks.
This change patches polygon rings consisting of 2 or 3 points only, so that they consist of 4 points.
> [GEOT-7295] HANA plugin attempts to create polygons consisting of 2 points only

- modules/unsupported/jdbc-h2gis/src/main/java/org/h2gis/geotools/H2GISDialect.java
- modules/unsupported/jdbc-h2gis/src/test/java/org/h2gis/geotools/H2GISTest.java
[![GEOT-7298](https://badgen.net/badge/JIRA/GEOT-7298/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7298) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fix srid and geometry type detection due to the last H2GIS 2.2.0 version.
> [GEOT-7298] H2GIS doesn't return the proper srid for an existing table

- .github/workflows/integration.yml
- modules/library/main/src/main/java/org/geotools/filter/function/InFunction.java
[![GEOT-7301](https://badgen.net/badge/JIRA/GEOT-7301/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7301) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket for details. No new tests implemented, as it's a performance optimization, and the in function already offers a bunch of tests with mixed data types and the like.
> [GEOT-7301] Static lookup for In function

- modules/library/metadata/src/main/java/org/geotools/util/DateTimeParser.java
- modules/library/metadata/src/test/java/org/geotools/util/DateTimeParserTest.java
[![GEOT-7304](https://badgen.net/badge/JIRA/GEOT-7304/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7304) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fixes a failing test in GeoServer. Copied parts of that test, and added parameterizing of Locale's.
> [GEOT-7304] DateTimeParser parse fails with negative year and Norwegian locale

- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
[![GHSA-99](https://badgen.net/badge/JIRA/GHSA-99/0052CC)](https://osgeo-org.atlassian.net/browse/GHSA-99) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
I got some new error's involving JDBC, and discovered this new PR. In the unwrapConnection function, it seems clear that the wrong variable is returned.
> Fix for Merge pull request from GHSA-99c3-qc2q-p94m

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/GeometryColumnEncoder.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisSimplifiedGeometryTest.java
[![GEOT-6262](https://badgen.net/badge/JIRA/GEOT-6262/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6262) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
`ERROR: lwgeom_write_to_buffer: X/Z precision cannot be greater than 7 or less than -7`
In GeoServer, in a linestring map layer from a PostGIS source, with the source's `Support on the fly geometry simplification` option set to its default value (`true`), when zooming in very far (scale around 1:50), the [ST_AsTWKB](https://postgis.net/docs/ST_AsTWKB.html) function is called with an invalid value (`8`) for the …
> [GEOT-6262] Zooming in a lot (around 1:10 scale) can make TWKB transfer fail

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/GeometryColumnEncoder.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisSimplifiedGeometryTest.java
[![GEOT-6262](https://badgen.net/badge/JIRA/GEOT-6262/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6262) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4181
**Authored by:** @wscherphof
> [Backport 28.x] [GEOT-6262] Zooming in a lot (around 1:10 scale) can make TWKB transfer fail

- docs/src/main/java/org/geotools/jdbc/JDBCExamples.java
- docs/user/library/jdbc/postgis.rst
- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/EscapeSql.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
- modules/library/jdbc/src/test/java/org/geotools/data/jdbc/FilterToSQLTest.java
- modules/library/main/src/main/java/org/geotools/filter/LikeFilterImpl.java
- modules/library/main/src/test/java/org/geotools/filter/FilterTest.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDialectBasic.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLFilterToSQLTest.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleFilterToSQL.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleFilterToSqlTest.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisNGDataStoreFactory.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisNGDataStoreFactoryTest.java
Backporting PR from @sikeoka along with a minor documentation improvement.
Authored by: @sikeoka
> [Backport 28.x] [GEOT-7302] Escape user inputs in SQL queries

- docs/src/main/java/org/geotools/jdbc/JDBCExamples.java
- docs/user/library/jdbc/postgis.rst
- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/EscapeSql.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
- modules/library/jdbc/src/test/java/org/geotools/data/jdbc/FilterToSQLTest.java
- modules/library/main/src/main/java/org/geotools/filter/LikeFilterImpl.java
- modules/library/main/src/test/java/org/geotools/filter/FilterTest.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDialectBasic.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLFilterToSQLTest.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleFilterToSQL.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleFilterToSqlTest.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisNGDataStoreFactory.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisNGDataStoreFactoryTest.java
Backport of https://github.com/geotools/geotools/pull/4192 adjused for 27.x branch (which does not include jsonArrayContains function)
> [Backport 27.x] [GEOT-7302] Escape user inputs in SQL queries

- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/EscapeSql.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
- modules/library/jdbc/src/test/java/org/geotools/data/jdbc/FilterToSQLTest.java
- modules/library/main/src/main/java/org/geotools/filter/LikeFilterImpl.java
- modules/library/main/src/test/java/org/geotools/filter/FilterTest.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDialectBasic.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLFilterToSQLTest.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleFilterToSQL.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleFilterToSqlTest.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisNGDataStoreFactory.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisNGDataStoreFactoryTest.java
Backport of https://github.com/geotools/geotools/pull/4192 adjusted for 26.x branch
> [Backport 26.x] [GEOT-7302] Escape user inputs in SQL queries 

- docs/common.py
- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/EscapeSql.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
- modules/library/jdbc/src/test/java/org/geotools/data/jdbc/FilterToSQLTest.java
- modules/library/main/src/main/java/org/geotools/filter/LikeFilterImpl.java
- modules/library/main/src/test/java/org/geotools/filter/FilterTest.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDialectBasic.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLFilterToSQLTest.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleFilterToSQL.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleFilterToSqlTest.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisNGDataStoreFactory.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisNGDataStoreFactoryTest.java
Backport of https://github.com/geotools/geotools/pull/4192 adjusted for 25.x branch
> [Backport 25.x] [GEOT-7302] Escape user inputs in SQL queries

- modules/library/referencing/src/main/java/org/geotools/referencing/factory/wms/OGCAPICRSFactory.java
- modules/library/referencing/src/main/resources/META-INF/services/org.opengis.referencing.crs.CRSAuthorityFactory
- modules/library/referencing/src/test/java/org/geotools/referencing/factory/HTTP_URI_AuthorityFactoryTest.java
- modules/library/referencing/src/test/java/org/geotools/referencing/factory/wms/OGCAPITest.java
[![GEOT-7314](https://badgen.net/badge/JIRA/GEOT-7314/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7314) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7314] Add OGC authority so that GeoTools can parse URIs such as "http://www.opengis.net/def/crs/OGC/1.3/CRS84"

- modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/bindings/FeaturePropertyTypeBinding.java
- modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/GML3EncodingTest.java
- modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/WFSFeatureCollectionEncodingTest.java
[![GEOT-7316](https://badgen.net/badge/JIRA/GEOT-7316/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7316) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-7316
The GML output comes with wrong repeated attributes inserted on container elements (gml:featureMember, wfs:member) pulled from the child Feature element.  This PR introduces a fix for this bug.
> [GEOT-7316] Child feature ClientProperties are replicated on GML parent container elements

- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaFilterToSQL.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaFilterToSqlTest.java
[![GEOT-7318](https://badgen.net/badge/JIRA/GEOT-7318/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7318) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The unit of measure string literal is not properly escaped in the DWithin filter.
> [GEOT-7318] Unit of measure not escaped in DWithin filter

- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaFilterToSQL.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaFilterToSqlTest.java
[![GEOT-7318](https://badgen.net/badge/JIRA/GEOT-7318/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7318) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4215
> [Backport 28.x] [GEOT-7318] Unit of measure not escaped in DWithin filter

- modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/bindings/FeaturePropertyTypeBinding.java
- modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/GML3EncodingTest.java
- modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/WFSFeatureCollectionEncodingTest.java
[![GEOT-7316](https://badgen.net/badge/JIRA/GEOT-7316/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7316) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4208
> [Backport 28.x] [GEOT-7316] Child feature ClientProperties are replicated on GML parent container elements

- modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/bindings/FeaturePropertyTypeBinding.java
- modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/GML3EncodingTest.java
- modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/WFSFeatureCollectionEncodingTest.java
[![GEOT-7316](https://badgen.net/badge/JIRA/GEOT-7316/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7316) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4208
> [Backport 27.x] [GEOT-7316] Child feature ClientProperties are replicated on GML parent container elements

- modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/bindings/FeaturePropertyTypeBinding.java
- modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/GML3EncodingTest.java
- modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/WFSFeatureCollectionEncodingTest.java
[![GEOT-7316](https://badgen.net/badge/JIRA/GEOT-7316/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7316) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4208
> [Backport 26.x] [GEOT-7316] Child feature ClientProperties are replicated on GML parent container elements

- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaFilterToSQL.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaFilterToSqlTest.java
[![GEOT-7318](https://badgen.net/badge/JIRA/GEOT-7318/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7318) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4215
> [Backport 26.x] [GEOT-7318] Unit of measure not escaped in DWithin filter

- modules/library/main/src/main/java/org/geotools/feature/FeatureTypes.java
- modules/library/main/src/test/java/org/geotools/feature/FeatureTypesTest.java
[![GEOT-7331](https://badgen.net/badge/JIRA/GEOT-7331/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7331) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7331] ContentFeatureSource reprojection requirement check fails to resolve to false with two WGS84 CRS instances

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WebMapTileServer.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java
[![GEOT-7325](https://badgen.net/badge/JIRA/GEOT-7325/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7325) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4234
**Authored by:** @ianturton
> [Backport 29.x] [GEOT-7325] fix NPE on REST template requests with no operations

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WebMapTileServer.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java
[![GEOT-7325](https://badgen.net/badge/JIRA/GEOT-7325/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7325) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4234
**Authored by:** @ianturton
> [Backport 28.x] [GEOT-7325] fix NPE on REST template requests with no operations

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WebMapTileServer.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java
[![GEOT-7325](https://badgen.net/badge/JIRA/GEOT-7325/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7325) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4234
**Authored by:** @ianturton
> [Backport 27.x] [GEOT-7325] fix NPE on REST template requests with no operations

- modules/library/main/src/main/java/org/geotools/feature/FeatureTypes.java
- modules/library/main/src/test/java/org/geotools/feature/FeatureTypesTest.java
[![GEOT-7331](https://badgen.net/badge/JIRA/GEOT-7331/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7331) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4233
> [Backport 29.x] [GEOT-7331] ContentFeatureSource reprojection requirement check fails to resolve to false with two WGS84 CRS instances

- modules/library/main/src/main/java/org/geotools/feature/FeatureTypes.java
- modules/library/main/src/test/java/org/geotools/feature/FeatureTypesTest.java
[![GEOT-7331](https://badgen.net/badge/JIRA/GEOT-7331/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7331) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4233
> [Backport 28.x] [GEOT-7331] ContentFeatureSource reprojection requirement check fails to resolve to false with two WGS84 CRS instances

- modules/library/main/src/main/java/org/geotools/feature/FeatureTypes.java
- modules/library/main/src/test/java/org/geotools/feature/FeatureTypesTest.java
[![GEOT-7331](https://badgen.net/badge/JIRA/GEOT-7331/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7331) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4233
> [Backport 27.x] [GEOT-7331] ContentFeatureSource reprojection requirement check fails to resolve to false with two WGS84 CRS instances

- docs/user/library/data/wfs-ng.rst
- modules/library/http/src/test/java/org/geotools/http/MockHttpClient.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSource.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentDataAccess.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSDataAccessFactory.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/ComplexGetFeatureResponse.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSContentComplexFeatureCollection.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/AbstractGetFeatureResponseParserFactory.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/ComplexGetFeatureResponseParserFactory.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/GetFeatureResponseParserFactory.java
- modules/unsupported/wfs-ng/src/main/resources/META-INF/services/org.geotools.data.wfs.internal.WFSResponseFactory
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/TestHttpClient.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSourceTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/WFSClientTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/KartverketStedsnavnDataStoreOnlineTest.java
[![GEOT-7323](https://badgen.net/badge/JIRA/GEOT-7323/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7323) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backporting three issues on the 28.x branch.
> GEOT-7323 Backport some wfs issues to 28.x

- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaFilterToSQL.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaFilterToSqlTest.java
[![GEOT-7318](https://badgen.net/badge/JIRA/GEOT-7318/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7318) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4215
> [Backport 29.x] [GEOT-7318] Unit of measure not escaped in DWithin filter

- modules/library/main/pom.xml
- modules/library/main/src/main/java/org/geotools/geometry/jts/CircularArc.java
- modules/library/main/src/test/java/org/geotools/geometry/jts/CircularArcTest.java
[![GEOT-7333](https://badgen.net/badge/JIRA/GEOT-7333/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7333) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4244
> [Backport 29.x] [GEOT-7333] The result of linearization after creating circulararc is wrong

- modules/library/main/pom.xml
- modules/library/main/src/main/java/org/geotools/geometry/jts/CircularArc.java
- modules/library/main/src/test/java/org/geotools/geometry/jts/CircularArcTest.java
[![GEOT-7333](https://badgen.net/badge/JIRA/GEOT-7333/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7333) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4244
> [Backport 28.x] [GEOT-7333] The result of linearization after creating circulararc is wrong

- modules/unsupported/flatgeobuf/pom.xml
> [Backport 29.x] Bump json from 20210307 to 20230227 in /modules/unsupported/flatgeobuf

- modules/unsupported/flatgeobuf/pom.xml
> [Backport 28.x] Bump json from 20210307 to 20230227 in /modules/unsupported/flatgeobuf

- modules/unsupported/flatgeobuf/pom.xml
> [Backport 26.x] Bump json from 20210307 to 20230227 in /modules/unsupported/flatgeobuf

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/ComplexGetFeatureResponse.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSContentComplexFeatureCollection.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlComplexFeatureParser.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSourceTest.java
[![GEOT-7322](https://badgen.net/badge/JIRA/GEOT-7322/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7322) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The constructor that takes a filter is used by the subCollection function. This will only be used by the old methods, that are supposed to go away.
This change will set that filter on the parser in the same manner as the old method.
> [GEOT-7322] WFSContentComplexFeatureCollection.subCollection doesn't use the filter

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
[![GEOT-7340](https://badgen.net/badge/JIRA/GEOT-7340/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7340) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fixes an annoying exception in static part of class initialization when using ImageMosaic.
Related to class loading of javax.xml.bind.JAXBException, and how this is treated in it.geosolutions.imageio.pam.PAMParser.
Not sure how to write a test case for this one.
> [GEOT-7340] Avoid PAMParser init causing ImageMosaic to fail

- docs/developer/conventions/code/code.rst
- docs/developer/conventions/code/urlchecker.rst
- docs/user/library/main/index.rst
- docs/user/library/main/urlchecker.rst
- modules/extension/mbstyle/src/main/java/org/geotools/mbstyle/sprite/SpriteGraphicFactory.java
- modules/extension/mbstyle/src/test/java/org/geotools/mbstyle/sprite/SpriteGraphicFactoryMockTest.java
- modules/library/main/src/main/java/org/geotools/data/ows/URLChecker.java
- modules/library/main/src/main/java/org/geotools/data/ows/URLCheckerException.java
- modules/library/main/src/main/java/org/geotools/data/ows/URLCheckers.java
- modules/library/main/src/test/java/org/geotools/data/ows/MockURLChecker.java
- modules/library/main/src/test/java/org/geotools/data/ows/URLCheckersTest.java
- modules/library/render/pom.xml
- modules/library/render/src/main/java/org/geotools/renderer/style/ImageGraphicFactory.java
- modules/library/render/src/test/java/org/geotools/renderer/style/ImageGraphicFactoryTest.java
- modules/plugin/svg/pom.xml
- modules/plugin/svg/src/main/java/org/geotools/renderer/style/svg/RenderableSVGCache.java
- modules/plugin/svg/src/main/java/org/geotools/renderer/style/svg/SVGGraphicFactory.java
- modules/plugin/svg/src/test/java/org/geotools/renderer/style/svg/SVGGraphicFactoryTest.java
GeoTools side of [GSIP-218](https://github.com/geoserver/geoserver/wiki/GSIP-218)
> [GEOT-6512] Control remote HTTP requests sent by GeoTools

- modules/plugin/http-commons/src/main/java/org/geotools/http/commons/MultithreadedHttpClient.java
- modules/plugin/http-commons/src/test/java/org/geotools/http/commons/MultithreadedHttpClientTest.java
[![GEOT-10906](https://badgen.net/badge/JIRA/GEOT-10906/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-10906) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR aims to fix [GEOT-10906](https://osgeo-org.atlassian.net/browse/GEOT-7337) by harmonizing the behaviour of the gt-http-commons module, by preemptively sending a basic authentication, if authentication is provided.  
> [GEOT-10906] Authentication not sent if connection pooling activated

- modules/plugin/http-commons/src/main/java/org/geotools/http/commons/MultithreadedHttpClient.java
- modules/plugin/http-commons/src/test/java/org/geotools/http/commons/MultithreadedHttpClientTest.java
[![GEOT-10906](https://badgen.net/badge/JIRA/GEOT-10906/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-10906) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4254
**Authored by:** @pmauduit
> [Backport 28.x] [GEOT-10906] Authentication not sent if connection pooling activated

- pom.xml
> [Backport 27.x] Bump sqlite-jdbc from 3.34.0 to 3.41.2.2

- pom.xml
> [Backport 28.x] Bump sqlite-jdbc from 3.34.0 to 3.41.2.2

- pom.xml
> [Backport 29.x] Bump sqlite-jdbc from 3.34.0 to 3.41.2.2

- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/library/main/src/main/java/org/geotools/data/util/DistanceBufferUtil.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisPSFilterToSql.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/AbstractFilterToMongo.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoCollectionMeta.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFilterSplitter.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoFilterSplitterTest.java
- modules/unsupported/jdbc-h2gis/src/main/java/org/h2gis/geotools/H2GISPSFilterToSql.java
[[GEOT-7360] DWITHIN support for mongo DB](https://osgeo-org.atlassian.net/browse/GEOT-7360)
Using DWITHIN in cql was executing operation in memory, instead of delegating it to mongoDB $near
Added support for DWITHIN for mongodb plugin
> Mongo DWITHIN implementation using $near

- pom.xml
[![GEOT-7373](https://badgen.net/badge/JIRA/GEOT-7373/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7373) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4307
> [Backport 27.x] [GEOT-7373] Bump hsqldb from 2.7.1 to 2.7.2

- pom.xml
[![GEOT-7373](https://badgen.net/badge/JIRA/GEOT-7373/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7373) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4307
> [Backport 28.x] [GEOT-7373] Bump hsqldb from 2.7.1 to 2.7.2

- modules/plugin/geopkg/src/main/resources/org/geotools/geopkg/gpkg_spatial_index.sql
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-7367](https://badgen.net/badge/JIRA/GEOT-7367/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7367) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4311
> [Backport 28.x] [GEOT-7367] Missing null-check in GeoPackage spatial index creation

- modules/plugin/geopkg/src/main/resources/org/geotools/geopkg/gpkg_spatial_index.sql
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-7367](https://badgen.net/badge/JIRA/GEOT-7367/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7367) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4311
> [Backport 29.x] [GEOT-7367] Missing null-check in GeoPackage spatial index creation

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/model/WMTSCapabilities.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/model/WMTSCapabilitiesTest.java
- modules/extension/wmts/src/test/resources/test-data/multilang.getcapa.xml
[![GEOT-7266](https://badgen.net/badge/JIRA/GEOT-7266/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7266) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
closes #4050 
This one with a test and an alternative way of handling abstracts.
> [GEOT-7266] WMTSCapabilities throws NPE for missing title

- docs/developer/conventions/code/code.rst
- docs/developer/conventions/code/urlchecker.rst
- docs/user/library/main/index.rst
- docs/user/library/main/urlchecker.rst
- modules/extension/mbstyle/src/main/java/org/geotools/mbstyle/sprite/SpriteGraphicFactory.java
- modules/extension/mbstyle/src/test/java/org/geotools/mbstyle/sprite/SpriteGraphicFactoryMockTest.java
- modules/library/main/src/main/java/org/geotools/data/ows/URLChecker.java
- modules/library/main/src/main/java/org/geotools/data/ows/URLCheckerException.java
- modules/library/main/src/main/java/org/geotools/data/ows/URLCheckers.java
- modules/library/main/src/test/java/org/geotools/data/ows/MockURLChecker.java
- modules/library/main/src/test/java/org/geotools/data/ows/URLCheckersTest.java
- modules/library/render/pom.xml
- modules/library/render/src/main/java/org/geotools/renderer/style/ImageGraphicFactory.java
- modules/library/render/src/test/java/org/geotools/renderer/style/ImageGraphicFactoryTest.java
- modules/plugin/svg/pom.xml
- modules/plugin/svg/src/main/java/org/geotools/renderer/style/svg/RenderableSVGCache.java
- modules/plugin/svg/src/main/java/org/geotools/renderer/style/svg/SVGGraphicFactory.java
- modules/plugin/svg/src/test/java/org/geotools/renderer/style/svg/SVGGraphicFactoryTest.java
> [Backport 28.x] [GEOT-6512] Control remote HTTP requests sent by GeoTools

- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Encoder.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/PullParser.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/ParserHandler.java
- modules/library/main/src/main/java/org/geotools/data/store/ContentFeatureCollection.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/GetFeatureRequest.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/GetFeatureResponseParserFactory.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/PullParserFeatureReader.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XsdHttpHandler.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/parsers/AbstractGetFeatureParserTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/parsers/PullParserTest.java
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/internal/parsers/test-data/Mjosovervak_stations.xsd
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/internal/parsers/test-data/wfs_get_feature.xml
[![GEOT-7365](https://badgen.net/badge/JIRA/GEOT-7365/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7365) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Injecting HTTPClient into XSD handling to take advantage of any configuration set in WFSDataStore or proxy setting.
In addition made some changes to the exception's thrown, and the exception that is passed if fetching the schema fails.
> [GEOT-7365] Problems with requesting Features from a WFS Version 2.0.0 and using a HTTP proxy

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/catalog/CatalogConfigurationBean.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/GranuleDescriptorTest.java
[![GEOT-7372](https://badgen.net/badge/JIRA/GEOT-7372/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7372) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Using equals instead of == to check strings.
Wonder if this functionality should be placed somewhere else, or exists, but haven't found a suitable class.
> [GEOT-7372] ImageMosaic SuggestedSPI ignored by GranuleDescriptor

- modules/library/main/src/main/java/org/geotools/data/ows/URLChecker.java
- modules/library/main/src/main/java/org/geotools/data/ows/URLCheckers.java
- modules/library/main/src/test/java/org/geotools/data/ows/URLCheckersTest.java
This is a follow up to https://github.com/geoserver/geoserver/pull/6916 which highlighted the need to account for normalization of locations prior to checking.
URLChecker.normalize(location) is introduced to:
- remove any redundant current directory or parent directory references.
- Converts ``file:/path`` locations to ``file:///path`` representation.
> [GEOT-6512] URLCheckers normalize location

- modules/extension/app-schema/app-schema/pom.xml
> [Backport 29.x] Bump jetty-server from 9.4.48.v20220622 to 9.4.51.v20230217 in /modules/extension/app-schema/app-schema

- modules/extension/app-schema/app-schema/pom.xml
> [Backport 28.x] Bump jetty-server from 9.4.48.v20220622 to 9.4.51.v20230217 in /modules/extension/app-schema/app-schema

- modules/unsupported/s3-geotiff/pom.xml
- modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/S3Connector.java
> [Backport 28.x] Bump aws-java-sdk-s3 from 1.11.36 to 1.12.261 in /modules/unsupported/s3-geotiff

- modules/unsupported/s3-geotiff/pom.xml
- modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/S3Connector.java
> [Backport 29.x] Bump aws-java-sdk-s3 from 1.11.36 to 1.12.261 in /modules/unsupported/s3-geotiff

- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java
This PR just fixes a WMTS unit test that is failing on main and other branches. It appears to be a change in how the server that the test is connecting to responds to a WMTS GetCapabilities request that is a REST request with the KVP parameters.  The previous PR had a typo and wasn't picking up the fix for some reason.
> Fix failing WMTS unit test

- modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/FESParseEncodeUtil.java
- modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/MeasureTypeBinding.java
- modules/extension/xsd/xsd-fes/src/test/java/org/geotools/filter/v2_0/bindings/DWithinBindingTest.java
[![GEOT-7383](https://badgen.net/badge/JIRA/GEOT-7383/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7383) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4352
> [Backport 29.x] [GEOT-7383] Distance element of DWithin filter should have an attribute "uom"

- modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/FESParseEncodeUtil.java
- modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/MeasureTypeBinding.java
- modules/extension/xsd/xsd-fes/src/test/java/org/geotools/filter/v2_0/bindings/DWithinBindingTest.java
[![GEOT-7383](https://badgen.net/badge/JIRA/GEOT-7383/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7383) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4352
> [Backport 28.x] [GEOT-7383] Distance element of DWithin filter should have an attribute "uom"

- docs/site/update_site.sh
29.x Backport of #3995
docs.geotools.org will be switching over to the new site later today, and this will be needed to support the [29.x docbuild](https://build.geoserver.org/view/geotools/job/geotools-29.x-docs/)
> Geotools doc migration 29.x backport

- docs/site/update_site.sh
So, for some reason, geotools-28.x-docs [fails on the new version of  update_site.sh](https://build.geoserver.org/view/geotools/job/geotools-28.x-docs/92/console): 
```
+ ssh -oStrictHostKeyChecking=no -p 2223 geotools@geo-docs.geoserver.org cd  /var/www/geotools/docs/maintenance/../ && ./update_site.sh maintenance
Usage ./update_site.sh <stable|latest>
```
However, the code that appears to be the culprit hasn't been changed since at least 2011.
The old maintenance builds were [working fine passing in maintenance](https://build.geoserver.org/view/geotools/job/geotools-28.x-docs/91/console), so I can only surmise we've been using an even older version of the script, or one with uncommitted changes, for the past several years. 
Does anyone have more insight into this? If there's another …
> GeoTools docbuild - support maintenance (again?) (28.x)

- docs/site/update_site.sh
Forwardport of #4383
This change technically won't become relevant until 30.x moves to maintenance.
> GeoTools docbuild - support maintenance (main)

- modules/extension/wms/pom.xml
- modules/library/http/pom.xml
- modules/library/main/pom.xml
- modules/library/main/src/test/java/org/geotools/filter/CapabilitiesTest.java
- modules/library/main/src/test/java/org/geotools/filter/function/ListFunctionsTest.java
- modules/library/main/src/test/java/org/geotools/temporal/object/DefaultDateAndTimeTest.java
- modules/plugin/http-commons/pom.xml
- modules/unsupported/stac-store/pom.xml
- pom.xml
[![GEOT-7396](https://badgen.net/badge/JIRA/GEOT-7396/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7396) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4391
> [Backport 29.x] [GEOT-7396] Upgrade wiremock to 2.35.0

- modules/extension/wms/pom.xml
- modules/library/http/pom.xml
- modules/library/main/pom.xml
- modules/library/main/src/test/java/org/geotools/filter/CapabilitiesTest.java
- modules/library/main/src/test/java/org/geotools/filter/function/ListFunctionsTest.java
- modules/library/main/src/test/java/org/geotools/temporal/object/DefaultDateAndTimeTest.java
- modules/plugin/http-commons/pom.xml
- modules/unsupported/stac-store/pom.xml
- pom.xml
[![GEOT-7396](https://badgen.net/badge/JIRA/GEOT-7396/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7396) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4391
> [Backport 28.x] [GEOT-7396] Upgrade wiremock to 2.35.0

- modules/unsupported/flatgeobuf/pom.xml
This patch release upgrade fixes a performance issue in spatial index search, see https://github.com/flatgeobuf/flatgeobuf/issues/274.
> Upgrade flatgeobuf to  3.26.1

- modules/library/main/src/main/java/org/geotools/feature/NameImpl.java
- modules/library/main/src/test/java/org/geotools/feature/NameImplTest.java
[![GEOT-7416](https://badgen.net/badge/JIRA/GEOT-7416/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7416) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Avoid creating garbage objects (StringBuffer/String) when comparing to another NameImpl, by comparing the namespace URI and the localPart separatedly.
> [GEOT-7416] org.geotools.feature.NameImpl.compareTo creates garbage objects

- modules/library/main/src/main/java/org/geotools/feature/NameImpl.java
- modules/library/main/src/test/java/org/geotools/feature/NameImplTest.java
[![GEOT-7416](https://badgen.net/badge/JIRA/GEOT-7416/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7416) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4416
**Authored by:** @groldan
> [Backport 29.x] [GEOT-7416] org.geotools.feature.NameImpl.compareTo creates garbage objects

- docs/user/library/data/elasticsearch.rst
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticDataStore.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticDataStoreFactory.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/RestElasticClient.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticDataStoreFactoryIT.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticDataStoreFinderIT.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticDataStoreIT.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticTestSupport.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/RestElasticClientTest.java
[![GEOT-7418](https://badgen.net/badge/JIRA/GEOT-7418/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7418) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4431
> [Backport 28.x] [GEOT-7418] Add a configuration parameter to the ElasticSearch plugin to support response greater than 100mb

- docs/user/library/data/elasticsearch.rst
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticDataStore.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticDataStoreFactory.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/RestElasticClient.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticDataStoreFactoryIT.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticDataStoreFinderIT.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticDataStoreIT.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticTestSupport.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/RestElasticClientTest.java
[![GEOT-7418](https://badgen.net/badge/JIRA/GEOT-7418/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7418) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4431
> [Backport 29.x] [GEOT-7418] Add a configuration parameter to the ElasticSearch plugin to support response greater than 100mb

- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
[![GEOT-7425](https://badgen.net/badge/JIRA/GEOT-7425/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7425) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket. Documentation updates here: https://github.com/geoserver/geoserver/pull/7077
> [GEOT-7425] Add support for extended colorMap in CSS

- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
[![GEOT-7425](https://badgen.net/badge/JIRA/GEOT-7425/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7425) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4434
> [Backport 28.x] [GEOT-7425] Add support for extended colorMap in CSS

- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
[![GEOT-7425](https://badgen.net/badge/JIRA/GEOT-7425/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7425) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4434
> [Backport 29.x] [GEOT-7425] Add support for extended colorMap in CSS

- modules/unsupported/elasticsearch/pom.xml
> [Backport 29.x] Bump org.springframework.security:spring-security-core to 5.7.10

- modules/unsupported/elasticsearch/pom.xml
> [Backport 28.x] Bump org.springframework.security:spring-security-core to 5.7.10

- pom.xml
> [Backport 29.x] Bump `batik.version` from 1.16 to 1.17

- pom.xml
> [Backport 28.x] Bump `batik.version` from 1.16 to 1.17

- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7427](https://badgen.net/badge/JIRA/GEOT-7427/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7427) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
…exclusively granule or index fields
cleanup
> [GEOT-7427] Vector Mosaic add native filtering support when query is exclusively granule or index fields

- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7427](https://badgen.net/badge/JIRA/GEOT-7427/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7427) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4455
> [Backport 29.x] [GEOT-7427] Vector Mosaic add native filtering support when query is exclusively granule or index fields

- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7427](https://badgen.net/badge/JIRA/GEOT-7427/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7427) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4455
> [Backport 28.x] [GEOT-7427] Vector Mosaic add native filtering support when query is exclusively granule or index fields

- modules/library/xml/src/main/java/org/geotools/xml/gml/FCBuffer.java
[![GEOT-7437](https://badgen.net/badge/JIRA/GEOT-7437/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7437) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
JEP 361 (Switch expression - https://openjdk.org/jeps/361) makes `yield` into a restricted identifier.
The JEP says:
>  If there is a unary method yield in scope, then the expression yield(x) would be ambiguous (could be either a method call, or a yield statement whose operand is a parenthesized expression), and this ambiguity is resolved in favor of the yield statement. If the method invocation is preferred then the method …
> [GEOT-7437] Avoid use of yield keyword for JDK 17 compatibility

- pom.xml
[![GEOT-7442](https://badgen.net/badge/JIRA/GEOT-7442/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7442) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Changes to file `pom.xml` to make `ErrorProne` run on Windows, where file names, including `${project.build.directory}`, contain backslashes.
- [N/A] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [N/A] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has …
> [GEOT-7442] Make ErrorProne run on Windows

- modules/unsupported/javafx/src/test/java/org/geotools/javafx/FXMapTest.java
- pom.xml
[![GEOT-7443](https://badgen.net/badge/JIRA/GEOT-7443/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7443) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The build system has a JDK11Test profile. AFAICT (and it looks like I was the one that added it about three years ago - don't really remember it though), that isn't actually JDK 11 though - its really "not JDK 8" or "JDK 11 or later".
- [N/A] [Documentation](https://github.com/geotools/geotools/tree/main/docs) has been updated (if …
> [GEOT-7443] Remove JDK 11 profile and rename associated JDK 11 Test

- modules/library/http/pom.xml
- modules/library/http/src/main/java/org/geotools/http/DelegateHTTPClient.java
- modules/library/http/src/main/java/org/geotools/http/HTTPClient.java
- modules/library/http/src/main/java/org/geotools/http/LoggingHTTPClient.java
- modules/library/http/src/main/java/org/geotools/http/SimpleHttpClient.java
- modules/library/http/src/test/java/org/geotools/http/DefaultHTTPClientFactoryTest.java
- modules/library/http/src/test/java/org/geotools/http/SimpleHttpClientTest.java
- modules/library/main/src/main/java/org/geotools/data/ows/AbstractOpenWebService.java
- modules/plugin/http-commons/src/main/java/org/geotools/http/commons/MultithreadedHttpClient.java
- modules/plugin/http-commons/src/test/java/org/geotools/http/commons/MultithreadedHttpClientTest.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSDataAccessFactory.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSConfig.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/WFSClientTest.java
[![GEOT-7431](https://badgen.net/badge/JIRA/GEOT-7431/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7431) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
From [GEOT-7431](https://osgeo-org.atlassian.net/browse/GEOT-7431): 
GeoTools WFS-Client should support sending custom HTTP request headers for GET and POST requests.
This is useful for various scenarios, for example for sending custom authentication and authorization headers (bearer tokens etc).
This includes the following tasks:
WFSClient inherits an headers field already, but there is no way to init -> provide further …
> [GEOT-7431] Support custom HTTP headers for WFS-Client and HTTP-Client

- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaGeographyOnlineTest.java
[![GEOT-7444](https://badgen.net/badge/JIRA/GEOT-7444/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7444) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4484
> [Backport 28.x] [GEOT-7444] HanaGeographyOnlineTest.testBounds is failing in CI

- .github/workflows/integration.yml
[![GEOT-7287](https://badgen.net/badge/JIRA/GEOT-7287/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7287) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
During the remove-opengis activity we setup extended integration tests that made use of an ant script update a selection of downstream projects that had setup branches to test with GeoTools SNAPSHOT jars. Now that 30-RC is out, and the downstream projects have completed their api refactor these additional checks are no longer needed.
This is a build change and does not warrant its own JIRA issue.
Now that this activity is …
> [GEOT-7287] integration check no longer requires the remove-opengis.xml api refactor

- modules/unsupported/jdbc-teradata/src/main/java/org/geotools/data/teradata/TeradataDataStoreFactory.java
- modules/unsupported/jdbc-teradata/src/main/java/org/geotools/data/teradata/WKBAttributeIO.java
[![GEOT-7463](https://badgen.net/badge/JIRA/GEOT-7463/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7463) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Part of https://osgeo-org.atlassian.net/browse/GEOT-7447, this just addresses the teradata JDBC module.
No code changes
> [GEOT-7463] Fix javadoc in teradata unsupported module

- modules/library/sample-data/src/main/java/org/geotools/TestData.java
[![GEOT-7464](https://badgen.net/badge/JIRA/GEOT-7464/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7464) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Part of https://osgeo-org.atlassian.net/browse/GEOT-7447, this just addresses the sample-data module.
No code changes.
> [GEOT-7464] Fix javadoc in sample data module

- modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/bindings/GML2EncodingUtils.java
- modules/extension/xsd/xsd-gml2/src/test/java/org/geotools/gml2/bindings/GML2EncodingUtilsTest.java
[![GEOT-7465](https://badgen.net/badge/JIRA/GEOT-7465/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7465) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket. Found by community testing of GeoServer 2.24-RC
> [GEOT-7465] GML2EncodingUtils.toURI fails with the Web Service authority

- modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/bindings/GML2EncodingUtils.java
- modules/extension/xsd/xsd-gml2/src/test/java/org/geotools/gml2/bindings/GML2EncodingUtilsTest.java
[![GEOT-7465](https://badgen.net/badge/JIRA/GEOT-7465/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7465) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4502
> [Backport 30.x] [GEOT-7465] GML2EncodingUtils.toURI fails with the Web Service authority

- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java
- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7429](https://badgen.net/badge/JIRA/GEOT-7429/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7429) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
…xclusively granule or index fields
clean
> [GEOT-7429] Vector Mosaic add native retyping support when query is exclusively granule or index fields

- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java
- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7429](https://badgen.net/badge/JIRA/GEOT-7429/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7429) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4459
> [Backport 30.x] [GEOT-7429] Vector Mosaic add native retyping support when query is exclusively granule or index fields

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java
[![GEOT-7458](https://badgen.net/badge/JIRA/GEOT-7458/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7458) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4497
> [Backport 30.x] [GEOT-7458] JDBCDataStore: Unique visitor not always compatible with sortBy

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java
[![GEOT-7458](https://badgen.net/badge/JIRA/GEOT-7458/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7458) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4497
> [Backport 29.x] [GEOT-7458] JDBCDataStore: Unique visitor not always compatible with sortBy

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java
[![GEOT-7458](https://badgen.net/badge/JIRA/GEOT-7458/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7458) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4497
> [Backport 28.x] [GEOT-7458] JDBCDataStore: Unique visitor not always compatible with sortBy

- modules/unsupported/swing/src/main/java/org/geotools/swing/AbstractMapPane.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/JMapFrame.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/MapLayerTable.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/MapPane.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/data/JFileDataStoreChooser.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/data/JParameterListWizard.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/dialog/JAboutDialog.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/event/MapPaneKeyHandler.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/tool/InfoToolHelper.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/tool/InfoToolHelperUtils.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/tool/PanTool.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/tool/ZoomInTool.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/tool/ZoomOutTool.java
[![GEOT-7461](https://badgen.net/badge/JIRA/GEOT-7461/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7461) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Part of https://osgeo-org.atlassian.net/browse/GEOT-7447, this just addresses the swing module.
No code changes.
> [GEOT-7461] Fix javadoc in swing module

- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/FilterToElastic.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFeatureFilterIT.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFilterTest.java
- modules/unsupported/geojson-core/src/main/java/com/bedatadriven/jackson/datatype/jts/JtsModule.java
- modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java
- modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
- modules/unsupported/geojson-store/src/test/java/org/geotools/data/geojson/store/AxisOrderTest.java
- modules/unsupported/geojson-store/src/test/java/org/geotools/data/geojson/store/GeoJSONWriteTest.java
[![GEOT-7434](https://badgen.net/badge/JIRA/GEOT-7434/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7434) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4513
> [Backport 30.x] [GEOT-7434] ElasticSearch throws repeated point exceptions on small bbox filters

- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/FilterToElastic.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFeatureFilterIT.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFilterTest.java
- modules/unsupported/geojson-core/src/main/java/com/bedatadriven/jackson/datatype/jts/JtsModule.java
- modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java
- modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
- modules/unsupported/geojson-store/src/test/java/org/geotools/data/geojson/store/AxisOrderTest.java
- modules/unsupported/geojson-store/src/test/java/org/geotools/data/geojson/store/GeoJSONWriteTest.java
[![GEOT-7434](https://badgen.net/badge/JIRA/GEOT-7434/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7434) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4513
> [Backport 29.x] [GEOT-7434] ElasticSearch throws repeated point exceptions on small bbox filters

- modules/library/cql/src/main/jjtree/ECQLGrammar.jjt
- modules/library/cql/src/test/java/org/geotools/filter/text/cql2/CQLAttributeNameTest.java
- modules/library/cql/src/test/java/org/geotools/filter/text/ecql/ECQLAttributeNameTest.java
[![GEOT-7487](https://badgen.net/badge/JIRA/GEOT-7487/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7487) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Update the ECQL grammar to allow spaces in attribute names.
Changes the definition of `ANY` to not disallow spaces, but only  backslashes.
> [GEOT-7487] Allow ECQL to parse attribute names with spaces

- modules/library/xml/src/main/java/org/geotools/xml/transform/TransformerBase.java
- modules/library/xml/src/test/java/org/geotools/xml/styling/SLDTransformerTest.java
[![GEOT-7486](https://badgen.net/badge/JIRA/GEOT-7486/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7486) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fix now produces
`<ogc:Literal><![CDATA[ ]]></ogc:Literal>`
instead of the problematic `<ogc:Literal> </ogc:Literal>`
> [GEOT-7486] CSS literal single space squashed to empty string

- modules/library/xml/src/main/java/org/geotools/xml/transform/TransformerBase.java
- modules/library/xml/src/test/java/org/geotools/xml/styling/SLDTransformerTest.java
[![GEOT-7486](https://badgen.net/badge/JIRA/GEOT-7486/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7486) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4537
**Authored by:** @petersmythe
> [Backport 30.x] [GEOT-7486] CSS literal single space squashed to empty string

- modules/library/main/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope.java
- modules/library/main/src/test/java/org/geotools/geometry/jts/ReferencedEnvelopeTest.java
[![GEOT-7485](https://badgen.net/badge/JIRA/GEOT-7485/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7485) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Checked the following:
> [GEOT-7485] Double Check ReferencedEnvelope against Rectangle2D.Double() expectations

- docs/user/welcome/upgrade.rst
Small fix for documentation: Packages mentioned in upgrade guide for GT 30.x:
https://docs.geotools.org/stable/userguide/welcome/upgrade.html#geotools-30-x
I have not created a JIRA issue for this.
- [ x ] I have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md).
- [ x ] I have sent a [Contribution Licence Agreement](https://docs.geotools.org/latest/developer/procedures/contribution_license.html) (not required for small changes, e.g., fixing typos in documentation).
- [ x ] First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
- [ x ] Avoid [Java 9+ split packages](http://tutorials.jenkov.com/java/modules.html#split-packages-not-allowed).
- [ x ] All the build checks are green ([see automated QA …
> Docs: Fix package ordering in GT 30x upgrade guide

- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/IntersectionFeatureCollection.java
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/IntersectionFeatureCollectionTest.java
> [Backport 30.x] [GEOT-7490] WPS Intersection NPE when the Return Value Should be a Point

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureSource.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreSetGeometryFactoryTest.java
[![GEOT-7491](https://badgen.net/badge/JIRA/GEOT-7491/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7491) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Use `GeometryFactory` of the `ShapeFileDataStore` if there is one and the `Query` has none.
> [GEOT-7491] ShapeFileDataStore should use GeometryFactory of DataStore

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureSource.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreSetGeometryFactoryTest.java
[![GEOT-7491](https://badgen.net/badge/JIRA/GEOT-7491/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7491) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4552
**Authored by:** @bestrauss
> [Backport 30.x] [GEOT-7491] ShapeFileDataStore should use GeometryFactory of DataStore

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureSource.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreSetGeometryFactoryTest.java
[![GEOT-7491](https://badgen.net/badge/JIRA/GEOT-7491/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7491) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4552
**Authored by:** @bestrauss
> [Backport 29.x] [GEOT-7491] ShapeFileDataStore should use GeometryFactory of DataStore

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureSource.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreSetGeometryFactoryTest.java
[![GEOT-7491](https://badgen.net/badge/JIRA/GEOT-7491/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7491) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4552
**Authored by:** @bestrauss
> [Backport 28.x] [GEOT-7491] ShapeFileDataStore should use GeometryFactory of DataStore

- modules/unsupported/flatgeobuf/pom.xml
- modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
This patch release upgrade fixes an issue that spatial index search on FlatGeobuf produces a result with wrong feature ids.  It also adds a test cases that reproduces the issue and verifies the fix.
See https://github.com/flatgeobuf/flatgeobuf/pull/334.
> Upgrade flatgeobuf to 3.26.2

- pom.xml
[![GEOT-7498](https://badgen.net/badge/JIRA/GEOT-7498/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7498) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4564
> [Backport 29.x] [GEOT-7498] Upgrade DB2 JDBC driver from 11.5.6.0 to 11.5.9.0

- pom.xml
> [Backport 28.x] Bump ch.qos.logback:logback-classic from 1.2.11 to 1.3.12

- release/src/it/logback/pom.xml
> [Backport 30.x] Bump ch.qos.logback:logback-classic from 1.2.11 to 13.12 in /release/src/it/logback

- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java
- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7507](https://badgen.net/badge/JIRA/GEOT-7507/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7507) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4595
> [Backport 30.x] [GEOT-7507] Vector mosaic store: filtering is not working if it uses a property that's not retrieved by the query

- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7508](https://badgen.net/badge/JIRA/GEOT-7508/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7508) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4597
> [Backport 29.x] [GEOT-7508] Optimize execution of NearestVisitor in Vector Mosaic store

- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7508](https://badgen.net/badge/JIRA/GEOT-7508/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7508) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4597
> [Backport 30.x] [GEOT-7508] Optimize execution of NearestVisitor in Vector Mosaic store

- .github/workflows/linux_jdk21.yml
- modules/extension/ysld/src/test/java/org/geotools/ysld/TestUtils.java
- modules/library/coverage/src/main/java/org/geotools/coverage/CategoryList.java
- modules/library/coverage/src/test/java/org/geotools/coverage/CategoryListTest.java
- modules/unsupported/vsi/pom.xml
- pom.xml
Pairs with https://github.com/geoserver/geoserver/pull/7207
Notes:
- Seems to be just enough to build with Java 21
- One cannot run the QA Profile with Java 21 (but it's not possible with Java 17 either, see notes in the [ErrorProne documentation](https://errorprone.info/docs/installation))
- Add a new Java 21 build (classic way, if the duplication annoys @jodygarnett, further PRs to clean the actions code are welcomed).
> Java 21 build support

- modules/library/main/src/main/java/org/geotools/filter/IsEqualsToImpl.java
- modules/library/main/src/test/java/org/geotools/filter/IsEqualsToImplTest.java
[![GEOT-7514](https://badgen.net/badge/JIRA/GEOT-7514/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7514) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4618
> [Backport 30.x] [GEOT-7514] PropertyIsEqualTo fails to compare true and Boolean.TRUE, when both are literals

- modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/RuleBuilder.java
- modules/extension/brewer/src/test/java/org/geotools/brewer/styling/builder/StyleBuilderTest.java
- modules/library/xml/src/main/java/org/geotools/xml/styling/SLDParser.java
- modules/library/xml/src/test/java/org/geotools/xml/styling/SLDParserTest.java
[![GEOS-11249](https://badgen.net/badge/JIRA/GEOS-11249/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11249) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR aims at resolving two issues with the i18n of legend titles (and abstracts) in SLD:
The i18n does not work anymore since the org.opengis refactor as GeoServer now uses the StyleBuilder (https://github.com/geoserver/geoserver/blob/c2f437acb46d5fd4a487be8c6a44a76cc9428934/src/main/src/main/java/org/geoserver/catalog/ResourcePool.java#L2216). I thought it made sense to use InternationalString for rule title and abstract …
> [GEOT-7518, GEOT-7519] Fix i18n in legend rules

- pom.xml
> [Backport 30.x] Bump com.jayway.jsonpath:json-path from 2.7.0 to 2.9.0

- docs/user/unsupported/css.rst
- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
[![GEOT-7521](https://badgen.net/badge/JIRA/GEOT-7521/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7521) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
With this commit a new directive "styleName" is supported, if the directive is specified then the resulting style will have the given name
> [GEOT-7521] Use style_body to define CSS style for a layer

- docs/user/unsupported/css.rst
- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
[![GEOT-7521](https://badgen.net/badge/JIRA/GEOT-7521/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7521) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4631
**Authored by:** @mirco-romagnoli
> [Backport 30.x] [GEOT-7521] Use style_body to define CSS style for a layer

- docs/user/unsupported/css.rst
- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
[![GEOT-7521](https://badgen.net/badge/JIRA/GEOT-7521/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7521) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4631
**Authored by:** @mirco-romagnoli
> [Backport 29.x] [GEOT-7521] Use style_body to define CSS style for a layer

- modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/FeatureTypeHandler.java
- modules/unsupported/geojson/src/test/java/org/geotools/geojson/FeatureJSONTest.java
[![GEOT-7513](https://badgen.net/badge/JIRA/GEOT-7513/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7513) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
PR to solve [this issue]. My usecase is processing .geojson files in which a column can be of type Long or Double. Currently, the FeatureTypeHandler throws an `IllegalStateException : Found conflicting types Double and Long` for property after processing Long -> Double -> Long again.
I am adding via this PR a fix, and a modified test to ensure that when you encounter Long, Double then Long, no exception is thrown.
For core and …
> [GEOT-7513] FeatureTypeHandler handle conflicting types Double and Long

- .github/workflows/linux_jdk11.yml
- .github/workflows/linux_jdk17.yml
- pom.xml
> [Backport 29.x] Bump com.jayway.jsonpath:json-path from 2.7.0 to 2.9.0

- .github/workflows/macos.yml
> [Backport 30.x] Remove GDAL from OSX, brew install is not working anymore

- .github/workflows/macos.yml
> [Backport 29.x] Remove GDAL from OSX, brew install is not working anymore

- modules/unsupported/jdbc-h2gis/src/test/java/org/h2gis/geotools/H2GISDataStoreFactoryTest.java
Fix for build failures on the build server, due to usage of a file that does not get cleaned with "mvn clean" (one test database is placed in the module root, rather than in "target").
> Make sure the test is not creating a database in the module root, where the mvn clean will not delete it

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/GeometryColumnEncoder.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisSimplifiedGeometryTest.java
[![GEOS-11256](https://badgen.net/badge/JIRA/GEOS-11256/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11256) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This is a PR for [GEOT-7526](https://osgeo-org.atlassian.net/browse/GEOT-7526)
When the method ``org.geotools.data.postgis.GeometryColumnEncoder.getTWKBDigits`` is called with 0.0 as distance, a weird case appears: ``-Integer.MIN_VALUE`` is computed but the result is still ``Integer.MIN_VALUE``. Therefore, the returned value is -7 instead of +7.
This change addresses that case.
> [GEOS-11256] getTWKBDigits should return 7 instead of -7 for 0 distance.

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/GeometryColumnEncoder.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisSimplifiedGeometryTest.java
[![GEOS-11256](https://badgen.net/badge/JIRA/GEOS-11256/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11256) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4655
**Authored by:** @iaunzu
> [Backport 30.x] [GEOS-11256] getTWKBDigits should return 7 instead of -7 for 0 distance.

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/GeometryColumnEncoder.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisSimplifiedGeometryTest.java
[![GEOS-11256](https://badgen.net/badge/JIRA/GEOS-11256/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11256) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4655
**Authored by:** @iaunzu
> [Backport 29.x] [GEOS-11256] getTWKBDigits should return 7 instead of -7 for 0 distance.

- pom.xml
> [Backport 29.x] Bump org.postgresql:postgresql from 42.6.0 to 42.7.2

- pom.xml
> [Backport 28.x] Bump org.postgresql:postgresql from 42.6.0 to 42.7.2

- modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java
- modules/library/render/src/test/java/org/geotools/renderer/GeneralizationDistanceTest.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java
[![GEOT-7527](https://badgen.net/badge/JIRA/GEOT-7527/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7527) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Details and rationale in the Jira ticket description.
> [GEOT-7527] StreamingRenderer can ask stores to simplify geometries with a distance of 'zero'

- docs/user/build/faq.rst
This updates the documentation in the FAQ for creating an executable JAR to the maven 3.5.1 shade plugin, adding likely needed transformers/filters
> Update docs on maven shade plugin to 3.5.1

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/XPath.java
- modules/library/main/src/main/java/org/geotools/feature/ComplexAttributeImpl.java
- modules/library/main/src/main/java/org/geotools/feature/PropertyImpl.java
[![GEOT-7411](https://badgen.net/badge/JIRA/GEOT-7411/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7411) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
While building a complex attribute with a large sequence of children, XPath.set(...) incurs in a huge performance penalty due to excessive collections allocation and the inherent inefficiency of `ComplexAttributeImpl.getProperties(Name)` and
`ComplexAttributeImpl.setValue(Collection<Property>)`.
This is a pure refactoring patch on app-schema's `XPath` class, and the addition of the following non-api methods to gt-main's complex …
> [GEOT-7411] App-schema performance improvement in setting attribute values

- modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/GDALTestCase.java
[![GEOT-7532](https://badgen.net/badge/JIRA/GEOT-7532/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7532) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
As the javadocs says, the function TestData.file will throw exception on missing file. Therefore I use an alternative approach to check if the file test.zip exists.
> [GEOT-7532] GDALTestCase superfluous reports on missing test.zip

- modules/unsupported/swt/pom.xml
> [Backport 29.x] Bump org.eclipse.platform:org.eclipse.core.runtime from 3.23.0 to 3.29.0 in /modules/unsupported/swt

- modules/unsupported/swt/pom.xml
> [Backport 30.x] Bump org.eclipse.platform:org.eclipse.core.runtime from 3.23.0 to 3.29.0 in /modules/unsupported/swt

- modules/unsupported/swt/pom.xml
> [Backport 31.x] Bump org.eclipse.platform:org.eclipse.core.runtime from 3.23.0 to 3.29.0 in /modules/unsupported/swt

- modules/unsupported/swt/pom.xml
> [Backport 29.x] Bump org.eclipse.platform:org.eclipse.jface from 3.23.0 to 3.31.0 in /modules/unsupported/swt

- modules/unsupported/swt/pom.xml
> [Backport 30.x] Bump org.eclipse.platform:org.eclipse.jface from 3.23.0 to 3.31.0 in /modules/unsupported/swt

- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicGranule.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFilterTest.java
- modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data2/RoadSegmentsRepositoryFilter.properties
What the title says. The result is that the granule store typename and filter options are ignored.
> Vector mosaic: typename and filter not being loaded when property selection is active

- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicGranule.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFilterTest.java
- modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data2/RoadSegmentsRepositoryFilter.properties
> [Backport 30.x] Vector mosaic: typename and filter not being loaded when property selection is active

- docs/index/index.rst
[![GEOT-7539](https://badgen.net/badge/JIRA/GEOT-7539/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7539) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4679
**Authored by:** @DevDengChao
> [Backport 30.x] [GEOT-7539] The latest tutorials link is broken in https://docs.geotools.org/

- docs/index/index.rst
[![GEOT-7539](https://badgen.net/badge/JIRA/GEOT-7539/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7539) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4679
**Authored by:** @DevDengChao
> [Backport 31.x] [GEOT-7539] The latest tutorials link is broken in https://docs.geotools.org/

- modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONReader.java
- modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONReaderTest.java
- modules/unsupported/geojson-core/src/test/resources/org/geotools/data/geojson/test-data/geometrynull.json
[![GEOT-7534](https://badgen.net/badge/JIRA/GEOT-7534/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7534) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
`geometry:null` is valid geojson and since a missing `geojson` field is also accepted, this should be fine.
> [GEOT-7534] fix geojsonreader stops reading features if it encounters one with geometry=null

- modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONReader.java
- modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONReaderTest.java
- modules/unsupported/geojson-core/src/test/resources/org/geotools/data/geojson/test-data/geometrynull.json
[![GEOT-7534](https://badgen.net/badge/JIRA/GEOT-7534/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7534) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4668
**Authored by:** @oberhamsi
> [Backport 31.x] [GEOT-7534] fix geojsonreader stops reading features if it encounters one with geometry=null

- modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONReader.java
- modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONReaderTest.java
- modules/unsupported/geojson-core/src/test/resources/org/geotools/data/geojson/test-data/geometrynull.json
[![GEOT-7534](https://badgen.net/badge/JIRA/GEOT-7534/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7534) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4668
**Authored by:** @oberhamsi
> [Backport 30.x] [GEOT-7534] fix geojsonreader stops reading features if it encounters one with geometry=null

- modules/unsupported/elasticsearch/pom.xml
> [Backport 31.x] Bump org.springframework.security:spring-security-core from 5.7.10 to 5.7.12 in /modules/unsupported/elasticsearch

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSFeatureSource.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/AbstractWFSStrategy.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/GetFeatureRequest.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSStrategy.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/v2_0/StrictWFS_2_0_Strategy.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/AbstractWFSStrategyTest.java
[![GEOT-7540](https://badgen.net/badge/JIRA/GEOT-7540/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7540) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Previously, when the `GetFeatureRequest` contained both `startIndex` and `maxFeatures`, the response was empty if `maxFeatures < startIndex` due to the missing handling of the `startIndex` parameter. 
This issue impacted the retrieval of features, leading to unexpected behavior when querying for a subset of features.
This pull request addresses this issue by introducing proper handling of the `startIndex` parameter in the …
> [GEOT-7540] Added `startIndex` parameter handling for WFS feature reqs

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSFeatureSource.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/AbstractWFSStrategy.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/GetFeatureRequest.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSStrategy.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/v2_0/StrictWFS_2_0_Strategy.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/AbstractWFSStrategyTest.java
[![GEOT-7540](https://badgen.net/badge/JIRA/GEOT-7540/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7540) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4686
**Authored by:** @axl8713
> [Backport 31.x] [GEOT-7540] Added `startIndex` parameter handling for WFS feature reqs

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSFeatureSource.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/AbstractWFSStrategy.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/GetFeatureRequest.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSStrategy.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/v2_0/StrictWFS_2_0_Strategy.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/AbstractWFSStrategyTest.java
[![GEOT-7540](https://badgen.net/badge/JIRA/GEOT-7540/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7540) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport https://github.com/geotools/geotools/pull/4686
Authored by: @axl8713
> [Backport 30.x] [GEOT-7540] Added startIndex parameter handling for WFS feature reqs

- modules/extension/complex/src/main/java/org/geotools/data/complex/expression/FeaturePropertyAccessorFactory.java
- modules/library/main/src/main/java/org/geotools/filter/expression/SimpleFeaturePropertyAccessorFactory.java
- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicPostPreFilterSplitter.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFilterTest.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicReaderTest.java
[![GEOT-7553](https://badgen.net/badge/JIRA/GEOT-7553/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7553) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4714
> [Backport 30.x] [GEOT-7553] Vector mosaic store does not optimize filters using the default geometry name

- modules/extension/complex/src/main/java/org/geotools/data/complex/expression/FeaturePropertyAccessorFactory.java
- modules/library/main/src/main/java/org/geotools/filter/expression/SimpleFeaturePropertyAccessorFactory.java
- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicPostPreFilterSplitter.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFilterTest.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicReaderTest.java
[![GEOT-7553](https://badgen.net/badge/JIRA/GEOT-7553/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7553) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4714
> [Backport 31.x] [GEOT-7553] Vector mosaic store does not optimize filters using the default geometry name

- modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java
- modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
[![GEOT-7555](https://badgen.net/badge/JIRA/GEOT-7555/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7555) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Module: `gt-geojson-core`.
[[GEOT-7555](https://osgeo-org.atlassian.net/browse/GEOT-7555)] This is a small fix to `GeoJSONWriter`, to format `Date` using private member variable date formatter.
> [GEOT-7555] Use dateFormatter of GeoJSONWriter instead of the default one

- modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java
- modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
[![GEOT-7555](https://badgen.net/badge/JIRA/GEOT-7555/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7555) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4721
**Authored by:** @initialdmg
> [Backport 30.x] [GEOT-7555] Use dateFormatter of GeoJSONWriter instead of the default one

- modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java
- modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
[![GEOT-7555](https://badgen.net/badge/JIRA/GEOT-7555/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7555) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4721
**Authored by:** @initialdmg
> [Backport 31.x] [GEOT-7555] Use dateFormatter of GeoJSONWriter instead of the default one

- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/cv/CoordinateVariable.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/utilities/NetCDFUtilities.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/io/MemoryMappedFileCache.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/io/MemoryMappedRandomAccessFile.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/CoordinateVariableTest.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFBaseTest.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFBasicTest.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFMemoryMappedRandomAccessFileTest.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFMosaicReaderTest.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFPolyphemusTest.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFStationsTest.java
[![GEOT-7544](https://badgen.net/badge/JIRA/GEOT-7544/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7544) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Replaces https://github.com/geotools/geotools/pull/4706
> [GEOT-7544]:Adding MemoryMappedRandomAccessFile

- modules/library/metadata/src/main/java/org/geotools/util/RangeSet.java
The current GeoTools main branch shows a build error in Eclipse 2023-06 IDE with Java 11, and this is the recommended fix for it.
According to ChatGPT:
> In this line:
> 
> (Comparable<? super T>) is a bounded wildcard. It means that range.getMinValue() should be cast to something that is a superclass of T and is also comparable to that superclass.
> This ensures that you're casting range.getMinValue() to a type that is comparable to T or its superclasses. This can be important when T is not itself comparable, but its superclass is.
> Test Eclipse suggested fix

- modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/PAMResourceInfo.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicFileResourceInfo.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RATCollectorListener.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterManager.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicRATTest.java
- modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/bluetopo/BlueTopo_BH4JS577_20230918.tiff.small.aux.xml
[![GEOT-7563](https://badgen.net/badge/JIRA/GEOT-7563/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7563) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Useful if new files are added or existing files are updated, that contain a different set of RAT entries (not done automatically, it can be expensive and the RAT might be uniform across files).
> [GEOT-7563] Allow to recompute an image mosaic summary Raster Attribute Table

- modules/unsupported/css/pom.xml
This "add-opens" is no longer needed since the last update of the parboiled library
> Remove opens no longer needed for Java 17

- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReader.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
- pom.xml
[![GEOT-7565](https://badgen.net/badge/JIRA/GEOT-7565/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7565) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Follows up with imageio-ext deprecation of a redundant property
> [GEOT-7565] Upgrade ImageIO-Ext to 1.4.10

- modules/library/main/src/main/java/org/geotools/renderer/crs/WrappingCoordinateFilter.java
- modules/library/main/src/main/java/org/geotools/renderer/crs/WrappingProjectionHandler.java
- modules/library/main/src/test/java/org/geotools/renderer/crs/WrappingProjectionHandlerTest.java
[![GEOT-7570](https://badgen.net/badge/JIRA/GEOT-7570/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7570) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
removed longestline filter
cleanup
> [GEOT-7570] Small features that cross the dateline may be interpreted as preflipped

- modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/GraphicLegendBuilder.java
- modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/MarkBuilder.java
- modules/extension/brewer/src/test/java/org/geotools/brewer/styling/builder/StyleBuilderTest.java
- modules/library/main/src/main/java/org/geotools/styling/ExternalGraphicImpl.java
- modules/library/main/src/test/java/org/geotools/styling/ExternalGraphicImplTest.java
[![GEOT-7568](https://badgen.net/badge/JIRA/GEOT-7568/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7568) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The problem was that GraphicLegendBuilder wasn't handling the symbols variable at all. Copied some code from GraphicBuilder.
There was also a problem with ExternalGraphicImpl and how it handled the variables location, uri and online.getLinkage(). Which should represent the same thing, but as different types.
> [GEOT-7568] ExternalGraphic isn't drawn when defined in LegendGraphic

- modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/GraphicLegendBuilder.java
- modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/MarkBuilder.java
- modules/extension/brewer/src/test/java/org/geotools/brewer/styling/builder/StyleBuilderTest.java
- modules/library/main/src/main/java/org/geotools/styling/ExternalGraphicImpl.java
- modules/library/main/src/test/java/org/geotools/styling/ExternalGraphicImplTest.java
[![GEOT-7568](https://badgen.net/badge/JIRA/GEOT-7568/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7568) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4745
> [Backport 30.x] [GEOT-7568] ExternalGraphic isn't drawn when defined in LegendGraphic

- modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/GraphicLegendBuilder.java
- modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/MarkBuilder.java
- modules/extension/brewer/src/test/java/org/geotools/brewer/styling/builder/StyleBuilderTest.java
- modules/library/main/src/main/java/org/geotools/styling/ExternalGraphicImpl.java
- modules/library/main/src/test/java/org/geotools/styling/ExternalGraphicImplTest.java
[![GEOT-7568](https://badgen.net/badge/JIRA/GEOT-7568/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7568) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4745
> [Backport 31.x] [GEOT-7568] ExternalGraphic isn't drawn when defined in LegendGraphic

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccessFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java
- modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/AppSchemaDataAccessRegistryTest.java
[![GEOT-7559](https://badgen.net/badge/JIRA/GEOT-7559/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7559) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
deep equality trimmed down
fixed equality compare and started on test
Cleanup
more cleanup
moved equal to local
> [GEOT-7559] App-Schema throws an error when mappings have duplicate names, even when they come from includes

- docs/developer/procedures/contribution_license.rst
[![GEOT-7561](https://badgen.net/badge/JIRA/GEOT-7561/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7561) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Implements https://github.com/geotools/geotools/wiki/Individual-contributor-clarification
> [GEOT-7561] Proposal: Individual contributor clarification

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccessFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java
- modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/AppSchemaDataAccessRegistryTest.java
[![GEOT-7559](https://badgen.net/badge/JIRA/GEOT-7559/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7559) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4730
> [Backport 31.x] [GEOT-7559] App-Schema throws an error when mappings have duplicate names, even when they come from includes

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccessFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java
- modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/AppSchemaDataAccessRegistryTest.java
[![GEOT-7559](https://badgen.net/badge/JIRA/GEOT-7559/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7559) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4730
> [Backport 30.x] [GEOT-7559] App-Schema throws an error when mappings have duplicate names, even when they come from includes

- modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufWriter.java
- modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
[![GEOT-7569](https://badgen.net/badge/JIRA/GEOT-7569/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7569) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Without this fix FlatGeobuf output will become much larger than expected. It appears the output will still work, which is why it went under the radar for quite some time, likely due to that redundant data is appended in buffers that is not read. If possible it would be good if this fix could be backported.
Originally noted in https://osgeo-org.atlassian.net/browse/GEOT-7569.
> [GEOT-7580] Fix missing builder clear writing FlatGeobuf data

- modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureConversions.java
- modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/AttributeRoundtripTest.java
[![GEOT-7579](https://badgen.net/badge/JIRA/GEOT-7579/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7579) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4768
> [Backport 31.x] [GEOT-7579] FlatGeobuf handle java.util.Date and iso correctness

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/util/XmlXpathUtilites.java
- modules/extension/app-schema/app-schema/src/test/java/org/geotools/appschema/util/XmlXpathUtilitesTest.java
- modules/extension/complex/src/main/java/org/geotools/data/complex/expression/FeaturePropertyAccessorFactory.java
- modules/extension/complex/src/main/java/org/geotools/data/complex/expression/MapPropertyAccessorFactory.java
- modules/extension/complex/src/test/java/org/geotools/filter/expression/FeaturePropertyAccessorTest.java
- modules/extension/complex/src/test/java/org/geotools/filter/expression/MapPropertyAccessorTest.java
- modules/extension/xsd/xsd-core/pom.xml
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathStreamingParserHandler.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathUtils.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/StreamingParserTest.java
This PR refactors all jxpath initialization into a new utility method that disables calling functions from XPath expressions and fixes an incomplete class check that allowed complex feature code to be used on simple features. Some unnecessary dependency exclusions were also removed to clean up the pom.xml (commons-jxpath has no transitive dependencies).
> [GEOT-7587] Improve handling of XPath expressions

- modules/library/main/src/main/java/org/geotools/filter/LikeToRegexConverter.java
- modules/library/main/src/test/java/org/geotools/filter/LikeFilterImplTest.java
[![GEOT-7590](https://badgen.net/badge/JIRA/GEOT-7590/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7590) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Small fix for supporting ampersand usage in "Like" filters. 
See https://osgeo-org.atlassian.net/browse/GEOT-7590
Thank you for taking care!
> [GEOT-7590] Fix ampersand handling in Like filters

- modules/library/main/src/main/java/org/geotools/filter/LikeToRegexConverter.java
- modules/library/main/src/test/java/org/geotools/filter/LikeFilterImplTest.java
[![GEOT-7590](https://badgen.net/badge/JIRA/GEOT-7590/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7590) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4807
**Authored by:** @awaterme
> [Backport 30.x] [GEOT-7590] Fix ampersand handling in Like filters

- modules/library/main/src/main/java/org/geotools/filter/LikeToRegexConverter.java
- modules/library/main/src/test/java/org/geotools/filter/LikeFilterImplTest.java
[![GEOT-7590](https://badgen.net/badge/JIRA/GEOT-7590/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7590) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4807
**Authored by:** @awaterme
> [Backport 31.x] [GEOT-7590] Fix ampersand handling in Like filters

- docs/user/welcome/userlistguide.rst
I tried to find the user mailing list archive and stumbled upon the "GeoTools user list posting guide". Unfortunately the link to "User list archives" was broken. After a little bit of research I found the new user mailinglist archive: https://sourceforge.net/p/geotools/mailman/geotools-gt2-users/
This PR fixes this issue.
> Fix url for the user mailing list archives

- .github/workflows/mysql_online.yml
[![GEOT-7599](https://badgen.net/badge/JIRA/GEOT-7599/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7599) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4816
> [Backport 31.x] [GEOT-7599] Update MySQL CI matrix (drop 5.7, add 8.4)

- docs/user/library/jdbc/postgis.rst
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisPSFilterToSql.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonTestSetup.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisJsonPathExistsTest.java
[![GEOT-7589](https://badgen.net/badge/JIRA/GEOT-7589/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7589) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR is aimed to add support for searching root level arrays using postgres implementation of JsonArrayContains.
Current implementation is using the @> operator, however to use it with array at root level the searched object should be wrapped in square brackets. Below is an examples of working queries for array wrapped in object and non wrapped:
```
("jsonColumn"::jsonb @> '{ "arrayStrValues": ["EL2"] }'::jsonb
```
for …
> [GEOT-7589] Fix the JsonArrayDelegation for Postgres to support searching in root level array

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/filter/expression/ToLineStringFunction.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/filter/expression/ToPointFunction.java
- modules/extension/app-schema/app-schema/src/test/java/org/geotools/appschema/filter/GeometryFunctionsTest.java
- modules/extension/transform/src/main/java/org/geotools/data/transform/CRSEvaluator.java
- modules/extension/transform/src/main/java/org/geotools/data/transform/TransformFeatureCollection.java
- modules/extension/transform/src/main/java/org/geotools/data/transform/Transformer.java
- modules/extension/transform/src/test/java/org/geotools/data/transform/TransformFeatureSourceTest.java
- modules/library/main/src/main/java/org/geotools/api/data/Query.java
- modules/library/main/src/main/java/org/geotools/feature/simple/SimpleFeatureBuilder.java
- modules/library/main/src/main/java/org/geotools/feature/simple/SimpleFeatureTypeBuilder.java
- modules/library/main/src/main/java/org/geotools/feature/type/Types.java
- modules/library/main/src/main/java/org/geotools/geometry/jts/JTS.java
- modules/library/main/src/test/java/org/geotools/feature/simple/SimpleFeatureBuilderTest.java
- modules/library/main/src/test/java/org/geotools/feature/simple/SimpleTypeBuilderTest.java
- modules/library/main/src/test/java/org/geotools/feature/type/TypesTest.java
- modules/library/main/src/test/java/org/geotools/geometry/jts/JTSTest.java
- modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
[![GEOT-7601](https://badgen.net/badge/JIRA/GEOT-7601/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7601) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Transform FeatureCollection handling of a query that both limits attributes and changes CRS.
During this PR several other issues came up as I ran into missing or inconsistent functionality. 
* [GEOT-7612](https://osgeo-org.atlassian.net/browse/GEOT-7612) Types.validate(Attribute) does not check ComplexAttribute values individually
* [GEOT-7601](https://osgeo-org.atlassian.net/browse/GEOT-7601) Transform FeatureCollection Query …
> [GEOT-7601] Transform FeatureCollection Query handling of reprojection

- pom.xml
[![GEOT-7615](https://badgen.net/badge/JIRA/GEOT-7615/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7615) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4836
> [Backport 31.x] [GEOT-7615] Update Jackson 2 libs from 2.17.1 to 2.17.2

- modules/library/http/src/main/java/org/geotools/http/SimpleHttpClient.java
- modules/library/http/src/test/java/org/geotools/http/SimpleHttpClientTest.java
- modules/library/xml/pom.xml
- modules/library/xml/src/main/java/org/geotools/xml/resolver/SchemaCache.java
- modules/library/xml/src/test/java/org/geotools/xml/resolver/SchemaCacheMockHttpClientFactory.java
- modules/library/xml/src/test/java/org/geotools/xml/resolver/SchemaCacheOnlineTest.java
- modules/library/xml/src/test/java/org/geotools/xml/resolver/SchemaCacheTest.java
- modules/library/xml/src/test/resources/META-INF/services/org.geotools.http.HTTPClientFactory
[![GEOT-7576](https://badgen.net/badge/JIRA/GEOT-7576/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7576) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Currently the XML SchemaCache makes direct HTTP calls for downloading XML schemas.
The goal of this PR is for the SchemaCache to use the geotools HttpClient instead. This ensures that if a specific HttpClient is set (see https://github.com/geotools/geotools/blob/main/docs/user/library/http/index.rst) it will be used for all outgoing HTTP calls.
Since there was a bit of logic for following redirections in SchemaCache, I have …
> [GEOT-7576] Use HttpClient in SchemaCache

- .github/workflows/macos.yml
- docs/user/library/data/ogr.rst
- modules/unsupported/ogr/ogr-jni/src/test/java/org/geotools/data/ogr/jni/JniOGRDataStoreTest.java
This is a follow-on to https://github.com/geotools/geotools/pull/4636 , restoring the GDAL OSX build by building GDAL from source.
This'll likely need a couple passes to get right, the initial commit is just the first pass based on how I've built GDAL on Mac locally. In particular, the GDAL version is currently hardcoded, and could be moved to job configuration / a CI variable
> Build GDAL from source for OSX Github build

- .github/workflows/mssql_online.yml
See changes in directory names, making the latest 2022 docker image incompatible with the 2019 one: https://hub.docker.com/r/microsoft/mssql-server
This PR tries to pin the previous tag to avoid the issue.
> Pinning MSSQL 2022 tag to avoid changes in tools directories. 

- docs/user/library/referencing/compare.rst
- modules/library/main/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope.java
- modules/library/main/src/test/java/org/geotools/geometry/jts/ReferencedEnvelopeTest.java
- modules/library/referencing/src/main/java/org/geotools/referencing/CRS.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageReaderHelper.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageRenderer.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageRendererUtilities.java
[![GEOT-7626](https://badgen.net/badge/JIRA/GEOT-7626/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7626) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This fix allows the CRSs compatibility check required by Rendering and ReferencedEnvelope to fallback on the identity transformation check. It may be the case that 2 CRSs are equivalent (no transformation required from source to target CRS) although the initial CRS.equalsIgnoreMetdata returns false.
> GEOT-7626: refine compatible CRS check that fallback on CRS's identity transformation check

- .github/workflows/mssql_online.yml
> [Backport 31.x] Pinning MSSQL 2022 tag to avoid changes in tools directories. 

- .github/workflows/mssql_online.yml
Seeing failures in the 2019 build with the same error as the 2022 one, trying to apply the same fix.
> Pinning MSSQL 2019 as well

- docs/user/library/referencing/compare.rst
- modules/library/main/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope.java
- modules/library/main/src/test/java/org/geotools/geometry/jts/ReferencedEnvelopeTest.java
- modules/library/referencing/src/main/java/org/geotools/referencing/CRS.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageReaderHelper.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageRenderer.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageRendererUtilities.java
[![GEOT-7626](https://badgen.net/badge/JIRA/GEOT-7626/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7626) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4847
**Authored by:** @dromagnoli
> [Backport 30.x] GEOT-7626: refine compatible CRS check that fallback on CRS's identity transformation check

- docs/user/library/referencing/compare.rst
- modules/library/main/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope.java
- modules/library/main/src/test/java/org/geotools/geometry/jts/ReferencedEnvelopeTest.java
- modules/library/referencing/src/main/java/org/geotools/referencing/CRS.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageReaderHelper.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageRenderer.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageRendererUtilities.java
[![GEOT-7626](https://badgen.net/badge/JIRA/GEOT-7626/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7626) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4847
**Authored by:** @dromagnoli
> [Backport 31.x] GEOT-7626: refine compatible CRS check that fallback on CRS's identity transformation check

- .github/workflows/integration.yml
Run downstream integration builds with the right downstream branches
> Run downstream integration builds for the 30.x too

- .github/workflows/integration.yml
The integration downstream build is using the main branch of each project, which is fine for the main branch of GeoTools, but useless in stable/maintenance ones.
> Run downstream integration builds for the 31.x too

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java
[![GEOT-7628](https://badgen.net/badge/JIRA/GEOT-7628/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7628) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7628] Regression in JDBC optimization of unique visitor with sorting

- modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/FeatureTypeStyleBuilder.java
- modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/StyleBuilder.java
- modules/extension/brewer/src/test/java/org/geotools/brewer/styling/builder/CookbookLineTest.java
- modules/unsupported/css/pom.xml
- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/CssBaseTest.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
[![GEOT-7631](https://badgen.net/badge/JIRA/GEOT-7631/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7631) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Stepping stone to support GeoServer style groups defined in CSS. There is going to a GeoServer PR following up with this one, with documentation updates.
> [GEOT-7631] Support multi-layer output in CSS

- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-7528](https://badgen.net/badge/JIRA/GEOT-7528/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7528) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4874
> [Backport 31.x] [GEOT-7528] GeoPackage: Timestamp is not written correctly

- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-7528](https://badgen.net/badge/JIRA/GEOT-7528/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7528) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4874
> [Backport 30.x] [GEOT-7528] GeoPackage: Timestamp is not written correctly

- modules/library/main/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java
- modules/library/main/src/test/java/org/geotools/renderer/crs/ProjectionHandlerTest.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java
[![GEOT-7636](https://badgen.net/badge/JIRA/GEOT-7636/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7636) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket for details.
This needs to go along with https://github.com/geoserver/geoserver/pull/7858
> [GEOT-7636] Line densification on reprojection can lead to OOM

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/AbstractFilterToMongo.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFilterSplitter.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoFilterSplitterTest.java
https://osgeo-org.atlassian.net/browse/GEOT-7634
Current implementation of DWITHIN for Mongo is being delegated to Mongo's $near operator, however, this operator accepts only points. This commit refactors delegation to instead make use of $geoIntersects, which accepts other geometry types.
The buffer is being applied to input geometry, and resulting geometry is being used in $geoIntersects.
> [GEOT-7634] Update DWITHIN delegation in Mongo to support linestring

- modules/extension/graph/pom.xml
- modules/extension/graph/src/main/java/org/geotools/graph/io/standard/SerializedReaderWriter.java
- modules/extension/graph/src/test/java/org/geotools/graph/io/standard/BasicGraphSerializerTest.java
- modules/library/main/src/main/java/org/geotools/data/sort/SimpleFeatureIO.java
- modules/library/main/src/test/java/org/geotools/data/sort/SimpleFeatureIOTest.java
- modules/library/metadata/src/main/java/org/geotools/util/Base64.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/UtilsTest.java
[![GEOT-7629](https://badgen.net/badge/JIRA/GEOT-7629/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7629) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR uses ValidatingObjectInputStream from the Commons IO library to to restrict the classes that are allowed when deserializing imagemosaic sample image and histogram files and graph files. There are multiple existing unit tests that test deserializing valid graph files. The sample image files are the primary concern for potential backwards-compatibility issues.
SimpleFeatureIO was restricted to only allow deserialization …
> [GEOT-7629] Add validation when deserializing objects

- modules/library/main/src/main/java/org/geotools/styling/zoom/WellKnownZoomContextFinder.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssParser.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/DomainCoverage.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/selector/AbstractSelectorVisitor.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/selector/SelectorVisitor.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/selector/ZoomRange.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/util/OgcFilterBuilder.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/util/PseudoClassExtractor.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/util/PseudoClassRemover.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/util/ScaleRangeExtractor.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/util/TypeNameExtractor.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/util/TypeNameSimplifier.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/ParserSyntheticTest.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
[![GEOT-7638](https://badgen.net/badge/JIRA/GEOT-7638/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7638) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
As the title says
Followed up by https://github.com/geoserver/geoserver/pull/7861
> [GEOT-7638] Add support for zoom level rule filtering in CSS

- .github/dependabot.yml
- .github/workflows/assembly.yml
- .github/workflows/db2_online.yml
- .github/workflows/elasticsearch_online.yml
- .github/workflows/geopkg_online.yml
- .github/workflows/hana_online.yml
- .github/workflows/informix.yml
- .github/workflows/integration.yml
- .github/workflows/linux_gdal.yml
- .github/workflows/linux_jdk11.yml
- .github/workflows/linux_jdk17.yml
- .github/workflows/linux_jdk21.yml
- .github/workflows/macos.yml
- .github/workflows/mssql_online.yml
- .github/workflows/mysql_online.yml
- .github/workflows/oracle_online.yml
- .github/workflows/postgis_online.yml
- .github/workflows/qa.yml
- .github/workflows/windows.yml
- docs/developer/procedures/release.rst
This adds a Dependabot configuration to keep any workflow actions across branches up-to-date.
see also https://dailystuff.nl/blog/2020/start-using-github-dependabot
To prevent flooding us with PRs for all the old action versions update the following actions to the current release:
- actions/checkout@v4
- actions/setup-java@v4
- actions/cache@v4
- actions/setup-python@v5
> Add Dependabot configuration to update workflow actions across branches

- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileTest.java
[![GEOT-7635](https://badgen.net/badge/JIRA/GEOT-7635/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7635) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Adds some more tests on shapefiles with missing dbf files.
> [GEOT-7635] Error in read empty DBF using FileDataStore

- modules/library/api/src/main/java/org/geotools/api/style/FeatureTypeStyle.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
[![GEOT-7643](https://badgen.net/badge/JIRA/GEOT-7643/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7643) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket for details. Documentation will follow in the GeoServer follow-up PR.
> [GEOT-7643] Add support for vector tiles flags for SLD and CSS

- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaCloudVersion.java
- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaDataStoreFactory.java
- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaDialect.java
- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaJNDIDataStoreFactory.java
- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaVersion.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaFeatureSourceOnlineTest.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaGeographyOnlineTest.java
- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaVirtualTableOnlineTest.java
[![GEOT-7606](https://badgen.net/badge/JIRA/GEOT-7606/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7606) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
With QRC/1 2024 a new and faster way to estimate extents of spatial column has been added to HANA.
More precisely, users can now use special columns in [this table](https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-spatial-reference/spatial-extent-with-sys-m-st-geometry-columns?locale=en-US) to get an estimation of the extent of a spatial column.
Even though the stored extent is only an estimation, …
> [GEOT-7606] Support fast extent estimation in HANA provider

- modules/library/main/src/main/java/org/geotools/api/data/DataAccessFinder.java
- modules/library/main/src/main/java/org/geotools/api/data/DataStoreFinder.java
- modules/library/main/src/test/java/org/geotools/api/data/DataStoreFinderTest.java
- modules/library/main/src/test/java/org/geotools/data/DataAccessFinderTest.java
@jodygarnett this is what you suggested in https://github.com/aaime/geoserver/pull/16
(PR with usage following)
> Allow programmatic registration and de-registration of stores

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisNGDataStoreFactory.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisJNDIDataSourceOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisNGDataStoreFactoryTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostgisReWriteBatchedInsertsFeatureStoreOnlineTest.java
[![GEOT-7614](https://badgen.net/badge/JIRA/GEOT-7614/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7614) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
adds support for setting `reWriteBatchedInserts` as a jdbc property for postgis
> [GEOT-7614] support for postgres reWriteBatchedInserts

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSFeatureSource.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSource.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/GetFeatureRequest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSourceTest.java
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/KartverketNo/GetFeature_sted_25833.xml
[![GEOT-7636](https://badgen.net/badge/JIRA/GEOT-7636/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7636) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Set SRS by the same approach as WFSFeatureSource.
> [GEOT-7636] GetFeatures call of WFSContentComplexFeatureSource should set srs according to query

- modules/library/main/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope.java
- modules/library/main/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java
- modules/library/main/src/main/java/org/geotools/renderer/crs/WrappingProjectionHandler.java
- modules/library/referencing/src/main/java/org/geotools/referencing/crs/AbstractCRS.java
- modules/library/referencing/src/main/java/org/geotools/referencing/crs/AbstractDerivedCRS.java
- modules/library/referencing/src/main/java/org/geotools/referencing/crs/AbstractSingleCRS.java
- modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultCompoundCRS.java
- modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultDerivedCRS.java
- modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultEngineeringCRS.java
- modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultGeocentricCRS.java
- modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultGeographicCRS.java
- modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultImageCRS.java
- modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultProjectedCRS.java
- modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultTemporalCRS.java
- modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultVerticalCRS.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java
Backport of #4914, minus the hash code API change in AbstractCRS (hashCode is not final in this PR).
> [Backport 32.x] Speed up reprojected rendering of large amounts of points

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFilterSplitter.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoFilterSplitterTest.java
[![GEOT-7658](https://badgen.net/badge/JIRA/GEOT-7658/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7658) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The issue was introduced in GEOT-7634. For the WMS GetFeatureInfo request the filter part was not handled properly, which resulted in inclusion of all features on layer into response. This behavior was corrected and test added.
> [GEOT-7658] [MongoDB Plugin] The filter spliter may drop part of the filter

- modules/extension/xsd/xsd-sld/src/main/java/org/geotools/sld/bindings/SLDGraphicBinding.java
- modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDGraphicBindingTest.java
- modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDMockData.java
* [GEOT-7666] Parsing empty Rotation style element throws a ClassCastException
---------
> [32.x backport] [GEOT-7666] Parsing empty Rotation style element throws a ClassCastException

- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/GranuleSourceProvider.java
- modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java
- modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7671](https://badgen.net/badge/JIRA/GEOT-7671/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7671) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Further optimization (and fix) for count processing.
> [GEOT-7671] Vector mosaic 'count' implementation does not account for max features

- build/build.xml
- docs/developer/procedures/release.rst
If the old maintenance (now archive) branch is not set to archive, and we ever had to create an emergency release for this archived branch, it would overwrite the current maintenence documentation which might be a version or two ahead of the archived version.
Ref: https://github.com/geotools/geotools/pull/4904/commits/3adaca02c310fab68a0b357033a45d5969efc406#r1761480318
> Update release procedure

- modules/extension/wms/src/main/java/org/geotools/ows/wms/WMSCapabilities.java
- modules/extension/wms/src/test/java/org/geotools/ows/wms/WMSCapabilitiesTest.java
[![GEOT-7669](https://badgen.net/badge/JIRA/GEOT-7669/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7669) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fix `ConcurrentModificationException` when traversing the list returned by `WMSCapabilities.getLayerList()`.
Avoid locking and synchronized blocks, worst case scenario the list is built more than once.
> [GEOT-7669] ConcurrentModificationException in WMSCapabilities.getLayerList()

- modules/library/main/src/main/java/org/geotools/filter/function/JsonArrayContainsFunction.java
As reported by Peter, running the Quickstart from command line will result in:
```
Nov 18, 2024 4:11:23 PM org.geotools.util.factory.FactoryRegistry scanForPlugins
WARNING: Can't load a service for category "Function". Cause is "ServiceConfigurationError: org.geotools.api.filter.expression.Function: Provider org.geotools.filter.function.JsonArrayContainsFunction could not be instantiated".
java.util.ServiceConfigurationError: org.geotools.api.filter.expression.Function: Provider org.geotools.filter.function.JsonArrayContainsFunction could not be instantiated
at java.base/[java.util.ServiceLoader.fail](http://java.util.serviceloader.fail/)([ServiceLoader.java:582](http://serviceloader.java:582/))
...
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactory
at …
```
> Avoiding class not found exception in Quickstart

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCInsertFeatureWriter.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCFeatureWriterOnlineTest.java
- modules/library/main/src/main/java/org/geotools/data/InProcessLockingManager.java
This PR exposes the `flush` method of JDBCInserrtFeatureWriter, by making the method public and implementing `java.io.Flushable`. The rationale is to allow for finer-grained control over when features get written out.
> [GEOT-7682] Expose JDBCInserrtFeatureWriter flush method

- modules/library/main/src/main/java/org/geotools/filter/BinaryLogicAbstract.java
- modules/library/main/src/test/java/org/geotools/filter/FiltersTest.java
[![GEOT-7689](https://badgen.net/badge/JIRA/GEOT-7689/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7689) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [32.x backport] [GEOT-7689] Logic filter equality checks incorrectly implemented

- modules/library/main/src/main/java/org/geotools/api/data/DataAccessFinder.java
- modules/library/main/src/main/java/org/geotools/api/data/DataStoreFinder.java
- modules/library/main/src/test/java/org/geotools/api/data/DataStoreFinderTest.java
- modules/library/main/src/test/java/org/geotools/data/DataAccessFinderTest.java
[![GEOT-7670](https://badgen.net/badge/JIRA/GEOT-7670/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7670) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This changes DataStoreFinder and DataAccessFinder to synchronize on a common object (DataAccessFinder.class) to avoid potential thread deadlocks.
> [GEOT-7670] Fix synchronization between DataStoreFinder and DataAccessFinder

- modules/library/main/src/test/java/org/geotools/data/util/ColorConverterFactoryTest.java
"gray" and "grey" are two names for the same color.  `Converter.convert` could return either depending on `HashMap` ordering.  Adjust the test to accept either.
https://github.com/geotools/geotools/blob/7f79128a9e8c1df6f07eff675ec35a7070e2d6af/modules/library/main/src/main/java/org/geotools/data/util/ColorConverterFactory.java#L119
Alternatively, a `LinkedHashMap` could be used for `CSS_COLORS`, but accepting either seems like a more minimal change.
There are more duplicate colors, but they are not tested:
```
colors.put("aqua", new Color(0, 255, 255));
colors.put("cyan", new Color(0, 255, 255));
colors.put("darkgray", new Color(169, 169, 169));
colors.put("darkgrey", new Color(169, 169, 169));
colors.put("darkslategray", new Color(47, 79, 79));
colors.put("darkslategrey", new Color(47, …
```
> ColorConverterFactoryTest.testToCss: Fix gray/grey

- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDataStoreFactory.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDialect.java
- modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerDialectOnlineTest.java
- modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerDialectTestSetup.java
[![GEOT-7234](https://badgen.net/badge/JIRA/GEOT-7234/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7234) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Query the (first) spatial index defined on a column to get the bounds, the option to use the fast-track is enabled using the `estimatedExtentsEnabled` feature flag.
> [GEOT-7234] Implement #getOptimizedBounds(...) in SQLServerDialect

- modules/library/referencing/src/main/java/org/geotools/referencing/operation/projection/GeostationarySatellite.java
- modules/library/referencing/src/test/java/org/geotools/referencing/operation/projection/GeostationarySatelliteTest.java
A fix to the geostationary projection in geotools to allow setting the sweep
axis as appropriate for GOES. The WKT parser only allows parameters
that can be parsed as doubles so I didn't add the sweep_axis as a parameter
with values x,y (which doesn't seem to be done anywhere anyway). We could fix
that, but it's a larger change. Instead, I added a sweep parameter that's
either a 0 (x) or a 1 (y).
All the math is copied over from PROJ of course, as it was before, but now it's
copied from a newer version of PROJ (5.2 instead of 4.9).
> [GEOT-7641] Support the "Sweep" parameter in the geostationary projections

- pom.xml
Noticed its snapshot repo being scanned (slowing down the build). 
Although the comment indicates this was a temporary measure I accidentally left it in when JTS release was made - sorry!
Set this up as a profile for future use rather than just throw out; this is a non functional build change.
> only use jts snapshot repo when requested with jts profile

- docs/themes/geotools-web/page.html
Noticed errors about mixed http/https usage in the JS console, preventing loading of blog posts. Then found other HTTP links in the same HTML template. Ended up switching all to https (java.net is gone, removed it altogether)
> Switch home page links to https, hopefully this will restore the blog post list as well

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
[![GEOT-7687](https://badgen.net/badge/JIRA/GEOT-7687/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7687) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The issue is tracked under [GEOT-7687](https://osgeo-org.atlassian.net/browse/GEOT-7687)
currently it is not possible to use numeric json(b) keys. When not escaped they are treated as array indices. Possible escaping leads to unwanted additional escapes. This PR should fix the behavior
> [GEOT-7687] fixed duplicated escaping when numeric object keys are used in jsonpointer

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/DefaultPropertiesCollectorSPI.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/FullPathCollector.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/RegExPropertiesCollector.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/properties/string/StringFileNameExtractorTest.java
[![GEOT-7703](https://badgen.net/badge/JIRA/GEOT-7703/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7703) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7703] Allow usage of fullPath in most common mosaic property collectors

- modules/library/main/src/main/java/org/geotools/filter/function/InFunction.java
- modules/library/main/src/test/java/org/geotools/filter/FilterTest.java
[![GEOT-7706](https://badgen.net/badge/JIRA/GEOT-7706/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-11591) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The ticket is being tracked under [GEOT-7706](https://osgeo-org.atlassian.net/browse/GEOT-7706)
The problem is (was) that `java.util.Date` is assignable from `java.sql.Timestamp` class instances but not vice-versa. This may cause problems when an in-condition (containing Date/Time) should be applied on a timestamp column. One needs to distinguish between assignable date sub-classes within the …
> [GEOT-7706] fixed class comparison for Date/Time instances

- modules/library/metadata/src/main/java/org/geotools/util/logging/LogbackLogger.java
- modules/library/metadata/src/test/java/org/geotools/util/logging/LoggingTest.java
[![GEOT-7545](https://badgen.net/badge/JIRA/GEOT-7545/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7545) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The logback logger was doing an incorrect log level comparison, suppressing messages that should have been shown based on the configured log level.
This PR fixes the logic and adds a unit test to prevent a regression.
> [GEOT-7545] Wrong log level comparison in LogbackLogger#isLoggable

- modules/library/metadata/src/main/java/org/geotools/util/logging/LogbackLogger.java
- modules/library/metadata/src/test/java/org/geotools/util/logging/LoggingTest.java
- modules/unsupported/elasticsearch/pom.xml
- pom.xml
- release/src/it/log4j/pom.xml
- release/src/it/logback/pom.xml
An update of slf4j 2.x introduced an incompatibility with logback which was not covered by test cases.
- https://github.com/geotools/geotools/pull/4979
This was detected by https://github.com/geotools/geotools/pull/5063 which introduced a test case.
> [GEOT-7711] 32.x upgrade log4j to 2.24.1, slf4j to 2.0.16, and logback 1.5.14

- modules/unsupported/jdbc-h2gis/pom.xml
- pom.xml
This is just a test dependency upgrade. The junit-bom is now used to manage the versions of all junit-jupiter dependencies.
> Upgrade junit-upiter from 5.8.2 to 5.11.4

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/response/WMTSGetCapabilitiesResponse.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/response/CapabilitiesResponseTest.java
[![GEOT-7709](https://badgen.net/badge/JIRA/GEOT-7709/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7709) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Rearranged the constructor to avoid ClassCastException and added tests for two situations.
> [GEOT-7709] WMTS GetCapabilities will not recognize ServiceException

- modules/library/main/src/main/java/org/geotools/data/ows/Response.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/TransactionRequest.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSExtensions.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSRequest.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSResponseFactory.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/AbstractWFSResponseFactory.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/ServiceExceptionResponseFactory.java
- modules/unsupported/wfs-ng/src/main/resources/META-INF/services/org.geotools.data.wfs.internal.WFSResponseFactory
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/IntegrationTestWFSClient.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/v1_1/XXEProtectionTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/WFSResponseFactoryTest.java
[![GEOT-7320](https://badgen.net/badge/JIRA/GEOT-7320/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7320) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Some WFS servers send ServiceException's like for other OGC services, even if the spec says differently.
This is a straight approach to use the same approach as other OGC services for parsing these ServiceException's and throw.
> [GEOT-7320] ServiceException from a WFS server GetFeature ends in a FactoryNotFoundException

- modules/extension/complex/src/main/java/org/geotools/data/complex/feature/type/FeatureTypeRegistry.java
- modules/extension/complex/src/test/java/org/geotools/data/complex/feature/type/FeatureTypeRegistryTest.java
[![GEOT-7713](https://badgen.net/badge/JIRA/GEOT-7713/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7713) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Just want to place synchronize at the right object. More should probably be done to get it thread-safe.
> [GEOT-7713]  FeatureTypeRegistry of gt-complex is not thread-safe

- pom.xml
[![GEOT-7725](https://badgen.net/badge/JIRA/GEOT-7725/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7725) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This is a draft pull-request to try out DB2 driver update to version 12.1.0.0.
> [GEOT-7725] Upgrade DB2 JDBC driver from 11.5.9.0 to 12.1.0.0

- pom.xml
[![GEOT-7729](https://badgen.net/badge/JIRA/GEOT-7729/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7729) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
For the fix of https://github.com/geosolutions-it/jai-ext/issues/309 jai-ext needs to be updated to the latest version (1.1.30) that contains the fix. 
> [GEOT-7729] Update jai-ext to 1.1.30

- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/JiffleProcess.java
- modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/JiffleProcessTest.java
- pom.xml
[![GEOT-7734](https://badgen.net/badge/JIRA/GEOT-7734/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7734) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Comes with [[GEOT-7719]](https://github.com/geotools/geotools/commit/4a4f33a6c442e083b7cfb7c1e4167ec50c907dc5)
as it's necessary to keep GeoTools compiling.
> [31.x backport] [GEOT-7734] Update to jai-ext 1.1.31

- modules/extension/wms/src/main/java/org/geotools/ows/wms/xml/Dimension.java
- modules/extension/wms/src/main/java/org/geotools/ows/wms/xml/WMSComplexTypes.java
- modules/extension/wms/src/test/java/org/geotools/ows/wms/xml/test/WMSComplexTypesTest.java
- modules/extension/wms/src/test/resources/org/geotools/ows/wms/xml/test/test-data/1.3.0Capabilities_Dimensions.xml
- modules/extension/wms/src/test/resources/org/geotools/ows/wms/xml/test/test-data/1.3.0Capabilities_Dimensions_missingUnits.xml
[![GEOT-7632](https://badgen.net/badge/JIRA/GEOT-7632/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7632) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR is to fix [[GEOT-7632]  WMS capabilities parsing should not fail if 'units' for a dimension is empty](https://osgeo-org.atlassian.net/browse/GEOT-7632). According to [OpenGIS Web Map Service WMS Implementation Specification](https://portal.ogc.org/files/?artifact_id=14416), for layer dimensions, `units` must **not** be missing, **but are allowed to be empty**:
> If the dimensional quantity has no units (e.g. band number …
> [GEOT-7632]  WMS capabilities parsing should not fail if 'units' for a dimension is empty

- modules/extension/transform/src/main/java/org/geotools/data/transform/TransformFeatureCollection.java
- modules/extension/transform/src/main/java/org/geotools/data/transform/Transformer.java
- modules/extension/transform/src/test/java/org/geotools/data/transform/TransformerTest.java
[![GEOT-7726](https://badgen.net/badge/JIRA/GEOT-7726/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7726) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The added `continue` in Transformer.java prevents an NPE which will otherwise happen any time that SortBy.NATURAL_ORDER is supplied, which the code clearly intends to handle without throwing an exception.
See JIRA issue for details.
Also fix NPE in TransformFeatureCollection, which prevents the first NPE from showing up in logs.
> [GEOT-7726] NPE in Transformer.getTransformedSortBy for SortBy.NATURAL_ORDER

- modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaGeographyOnlineTest.java
[![GEOT-7743](https://badgen.net/badge/JIRA/GEOT-7743/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7743) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
After an upgrade, HANA's envelope computation returns slightly different values in geographic spatial reference systems.
We increase the tolerance from 1 to 2 ULP in the test to accept the envelope returned by the database.
> [GEOT-7743] HanaGeographyOnlineTest is failing after database upgrade

- modules/unsupported/geoparquet/pom.xml
- modules/unsupported/geoparquet/src/main/java/org/geotools/data/duckdb/AbstractDuckDBDataStoreFactory.java
- modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/ForwardingDataStore.java
- modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/ForwardingDataStoreFactory.java
- modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetDataStoreFactory.java
- modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetDataStoreFactoryDelegate.java
- modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetDialect.java
- modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetViewManager.java
- modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoparquetDataStore.java
- modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetDataStoreFactoryTest.java
- modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetDataStoreTest.java
- modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetTestSupport.java
Refactors GeoParquet implementation to use the decorator pattern, with GeoparquetDataStore as a decorator over JDBCDataStore and GeoParquetDataStoreFactory as a decorator over a new delegate factory.
Key improvements:
- Available type names are now resolved quickly using a fast path query
- Database view registration is delayed until the feature type is actually needed
- Adds proper thread safety for concurrent initialization of views
- Adds comprehensive Javadocs to all new and modified classes
This enhancement significantly improves responsiveness when working with large GeoParquet datasets, particularly with Hive partitioning and remote URIs, by avoiding unnecessary view registrations during initial data store setup.
> Improve GeoParquet DataStore performance by delaying view registration

- modules/unsupported/geoparquet/src/main/java/org/geotools/data/duckdb/DuckDBDialect.java
- modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetDialect.java
- modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetDataStoreTest.java
This commit addresses several issues with the GeoParquet DataStore:
- Fix SQL for bbox computation to use correct parameter ordering
- Add CRS handling override to preserve axis order from GeoParquet metadata
- Remove unnecessary Connection parameter from getGeometrySRIDInternal method
- Add trailing whitespace in SQL generation to fix JDBCDataStore handling
- Enhance tests to verify correct CRS axis order and bounds computation
- Add new test for the bbox column fallback method
These fixes ensure proper SQL generation and consistent CRS handling, especially important for coordinate order in different reference systems.
> Fix GeoParquet bugs and improve CRS handling

- modules/ogc/net.opengis.wmts/build.properties
- modules/ogc/net.opengis.wmts/pom.xml
Fix 'cannot nest resources inside src' for `modules/ogc/net.opengis.wmts`
With this change, GeoTools can be imported as a maven project in Eclipse instead of having to use the deprecated `mvn eclipse:eclipse` command.
* Update POM to add custom resources configuration that handles both
src/main/resources and .ecore files in the root directory
* Update build.properties to use src/ as the source directory to match
the actual project structure
> Fix Eclipse maven integration for non-standard source folders in modules/ogc/pom.xml

- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
[![GEOT-7765](https://badgen.net/badge/JIRA/GEOT-7765/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7765) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The goal is to allow propertyIsLike filter to be used on numeric columns in postgres. Since postgres does not allow that currently it results in exception. To make it work we need to cast numeric column to text.
This commit is checking the type of attribute and if it is numeric add a cast to ::text for PropertyIsLike filter.
Added corresponding test.
> [GEOT-7765] Improve PropertyIsLike filter to work for numeric columns in postgres

- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
[![GEOT-7765](https://badgen.net/badge/JIRA/GEOT-7765/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7765) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
port https://github.com/geotools/geotools/pull/5207
> [BACKPORT 33.x][GEOT-7765] Improve PropertyIsLike filter to work for numeric columns in postgres

- modules/unsupported/arcgis-rest/src/main/java/org/geotools/data/arcgisrest/GeoJSONParser.java
- modules/unsupported/arcgis-rest/src/test/java/org/geotools/data/arcgisrest/GeoJSONParserTest.java
[![GEOT-7773](https://badgen.net/badge/JIRA/GEOT-7773/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7773) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
> [GEOT-7773] GeoJSONParser of gt-arcgisrest sets Id of each feature to "features"

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/RegExPropertiesCollector.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/numeric/NumericFileNameExtractor.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/string/StringFileNameExtractor.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/time/TimestampFileNameExtractor.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/properties/numeric/NumericFileNameExtractorTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/properties/string/StringFileNameExtractorTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/properties/time/TimestampFileNameExtractorTest.java
[![GEOT-7776](https://badgen.net/badge/JIRA/GEOT-7776/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7776) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket for details, the current behavior makes it pretty hard to debug a mosaic setup having many variables.
> [GEOT-7776] Image mosaic property collectors fail with a array access exception when the regex does not match

- modules/extension/complex/src/main/java/org/geotools/data/complex/expression/FeaturePropertyAccessorFactory.java
- modules/library/main/src/main/java/org/geotools/filter/expression/PropertyAccessorFactory.java
- modules/library/main/src/main/java/org/geotools/filter/expression/PropertyAccessors.java
- modules/library/main/src/test/java/org/geotools/filter/expression/PropertyAccessorsFactoryTest.java
- modules/library/main/src/test/resources/META-INF/services/org.geotools.filter.expression.PropertyAccessorFactory
[![GEOT-7781](https://badgen.net/badge/JIRA/GEOT-7781/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7781) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Currently multiple property accessor factories can be used by the GeoServer, however this can cause issues because there are no clear priority, and order of them can vary. This changes add support for a priority.
> [GEOT-7781] Add a priority to property accessors

- modules/unsupported/jdbc-singlestore/src/main/java/org/geotools/data/singlestore/SingleStoreDialect.java
- modules/unsupported/jdbc-singlestore/src/test/java/org/geotools/data/singlestore/SingleStoreFeatureSourceNullGeomOnlineTest.java
- modules/unsupported/jdbc-singlestore/src/test/java/org/geotools/data/singlestore/SingleStoreNullGeomTestSetup.java
[![GEOT-7785](https://badgen.net/badge/JIRA/GEOT-7785/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7785) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOT-7785
> [GEOT-7785] Bounds computation fails when a null geometry is present on SingleStore datastore

- docs/user/artifacts/function_list
- modules/library/main/src/main/java/org/geotools/filter/function/ParseTimeFunction.java
- modules/library/main/src/main/resources/META-INF/services/org.geotools.api.filter.expression.Function
- modules/library/main/src/test/java/org/geotools/filter/function/ParseTimeFunctionTest.java
[![GEOT-7788](https://badgen.net/badge/JIRA/GEOT-7788/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7788) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Add a function that will allow to use GT time notations (for example 'P2M' for past 2 months) in filters.
For example time_attr >= parseTime('P2M')
> [GEOT-7788] Function to parse GeoTools time notation to date

- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-7787](https://badgen.net/badge/JIRA/GEOT-7787/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7787) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
As described in [GEOT-7787](https://osgeo-org.atlassian.net/browse/GEOT-7787), it appears that right now a Boolean is mapped to a SQL INTEGER type instead of a SQL BOOLEAN when we're dealing with geopackages.
The goal of this PR is to change this to BOOLEAN, since that makes more sense when looking at features in QGIS.
> [GEOT-7787] Boolean attributes don't get stored as a true boolean in geopackages

- docs/user/library/cql/ecql.rst
Fixing a link to the confluence wiki, found this while looking up how to escape quotes, so I added a clear example.
> Fix ECQL BNF link and add quote / double / escape examples

- modules/unsupported/flatgeobuf/pom.xml
Upgrade org.wololo.flatgeobuf to 3.28.1.
Primary purpose is to resolve issues with larger FlatGeobuf files which has been resolved in the dependency. See https://github.com/flatgeobuf/flatgeobuf/issues/450.
> Upgrade org.wololo.flatgeobuf to 3.28.1

- modules/library/coverage/src/test/java/org/geotools/coverage/grid/Viewer.java
Just replacing GraphicsJAI with equivalent functionality from Graphics2D, as GraphicsJAI is getting moved to the legacy module in ImageN. This is to prevent a compile error when GeoTools will upgrade to ImageN 0.9.
> ImageN evolution: do not depend on GraphicsJAI
