pom.xml
Batik has resolved CVE-2020-11987. As a result of this upgrade xmlgraphics-commons will also be upgraded (from 2.4 to 2.6) which resolved CVE-2020-11988
resolves [GEOT-6839](https://osgeo-org.atlassian.net/browse/GEOT-6839) …
=> [GEOT-6839] Update Batik from 1.13 to 1.14

docs/user/library/referencing/faq.rst
=> fix typos in referencing faq

modules/unsupported/mbtiles/src/main/java/org/geotools/mbtiles/MBTilesFile.java, modules/unsupported/mbtiles/src/main/java/org/geotools/mbtiles/MBTilesMetadata.java, modules/unsupported/mbtiles/src/test/java/org/geotools/mbtiles/MBTilesFileTest.java
Adding "center" metadata parsing on MBTiles Metadata
=> [GEOT-6847]: Adding center metadata parsing on MBTiles Metadata

.github/workflows/oracle_online.yml
also:
- cleanup cached docker images
- cleanup android and dotnet sdk's 
before we start.
After cleanup:
```
Filesystem      Size  Used Avail Use% Mounted on
udev            3.4G     0  3.4G   0% /dev
tmpfs           696M  684K  695M   1% /run
/dev/sda1        84G   26G   58G  31% /
tmpfs           3.4G  8.0K  3.4G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        14G  4.1G  9.0G  32% /mnt
```
should give enough free space on `/` to download and run the large oracle docker image, because we started to see some failures once this job started running on ubuntu-20.04
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited …
=> run oracle online tests on ubuntu-18.04

.github/workflows/oracle_online.yml
also cleanup cached docker images before we start
also delete preinstalled dotnet and android
backport  #3408
=> [24.x backport] run oracle online tests on ubuntu-18.04

.github/workflows/oracle_online.yml
also cleanup cached docker images before we start
also delete preinstalled dotnet and android
backports #3408
=> [25.x backport] run oracle online tests on ubuntu-18.04 

modules/extension/xsd/xsd-sld/src/main/java/org/geotools/sld/bindings/SLDRasterSymbolizerBinding.java, modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDMockData.java, modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDRasterSymbolizerBindingTest.java, modules/library/xml/src/main/java/org/geotools/xml/styling/SLDParser.java, modules/library/xml/src/test/java/org/geotools/xml/styling/SLDParserTest.java
Jira ticket  https://osgeo-org.atlassian.net/browse/GEOT-6848
=> [GEOT-6848] Vendor options in RasterSymbolizer are not parsed

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccessFactory.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessRegistry.java, modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/AppSchemaDataAccessFactoryTest.java, modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/HiddenDataAccessDisposalPolymorphicTest.java
=> [GEOT-6681] App-Schema throws Duplicate Mapping on includedTypes

modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFReader.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFReaderTest.java
=> [GEOT-6849]:NetCDF Reader GridGeometry read fix

modules/unsupported/mbtiles/src/main/java/org/geotools/mbtiles/MBTilesFile.java, modules/unsupported/mbtiles/src/main/java/org/geotools/mbtiles/MBTilesMetadata.java, modules/unsupported/mbtiles/src/test/java/org/geotools/mbtiles/MBTilesFileTest.java
Backporting GEOT-6847 (Center attribute metadata parsing on MBTiles)
=> [GEOT-6847](Backport 25.x): Adding center metadata parsing on MBTiles Metadata

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterManager.java
See: https://osgeo-org.atlassian.net/browse/GEOT-6853
=> [GEOT-6853] ImageMosaic performs full scan aggregation on heterogenous mosaics

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterManager.java
Backport to 25.x of https://github.com/geotools/geotools/pull/3417
=> [GEOT-6853] ImageMosaic performs full scan aggregation on heterogenous mosaics (25.x)

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterManager.java
24.x backport of https://github.com/geotools/geotools/pull/3417
=> [GEOT-6853] ImageMosaic performs full scan aggregation on heterogenous mosaics (24.x)

modules/library/main/src/main/java/org/geotools/feature/ComplexAttributeImpl.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6856
=> [GEOT-6856] Replace new Collection method invocation via reflection with new ArrayList in ComplexAttributeImpl class

modules/unsupported/process-geometry/src/main/java/org/geotools/process/geometry/PolyLabeller.java, modules/unsupported/process-geometry/src/test/java/org/geotools/process/geometry/PolyLabellerTest.java
=> [GEOS-9907] Enable usage of labelPoint function in GetFeatureInfo requests

modules/library/main/src/main/java/org/geotools/data/DataAccessFactory.java
=> [GEOT-6863] Datastores with Character parameters can't be reopened

modules/library/main/src/main/java/org/geotools/data/DataAccessFactory.java
=> [GEOT-6863] Datastores with Character parameters can't be reopened backport 24.x

modules/library/main/src/main/java/org/geotools/data/DataAccessFactory.java
=> [GEOT-6863] Datastores with Character parameters can't be reopened backport to 25.x 

modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/FESConfiguration.java, modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/MeasureTypeBinding.java, modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/DistanceUnits.java, modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCDistanceTypeBinding.java, modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_1/OGCFilterTest.java, modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/bindings/GetFeatureTypeBindingTest.java
This PR is a backport of Alessandro Martellini Fix on 25.x .
The pb was detected using geoserver 18.2 with spatial filter (fex:DWithin), that does use geotools 24.x, while the fix only targeted 25.x (geoserver 19+)
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or …
=> [24.x backport][GEOT-6703] Dwithin old syntax no longer supported

modules/ogc/net.opengis.wfs/src/net/opengis/wfs20/StarStringType.java, modules/ogc/net.opengis.wfs/src/net/opengis/wfs20/impl/Wfs20PackageImpl.java, modules/ogc/net.opengis.wmts/src/net/opengis/gml311/SignType.java, modules/ogc/net.opengis.wmts/src/net/opengis/gml311/impl/DirectedEdgePropertyTypeImpl.java, modules/ogc/net.opengis.wmts/src/net/opengis/gml311/impl/DirectedFacePropertyTypeImpl.java, modules/ogc/net.opengis.wmts/src/net/opengis/gml311/impl/DirectedNodePropertyTypeImpl.java, modules/ogc/net.opengis.wmts/src/net/opengis/gml311/impl/DirectedTopoSolidPropertyTypeImpl.java, modules/ogc/net.opengis.wmts/src/net/opengis/gml311/impl/OrientableCurveTypeImpl.java, modules/ogc/net.opengis.wmts/src/net/opengis/gml311/impl/OrientableSurfaceTypeImpl.java
This allows geotools to be compiled ~~with~~ to Java 9+
=> [GEOT-6864] Avoid use of underscore as identifier

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGroupByVisitorOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGroupByVisitorOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostgisGroupByVisitorOnlineTest.java
See https://osgeo-org.atlassian.net/browse/GEOT-6865
=> [GEOT-6865] PostGIS: SQL translation of DateDifference function fails against DATE columns

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGroupByVisitorOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGroupByVisitorOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostgisGroupByVisitorOnlineTest.java
Backport of https://github.com/geotools/geotools/pull/3446 
=> [GEOT-6865] PostGIS: SQL translation of DateDifference function failsagainst DATE columns (25.x)

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGroupByVisitorOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGroupByVisitorOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostgisGroupByVisitorOnlineTest.java
24.x backport of https://github.com/geotools/geotools/pull/3446
=> [GEOT-6865] PostGIS: SQL translation of DateDifference function fails against DATE columns (24.x)

pom.xml
Upgrade to latest version, making checks strict (by default order of elements is checked, but not formatting)
=> [GEOT-6857] Sortpom upgrade, making check strict

pom.xml
Backport of https://github.com/geotools/geotools/pull/3452
=> [GEOT-6857] Sortpom upgrade, making check strict (25.x)

pom.xml
Backport of https://github.com/geotools/geotools/pull/3452
=> [GEOT-6857] Sortpom upgrade, making check strict (24.x)

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileWriter.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/DbaseFileTest.java
Shapefile data is stored in dbase file format and text columns have a limit of 254 bytes.
getFieldString(int size, String s) is the method responsible for truncating an
input string to one that is small enough to fit into the column.
It does this by putting the string into a string buffer and then removing a character
at a time from the end, until the string fits. But for very long strings this can
take a rather long time. The reason that characters are removed one at a time is that
the limit is in bytes, and many charsets require mutliple bytes per character.
Careful reading of the StringBuffer.replace javadocs says that the sequence (buffer)
will be 'lengthened to accommodate the specified String if necessary' hence the buffer
becoming far bigger than expected.
Solution: use …
=> [GEOT-6859] Speed up geotools DbaseFileWriter.FieldFormatter.getFieldString(int size, String s)

modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/RuleBuilder.java, modules/extension/brewer/src/test/java/org/geotools/brewer/styling/builder/StyleBuilderTest.java, modules/extension/xsd/xsd-sld/src/main/java/org/geotools/sld/bindings/SLDRuleBinding.java, modules/extension/xsd/xsd-sld/src/main/resources/org/geotools/se/v1_1/FeatureStyle.xsd, modules/extension/xsd/xsd-sld/src/main/resources/org/geotools/sld/bindings/StyledLayerDescriptor.xsd, modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDMockData.java, modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDRuleBindingTest.java, modules/library/main/src/main/java/org/geotools/styling/Rule.java, modules/library/main/src/main/java/org/geotools/styling/RuleImpl.java, modules/library/xml/src/main/java/org/geotools/xml/styling/SLDParser.java, modules/library/xml/src/main/java/org/geotools/xml/styling/SLDTransformer.java, modules/library/xml/src/test/java/org/geotools/xml/styling/SLDParserTest.java, modules/library/xml/src/test/java/org/geotools/xml/styling/SLDTransformerTest.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6870
Add VendorOptions to sld Rule
=> [GEOT-6870] Add vendor options support for Rule

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureCollection.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/JdbcMultipleValue.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/MultipleValueExtractor.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6871
Integration tests provided here https://github.com/geoserver/geoserver/pull/4973
=> [GEOT-6871] AppSchema defining nested attribute with root attribute filter might return 0 on count

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureCollection.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/JdbcMultipleValue.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/MultipleValueExtractor.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java
* [GEOT-6871] AppSchema defining nested attribute with root attribute filter might return 0 on count
=> [25.x backport][GEOT-6871] AppSchema defining nested attribute with root attribute filter might return 0 on count (#3458)

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureCollection.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/JdbcMultipleValue.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/MultipleValueExtractor.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java
* [GEOT-6871] AppSchema defining nested attribute with root attribute filter might return 0 on count
=> [23.x backport][GEOT-6871] AppSchema defining nested attribute with root attribute filter might return 0 on count (#3458)

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureCollection.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/JdbcMultipleValue.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/MultipleValueExtractor.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java
* [GEOT-6871] AppSchema defining nested attribute with root attribute filter might return 0 on count
=> [24.x backport][GEOT-6871] AppSchema defining nested attribute with root attribute filter might return 0 on count

modules/library/main/src/main/java/org/geotools/feature/ComplexAttributeImpl.java
=> [25.x backport] [GEOT-6856] Replace new Collection method invocation via reflection with new ArrayList in ComplexAttributeImpl class

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java, modules/library/main/src/main/java/org/geotools/feature/visitor/UniqueCountVisitor.java, modules/library/main/src/test/java/org/geotools/feature/visitor/UniqueCountVisitorTest.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6874
This pr:
- adds a UniqueCountVisitor feature visitor extending the UniqueVisitor;
- adds an optimization path for it for JDBCDataStore
=> [GEOT-6874] Add support for count distinct aggregations in gt-jdbc

pom.xml
=> [GEOT-6877] Upgrade to imageio-ext 1.3.6 (tiff 32 bit with deflate/lzw support)

pom.xml
Backport of https://github.com/geotools/geotools/pull/3470 to 24.x
=> [GEOT-6877] Upgrade to imageio-ext 1.3.6 (tiff 32 bit with deflate/lzw with predictor 2) 24.x

pom.xml
Backport of https://github.com/geotools/geotools/pull/3470/commits to 25.x
=> [GEOT-6877] Upgrade to imageio-ext 1.3.6 (tiff 32 bit with deflate/lzw with predictor 2) 25.x

modules/library/main/src/main/java/org/geotools/feature/ComplexAttributeImpl.java
=> [24.x backport][GEOT-6856] Replace new Collection method invocation via reflection with new ArrayList in ComplexAttributeImpl class

modules/library/xml/src/main/java/org/geotools/xml/resolver/SchemaCache.java, modules/library/xml/src/test/java/org/geotools/xml/resolver/SchemaCacheOnlineTest.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6860
this pr: 
- makes the SchemaCache able to follow a redirect when downloading;
- fix an https url in the online-test replacing a not working one causing the test to fail …
=> [GEOT-6860] SchemaCache doesn't follow redirect when downloading from HttpConnection

modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/RuleBuilder.java, modules/extension/brewer/src/test/java/org/geotools/brewer/styling/builder/StyleBuilderTest.java, modules/extension/xsd/xsd-sld/src/main/java/org/geotools/sld/bindings/SLDRuleBinding.java, modules/extension/xsd/xsd-sld/src/main/resources/org/geotools/se/v1_1/FeatureStyle.xsd, modules/extension/xsd/xsd-sld/src/main/resources/org/geotools/sld/bindings/StyledLayerDescriptor.xsd, modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDMockData.java, modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDRuleBindingTest.java, modules/library/main/src/main/java/org/geotools/styling/Rule.java, modules/library/main/src/main/java/org/geotools/styling/RuleImpl.java, modules/library/xml/src/main/java/org/geotools/xml/styling/SLDParser.java, modules/library/xml/src/main/java/org/geotools/xml/styling/SLDTransformer.java, modules/library/xml/src/test/java/org/geotools/xml/styling/SLDParserTest.java, modules/library/xml/src/test/java/org/geotools/xml/styling/SLDTransformerTest.java
Early backport request here https://sourceforge.net/p/geotools/mailman/message/37265419/
* [GEOT-6870] Add vendor options support for Rule …
=> [25.x backport][GEOT-6870] Add vendor options support for Rule (#3457)

modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/RuleBuilder.java, modules/extension/brewer/src/test/java/org/geotools/brewer/styling/builder/StyleBuilderTest.java, modules/extension/xsd/xsd-sld/src/main/java/org/geotools/sld/bindings/SLDRuleBinding.java, modules/extension/xsd/xsd-sld/src/main/resources/org/geotools/se/v1_1/FeatureStyle.xsd, modules/extension/xsd/xsd-sld/src/main/resources/org/geotools/sld/bindings/StyledLayerDescriptor.xsd, modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDMockData.java, modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDRuleBindingTest.java, modules/library/main/src/main/java/org/geotools/styling/Rule.java, modules/library/main/src/main/java/org/geotools/styling/RuleImpl.java, modules/library/xml/src/main/java/org/geotools/xml/styling/SLDParser.java, modules/library/xml/src/main/java/org/geotools/xml/styling/SLDTransformer.java, modules/library/xml/src/test/java/org/geotools/xml/styling/SLDParserTest.java, modules/library/xml/src/test/java/org/geotools/xml/styling/SLDTransformerTest.java
Early backport request here https://sourceforge.net/p/geotools/mailman/message/37265419/
* [GEOT-6870] Add vendor options support for Rule …
=> [24.x backport] [GEOT-6870] Add vendor options support for Rule (#3457)

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java, modules/library/main/src/main/java/org/geotools/feature/visitor/UniqueCountVisitor.java, modules/library/main/src/test/java/org/geotools/feature/visitor/UniqueCountVisitorTest.java
Early backport request [here](https://sourceforge.net/p/geotools/mailman/message/37271370/)
=> [24.x backport][GEOT-6874] Add support for count distinct aggregations in gt-jdbc

modules/library/render/src/main/java/org/geotools/renderer/lite/ZGroupLayer.java, modules/library/render/src/test/java/org/geotools/renderer/lite/ZOrderTest.java
=> [GEOT-6880] Rendering process fails if vendor option sortByGroup is used (24.x)

build/qa/pmd-ruleset.xml, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AttributeMapping.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/SourceDataStore.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/TypeMapping.java, modules/extension/brewer/src/main/java/org/geotools/brewer/color/StyleGenerator.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xs/bindings/XSNegativeIntegerStrategyTest.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xs/bindings/XSNonNegativeIntegerStrategyTest.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xs/bindings/XSNonPositiveIntegerStrategyTest.java, modules/library/main/src/main/java/org/geotools/feature/visitor/QuantileListVisitor.java, modules/library/main/src/main/java/org/geotools/filter/function/ClassificationFunction.java, modules/library/main/src/main/java/org/geotools/filter/function/EqualIntervalFunction.java, modules/library/main/src/main/java/org/geotools/filter/function/UniqueIntervalFunction.java, modules/library/main/src/test/java/org/geotools/data/util/NumericConverterFactoryTest.java, modules/library/main/src/test/java/org/geotools/filter/IsEqualsToImplTest.java, modules/library/xml/src/main/java/org/geotools/xml/handlers/xsi/ComplexTypeHandler.java, modules/library/xml/src/main/java/org/geotools/xml/handlers/xsi/ElementTypeHandler.java, modules/library/xml/src/main/java/org/geotools/xml/impl/DatatypeConverterImpl.java, modules/library/xml/src/main/java/org/geotools/xml/styling/SLDParser.java, modules/plugin/grassraster/src/main/java/org/geotools/gce/grassraster/JGrassRegion.java, modules/plugin/grassraster/src/main/java/org/geotools/gce/grassraster/core/GrassBinaryRasterReadHandler.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/sdo/GeometryConverter.java, modules/unsupported/gtopo30/src/main/java/org/geotools/gce/gtopo30/GTopo30Writer.java, modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrFeatureSource.java, modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/io/TripletId.java
See: https://pmd.github.io/latest/pmd_rules_java_performance.html#unnecessarywrapperobjectcreation
=> [GEOT-6878] Avoid unnecessary object wrapper creation, add a PMD rule to check it

modules/extension/wms/src/main/java/org/geotools/ows/wms/WMS1_0_0.java, modules/extension/wms/src/main/java/org/geotools/ows/wms/WMS1_1_0.java, modules/extension/wms/src/main/java/org/geotools/ows/wms/request/AbstractGetLegendGraphicRequest.java, modules/extension/wms/src/main/java/org/geotools/ows/wms/request/AbstractWMSRequest.java, modules/extension/wms/src/test/java/org/geotools/ows/wms/test/GetCapabilitiesRequestTest.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WMTSSpecification.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WMTSSpecificationTest.java, modules/library/main/src/main/java/org/geotools/data/ows/AbstractRequest.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/GetCapabilitiesRequest.java, modules/unsupported/wps/src/main/java/org/geotools/data/wps/WPS1_0_0.java, modules/unsupported/wps/src/main/java/org/geotools/data/wps/request/AbstractWPSRequest.java
=> [GEOT-6677] Do not modify non-standard keywords as this will break badly written servers

modules/library/xml/src/main/java/org/geotools/xml/resolver/SchemaCache.java, modules/library/xml/src/test/java/org/geotools/xml/resolver/SchemaCacheOnlineTest.java
* [GEOT-6860] SchemaCache doesn't follow redirect when downloading from HttpConnection
=> [24.x backport][GEOT-6860] SchemaCache doesn't follow redirect when downloading from HttpConnection (#3429)

modules/library/xml/src/main/java/org/geotools/xml/resolver/SchemaCache.java, modules/library/xml/src/test/java/org/geotools/xml/resolver/SchemaCacheOnlineTest.java
* [GEOT-6860] SchemaCache doesn't follow redirect when downloading from HttpConnection
=> [25.x backport][GEOT-6860] SchemaCache doesn't follow redirect when downloading from HttpConnection (#3429)

.github/workflows/db2_online.yml, .github/workflows/geopkg_online.yml, .github/workflows/integration.yml, .github/workflows/linux_jdk11.yml, .github/workflows/linux_jdk8.yml, .github/workflows/macos.yml, .github/workflows/mssql_online.yml, .github/workflows/mysql_online.yml, .github/workflows/oracle_online.yml, .github/workflows/postgis_online.yml, .github/workflows/qa.yml, .github/workflows/windows.yml
As per our discussion on the gt-devel list, tries to use the same cache key across all builds.
=> Share pull request repository cache across builds

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSDataAccessFactory.java
=> Fix typo - correct type for WFSFactoryParam

modules/library/metadata/src/main/java/org/geotools/util/DateTimeParser.java, modules/library/metadata/src/test/java/org/geotools/util/DateTimeParserTest.java
Added a check that will exit the loop when attempting to parse certain invalid inputs.
https://osgeo-org.atlassian.net/browse/GEOT-6883
=> [GEOT-6883] Fix edge cases in the date time parser

modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java, modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/ContourProcessTest.java, modules/unsupported/process-raster/src/test/resources/org/geotools/process/raster/test-data/contour_multi_fts_with_opacity.sld, modules/unsupported/process-raster/src/test/resources/org/geotools/process/raster/test-data/contour_multi_fts_without_opacity.sld
[![GEOT-6886](https://badgen.net/badge/JIRA/GEOT-6886/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6886) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR moves the projection handling code for raster to vector rendering transformations from the plain renderer into a separate method that is called by both the plain renderer and the optimized renderer.
https://osgeo-org.atlassian.net/browse/GEOT-6886
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and …
=> [GEOT-6886] Raster to Vector rendering transformations with reprojection can generate incorrect images

modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java, modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/ContourProcessTest.java, modules/unsupported/process-raster/src/test/resources/org/geotools/process/raster/test-data/contour_multi_fts_with_opacity.sld, modules/unsupported/process-raster/src/test/resources/org/geotools/process/raster/test-data/contour_multi_fts_without_opacity.sld
[![GEOT-6886](https://badgen.net/badge/JIRA/GEOT-6886/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6886) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
24.x backport for https://github.com/geotools/geotools/pull/3499 …
=> [24.x][GEOT-6886] Raster to Vector rendering transformations with reprojection can generate incorrect images

modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java, modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/ContourProcessTest.java, modules/unsupported/process-raster/src/test/resources/org/geotools/process/raster/test-data/contour_multi_fts_with_opacity.sld, modules/unsupported/process-raster/src/test/resources/org/geotools/process/raster/test-data/contour_multi_fts_without_opacity.sld
[![GEOT-6886](https://badgen.net/badge/JIRA/GEOT-6886/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6886) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
25.x backport for https://github.com/geotools/geotools/pull/3499 …
=> [25.x][GEOT-6886] Raster to Vector rendering transformations with reprojection can generate incorrect images

modules/library/metadata/src/main/java/org/geotools/util/DateTimeParser.java, modules/library/metadata/src/test/java/org/geotools/util/DateTimeParserTest.java
[![GEOT-6883](https://badgen.net/badge/JIRA/GEOT-6883/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6883) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
25.x backport for https://github.com/geotools/geotools/pull/3496 …
=> [25.x][GEOT-6883] Fix edge cases in the date time parser

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-6898](https://badgen.net/badge/JIRA/GEOT-6898/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6898) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket for details. Existing tests have been modified, rather than adding new ones.
The …
=> [GEOT-6898] Read only GeoPackages fail when using the new GPKG application id

modules/library/main/src/main/java/org/geotools/filter/ExpressionDOMParser.java, modules/library/main/src/test/java/org/geotools/filter/ExpressionDomParserTest.java
[![GEOT-6892](https://badgen.net/badge/JIRA/GEOT-6892/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6892) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with …
=> [GEOT-6892] ExpressionDomParser early NPE

modules/unsupported/gml-geometry-streaming/src/main/java/org/geotools/gml/stream/XmlStreamGeometryReader.java, modules/unsupported/gml-geometry-streaming/src/test/java/org/geotools/gml/stream/XmlStreamGeometryReaderParameterizedTest.java
[![GEOT-6903](https://badgen.net/badge/JIRA/GEOT-6903/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6903) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Uses the CurvedGeometryFactory to create MultiSurfaces if there are curves in the shell or holes.
Simplified Arc coordinates parsing and removed restriction of 3 control points.
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus limited in time). We need to keep the review overhead as small as possible, and appreciate if you help us to do so by completing the following items. Feel free to …
=> [GEOT-6903] Add support for curved polygons and Arcs with more than 3 control points to gml-geometry-streaming

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapeFileIndexer.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileIndexerBoundsHelper.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/index/quadtree/QuadTree.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapeFileIndexerStressTest.java
[![GEOT-6900](https://badgen.net/badge/JIRA/GEOT-6900/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6900) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #3528 to `25.x`
=> [GEOT-6900][backport 25.x] Shapefile quadtree build performance improvements

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapeFileIndexer.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileIndexerBoundsHelper.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/index/quadtree/QuadTree.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapeFileIndexerStressTest.java
[![GEOT-6900](https://badgen.net/badge/JIRA/GEOT-6900/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6900) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #3528 to `24.x`
=> [GEOT-6900][backport 24.x] Shapefile quadtree build performance improvements

modules/plugin/shapefile/pom.xml, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/IndexManager.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapeFileIndexer.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/IndexManagerTest.java
[![GEOT-6899](https://badgen.net/badge/JIRA/GEOT-6899/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6899) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #3527 to `24.x`
=> [GEOT-6899][backport 24.x] Resource (CPU/Heap) starvation building shapefile spatial index

modules/plugin/shapefile/pom.xml, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/IndexManager.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapeFileIndexer.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/IndexManagerTest.java
[![GEOT-6899](https://badgen.net/badge/JIRA/GEOT-6899/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6899) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport of #3527 to `25.x`
=> [GEOT-6899][backport 25.x] Resource (CPU/Heap) starvation building shapefile spatial index

modules/library/metadata/src/main/java/org/geotools/util/DateTimeParser.java, modules/library/metadata/src/test/java/org/geotools/util/DateTimeParserTest.java
[![GEOT-6883](https://badgen.net/badge/JIRA/GEOT-6883/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6883) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
24.x backport for https://github.com/geotools/geotools/pull/3496 …
=> [24.x][GEOT-6883] Fix edge cases in the date time parser

modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/AncillaryFileManager.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/VariableAdapter.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/utilities/NetCDFUtilities.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFCRSTest.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFReaderTest.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/imageio/netcdf/NetCDFUtilitiesTest.java
[![GEOT-6902](https://badgen.net/badge/JIRA/GEOT-6902/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6902) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
A few caching improvements on NetCDF plugin
https://osgeo-org.atlassian.net/browse/GEOT-6902
The …
=> [GEOT-6902]: NetCDF dataset access performance improvements

modules/library/main/src/test/java/org/geotools/filter/CapabilitiesTest.java, modules/library/opengis/src/main/java/org/opengis/filter/PropertyIsGreaterThanOrEqualTo.java, modules/library/opengis/src/main/java/org/opengis/filter/PropertyIsLessThanOrEqualTo.java
[![GEOT-6881](https://badgen.net/badge/JIRA/GEOT-6881/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6881) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fix name of capabilities to align with WFS specs.
The following are required only for core and …
=> [GEOT-6881] GreaterThanEqualTo and LessThanEqualTo incorrectly marked as unsupported in WFS query

modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/AncillaryFileManager.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/VariableAdapter.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/utilities/NetCDFUtilities.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFCRSTest.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFReaderTest.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/imageio/netcdf/NetCDFUtilitiesTest.java
[![GEOT-6902](https://badgen.net/badge/JIRA/GEOT-6902/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6902) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backporting GEOT-6902 work to 25.x
=> [Backport-25.x][GEOT-6902]: NetCDF dataset access performance improvements

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGroupByVisitorOnlineTest.java, modules/library/main/src/main/java/org/geotools/data/util/AbbreviatedTimeUnitConverterFactory.java, modules/library/main/src/main/java/org/geotools/filter/function/DateDifferenceFunction.java, modules/library/main/src/main/resources/META-INF/services/org.geotools.util.ConverterFactory, modules/library/main/src/test/java/org/geotools/data/util/AbbreviatedTimeUnitConverterFactoryTest.java, modules/library/main/src/test/java/org/geotools/filter/function/DateDifferenceTest.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java
[![GEOT-6917](https://badgen.net/badge/JIRA/GEOT-6917/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6917) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket: [GEOT-6917]
The following are required only for core and extension modules (they are …
=> [GEOT-6917]: DateDifference function supporting time units

modules/library/main/src/main/java/org/geotools/filter/function/NowFunction.java, modules/library/main/src/main/resources/META-INF/services/org.opengis.filter.expression.Function, modules/library/main/src/test/java/org/geotools/filter/function/DateDifferenceTest.java
[![GEOT-6918](https://badgen.net/badge/JIRA/GEOT-6918/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6918) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See [GEOT-6918]:
The following are required only for core and extension modules (they are welcomed, …
=> [GEOT-6918]: Implementing now function

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/datasource/JNDIDataSourceFactory.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCJNDIDataStoreFactory.java, modules/library/metadata/src/main/java/org/geotools/util/factory/GeoTools.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/AbstractEpsgMediator.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/epsg/AbstractEpsgFactory.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/epsg/ThreadedEpsgFactory.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/PGRasterConfig.java
[![GEOT-6889](https://badgen.net/badge/JIRA/GEOT-6889/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6889) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The function getInitialContext threw an IllegalArgumentException that caller didn't catch. The functionality behind new InitialContext is rather mysterious, so I've tried to log those variables that I've seen influence it. That might change by time.
Lastly the argument hints wasn't used, and probably that was the whole problem for me.
Reviewing is a process done by project maintainers, **mostly on a volunteer basis** (thus …
=> [GEOT-6889] Configuration of JNDI and exception handling

modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WMTSHelper.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WMTSSpecification.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/TileURLBuilder.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTile.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTileService.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WMTSHelperTest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/client/TileURLBuilderTest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/client/WMTSTileFactory4326Test.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/RestWMTSOnlineTest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/WebMapTileServerOnlineTest.java
[![GEOT-6895](https://badgen.net/badge/JIRA/GEOT-6895/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6895) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The goal of this PR is to clean up the separation between WebMapTileServer and WMTSTileServer. WebMapTileServer will deal with the capabilities document, and give out information about available layers, styles and formats. WMTSTileServer is a subclass of TileServer and should only deal with one single cache of images for a specific layer, style.
I've added some helper classes based on code fragments I found, and to make url …
=> [GEOT-6895] - Restrict the responsibilities of WMTSTileService

modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WMTSHelper.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WMTSSpecification.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/TileURLBuilder.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTile.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTileService.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WMTSHelperTest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/client/TileURLBuilderTest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/client/WMTSTileFactory4326Test.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/RestWMTSOnlineTest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/online/WebMapTileServerOnlineTest.java
Fixed the problem with url encoding.
=> [GEOT 6895] - Restrict the responsibilities of WMTSTileService - #2

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGroupByVisitorOnlineTest.java, modules/library/main/src/main/java/org/geotools/data/util/AbbreviatedTimeUnitConverterFactory.java, modules/library/main/src/main/java/org/geotools/filter/function/DateDifferenceFunction.java, modules/library/main/src/main/resources/META-INF/services/org.geotools.util.ConverterFactory, modules/library/main/src/test/java/org/geotools/data/util/AbbreviatedTimeUnitConverterFactoryTest.java, modules/library/main/src/test/java/org/geotools/filter/function/DateDifferenceTest.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java
[![GEOT-6917](https://badgen.net/badge/JIRA/GEOT-6917/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6917) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backporting GEOT-6917 to 25.x
=> [25.x-backport][GEOT-6917]: DateDifference function supporting time units

modules/library/main/src/main/java/org/geotools/filter/function/NowFunction.java, modules/library/main/src/main/resources/META-INF/services/org.opengis.filter.expression.Function, modules/library/main/src/test/java/org/geotools/filter/function/DateDifferenceTest.java
[![GEOT-6918](https://badgen.net/badge/JIRA/GEOT-6918/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6918) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backporting GEOT-6918 to 25.x
=> [Backport-25.x][GEOT-6918]: Implementing now function (#3558)

build/qa/pmd-ruleset.xml, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/model/WMTSCapabilities.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/bindings/ComplexSupportXSAnyTypeBinding.java, modules/library/xml/src/main/java/org/geotools/xml/handlers/xsi/ComplexTypeHandler.java, modules/library/xml/src/main/java/org/geotools/xml/impl/Duration.java, modules/library/xml/src/main/java/org/geotools/xml/impl/XsDateTimeFormat.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java, modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
[![GEOT-6925](https://badgen.net/badge/JIRA/GEOT-6925/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6925) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Current threshold is 160, this commit fixes methods down to the 140 threshold and enforces it.
The …
=> [GEOT-6925] Lowering CC threshold down to 140

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/catalog/GranuleCatalogFactory.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/HeterogenousCRSTest.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/QueryCollectingFeatureSource.java
[![GEOT-6938](https://badgen.net/badge/JIRA/GEOT-6938/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6938) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See tickets for details
The following are required only for core and extension modules (they are …
=> [GEOT-6938] Image mosaic: avoid sorting on CRS when doing a 'dry run' check after finding no granules in the target area

modules/extension/tile-client/pom.xml, modules/extension/wms/pom.xml, modules/extension/wms/src/test/java/org/geotools/ows/wms/map/WMSCoverageReaderTest.java, modules/extension/wms/src/test/java/org/geotools/ows/wms/map/WMSLayerTest.java, modules/plugin/http-commons/pom.xml, modules/plugin/http-commons/src/main/java/org/geotools/http/commons/MultithreadedHttpClient.java, modules/plugin/http-commons/src/test/java/org/geotools/http/commons/MultithreadedHttpClientTest.java, modules/unsupported/wfs-ng/pom.xml, pom.xml
[![GEOT-5859](https://badgen.net/badge/JIRA/GEOT-5859/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-5859) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The following are …
=> [GEOT-5859] upgrade httpclient

modules/plugin/mongodb/README.rst
Fix typo comma in GeoJSON properties Object.
- [ ✓] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/main/CONTRIBUTING.md)
- [ ✓] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [ ✓] Make sure the first PR targets the `main` branch, eventual backports …
=> Typo comma in GeoJSON json

.github/PULL_REQUEST_TEMPLATE.md
We are trying to make the PR template easier to read, more approachable and easier to understand.
=> Make Pull Request template shorter and more approachable

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
[![GEOT-6937](https://badgen.net/badge/JIRA/GEOT-6937/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6937) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [24.x backport][GEOT-6937] AppSchema JdbcMultipleValue will fill wrong values if targetColumn is a PK (#3579)

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
[![GEOT-6937](https://badgen.net/badge/JIRA/GEOT-6937/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6937) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [25.x backport][GEOT-6937] AppSchema JdbcMultipleValue will fill wrong values if targetColumn is a PK (#3579)

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicDirectoryWalker.java
=> undo inadvertant commit to main

build/qa/dependency-check-suppression.xml, pom.xml
and update the config to suppress false positives for MySQL and DB2 server.
even though this profile does not currently run on the project CI services it pays to keep up-to-date; and I have it running in a personal branch
=> Bump org.owasp:dependency-check-maven to 6.2.2

pom.xml
[![GEOT-6952](https://badgen.net/badge/JIRA/GEOT-6952/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6952) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Upgrade various JDBC drivers for the databases we support as subtasks of [GEOT-6952](https://osgeo-org.atlassian.net/browse/GEOT-6952):
=> [GEOT-6952] upgrade JDBC drivers

modules/library/main/src/test/java/org/geotools/filter/CapabilitiesTest.java, modules/library/opengis/src/main/java/org/opengis/filter/PropertyIsGreaterThanOrEqualTo.java, modules/library/opengis/src/main/java/org/opengis/filter/PropertyIsLessThanOrEqualTo.java
[![GEOT-6881](https://badgen.net/badge/JIRA/GEOT-6881/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6881) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
backports #3543
=> [GEOT-6881] [Backport 25.x] GreaterThanEqualTo and LessThanEqualTo incorrectly marked as unsupported in WFS query

docs/user/unsupported/arcgis-rest.rst
[![GEOT-6783](https://badgen.net/badge/JIRA/GEOT-6783/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6783) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Changed the documentation to make it clear how to include this module with Maven.
=> [GEOT-6783] Unsupported module gt-arcgisrest isn't activated by -Dall

modules/library/main/src/test/java/org/geotools/filter/CapabilitiesTest.java, modules/library/opengis/src/main/java/org/opengis/filter/PropertyIsGreaterThanOrEqualTo.java, modules/library/opengis/src/main/java/org/opengis/filter/PropertyIsLessThanOrEqualTo.java
[![GEOT-6881](https://badgen.net/badge/JIRA/GEOT-6881/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6881) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
backports #3543
=> [GEOT-6881] [Backport 24.x] GreaterThanEqualTo and LessThanEqualTo incorrectly marked as unsupported in WFS query

.github/workflows/oracle_online.yml, build/ci/oracle/start-oracle.sh, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleNativeFilterTestSetup.java
Change to a docker image that is about 3.4GB (and appears to be maintained), while the other is 12.7GB (and hasn't seen any updates), so this should shave off some download time, startup time of a container seemed pretty much the same for both at ~30sec
These changes shave roughly 5min (~30%) off the Oracle online build/test.
Note that this docker image has all Java packages removed from Oracle so you cannot use Java Stored Procedures such as `SDO_GEOMETRY('POINT (1.0 2.0)', 4326))` (that parses a WKT) but need top use `SDO_GEOMETRY(2001, 4326, SDO_POINT_TYPE(1.0, 2.0, NULL), NULL, NULL))` instead.
=> [CI] Use a smaller Oracle docker image for online test speedup

.github/workflows/oracle_online.yml, build/ci/oracle/start-oracle.sh, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleNativeFilterTestSetup.java
=> [CI][25.x backport] Use a smaller Oracle docker image for the tests

modules/library/xml/src/main/java/org/geotools/gml/producer/CoordinateFormatter.java, modules/library/xml/src/test/java/org/geotools/gml/producer/CoordinateFormatterTest.java
[![GEOT-6960](https://badgen.net/badge/JIRA/GEOT-6960/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6960) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Amend range in which force decimals is applied, add some tests to cover the changes, leaving existing tests intact. 
=> [GEOT-6960] Amend condition in which force decimals will be applied

modules/library/http/src/main/java/org/geotools/http/SimpleHttpClient.java, modules/library/http/src/test/java/org/geotools/http/HTTPClientFinderTest.java
[![GEOT-6959](https://badgen.net/badge/JIRA/GEOT-6959/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6959) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Correcting a wrong assumption that SimpleHttpClient didn't support proxy servers.
=> [GEOT-6959] SimpleHttpClient does support proxy

pom.xml
[![GEOT-6968](https://badgen.net/badge/JIRA/GEOT-6968/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6968) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Signed-off-by: Jim Hughes <jhughes@ccri.com>
=> [GEOT-6968] Upgrade to JTS Topology Suite 1.18.2

docs/user/unsupported/gml-geometry-streaming.rst, docs/user/unsupported/index.rst, modules/unsupported/gml-geometry-streaming/src/main/java/org/geotools/gml/stream/XmlStreamGeometryReader.java
[![GEOT-6974](https://badgen.net/badge/JIRA/GEOT-6974/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6974) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-6974] Document gt-gml-geometry-streaming

modules/unsupported/elasticsearch/pom.xml, pom.xml
[![GEOT-6975](https://badgen.net/badge/JIRA/GEOT-6975/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6975) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Updates:
```
org.elasticsearch.client:elasticsearch-rest-client ... 7.10.2 -> 7.14.0
org.locationtech.spatial4j:spatial4j ....................... 0.6 -> 0.8
com.github.davidmoten:geo .............................. 0.7.4 -> 0.7.7
com.google.guava:guava ......................... 30.1-jre -> 30.1.1-jre
joda-time:joda-time ................................. 2.10.1 -> 2.10.10
org.testcontainers:elasticsearch ..................... …
```
=> [GEOT-6975] Update dependencies of (unsupported) Elasticsearch plugin

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/EmfAppSchemaParser.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/parsers/EmfAppSchemaParserTest.java
[![GEOT-6976](https://badgen.net/badge/JIRA/GEOT-6976/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6976) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-6976] wfs-ng memory leak

modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerFilterToSQL.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerBooleanOnlineTest.java
[![GEOT-6410](https://badgen.net/badge/JIRA/GEOT-6410/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6410) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-6410] Conversion from boolean true/false in geoserver to SQL Server bit 0/1, is broken

pom.xml
[![GEOT-6978](https://badgen.net/badge/JIRA/GEOT-6978/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6978) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
various bugs were fixed:
> 19.12 is the July Critical Patch Update (CPU) which contains NNE fix for the vulnerability CVE-2021-2351. 
Refer MOS note 2791571.1 for more details. 
https://download.oracle.com/otn-pub/otn_software/jdbc/1912/Bugs-fixed-in-1912.txt?AuthParam=1630677373_aa32ffb5ac7010ff22aa4f210ae6fc6c
=> [GEOT-6978] Upgrade Oracle JDBC driver (com.oracle.database.jdbc:ojdbc8) 19.11.0.0 ➜ 19.12.0.0

modules/plugin/mongodb/pom.xml
[![GEOT-6982](https://badgen.net/badge/JIRA/GEOT-6982/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6982) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
backports #3632 to 25.x
=> [25.x backport][GEOT-6982] Update Mongo DB driver to 4.0.6 to mitigate CVE-2021-20328

modules/library/xml/src/main/java/org/geotools/xml/styling/SLDTransformer.java, modules/library/xml/src/main/java/org/geotools/xml/transform/TransformerBase.java
[![GEOT-6981](https://badgen.net/badge/JIRA/GEOT-6981/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6981) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
In working with a bug [GEOS-10220](https://osgeo-org.atlassian.net/browse/GEOS-10220) I added some code that might be useful for others.
=> [GEOT-6981] Report on missing functionality in sld serializing

modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/MaskOverviewProvider.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/AncillaryFileManager.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/VariableAdapter.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/utilities/NetCDFUtilities.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFCRSTest.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFReaderTest.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/imageio/netcdf/NetCDFUtilitiesTest.java
[![GEOT-6902](https://badgen.net/badge/JIRA/GEOT-6902/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6902) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport to 23.x
=> [23.x-backport][GEOT-6902]: NetCDF dataset access performance improvements

modules/library/render/src/main/java/org/geotools/renderer/style/DynamicSymbolFactoryFinder.java, modules/library/render/src/main/java/org/geotools/renderer/style/MarkFactoryListComparator.java, modules/library/render/src/main/java/org/geotools/renderer/style/MarkFactoryListPredicate.java, modules/library/render/src/main/java/org/geotools/renderer/style/SLDStyleFactory.java, modules/library/render/src/test/java/org/geotools/renderer/style/SLDStyleFactoryTest.java
[![GEOT-6948](https://badgen.net/badge/JIRA/GEOT-6948/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6948) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR introduces support for filtering and ordering hints on mark factories during rendering.
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOT-6948
Proposal:
https://github.com/geotools/geotools/wiki/Rendering-pre-process-Mark-Factories-Hint
=> [GEOT-6948] MarkFactory performance optimization hints support

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSource.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSContentComplexFeatureCollection.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlComplexFeatureParser.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlFeatureParser.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSourceTest.java
[![GEOT-6961](https://badgen.net/badge/JIRA/GEOT-6961/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6961) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
There were some problems calling getFeatures for a WFS with complex structure. With these changes, I managed to iterate through the whole response.
In addition to the problems described in the ticket, there was a problem with reading geometry. That I solved in the same manner as other complex structures within that function.
=> [GEOT-6961] - WFSContentComplexFeatureSource.getFeatures must use correct namespace

modules/extension/tile-client/pom.xml, modules/extension/tile-client/src/main/java/org/geotools/tile/TileService.java, modules/extension/tile-client/src/main/java/org/geotools/tile/impl/bing/BingService.java, modules/extension/tile-client/src/main/java/org/geotools/tile/impl/bing/BingTileFactory.java, modules/extension/tile-client/src/main/java/org/geotools/tile/impl/osm/OSMService.java, modules/extension/tile-client/src/main/java/org/geotools/tile/impl/osm/OSMTileFactory.java, modules/extension/tile-client/src/test/java/org/geotools/tile/TileServiceTest.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTileFactory.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTileService.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/client/WMTSTileFactory4326Test.java
[![GEOT-6989](https://badgen.net/badge/JIRA/GEOT-6989/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6989) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The function addTileToCache isn't used properly. The purpose is to add the incoming tile to a cache if it's not there, and then return the tile that's in the cache. Which should be the one used thereafter. It doesn't seem to be used in such a way.
My suggestion is to use a different name, and use a tile as an argument, but the tile identifier which is actually what's being used in cache-lookup.
Tile addTileToCache(Tile tile) …
=> [GEOT-6989] Replace method addTileToCache of TileService

modules/library/main/src/main/java/org/geotools/data/directory/DirectoryTypeCache.java, modules/library/main/src/main/java/org/geotools/data/directory/FilteringFileStoreFactory.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStore.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStoreFactory.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/files/ShpFiles.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShpFilesTest.java
[![GEOT-7007](https://badgen.net/badge/JIRA/GEOT-7007/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7007) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
[Backport-26.x][GEOT-7007]
=> [Backport-26.x][GEOT-7007]: Performance improvement on shapeFiles directory handling

modules/extension/graph/src/main/java/org/geotools/graph/io/standard/SerializedReaderWriter.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java, modules/library/coverage/src/test/java/org/geotools/coverage/grid/GridCoverageTestBase.java, modules/library/cql/src/test/java/org/geotools/filter/text/cql2/FilterToCQLTest.java, modules/library/main/src/main/java/org/geotools/data/sort/SimpleFeatureIO.java, modules/library/main/src/test/java/org/geotools/feature/FeatureFlatTest.java, modules/library/main/src/test/java/org/geotools/feature/NameImplTest.java, modules/library/main/src/test/java/org/geotools/filter/FunctionExpressionImplTest.java, modules/library/metadata/src/test/java/org/geotools/util/InternationalStringTest.java, modules/library/metadata/src/test/java/org/geotools/util/PartiallyOrderedSetTest.java, modules/library/referencing/src/main/java/org/geotools/geometry/GeneralDirectPosition.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/epsg/DirectEpsgFactory.java, modules/library/referencing/src/main/java/org/geotools/referencing/operation/matrix/GeneralMatrix.java, modules/library/referencing/src/test/java/org/geotools/measure/UnitsTest.java, modules/library/referencing/src/test/java/org/geotools/parameter/ParametersTest.java, modules/library/referencing/src/test/java/org/geotools/referencing/PredefinedObjectsTest.java, modules/library/referencing/src/test/java/org/geotools/referencing/factory/URN_ParserTest.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileTest.java, modules/unsupported/swing/src/test/java/org/geotools/swing/tool/CursorToolTest.java, pom.xml
[![GEOT-7010](https://badgen.net/badge/JIRA/GEOT-7010/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7010) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Updates version and fixes/suppresses issues found.
=> [GEOT-7010] Update ErrorProne to 2.9.0

modules/library/main/src/main/java/org/geotools/data/directory/DirectoryTypeCache.java, modules/library/main/src/main/java/org/geotools/data/directory/FilteringFileStoreFactory.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStore.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStoreFactory.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/files/ShpFiles.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShpFilesTest.java
[![GEOT-7007](https://badgen.net/badge/JIRA/GEOT-7007/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7007) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
[Backport-25.x][GEOT-7007]: Performance improvement on shapeFiles directory handling
=> [Backport-25.x][GEOT-7007]: Performance improvement on shapeFiles directory handling

modules/library/main/src/main/java/org/geotools/renderer/crs/OrthographicProjectionHandlerFactory.java, modules/library/main/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java, modules/library/main/src/main/resources/META-INF/services/org.geotools.renderer.crs.ProjectionHandlerFactory, modules/library/main/src/test/java/org/geotools/renderer/crs/OrthographicProjectionHandlerFactoryTest.java
[![GEOT-7020](https://badgen.net/badge/JIRA/GEOT-7020/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7020) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
A few pictures:
=> [GEOT-7020] Add ProjectionHandler for orthographic

.github/workflows/db2_online.yml, .github/workflows/geopkg_online.yml, .github/workflows/integration.yml, .github/workflows/linux_jdk11.yml, .github/workflows/linux_jdk17.yml, .github/workflows/linux_jdk8.yml, .github/workflows/macos.yml, .github/workflows/mssql_online.yml, .github/workflows/mysql_online.yml, .github/workflows/oracle_online.yml, .github/workflows/postgis_online.yml, .github/workflows/qa.yml, .github/workflows/windows.yml, build/ci/db2/start-db2.sh, build/ci/oracle/start-oracle.sh, docs/developer/conventions/test/online.rst
I'm not sure if there are incompatibilities between these two and if it's worth the extra overhead (our Oracle Online tests take about 10 minutes, making them the slowest already, OTOH adding doesn't add 10 mins. as these builds run in parallel. Note that during the last 2 weeks we silently wen from 18.4.0 to 21.3.0 because we were using the `latest` tag in our workflow
=> Update docker images and actions in github CI

.github/workflows/elasticsearch_online.yml, modules/unsupported/elasticsearch/pom.xml, modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticTestSupport.java
[![GEOT-7021](https://badgen.net/badge/JIRA/GEOT-7021/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7021) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Adding a Github action to run ElasticSearch online tests (they are based on [testcontainers](https://www.testcontainers.org/), so no need for a dedicated docker image, testcontainers runs it for us).
=> [GEOT-7021] Run ElasticSearch integration tests in GitHub actions

pom.xml
=> [QA] Bump org.owasp:dependency-check-maven from 6.2.2 to 6.5.0

build/ci/oracle/start-oracle.sh
It seems that the 21.3.0 image has been broken.
see also #3678
=> [CI] downgrade Oracle docker image to gvenzl/oracle-xe:18.4.0

modules/library/referencing/src/main/java/org/geotools/referencing/factory/DeferredAuthorityFactory.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/epsg/ThreadedEpsgFactory.java, modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffCRSFactoryDeadlockTest.java
[![GEOT-7022](https://badgen.net/badge/JIRA/GEOT-7022/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7022) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [Backport-25.x][GEOT-7022]: Referencing factories deadlock prevention

modules/library/referencing/src/main/java/org/geotools/referencing/factory/DeferredAuthorityFactory.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/epsg/ThreadedEpsgFactory.java, modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffCRSFactoryDeadlockTest.java
[![GEOT-7022](https://badgen.net/badge/JIRA/GEOT-7022/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7022) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [Backport-26.x][GEOT-7022]: Referencing factories deadlock prevention

modules/unsupported/process-geometry/src/main/resources/META-INF/services/org.geotools.process.ProcessFactory
[![GEOT-7025](https://badgen.net/badge/JIRA/GEOT-7025/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7025) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7025] fix spelling of center

modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTileFactory.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTileService.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/model/TileMatrixSet.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/client/WMTSTileFactory4326Test.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/client/WMTSTileServiceTest.java
[![GEOT-7014](https://badgen.net/badge/JIRA/GEOT-7014/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7014) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Some functionality are moved from AbstractGetTileRequest to WMTSTileService. The functionality should be the same, but with less code, and a call for WMTSTileService.findTilesInExtent would potentially return tiles that wasn't within the limits of WMTSLayer.
Some functionality are moved from WMTSTileFactory to WMTSTileService. Leaving behind some deprecated functions.
I've added some tests that covers the change.
For core and …
=> [GEOT-7014] Move functionality for filtering tiles by the layer's tileMatrixLimits

build/ci/oracle/start-oracle.sh, docs/developer/conventions/test/online.rst, modules/library/main/src/main/java/org/geotools/filter/function/BandsFunction.java, modules/library/main/src/main/resources/META-INF/services/org.opengis.filter.expression.Function, modules/library/main/src/test/java/org/geotools/filter/function/BandsFunctionTest.java, modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/JiffleProcess.java, modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/JiffleProcessTest.java, pom.xml
Been a month, caused no issues (the changes only affect the Jiffle process)
=> Jiffle variable output bands improvements (26.x backport)

pom.xml
[![GEOT-7038](https://badgen.net/badge/JIRA/GEOT-7038/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7038) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket.
=> [GEOT-7038] Update log4j to a version that does not support RCE

pom.xml
[![GEOT-7038](https://badgen.net/badge/JIRA/GEOT-7038/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7038) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7038] Update log4j to a version that does not support RCE (26.x)

pom.xml
[![GEOT-7038](https://badgen.net/badge/JIRA/GEOT-7038/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7038) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7038] Update log4j to a version that does not support RCE (24.x)

pom.xml
[![GEOT-7038](https://badgen.net/badge/JIRA/GEOT-7038/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7038) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport from main.
=> [GEOT-7038] Update log4j to a version that does not support RCE (25.x)

modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/PointStackerProcess.java, modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/PointStackerProcessTest.java
[![GEOT-7039](https://badgen.net/badge/JIRA/GEOT-7039/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7039) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7039] return original attributes for single points

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSDataStore.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSFeatureReader.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSFeatureSource.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSRemoteTransactionState.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/TransactionResponse.java
[![GEOT-7037](https://badgen.net/badge/JIRA/GEOT-7037/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7037) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7037] wfs-ng doesn't dispose reponses; connection leak

modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/PointStackerProcess.java, modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/PointStackerProcessTest.java
[![GEOT-7041](https://badgen.net/badge/JIRA/GEOT-7041/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7041) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [geot-7041] add an optional filter to clustering process

pom.xml
=> [QA] Bump dependency-check-maven from 6.5.0 to 6.5.1

modules/library/render/src/main/java/org/geotools/renderer/style/DynamicSymbolFactoryFinder.java, modules/library/render/src/main/java/org/geotools/renderer/style/MarkFactoryListComparator.java, modules/library/render/src/main/java/org/geotools/renderer/style/MarkFactoryListPredicate.java, modules/library/render/src/main/java/org/geotools/renderer/style/SLDStyleFactory.java, modules/library/render/src/test/java/org/geotools/renderer/style/SLDStyleFactoryTest.java
[![GEOT-6948](https://badgen.net/badge/JIRA/GEOT-6948/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6948) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR introduces support for filtering and ordering hints on mark factories during rendering.
JIRA ticket:
https://osgeo-org.atlassian.net/browse/GEOT-6948
Proposal:
https://github.com/geotools/geotools/wiki/Rendering-pre-process-Mark-Factories-Hint
=> [26.x backport][GEOT-6948] MarkFactory performance optimization hints support

modules/library/main/src/main/java/org/geotools/data/util/BooleanConverterFactory.java, modules/library/main/src/test/java/org/geotools/data/util/BooleanConverterFactoryTest.java
[![GEOT-7033](https://badgen.net/badge/JIRA/GEOT-7033/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7033) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Exending existing to boolean mapping for GML in order to handle BigDecimal.
I'm currently migrating a WFS service to Geoserver 2.20 (from 2.7) and ran into a mapping issue. The exception presented was "java.lang.ClassCastException: class java.math.BigDecimal cannot be cast to class java.lang.Boolean".
=> [GEOT-7033] GML: Adding BigDecimal to Boolean conversion

pom.xml
[![GEOT-7048](https://badgen.net/badge/JIRA/GEOT-7048/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7048) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Upgrade NetCDF to 4.6.19 to address security vulnerabilities in third-party libraries in Dependency Check scans.
Related to https://github.com/geoserver/geoserver/pull/5562
=> [GEOT-7048] Upgrade NetCDF to 4.6.19

.zendo.json
=> add zendo config file to aid creation of DOI

pom.xml
[![GEOT-7057](https://badgen.net/badge/JIRA/GEOT-7057/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7057) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Maven artifact `com.googlecode.json-simple:json-simple:1.1.1`
carries over `junit:junit` as a compile scoped transtitive
dependency. Exclude it.
See https://mvnrepository.com/artifact/com.googlecode.json-simple/json-simple/1.1.1
=> [GEOT-7057] Remove junit compile time transitive dependency from json-simple

modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WebMapTileServer.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/map/WMTSCoverageReaderTest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/model/WMTSCapabilitiesTest.java, modules/extension/wmts/src/test/resources/test-data/linz_basemaps_capabilities.xml
[![GEOT-7052](https://badgen.net/badge/JIRA/GEOT-7052/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7052) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fixing a problem where OperationsMetadata isn't included in the capabilities document. In the original code this section were used to find a serverUrl. When this section is missing, there isn't actually anyway to get the serverUrl from the capabilities document.
I've introduced new constructors that takes serverUrl as arguments, and deprecated the old ones.
This is a fix for …
=> [GEOT-7052] OperationsMetadata is optional for RESTful WMTS

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgFilterToSQLTest.java
[![GEOT-7054](https://badgen.net/badge/JIRA/GEOT-7054/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7054) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Like query was not supported in geopackage. With this PR requests using like query will be supported in geopackage.
=> [GEOT-7054] Like Query Addition to Geopackage

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDataStoreFactory.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDataStoreContentsOnlyTest.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDataStoreFactoryTestSetup.java
[![GEOT-7019](https://badgen.net/badge/JIRA/GEOT-7019/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7019) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Appschema integration is done for Geopackage
=> [GEOT-7019] Appschema support for geopackage

modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/utilities/NetCDFUtilities.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/imageio/netcdf/NetCDFUtilitiesTest.java, modules/plugin/coverage-multidim/netcdf/src/test/resources/org/geotools/imageio/netcdf/test-data/xxe.nc
This PR disables DTDs in the NETCDF parser and adds some debug logging rather than just swallowing the exception.
=> Disable DTDs in the NETCDF XML parser.

pom.xml
=> bump jdbc drivers

release/src/markdown/README.md
class path delimiter was improper
=> Fixed run command for windows

modules/unsupported/geojson-core/src/main/java/com/bedatadriven/jackson/datatype/jts/serialization/GeometrySerializer.java, modules/unsupported/geojson-core/src/test/java/com/bedatadriven/jackson/datatype/jts/MiscTests.java
[![GEOT-7027](https://badgen.net/badge/JIRA/GEOT-7027/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7027) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7027] Invalid number format when writing geojson features.

modules/library/main/src/main/java/org/geotools/geometry/jts/WKTReader2.java, modules/library/main/src/test/java/org/geotools/geometry/jts/WKTReader2Test.java
[![GEOT-7065](https://badgen.net/badge/JIRA/GEOT-7065/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7065) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7065] WKTReader2 can't read EMPTY geometries

modules/library/cql/src/main/java/org/geotools/filter/text/commons/AbstractFilterBuilder.java, modules/library/cql/src/main/java/org/geotools/filter/text/ecql/ECQLFilterBuilder.java, modules/library/cql/src/test/java/org/geotools/filter/text/ecql/ECQLGeoOperationTest.java, modules/unsupported/cql2/src/main/java/org/geootols/filter/text/cql_2/CQL2FilterBuilder.java, modules/unsupported/cql2/src/test/java/org/geotools/filter/text/cql_2/CQL2GeoOperationTest.java
[![GEOT-7066](https://badgen.net/badge/JIRA/GEOT-7066/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7066) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket
=> [GEOT-7066] ECQL cannot parse geometry predicates using ENVELOPE

modules/unsupported/geojson-core/src/main/java/com/bedatadriven/jackson/datatype/jts/parsers/MultiPointParser.java, modules/unsupported/geojson-core/src/main/java/com/bedatadriven/jackson/datatype/jts/parsers/PointParser.java, modules/unsupported/geojson-core/src/main/java/com/bedatadriven/jackson/datatype/jts/parsers/PolygonParser.java, modules/unsupported/geojson-core/src/main/java/com/bedatadriven/jackson/datatype/jts/serialization/GeometrySerializer.java, modules/unsupported/geojson-core/src/test/java/com/bedatadriven/jackson/datatype/jts/MiscTests.java, modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONReaderTest.java, modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
[![GEOT-5192](https://badgen.net/badge/JIRA/GEOT-5192/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-5192) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-5192] NPE occurs while writing features' collection to GeoJSON where features have EmptyGeometry.

modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/utilities/NetCDFUtilities.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/imageio/netcdf/NetCDFUtilitiesTest.java, modules/plugin/coverage-multidim/netcdf/src/test/resources/org/geotools/imageio/netcdf/test-data/xxe.nc
26.x backport of https://github.com/geotools/geotools/pull/3758
=> [26.x] Disable DTDs in the NETCDF XML parser.

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
[![GEOT-7060](https://badgen.net/badge/JIRA/GEOT-7060/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7060) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
[JoiningJDBCFeatureSource.getCountInternal function](https://github.com/geotools/geotools/blob/eaa3b0e02e3e9a38143ea83cd2474dcb4a9b77e4/modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java#L1498-L1522) was not setting prepared statement values. This behaviour is observed during appschema-geopkg test.
Testing is done with appschema geopackage, postgis and other related …
=> [GEOT-7060] prepared statement values in the count query are set

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
[![GEOT-7060](https://badgen.net/badge/JIRA/GEOT-7060/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7060) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
25.x backport https://github.com/geotools/geotools/pull/3759
=> [25.x][GEOT-7060] prepared statement values in the count query are set

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgFilterToSQLTest.java
[![GEOT-7054](https://badgen.net/badge/JIRA/GEOT-7054/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7054) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
25.x backport https://github.com/geotools/geotools/pull/3744
=> [25.x][GEOT-7054] Like Query Addition to Geopackage (#3744)

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgFilterToSQLTest.java
[![GEOT-7054](https://badgen.net/badge/JIRA/GEOT-7054/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7054) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
26.x backport https://github.com/geotools/geotools/pull/3744
=> [26.x][GEOT-7054] Like Query Addition to Geopackage (#3744)

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDataStoreFactory.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDataStoreContentsOnlyTest.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDataStoreFactoryTestSetup.java
[![GEOT-7019](https://badgen.net/badge/JIRA/GEOT-7019/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7019) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
26.x backport https://github.com/geotools/geotools/pull/3667
=> [26.x][GEOT-7019] Appschema support for geopackage (#3667)

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDataStoreFactory.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDataStoreContentsOnlyTest.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDataStoreFactoryTestSetup.java
[![GEOT-7019](https://badgen.net/badge/JIRA/GEOT-7019/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7019) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
25.x backport of https://github.com/geotools/geotools/pull/3667
=> [25.x][GEOT-7019] Appschema support for geopackage (#3667)

modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonTestSetup.java
[![GEOT-7075](https://badgen.net/badge/JIRA/GEOT-7075/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7075) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7075] Perform the same tests found in PostgisJSONOnlineTest on JSONB columns

modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java, modules/extension/wmts/src/test/resources/test-data/sgx_geodatenzentrum_de.getcapa.xml
[![GEOT-7078](https://badgen.net/badge/JIRA/GEOT-7078/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7078) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fixes an issue reported in Geoserver:
[GEOS-10395](https://osgeo-org.atlassian.net/browse/GEOS-10395)
Chooses first style of layer if none has the attribute isDefault=true.
=> [GEOT-7078] Use first style of WMTS layer's without isDefault set

docs/index/index.rst, docs/user/library/coverage/imageio.rst, docs/user/library/data/ogr.rst, pom.xml
[![GEOT-7085](https://badgen.net/badge/JIRA/GEOT-7085/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7085) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This pull request waiting on https://github.com/geosolutions-it/imageio-ext/pull/253 and ImageIO-EXT 1.4.0 release, both of which are now complete:
=> [GEOT-7085] ImageIO-EXT 1.4.0 update with instructions for GDAL 3.2 use

modules/library/main/src/main/java/org/geotools/feature/collection/ClippedFeatureCollection.java, modules/library/main/src/test/java/org/geotools/feature/collection/ClippedFeatureCollectionTest.java
[![GEOT-7091](https://badgen.net/badge/JIRA/GEOT-7091/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7091) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket.
=> [GEOT-7091] ClippingFeatureCollection won't handle input feature types with generic Geometry columns

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/IndexManager.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureSource.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileSetManager.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileReader.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/fid/IndexedFidReader.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/index/quadtree/fs/FileSystemIndexStore.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/ShapefileReader.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDescriptorLeakTest.java
[![GEOT-7088](https://badgen.net/badge/JIRA/GEOT-7088/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7088) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
26.x backport for https://github.com/geotools/geotools/pull/3811
=> [26.x][GEOT-7088] Fix shapefile resource leaks (#3811)

pom.xml
[![GEOT-7101](https://badgen.net/badge/JIRA/GEOT-7101/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7101) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket.
=> [GEOT-7101] Update Jackson to 2.13.2

pom.xml
[![GEOT-7101](https://badgen.net/badge/JIRA/GEOT-7101/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7101) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7101] Update Jackson to 2.13.2 (26.x)

pom.xml
[![GEOT-7101](https://badgen.net/badge/JIRA/GEOT-7101/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7101) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7101] Update Jackson to 2.13.2 (25.x)

build/qa/dependency-check-suppression.xml, pom.xml
also ignore false positives for reload4j
=> Bump `org.owasp:dependency-check-maven` from 6.5.1 to 7.0.4

modules/unsupported/elasticsearch/pom.xml, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticFeatureSource.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/FilterToElastic.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/ElasticBucketVisitor.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/GeoHashGrid.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/GeoHashGridProcess.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFilterTest.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticViewParametersFilterIT.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridProcessTest.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridTest.java
[![GEOT-7102](https://badgen.net/badge/JIRA/GEOT-7102/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7102) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
got wms working
added in query and nativeOnly parameters
fixed test issues
fixed featuresource versus featurecollection issue
cleanup
Got unit tests working
Fixed other tests to use correct hint key
cleanup
=> [GEOT-7102] ElasticSearch plugin move aggregation creation from view parameters to Rendering Transformation parameter

pom.xml
[![GEOT-7113](https://badgen.net/badge/JIRA/GEOT-7113/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7113) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Update to latest.
=> [GEOT-7113] Update to jai-ext 1.1.22

pom.xml
[![GEOT-7113](https://badgen.net/badge/JIRA/GEOT-7113/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7113) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7113] Update to jai-ext 1.1.22 (26.x)

pom.xml
[![GEOT-7113](https://badgen.net/badge/JIRA/GEOT-7113/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7113) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7113] Update to jai-ext 1.1.22 (24.x)

modules/library/metadata/src/main/java/org/geotools/util/factory/GeoTools.java, pom.xml
[![GEOT-7113](https://badgen.net/badge/JIRA/GEOT-7113/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7113) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7113] Update to jai-ext 1.1.22 (25.x)

modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticDataStoreFactory.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticFeatureSource.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticRequest.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/FilterToElastic.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/GeohashUtil.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/ElasticBucketVisitor.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/GeoHashGrid.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/GeoHashGridProcess.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticTestSupport.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticViewParametersFilterIT.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/GeohashUtilTest.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridProcessIT.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridProcessTest.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridTest.java
=> Backporting ES GeoHashGrid improvements

docs/src/main/java/org/geotools/tutorial/logging/Example.java, docs/src/main/java/org/geotools/tutorial/logging/Example2.java, docs/src/main/java/org/geotools/tutorial/logging/Example3.java, docs/src/main/java/org/geotools/tutorial/logging/Example4.java, docs/src/main/java/org/geotools/tutorial/logging/Welcome.java, docs/src/main/java/org/geotools/tutorial/logging/Welcome2.java, docs/user/library/metadata/logging/factory.rst, docs/user/library/metadata/logging/java_logging.rst, docs/user/library/metadata/logging/jcl.rst, docs/user/library/metadata/logging/log4j.rst, docs/user/library/metadata/logging/logback.rst, docs/user/library/metadata/logging/reload4j.rst, docs/user/library/metadata/logging/use.rst, modules/library/metadata/pom.xml, modules/library/metadata/src/it/commons/pom.xml, modules/library/metadata/src/it/log4j/pom.xml, modules/library/metadata/src/it/logback/pom.xml, modules/library/metadata/src/it/logback/src/main/java/org/geotools/tutorial/logging/LogbackIntegration.java, modules/library/metadata/src/it/logback/src/main/resources/logback.xml, modules/library/metadata/src/it/logging/pom.xml, modules/library/metadata/src/it/logging/src/main/java/org/geotools/tutorial/logging/LoggingIntegration.java, modules/library/metadata/src/main/java/org/geotools/util/factory/GeoTools.java, modules/library/metadata/src/main/java/org/geotools/util/logging/CommonsLoggerFactory.java, modules/library/metadata/src/main/java/org/geotools/util/logging/DefaultLoggerFactory.java, modules/library/metadata/src/main/java/org/geotools/util/logging/Logging.java, pom.xml
[![GEOT-7112](https://badgen.net/badge/JIRA/GEOT-7112/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7112) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
I was missing the addition of DefaultLoggingFactory from https://github.com/geotools/geotools/pull/3809 which makes GeoTools.init() process more understandable.
This pull-request also notes that logging integration tests were not being compiled, and thus not in position to run :)
=> [GEOT-7112] Introduce DefaultLoggingFactory and revise logging integration tests to fail build

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java, modules/library/main/src/main/java/org/geotools/feature/visitor/CalcUtil.java, modules/library/main/src/main/java/org/geotools/feature/visitor/UniqueVisitor.java, modules/library/main/src/test/java/org/geotools/feature/visitor/UniqueVisitorTest.java, modules/plugin/jdbc/jdbc-db2/src/test/java/org/geotools/data/db2/DB2TestSetup.java, modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2TestSetup.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaTestSetup.java, modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLTestSetup.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISTestSetup.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerTestSetup.java, modules/unsupported/jdbc-teradata/src/test/java/org/geotools/data/teradata/TeradataTestSetup.java
[![GEOT-7111](https://badgen.net/badge/JIRA/GEOT-7111/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7111) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7111] Allows UniqueVisitor to select multiple features' attributes

.github/workflows/linux_jdk11.yml, .github/workflows/linux_jdk17.yml, .github/workflows/linux_jdk8.yml, .github/workflows/postgis_online.yml
Some PRs are not finding latest dependencies.
Forcing the update on maven build
=> Forcing -U to maven build

pom.xml
Simple update of imageio-ext-1.4.4 needed for [GEOS-10465]
=> Updating to imageio-ext-1.4.4

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java
[![GEOT-7111](https://badgen.net/badge/JIRA/GEOT-7111/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7111) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7111] Fix uniqueVisitor returning List of value instead of List of List when only a unique distinct sequence is selected

pom.xml
[![GEOT-7107](https://badgen.net/badge/JIRA/GEOT-7107/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7107) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Minor top-level cleanup.
=> [GEOT-7107] Remove duplicate entries in pom.xml

.github/workflows/linux_jdk11.yml, .github/workflows/linux_jdk17.yml, .github/workflows/linux_jdk8.yml
Builds are failing with:
```
404  Not Found [IP: 40.81.13.82 80]
Fetched 55.9 MB in 8s (6930 kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl4-gnutls-dev_7.68.0-1ubuntu2.7_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
Based on [this SO question](https://serverfault.com/questions/1070642/ubuntu-package-revision-not-found-in-github-actions), a ``apt update`` might help... giving it a try.
=> Attempt to fix GDAL setup in the build

modules/plugin/feature-pregeneralized/pom.xml, modules/plugin/feature-pregeneralized/src/main/java/org/geotools/data/gen/PreGeneralizedFeatureSource.java, modules/plugin/feature-pregeneralized/src/test/java/org/geotools/data/gen/PreGeneralizedFeatureSourceNotCachedTest.java
[![GEOT-6927](https://badgen.net/badge/JIRA/GEOT-6927/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6927) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR contains a fix for the problem where OSM usage of pre-generalized can cause " DataSource not available after calling dispose() or before being set".
JIRA ticket is here: https://osgeo-org.atlassian.net/browse/GEOT-6927
=> [GEOT-6927] OSM usage of pre-generalized can cause exception

modules/library/render/src/main/java/org/geotools/renderer/lite/FastBBOX.java, modules/library/render/src/test/java/org/geotools/renderer/lite/FastBBOXTest.java
[![GEOT-7135](https://badgen.net/badge/JIRA/GEOT-7135/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7135) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7135] FastBBOX Class cast exception when evaluating on ComplexFeatures

modules/plugin/feature-pregeneralized/pom.xml, modules/plugin/feature-pregeneralized/src/main/java/org/geotools/data/gen/PreGeneralizedFeatureSource.java, modules/plugin/feature-pregeneralized/src/test/java/org/geotools/data/gen/PreGeneralizedFeatureSourceNotCachedTest.java
[![GEOT-6927](https://badgen.net/badge/JIRA/GEOT-6927/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6927) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-6927] OSM usage of pre-generalized can cause exception (26.x)

modules/plugin/feature-pregeneralized/pom.xml, modules/plugin/feature-pregeneralized/src/main/java/org/geotools/data/gen/PreGeneralizedFeatureSource.java, modules/plugin/feature-pregeneralized/src/test/java/org/geotools/data/gen/PreGeneralizedFeatureSourceNotCachedTest.java
[![GEOT-6927](https://badgen.net/badge/JIRA/GEOT-6927/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6927) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-6927] OSM usage of pre-generalized can cause exception (25.x)

modules/library/render/src/main/java/org/geotools/renderer/lite/FastBBOX.java, modules/library/render/src/test/java/org/geotools/renderer/lite/FastBBOXTest.java
[![GEOT-7135](https://badgen.net/badge/JIRA/GEOT-7135/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7135) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [26.x backport][GEOT-7135] FastBBOX Class cast exception when evaluating on ComplexFeatures

docs/pom.xml, docs/src/main/java/org/geotools/imagemosaic/MosaicViewer.java, docs/user/library/coverage/mosaic.rst, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/MosaicQueryBuilder.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/catalog/CachingDataStoreGranuleCatalog.java
[![GEOT-7131](https://badgen.net/badge/JIRA/GEOT-7131/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7131) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Added a small program to display an Image Mosaic. One of the features being multi-threading. During that process there were some issues that caused me to add exception handling and logging.
=> [GEOT-7131] Clarify ImageMosaic documentation with an example

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/StreamingParser.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/StreamingParserTest.java
[![GEOT-7129](https://badgen.net/badge/JIRA/GEOT-7129/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7129) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR allows the EntityResolver to be set on a StreamingParser instance.
=> [GEOT-7129] Allow StreamingParser to set the entity resolver

modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticFeatureSource.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/FilterToElastic.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridProcessIT.java
See: 
* https://osgeo-org.atlassian.net/browse/GEOT-7142
* https://osgeo-org.atlassian.net/browse/GEOT-7143
=> ElasticSearch GeoHash fixes: support scrolling and renamed geometry attributes

modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticFeatureSource.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/FilterToElastic.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridProcessIT.java
=> ElasticSearch GeoHash fixes: support scrolling and renamed geometry attributes (27.x)

modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticFeatureSource.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/FilterToElastic.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/GeohashUtil.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/GeoHashGrid.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/GeoHashGridProcess.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/process/elasticsearch/GridCoverageUtil.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticViewParametersFilterIT.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridProcessIT.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/GeoHashGridProcessTest.java
=> ElasticSearch GeoHash fixes: support scrolling and renamed geometry attributes (26.x)

docs/user/library/referencing/faq.rst, modules/library/referencing/src/main/java/org/geotools/referencing/DefaultAuthorityFactory.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/Abstract_URI_AuthorityFactory.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/AuthorityFactoryAdapter.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/FallbackAuthorityFactory.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/ManyAuthoritiesFactory.java, modules/library/referencing/src/test/java/org/geotools/referencing/DefaultAuthorityFactoryTest.java, modules/library/referencing/src/test/java/org/geotools/referencing/crs/FirstEPSGFactory.java, modules/library/referencing/src/test/java/org/geotools/referencing/crs/SecondEPSGFactory.java, modules/library/referencing/src/test/java/org/geotools/referencing/crs/ThirdEPSGFactory.java, modules/library/referencing/src/test/java/org/geotools/referencing/factory/MockCRSAuthorityFactory.java, modules/library/referencing/src/test/resources/META-INF/services/org.opengis.referencing.crs.CRSAuthorityFactory, modules/plugin/epsg-wkt/src/main/java/org/geotools/referencing/epsg/wkt/EPSGCRSAuthorityFactory.java
[![GEOT-7081](https://badgen.net/badge/JIRA/GEOT-7081/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7081) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fixes a problem with choosing correct EPSG-library when urn specifies a version.
The main solution is to give VERSION as a hint to each EPSG-library involved, in this case gt-epsg-wkt.
I've added some logging within AuthorityFactoryAdaptor which I thought were useful.
There were code within DefaultAuthorityFactory that I think made the whole process less intuitive. I think what that code tried to solve, are solved by the …
=> [GEOT-7081] Choose correct EPSG library

pom.xml
[![GEOT-7146](https://badgen.net/badge/JIRA/GEOT-7146/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7146) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7146] Upgrade jai-ext to 1.1.23 (27.x)

docs/developer/conventions/test/online.rst
=> [doc] fix a typo and update docker versions for online testing

modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostGISPSTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostgisDataStoreOnlineTest.java
[![GEOT-6888](https://badgen.net/badge/JIRA/GEOT-6888/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6888) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-6888] PostGIS - fixed columns lengths when using prepared statements

modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostGISPSTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostgisDataStoreOnlineTest.java
[![GEOT-6888](https://badgen.net/badge/JIRA/GEOT-6888/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6888) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
backports #3893 to 26.x
=> [GEOT-6888] PostGIS - fixed columns lengths when using prepared statements (26.x)

modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java, modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
[![GEOT-7147](https://badgen.net/badge/JIRA/GEOT-7147/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7147) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket.
=> [GEOT-7147] Add support for missing CSS label vendor options

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java, modules/library/main/src/main/java/org/geotools/feature/visitor/CalcUtil.java, modules/library/main/src/main/java/org/geotools/feature/visitor/UniqueVisitor.java, modules/library/main/src/test/java/org/geotools/feature/visitor/UniqueVisitorTest.java, modules/plugin/jdbc/jdbc-db2/src/test/java/org/geotools/data/db2/DB2TestSetup.java, modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2TestSetup.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaTestSetup.java, modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLTestSetup.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISTestSetup.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerTestSetup.java, modules/plugin/jdbc/jdbc-teradata/src/test/java/org/geotools/data/teradata/TeradataTestSetup.java
[![GEOT-7111](https://badgen.net/badge/JIRA/GEOT-7111/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7111) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [26.x backport][GEOT-7111] Allows UniqueVisitor to select multiple features' attributes (#3844)

modules/library/xml/src/main/java/org/geotools/xml/handlers/xsi/ComplexTypeHandler.java, modules/library/xml/src/main/java/org/geotools/xml/handlers/xsi/ElementTypeHandler.java, modules/library/xml/src/test/java/org/geotools/xml/handlers/xsi/ComplexTypeHandlerTest.java, modules/library/xml/src/test/java/org/geotools/xml/handlers/xsi/ElementTypeHandlerTest.java
[![GEOS-10510](https://badgen.net/badge/JIRA/GEOS-10510/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-10510) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Found something odd in GTXML parser: Use of Boolean.getBoolean( String  ) which checks system property, where I believe Boolean.valueOf( text ) was intended to check for "true" or "false".
I expect GTXML was unable to recognize:
- ComplexType with mixed content: mixed=true resulting in lookup of ``-Dtrue`` system property, returning Boolean.FALSE
- ElementType marked as abstract: abstract=true resulting in lookup of …
=> [GEOS-10510] GTXML use parsing of abstract and mixed as xs:boolean true or false values

.github/workflows/linux_jdk11.yml, .github/workflows/linux_jdk17.yml, .github/workflows/linux_jdk8.yml, docs/common.py
[![GEOT-7154](https://badgen.net/badge/JIRA/GEOT-7154/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7154) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7154] Sphinx build failure with extlinks (new warnings in Sphinx build) (27.x)

docs/user/library/data/ogr.rst
=> Fix formatting issue in OGR docs

modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFMosaicReaderTest.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/PurgingGranuleStore.java
[![GEOT-7153](https://badgen.net/badge/JIRA/GEOT-7153/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7153) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket
=> [GEOT-7153] Removing NetCDF granules from a mosaic can cause spurious netcdf index re-inits

modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFMosaicReaderTest.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/PurgingGranuleStore.java
[![GEOT-7153](https://badgen.net/badge/JIRA/GEOT-7153/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7153) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7153] Removing NetCDF granules from a mosaic can cause spurious netcdf index re-inits (26.x)

modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFMosaicReaderTest.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/PurgingGranuleStore.java
[![GEOT-7153](https://badgen.net/badge/JIRA/GEOT-7153/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7153) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7153] Removing NetCDF granules from a mosaic can cause spurious netcdf index re-inits (27.x)

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
[![GEOT-7159](https://badgen.net/badge/JIRA/GEOT-7159/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7159) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fix some error messages
=> [GEOT-7159] JDBCDataStore  : some error messages are inconsistent

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureSource.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisCRSOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisCRSTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostGIS3DOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostGISFeatureSourceExposePkOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostGISFeatureSourceOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostgisDataStoreAPIOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostgisDataStoreOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostgisGeographyOnlineTest.java
[![GEOT-7152](https://badgen.net/badge/JIRA/GEOT-7152/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7152) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The title could be misleading. We're actually using the spatial_ref_sys to get the authority og srid.
Just in cases were our own plugins doesn't give a cos, we will try with the provided WKT in spatial_ref_sys.
=> [GEOT-7152] Use table spatial_ref_sys to create CRS

modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/AncillaryFileManager.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFMosaicReaderTest.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicConfigHandler.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterManager.java
[![GEOT-7164](https://badgen.net/badge/JIRA/GEOT-7164/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7164) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket.
=> [GEOT-7164] Make it easier to move mosaics of NetCDF around

modules/library/sample-data/src/main/java/org/geotools/test/OnlineTestCase.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISPartitionedTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISPartitionedTestSetup.java
[![GEOT-7162](https://badgen.net/badge/JIRA/GEOT-7162/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7162) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7162] Postgis Partition tests fail on postgres versions below 11

pom.xml
Backport https://github.com/geotools/geotools/pull/3936
Bumps [mysql-connector-java](https://github.com/mysql/mysql-connector-j) from 8.0.26 to 8.0.28.
- [Release notes](https://github.com/mysql/mysql-connector-j/releases)
- [Changelog](https://github.com/mysql/mysql-connector-j/blob/release/8.0/CHANGES)
- [Commits](https://github.com/mysql/mysql-connector-j/compare/8.0.26...8.0.28)
---
updated-dependencies:
- dependency-name: mysql:mysql-connector-java
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
=> [Backport 26.x] Bump mysql-connector-java from 8.0.26 to 8.0.28

modules/plugin/jdbc/jdbc-informix/src/main/java/org/geotools/data/informix/InformixDataStoreFactory.java, modules/plugin/jdbc/jdbc-informix/src/test/java/org/geotools/data/informix/InformixAggregateFunctionOnlineTest.java, modules/plugin/jdbc/jdbc-informix/src/test/java/org/geotools/data/informix/InformixTestSetup.java
[![GEOT-7166](https://badgen.net/badge/JIRA/GEOT-7166/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7166) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Context:  https://github.com/geotools/geotools/pull/3896
- fix the InformixJNDIDataSourceOnlineTest 
- geotools\modules\plugin\jdbc\jdbc-informix\src\test\java\org\geotools\data\informix\InformixJNDIDataSourceOnlineTest.java
- fix the InformixAggregateFunctionOnlineTest
=> [Geot-7166] Fix jdbc informix failed tests

modules/plugin/jdbc/jdbc-informix/src/main/java/org/geotools/data/informix/InformixDataStoreFactory.java, modules/plugin/jdbc/jdbc-informix/src/test/java/org/geotools/data/informix/InformixTestSetup.java
[![GEOT-7166](https://badgen.net/badge/JIRA/GEOT-7166/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7166) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
backports #3940 to 27.x
=> [Backport 27.x] [GEOT-7166] Fix jdbc informix failed tests (#3940)

modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/bindings/DirectPositionListTypeBindingTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/bindings/LineStringTypeBindingTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/v3_2/bindings/ArcStringTypeBindingTest.java, modules/library/main/src/main/java/org/geotools/geometry/jts/LiteCoordinateSequence.java, modules/library/main/src/main/java/org/geotools/geometry/jts/coordinatesequence/CoordinateSequences.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/TWKBReader.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/TWKBReaderTest.java, pom.xml
[![GEOT-7167](https://badgen.net/badge/JIRA/GEOT-7167/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7167) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7167] Upgrade JTS to 1.19.0

build/ci/db2/start-db2.sh, build/ci/informix/start-informix.sh, build/ci/mssql/start-mssql.sh, build/ci/mysql/start-mysql.sh, build/ci/oracle/start-oracle.sh
Also the log messages of mysql 5 changed, so fix that.
Bail out after 300 sec. note that the database may still be up-and-running, just that the wait loop is looking for a different message, so don't `exit 1`. 
See also https://github.com/geotools/geotools/pull/3955#issuecomment-1181532082
=> [CI] Don't wait indefinitely for a database to come online

pom.xml
Use an up-2-date version of the OWASP dependency scanner plugin
=> Bump org.owasp:dependency-check-maven from 7.0.4 to 7.1.1

modules/unsupported/stac-store/pom.xml, modules/unsupported/stac-store/src/main/java/org/geotools/stac/client/STACClient.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/STACDataStore.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/STACDataStoreFactory.java, modules/unsupported/stac-store/src/test/java/org/geotools/stac/store/STACDataStoreFactoryTest.java
[![GEOT-7192](https://badgen.net/badge/JIRA/GEOT-7192/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7192) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket
=> [GEOT-7192] STAC datastore: allow full HTTP client configuration

modules/unsupported/stac-store/pom.xml, modules/unsupported/stac-store/src/main/java/org/geotools/stac/client/CQL2Conformance.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/CQL2PostPreFilterSplitter.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/STACDataStore.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/STACFeatureSource.java, modules/unsupported/stac-store/src/test/java/org/geotools/stac/store/CQL2PostPreFilterSplitterTest.java, modules/unsupported/stac-store/src/test/java/org/geotools/stac/store/STACFeatureSourceTest.java, modules/unsupported/stac-store/src/test/resources/org/geotools/stac/landingPage.json, modules/unsupported/stac-store/src/test/resources/org/geotools/stac/majaCloudCover50.json
[![GEOT-7193](https://badgen.net/badge/JIRA/GEOT-7193/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7193) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket
=> [GEOT-7193] STAC datastore: support CQL2 filter encoding

pom.xml
[![GEOT-7197](https://badgen.net/badge/JIRA/GEOT-7197/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7197) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7197] Bump postgresql from 42.3.3 to 42.4.1 (26.x backport)

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/HeterogenousCRSTest.java
[![GEOT-7198](https://badgen.net/badge/JIRA/GEOT-7198/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7198) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket
=> [GEOT-7198] GeoTIFF native band selection does not work in heterogeneous CRS mosaics

modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaDialect.java
[![GEOT-7212](https://badgen.net/badge/JIRA/GEOT-7212/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7212) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Geometry simplification is supported in HANA Cloud and HANA 2 SPS04 and later.
=> [GEOT-7212] Support geometry simplification in gt-jdbc-hana

pom.xml
Updating imageio-ext version to 1.4.7
=> Updating ImageIO-EXT version to 1.4.7

modules/extension/ysld/pom.xml
[![GEOT-7221](https://badgen.net/badge/JIRA/GEOT-7221/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7221) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR upgrades SnakeYAML from 1.26 to 1.32 in order to address a vulnerability in the library.
=> [GEOT-7221] Upgrade SnakeYAML to 1.32

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
[![GEOT-7214](https://badgen.net/badge/JIRA/GEOT-7214/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7214) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7214] app-schema GetFeature numberMatched fails with ID filter

modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/v2_0/storedquery/ParameterTypeFactoryTest.java
[![GEOT-7226](https://badgen.net/badge/JIRA/GEOT-7226/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7226) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The test fails in newer JDK for certain locales, because of the minus character being used.
I've included a function that creates an expectation in accordance with the locale of the user.
=> [GEOT-7226] ParameterTypeFactoryTest fails for certain locales

modules/library/main/src/main/java/org/geotools/geometry/jts/coordinatesequence/CoordinateSequences.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiLineHandler.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiPointHandler.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PointHandler.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PolygonHandler.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/shp/ZMHandlersTest.java
Reverts geotools/geotools#4029
=> Revert "GEOT-7231: Z values shapefiles don't handle NaN M values correctly"

modules/library/main/src/main/java/org/geotools/geometry/jts/coordinatesequence/CoordinateSequences.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiLineHandler.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiPointHandler.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PointHandler.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PolygonHandler.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/shp/ZMHandlersTest.java
=> [Backport 27.x] GEOT-7231] Z values shapefiles don't handle NaN M values correctly

modules/library/main/src/main/java/org/geotools/geometry/jts/coordinatesequence/CoordinateSequences.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiLineHandler.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/MultiPointHandler.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PointHandler.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/PolygonHandler.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/shp/ZMHandlersTest.java
=> [Backport 26.x] GEOT-7231] Z values shapefiles don't handle NaN M values correctly

modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDialect.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerPrimaryKeyOnlineTest.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerPrimaryKeyTestSetup.java
[![GEOT-7233](https://badgen.net/badge/JIRA/GEOT-7233/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7233) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Implement `encodeNextSequenceValue(...)` and `getNextSequenceValue(...)` to provide support for sequences.
Note that part of this support relies on using the primary key metadata table.
=> [GEOT-7233] Add support for sequences to SQL Server dialect

modules/library/main/pom.xml
[![CVE-2022](https://badgen.net/badge/JIRA/CVE-2022/0052CC)](https://osgeo-org.atlassian.net/browse/CVE-2022) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
commons-text fixed CVE-2022-42889; this is not a vulnerability that applies to GeoTools as GeoTools only uses the `WordUtils.abbreviate(...)` and `WordUtils.capitalizeFully()` methods that don't do string interpolation
=> Bump org.apache.commons:commons-text from 1.6 to 1.10.0

modules/library/metadata/src/main/java/org/geotools/util/NIOUtilities.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureWriter.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/files/ShpFiles.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/files/ShpFilesLocker.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/files/StorageFile.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileReadWriteTest.java
[![GEOT-6259](https://badgen.net/badge/JIRA/GEOT-6259/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6259) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fixes a problem with failing unit test at Windows with JDK 11.
Found old issue in Jira and used a code snippet from the discussion that seems to work.
In addition I did some work on logging of unlock, and an exception with explanation if the replaceOriginals fails.
=> [GEOT-6259] ShapefileReadWriteTest fail on Windows

modules/library/main/src/main/java/org/geotools/filter/visitor/ExtractBoundsFilterVisitor.java, modules/library/main/src/test/java/org/geotools/filter/visitor/ExtractBoundsFilterVisitorTest.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureReader.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
[![GEOT-7227](https://badgen.net/badge/JIRA/GEOT-7227/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7227) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [Geot-7227] FlatGeobufFeatureReader throws a NPE when query filter Literal Expression is a ReferencedEnvelope

modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDialect.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerDateOnlineTest.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerDateTestSetup.java
[![GEOT-7220](https://badgen.net/badge/JIRA/GEOT-7220/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7220) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7220] Support datetime2 and datetimeoffset in JDBC SQL Server

modules/library/main/src/main/java/org/geotools/factory/CommonFactoryFinder.java, modules/library/main/src/test/java/org/geotools/factory/CommonFactoryFinderTest.java
[![GEOT-7259](https://badgen.net/badge/JIRA/GEOT-7259/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7259) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
In CommonFactoryFinder I came across this code:
```
try {
Class<?> lenient = Class.forName("org.geotools.feature.LenientFeatureFactoryImpl");
hints.put(Hints.FEATURE_FACTORY, lenient);
} catch (ClassNotFoundException e) {
java.util.logging.Logger.getGlobal().log(java.util.logging.Level.INFO, "", e);
}
```
The class we’re looking for lives in the same jar, so it seems unnecessary to use Class.forName to look it up. Instead we …
=> [GEOT-7259] Avoid Class.forName in CommonFactoryFinder.getFeatureFactory

docs/user/library/data/wfs-ng.rst, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSDataAccessFactory.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/KartverketStedsnavnDataStoreOnlineTest.java
[![GEOT-7253](https://badgen.net/badge/JIRA/GEOT-7253/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7253) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
All the parameters are presented in a common format within WFSDataAccessFactory, all but this one.
In addition I included a description in the documentation.
=> [GEOT-7253] Create an ordinary WFSFactoryParam of WFSDataStoreFactory:SCHEMA_CACHE_LOCATION

docs/index/conf.py, docs/index/index.rst
[![GEOT-7265](https://badgen.net/badge/JIRA/GEOT-7265/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The use of extlink user requires hand editing of the index page for prior branches.
=> [GEOT-7265] Do not use extlink user for index page

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Encoder.java, modules/library/xml/src/main/java/org/geotools/gml/producer/FeatureTransformer.java, modules/library/xml/src/main/java/org/geotools/xml/transform/QNameValidatingHandler.java, modules/library/xml/src/main/java/org/geotools/xml/transform/TransformerBase.java, modules/library/xml/src/test/java/org/geotools/gml/producer/FeatureTransformerTest.java
[![GEOT-7268](https://badgen.net/badge/JIRA/GEOT-7268/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7268) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR updates the TransformerBase and Encoder APIs to validate all element and attribute names and throw an exception if they contain any illegal or invalid XML characters.  The validation also blocks using the XHTML namespace which could allow injecting script without using those characters.  Additional GML unit tests are in https://github.com/geoserver/geoserver/pull/6364.
=> [GEOT-7268] GeoTools can create GML output that is not valid XML

modules/plugin/epsg-hsql/pom.xml, modules/plugin/epsg-hsql/src/main/java/org/geotools/referencing/factory/epsg/hsql/ThreadedHsqlEpsgFactory.java, pom.xml
[![GEOT-7274](https://badgen.net/badge/JIRA/GEOT-7274/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7274) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Dependency upgrade.
=> [GEOT-7274] Upgrade HSQLDB dependency to 2.7.1

docs/user/library/jdbc/oracle.rst, modules/library/jdbc/src/main/java/org/geotools/jdbc/ColumnMetadata.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureSource.java, modules/plugin/coverage-multidim/coverage-api/src/test/java/org/geotools/coverage/io/catalog/CatalogSliceTest.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleNGDataStoreFactory.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleNGOCIDataStoreFactory.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDataStoreAPIOnlineTest.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDataStoreAPITestSetup.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleJNDIDataSourceOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreAPIOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreAPITestSetup.java
[![GEOT-7241](https://badgen.net/badge/JIRA/GEOT-7241/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7241) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
…ected JDBC stores
added online tests
cleanup
oracle doc
sometimes comments are empty instead of null
test has comment that broke equality
make sure parameters show up
one more
Update modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleNGDataStoreFactory.java
Co-authored-by: Andrea Aime <andrea.aime@gmail.com>
PR responses
more PR responses
Update …
=> [GEOT-7241] Expose column comments in FeatureType descriptions on sel (28.x)

docs/user/library/jdbc/oracle.rst, modules/library/jdbc/src/main/java/org/geotools/jdbc/ColumnMetadata.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureSource.java, modules/plugin/coverage-multidim/coverage-api/src/test/java/org/geotools/coverage/io/catalog/CatalogSliceTest.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleNGDataStoreFactory.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleNGOCIDataStoreFactory.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDataStoreAPIOnlineTest.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDataStoreAPITestSetup.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleJNDIDataSourceOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreAPIOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreAPITestSetup.java
[![GEOT-7241](https://badgen.net/badge/JIRA/GEOT-7241/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7241) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7241] Expose column comments in FeatureType descriptions on sel (27.x)

modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/RenamingGranuleSource.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicConfigHandler.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/MosaicQueryBuilder.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/catalog/CatalogConfigurationBean.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/catalog/index/IndexerUtils.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/HeterogenousCRSTest.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/AssetsMappingReader.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/STACFeatureSource.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/STACFeatureTypeFactoryImpl.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/SearchQueryBuilder.java, modules/unsupported/stac-store/src/test/java/org/geotools/stac/client/STACClientEarthSearchOnlineTest.java, modules/unsupported/stac-store/src/test/java/org/geotools/stac/client/STACClientPlanetaryOnlineTest.java, modules/unsupported/stac-store/src/test/java/org/geotools/stac/mosaic/STACMosaicIntegrationTest.java, modules/unsupported/stac-store/src/test/java/org/geotools/stac/store/STACDataStoreTest.java, modules/unsupported/stac-store/src/test/java/org/geotools/stac/store/STACFeatureSourceTest.java, modules/unsupported/stac-store/src/test/java/org/geotools/stac/store/SearchQueryBuilderTest.java, modules/unsupported/stac-store/src/test/resources/org/geotools/stac/mosaic/indexer.properties
Couple of related changes to optimize the data transfer to STAC APIs:
* https://osgeo-org.atlassian.net/browse/GEOT-7277
* https://osgeo-org.atlassian.net/browse/GEOT-7279
=> Optimized STAC API property extraction in data store and mosaic

modules/library/render/src/test/java/org/geotools/renderer/lite/GridCoverageRendererTest.java
[![GEOT-7290](https://badgen.net/badge/JIRA/GEOT-7290/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7290) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7290] Visual difference for ReprojectGoogleMercatorLargerThanWorld test on aarch64

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleFilterToSQL.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleFilterToSqlTest.java
[![GEOT-7299](https://badgen.net/badge/JIRA/GEOT-7299/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7299) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7299] Unimplemented visitLiteralGeometry in OracleFilterToSQL cause AppSchema errors

.github/workflows/integration.yml, modules/library/main/src/main/java/org/geotools/filter/function/InFunction.java
[![GEOT-7301](https://badgen.net/badge/JIRA/GEOT-7301/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7301) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4176
=> [Backport 28.x] [GEOT-7301] Static lookup for In function

modules/library/main/src/main/java/org/geotools/data/store/FilteringFeatureCollection.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDumper.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDumperTest.java, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dumper/AllTypesMultiColumn.properties, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dumper/PrimitiveGeoFeature.properties
[![GEOT-7305](https://badgen.net/badge/JIRA/GEOT-7305/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7305) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7305] Improve ShapefileDumper to handle multiple geometry columns

modules/library/main/src/main/java/org/geotools/data/store/FilteringFeatureCollection.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDumper.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDumperTest.java, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dumper/AllTypesMultiColumn.properties, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dumper/PrimitiveGeoFeature.properties
[![GEOT-7305](https://badgen.net/badge/JIRA/GEOT-7305/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7305) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4188
=> [Backport 27.x] [GEOT-7305] Improve ShapefileDumper to handle multiple geometry columns

SECURITY.md
Security policy describes stable and maintenance branches; some avenues to contact the team securely.
=> Define a security policy for geotools project

docs/src/main/java/org/geotools/jdbc/JDBCExamples.java, docs/user/library/jdbc/postgis.rst
During review of GEOT-7302 I noticed the postgis connection parameters were not quite documented (class name changed to PostgisNGDataStoreFactory).
=> [GEOT-7302] Document PostGIS parameters

SECURITY.md
=> [Backport 28.x] Define a security policy for geotools project

SECURITY.md
=> [Backport 27.x] Define a security policy for geotools project

build/ci/oracle/start-oracle.sh, pom.xml
[![GEOT-7310](https://badgen.net/badge/JIRA/GEOT-7310/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7310) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Upgrade to the latest patch version.
Also update the CI workflow to pull from the Github registry instead of the Docker registry.
=> [GEOT-7310] Update Oracle JDBC driver to 19.18.0.0

build/ci/oracle/start-oracle.sh, pom.xml
[![GEOT-7310](https://badgen.net/badge/JIRA/GEOT-7310/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7310) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4202
=> [Backport 27.x] [GEOT-7310] Update Oracle JDBC driver to 19.18.0.0

modules/extension/ysld/pom.xml, modules/extension/ysld/src/main/java/org/geotools/ysld/YamlUtil.java, modules/extension/ysld/src/main/java/org/geotools/ysld/encode/YsldRepresenter.java, modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
[![GEOT-7317](https://badgen.net/badge/JIRA/GEOT-7317/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7317) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4212
=> [Backport 28.x] [GEOT-7317] Upgrade snakeyaml from 1.32 to to 2.0

modules/extension/ysld/pom.xml, modules/extension/ysld/src/main/java/org/geotools/ysld/YamlUtil.java, modules/extension/ysld/src/main/java/org/geotools/ysld/encode/YsldRepresenter.java, modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
[![GEOT-7317](https://badgen.net/badge/JIRA/GEOT-7317/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7317) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4212
=> [Backport 27.x] [GEOT-7317] Upgrade snakeyaml from 1.32 to to 2.0

modules/extension/ysld/pom.xml, modules/extension/ysld/src/main/java/org/geotools/ysld/YamlUtil.java, modules/extension/ysld/src/main/java/org/geotools/ysld/encode/YsldRepresenter.java, modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
[![GEOT-7317](https://badgen.net/badge/JIRA/GEOT-7317/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7317) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4212
* Bump snakeyaml from 1.32 to 2.0 in /modules/extension/ysld
Bumps [snakeyaml](https://bitbucket.org/snakeyaml/snakeyaml) from 1.32 to 2.0.
- [Commits](https://bitbucket.org/snakeyaml/snakeyaml/branches/compare/snakeyaml-2.0..snakeyaml-1.32)
---
updated-dependencies:
- dependency-name: org.yaml:snakeyaml dependency-type: direct:production ...
* Address snakeyaml API changes
---------
For core and extension …
=> [Backport 29.x] [GEOT-7317] Upgrade snakeyaml from 1.32 to to 2.0

modules/extension/transform/src/main/java/org/geotools/data/transform/TransformFilterVisitor.java, modules/extension/transform/src/main/java/org/geotools/data/transform/Transformer.java, modules/extension/transform/src/test/java/org/geotools/data/transform/TransformFeatureSourceTest.java, modules/extension/transform/src/test/java/org/geotools/data/transform/TransformerTest.java
[![GEOT-7327](https://badgen.net/badge/JIRA/GEOT-7327/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7327) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket.
=> [GEOT-7327] TransformFeatureSource needs to transform FID filters too

modules/extension/transform/src/main/java/org/geotools/data/transform/TransformFilterVisitor.java, modules/extension/transform/src/main/java/org/geotools/data/transform/Transformer.java, modules/extension/transform/src/test/java/org/geotools/data/transform/TransformFeatureSourceTest.java, modules/extension/transform/src/test/java/org/geotools/data/transform/TransformerTest.java
[![GEOT-7327](https://badgen.net/badge/JIRA/GEOT-7327/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7327) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4227
=> [Backport 27.x] [GEOT-7327] TransformFeatureSource needs to transform FID filters too

modules/extension/transform/src/main/java/org/geotools/data/transform/TransformFilterVisitor.java, modules/extension/transform/src/main/java/org/geotools/data/transform/Transformer.java, modules/extension/transform/src/test/java/org/geotools/data/transform/TransformFeatureSourceTest.java, modules/extension/transform/src/test/java/org/geotools/data/transform/TransformerTest.java
[![GEOT-7327](https://badgen.net/badge/JIRA/GEOT-7327/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7327) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4227
=> [Backport 28.x] [GEOT-7327] TransformFeatureSource needs to transform FID filters too

modules/extension/transform/src/main/java/org/geotools/data/transform/TransformFilterVisitor.java, modules/extension/transform/src/main/java/org/geotools/data/transform/Transformer.java, modules/extension/transform/src/test/java/org/geotools/data/transform/TransformFeatureSourceTest.java, modules/extension/transform/src/test/java/org/geotools/data/transform/TransformerTest.java
[![GEOT-7327](https://badgen.net/badge/JIRA/GEOT-7327/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7327) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4227
=> [Backport 29.x] [GEOT-7327] TransformFeatureSource needs to transform FID filters too

docs/user/library/opengis/faq.rst
This now focuses on geotools project history only. Apparently the history I had written here ages ago was in correct; it is faster just to remove it.
See: https://git.osgeo.org/gitea/osgeo/todo/issues/142
=> Remove GeoAPI history from OpenGIS FAQ

modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WebMapTileServer.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java
[![GEOT-7325](https://badgen.net/badge/JIRA/GEOT-7325/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7325) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7325] fix NPE on REST template requests with no operations

modules/library/main/pom.xml, modules/library/main/src/main/java/org/geotools/geometry/jts/CircularArc.java, modules/library/main/src/test/java/org/geotools/geometry/jts/CircularArcTest.java
[![GEOT-7333](https://badgen.net/badge/JIRA/GEOT-7333/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7333) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4244
=> [Backport 27.x] [GEOT-7333] The result of linearization after creating circulararc is wrong

pom.xml
=> [Backport 28.x] Bump jackson-databind from 2.13.4.1 to 2.13.4.2

pom.xml
=> [Backport 27.x] Bump jackson-databind from 2.13.4.1 to 2.13.4.2

pom.xml
=> [Backport 29.x] Bump jackson-databind from 2.13.4.1 to 2.13.4.2

modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/DefaultGeometryTest.java, modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/measurementsDefaultGeometry.xml, modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/measurementsDefaultGeometry.xsd, modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/stationsDefaultGeometry.xml, modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/stationsDefaultGeometry.xsd, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/bindings/ComplexSupportXSAnyTypeBinding.java
[![GEOT-7338](https://badgen.net/badge/JIRA/GEOT-7338/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7338) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-7338
This PR introduces a fix for App-Schema complex features duplicated attributes between feature containers and features.
=> [GEOT-7338] Fix XML container element duplicates child attributes

modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/DefaultGeometryTest.java, modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/measurementsDefaultGeometry.xml, modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/measurementsDefaultGeometry.xsd, modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/stationsDefaultGeometry.xml, modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/stationsDefaultGeometry.xsd, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/bindings/ComplexSupportXSAnyTypeBinding.java
[![GEOT-7338](https://badgen.net/badge/JIRA/GEOT-7338/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7338) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4255
=> [Backport 28.x] [GEOT-7338] Fix XML container element duplicates child attributes

modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/DefaultGeometryTest.java, modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/measurementsDefaultGeometry.xml, modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/measurementsDefaultGeometry.xsd, modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/stationsDefaultGeometry.xml, modules/extension/app-schema/app-schema/src/test/resources/test-data/stations/stationsDefaultGeometry.xsd, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/bindings/ComplexSupportXSAnyTypeBinding.java
[![GEOT-7338](https://badgen.net/badge/JIRA/GEOT-7338/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7338) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4255
=> [Backport 29.x] [GEOT-7338] Fix XML container element duplicates child attributes

SECURITY.md
update the security policy after release of 29.0
=> [docs] Update supported versions in security policy

modules/unsupported/flatgeobuf/pom.xml
=> [Backport 27.x] Bump json from 20210307 to 20230227 in /modules/unsupported/flatgeobuf

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/ComplexGetFeatureResponse.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSContentComplexFeatureCollection.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlComplexFeatureParser.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentComplexFeatureSourceTest.java
[![GEOT-7322](https://badgen.net/badge/JIRA/GEOT-7322/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7322) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4220
=> [Backport 29.x] [GEOT-7322] WFSContentComplexFeatureCollection.subCollection doesn't use the filter

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
[![GEOT-7340](https://badgen.net/badge/JIRA/GEOT-7340/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7340) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4263
=> [Backport 27.x] [GEOT-7340] Avoid PAMParser init causing ImageMosaic to fail

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
[![GEOT-7340](https://badgen.net/badge/JIRA/GEOT-7340/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7340) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4263
=> [Backport 28.x] [GEOT-7340] Avoid PAMParser init causing ImageMosaic to fail

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
[![GEOT-7340](https://badgen.net/badge/JIRA/GEOT-7340/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7340) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4263
=> [Backport 29.x] [GEOT-7340] Avoid PAMParser init causing ImageMosaic to fail

modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/bindings/GML2EncodingUtils.java, modules/extension/xsd/xsd-gml2/src/test/java/org/geotools/gml2/GML3EncodingUtilsTest.java, modules/library/metadata/src/main/java/org/geotools/util/factory/GeoTools.java, modules/library/metadata/src/main/java/org/geotools/util/factory/Hints.java
[![GEOT-7267](https://badgen.net/badge/JIRA/GEOT-7267/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7267) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Geotools force OGC_HTTP_URL syntax on CRS that are east/north. This causes problems for INSPIRE and this cannot be resolved with configuration in geoserver, because it is hard coded and ignores everything else. I don't think this should happen in theory, but had to make this into a configurable property for backwards compatibility.
=> [GEOT-7267] force correct srs style property

modules/library/http/src/main/java/org/geotools/http/AbstractHttpClient.java, modules/library/http/src/main/java/org/geotools/http/DefaultHttpResponse.java, modules/library/http/src/main/java/org/geotools/http/SimpleHttpClient.java, modules/plugin/http-commons/src/main/java/org/geotools/http/commons/MultithreadedHttpClient.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSDataStoreFactory.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSDataAccessFactory.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/WFSDataStoreFactoryTest.java
[![GEOT-7345](https://badgen.net/badge/JIRA/GEOT-7345/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7345) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The goal is to let WFSDataAccessFactory handle GetCapabilities stored as a local file.
To do this I've done a little change to MultithreadedHttpClient, so that it behaves in the same way as SimpleHttpClient for file url's. This is done by making them both subclasses og AbstractHttpClient and have functionality there for making connection against file url's.
I did also a refactor of the class SimpleHttpClient.SimpleHTTPResponse …
=> [GEOT-7345] WFS Capabilities from local file

docs/user/library/main/data.rst, docs/user/library/main/feature.rst, modules/library/main/src/main/java/org/geotools/data/DataUtilities.java, modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java, modules/plugin/iau-wkt/pom.xml, modules/plugin/property/pom.xml, modules/plugin/property/src/test/java/org/geotools/data/property/PropertyDataStoreTest.java
[![GEOT-7361](https://badgen.net/badge/JIRA/GEOT-7361/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7361) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Allow property data store to use the IAU authority, and other authorities, in support for non EPSG authority code development and test (as the property store is our favourite test data store).
=> [GEOT-7361] Support non EPSG authorities in DataUtilities type spec, and property data store

modules/library/http/src/main/java/org/geotools/http/AbstractHttpClient.java, modules/library/http/src/main/java/org/geotools/http/DefaultHttpResponse.java, modules/library/http/src/main/java/org/geotools/http/SimpleHttpClient.java, modules/plugin/http-commons/src/main/java/org/geotools/http/commons/MultithreadedHttpClient.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSDataStoreFactory.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSDataAccessFactory.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/WFSDataStoreFactoryTest.java
[![GEOT-7345](https://badgen.net/badge/JIRA/GEOT-7345/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7345) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4275
=> [Backport 29.x] [GEOT-7345] WFS Capabilities from local file

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java, modules/library/main/src/main/java/org/geotools/data/util/DistanceBufferUtil.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisPSFilterToSql.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/AbstractFilterToMongo.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoCollectionMeta.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFilterSplitter.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoFilterSplitterTest.java, modules/unsupported/jdbc-h2gis/src/main/java/org/h2gis/geotools/H2GISPSFilterToSql.java
[![GEOT-7360](https://badgen.net/badge/JIRA/GEOT-7360/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7360) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=>  [Backport 28.x][GEOT-7360] DWITHIN support for mongo DB

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java, modules/library/main/src/main/java/org/geotools/data/util/DistanceBufferUtil.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisPSFilterToSql.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/AbstractFilterToMongo.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoCollectionMeta.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFilterSplitter.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoFilterSplitterTest.java, modules/unsupported/jdbc-h2gis/src/main/java/org/h2gis/geotools/H2GISPSFilterToSql.java
[![GEOT-7360](https://badgen.net/badge/JIRA/GEOT-7360/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7360) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [Backport 29.x][GEOT-7360] DWITHIN support for mongo DB

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
[![GEOT-7366](https://badgen.net/badge/JIRA/GEOT-7366/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7366) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Just clarified the Javadocs regarding usage of the class and thread-safety.
=> [GEOT-7366] Issue with shared memory

pom.xml
[![GEOT-7375](https://badgen.net/badge/JIRA/GEOT-7375/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7375) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Dependency upgrade with security fixes.  This PR should be backported.
=> [GEOT-7375] Upgrade guava from 30.1.1 to 32.0.0

pom.xml
[![GEOT-7376](https://badgen.net/badge/JIRA/GEOT-7376/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7376) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Dependency upgrade with bug fixes.  Backport is optional for this PR.
=> [GEOT-7376] Upgrade postgresql from 42.4.3 to 42.6.0

pom.xml
[![GEOT-7376](https://badgen.net/badge/JIRA/GEOT-7376/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7376) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4315
=> [Backport 28.x] [GEOT-7376] Upgrade postgresql from 42.4.3 to 42.6.0

pom.xml
[![GEOT-7376](https://badgen.net/badge/JIRA/GEOT-7376/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7376) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4315
=> [Backport 29.x] [GEOT-7376] Upgrade postgresql from 42.4.3 to 42.6.0

pom.xml
[![GEOT-7375](https://badgen.net/badge/JIRA/GEOT-7375/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7375) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4314
=> [Backport 28.x] [GEOT-7375] Upgrade guava from 30.1.1 to 32.0.0

pom.xml
[![GEOT-7375](https://badgen.net/badge/JIRA/GEOT-7375/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7375) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4314
=> [Backport 29.x] [GEOT-7375] Upgrade guava from 30.1.1 to 32.0.0

modules/library/main/src/main/java/org/geotools/geometry/jts/GeometrySmoother.java
[![GEOT-7332](https://badgen.net/badge/JIRA/GEOT-7332/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7332) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4291
**Authored by:** @sebastian-orlowski
=> [Backport 28.x] [GEOT-7332] Resolve incompatibility between LGPL-2.1 and LGPL-3+

modules/library/main/src/main/java/org/geotools/geometry/jts/GeometrySmoother.java
[![GEOT-7332](https://badgen.net/badge/JIRA/GEOT-7332/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7332) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4291
**Authored by:** @sebastian-orlowski
=> [Backport 29.x] [GEOT-7332] Resolve incompatibility between LGPL-2.1 and LGPL-3+

modules/extension/wmts/src/main/java/org/geotools/ows/wmts/model/WMTSCapabilities.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/model/WMTSCapabilitiesTest.java, modules/extension/wmts/src/test/resources/test-data/multilang.getcapa.xml
[![GEOT-7266](https://badgen.net/badge/JIRA/GEOT-7266/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7266) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4296
=> [Backport 28.x] [GEOT-7266] WMTSCapabilities throws NPE for missing title

modules/extension/wmts/src/main/java/org/geotools/ows/wmts/model/WMTSCapabilities.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/model/WMTSCapabilitiesTest.java, modules/extension/wmts/src/test/resources/test-data/multilang.getcapa.xml
[![GEOT-7266](https://badgen.net/badge/JIRA/GEOT-7266/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7266) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4296
=> [Backport 29.x] [GEOT-7266] WMTSCapabilities throws NPE for missing title

docs/developer/conventions/code/code.rst, docs/developer/conventions/code/urlchecker.rst, docs/user/library/main/index.rst, docs/user/library/main/urlchecker.rst, modules/extension/mbstyle/src/main/java/org/geotools/mbstyle/sprite/SpriteGraphicFactory.java, modules/extension/mbstyle/src/test/java/org/geotools/mbstyle/sprite/SpriteGraphicFactoryMockTest.java, modules/library/main/src/main/java/org/geotools/data/ows/URLChecker.java, modules/library/main/src/main/java/org/geotools/data/ows/URLCheckerException.java, modules/library/main/src/main/java/org/geotools/data/ows/URLCheckers.java, modules/library/main/src/test/java/org/geotools/data/ows/MockURLChecker.java, modules/library/main/src/test/java/org/geotools/data/ows/URLCheckersTest.java, modules/library/render/pom.xml, modules/library/render/src/main/java/org/geotools/renderer/style/ImageGraphicFactory.java, modules/library/render/src/test/java/org/geotools/renderer/style/ImageGraphicFactoryTest.java, modules/plugin/svg/pom.xml, modules/plugin/svg/src/main/java/org/geotools/renderer/style/svg/RenderableSVGCache.java, modules/plugin/svg/src/main/java/org/geotools/renderer/style/svg/SVGGraphicFactory.java, modules/plugin/svg/src/test/java/org/geotools/renderer/style/svg/SVGGraphicFactoryTest.java
=> [Backport 29.x] [GEOT-6512] Control remote HTTP requests sent by GeoTools

pom.xml
[![GEOT-7378](https://badgen.net/badge/JIRA/GEOT-7378/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7378) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4329
=> [Backport 29.x] [GEOT-7378] Upgrade commons-lang3 from 3.8.1 to 3.12.0

pom.xml
[![GEOT-7378](https://badgen.net/badge/JIRA/GEOT-7378/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7378) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4329
=> [Backport 28.x] [GEOT-7378] Upgrade commons-lang3 from 3.8.1 to 3.12.0

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicDirectoryWalker.java, pom.xml
[![GEOT-7379](https://badgen.net/badge/JIRA/GEOT-7379/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7379) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Dependency upgrade with bug fixes and new features. Backport is optional for this PR.
=> [GEOT-7379] Upgrade commons-io from 2.10.0 to 2.12.0

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Encoder.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/PullParser.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/ParserHandler.java, modules/library/main/src/main/java/org/geotools/data/store/ContentFeatureCollection.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/GetFeatureRequest.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/GetFeatureResponseParserFactory.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/PullParserFeatureReader.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XsdHttpHandler.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/parsers/AbstractGetFeatureParserTest.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/parsers/PullParserTest.java, modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/internal/parsers/test-data/Mjosovervak_stations.xsd, modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/internal/parsers/test-data/wfs_get_feature.xml
[![GEOT-7365](https://badgen.net/badge/JIRA/GEOT-7365/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7365) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4306
=> [Backport 28.x] [GEOT-7365] Problems with requesting Features from a WFS Version 2.0.0 and using a HTTP proxy

modules/library/main/src/main/java/org/geotools/data/ows/URLChecker.java, modules/library/main/src/main/java/org/geotools/data/ows/URLCheckers.java, modules/library/main/src/test/java/org/geotools/data/ows/URLCheckersTest.java
=> [Backport 29.x] [GEOT-6512] URLCheckers normalize location

modules/library/main/src/main/java/org/geotools/data/ows/URLChecker.java, modules/library/main/src/main/java/org/geotools/data/ows/URLCheckers.java, modules/library/main/src/test/java/org/geotools/data/ows/URLCheckersTest.java
=> [Backport 28.x] [GEOT-6512] URLCheckers normalize location

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/catalog/CatalogConfigurationBean.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/GranuleDescriptorTest.java
[![GEOT-7372](https://badgen.net/badge/JIRA/GEOT-7372/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7372) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4304
=> [Backport 28.x] [GEOT-7372] ImageMosaic SuggestedSPI ignored by GranuleDescriptor

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/catalog/CatalogConfigurationBean.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/GranuleDescriptorTest.java
[![GEOT-7372](https://badgen.net/badge/JIRA/GEOT-7372/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7372) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4304
=> [Backport 29.x] [GEOT-7372] ImageMosaic SuggestedSPI ignored by GranuleDescriptor

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-6266](https://badgen.net/badge/JIRA/GEOT-6266/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6266) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This resolves an issue where entry names containing characters like hyphens and spaces (carried over from GeoServer layer names) caused a crash when exporting a GeoPackage.
In making these changes I noticed a small issue with `getTileBound`, which is that it returns 0 even if the requested zoom level does not exist (as opposed to, say, -1). I haven't changed anything behaviour-wise but just added a couple of assertions to test …
=> [GEOT-6266] Generating GeoPackage fails when layer name has spaces or dashes

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-6266](https://badgen.net/badge/JIRA/GEOT-6266/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6266) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4345
**Authored by:** @mikesname
=> [Backport 28.x] [GEOT-6266] Generating GeoPackage fails when layer name has spaces or dashes

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-6266](https://badgen.net/badge/JIRA/GEOT-6266/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-6266) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4345
**Authored by:** @mikesname
=> [Backport 29.x] [GEOT-6266] Generating GeoPackage fails when layer name has spaces or dashes

modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/S3Connector.java, modules/unsupported/s3-geotiff/src/test/java/org/geotools/s3/S3ConnectorTest.java
Fix for a `UnsupportedOperationException` when setting the region on `AmazonS3Client`. When created with the `AmazonS3ClientBuilder` the `AmazonS3Client` is immutable.
See comment on #4341 for additional details.
=> Fix setting region on immutable AmazonS3Client (s3-geotiff)

modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java
=> [Backport 28.x] Fix failing WMTS unit test

modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java
=> [Backport 29.x] Fix failing WMTS unit test

modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/S3Connector.java, modules/unsupported/s3-geotiff/src/test/java/org/geotools/s3/S3ConnectorTest.java
Backport #4355
**Authored by:** @c-mckenna
=> [Backport 29.x] Fix setting region on immutable AmazonS3Client (s3-geotiff)

modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/S3Connector.java, modules/unsupported/s3-geotiff/src/test/java/org/geotools/s3/S3ConnectorTest.java
Backport #4355
**Authored by:** @c-mckenna
=> [Backport 28.x] Fix setting region on immutable AmazonS3Client (s3-geotiff)

modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/FESParseEncodeUtil.java, modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/MeasureTypeBinding.java, modules/extension/xsd/xsd-fes/src/test/java/org/geotools/filter/v2_0/bindings/DWithinBindingTest.java
[![GEOT-7383](https://badgen.net/badge/JIRA/GEOT-7383/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7383) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This change will bring the encoding / parsing of the Distance element in par with the xsd-schema. And I also have a server that reports error on missing "uom"-attribute.
=> [GEOT-7383] Distance element of DWithin filter should have an attribute "uom"

modules/library/metadata/src/it/commons/pom.xml, modules/library/metadata/src/it/log4j/pom.xml, modules/library/metadata/src/it/logback/pom.xml, modules/library/metadata/src/it/logging/pom.xml, modules/library/metadata/src/it/reload4j/pom.xml, pom.xml
[![GEOT-7382](https://badgen.net/badge/JIRA/GEOT-7382/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7382) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This ensures that the plugins used by integration tests are available locally avoiding complications when running in crazy integration isolated environment
=> [GEOT-7382] Update maven plugins and use the same plugins for integration

modules/library/metadata/src/it/commons/pom.xml, modules/library/metadata/src/it/log4j/pom.xml, modules/library/metadata/src/it/logback/pom.xml, modules/library/metadata/src/it/logging/pom.xml, modules/library/metadata/src/it/reload4j/pom.xml, pom.xml
[![GEOT-7382](https://badgen.net/badge/JIRA/GEOT-7382/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7382) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4356
=> [Backport 28.x] [GEOT-7382] Update maven plugins and use the same plugins for integration

docs/site/update_site.sh
Preliminary version of update_site.sh for use with the new doc server (pending)
**DO NOT MERGE** until docs.geotools.org has been migrated to the new server.
=> Update update_site.sh for the new doc server configuration

modules/unsupported/flatgeobuf/pom.xml, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureCollectionConversions.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureConversions.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureReader.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/ReadAllInterable.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/ReadFidsIterable.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/ReadHitsIterable.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/AttributeRoundtripTest.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FeatureCollectionConversionsTest.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
[![GEOT-7381](https://badgen.net/badge/JIRA/GEOT-7381/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7381) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7381] FlatGeobufDataStore FID filtering

modules/unsupported/flatgeobuf/pom.xml, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureCollectionConversions.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureConversions.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureReader.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/ReadAllInterable.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/ReadFidsIterable.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/ReadHitsIterable.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/AttributeRoundtripTest.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FeatureCollectionConversionsTest.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
[![GEOT-7381](https://badgen.net/badge/JIRA/GEOT-7381/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7381) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4349
=> [Backport 28.x] [GEOT-7381] FlatGeobufDataStore FID filtering

modules/unsupported/flatgeobuf/pom.xml, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureCollectionConversions.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureConversions.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureReader.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/ReadAllInterable.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/ReadFidsIterable.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/ReadHitsIterable.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/AttributeRoundtripTest.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FeatureCollectionConversionsTest.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
[![GEOT-7381](https://badgen.net/badge/JIRA/GEOT-7381/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7381) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4349
=> [Backport 29.x] [GEOT-7381] FlatGeobufDataStore FID filtering

modules/library/main/src/main/java/org/geotools/data/ows/URLCheckers.java, modules/library/main/src/test/java/org/geotools/data/ows/URLCheckersTest.java, modules/library/render/src/main/java/org/geotools/renderer/lite/StyledShapePainter.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StyledShapePainterTest.java
[![GEOT-7387](https://badgen.net/badge/JIRA/GEOT-7387/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7387) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR contains the following changes:
1. Blocks URLs with invalid escape sequences which can interfere with normalization.
2. Blocks URLs with URL encoded percent and slash characters which can interfere with normalization.
3. Blocks URLs if all applicable normalization attempts fail.
4. StyledShapePainter uses URLCheckers for SLD GraphicLegend links.
=> [GEOT-7387] Improve URL checking

modules/library/main/src/main/java/org/geotools/data/ows/URLCheckers.java, modules/library/main/src/test/java/org/geotools/data/ows/URLCheckersTest.java, modules/library/render/src/main/java/org/geotools/renderer/lite/StyledShapePainter.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StyledShapePainterTest.java
[![GEOT-7387](https://badgen.net/badge/JIRA/GEOT-7387/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7387) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
28.x backport for https://github.com/geotools/geotools/pull/4362
=> [28.x][GEOT-7387] Improve URL checking

modules/library/main/src/main/java/org/geotools/data/ows/URLCheckers.java, modules/library/main/src/test/java/org/geotools/data/ows/URLCheckersTest.java, modules/library/render/src/main/java/org/geotools/renderer/lite/StyledShapePainter.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StyledShapePainterTest.java
[![GEOT-7387](https://badgen.net/badge/JIRA/GEOT-7387/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7387) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
29.x backport for https://github.com/geotools/geotools/pull/4362.
=> [29.x][GEOT-7387] Improve URL checking

pom.xml
[![GEOT-7394](https://badgen.net/badge/JIRA/GEOT-7394/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7394) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Dependency upgrade with bug fixes.  Backport is optional.
=> [GEOT-7394] Upgrade httpclient from 4.5.13 to 4.5.14

pom.xml
[![GEOT-7394](https://badgen.net/badge/JIRA/GEOT-7394/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7394) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4386
=> [Backport 29.x] [GEOT-7394] Upgrade httpclient from 4.5.13 to 4.5.14

pom.xml
[![GEOT-7394](https://badgen.net/badge/JIRA/GEOT-7394/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7394) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4386
=> [Backport 28.x] [GEOT-7394] Upgrade httpclient from 4.5.13 to 4.5.14

modules/extension/wms/pom.xml, modules/library/http/pom.xml, modules/library/main/pom.xml, modules/library/main/src/test/java/org/geotools/filter/CapabilitiesTest.java, modules/library/main/src/test/java/org/geotools/filter/function/ListFunctionsTest.java, modules/library/main/src/test/java/org/geotools/temporal/object/DefaultDateAndTimeTest.java, modules/plugin/http-commons/pom.xml, modules/unsupported/stac-store/pom.xml, pom.xml
[![GEOT-7396](https://badgen.net/badge/JIRA/GEOT-7396/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7396) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This dependency upgrade includes security fixes but it is a test dependency so they may not be as important to backport.
=> [GEOT-7396] Upgrade wiremock to 2.35.0

modules/library/referencing/src/main/java/org/geotools/referencing/factory/PropertyCoordinateOperationAuthorityFactory.java
=> [Backport 29.x] Provide more information about failure to read custom operation WKT

modules/library/referencing/src/main/java/org/geotools/referencing/factory/PropertyCoordinateOperationAuthorityFactory.java
=> [Backport 28.x] Provide more information about failure to read custom operation WKT

modules/unsupported/geobuf/src/main/java/org/geotools/data/geobuf/GeobufFeature.java, modules/unsupported/geobuf/src/main/java/org/geotools/data/geobuf/GeobufFeatureType.java, modules/unsupported/geobuf/src/test/java/org/geotools/data/geobuf/GeobufFeatureTest.java
[![GEOT-7313](https://badgen.net/badge/JIRA/GEOT-7313/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7313) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The name of geometry is always `geom`, you can encode a SimpleFeature with a property name of `geom`, but will be failed to decode it.
=> [GEOT-7313] fix gt-geobuf: support arbitrary property name & date type

modules/unsupported/flatgeobuf/pom.xml
=> [Backport 29.x] Upgrade flatgeobuf to  3.26.1

modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java, modules/library/coverage/src/test/java/org/geotools/image/ImageWorkerTest.java, modules/plugin/imageio-ext-gdal/src/main/java/org/geotools/coverageio/BaseGridCoverage2DReader.java, modules/plugin/imageio-ext-gdal/src/main/java/org/geotools/coverageio/RasterLayerRequest.java, modules/plugin/imageio-ext-gdal/src/main/java/org/geotools/coverageio/RasterLayerResponse.java, modules/plugin/imageio-ext-gdal/src/main/java/org/geotools/coverageio/gdal/BaseGDALGridCoverage2DReader.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/vrt/VRTTest.java
=> [Backport 28.x] Support NoData in GDAL readers

modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java, modules/library/coverage/src/test/java/org/geotools/image/ImageWorkerTest.java, modules/plugin/imageio-ext-gdal/src/main/java/org/geotools/coverageio/BaseGridCoverage2DReader.java, modules/plugin/imageio-ext-gdal/src/main/java/org/geotools/coverageio/RasterLayerRequest.java, modules/plugin/imageio-ext-gdal/src/main/java/org/geotools/coverageio/RasterLayerResponse.java, modules/plugin/imageio-ext-gdal/src/main/java/org/geotools/coverageio/gdal/BaseGDALGridCoverage2DReader.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/vrt/VRTTest.java
=> [Backport 29.x] Support NoData in GDAL readers

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDataStoreFactory.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDataStoreFactoryTest.java
[![GEOT-7404](https://badgen.net/badge/JIRA/GEOT-7404/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7404) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7404] Add SQLite Connection Timeout in case of hung GeoPackage connections

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDataStoreFactory.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDataStoreFactoryTest.java
[![GEOT-7404](https://badgen.net/badge/JIRA/GEOT-7404/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7404) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4405
=> [Backport 29.x] [GEOT-7404] Add SQLite Connection Timeout in case of hung GeoPackage connections

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDataStoreFactory.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDataStoreFactoryTest.java
[![GEOT-7404](https://badgen.net/badge/JIRA/GEOT-7404/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7404) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4405
=> [Backport 28.x] [GEOT-7404] Add SQLite Connection Timeout in case of hung GeoPackage connections

modules/library/main/src/main/java/org/geotools/filter/function/IDFunction.java, modules/library/main/src/main/java/org/geotools/filter/function/InterpolateFunction.java, modules/library/main/src/main/java/org/geotools/filter/visitor/SimplifyingFilterVisitor.java, modules/library/main/src/test/java/org/geotools/filter/visitor/SimplifyingFilterVisitorTest.java, modules/library/render/src/main/java/org/geotools/renderer/lite/SimplifyingStyleVisitor.java, modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java, modules/library/render/src/test/java/org/geotools/renderer/lite/SimplifyingStyleVisitorTest.java, modules/library/render/src/test/resources/org/geotools/renderer/lite/test-data/simplify.sld
=> [Backport 29.x] Speed up evaluation of symbolizer properties during rendering

modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicState.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicStore.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7407](https://badgen.net/badge/JIRA/GEOT-7407/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7407) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7407] Vector Mosaic Cache granuleFeatureType at DataStore and improve granule FeatureType acquisition

modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicState.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicStore.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7407](https://badgen.net/badge/JIRA/GEOT-7407/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7407) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4408
=> [Backport 28.x] [GEOT-7407] Vector Mosaic Cache granuleFeatureType at DataStore and improve granule FeatureType acquisition

modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicState.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicStore.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7407](https://badgen.net/badge/JIRA/GEOT-7407/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7407) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4408
=> [Backport 29.x] [GEOT-7407] Vector Mosaic Cache granuleFeatureType at DataStore and improve granule FeatureType acquisition

modules/unsupported/vector-mosaic/pom.xml, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicReaderTest.java
[![GEOT-7420](https://badgen.net/badge/JIRA/GEOT-7420/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7420) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket.
=> [GEOT-7420] Vector mosaic reader: do not recompute the schema for every feature read

modules/unsupported/vector-mosaic/pom.xml, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicReaderTest.java
[![GEOT-7420](https://badgen.net/badge/JIRA/GEOT-7420/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7420) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4427
=> [Backport 28.x] [GEOT-7420] Vector mosaic reader: do not recompute the schema for every feature read

modules/library/referencing/src/main/java/org/geotools/referencing/CRS.java
[![GEOT-7421](https://badgen.net/badge/JIRA/GEOT-7421/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7421) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4423
=> [Backport 29.x] [GEOT-7421] Caching WKT parsing results

modules/unsupported/elasticsearch/pom.xml
this harmonises the version with GeoServer and should resolve #3903
=> Bump org.springframework.security:spring-security-core to 5.7.10

.github/workflows/integration.yml, docs/user/welcome/files/remove-opengis.xml, docs/user/welcome/upgrade.rst, modules/library/api/src/main/java/org/geotools/api/geometry/DirectPosition.java, modules/library/api/src/main/java/org/geotools/api/geometry/coordinate/PointArrayArchive.java, modules/library/api/src/main/java/org/geotools/api/geometry/coordinate/PositionArchive.java, modules/library/main/src/main/java/org/geotools/geometry/jts/coordinatesequence/InPlaceCoordinateSequenceTransformer.java, modules/library/referencing/src/main/java/org/geotools/geometry/AbstractDirectPosition.java, modules/library/referencing/src/main/java/org/geotools/geometry/DirectPosition2D.java, modules/library/referencing/src/main/java/org/geotools/geometry/DirectPosition3D.java, modules/library/referencing/src/main/java/org/geotools/referencing/GeodeticCalculator.java
[![GEOT-7287](https://badgen.net/badge/JIRA/GEOT-7287/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7287) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This feeds into https://github.com/geotools/geotools/pull/4367 as a separate QA activity check
=> [GEOT-7287] Clean up use of DirectPosition and GeneralEnvelope

.github/workflows/integration.yml
[![GEOT-7287](https://badgen.net/badge/JIRA/GEOT-7287/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7287) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Bringing mapfish-v3 back in the migration test build
=> [GEOT-7287] Remove-opengis Mapfish v3

pom.xml
[![GEOT-7440](https://badgen.net/badge/JIRA/GEOT-7440/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7440) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This is a general update to newer versions of maven dependencies. 
Notably not included is an upgrade of spotless + formatter. That changes significant number of files (albeit mostly pretty small changes), and will be handled under https://osgeo-org.atlassian.net/browse/GEOT-7439
- [N/A] …
=> [GEOT-7440] Update maven plugin versions

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCEmptyGeometryOnlineTest.java, modules/library/main/src/main/java/org/geotools/geometry/jts/WKBReader.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISEmptyGeometryOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostGISEmptyGeometryOnlineTest.java
[![GEOT-7363](https://badgen.net/badge/JIRA/GEOT-7363/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7363) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket
=> [GEOT-7363] ParseException if returning POLYGON EMPTY

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCEmptyGeometryOnlineTest.java, modules/library/main/src/main/java/org/geotools/geometry/jts/WKBReader.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISEmptyGeometryOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/ps/PostGISEmptyGeometryOnlineTest.java
[![GEOT-7363](https://badgen.net/badge/JIRA/GEOT-7363/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7363) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4419
=> [Backport 29.x] [GEOT-7363] ParseException if returning POLYGON EMPTY

pom.xml
[![GEOT-7445](https://badgen.net/badge/JIRA/GEOT-7445/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7445) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
https://github.com/geotools/geotools/pull/4478#issuecomment-1723591677 identified an issue from the maven plugin version bumps at https://github.com/geotools/geotools/pull/4478
Fixing this might be more complicated than I can handle right now, so this reverts the javadoc (and site) parts of #4478 
Follow-up tickets https://osgeo-org.atlassian.net/browse/GEOT-7447 and https://osgeo-org.atlassian.net/browse/GEOT-7446 have been …
=> [GEOT-7445] Revert maven javadoc plugin upgrade

modules/unsupported/flatgeobuf/pom.xml
[![GEOT-745](https://badgen.net/badge/JIRA/GEOT-745/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-745) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7451] Upgrade org.json:json to 20230618

modules/unsupported/flatgeobuf/pom.xml
[![GEOT-7451](https://badgen.net/badge/JIRA/GEOT-7451/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7451) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4487
=> [Backport 29.x] [GEOT-7451] Upgrade org.json:json to 20230618

modules/unsupported/flatgeobuf/pom.xml
[![GEOT-7451](https://badgen.net/badge/JIRA/GEOT-7451/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7451) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4487
=> [Backport 28.x] [GEOT-7451] Upgrade org.json:json to 20230618

modules/unsupported/flatgeobuf/pom.xml
[![GEOT-7451](https://badgen.net/badge/JIRA/GEOT-7451/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7451) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4487
=> [Backport 30.x] [GEOT-7451] Upgrade org.json:json to 20230618

docs/pom.xml, modules/extension/app-schema/app-schema/pom.xml, modules/extension/complex/pom.xml, modules/extension/wms/pom.xml, modules/extension/xsd/xsd-core/pom.xml, modules/extension/xsd/xsd-filter/pom.xml, modules/extension/xsd/xsd-gml3/pom.xml, modules/extension/ysld/pom.xml, modules/library/coverage/pom.xml, modules/library/cql/pom.xml, modules/library/http/pom.xml, modules/library/jdbc/pom.xml, modules/library/main/pom.xml, modules/library/referencing/pom.xml, modules/library/render/pom.xml, modules/plugin/coverage-multidim/netcdf/pom.xml, modules/plugin/http-commons/pom.xml, modules/plugin/imageio-ext-gdal/pom.xml, modules/plugin/imagemosaic/pom.xml, modules/plugin/jdbc/jdbc-h2/pom.xml, modules/unsupported/cql2/pom.xml, modules/unsupported/elasticsearch/pom.xml, modules/unsupported/mbtiles/pom.xml, modules/unsupported/ogr/ogr-core/pom.xml, modules/unsupported/process-raster/pom.xml, modules/unsupported/solr/pom.xml, modules/unsupported/wps/pom.xml, pom.xml, release/pom.xml
[![GEOT-7441](https://badgen.net/badge/JIRA/GEOT-7441/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7441) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The sortpom plugin is lagging behind current. See https://github.com/Ekryd/sortpom#news
Note there are two breaking changes, which cause our POM files to change. I think its an improvement though.
=> [GEOT-7441] Upgrade sortpom plugin

modules/unsupported/process/src/main/java/org/geotools/process/Process.java, modules/unsupported/process/src/main/java/org/geotools/process/Progress.java, modules/unsupported/process/src/main/java/org/geotools/process/factory/AnnotationDrivenProcessFactory.java, modules/unsupported/process/src/main/java/org/geotools/process/feature/AbstractFeatureCollectionProcess.java, modules/unsupported/process/src/main/java/org/geotools/process/feature/AbstractFeatureCollectionProcessFactory.java, modules/unsupported/process/src/main/java/org/geotools/process/feature/FeatureToFeatureProcessFactory.java, modules/unsupported/process/src/main/java/org/geotools/process/function/ProcessFunction.java, modules/unsupported/process/src/main/java/org/geotools/process/impl/package-info.java, modules/unsupported/process/src/main/java/org/geotools/process/package-info.java
[![GEOT-7462](https://badgen.net/badge/JIRA/GEOT-7462/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7462) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Part of https://osgeo-org.atlassian.net/browse/GEOT-7447, this just addresses the process module.
One minor code change.
=> [GEOT-7462] Fix javadoc in process module

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/InvertAxisFilterVisitor.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentDataAccess.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSDataAccessFactory.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/AbstractWFSStrategy.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/URIs.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSException.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSResponseFactory.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSStrategy.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/AbstractGetFeatureResponseParserFactory.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/AbstractWFSResponseFactory.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/PullParserFeatureReader.java
[![GEOT-7460](https://badgen.net/badge/JIRA/GEOT-7460/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7460) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Part of https://osgeo-org.atlassian.net/browse/GEOT-7447, this just addresses the WFS-NG module.
No code changes.
=> [GEOT-7460] Fix javadoc in WFS-NG unsupported module

docs/pom.xml, modules/extension/app-schema/app-schema/pom.xml, modules/extension/complex/pom.xml, modules/extension/wms/pom.xml, modules/extension/xsd/xsd-core/pom.xml, modules/extension/xsd/xsd-filter/pom.xml, modules/extension/xsd/xsd-gml3/pom.xml, modules/extension/ysld/pom.xml, modules/library/coverage/pom.xml, modules/library/cql/pom.xml, modules/library/http/pom.xml, modules/library/jdbc/pom.xml, modules/library/main/pom.xml, modules/library/referencing/pom.xml, modules/library/render/pom.xml, modules/plugin/coverage-multidim/netcdf/pom.xml, modules/plugin/http-commons/pom.xml, modules/plugin/imageio-ext-gdal/pom.xml, modules/plugin/imagemosaic/pom.xml, modules/plugin/jdbc/jdbc-h2/pom.xml, modules/unsupported/cql2/pom.xml, modules/unsupported/elasticsearch/pom.xml, modules/unsupported/mbtiles/pom.xml, modules/unsupported/ogr/ogr-core/pom.xml, modules/unsupported/process-raster/pom.xml, modules/unsupported/solr/pom.xml, modules/unsupported/wps/pom.xml, pom.xml, release/pom.xml
[![GEOT-7441](https://badgen.net/badge/JIRA/GEOT-7441/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7441) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4476
**Authored by:** @bradh
=> [Backport 30.x] [GEOT-7441] Upgrade sortpom plugin

modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7429](https://badgen.net/badge/JIRA/GEOT-7429/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7429) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> Geot 7429 vector mosaic native retype 29 x

modules/library/http/src/main/java/org/geotools/http/SimpleHttpClient.java
[![GEOT-7453](https://badgen.net/badge/JIRA/GEOT-7453/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7453) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Remove code that was deprecated.
=> [GEOT-7453] Remove deprecated SimpleHTTPResponse

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSContentComplexFeatureCollection.java
[![GEOT-7452](https://badgen.net/badge/JIRA/GEOT-7452/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7452) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Remove some constructors that were deprecated, and the last code that where using them.
=> [GEOT-7452] Remove deprecated constructors from WFSContentComplexFeatureCollection

modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/FilterToElastic.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFeatureFilterIT.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFilterTest.java, modules/unsupported/geojson-core/src/main/java/com/bedatadriven/jackson/datatype/jts/JtsModule.java, modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java, modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java, modules/unsupported/geojson-store/src/test/java/org/geotools/data/geojson/store/AxisOrderTest.java, modules/unsupported/geojson-store/src/test/java/org/geotools/data/geojson/store/GeoJSONWriteTest.java
[![GEOT-7434](https://badgen.net/badge/JIRA/GEOT-7434/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7434) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
…box filters
=> [GEOT-7434] ElasticSearch throws repeated point exceptions on small bbox filters

.github/workflows/assembly.yml, .github/workflows/linux_jdk11.yml, .github/workflows/linux_jdk17.yml, release/README.md, release/pom.xml, release/src/assembly/binaryDistDependencies.xml, release/src/markdown/README.md, release/src/markdown/html/footer.html
[![GEOT-7472](https://badgen.net/badge/JIRA/GEOT-7472/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7472) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
gt-api was missing from bin download, RUNNING also mentioned Java 8
Verified with:
```
unzip -l target/geotools-*-SNAPSHOT-bin.zip | grep gt-api
225410  10-12-2023 11:52   geotools-31-SNAPSHOT/lib/gt-api-31-SNAPSHOT.jar
```
=> [GEOT-7472] Update bin download for gt-api and java 11

.github/workflows/assembly.yml, .github/workflows/linux_jdk11.yml, .github/workflows/linux_jdk17.yml, release/README.md, release/pom.xml, release/src/assembly/binaryDistDependencies.xml, release/src/markdown/README.md, release/src/markdown/html/footer.html
[![GEOT-7472](https://badgen.net/badge/JIRA/GEOT-7472/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7472) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4519
=> [Backport 30.x] [GEOT-7472] Update bin download for gt-api and java 11

modules/unsupported/flatgeobuf/pom.xml
=> [Backport 29.x] Bump org.json:json from 20230618 to 20231013 in /modules/unsupported/flatgeobuf

modules/unsupported/flatgeobuf/pom.xml
=> [Backport 30.x] Bump org.json:json from 20230618 to 20231013 in /modules/unsupported/flatgeobuf

.github/workflows/linux_gdal.yml, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/GDALTestCase.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/aig/AIGTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/dted/DTEDTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/ecw/ECWTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/ehdr/EsriHdrTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/envihdr/EnviHdrTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/erdasimg/ErdasImgTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/idrisi/IDRISIImgTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/jp2kak/JP2KTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/jp2mrsid/JP2MrSIDTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/mrsid/MrSIDTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/nitf/NITFTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/rpftoc/RPFTOCTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/srp/SRPTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/vrt/VRTTest.java
=> [Backport 29.x] Adding GDAL Github action

.github/workflows/linux_gdal.yml, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/GDALTestCase.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/aig/AIGTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/dted/DTEDTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/ecw/ECWTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/ehdr/EsriHdrTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/envihdr/EnviHdrTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/erdasimg/ErdasImgTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/idrisi/IDRISIImgTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/jp2kak/JP2KTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/jp2mrsid/JP2MrSIDTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/mrsid/MrSIDTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/nitf/NITFTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/rpftoc/RPFTOCTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/srp/SRPTest.java, modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/vrt/VRTTest.java
=> [Backport 30.x] Adding GDAL Github action

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGroupByVisitorOnlineTest.java, modules/library/main/src/main/java/org/geotools/feature/visitor/Aggregate.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-db2/src/test/java/org/geotools/data/db2/DB2GroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2GroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerGroupByVisitorTestSetup.java, modules/unsupported/jdbc-h2gis/src/test/java/org/h2gis/geotools/H2GISGroupByVisitorTestSetup.java
[![GEOT-7480](https://badgen.net/badge/JIRA/GEOT-7480/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7480) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7480] SumVisitor NPE When Value from Database is Null

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGroupByVisitorOnlineTest.java, modules/library/main/src/main/java/org/geotools/feature/visitor/Aggregate.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-db2/src/test/java/org/geotools/data/db2/DB2GroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2GroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerGroupByVisitorTestSetup.java, modules/unsupported/jdbc-h2gis/src/test/java/org/h2gis/geotools/H2GISGroupByVisitorTestSetup.java
[![GEOT-7480](https://badgen.net/badge/JIRA/GEOT-7480/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7480) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4530
=> [Backport 29.x] [GEOT-7480] SumVisitor NPE When Value from Database is Null

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGroupByVisitorOnlineTest.java, modules/library/main/src/main/java/org/geotools/feature/visitor/Aggregate.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-db2/src/test/java/org/geotools/data/db2/DB2GroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2GroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGroupByVisitorTestSetup.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerGroupByVisitorTestSetup.java, modules/unsupported/jdbc-h2gis/src/test/java/org/h2gis/geotools/H2GISGroupByVisitorTestSetup.java
[![GEOT-7480](https://badgen.net/badge/JIRA/GEOT-7480/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7480) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4530
=> [Backport 30.x] [GEOT-7480] SumVisitor NPE When Value from Database is Null

docs/developer/procedures/release.rst
=> Update release instructions after last release

modules/library/xml/src/main/java/org/geotools/xml/resolver/SchemaResolver.java, modules/unsupported/wfs-ng/pom.xml, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentDataAccess.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/impl/WFSContentDataAccessTest.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/KartverketStedsnavnDataStoreOnlineTest.java
=> [Backport 30.x] Backport 4472 to 30.x

modules/library/xml/src/main/java/org/geotools/xml/transform/TransformerBase.java, modules/library/xml/src/test/java/org/geotools/xml/styling/SLDTransformerTest.java
=> Backport 4537 to 29.x

modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/IntersectionFeatureCollection.java, modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/IntersectionFeatureCollectionTest.java
=> [GEOT-7490] WPS Intersection NPE when the Return Value Should be a Point

modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/IntersectionFeatureCollection.java, modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/IntersectionFeatureCollectionTest.java
=> [Backport 29.x] [GEOT-7490] WPS Intersection NPE when the Return Value Should be a Point

modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/IntersectionFeatureCollection.java, modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/IntersectionFeatureCollectionTest.java
=> [Backport 27.x] [GEOT-7490] WPS Intersection NPE when the Return Value Should be a Point

modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/IntersectionFeatureCollection.java, modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/IntersectionFeatureCollectionTest.java
=> [Backport 26.x] [GEOT-7490] WPS Intersection NPE when the Return Value Should be a Point

docs/user/welcome/upgrade.rst
Backport #4531
**Authored by:** @awaterme
=> [Backport 30.x] Docs: Fix package ordering in GT 30x upgrade guide

modules/library/main/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope.java, modules/library/main/src/test/java/org/geotools/geometry/jts/ReferencedEnvelopeTest.java
[![GEOT-7485](https://badgen.net/badge/JIRA/GEOT-7485/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7485) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This is a backport of https://github.com/geotools/geotools/pull/4542
=> [Backport 30.x][GEOT-7485] Double Check ReferencedEnvelope against Rectangle2D behaviour

modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/GMLSchema.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/v3_2/GMLSchema.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/bindings/MultiSurfaceTypeBindingTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/v3_2/bindings/MultiSurfaceTypeBindingTest.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCCurvesTest.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGeometryOnlineTest.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerGeometryOnlineTest.java
[![GEOT-7415](https://badgen.net/badge/JIRA/GEOT-7415/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7415) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
…412)
* Switch binding from Multipolygon to Multisurface for Multisurface type in GML Schema
* Add control on null geometries
* Fix bad value for getGeometryAccordingtoBinding
* Use instanceof for multisurface
* fix compilation warning
* Ensure binding is of type Multipolygon
* Add unit test and change method name
* junit
* Relaunch CI
* Relaunch CI
* Switch binding from Multipolygon to Multisurface for Multisurface type in GML …
=> [Backport 30.x][GEOT-7415] : Error on WFS Transaction with Multisurface features (#4412)

modules/unsupported/flatgeobuf/pom.xml, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
=> [Backport 29.x] Upgrade flatgeobuf to 3.26.2

modules/unsupported/flatgeobuf/pom.xml, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
=> [Backport 30.x] Upgrade flatgeobuf to 3.26.2

modules/library/metadata/src/main/java/org/geotools/util/factory/Hints.java
[![GEOT-7495](https://badgen.net/badge/JIRA/GEOT-7495/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7495) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This was missed during the org.opengis refactoring
=> [GEOT-7495] Correct Hints.REPOSITORY reference org.geotools.api.data.Repository

modules/library/metadata/src/main/java/org/geotools/util/factory/Hints.java
[![GEOT-7495](https://badgen.net/badge/JIRA/GEOT-7495/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7495) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4561
=> [Backport 30.x] [GEOT-7495] Correct Hints.REPOSITORY reference org.geotools.api.data.Repository

pom.xml
[![GEOT-7498](https://badgen.net/badge/JIRA/GEOT-7498/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7498) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Dependency upgrade that includes security fixes (in 11.5.8.0).
=> [GEOT-7498] Upgrade DB2 JDBC driver from 11.5.6.0 to 11.5.9.0

pom.xml
[![GEOT-7498](https://badgen.net/badge/JIRA/GEOT-7498/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7498) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4564
=> [Backport 30.x] [GEOT-7498] Upgrade DB2 JDBC driver from 11.5.6.0 to 11.5.9.0

pom.xml
=> [Backport 30.x] Bump ch.qos.logback:logback-core from 1.2.11 to 1.3.12

modules/library/xml/src/main/java/org/geotools/xml/XMLUtils.java
=> [Backport 30.x] Added a utility method to test for JAXP 1.5 support.

modules/library/main/src/main/java/org/geotools/filter/function/LinFunction.java, modules/library/main/src/main/resources/META-INF/services/org.geotools.api.filter.expression.Function, modules/library/main/src/test/java/org/geotools/filter/function/LinFunctionTest.java
[![GEOT-7419](https://badgen.net/badge/JIRA/GEOT-7419/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7419) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7419] add lin (list in) function

docs/user/artifacts/function_list, modules/library/api/src/main/java/org/geotools/api/filter/expression/SimplifiableFunction.java, modules/library/main/src/main/java/org/geotools/filter/function/NorthFix.java, modules/library/main/src/main/java/org/geotools/filter/visitor/SimplifyingFilterVisitor.java, modules/library/main/src/main/resources/META-INF/services/org.geotools.api.filter.expression.Function, modules/library/main/src/test/java/org/geotools/filter/function/NorthFixTest.java, modules/library/main/src/test/java/org/geotools/filter/visitor/SimplifyingFilterVisitorTest.java, modules/library/render/src/main/java/org/geotools/renderer/lite/SimplifyingStyleVisitor.java, modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java
[![GEOT-7500](https://badgen.net/badge/JIRA/GEOT-7500/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7500) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4585
=> [Backport 30.x] [GEOT-7500] New function fixing a rotation angle to account for local north direction: northFix

modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7507](https://badgen.net/badge/JIRA/GEOT-7507/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7507) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket. While I was at it, simplified the reader code and made feature building more efficient (by re-using the same feature builder over and over).
=> [GEOT-7507] Vector mosaic store: filtering is not working if it uses a property that's not retrieved by the query

modules/unsupported/swing/src/main/java/org/geotools/swing/MapLayerTable.java
[![GEOT-7504](https://badgen.net/badge/JIRA/GEOT-7504/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7504) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
[GEOT-7504] Add MapLayerTable.onMoveLayer() 
org.geotools.map.MapContent.moveLayer(sourcePosition, destPosition) doesn't change the Layer's order in the MapLayerTable. The order of the Layers in the MapContent should be synchronized with the order of the Layers in the MapLayerTable, and vice versa.
=> [GEOT-7504] MapContent.moveLayer() doesn't change the Layer's order in the MapLayerTable.

.github/workflows/mysql_online.yml
The `8` tag currently actually is 8.2, so no tests were run against 8.0 anymore.
5.7.x tagged images are still available, but it seems to be no longer supported: https://www.mysql.com/support/supportedplatforms/database.html so not sure if we should continue running those?...
=> Make MySQL test matrix more specific

.github/workflows/mysql_online.yml
=> [Backport 30.x] Make MySQL test matrix more specific

.github/workflows/macos.yml
As discussed on the ML thread starting with: [[Geotools-devel] Can anyone figure out the GDAL setup failure in the MAC OS build?](https://sourceforge.net/p/geotools/mailman/message/58708948/)
=> [CI] Run `brew update`/`brew upgrade` on MacOS runner to make sure packages are up-2-date

.github/workflows/macos.yml
=> [Backport 30.x] [CI] Run `brew update`/`brew upgrade` on MacOS runner to make sure packages are up-2-date

.github/workflows/macos.yml
=> [Backport 29.x] [CI] Run `brew update`/`brew upgrade` on MacOS runner to make sure packages are up-2-date

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureSource.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureStore.java, modules/library/main/src/main/java/org/geotools/data/store/ContentFeatureSource.java, modules/library/main/src/main/java/org/geotools/data/store/ContentFeatureStore.java, modules/library/main/src/test/java/org/geotools/data/store/ContentFeatureSourceTest.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureStore.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureSource.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureStore.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticFeatureSource.java, modules/unsupported/ogr/ogr-core/src/main/java/org/geotools/data/ogr/OGRFeatureSource.java, modules/unsupported/ogr/ogr-core/src/main/java/org/geotools/data/ogr/OGRFeatureStore.java, modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrFeatureSource.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/store/STACFeatureSource.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSFeatureSource.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSFeatureStore.java
[![GEOT-7509](https://badgen.net/badge/JIRA/GEOT-7509/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7509) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The intent is to allow for data stores that can optimize for certain query capabilities based on the actual query. The need for this was discovered in https://github.com/geotools/geotools/pull/4590.
This PR implements this by adding new capability methods that has query as parameter and deprecates the only parameter-less capability methods.
=> [GEOT-7509] Introduce query as context to ContentFeatureSource capabilities

modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/S3Connector.java, modules/unsupported/s3-geotiff/src/test/java/org/geotools/s3/S3ConnectorTest.java
Backport #4604
**Authored by:** @mloeks
=> [Backport 30.x] Fix updating immutable AmazonS3 client

modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/S3Connector.java, modules/unsupported/s3-geotiff/src/test/java/org/geotools/s3/S3ConnectorTest.java
Backport #4604
**Authored by:** @mloeks
=> [Backport 29.x] Fix updating immutable AmazonS3 client

modules/library/main/src/main/java/org/geotools/filter/function/PointOnLineFunction.java, modules/library/main/src/main/resources/META-INF/services/org.geotools.api.filter.expression.Function, modules/library/main/src/test/java/org/geotools/filter/function/PointOnLineFunctionTest.java
[![GEOT-7515](https://badgen.net/badge/JIRA/GEOT-7515/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7515) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4617
=> [Backport 30.x] [GEOT-7515] PointOnLine function, looking up a point along the line

modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureCollectionConversions.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufDataStore.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureReader.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureSource.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/ReadAllInterable.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
[![GEOT-7502](https://badgen.net/badge/JIRA/GEOT-7502/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7502) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
- [ x First PR targets the `main` branch (backports managed later; ignore for branch specific issues).
=> [GEOT-7502] Optimize FlatGeobuf DataStore for raw Query with startIndex

modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/RuleBuilder.java, modules/extension/brewer/src/test/java/org/geotools/brewer/styling/builder/StyleBuilderTest.java, modules/library/xml/src/main/java/org/geotools/xml/styling/SLDParser.java, modules/library/xml/src/test/java/org/geotools/xml/styling/SLDParserTest.java
[![GEOT-7518](https://badgen.net/badge/JIRA/GEOT-7518/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7518) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4623
**Authored by:** @vuilleumierc
=> [Backport 30.x] [GEOT-7518, GEOT-7519] Fix i18n in legend rules

modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/FeatureTypeHandler.java, modules/unsupported/geojson/src/test/java/org/geotools/geojson/FeatureJSONTest.java
[![GEOT-7513](https://badgen.net/badge/JIRA/GEOT-7513/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7513) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4613
**Authored by:** @AntoineLecacheurInsee
=> [Backport 30.x] [GEOT-7513] FeatureTypeHandler handle conflicting types Double and Long

modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFMosaicReaderTest.java
[![GEOT-7522](https://badgen.net/badge/JIRA/GEOT-7522/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7522) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Modification of the test NetCDFMosaicReaderTest.testGranuleSourceFileView() by the addition of a line of code to set the Timezone of the JVM before running two assertEquals using a timestamp. Without this change, the test uses the computer's Timezone  when running "mvn install". The Timezone is set to "UTC" for UTC+0:00.
=> [GEOT- 7522] NetCDFMosaicReaderTest failure

modules/unsupported/jdbc-h2gis/src/test/java/org/h2gis/geotools/H2GISDataStoreFactoryTest.java
=> [Backport 30.x] Make sure the test is not creating a database in the module root, where the mvn clean will not delete it

modules/unsupported/jdbc-h2gis/src/test/java/org/h2gis/geotools/H2GISDataStoreFactoryTest.java
=> [Backport 29.x] Make sure the test is not creating a database in the module root, where the mvn clean will not delete it

modules/unsupported/jdbc-h2gis/src/test/java/org/h2gis/geotools/H2GISTest.java
=> [Backport 30.x] Fix one more H2GIS test in a shared directory

modules/unsupported/jdbc-h2gis/src/test/java/org/h2gis/geotools/H2GISTest.java
=> [Backport 29.x] Fix one more H2GIS test in a shared directory

modules/unsupported/vector-mosaic/pom.xml, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/GranuleStoreFinderImpl.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicGranule.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFilterTest.java, modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data2/Lakes.properties, modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data2/RoadSegmentsAll.properties, modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data2/RoadSegmentsFilter.properties, modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data2/RoadSegmentsNone.properties, modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data2/RoadSegmentsRepository.properties, modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data2/granules/RoadSegments1.properties, modules/unsupported/vector-mosaic/src/test/resources/org.geotools.vectormosaic.data2/granules/RoadSegments2.properties
=> [Backport 30.x] Vector mosaic: support granule filtering and picking granules from a repository

pom.xml
[![GEOT-7529](https://badgen.net/badge/JIRA/GEOT-7529/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7529) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This provides SystemUtils constants for Java 17 and Java 21 environments.
This PR relies on existing test coverage, and github workflows to test in Java 17 and Java 21 environment.
=> [GEOT-7529] Update Apache Commons-lang3 to version 3.14

pom.xml
=> [Backport 30.x] Bump org.postgresql:postgresql from 42.6.0 to 42.7.2

modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java, modules/library/render/src/test/java/org/geotools/renderer/GeneralizationDistanceTest.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java
[![GEOT-7527](https://badgen.net/badge/JIRA/GEOT-7527/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7527) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4659
=> [Backport 30.x] [GEOT-7527] StreamingRenderer can ask stores to simplify geometries with a distance of 'zero'

modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java, modules/library/render/src/test/java/org/geotools/renderer/GeneralizationDistanceTest.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java
[![GEOT-7527](https://badgen.net/badge/JIRA/GEOT-7527/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7527) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4659
=> [Backport 29.x] [GEOT-7527] StreamingRenderer can ask stores to simplify geometries with a distance of 'zero'

modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/GDALTestCase.java
[![GEOT-7532](https://badgen.net/badge/JIRA/GEOT-7532/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7532) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4667
=> [Backport 30.x] [GEOT-7532] GDALTestCase superfluous reports on missing test.zip

modules/plugin/imageio-ext-gdal/src/test/java/org/geotools/coverageio/gdal/GDALTestCase.java
[![GEOT-7532](https://badgen.net/badge/JIRA/GEOT-7532/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7532) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4667
=> [Backport 29.x] [GEOT-7532] GDALTestCase superfluous reports on missing test.zip

docs/index/index.rst
[![GEOT-7539](https://badgen.net/badge/JIRA/GEOT-7539/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7539) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7539] The latest tutorials link is broken in https://docs.geotools.org/

docs/user/tutorial/datastore/optimisation.rst, docs/user/welcome/upgrade.rst
[![GEOT-7509](https://badgen.net/badge/JIRA/GEOT-7509/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7509) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
To close https://osgeo-org.atlassian.net/browse/GEOT-7509, Bjorn and I attempted to modify the DataStore Optimisation tutorial.
We would really appreciate an informed opinion on whether this is sufficient.
=> [GEOT-7509] Document query parameter

docs/user/tutorial/datastore/optimisation.rst, docs/user/welcome/upgrade.rst
[![GEOT-7509](https://badgen.net/badge/JIRA/GEOT-7509/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7509) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4700
**Authored by:** @petersmythe
=> [Backport 31.x] [GEOT-7509] Document query parameter

pom.xml
=> [Backport 31.x] Bump org.apache.solr:solr-solrj from 8.9.0 to 8.11.3

modules/library/api/src/main/java/org/geotools/api/referencing/operation/TransformException.java, modules/library/main/src/main/java/org/geotools/renderer/crs/GeosProjectionHandlerFactory.java, modules/library/main/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java, modules/library/main/src/main/resources/META-INF/services/org.geotools.renderer.crs.ProjectionHandlerFactory, modules/library/main/src/test/java/org/geotools/renderer/crs/GeosProjectionHandlerFactoryTest.java, modules/library/main/src/test/java/org/geotools/renderer/crs/ProjectionHandlerTest.java, modules/library/referencing/src/main/java/org/geotools/referencing/EnvelopeReprojector.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/wms/Auto97004.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/wms/AutoCRSFactory.java, modules/library/referencing/src/main/java/org/geotools/referencing/operation/projection/GeostationarySatellite.java, modules/library/referencing/src/main/java/org/geotools/referencing/operation/transform/WarpAdapter.java, modules/library/referencing/src/test/java/org/geotools/referencing/EnvelopeReprojectorTest.java, modules/library/referencing/src/test/java/org/geotools/referencing/factory/wms/AUTOTest.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java
For Geostationary satellite, add an AUTO code and a projection handler.
The projection is however so finicky that the above are not enough, a new algorithm based on bisection has been introduced to transform envelopes in projections that do not like "rectangular" areas (e.g., geostationary area of validity looks roughly like a circle in lon/lat, any reprojection outside of it would fail).
Since that involves a number of trials and errors with exceptions, TransformException stack trace filling is now optional, to work with situations where many errors are foreseeable (helps in envelope reprojection, helps a lot in raster reprojection).
Downstream build is expected to fail due to differences in envelope reprojection, has been adjusted as a consequence in this PR: …
=> Geostationary satellite projection improvements, and try harder to reproject envelopes

modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/GranuleSourceProvider.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7551](https://badgen.net/badge/JIRA/GEOT-7551/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7551) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7551] Vector mosaic: delegate count to granule stores

modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/GranuleSourceProvider.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7551](https://badgen.net/badge/JIRA/GEOT-7551/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7551) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4711
=> [Backport 30.x] [GEOT-7551] Vector mosaic: delegate count to granule stores

modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/GranuleSourceProvider.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureReader.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicFeatureSource.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFeatureSourceTest.java
[![GEOT-7551](https://badgen.net/badge/JIRA/GEOT-7551/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7551) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4711
=> [Backport 31.x] [GEOT-7551] Vector mosaic: delegate count to granule stores

modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufDataStore.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureSource.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureWriter.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDirectoryDataStoreTest.java
[![GEOT-7552](https://badgen.net/badge/JIRA/GEOT-7552/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7552) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7552] Improve flatgeobuf ability to quickly perform count/bounds

modules/extension/complex/src/main/java/org/geotools/data/complex/expression/FeaturePropertyAccessorFactory.java, modules/library/main/src/main/java/org/geotools/filter/expression/SimpleFeaturePropertyAccessorFactory.java, modules/unsupported/vector-mosaic/src/main/java/org/geotools/vectormosaic/VectorMosaicPostPreFilterSplitter.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicFilterTest.java, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicReaderTest.java
[![GEOT-7553](https://badgen.net/badge/JIRA/GEOT-7553/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7553) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7553] Vector mosaic store does not optimize filters using the default geometry name

modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufDataStore.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureSource.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureWriter.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDirectoryDataStoreTest.java
[![GEOT-7552](https://badgen.net/badge/JIRA/GEOT-7552/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7552) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4710
=> [Backport 30.x] [GEOT-7552] Improve flatgeobuf ability to quickly perform count/bounds

modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufDataStore.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureSource.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureWriter.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDirectoryDataStoreTest.java
[![GEOT-7552](https://badgen.net/badge/JIRA/GEOT-7552/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7552) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4710
=> [Backport 31.x] [GEOT-7552] Improve flatgeobuf ability to quickly perform count/bounds

pom.xml
[![GEOT-7549](https://badgen.net/badge/JIRA/GEOT-7549/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7549) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Updated the links for Java SE 11 Javadocs.
=> [GEOT-7549] Update javadoc links

pom.xml
[![GEOT-7549](https://badgen.net/badge/JIRA/GEOT-7549/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7549) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4708
=> [Backport 31.x] [GEOT-7549] Update javadoc links

modules/library/cql/ECQL.md
The ECQL doc mentions "geography literal" but there is no such thing. There is however a "geometry literal" which I think was meant.
=> Fix typo "geography literal" -> "geometry literal"

modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/PAMResourceInfo.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicFileResourceInfo.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RATCollectorListener.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterManager.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicRATTest.java, modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/bluetopo/BlueTopo_BH4JS577_20230918.tiff.small.aux.xml
[![GEOT-7563](https://badgen.net/badge/JIRA/GEOT-7563/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7563) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4732
=> [Backport 31.x] [GEOT-7563] Allow to recompute an image mosaic summary Raster Attribute Table

modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReader.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java, pom.xml
[![GEOT-7565](https://badgen.net/badge/JIRA/GEOT-7565/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7565) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4733
=> [Backport 31.x] [GEOT-7565] Upgrade ImageIO-Ext to 1.4.10

modules/unsupported/css/pom.xml
=> [Backport 31.x] Remove opens no longer needed for Java 17

pom.xml
[![GEOT-7567](https://badgen.net/badge/JIRA/GEOT-7567/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7567) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4744
=> [Backport 30.x] [GEOT-7567] Upgrade guava from 32.0.0 to 33.2.0

pom.xml
[![GEOT-7567](https://badgen.net/badge/JIRA/GEOT-7567/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7567) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4744
=> [Backport 31.x] [GEOT-7567] Upgrade guava from 32.0.0 to 33.2.0

pom.xml
[![GEOT-7566](https://badgen.net/badge/JIRA/GEOT-7566/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7566) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4743
=> [Backport 30.x] [GEOT-7566] Upgrade commons-io from 2.12.0 to 2.16.1

pom.xml
[![GEOT-7566](https://badgen.net/badge/JIRA/GEOT-7566/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7566) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4743
=> [Backport 31.x] [GEOT-7566] Upgrade commons-io from 2.12.0 to 2.16.1

build/release/build_release.sh, build/release/publish_release.sh, pom.xml
There is no Javadoc jars published alongside the jar and sources. I believe this is because of a missing javadoc:jar call before the install.
In addition I've removed a warning for wrong configuration (additionalparam), and the keywords option is just necessary for the javadoc that are published to a web site.
=> [GEOT-7556] Generate javadoc for Maven deploy

modules/library/main/pom.xml, pom.xml
[![GEOT-7574](https://badgen.net/badge/JIRA/GEOT-7574/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7574) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR is just a regular dependency upgrade. The dependency version was moved into the root pom.xml for easier management.
=> [GEOT-7574] Upgrade commons-text from 1.10.0 to 1.12.0

pom.xml
[![GEOT-7573](https://badgen.net/badge/JIRA/GEOT-7573/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7573) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR is just a regular dependency upgrade.
=> [GEOT-7573] Upgrade PostgreSQL driver from 42.7.2 to 42.7.3

build/release/build_release.sh, build/release/publish_release.sh, pom.xml
=> [Backport 30.x] [GEOT-7556] Generate javadoc for Maven deploy

build/release/build_release.sh, build/release/publish_release.sh, pom.xml
=> [Backport 31.x] [GEOT-7556] Generate javadoc for Maven deploy

modules/library/main/src/main/java/org/geotools/renderer/crs/WrappingCoordinateFilter.java, modules/library/main/src/main/java/org/geotools/renderer/crs/WrappingProjectionHandler.java, modules/library/main/src/test/java/org/geotools/renderer/crs/WrappingProjectionHandlerTest.java
[![GEOT-7570](https://badgen.net/badge/JIRA/GEOT-7570/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7570) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4747
=> [Backport 30.x] [GEOT-7570] Small features that cross the dateline may be interpreted as preflipped

modules/library/main/src/main/java/org/geotools/renderer/crs/WrappingCoordinateFilter.java, modules/library/main/src/main/java/org/geotools/renderer/crs/WrappingProjectionHandler.java, modules/library/main/src/test/java/org/geotools/renderer/crs/WrappingProjectionHandlerTest.java
[![GEOT-7570](https://badgen.net/badge/JIRA/GEOT-7570/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7570) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4747
=> [Backport 31.x] [GEOT-7570] Small features that cross the dateline may be interpreted as preflipped

modules/library/main/pom.xml, pom.xml
[![GEOT-7574](https://badgen.net/badge/JIRA/GEOT-7574/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7574) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4757
=> [Backport 30.x] [GEOT-7574] Upgrade commons-text from 1.10.0 to 1.12.0

modules/library/main/pom.xml, pom.xml
[![GEOT-7574](https://badgen.net/badge/JIRA/GEOT-7574/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7574) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4757
=> [Backport 31.x] [GEOT-7574] Upgrade commons-text from 1.10.0 to 1.12.0

pom.xml
[![GEOT-7573](https://badgen.net/badge/JIRA/GEOT-7573/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7573) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4756
=> [Backport 31.x] [GEOT-7573] Upgrade PostgreSQL driver from 42.7.2 to 42.7.3

docs/user/welcome/upgrade.rst, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/KeysFetcher.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/PreparedStatementSQLDialect.java, modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java, modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaDialect.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonWriterOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonWriterPSOnlineTest.java
[![GEOT-7571](https://badgen.net/badge/JIRA/GEOT-7571/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7571) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Support for INSERT/UPDATE on PostGIS json/jsonb columns.
The change affects the core of the JDBC code. So I have tried out some variants and found this solution the least intrusive. I have run various online tests to make sure not to break things (PostGIS, Oracle, SQL Server, DB2,  HANA, mySQL). Also paid attention to GeoPackage and H2-DB.
Thank you for considering this!
Best regards,
Andreas
=> [GEOT-7571] Support INSERT/UPDATE on PostGIS json/jsonb columns

modules/library/main/src/main/java/org/geotools/filter/function/JsonFunctionUtils.java, modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/client/STACFilterSerializer.java, pom.xml
[![GEOT-7577](https://badgen.net/badge/JIRA/GEOT-7577/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7577) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR is just a regular dependency upgrade. Code changes removes use of deprecated API and implements a new abstract method.
=> [GEOT-7577] Upgrade jackson from 2.15.2 to 2.17.1

modules/extension/ysld/pom.xml, pom.xml
[![GEOT-7578](https://badgen.net/badge/JIRA/GEOT-7578/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7578) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR is just a regular dependency upgrade. Dependency version moved into the root pom.xml for easier management.
=> [GEOT-7578] Upgrade snakeyaml from 2.0 to 2.2

modules/library/main/src/main/java/org/geotools/filter/function/JsonFunctionUtils.java, modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/client/STACFilterSerializer.java, pom.xml
[![GEOT-7577](https://badgen.net/badge/JIRA/GEOT-7577/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7577) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4769
=> [Backport 31.x] [GEOT-7577] Upgrade jackson from 2.15.2 to 2.17.1

modules/extension/ysld/pom.xml, pom.xml
[![GEOT-7578](https://badgen.net/badge/JIRA/GEOT-7578/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7578) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4770
=> [Backport 30.x] [GEOT-7578] Upgrade snakeyaml from 2.0 to 2.2

modules/extension/ysld/pom.xml, pom.xml
[![GEOT-7578](https://badgen.net/badge/JIRA/GEOT-7578/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7578) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4770
=> [Backport 31.x] [GEOT-7578] Upgrade snakeyaml from 2.0 to 2.2

modules/library/main/src/main/java/org/geotools/filter/function/JsonFunctionUtils.java, modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java, modules/unsupported/stac-store/src/main/java/org/geotools/stac/client/STACFilterSerializer.java, pom.xml
[![GEOT-7577](https://badgen.net/badge/JIRA/GEOT-7577/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7577) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4769
=> [Backport 30.x] [GEOT-7577] Upgrade jackson from 2.15.2 to 2.17.1

build/release/publish_release.sh
=> Revert GEOT-7556 Generate javadoc at deploy

pom.xml
[![GEOT-7582](https://badgen.net/badge/JIRA/GEOT-7582/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7582) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7582] Upgrade to ImageIO-EXT 1.4.11

pom.xml
[![GEOT-7582](https://badgen.net/badge/JIRA/GEOT-7582/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7582) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4780
=> [Backport 31.x] [GEOT-7582] Upgrade to ImageIO-EXT 1.4.11

modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureConversions.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/AttributeRoundtripTest.java
[![GEOT-7569](https://badgen.net/badge/JIRA/GEOT-7569/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7569) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
It was noted in https://osgeo-org.atlassian.net/browse/GEOT-7569 that FlatGeobuf implementation doesn't handle java.util.Date in serialization. This PR fixes that and also ensures iso format correctness to avoid some likely other bugs.
=> [GEOT-7579] FlatGeobuf handle java.util.Date and iso correctness

modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureConversions.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/AttributeRoundtripTest.java
[![GEOT-7579](https://badgen.net/badge/JIRA/GEOT-7579/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7579) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4768
=> [Backport 30.x] [GEOT-7579] FlatGeobuf handle java.util.Date and iso correctness

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-7586](https://badgen.net/badge/JIRA/GEOT-7586/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7586) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
GeoServer issue - https://osgeo-org.atlassian.net/browse/GEOS-11415
Geotools can create GeoPackages with incorrect column types.  Typically this will happen if you have a JDBC (i.e. postgis) layer and then request a WFS with GeoPackage output.
The issue is caused because some Datastores (i.e. postgis) add JDBC_NATIVE_TYPENAME and JDBC_NATIVE_TYPE column metadata (descriptor userdata) to the schema.  The JDBCDatastore then …
=> [GEOT-7586] GeoPackage output contains invalid field types

modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/AttributeRoundtripTest.java
=> [Backport 30.x] FlatGeobuf fix AttributeRoundtripTest exotic1 flakyness

modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/AttributeRoundtripTest.java
=> [Backport 31.x] FlatGeobuf fix AttributeRoundtripTest exotic1 flakyness

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-7586](https://badgen.net/badge/JIRA/GEOT-7586/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7586) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4788
**Authored by:** @davidblasby
=> [Backport 31.x] [GEOT-7586] GeoPackage output contains invalid field types

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-7586](https://badgen.net/badge/JIRA/GEOT-7586/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7586) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4788
**Authored by:** @davidblasby
=> [Backport 30.x] [GEOT-7586] GeoPackage output contains invalid field types

.github/workflows/assembly.yml, pom.xml, tutorials/quickstart/pom.xml
=> [GEOT-7556] maven javadoc aggregate quickstart tutorial fix

.github/workflows/assembly.yml, pom.xml
Follow on to https://github.com/geotools/geotools/pull/4779 as we can only test in Jenkins.
This PR is adding both a fix and a GitHub workflow check so javadocs do not break build.
=> [GEOT-7556] Just build javadocs for modules, and mvn javadoc doclint config

.github/workflows/assembly.yml, pom.xml, tutorials/quickstart/pom.xml
=> [Backport 30.x] [GEOT-7556] maven javadoc aggregate quickstart tutorial fix

.github/workflows/assembly.yml, pom.xml, tutorials/quickstart/pom.xml
=> [Backport 31.x] [GEOT-7556] maven javadoc aggregate quickstart tutorial fix

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/util/XmlXpathUtilites.java, modules/extension/app-schema/app-schema/src/test/java/org/geotools/appschema/util/XmlXpathUtilitesTest.java, modules/extension/complex/src/main/java/org/geotools/data/complex/expression/FeaturePropertyAccessorFactory.java, modules/extension/complex/src/main/java/org/geotools/data/complex/expression/MapPropertyAccessorFactory.java, modules/extension/complex/src/test/java/org/geotools/filter/expression/FeaturePropertyAccessorTest.java, modules/extension/complex/src/test/java/org/geotools/filter/expression/MapPropertyAccessorTest.java, modules/extension/xsd/xsd-core/pom.xml, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathStreamingParserHandler.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathUtils.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/StreamingParserTest.java
=> [Backport 30.x] [GEOT-7587] Improve handling of XPath expressions

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/util/XmlXpathUtilites.java, modules/extension/app-schema/app-schema/src/test/java/org/geotools/appschema/util/XmlXpathUtilitesTest.java, modules/extension/complex/src/main/java/org/geotools/data/complex/expression/FeaturePropertyAccessorFactory.java, modules/extension/complex/src/main/java/org/geotools/data/complex/expression/MapPropertyAccessorFactory.java, modules/extension/complex/src/test/java/org/geotools/filter/expression/FeaturePropertyAccessorTest.java, modules/extension/complex/src/test/java/org/geotools/filter/expression/MapPropertyAccessorTest.java, modules/extension/xsd/xsd-core/pom.xml, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathStreamingParserHandler.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathUtils.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/StreamingParserTest.java
=> [Backport 31.x] [GEOT-7587] Improve handling of XPath expressions

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/util/XmlXpathUtilites.java, modules/extension/app-schema/app-schema/src/test/java/org/geotools/appschema/util/XmlXpathUtilitesTest.java, modules/extension/complex/src/main/java/org/geotools/data/complex/expression/FeaturePropertyAccessorFactory.java, modules/extension/complex/src/main/java/org/geotools/data/complex/expression/MapPropertyAccessorFactory.java, modules/extension/complex/src/test/java/org/geotools/filter/expression/FeaturePropertyAccessorTest.java, modules/extension/complex/src/test/java/org/geotools/filter/expression/MapPropertyAccessorTest.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathStreamingParserHandler.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathUtils.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/StreamingParserTest.java
=> [29.x backport] [GEOT-7587] Improve handling of XPath expressions

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/util/XmlXpathUtilites.java, modules/extension/app-schema/app-schema/src/test/java/org/geotools/appschema/util/XmlXpathUtilitesTest.java, modules/extension/complex/src/main/java/org/geotools/data/complex/expression/FeaturePropertyAccessorFactory.java, modules/extension/complex/src/main/java/org/geotools/data/complex/expression/MapPropertyAccessorFactory.java, modules/extension/complex/src/test/java/org/geotools/filter/expression/FeaturePropertyAccessorTest.java, modules/extension/complex/src/test/java/org/geotools/filter/expression/MapPropertyAccessorTest.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathStreamingParserHandler.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/jxpath/JXPathUtils.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/StreamingParserTest.java
=> [Backport 28.x] [GEOT-7587] Improve handling of XPath expressions

.github/workflows/assembly.yml, docs/build.xml, docs/readme.md, docs/requirements.txt, pom.xml, tutorials/quickstart/pom.xml
I need the build to work as I wish to make a 2.29.x. - however these do not make any changes to the code
Backporting several things:
* https://github.com/geotools/geotools/pull/4779
*  https://github.com/geotools/geotools/pull/4796
=> [Backport 29.x][GEOT-7556] maven javadoc aggregate quickstart tutorial fix

pom.xml
[![GEOT-7597](https://badgen.net/badge/JIRA/GEOT-7597/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7597) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7597] Upgrade to ImageIO-EXT 1.4.12

pom.xml
[![GEOT-7597](https://badgen.net/badge/JIRA/GEOT-7597/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7597) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4811
=> [Backport 31.x] [GEOT-7597] Upgrade to ImageIO-EXT 1.4.12

modules/library/main/src/main/java/org/geotools/filter/function/InterpolateFunction.java, modules/library/main/src/test/java/org/geotools/filter/function/InterpolateFunctionTest.java
[![GEOT-7607](https://badgen.net/badge/JIRA/GEOT-7607/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7607) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Fix `org.geotools.filter.function.InterpolateFunction` argument validateion and context fallback.
The defect was exposed by [GEOT-7414] at commit d7991fdc, as `InterpolateFunctionImpl` wouldn't adhere to the interface contract when receiving `null` or `Object.class` as `context` parameter.
=> [GEOT-7607] Error using function Interpolate in COLOR mode from SLD

modules/library/main/src/main/java/org/geotools/filter/function/InterpolateFunction.java, modules/library/main/src/test/java/org/geotools/filter/function/InterpolateFunctionTest.java
[![GEOT-7607](https://badgen.net/badge/JIRA/GEOT-7607/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7607) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4819
**Authored by:** @groldan
=> [Backport 30.x] [GEOT-7607] Error using function Interpolate in COLOR mode from SLD

modules/library/main/src/main/java/org/geotools/filter/function/InterpolateFunction.java, modules/library/main/src/test/java/org/geotools/filter/function/InterpolateFunctionTest.java
[![GEOT-7607](https://badgen.net/badge/JIRA/GEOT-7607/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7607) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4819
**Authored by:** @groldan
=> [Backport 31.x] [GEOT-7607] Error using function Interpolate in COLOR mode from SLD

.github/workflows/mysql_online.yml
[![GEOT-7599](https://badgen.net/badge/JIRA/GEOT-7599/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7599) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Update the MySQL online workflow to test against 8.0, 8.2 and (new/added) 8.4, dropping/removing 5.7 from the test matrix.
=> [GEOT-7599] Update MySQL CI matrix (drop 5.7, add 8.4)

docs/user/library/jdbc/postgis.rst, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisPSFilterToSql.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisJsonPathExistsTest.java
[![GEOT-7589](https://badgen.net/badge/JIRA/GEOT-7589/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7589) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4805
**Authored by:** @Mike7311
=> [Backport 30.x] [GEOT-7589] Fix the JsonArrayDelegation for Postgres to support searching in root level array

docs/user/library/jdbc/postgis.rst, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisPSFilterToSql.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisJsonPathExistsTest.java
[![GEOT-7589](https://badgen.net/badge/JIRA/GEOT-7589/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7589) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4805
**Authored by:** @Mike7311
=> [Backport 31.x] [GEOT-7589] Fix the JsonArrayDelegation for Postgres to support searching in root level array

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/filter/expression/ToLineStringFunction.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/filter/expression/ToPointFunction.java, modules/extension/app-schema/app-schema/src/test/java/org/geotools/appschema/filter/GeometryFunctionsTest.java, modules/extension/transform/src/main/java/org/geotools/data/transform/CRSEvaluator.java, modules/extension/transform/src/main/java/org/geotools/data/transform/TransformFeatureCollection.java, modules/extension/transform/src/main/java/org/geotools/data/transform/Transformer.java, modules/extension/transform/src/test/java/org/geotools/data/transform/TransformFeatureSourceTest.java, modules/library/main/src/main/java/org/geotools/api/data/Query.java, modules/library/main/src/main/java/org/geotools/feature/simple/SimpleFeatureBuilder.java, modules/library/main/src/main/java/org/geotools/feature/simple/SimpleFeatureTypeBuilder.java, modules/library/main/src/main/java/org/geotools/feature/type/Types.java, modules/library/main/src/main/java/org/geotools/geometry/jts/JTS.java, modules/library/main/src/test/java/org/geotools/feature/simple/SimpleFeatureBuilderTest.java, modules/library/main/src/test/java/org/geotools/feature/simple/SimpleTypeBuilderTest.java, modules/library/main/src/test/java/org/geotools/feature/type/TypesTest.java, modules/library/main/src/test/java/org/geotools/geometry/jts/JTSTest.java, modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
[![GEOT-7601](https://badgen.net/badge/JIRA/GEOT-7601/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7601) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4818
=> [Backport 31.x] [GEOT-7601] Transform FeatureCollection Query handling of reprojection

pom.xml
[![GEOT-7615](https://badgen.net/badge/JIRA/GEOT-7615/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7615) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
see also: https://github.com/geoserver/geoserver/pull/7767
=> [GEOT-7615] Update Jackson 2 libs from 2.17.1 to 2.17.2

modules/unsupported/graticules/pom.xml, modules/unsupported/graticules/src/main/java/org/geotools/data/graticule/GraticuleDataStore.java, modules/unsupported/graticules/src/main/java/org/geotools/data/graticule/GraticuleDataStoreFactory.java, modules/unsupported/graticules/src/main/java/org/geotools/data/graticule/GraticuleFeatureReader.java, modules/unsupported/graticules/src/main/java/org/geotools/data/graticule/GraticuleFeatureSource.java, modules/unsupported/graticules/src/main/java/org/geotools/data/graticule/gridsupport/LineFeatureBuilder.java, modules/unsupported/graticules/src/main/java/org/geotools/process/vector/GraticuleLabelPointProcess.java, modules/unsupported/graticules/src/main/resources/META-INF/services/org.geotools.api.data.DataStoreFactorySpi, modules/unsupported/graticules/src/main/resources/META-INF/services/org.geotools.process.ProcessFactory, modules/unsupported/graticules/src/main/resources/META-INF/services/org.geotools.process.vector.VectorProcess, modules/unsupported/graticules/src/test/java/org/geotools/data/graticule/GraticuleDataStoreFactoryTest.java, modules/unsupported/graticules/src/test/java/org/geotools/data/graticule/GraticuleDataStoreTest.java, modules/unsupported/graticules/src/test/java/org/geotools/data/graticule/GraticuleFeatureReaderTest.java, modules/unsupported/graticules/src/test/java/org/geotools/data/graticule/GraticuleFeatureSourceTest.java, modules/unsupported/graticules/src/test/java/org/geotools/process/vector/GraticuleLabelPointProcessTest.java, modules/unsupported/graticules/src/test/java/org/geotools/process/vector/GraticuleLabelTestSupport.java, modules/unsupported/pom.xml
[![GEOT-7618](https://badgen.net/badge/JIRA/GEOT-7618/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7618) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7618] Move the geotools elements of the graticule module to GeoTools

pom.xml
[![GEOT-7622](https://badgen.net/badge/JIRA/GEOT-7622/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7622) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7622] Upgrade guava from 33.2.0 to 33.2.1

pom.xml
[![GEOT-7624](https://badgen.net/badge/JIRA/GEOT-7624/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7624) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This is just a test dependency upgrade.
=> [GEOT-7624] Upgrade junit from 4.13.1 to 4.13.2

pom.xml
[![GEOT-7623](https://badgen.net/badge/JIRA/GEOT-7623/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7623) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7623] Upgrade commons-lang3 from 3.14.0 to 3.15.0

.github/workflows/mssql_online.yml
=> [Backport 30.x] Pinning MSSQL 2022 tag to avoid changes in tools directories. 

.github/workflows/mssql_online.yml
=> [Backport 31.x] Pinning MSSQL 2019 as well

.github/workflows/mssql_online.yml
=> [Backport 30.x] Pinning MSSQL 2019 as well

modules/library/api/src/main/java/org/geotools/api/referencing/operation/TransformException.java, modules/library/main/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java, modules/library/main/src/test/java/org/geotools/renderer/crs/ProjectionHandlerTest.java, modules/library/referencing/src/main/java/org/geotools/referencing/EnvelopeReprojector.java, modules/library/referencing/src/main/java/org/geotools/referencing/operation/transform/WarpAdapter.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java
[![GEOS-7550](https://badgen.net/badge/JIRA/GEOS-7550/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-7550) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport from main (landed there in late march 2024), needed to fix build issues in GeoServer 2.24.x.
Must be merged with https://github.com/geoserver/geoserver/pull/7807
=> [30.x backport] [GEOS-7550] Try harder to reproject envelopes with projections having a complex valid area

modules/library/api/src/main/java/org/geotools/api/referencing/operation/TransformException.java, modules/library/main/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java, modules/library/main/src/test/java/org/geotools/renderer/crs/ProjectionHandlerTest.java, modules/library/referencing/src/main/java/org/geotools/referencing/EnvelopeReprojector.java, modules/library/referencing/src/main/java/org/geotools/referencing/operation/transform/WarpAdapter.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java
[![GEOS-7550](https://badgen.net/badge/JIRA/GEOS-7550/0052CC)](https://osgeo-org.atlassian.net/browse/GEOS-7550) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport of https://github.com/geotools/geotools/pull/4861
Must be merged with https://github.com/geoserver/geoserver/pull/7810
=> [Backport 31.x] [GEOS-7550] Try harder to reproject envelopes with projections having a complex valid area

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java
[![GEOT-7628](https://badgen.net/badge/JIRA/GEOT-7628/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7628) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4867
=> [Backport 30.x] [GEOT-7628] Regression in JDBC optimization of unique visitor with sorting

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java
[![GEOT-7628](https://badgen.net/badge/JIRA/GEOT-7628/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7628) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #4867
=> [Backport 31.x] [GEOT-7628] Regression in JDBC optimization of unique visitor with sorting

pom.xml
This is just a test dependency upgrade. The property name was changed to match GeoServer and GeoWebCache.
=> Upgrade mockito from 5.6.0 to 5.12.0

pom.xml
This is just a test dependency upgrade.
=> Upgrade easymock from 5.3.0 to 5.4.0

modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-7528](https://badgen.net/badge/JIRA/GEOT-7528/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7528) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
this only adds the testcase from the issue as the problem appears to have been fixed with [GEOT-7537](https://osgeo-org.atlassian.net/browse/GEOT-7537) / https://github.com/geotools/geotools/pull/4793
=> [GEOT-7528] GeoPackage: Timestamp is not written correctly

modules/extension/mbstyle/pom.xml, modules/extension/xsd/xsd-csw/pom.xml, modules/extension/xsd/xsd-gml2/pom.xml, modules/extension/xsd/xsd-gml3/pom.xml, modules/extension/xsd/xsd-wfs/pom.xml, modules/extension/xsd/xsd-wmts/pom.xml, modules/extension/ysld/pom.xml, modules/library/http/pom.xml, modules/library/main/pom.xml, modules/library/render/pom.xml, modules/library/sample-data/pom.xml, modules/library/xml/pom.xml, modules/plugin/coverage-multidim/netcdf/pom.xml, modules/plugin/geopkg/pom.xml, modules/plugin/imagemosaic/pom.xml, modules/plugin/mongodb/pom.xml, modules/unsupported/css/pom.xml, modules/unsupported/elasticsearch/pom.xml, modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFilterTest.java, modules/unsupported/mbtiles/pom.xml, modules/unsupported/stac-store/pom.xml, modules/unsupported/vector-mosaic/pom.xml, modules/unsupported/vector-mosaic/src/test/java/org/geotools/vectormosaic/VectorMosaicStoreFactoryTest.java, modules/unsupported/wfs-ng/pom.xml, pom.xml
This is a test dependency upgrade.
This PR adds the hamcrest 3.0 dependency to the root pom.xml and removes all hamcrest-core, hamcrest-library, hamcrest-integration and hamcrest-all dependencies. The version is set to 3.0 for hamcrest-core and hamcrest-library in case there is another transitive dependency on it (these are empty jar files). hamcrest-integration and hamcrest-all has no version beyond 1.3. The sample-data module needs a provided scope on hamcrest.
Some code changes were required for deprecated API.
=> Upgrade hamcrest from 1.3 to 3.0

docs/user/library/coverage/mosaic.rst, docs/user/welcome/upgrade.rst, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java
[![GEOT-7629](https://badgen.net/badge/JIRA/GEOT-7629/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7629) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7629] document org.geotools.gce.imagemosaic.sampleimage.allowlist

docs/developer/procedures/add.rst, modules/extension/app-schema/app-schema-data/README.md, modules/extension/app-schema/app-schema-packages/README.md
minor doc change changing from webdav to nexus repo.
non functional documentation change.
=> update third-party-jar instructions

.github/workflows/assembly.yml, .github/workflows/db2_online.yml, .github/workflows/elasticsearch_online.yml, .github/workflows/geopkg_online.yml, .github/workflows/hana_online.yml, .github/workflows/informix.yml, .github/workflows/integration.yml, .github/workflows/linux_gdal.yml, .github/workflows/linux_jdk11.yml, .github/workflows/linux_jdk17.yml, .github/workflows/linux_jdk21.yml, .github/workflows/macos.yml, .github/workflows/mssql_online.yml, .github/workflows/mysql_online.yml, .github/workflows/oracle_online.yml, .github/workflows/postgis_online.yml, .github/workflows/qa.yml, .github/workflows/windows.yml
This PR backports the workflow updates of #4891 to 31.x
=> Workflow updates for 31.x

.github/workflows/assembly.yml, .github/workflows/db2_online.yml, .github/workflows/elasticsearch_online.yml, .github/workflows/geopkg_online.yml, .github/workflows/hana_online.yml, .github/workflows/informix.yml, .github/workflows/integration.yml, .github/workflows/linux_gdal.yml, .github/workflows/linux_jdk11.yml, .github/workflows/linux_jdk17.yml, .github/workflows/macos.yml, .github/workflows/mssql_online.yml, .github/workflows/mysql_online.yml, .github/workflows/oracle_online.yml, .github/workflows/postgis_online.yml, .github/workflows/qa.yml, .github/workflows/windows.yml
This PR backports the workflow updates of #4891 to 30.x
=> Workflow updates for 30.x

modules/unsupported/process-geometry/src/main/java/org/geotools/process/geometry/PolyLabeller.java, modules/unsupported/process-geometry/src/main/java/org/geotools/process/geometry/PolygonLabelFunction.java, modules/unsupported/process-geometry/src/main/java/org/geotools/process/geometry/PolygonLabelProcess.java, modules/unsupported/process-geometry/src/test/java/org/geotools/process/geometry/PolyLabellerTest.java
[![GEOT-7640](https://badgen.net/badge/JIRA/GEOT-7640/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7640) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket for rationale and some comparison screenshots.
Quick visual comparison, before the changes, with a tolerance of 0.1 (too small to get good results, but also, unintuitive IMHO):
And here is with the changes in this PR, also no need to guess a good tolerance:
=> [GEOT-7640] Improve the polygon label function for rectangular geometries, and automatically compute a sane tolerance

modules/extension/brewer/pom.xml, modules/extension/wmts/pom.xml, modules/extension/xsd/xsd-ows/pom.xml, modules/extension/ysld/pom.xml, modules/library/api/pom.xml, modules/library/coverage/pom.xml, modules/library/main/pom.xml, modules/library/metadata/pom.xml, modules/library/referencing/pom.xml, modules/library/render/pom.xml, modules/library/xml/pom.xml, modules/ogc/net.opengis.wps/pom.xml, modules/plugin/arcgrid/pom.xml, modules/plugin/coverage-multidim/coverage-api/pom.xml, modules/plugin/coverage-multidim/netcdf/pom.xml, modules/plugin/geotiff/pom.xml, modules/plugin/imagemosaic/pom.xml, modules/plugin/jdbc/jdbc-hana/pom.xml, modules/unsupported/elasticsearch/pom.xml, modules/unsupported/process-feature/pom.xml, modules/unsupported/wps/pom.xml
[![GEOT-7642](https://badgen.net/badge/JIRA/GEOT-7642/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7642) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Initially added `javax.measure:unit-api` dependency to `gt-api` and `gt-metadata` that were causing the problem for me, also added the `javax.measure:unit-api` dependency to any other modules that have code importing any from `javax.measure.*`
=> [GEOT-7642] some modules rely on transitive version of units-api

pom.xml
[![GEOT-7648](https://badgen.net/badge/JIRA/GEOT-7648/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7648) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7648] Update to ImageIO-Ext 1.14.13

modules/plugin/coverage-multidim/coverage-api/pom.xml, modules/plugin/coverage-multidim/coverage-api/src/main/java/org/geotools/coverage/io/catalog/CoverageSlicesCatalog.java, modules/plugin/coverage-multidim/coverage-api/src/test/java/org/geotools/coverage/io/catalog/CoverageSlicesCatalogTest.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/AncillaryFileManager.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReader.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/imageio/netcdf/NetCDFImageReaderTest.java, modules/plugin/coverage-multidim/netcdf/src/test/resources/org/geotools/coverage/io/netcdf/test-data/DUMMYGOME2_IRT.xml
[![GEOT-7652](https://badgen.net/badge/JIRA/GEOT-7652/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7652) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket for details.
=> [GEOT-7652] Avoid typename listing when NetCDF indexer file points to a single coverage

modules/library/main/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope.java, modules/library/main/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java, modules/library/main/src/main/java/org/geotools/renderer/crs/WrappingProjectionHandler.java, modules/library/referencing/src/main/java/org/geotools/referencing/crs/AbstractCRS.java, modules/library/referencing/src/main/java/org/geotools/referencing/crs/AbstractDerivedCRS.java, modules/library/referencing/src/main/java/org/geotools/referencing/crs/AbstractSingleCRS.java, modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultCompoundCRS.java, modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultDerivedCRS.java, modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultEngineeringCRS.java, modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultGeocentricCRS.java, modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultGeographicCRS.java, modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultImageCRS.java, modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultProjectedCRS.java, modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultTemporalCRS.java, modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultVerticalCRS.java, modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java
Two distinct fixes, with parts that are not necessarily unique to points, but show up prominently when rendering millions of points in a single map: 
* https://osgeo-org.atlassian.net/browse/GEOT-7653
* https://osgeo-org.atlassian.net/browse/GEOT-7654
=>  Speed up reprojected rendering of large amounts of points

docs/src/main/java/org/geotools/tutorial/crs/CRSLab.java, docs/user/library/jts/geometry.rst, docs/user/library/main/feature.rst, docs/user/tutorial/datastore/optimisation.rst, docs/user/welcome/upgrade.rst, modules/extension/xsd/xsd-kml/src/main/resources/org/geotools/kml/kml21.xsd, modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/BandMerge.java, modules/library/main/src/main/java/org/geotools/feature/simple/SimpleFeatureTypeBuilder.java, modules/library/main/src/test/java/org/geotools/geometry/jts/JTSTest.java, modules/plugin/property/src/test/java/org/geotools/data/property/PropertyDataStoreTest.java, modules/unsupported/ogr/ogr-core/src/main/java/org/geotools/data/ogr/FeatureMapper.java, modules/unsupported/ogr/ogr-core/src/main/java/org/geotools/data/ogr/OGRDataStore.java
[![GEOT-7661](https://badgen.net/badge/JIRA/GEOT-7661/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7661) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7661] Fix spelling of geoemtry (geometry) in several places

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AbstractMappingFeatureIterator.java
We are seeing a lot of GeoServer build failures due to app-schema integration tests, in particular LocalResolveTest#testResolveTimeOut:
```
2024-10-02T15:44:18.1173215Z 15:44:18,115 [ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.703 s <<< FAILURE! - in org.geoserver.test.LocalResolveTest
2024-10-02T15:44:18.1214470Z 15:44:18,121 [ERROR] testResolveTimeOut(org.geoserver.test.LocalResolveTest)  Time elapsed: 0.036 s  <<< FAILURE!
2024-10-02T15:44:18.1219724Z java.lang.AssertionError: expected:<0> but was:<1>
2024-10-02T15:44:18.1224544Z 	at org.geoserver.test.LocalResolveTest.testResolveTimeOut(LocalResolveTest.java:123)
2024-10-02T15:44:18.1236115Z 
```
[The test is assuming that setting the timeout to zero will ensure no resolve …
=> Trying to appease GeoServer resolve timeout build failures

modules/extension/wmts/src/main/java/org/geotools/ows/wmts/model/WMTSCapabilities.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/client/WMTSUndefinedTileMatrixSetTest.java, modules/extension/wmts/src/test/resources/test-data/undefinedTileMatrixSet.xml
[![GEOT-7541](https://badgen.net/badge/JIRA/GEOT-7541/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7541) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
When cascading WMTS capabilities specifies a TileMatrixSet that doesn't exist GeoTools throws a ConcurrentModificationException.
=> [GEOT-7541] When cascading WMTS capabilities specifies a TileMatrixSet that doesn't exist GeoTools throws a ConcurrentModificationException

modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/PointStackerProcess.java, modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/PointStackerProcessTest.java
[![GEOT-7665](https://badgen.net/badge/JIRA/GEOT-7665/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7665) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7665] PointStacker envBBOX has wrong value

modules/extension/xsd/xsd-sld/src/main/java/org/geotools/sld/bindings/SLDGraphicBinding.java, modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDGraphicBindingTest.java, modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDMockData.java
[![GEOT-7666](https://badgen.net/badge/JIRA/GEOT-7666/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7666) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7666] Parsing empty Rotation style element throws a ClassCastException

modules/extension/xsd/xsd-sld/src/main/java/org/geotools/sld/bindings/SLDGraphicBinding.java, modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDGraphicBindingTest.java, modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/bindings/SLDMockData.java
[![GEOT-7666](https://badgen.net/badge/JIRA/GEOT-7666/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7666) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
* [GEOT-7666] Parsing empty Rotation style element throws a ClassCastException
* [GEOT-7666] Parsing empty Rotation style element throws a ClassCastException
---------
=> [31.x backport] [GEOT-7666] Parsing empty Rotation style element throws a ClassCastException

pom.xml
=> bump commons-io:commons-io to 2.17.0

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCDataStoreTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISJsonOnlineTest.java
[![GEOT-7667](https://badgen.net/badge/JIRA/GEOT-7667/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7667) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7667] JDBCDataStore getAggregateValue is not JSONPointer aware when splitting the filters

modules/unsupported/stac-store/pom.xml, release/pom.xml
[![GEOT-7664](https://badgen.net/badge/JIRA/GEOT-7664/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7664) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7664] Use CQL2 related module names fro release and stac-store dependencies

modules/unsupported/elasticsearch/pom.xml, pom.xml, release/src/it/log4j/pom.xml
[![GEOT-7677](https://badgen.net/badge/JIRA/GEOT-7677/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7677) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR upgrades the log4j and slf4j dependencies to their current versions and is related to GeoServer's Wicket 9 upgrade. Unnecessary version properties were removed from child POMs.
See https://osgeo-org.atlassian.net/browse/GEOS-11590 for more information.
=> [GEOT-7677] Upgrade log4j to 2.24.1 and slf4j to 2.0.16

docs/user/library/cql/cql.rst, docs/user/unsupported/cql2.rst, docs/user/unsupported/index.rst
Adding some specification reference, pointing to the many examples in it and in the repositories, and showing some actual code usage.
=> Adding some CQL2 documentation

modules/library/main/src/main/java/org/geotools/filter/function/JsonArrayContainsFunction.java
Reverts geotools/geotools#4989
=> Revert "[Backport 32.x] Avoiding class not found exception in Quickstart"

modules/library/main/src/main/java/org/geotools/filter/function/JsonArrayContainsFunction.java
Reverts geotools/geotools#4988
=> Revert "Avoiding class not found exception in Quickstart"

release/pom.xml, release/src/assembly/binaryDistDependencies.xml
[![GEOT-7685](https://badgen.net/badge/JIRA/GEOT-7685/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7685) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This was noticed by @petersmythe during 32.1 release (see also https://github.com/geotools/geotools/pull/4988)
=> [GEOT-7685] Include cql2 in binaryDistDependencies.xml for inclusion of jackson jars

modules/plugin/jdbc/jdbc-mysql/pom.xml, pom.xml
[![GEOT-7694](https://badgen.net/badge/JIRA/GEOT-7694/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7694) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7694] Update MySQL driver to 9.1.0

modules/plugin/jdbc/jdbc-mysql/pom.xml, pom.xml
[![GEOT-7694](https://badgen.net/badge/JIRA/GEOT-7694/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7694) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport #5016
=> [Backport 31.x] [GEOT-7694] Update MySQL driver to 9.1.0

modules/library/http/pom.xml, modules/library/http/src/test/java/org/geotools/http/SimpleHttpClientTest.java, modules/library/xml/pom.xml, modules/library/xml/src/test/java/org/geotools/xml/resolver/SchemaCacheTest.java, modules/plugin/http-commons/pom.xml, modules/plugin/http-commons/src/test/java/org/geotools/http/commons/MultithreadedHttpClientTest.java, modules/unsupported/stac-store/pom.xml, modules/unsupported/stac-store/src/test/java/org/geotools/stac/store/STACDataStoreFactoryTest.java, pom.xml
Upgrade the wiremock dependency to the current version. GeoTools uses the standalone JAR which includes all of its dependencies under a separate package so it isn't impacted by wiremock's Tomcat 11 and Jakarta EE dependencies.
Some of the tests were incorrectly registering the stubs and had to be updated for the new version. All of the tests were also updated to use the class rule which improves performance when the test classes contain a lot of tests.
=> Upgrade wiremock from 2.35.1 to 3.10.0

pom.xml
This dependency upgrade fixes a critical bug that can cause getLogger to return null.
=> Updated log4j from 2.24.1 to 2.24.3

pom.xml
=> Upgrade Jackson from 2.17.2 to 2.18.2

modules/unsupported/arcgis-rest/pom.xml, modules/unsupported/arcgis-rest/src/main/java/org/geotools/data/arcgisrest/ArcGISRestDataStore.java, modules/unsupported/arcgis-rest/src/main/java/org/geotools/data/arcgisrest/ArcGISRestFeatureSource.java, modules/unsupported/arcgis-rest/src/test/java/org/geotools/data/arcgisrest/ArcGISRestDataStoreTest.java
[![GEOT-7704](https://badgen.net/badge/JIRA/GEOT-7704/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7704) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
The ArcGIS ReST API Datastore uses the old, EOL-ed commons-httpclient:commons-httpclient library; this has various problems in handling secure connections and it should be replaced/refactored to use either plain Java code or  org.apache.httpcomponents:httpclient used in other GeoTools modules.
this will resolve https://github.com/geotools/geotools/security/dependabot/73 
=> [GEOT-7704] Replace commons-httpclient with httpcomponents:httpclient

modules/extension/app-schema/app-schema/pom.xml
Updating this test dependency
should resolve https://github.com/geotools/geotools/security/dependabot/77
=> Bump org.eclipse.jetty:jetty-server from 9.4.55.v20240627 to 9.4.57.v20241219 in /modules/extension/app-schema/app-schema

modules/library/metadata/src/main/java/org/geotools/util/logging/LogbackLogger.java, modules/library/metadata/src/test/java/org/geotools/util/logging/LoggingTest.java, modules/unsupported/elasticsearch/pom.xml, pom.xml, release/src/it/log4j/pom.xml, release/src/it/logback/pom.xml
[![GEOT-7711](https://badgen.net/badge/JIRA/GEOT-7711/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7711) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
An update of slf4j 2.x introduced an incompatibility with logback which was not covered by test cases.
* https://github.com/geotools/geotools/pull/4979
This was detected by https://github.com/geotools/geotools/pull/5062 which introduced a test case.
=> [GEOT-7711] 31.x upgrade log4j to 2.24.1, slf4j to 2.0.16, and logback 1.5.14

pom.xml
[![GEOT-7712](https://badgen.net/badge/JIRA/GEOT-7712/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7712) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7712] Update JAI-Ext to 1.1.28

pom.xml
[![GEOT-7712](https://badgen.net/badge/JIRA/GEOT-7712/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7712) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [Backport 31.x] [GEOT-7712] Update JAI-Ext to 1.1.28

pom.xml
=> Upgrade PostgreSQL driver from 42.7.3 to 42.7.5

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCDataStoreOnlineTest.java, modules/plugin/jdbc/jdbc-informix/src/test/java/org/geotools/data/informix/InformixDataStoreOnlineTest.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSContentDataAccess.java, pom.xml
This is just a regular dependency upgrade. There are some minor code changes to refactor using newly deprecated API.
=> Upgrade commons-lang3 from 3.15.0 to 3.17.0

pom.xml
=> Upgrade guava from 33.2.1 to 33.4.0

modules/extension/graph/src/main/java/org/geotools/graph/io/standard/SerializedReaderWriter.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java, pom.xml
This is just a regular dependency upgrade. There are some minor code changes to refactor using newly deprecated API.
=> Upgrade commons-io from 2.17.0 to 2.18.0

pom.xml
This is just a test dependency upgrade.
=> Upgrade mockito from 5.12.0 to 5.15.2

pom.xml
This is just a test dependency upgrade.  
=> Upgrade wiremock from 3.10.0 to 3.11.0

pom.xml
=> Upgrade commons-text from 1.12.0 to 1.13.0

modules/library/main/pom.xml
=> Upgrade re2j from 1.6 to 1.8

modules/library/metadata/src/test/java/org/geotools/util/factory/GeoToolsTest.java, pom.xml
=> Upgrade commons-logging from 1.2 to 1.3.5

pom.xml
=> Upgrade commons-beanutils from 1.9.4 to 1.10.1

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleNClobConverterFactory.java, modules/plugin/jdbc/jdbc-oracle/src/main/resources/META-INF/services/org.geotools.util.ConverterFactory, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleLobOnlineTest.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleLobTestSetup.java
[![GEOT-7721](https://badgen.net/badge/JIRA/GEOT-7721/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7721) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7721] Oracle datastore does not handle NCLOB

modules/plugin/jdbc/jdbc-oracle/pom.xml, pom.xml
[![GEOT-7723](https://badgen.net/badge/JIRA/GEOT-7723/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7723) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7723] Upgrade Oracle JDBC driver (ojdbc) from 8 to 11

modules/unsupported/geojson/pom.xml, modules/unsupported/geojson/src/main/java/org/geotools/geojson/GeoJSONUtil.java, modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/ComplexPropertyHandler.java, modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/FeatureHandler.java, modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/FeatureTypeHandler.java, modules/unsupported/geojson/src/test/java/org/geotools/geojson/ComplexGeoJSONPropertiesTest.java, modules/unsupported/geojson/src/test/java/org/geotools/geojson/ComplexPropertyHandlerTest.java
[![GEOT-5158](https://badgen.net/badge/JIRA/GEOT-5158/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-5158) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This PR allows JSON Objects as a Map.class binding, and JSON Arrays as a List.class binding inside a SimpleFeature.
The existing schema discovery and type checking has been extended to work with Map and List, and included explicit compatibility with "properties which are geometry objects".
With that, it will also solve GEOT-5158.
It has previously been proposed and is a true copy of this PR: …
=> [GEOT-5158] Support of complex props in GeoJSON

pom.xml
[![GEOT-7734](https://badgen.net/badge/JIRA/GEOT-7734/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7734) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Dependency update
=> [GEOT-7734] Update to jai-ext 1.1.31

pom.xml
[![GEOT-7735](https://badgen.net/badge/JIRA/GEOT-7735/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7735) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Dependency update
=> [GEOT-7735] Upgrade ImageIO-EXT to 1.4.15

modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONReader.java, modules/unsupported/geojson-core/src/test/java/org/geotools/data/geojson/GeoJSONReaderTest.java, modules/unsupported/geojson-core/src/test/resources/org/geotools/data/geojson/test-data/planetary_stac.json, modules/unsupported/stac-store/src/main/java/org/geotools/stac/client/STACClient.java
[![GEOT-7738](https://badgen.net/badge/JIRA/GEOT-7738/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7738) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
STAC assets are kept in UserData, which wasn't copied in call to DataUtilities.reType. In addition it seems redundant when the object keeps a SimpleFeatureBuilder.
The change in STACClient is to avoid some dead code.
=> [GEOT-7738] STAC Client misses assets from Microsoft Planetarycomputer calls

docs/user/unsupported/geoparquet.rst, docs/user/unsupported/index.rst, modules/unsupported/geoparquet/pom.xml, modules/unsupported/geoparquet/src/main/java/org/geotools/data/duckdb/AbstractDuckDBDataStoreFactory.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/duckdb/DuckDBDialect.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/duckdb/datasource/DuckdbConnectionFactory.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/duckdb/datasource/DuckdbDataSource.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetDataStoreFactory.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetDatabaseUtils.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetDialect.java, modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetDataStoreFactoryTest.java, modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetDatabaseUtilsTest.java, pom.xml
Create DuckdbDataSource and DuckdbConnectionFactory classes that leverage DuckDB's
native connection duplication feature for improved performance:
- DuckdbDataSource extends DBCP's BasicDataSource with DuckDB-specific optimizations
- DuckdbConnectionFactory maintains a single sentinel connection that's duplicated
- Database initialization (extensions loading) happens once per data source
- Uses per-datastore-parameters-set named memory databases for isolation
- Reduces connection overhead by reusing the same underlying database
- Improves concurrency with better connection handling
The implementation also includes comprehensive documentation explaining the
connection duplication approach and its benefits for the GeoParquet module.
=> Implement specialized DuckDB connection management for GeoParquet

.github/workflows/assembly.yml, .github/workflows/backport.yml, .github/workflows/cql2_online.yml, .github/workflows/elasticsearch_online.yml, .github/workflows/geopkg_online.yml, .github/workflows/linux_jdk21.yml, .github/workflows/qa.yml
Ubuntu 20.04 is no longer supported, as noted in https://github.com/actions/runner-images/issues/11101
GDAL Linux builds are left as-is as no apt package for libgdal-java is available for newer Ubuntu versions
=> [CI] Update mos Linux runner OS in workflows

.github/workflows/assembly.yml, .github/workflows/backport.yml, .github/workflows/elasticsearch_online.yml, .github/workflows/geopkg_online.yml, .github/workflows/linux_jdk21.yml, .github/workflows/qa.yml
=> [Backport 32.x] [CI] Update most Linux runner OS in workflows

docs/user/unsupported/geoparquet.rst, docs/user/unsupported/index.rst, modules/unsupported/geoparquet/pom.xml, modules/unsupported/geoparquet/src/main/java/org/geotools/data/duckdb/AbstractDuckDBDataStoreFactory.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/duckdb/DuckDBDialect.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/duckdb/datasource/DuckdbConnectionFactory.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/duckdb/datasource/DuckdbDataSource.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetDataStoreFactory.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetDatabaseUtils.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetDialect.java, modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetDataStoreFactoryTest.java, modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetDatabaseUtilsTest.java
Backport #5151
**Authored by: @groldan**
=> [Backport 33.x] Implement specialized DuckDB connection management for GeoParquet

docs/user/unsupported/geoparquet.rst, modules/unsupported/geoparquet/README.md, modules/unsupported/geoparquet/src/main/java/org/geotools/data/duckdb/datasource/DuckdbDataSource.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetConfig.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetDataStoreFactory.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetDialect.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetFilterToSQL.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/GeoParquetViewManager.java, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/HivePartitionResolver.java, modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetDataStoreFactoryTest.java, modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetDataStoreTest.java, modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetLocalFileTest.java, modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetTestSupport.java, modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/GeoParquetTestSupportTest.java, modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/HivePartitionResolverTest.java, modules/unsupported/geoparquet/src/test/resources/org/geotools/data/geoparquet/setup_test_data.sql
[![GEOT-7747](https://badgen.net/badge/JIRA/GEOT-7747/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7747) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Add support for Hive-partitioned datasets (directory structures with `key=value` patterns), enabling:
- Automatic detection of partitioned datasets in local/remote files
- Configurable partition depth via `max_hive_depth` parameter
- Each distinct partition available as a separate feature type
- Support for time-series data with hierarchical partitioning
- Optimized partition handling for datasets like Overture Maps …
=> [GEOT-7747] Add Hive partitioning support to GeoParquet DataStore

modules/extension/xsd/xsd-wfs/src/main/java/org/geotools/wfs/v1_1/PropertyTypeBinding_1_1.java, modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v1_1/WFSEncodingTest.java
[![GEOT-7720](https://badgen.net/badge/JIRA/GEOT-7720/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7720) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7720] Сorrect determination of the number of decimal places in coordinates

pom.xml
=> Upgrade duckdb_jdbc:1.2.0 -> 1.2.2.0

modules/extension/wms/src/main/java/org/geotools/ows/wms/Layer.java, modules/extension/wms/src/main/java/org/geotools/ows/wms/map/WMSCoverageReader.java, modules/extension/wms/src/test/java/org/geotools/ows/wms/map/WMSCoverageReaderTest.java
[![GEOT-7749](https://badgen.net/badge/JIRA/GEOT-7749/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7749) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
When making a cascading call to an external WMS ensure the vendor parameters are included in the request.
The vendor parameters are treated the same as other parameters and need to have protected characters encoded
ie 
Something like 
CQL_FILTER=LAND_KM > 200000
should be written
CQL_FILTER=LAND_KM%20%3E%20200000
Commas do not need to be encoded
CSV=5,10,20,5,1,3,1,,,,1
List=l1,l2,l3,l4,l5
Spaces need to be escaped …
=> [GEOT-7749] Add support for vendor parameters in WMSLayer

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/EnumMapper.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/EnumMapping.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureReader.java, modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java, modules/plugin/geopkg/src/main/java/org/geotools/geopkg/JSONArrayIO.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgEnumTest.java
[![GEOT-7715](https://badgen.net/badge/JIRA/GEOT-7715/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7715) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport https://github.com/geotools/geotools/pull/5073
Authored by: @axl8713
=> [Backport 33.x] [GEOT-7715] Support for GeoPackage data column constraint enums with string keys

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/EnumMapper.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/EnumMapping.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureReader.java, modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java, modules/plugin/geopkg/src/main/java/org/geotools/geopkg/JSONArrayIO.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgEnumTest.java
[![GEOT-7715](https://badgen.net/badge/JIRA/GEOT-7715/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7715) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport https://github.com/geotools/geotools/pull/5073
Authored by: @axl8713
=> [Backport 32.x] [GEOT-7715] Support for GeoPackage data column constraint enums with string keys

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/EnumMapper.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/EnumMapping.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureReader.java, modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java, modules/plugin/geopkg/src/main/java/org/geotools/geopkg/JSONArrayIO.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgEnumTest.java
[![GEOT-7715](https://badgen.net/badge/JIRA/GEOT-7715/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7715) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport https://github.com/geotools/geotools/pull/5073
Authored by: @axl8713
=> [Backport 31.x] [GEOT-7715] Support for GeoPackage data column constraint enums with string keys

.github/workflows/assembly.yml, .github/workflows/backport.yml, .github/workflows/elasticsearch_online.yml, .github/workflows/geopkg_online.yml, .github/workflows/linux_jdk11.yml, .github/workflows/linux_jdk17.yml, .github/workflows/linux_jdk21.yml, .github/workflows/oracle_online.yml, .github/workflows/qa.yml
=> Github actions 31.x: switch to Ubuntu 22.04 as builds won't run any longer on 20.04

docs/developer/communication.rst, docs/developer/procedures/build_server.rst, docs/developer/procedures/release.rst, docs/user/build/maven/snapshots.rst, docs/user/welcome/support.rst
[![GEOT-7756](https://badgen.net/badge/JIRA/GEOT-7756/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7756) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
This is a non functional documentation change, fixes some unintended markdown link formatting also.
=> [GEOT-7756] Communication update address outdated http, irc, project and corporate links

.github/workflows/mssql_online.yml, build/ci/mssql/setup-mssql.sh, docs/developer/conventions/test/online.rst
Since 2025 is now available, add that and drop 2019 from the build matrix
=> [CI] Update SQL Server build matrix

pom.xml
fixes access to a database behind a pgbouncer alias which doesn't match the real database name, cf pgjdbc/pgjdbc#3565
more analysis in [GEOS-11849](https://osgeo-org.atlassian.net/browse/GEOS-11849)
see https://github.com/pgjdbc/pgjdbc/releases/tag/REL42.7.6 for other changes in this release. Been working fine with geoserver 2.27.1. would welcome a backport to branches 33 & 32 since those depend on 42.7.5, which has the regression introduced in 42.7.4.
=> upgrade postgresql to 42.7.6

modules/unsupported/mbtiles/pom.xml, pom.xml
This PR is just a regular dependency upgrade.
=> Upgrade guava from 33.4.0 to 33.4.8

pom.xml
This PR is just a regular dependency upgrade.
=> Upgrade snakeyaml from 2.3 to 2.4

modules/unsupported/geojson-core/src/main/java/org/geotools/data/geojson/GeoJSONReader.java, pom.xml
This PR is just a regular dependency upgrade.
=> Upgrade jackson from 2.18.2 to 2.19.0

bom/pom.xml
Missed it at [GEOT-7759](https://github.com/geotools/geotools/pull/5196), since in GeoServer it's only used by the app-schema-online-test profile.
=> Add org.geotools:gt-solr:tests to gt-bom

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
[![GEOT-7767](https://badgen.net/badge/JIRA/GEOT-7767/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7767) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
When generating geopkg with java.util.UUID type, for example from geoserver, the export fails with exception: 
```
No mapping for java.util.UUID
java.io.IOException: Error occurred creating table
at org.geotools.jdbc.JDBCDataStore.createSchema(JDBCDataStore.java:743)
at org.geotools.geopkg.GeoPackage.create(GeoPackage.java:824)
at org.geotools.geopkg.GeoPackage.add(GeoPackage.java:882)
....
```
This PR will add mapping of …
=> [GEOT-7767] Java UUID type support to geopkg dialect

modules/library/main/src/main/java/org/geotools/feature/visitor/GroupByVisitor.java, modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java, modules/library/render/src/test/java/org/geotools/renderer/lite/OpaqueTransformationFunction.java, modules/library/render/src/test/java/org/geotools/renderer/lite/RenderingTransformationTest.java, modules/library/render/src/test/resources/META-INF/services/org.geotools.api.filter.expression.Function, modules/library/render/src/test/resources/META-INF/services/org.geotools.util.ConverterFactory, modules/library/render/src/test/resources/org/geotools/renderer/lite/test-data/opaqueRenderingTransformation.sld, modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/AggregateProcess.java, modules/unsupported/process-feature/src/main/resources/META-INF/services/org.geotools.util.ConverterFactory, modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/AggregateProcessTest.java, modules/unsupported/process/src/main/java/org/geotools/process/function/ProcessFunction.java
[![GEOT-7782](https://badgen.net/badge/JIRA/GEOT-7782/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7782) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
See ticket for details.
A change in a XStream mapped bean breaks the downstream build, this PR contains the fix:
https://github.com/geoserver/geoserver/pull/8630
=> [GEOT-7782] Allow usage of grouping aggregation as a rendering transformation

docs/user/unsupported/geoparquet.rst, modules/unsupported/geoparquet/src/main/java/org/geotools/data/geoparquet/HivePartitionResolver.java, modules/unsupported/geoparquet/src/test/java/org/geotools/data/geoparquet/HivePartitionResolverTest.java
=> Fix Hive partitioning with query parameters in the uri

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicFormat.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerRequest.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java
[![GEOT-7797](https://badgen.net/badge/JIRA/GEOT-7797/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7797) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> [GEOT-7797]: Skipping duplicates in imageMosaic granules loading

modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/S3Connector.java
Note: existing (online) test was broken, this fixes it.
[![GEOT-7803](https://badgen.net/badge/JIRA/GEOT-7803/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7803) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
=> GEOT-7803 fix custom server region

modules/unsupported/flatgeobuf/pom.xml, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureCollectionConversions.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FeatureConversions.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatBuffers.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatGeobufFeatureWriter.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/HeaderMetaUtil.java, modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/ReadHitsIterable.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FeatureCollectionConversionsTest.java, modules/unsupported/flatgeobuf/src/test/java/org/geotools/data/flatgeobuf/FlatGeobufDataStoreTest.java
This fixes issues with reading large FlatGeobuf. See https://github.com/flatgeobuf/flatgeobuf/issues/453 for details.
=> Upgrade org.wololo.flatgeobuf to 3.28.2 and fix int overflow issue + write geometryType

modules/extension/transform/src/main/java/org/geotools/data/transform/Definition.java, modules/library/main/src/main/java/org/geotools/feature/AttributeTypeBuilder.java, modules/library/main/src/main/java/org/geotools/feature/FeatureTypes.java, modules/library/main/src/main/java/org/geotools/feature/simple/SimpleFeatureTypeBuilder.java, modules/library/main/src/test/java/org/geotools/feature/simple/SimpleFeatureBuilderTest.java
[![GEOT-7815](https://badgen.net/badge/JIRA/GEOT-7815/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7815) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
Backport: #5359
=> [Backport 33.x] [GEOT-7815] Added support to attributes restrictions handling.

platform-dependencies/pom.xml
[![GEOT-7823](https://badgen.net/badge/JIRA/GEOT-7823/0052CC)](https://osgeo-org.atlassian.net/browse/GEOT-7823) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=geotools&utm_campaign=badge_info)
In preparation for the 34.0 release
=> [GEOT-7823] Migrate to ImageN 0.9.0 and ImageIO Ext 2.0.0
