geotools/geotools

- docs/pom.xml
- docs/user/tutorial/datastore/store.rst
Fixed a couple broken links, and fixing the broken build. Forgot to include the change to the docs pom.xml.
> Fix package and sphinx errors

- modules/plugin/property/src/test/java/org/geotools/data/property/PropertyDataStoreCurveTest.java
- modules/unsupported/property-ng/src/main/java/org/geotools/data/property/ng/PropertyFeatureReader.java
- modules/unsupported/property-ng/src/main/java/org/geotools/data/property/ng/PropertyFeatureSource.java
- modules/unsupported/property-ng/src/test/java/org/geotools/data/property/ng/PropertyDataStoreCurveTest.java
Also added test cases for curves and linearization tolerance (copied from gt-property).
> Added WKT reader to PropertyFeatureReader. 

- modules/library/data/src/main/java/org/geotools/data/store/ContentFeatureStore.java
Simple fix of type (SimpleFeatureLocking instead of FeatureLocking<...>
> ContentFeatureStore extends SimpleFeatureLocking

- modules/unsupported/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java
- modules/unsupported/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
- modules/unsupported/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
> Remove entries when removing feature tables

- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/DatatypeConverterImpl.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/XsDateTimeFormat.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xml/impl/XsDateTimeFormatTest.java
Backport on 12.x branch of the fix for JIRA: https://jira.codehaus.org/browse/GEOT-4967
> [GEOT-4967] XsDateTimeFormat should be more lenient (Backport on 12.x)

- modules/unsupported/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
> Let geopackage databases use specific geometry types for geometry columns

- modules/extension/graph/src/main/java/org/geotools/graph/traverse/standard/DijkstraIterator.java
- modules/extension/graph/src/test/java/org/geotools/graph/traverse/standard/DijkstraIteratorTest.java
Added test cases for #682.
Since getRelated was not really tested by the existing test cases, I have added tests for both directed (test_7) and undirected (test_8) graphs.
> Correction for bug on directed graphs (with tests)

- modules/unsupported/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
Solved Issue #4994
http://jira.codehaus.org/browse/GEOT-4994
Thanks!
Jared
> GeoPackage feature tables should have a primary key with AUTOINCREMENT

- modules/unsupported/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java
- modules/unsupported/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
Solved issue #4995.
http://jira.codehaus.org/browse/GEOT-4995
Thanks!
Jared
> GeoPackage databases should be initialized with default spatial references

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Resampler2D.java
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/ResampleTest.java
This pull requests contains a fix for JIRA: https://jira.codehaus.org/browse/GEOT-4853
> [GEOT-4853] Reprojection Color Banding Issue

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Resampler2D.java
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/ResampleTest.java
See: https://github.com/geotools/geotools/pull/715
> [GEOT-4853] Reprojection Color Banding Issue (Backport on 12.x)

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
Updated pull requets, a unit test seems hard to do since I can't even reproduce the issue locally. It is a numerical edge case.
> GEOT-4998 add additional ROI check after scaling the image

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
Backport of GEOT-4998 to 12.x branch
> GEOT-4998  backport to 12.x

- modules/library/render/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java
- modules/library/render/src/test/java/org/geotools/renderer/crs/ProjectionHandlerTest.java
This pull request contains a fix for JIRA https://jira.codehaus.org/browse/GEOT-5006.
> [GEOT-5006] ProjectionHandler should not intersect Geometries with wrong GeometryType

- modules/library/render/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java
- modules/library/render/src/test/java/org/geotools/renderer/crs/ProjectionHandlerTest.java
See: https://github.com/geotools/geotools/pull/723
> [GEOT-5006] ProjectionHandler should not intersect Geometries with wrong GeometryType (Backport 12.x)

- modules/unsupported/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
following https://github.com/geotools/geotools/pull/651
> Geopackage fix srs name (GEOT-4625) - test

- modules/unsupported/solr/src/main/java/org/geotools/data/solr/FieldLayerMapper.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/SingleLayerMapper.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrDataStore.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrDataStoreFactory.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrLayerMapper.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrUtils.java
- modules/unsupported/solr/src/test/java/org/geotools/data/solr/SolrDataStoreFactoryTest.java
- modules/unsupported/solr/src/test/java/org/geotools/data/solr/SolrSingleLayerMappingTest.java
- modules/unsupported/solr/src/test/java/org/geotools/data/solr/SolrTestSupport.java
Also added LayerMappingStrategy with an implementation for mapping to single layer.
> GEOT-5000: Support for mapping solr index to single layer.

- docs/index/index.rst
- docs/web/getinvolved.rst
Also fixes a type on the Get Involved page.
> Fixed broken link in GeoTools doc page

- modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java
- modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderTest.java
This addresses the issue of an unuseful error message (namely: "No input stream for the provided source") when the `GeoTiffReader` is given a file path that does not exist, is a directory, or when the user does not have permissions to the file.
The issue arises from `imageio-ext` code: [This code](https://github.com/geosolutions-it/imageio-ext/blob/master/library/streams/src/main/java/it/geosolutions/imageio/stream/input/spi/FileImageInputStreamExtImplSpi.java#L159) in imageio-ext's `FileImageInputStreamExtImplSpi` swallows any IO exceptions that are thrown from [this code](https://github.com/geosolutions-it/imageio-ext/blob/master/library/streams/src/main/java/it/geosolutions/imageio/stream/input/FileImageInputStreamExtImpl.java#L216) in `FileImageInputStreamExtImpl`. So instead of the …
> [GEOT-4873] Provide useful error message in GeoTiffReader for file read errors.

- README.md
Fixed a small typo (relateded to related) in the README.md.
> Fixed a typo in Mailing Lists.

- docs/user/library/jdbc/sqlserver.rst
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCTestSupport.java
- modules/library/render/src/main/java/org/geotools/renderer/style/SLDStyleFactory.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/FillTest.java
- modules/library/render/src/test/resources/org/geotools/renderer/lite/test-data/fillCrossUom.sld
- modules/plugin/jdbc/jdbc-sqlserver/pom.xml
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDataStoreFactory.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDialect.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerJNDIDataStoreFactory.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/jtds/JTDSClobConverterFactory.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/jtds/JTDSDateConverterFactory.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/jtds/JTDSSQLServerDialect.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/jtds/JTDSSqlServerDataStoreFactory.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/resources/META-INF/services/org.geotools.data.DataStoreFactorySpi
- modules/plugin/jdbc/jdbc-sqlserver/src/main/resources/META-INF/services/org.geotools.util.ConverterFactory
- modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerDataStoreFactoryOnlineTest.java
- modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerSkipColumnOnlineTest.java
- modules/plugin/property/pom.xml
- modules/unsupported/css/src/main/java/org/geotools/styling/css/DomainCoverage.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/RulePowerSetBuilder.java
- modules/unsupported/css/src/test/resources/css/integration/nestedor-first.sld
- modules/unsupported/css/src/test/resources/css/integration/nestedor.sld
Allows users with more than one DB on their machine to use the instance parameter to pick the right one.
With dbtype parameter jtds-sqlserver selects the JTDS driver which we can distribute.
> GEOT-4984 add INSTANCE parameter and GEOT-4476 allow use of JTDS driver

- modules/library/render/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java
- modules/library/render/src/test/java/org/geotools/renderer/crs/ProjectionHandlerTest.java
Please look at the following JIRA: https://jira.codehaus.org/browse/GEOT-5041.
> [GEOT-5041] ProjectionHandler fails with empty GeometryCollection

- modules/library/render/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java
- modules/library/render/src/test/java/org/geotools/renderer/crs/ProjectionHandlerTest.java
Backport on 13.x for jira: https://jira.codehaus.org/browse/GEOT-5041
> [GEOT-5041] ProjectionHandler fails with empty GeometryCollection (Backport on 13.x)

- modules/library/render/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java
- modules/library/render/src/test/java/org/geotools/renderer/crs/ProjectionHandlerTest.java
Backport on 12.x for JIRA: https://jira.codehaus.org/browse/GEOT-5041
> [GEOT-5041] ProjectionHandler fails with empty GeometryCollection (Backport on 12.x)

- modules/extension/xsd/xsd-core/pom.xml
> Update JUnit dependency in XSD-Core to match root POM

- modules/library/coverage/src/main/java/org/geotools/coverage/Category.java
- modules/library/coverage/src/main/java/org/geotools/coverage/GridSampleDimension.java
- modules/library/coverage/src/main/java/org/geotools/coverage/grid/Calculator2D.java
- modules/library/coverage/src/main/java/org/geotools/coverage/grid/GridCoverage2D.java
- modules/library/coverage/src/main/java/org/geotools/coverage/grid/ViewType.java
- modules/library/coverage/src/main/java/org/geotools/coverage/processing/Operations.java
- modules/library/coverage/src/main/java/org/geotools/resources/coverage/CoverageUtilities.java
- modules/library/opengis/src/main/java/org/opengis/coverage/SampleDimension.java
Please look at the following JIRA: https://jira.codehaus.org/browse/GEOT-5050
> [GEOT-5050] Deprecate Views Management classes

- modules/plugin/jdbc/jdbc-sqlserver/pom.xml
Added documentation and sqlserver profile activation parameter (based on Oracle plugin), and updated driver version to 4.1 (from 4.0).
> Updated pom for new MS SQL Server jar

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Crop.java
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/CropTest.java
Please look at the following JIRA: https://jira.codehaus.org/browse/GEOT-5063
> [GEOT-5063] Crop operation fails to render ROI correctly in openJDK7

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Crop.java
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/CropTest.java
Backport on 13.x of the fix for JIRA: https://jira.codehaus.org/browse/GEOT-5063
> [GEOT-5063] Crop operation fails to render ROI correctly in openJDK7 (Backport on 13.x)

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Crop.java
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/CropTest.java
Backport on 12.x of the fix for JIRA: https://jira.codehaus.org/browse/GEOT-5063
> [GEOT-5063] Crop operation fails to render ROI correctly in openJDK7 (Backport on 12.x)

- modules/library/main/src/main/java/org/geotools/styling/FeatureTypeStyleImpl.java
- modules/library/main/src/main/java/org/geotools/styling/visitor/DuplicatingStyleVisitor.java
- modules/library/main/src/test/java/org/geotools/styling/visitor/DuplicatorStyleVisitorTest.java
> GEOT-5053: DuplicatingStyleVisitor does not duplicate FeatureTypeStyleImpl completely

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/AddConst.java
See http://osgeo-org.1560.x6.nabble.com/SubtractFromConst-and-AddConst-errors-td5200933.html for discussion.  This solves issue #5073.
Thanks!
Jared
> AddConst is calling the wrong super constructor

- modules/library/coverage/pom.xml
- pom.xml
See the related issue: https://osgeo-org.atlassian.net/browse/GEOT-5078
> [GEOT-5078] Upgrade JAIEXT to 1.0.2

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Mosaic.java
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/MosaicTest.java
Removed the JAIEXT check for the sources extraction.
> Fixed minor issue on mosaic operation

- modules/unsupported/wfs/src/main/java/org/geotools/data/wfs/v1_1_0/WFSFeatureCollection.java
This version uses a less expensive way of counting the number of features inside
the FeatureCollection document if numberOfFeatures attribute is not provided. This
also caches the bounds once a forced bounds calculation has been performed.
> [GEOT-5044] A less expensive WFSFeatureCollection.getCount()

- modules/unsupported/geojson/pom.xml
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/GeoJSONUtil.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/FeatureTypeAttributeIO.java
- modules/unsupported/geojson/src/test/java/org/geotools/geojson/FeatureJSONExtendedTest.java
- modules/unsupported/geojson/src/test/java/org/geotools/geojson/GEOT5036RegressionTest.java
The first commit provides a regression test which exploits the bug against current code; the second provides a fix (and updated test).
> Fix bug GEOT-5036

- modules/plugin/arcsde/datastore/src/main/java/org/geotools/arcsde/data/ArcSDEQuery.java
On SDE on Oracle (and maybe other platforms) WFS queries against layers containing large numbers of features is very slow. This is because WFS requires computing the size of the query result before the query is executed to retrieve data. The SDE API method SEQuery.calculateTableStatistics currently used to do this is very slow (on Oracle at least).
A workaround is to run the query twice, once to count the features and once to fetch the data.
Note that due to an undocumented quirk of the SDE API, it is also necessary to call SEQuery.prepareQueryInfo before SEQuery.setSpatialConstraints. Otherwise, the spatial filter will not apply.
See https://osgeo-org.atlassian.net/browse/GEOT-5085
> GEOT-5085 Workaround for slow performance of SDE Table Stats on Oracle

- modules/library/referencing/src/main/java/org/geotools/referencing/operation/matrix/GeneralMatrix.java
- modules/library/referencing/src/main/java/org/geotools/referencing/operation/transform/ProjectiveTransform.java
- modules/library/referencing/src/test/java/org/geotools/referencing/operation/matrix/GeneralMatrixTest.java
* Updated a constructor to call setIdentity.
* Tweaked copySubMatrix.
* Fixed sub.
Additionally, changed an expected exception in org/geotools/referencing/operation/transform/ProjectiveTransform.java.
> Fixed outstanding test failures for the vecmath transition.

- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCDateOnlineTest.java
fixed timezone leak in online date tests (which was breaking PostGIS and SQLServer)
> reset timezone and database after tests

- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/PullParser.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/ParserHandler.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/PullParserFeatureReader.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/v2_0/FeatureTypeInfoImpl.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/AbstractIntegrationTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/IntegrationTestWFSClient.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/v2_0/GeoServerIntegrationTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/v2_0/GeoServerOnlineTest.java
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/GeoServer_2.2.x/2.0.0/DescribeFeatureType_archsites.xsd
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/GeoServer_2.2.x/2.0.0/DescribeFeatureType_roads.xsd
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/GeoServer_2.2.x/2.0.0/GetCapabilities.xml
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/GeoServer_2.2.x/2.0.0/GetFeature_archsites.xml
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/GeoServer_2.2.x/2.0.0/GetFeature_roads.xml
Follow on to https://osgeo-org.atlassian.net/browse/GEOT-4908
> Wfs-ng: wfs2.0 tests [GEOT-4908]

- modules/library/referencing/pom.xml
- modules/library/referencing/src/main/java/org/geotools/referencing/factory/epsg/DirectEpsgFactory.java
- modules/library/referencing/src/test/java/org/geotools/referencing/AbstractCRSTest.java
- modules/plugin/epsg-hsql/pom.xml
- modules/plugin/epsg-hsql/src/test/java/org/geotools/referencing/HSQLCRSTest.java
- modules/plugin/epsg-postgresql/pom.xml
- modules/plugin/epsg-postgresql/src/main/java/org/geotools/referencing/factory/epsg/ThreadedPostgreSQLEpsgFactory.java
- modules/plugin/imagemosaic-jdbc/pom.xml
- modules/plugin/jdbc/jdbc-postgis/pom.xml
- pom.xml
Tested locally the jdbc-postgis module, full pass, the epsg-postgresql one, for which I've built an online test, and the gt-imagemosaic-jdbc one, limited to the postgis and pgraster online tests.
> [GEOT-4636] Upgrade PostgreSQL JDBC library

- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoDBObjectFeature.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoInferredMapper.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoUtil.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoTestSupport.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
Port of https://github.com/boundlessgeo/geoserver-exts/pull/85 to GeoTools
> MongoDB plugin ignores arrays when generating a schema

- modules/library/main/src/main/java/org/geotools/filter/function/JenksNaturalBreaksFunction.java
See https://osgeo-org.atlassian.net/browse/GEOT-5154 - Jenks was leaking featureIterators
> fixed leaking featureIterators

- modules/unsupported/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDataStoreFactory.java
Registers the geopackage "database" attribute (which is a local file path) as a File parameter, in order to support file upload in rest config.
> Geopackage: File Parameter

- modules/unsupported/geojson/src/test/java/org/geotools/geojson/GEOT5158RegressionTest.java
- modules/unsupported/geojson/src/test/resources/org/geotools/geojson/sample.geojson
TestCase for GEOT - 5158 - FeatureJson readFeatureCollection not working properly if the geojson contains array of object in it.
> TestCase for GEOT - 5158 - FeatureJson readFeatureCollection not working properly if the geojson contains array of object in it.

- modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrDataStore.java
The pull request changes the interpretation of layer configuration, making them similar to sql views
> [GEOT-5146] Deprecate SOLR data store per attribute layer generation

- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoTestSetup.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoTestSupport.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
See [related JIRA issue](https://osgeo-org.atlassian.net/browse/GEOT-5172).
> [GEOT-5172] Fixed date comparison filters in MongoDB datastore

- modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/bindings/ValueCollectionTypeBindingTest.java
- modules/library/main/src/main/java/org/geotools/util/CommonsConverterFactory.java
- modules/plugin/jdbc/jdbc-db2/src/main/java/org/geotools/data/db2/DB2FilterToSQL.java
- modules/plugin/jdbc/jdbc-h2/src/main/java/org/geotools/data/h2/H2FilterToSQL.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerFilterToSQL.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/RecnoFilterToSQL.java
- modules/unsupported/efeature/src/main/java/org/geotools/data/efeature/adapters/DateAdapter.java
- modules/unsupported/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java
This is a replacement for #860, it has been rebased, and CommonsConverterFactory.DataConverter has been revised based on discussion.
See: https://osgeo-org.atlassian.net/browse/GEOT-5130
> removed static dateformats as they are not thread safe [GEOT-5130]

- docs/user/tutorial/raster/jaiext.rst
Added code-block section and tweaked some grammar
> minor doc cleanup

- modules/library/main/src/main/java/org/geotools/util/SubProgressListener.java
- modules/library/main/src/test/java/org/geotools/util/SubProgressListenerTest.java
(Edit) Needed for https://github.com/geoserver/geoserver/pull/1188
Prior PR and discussion here https://github.com/geotools/geotools/pull/894   (For some reason Github won't let me just re-open the original PR after the rebase and forced push)
> fix event delegation

- modules/plugin/jdbc/jdbc-db2/src/main/java/org/geotools/data/db2/DB2FilterToSQL.java
https://osgeo-org.atlassian.net/browse/GEOT-5212
> GEOT-5212 DB2 st_disjoint does not work with SELECTIVITY clause

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Resampler2D.java
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/ResampleTest.java
See GEOT-5218, this is the backport for 13.x
> fix for GEOT-5218, JAI Workaround in Warp generates stackoverflow exception

- docs/developer/communication.rst
Also a spelling fix, in best GeoTools tradition.
> Fix out-of-date links

- modules/extension/transform/src/main/java/org/geotools/data/transform/TransformFeatureIteratorWrapper.java
- modules/extension/transform/src/main/java/org/geotools/data/transform/TransformFeatureReaderWrapper.java
- modules/extension/transform/src/main/java/org/geotools/data/transform/Transformer.java
- modules/extension/transform/src/test/java/org/geotools/data/transform/TransformFeatureSourceTest.java
> [GEOT-5240] Transforming feature source does not honor naming convention on FID

- modules/library/api/src/main/java/org/geotools/data/CloseableIterator.java
- modules/library/api/src/main/java/org/geotools/data/FileGroupProvider.java
- modules/library/api/src/main/java/org/geotools/data/FileResourceInfo.java
- modules/library/api/src/main/java/org/geotools/data/FileServiceInfo.java
- modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/AbstractGridCoverage2DReader.java
- modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/GridCoverage2DReader.java
- modules/library/main/src/main/java/org/geotools/data/DefaultCloseableIterator.java
- modules/library/main/src/main/java/org/geotools/data/DefaultFileResourceInfo.java
- modules/library/main/src/main/java/org/geotools/data/DefaultFileServiceInfo.java
- modules/plugin/coverage-multidim/coverage-api/src/main/java/org/geotools/coverage/io/catalog/CoverageSlice.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFDriver.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFFileResourceInfo.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFReader.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFReaderTest.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/PostGisIndexTest.java
- modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java
- modules/plugin/image/src/main/java/org/geotools/gce/image/WorldImageReader.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicFileResourceInfo.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicReader.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterManager.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/CloseableIteratorWrapper.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/IndexManager.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/IndexedShapefileFeatureReader.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureSource.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/index/CachedQuadTree.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/index/quadtree/LazySearchIterator.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/index/quadtree/QuadTree.java
Once merged, make sure to merge 
https://github.com/geoserver/geoserver/pull/1277
Containing the required GeoServer code updates
> [GEOT-5247]: Add capability to report files composing a store/reader

- modules/library/xml/src/main/java/org/geotools/xml/schema/Schema.java
> Fix small typos in Schema.java

- modules/plugin/property/src/test/java/org/geotools/data/property/PropertyDataStore2Test.java
Compiling module gt-property actual version 15-SNAPSHOT does generate files and directories within the project directory. I relocated these files into the target directory. Now git as well does not find changes anymore.
> test property files are now created within target directory

- docs/user/tutorial/map/style.rst
removed references to SVN and added refs to git
> updated refs to svn to git and version

- modules/library/render/src/main/java/org/geotools/renderer/lite/CompositingGroup.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/DirectLayerLabelsTest.java
Fixes issue where labels were lost when a directlayer was included in a map.
> Backport of fix for [GEOT-5216] and PR978

- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/RulePowerSetBuilder.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
- modules/unsupported/css/src/test/resources/css/integration/flat-capitals-first.sld
- modules/unsupported/css/src/test/resources/css/integration/flat-capitals.css
- modules/unsupported/css/src/test/resources/css/integration/flat-capitals.sld
This is a cleaned up version of pull request #989
> CSS style title/abstract and flat mode

- modules/library/data/src/main/java/org/geotools/data/memory/MemoryDataStore.java
- modules/library/data/src/test/java/org/geotools/data/memory/MemoryDataStoreTest.java
backport to 14.x branch for https://osgeo-org.atlassian.net/browse/GEOT-5256
> [GEOT-5256] added removeSchema Support for MemoryDataStore

- modules/library/cql/README.md
Just discovered this little one whilst digging around in doco.
> Fixed incorrect/outdated links

- modules/unsupported/geopkg/src/main/resources/org/geotools/geopkg/gpkg_contents.sql
- modules/unsupported/geopkg/src/main/resources/org/geotools/geopkg/gpkg_data_column_constraints.sql
- modules/unsupported/geopkg/src/main/resources/org/geotools/geopkg/gpkg_geometry_columns.sql
- modules/unsupported/geopkg/src/main/resources/org/geotools/geopkg/gpkg_metadata.sql
- modules/unsupported/geopkg/src/main/resources/org/geotools/geopkg/gpkg_metadata_reference.sql
https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-5230
> [GEOT-5230] Update GeoPackage gpkg_contents DDL to match (revised) standard

- docs/developer/conventions/code/style.rst
- docs/developer/conventions/test/online.rst
- docs/user/build/maven/build.rst
- docs/user/build/maven/javadocs.rst
- docs/user/library/coverage/geotiff.rst
- docs/user/library/referencing/extension.rst
- docs/user/library/referencing/wkt.rst
- docs/user/tutorial/map/style.rst
- docs/user/welcome/application.rst
- docs/user/welcome/faq.rst
- docs/web/about.rst
In addition cleanup of outdated javadoc tags (@Source $URL$)
> changed svn references to github

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSDataAccessFactory.java
https://osgeo-org.atlassian.net/browse/GEOS-7266
> Wfs-ng: fix strategy parameter for wfs compatibility

- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReader.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/Slice2DIndex.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/cv/NumericCoordinateVariable.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/cv/TimeCoordinateVariable.java
> [GEOT-5013]: fix thread-safety in indexManager and mitigating

- modules/extension/wms/pom.xml
- modules/extension/wms/src/main/java/org/geotools/data/wms/WMS1_1_0.java
- modules/extension/wms/src/main/java/org/geotools/data/wms/WMS1_1_1.java
- modules/extension/wms/src/main/java/org/geotools/data/wms/request/AbstractGetStylesRequest.java
- modules/extension/wms/src/test/java/org/geotools/data/wms/test/LocalGeoServerOnlineTest.java
Reverts geotools/geotools#1030
> Revert "Implements GetStyles request on WMS 1.1.1 [GEOT-5309]"

- modules/unsupported/geobuf/src/main/java/org/geotools/data/geobuf/GeobufDataStore.java
- modules/unsupported/geobuf/src/main/java/org/geotools/data/geobuf/GeobufDirectoryDataStore.java
- modules/unsupported/geobuf/src/test/java/org/geotools/data/geobuf/GeobufDataStoreTest.java
- modules/unsupported/geobuf/src/test/java/org/geotools/data/geobuf/GeobufDirectoryDataStoreTest.java
Fixes https://osgeo-org.atlassian.net/browse/GEOT-5332.
Thanks!
Jared
> Add removeSchema support to geobuf DataStore.  Fixes issue GEOT-5332

- modules/plugin/property/src/main/java/org/geotools/data/property/PropertyDataStore.java
- modules/plugin/property/src/test/java/org/geotools/data/property/PropertyDataStoreTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5333
Thanks!
Jared
> Make Property DataStore support removeSchema.  Solves issue GEOT-5333.

- modules/library/coverage/src/main/java/org/geotools/coverage/processing/EmptyIntersectionException.java
- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Crop.java
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/CropTest.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageReaderHelper.java
Checking if the numerical instability also happens on Travis
> [GEOT-5335] Coverage cropping during read might fail due to numerical issues

- modules/plugin/jdbc/jdbc-spatialite/src/main/java/org/geotools/data/spatialite/SpatiaLiteDialect.java
- modules/plugin/jdbc/jdbc-spatialite/src/test/java/org/geotools/data/spatialite/SpatiaLiteDataStoreAPIOnlineTest.java
- modules/plugin/jdbc/jdbc-spatialite/src/test/java/org/geotools/data/spatialite/SpatiaLiteDataStoreAPITestSetup.java
See https://osgeo-org.atlassian.net/browse/GEOT-5261
> GEOT-5261 Delete record from geometry_columns when featureType removed

- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/FeatureClassStats.java
- modules/unsupported/process-feature/src/main/resources/META-INF/services/org.geotools.process.vector.VectorProcess
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/FeatureClassStatsTest.java
- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/CoverageClassStats.java
- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/classify/Classification.java
- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/classify/NaturalClassification.java
- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/classify/QuantileClassification.java
- modules/unsupported/process-raster/src/main/java/org/geotools/processing/jai/ClassBreaksDescriptor.java
- modules/unsupported/process-raster/src/main/java/org/geotools/processing/jai/ClassBreaksOpImage.java
- modules/unsupported/process-raster/src/main/java/org/geotools/processing/jai/ClassBreaksRIF.java
- modules/unsupported/process-raster/src/main/java/org/geotools/processing/jai/ClassBreaksSpi.java
- modules/unsupported/process-raster/src/main/java/org/geotools/processing/jai/EqualIntervalBreaksOpImage.java
- modules/unsupported/process-raster/src/main/java/org/geotools/processing/jai/NaturalBreaksOpImage.java
- modules/unsupported/process-raster/src/main/java/org/geotools/processing/jai/QuantileBreaksOpImage.java
- modules/unsupported/process-raster/src/main/resources/META-INF/registryFile.jai
- modules/unsupported/process-raster/src/main/resources/META-INF/services/javax.media.jai.OperationsRegistrySpi
- modules/unsupported/process-raster/src/main/resources/META-INF/services/org.geotools.process.raster.RasterProcess
- modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/CoverageClassStatsTest.java
- modules/unsupported/process/src/main/java/org/geotools/process/classify/ClassificationMethod.java
- modules/unsupported/process/src/main/java/org/geotools/process/classify/ClassificationStats.java
Adds FeatureClassStats and CoverageClassStats process classes that allow for
classifying data using one of equal interval, quantile, or natural breaks method.
> Added processes for classifying raster and vector data.

- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/CreateIndexer.java
adding support for elevation attribute as double
> NetCDF/GRIB: Minor improvements on the Indexer Creator testing tool

- modules/unsupported/wfs/src/main/java/org/geotools/data/wfs/v1_1_0/parsers/XmlSimpleFeatureParser.java
- modules/unsupported/wfs/src/test/java/org/geotools/data/wfs/v1_1_0/AbstractGetFeatureParserTest.java
- modules/unsupported/wfs/src/test/java/org/geotools/data/wfs/v1_1_0/DataTestSupport.java
- modules/unsupported/wfs/src/test/java/org/geotools/data/wfs/v1_1_0/XmlSimpleFeatureParserTest.java
- modules/unsupported/wfs/src/test/resources/org/geotools/data/wfs/v1_1_0/test-data/geoserver/DescribeFeatureType_simplecurveroads.xsd
- modules/unsupported/wfs/src/test/resources/org/geotools/data/wfs/v1_1_0/test-data/geoserver/GetFeature_simplecurveroads.xml
Hi,
Small PR for adding Curve support into WFS-NG SimpleFeatureParser.
This PR is related to GEOT-5364 and GEOS-7420
Tell me if improvements are needed.
Regards,
> [GEOT-5364] Add support for Curve (WFS-NG)

- modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/GML2FeatureCollectionEncoderDelegate.java
- modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/GenericGeometryEncoder.java
- modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/GeometryCollectionEncoder.java
- modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GML32FeatureCollectionEncoderDelegate.java
- modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GenericGeometryEncoder.java
- modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GeometryCollectionEncoder.java
- modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/GeometryCollectionEncoderTest.java
WMS seems to work just fine with GeometryCollection, however, WFS does not.
The classes added here encodes the geometries within the geometrycollection.
Update GML2FeatureCollectionEncoderDelegate.java
> [GEOT-5360] Issue serializing xml (WFS) for Geometry collections

- modules/extension/xsd/xsd-gml2/pom.xml
- modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/GenericGeometryEncoder.java
- modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/GeometryCollectionEncoder.java
- modules/extension/xsd/xsd-gml2/src/test/java/org/geotools/gml2/simple/GeometryCollectionEncoderTest.java
Unit tests for GML2 - follow up on the previous commit.
> [GEOT-5360] Unit test GML2

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreAPIOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreAPITestSetup.java
Backport of https://github.com/geotools/geotools/pull/1132 to 14.x
> [GEOT-4737] (14.x) Use of PostGIS ST_Simplify causes small polygons to disappear completely

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreAPIOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreAPITestSetup.java
Backport of https://github.com/geotools/geotools/pull/1132 to 13.x
> [GEOT-4737] (13.x) Use of PostGIS ST_Simplify causes small polygons to disappear completely

- modules/library/jdbc/src/main/java/org/geotools/jdbc/MetadataTablePrimaryKeyFinder.java
fixes [GEOT-5349](https://osgeo-org.atlassian.net/browse/GEOT-5349)
see also #1140
> [GEOT-5349] Use encodeSchemaName(...) while looking up GT_PK_METADATA [14.x]

- modules/library/coverage/src/main/java/org/geotools/coverage/ColorModelFactory.java
- modules/library/coverage/src/test/java/org/geotools/coverage/ColorModelFactoryTest.java
[GEOT-5390] Fixed ColorModelFactory returning cached ColorModel objects with the wrong data type.
> [GEOT-5390] Fixed ColorModelFactory returning cached ColorModel objects with the wrong data type.

- modules/unsupported/ysld/README.md
A few updates, please review @smithkm / @jdeolive
> update examples and grammar

- docs/user/library/main/collection.rst
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGroupByVisitorOnlineTest.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCGroupByVisitorTestSetup.java
- modules/library/main/src/main/java/org/geotools/feature/visitor/Aggregate.java
- modules/library/main/src/main/java/org/geotools/feature/visitor/GroupByVisitor.java
- modules/library/main/src/main/java/org/geotools/feature/visitor/GroupByVisitorBuilder.java
- modules/library/main/src/test/java/org/geotools/feature/visitor/GroupByVisitorTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGroupByVisitorOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisGroupByVisitorTestSetup.java
- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/AggregateProcess.java
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/AggregateProcessTest.java
Issue: https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-5375
> [GEOT-5375] Add a group by visitor (backport 14.x)

- modules/library/metadata/pom.xml
- modules/library/metadata/src/main/java/org/geotools/factory/GeoTools.java
- modules/library/metadata/src/test/java/org/geotools/factory/GeoToolsTest.java
Used to verify geotools execution environment.
> jar lookup of manifest and version details

- modules/library/main/src/main/java/org/geotools/util/TemporalConverterFactory.java
- modules/library/main/src/test/java/org/geotools/util/TemporalConverterFactoryTest.java
This adds a Long to Date converter to handle dates produced by arcgis server rest interface 
[GEOT-5388](https://osgeo-org.atlassian.net/browse/GEOT-5388)
see also: https://sourceforge.net/p/geotools/mailman/message/34966228/
> [GEOT-5388] Add Long -> Date converter to TemporalConverterFactory

- modules/library/main/src/main/java/org/geotools/util/TemporalConverterFactory.java
- modules/library/main/src/test/java/org/geotools/util/TemporalConverterFactoryTest.java
> [GEOT-5388] Add Long -> Date converter to TemporalConverterFactory (14.x)

- modules/unsupported/solr/pom.xml
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/FieldLayerMapper.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/FilterToSolr.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/SingleLayerMapper.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrDataStore.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrFeatureReader.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrFeatureSource.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrLayerMapper.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrSpatialStrategy.java
- modules/unsupported/solr/src/test/java/org/geotools/data/solr/SolrFeatureSourceTest.java
- modules/unsupported/solr/src/test/java/org/geotools/data/solr/SolrSpatialStrategyTest.java
- modules/unsupported/solr/src/test/resources/wifiAccessPoint.xml
update to a newer version of Solr.
> [GEOT-5387]Solr version update from 4.9.0 to 5.2.1

- modules/library/main/src/main/java/org/geotools/data/store/FilteringFeatureIterator.java
- modules/library/main/src/test/java/org/geotools/data/store/FilteringSimpleFeatureCollectionTest.java
see [GEOT-5403](https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-5403) for full discussion
> [GEOT-5403] fix issue with next/hasNext

- modules/library/main/src/main/java/org/geotools/data/store/FilteringFeatureIterator.java
- modules/library/main/src/test/java/org/geotools/data/store/FilteringSimpleFeatureCollectionTest.java
Fix for issue discussed in [GEOT-5403](https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-5403) backported to 14.x
> back port of GEOT-5403 fix

- modules/library/main/src/main/java/org/geotools/util/TemporalConverterFactory.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/BigDate.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisUDTOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisUDTTestSetup.java
Allows for supporting a wider range of dates than the postgresql timestamp type. This is rework of what was originally pull request #997.
> GEOT-5258, Support for storing dates as bigint with postgis.

- docs/developer/procedures/add.rst
- docs/user/library/jts/index.rst
- docs/user/library/jts/operation.rst
Also includes a bonus typo fix from the JTS docs.
> [GEOT-5389] Fix JTS version reference in documentation.

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
14.x backport for https://github.com/geotools/geotools/pull/1133
> [GEOT-5378] (14.x) Add check for functions deprecated in PostGIS 2.1.0

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
13.x backport for https://github.com/geotools/geotools/pull/1133
> [GEOT-5378] (13.x) Add check for functions deprecated in PostGIS 2.1.0

- modules/library/main/src/main/java/org/geotools/data/DataUtilities.java
- modules/library/main/src/test/java/org/geotools/data/collection/SortedFeatureCollectionTest.java
Backport of https://github.com/geotools/geotools/pull/1188
> SortOrder.DESCENDING doesn't sort in descending order

- modules/library/main/src/main/java/org/geotools/data/DataUtilities.java
- modules/library/main/src/test/java/org/geotools/data/collection/SortedFeatureCollectionTest.java
backport of https://github.com/geotools/geotools/pull/1188
> Backport: [GEOT-5416] Fix so SortOrder.DESCENDING works

- modules/library/main/src/main/java/org/geotools/styling/FeatureTypeStyleImpl.java
- modules/library/main/src/test/java/org/geotools/styling/FeatureTypeStyleImplTest.java
New test: org.geotools.styling.FeatureTypeStyleImplTest
> [GEOT-5397] fixed org.geotools.styling.FeatureTypeStyleImpl.clone()

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicDatastoreWalker.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/catalog/GTDataStoreGranuleCatalog.java
Does not require a new test in that it's just a different solution to the GEOT-5168 (pure performance optimization)
> [GEOT-5420] Performance regression creating image mosaic reader agaist databases with thousands of tables

- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReaderSpi.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/imageio/netcdf/NetCDFImageReaderSpiTest.java
Backport of pull request: https://github.com/geotools/geotools/pull/1194
> [GEOT-5419] Fix NetCDFImageReaderSpi file dispose (backport 15.x)

- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReaderSpi.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/imageio/netcdf/NetCDFImageReaderSpiTest.java
Backport of pull request: https://github.com/geotools/geotools/pull/1194
> [GEOT-5419] Fix NetCDFImageReaderSpi file dispose (backport 14.x)

- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerJNDIDataStoreFactory.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/jtds/JDTSSQLServerJNDIDataStoreFactory.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/resources/META-INF/services/org.geotools.data.DataStoreFactorySpi
- modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/jdts/SQLServerJTDSJNDITest.java
reference: https://osgeo-org.atlassian.net/browse/GEOT-5422
> [GEOT-5422] fix jndi factory lookup for jtds driver sqlserver (master)

- docs/developer/conventions/code/style.rst
See https://github.com/geotools/geotools/wiki/Updates-to-Copyright-Header-Policy
> Apply OSGeo copyright on creation/contribution

- modules/library/xml/src/main/java/org/geotools/xml/xsi/XSISimpleTypes.java
- modules/library/xml/src/test/java/org/geotools/xml/xsi/XSISimpleTypesTest.java
> Return null instead of throwing exception when parsing empty dates [GEOT-5435]

- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerJNDIDataStoreFactory.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/jtds/JDTSSQLServerJNDIDataStoreFactory.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/resources/META-INF/services/org.geotools.data.DataStoreFactorySpi
- modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/jdts/SQLServerJTDSJNDITest.java
fixes https://osgeo-org.atlassian.net/browse/GEOT-5422
see #1198
> [GEOT-5422] fix jndi factory lookup for jtds driver sqlserver (14.x) 

- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerJNDIDataStoreFactory.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/jtds/JDTSSQLServerJNDIDataStoreFactory.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/resources/META-INF/services/org.geotools.data.DataStoreFactorySpi
- modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/jdts/SQLServerJTDSJNDITest.java
fixes https://osgeo-org.atlassian.net/browse/GEOT-5422
see #1198
> [GEOT-5422] fix jndi factory lookup for jtds driver sqlserver (15.x)

- modules/library/referencing/src/main/java/org/geotools/referencing/operation/transform/WarpTransform2D.java
- modules/library/referencing/src/main/java/org/geotools/referencing/operation/transform/WarpTransform2DProvider.java
- modules/library/referencing/src/main/resources/META-INF/services/org.geotools.referencing.operation.MathTransformProvider
See: https://osgeo-org.atlassian.net/browse/GEOT-561
> isolate provider to prevent SPI failure if no JAI [GEOT-561]

- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDataStoreOnlineTest.java
fix for https://osgeo-org.atlassian.net/browse/GEOT-5451 
I can't see any way to add a unit test for this.
> increased oracle nvarchar2 max size to 4000 [GEOT-5451]

- modules/library/coverage/src/main/java/org/geotools/resources/image/ImageUtilities.java
- modules/plugin/gtopo30/src/main/java/org/geotools/gce/gtopo30/GTopo30Writer.java
- modules/plugin/gtopo30/src/test/java/org/geotools/gce/gtopo30/GT30ZipWriterTest.java
…ctor doesn't support this type.
> Backport GEOT-5137 to 14.x

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSDataStore.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSDataAccessFactory.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSConfig.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/v1_x/FeatureTypeInfoImpl.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/v1_x/StrictWFS_1_x_Strategy.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/v2_0/FeatureTypeInfoImpl.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/v2_0/StrictWFS_2_0_Strategy.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/WFSDataStoreTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/WFSFeatureStoreTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/WFSLegacyNamingTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/WFSTestData.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/v1_1/GeoServerIntegrationTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/v1_1/MapServerTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/v1_1/TinyOwsTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/v2_0/GeoServerIntegrationTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/v2_0/FeatureTypeInfoImplTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/v2_0/storedquery/ParameterTypeFactoryTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/AbstractWfsDataStoreOnlineTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/MapServerOnlineTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/WFSOnlineTestSupport.java
https://osgeo-org.atlassian.net/browse/GEOT-4883
> WFS Legacy Naming (GEOT-4883)

- modules/library/sample-data/src/main/resources/org/geotools/test-data/xml/capabilities/WFSGetCapsEmptyOnlineResource.xml
- modules/unsupported/wfs/src/main/java/org/geotools/data/wfs/v1_0_0/xml/WFSCapabilitiesComplexTypes.java
- modules/unsupported/wfs/src/test/java/org/geotools/data/wfs/v1_0_0/ParseCapabilitesTest.java
See https://osgeo-org.atlassian.net/browse/GEOT-5458
> [GEOT-5458] WFS 1.0.0 / Tolerate empty OnlineResource.

- modules/plugin/imagepyramid/src/main/java/org/geotools/gce/imagepyramid/ImagePyramidFormat.java
- modules/plugin/imagepyramid/src/main/java/org/geotools/gce/imagepyramid/ImagePyramidFormatFactory.java
- modules/plugin/imagepyramid/src/main/java/org/geotools/gce/imagepyramid/ImagePyramidReader.java
- modules/plugin/imagepyramid/src/main/java/org/geotools/gce/imagepyramid/Utils.java
- modules/plugin/imagepyramid/src/test/java/org/geotools/gce/imagepyramid/ImagePyramidReaderTest.java
- modules/plugin/imagepyramid/src/test/java/org/geotools/gce/imagepyramid/ImagePyramidServiceTest.java
- modules/plugin/imagepyramid/src/test/java/org/geotools/gce/imagepyramid/TestUtils.java
Reformatting the full ImagePyramid module code
> Reformatting the ImagePyramid module code on master

- modules/plugin/imagepyramid/src/main/java/org/geotools/gce/imagepyramid/ImagePyramidFormat.java
- modules/plugin/imagepyramid/src/main/java/org/geotools/gce/imagepyramid/ImagePyramidFormatFactory.java
- modules/plugin/imagepyramid/src/main/java/org/geotools/gce/imagepyramid/ImagePyramidReader.java
- modules/plugin/imagepyramid/src/main/java/org/geotools/gce/imagepyramid/Utils.java
- modules/plugin/imagepyramid/src/test/java/org/geotools/gce/imagepyramid/ImagePyramidReaderTest.java
- modules/plugin/imagepyramid/src/test/java/org/geotools/gce/imagepyramid/ImagePyramidServiceTest.java
- modules/plugin/imagepyramid/src/test/java/org/geotools/gce/imagepyramid/TestUtils.java
Reformatting the ImagePyramid module code on 14.x branch
> Reformatting the ImagePyramid module code on 14.x branch

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/XPath.java
https://osgeo-org.atlassian.net/browse/GEOT-5469
Test coverage is in GeoServer gs-app-schema-test https://github.com/geoserver/geoserver/pull/1730
> [GEOT-5469] Support multivalued xlink:href ClientProperty

- modules/library/main/src/main/java/org/geotools/filter/visitor/ExtractBoundsFilterVisitor.java
- modules/library/main/src/test/java/org/geotools/filter/visitor/ExtractBoundsFilterVisitorTest.java
Signed-off-by: Andrew Hulbert <andrew.hulbert@ccri.com>
> [GEOT-5478] Fix ExtractBoundsFilterVisitor AND'd DURING filters

- modules/library/main/src/main/java/org/geotools/filter/visitor/ExtractBoundsFilterVisitor.java
- modules/library/main/src/test/java/org/geotools/filter/visitor/ExtractBoundsFilterVisitorTest.java
> [GEOT-5478] Fix ExtractBoundsFilterVisitor AND'd DURING filters (15.x backport)

- modules/library/main/src/main/java/org/geotools/filter/visitor/ExtractBoundsFilterVisitor.java
- modules/library/main/src/test/java/org/geotools/filter/visitor/ExtractBoundsFilterVisitorTest.java
Signed-off-by: Andrew Hulbert <andrew.hulbert@ccri.com>
> [GEOT-5478] Fix ExtractBoundsFilterVisitor AND'd DURING filters (14.x backport)

- modules/library/main/src/main/java/org/geotools/filter/function/string/URLEncodeFunction.java
- modules/library/main/src/main/resources/META-INF/services/org.opengis.filter.expression.Function
- modules/library/main/src/test/java/org/geotools/filter/function/string/URLEncodeFunctionTest.java
- Added a filter function to URL encode a string
JIRA Issue: https://osgeo-org.atlassian.net/browse/GEOT-5472
> Add URL encode filter function

- docs/developer/conventions/test/junit.rst
"Lists must always start a new paragraph -- that is, they must appear after a blank line."
http://docutils.sourceforge.net/docs/user/rst/quickstart.html#lists
> Fix list formatting in junit.rst

- modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/BinarySpatialOpTypeBinding.java
- modules/extension/xsd/xsd-fes/src/test/java/org/geotools/filter/v2_0/bindings/FilterTypeBindingTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/v2_0/GeoServerOnlineTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5132
> Wfs-ng: encode spatial filters in wfs 2.0 (GEOT-5132)

- docs/src/main/java/org/geotools/tutorial/feature/Csv2Shape.java
- docs/user/tutorial/quickstart/artifacts/pom.xml
- docs/user/tutorial/quickstart/eclipse.rst
Update the version number to the latest stable/snapshot. Some updates about Eclipse installs. Organized the imports on the Csv2Shape.java
> Updates to the quickstart for the latest release

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/granulecollector/ReprojectingSubmosaicProducer.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/HeterogenousCRSTest.java
Fixed a reference to the local variable that should have been a local variable. Also made the method static since it's really meant to be used statically anyway.
> [GEOT-5489] - NPE when using an interpolation in reprojecting mosaic

- modules/unsupported/swing/src/main/java/org/geotools/swing/styling/JFontChooser.java
For details see https://osgeo-org.atlassian.net/browse/GEOT-5501
> Fix visibility of JFontChooser.showDialog [GEOT-5501]

- docs/user/library/jts/dim9.rst
The removed paragraph appears twice in this document.
> [DOCS] Remove duplicate paragraph in JTS Dimensions

- modules/library/api/src/main/java/org/geotools/geometry/jts/CompoundCurve.java
- modules/library/api/src/test/java/org/geotools/geometry/jts/CurvedGeometryTest.java
fix for https://osgeo-org.atlassian.net/browse/GEOT-5508
see also #1297
> 14.x Fix possible NPE in CompoundCurve [GEOT-5508]

- modules/library/api/src/main/java/org/geotools/geometry/jts/CompoundCurve.java
- modules/library/api/src/test/java/org/geotools/geometry/jts/CurvedGeometryTest.java
fix for https://osgeo-org.atlassian.net/browse/GEOT-5508
see #1297
> 15.x Fix possible NPE in CompoundCurve [GEOT-5508]

- modules/library/main/src/main/java/org/geotools/styling/visitor/Measure.java
- modules/library/main/src/main/java/org/geotools/styling/visitor/RescalingMode.java
- modules/library/main/src/test/java/org/geotools/styling/visitor/DpiRescaleStyleVisitorTest.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/GraphicsAwareDpiRescaleStyleVisitorTest.java
Suggested fix for [GEOT-5519](https://osgeo-org.atlassian.net/browse/GEOT-5519), including test cases.
> [GEOT-5519] Fix graphic size on custom DPIs

- modules/library/xml/src/main/java/org/geotools/xml/xsi/XSISimpleTypes.java
- modules/library/xml/src/test/java/org/geotools/xml/xsi/XSISimpleTypesTest.java
Fix for [GEOT-5506](https://osgeo-org.atlassian.net/browse/GEOT-5506)
> [GEOT-5506]: Specific encoding for XSISimpleTypes.Date and DateTime

- modules/library/xml/src/main/java/org/geotools/xml/gml/GMLComplexTypes.java
- modules/library/xml/src/test/java/org/geotools/xml/gml/GMLComplexTypesTest.java
> [GEOT-5503]: Avoid error through encoding of null geoms, fixed NPE

- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/SDO11OracleDialect.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/SDOOracleDialect.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/sdo/GeometryConverter.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/sdo/SDO.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleGeometryOnlineTest.java
fixes "Oracle DataStore is unable to add empty geometries"
Applies patches provided in #1228 to 14.x branch
> [GEOT-724] backport for 14.x

- modules/library/xml/pom.xml
- modules/library/xml/src/main/java/org/geotools/xml/DocumentFactory.java
- modules/library/xml/src/main/java/org/geotools/xml/XMLHandlerHints.java
- modules/library/xml/src/main/java/org/geotools/xml/XMLSAXHandler.java
- modules/library/xml/src/main/java/org/geotools/xml/handlers/ComplexElementHandler.java
- modules/library/xml/src/main/java/org/geotools/xml/handlers/DocumentHandler.java
- modules/library/xml/src/main/java/org/geotools/xml/handlers/ElementHandlerFactory.java
- modules/library/xml/src/test/java/org/geotools/xml/DocumentFactoryTest.java
- pom.xml
See: https://osgeo-org.atlassian.net/browse/GEOT-5514
This is a followup/replacement to #1302 by @aaronwaddell.
> GEOT-5514: Disabled DTD's in gt-xml to protect against XEE attacks

- modules/plugin/coverage-multidim/grib/src/test/java/org/geotools/coverage/io/grib/GribTest.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReaderSpi.java
https://osgeo-org.atlassian.net/browse/GEOT-5524
This pull request targets master.
> [GEOT-5524] Incorrect detection of GRIB files with WMO header (master)

- modules/plugin/coverage-multidim/grib/src/test/java/org/geotools/coverage/io/grib/GribTest.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReaderSpi.java
https://osgeo-org.atlassian.net/browse/GEOT-5524
This pull request targets 15.x.
> [GEOT-5524] Incorrect detection of GRIB files with WMO header (15.x)

- modules/extension/wms/src/main/java/org/geotools/data/wms/WMS1_0_0.java
- modules/extension/wms/src/main/java/org/geotools/data/wms/WMS1_1_0.java
- modules/extension/wms/src/main/java/org/geotools/data/wms/WebMapServer.java
- modules/extension/wms/src/main/java/org/geotools/data/wms/response/DescribeLayerResponse.java
- modules/extension/wms/src/main/java/org/geotools/data/wms/response/WMSGetCapabilitiesResponse.java
- modules/extension/wms/src/test/java/org/geotools/data/wms/test/EntityResolverTest.java
- modules/extension/wms/src/test/java/org/geotools/data/wms/test/GetCapabilitiesRequestTest.java
- modules/extension/wms/src/test/java/org/geotools/data/wms/test/NoExternalEntityResolver.java
- modules/extension/wms/src/test/resources/org/geotools/data/wms/test/test-data/1.1.1Capabilities-xxe.xml
- modules/extension/wms/src/test/resources/org/geotools/data/wms/test/test-data/1.3.0Capabilities-xxe.xml
- modules/library/main/src/main/java/org/geotools/data/ows/AbstractOpenWebService.java
- modules/library/main/src/main/java/org/geotools/data/ows/AbstractRequest.java
- modules/library/main/src/main/java/org/geotools/data/ows/Request.java
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/v2_0/StrictWFS_2_0_Strategy.java
- modules/unsupported/wps/src/main/java/org/geotools/data/wps/WPS1_0_0.java
- modules/unsupported/wps/src/main/java/org/geotools/data/wps/response/WPSGetCapabilitiesResponse.java
> GEOT-5514, make the xml configuration actually configurable

- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDataStoreOnlineTest.java
- modules/unsupported/geopkg/src/test/java/org/geotools/geopkg/GeoPkgFeatureStoreTestSetup.java
Attempt to fix failing Oracle Test
> try to fix fail in LongVarTest

- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDataStoreOnlineTest.java
solve problem preventing tests running twice
> delete table after use in LongVar test

- modules/library/api/src/main/java/org/geotools/styling/PolygonSymbolizer.java
- modules/library/main/src/main/java/org/geotools/styling/visitor/UomRescaleStyleVisitor.java
- modules/library/main/src/test/java/org/geotools/styling/visitor/UomRescaleStyleVisitorTest.java
https://osgeo-org.atlassian.net/browse/GEOS-7576
> [GEOS-7576] Make rescale visitors rescale polygons graphic-margin parameter (backport 14.x)

- modules/library/api/src/main/java/org/geotools/styling/PolygonSymbolizer.java
- modules/library/main/src/main/java/org/geotools/styling/visitor/UomRescaleStyleVisitor.java
- modules/library/main/src/test/java/org/geotools/styling/visitor/UomRescaleStyleVisitorTest.java
https://osgeo-org.atlassian.net/browse/GEOS-7576
> [GEOS-7576] Make rescale visitors rescale polygons graphic-margin parameter (backport 15.x)

- modules/library/api/src/main/java/org/geotools/styling/PolygonSymbolizer.java
- modules/library/main/src/main/java/org/geotools/styling/visitor/UomRescaleStyleVisitor.java
- modules/library/main/src/test/java/org/geotools/styling/visitor/UomRescaleStyleVisitorTest.java
https://osgeo-org.atlassian.net/browse/GEOS-7576
> [GEOS-7576] Make rescale visitors rescale polygons graphic-margin parameter

- modules/extension/complex/src/test/java/org/geotools/filter/function/AttributeCountFunctionTest.java
- modules/library/main/src/main/java/org/geotools/filter/function/AttributeCountFunction.java
- modules/library/main/src/main/resources/META-INF/services/org.opengis.filter.expression.Function
https://osgeo-org.atlassian.net/browse/GEOT-5541
So I made the function in main, but the test resides in gt-complex because it needs some dependencies there. There are extra tests in geoserver with app-schema config, but I'll push that after this one is accepted. Thanks.
> GEOT-5541: Create a function to return number of complex attributes

- modules/extension/app-schema/app-schema/pom.xml
- modules/plugin/imagemosaic/pom.xml
- modules/unsupported/solr/pom.xml
- pom.xml
See the mailing list for more details: https://www.mail-archive.com/geotools-devel@lists.sourceforge.net/msg37155.html
This should be ported to  the 16.x branch before the 16.0 release.
> Replace commons-beanutils-1.7.0 with 1.9.2-noclassprop

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AbstractMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureIteratorFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureSource.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/NestedAttributeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/FeatureChainedAttributeVisitor.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/UnmappingFilterVisitor.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningNestedAttributeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/filter/NestedAttributeExpression.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/JoiningJDBCFeatureSource.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/NamespaceAwareAttributeRenameVisitor.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/NestedFilterToSQL.java
- modules/extension/complex/src/main/java/org/geotools/data/complex/filter/XPathUtil.java
- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/DuplicatingFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/PostPreProcessFilterSplittingVisitor.java
Related JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-5526
Related ML discussion:
http://osgeo-org.1560.x6.nabble.com/App-Schema-Encoding-of-Filters-on-Nested-Attributes-td5285165.html
Unit tests and docs will be added in a separate GeoServer PR.
> [GEOT-5526] Apps-Schema: Native Encoding  of Nested Filters

- modules/extension/app-schema/app-schema/pom.xml
- modules/plugin/imagemosaic/pom.xml
- modules/unsupported/solr/pom.xml
- pom.xml
> Replace commons-beanutils-1.7.0 with 1.9.2-noclassprop (16.x)

- modules/library/coverage/src/main/java/org/geotools/coverage/grid/GridCoverageFactory.java
- modules/library/coverage/src/test/java/org/geotools/coverage/grid/GridCoverageFactoryTest.java
Added null checks on culprit methods.
PS apologies for the misfire pull requests.  I'm still learning git.
> [GEOT-5544] GridCoverageFactory throws NullPointerException on arg

- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicEgrTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5545
> [GEOT-5545] ImageMosaicEgrTest failures on OpenJDK

- modules/library/main/src/main/java/org/geotools/filter/function/StaticGeometry.java
- modules/library/main/src/test/java/org/geotools/filter/function/StaticGeometryTest.java
Same changes offered in pull request #1359 but I have not attempted to fix the non-adherence to the coding standards found in the remainder of the file.
> [GEOS-7768] Filter function "greaterEqualThan" is not properly working

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AbstractMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureIteratorFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureSource.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/NestedAttributeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/FeatureChainedAttributeVisitor.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/UnmappingFilterVisitor.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningNestedAttributeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/filter/NestedAttributeExpression.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/JoiningJDBCFeatureSource.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/NamespaceAwareAttributeRenameVisitor.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/NestedFilterToSQL.java
- modules/extension/complex/src/main/java/org/geotools/data/complex/filter/XPathUtil.java
- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/DuplicatingFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/PostPreProcessFilterSplittingVisitor.java
Straightforward backport of #1319 to Geotools 15.x.
> [GEOT-5526] App-Schema: Native Encoding of Nested Filters

- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/HeterogenousCRSTest.java
This will skip the test for now when the expected CRS isn't found. Hopefully will add proper fix in the next release.
> Added a workaround for the reprojecting mosaic test failing

- modules/library/referencing/src/main/resources/META-INF/services/org.geotools.referencing.operation.MathTransformProvider
- modules/library/referencing/src/test/java/org/geotools/referencing/CrsTest.java
JIRA:
https://osgeo-org.atlassian.net/browse/GEOT-5559
Mailinglist:
http://osgeo-org.1560.x6.nabble.com/CRS-parseText-fails-for-WagnerV-WKT-td5292926.html
> Add WagnerV SPI entry to get CRS.parseText working with WagnerV WKT

- CONTRIBUTING.md
After discussion with Andrea, I suggest the following wording change to the contribution agreement would better reflect the desires of the developers.
> Amended contribution guidelines as suggested by Andrea

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureReader.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCUpdateFeatureWriter.java
"boolean isDirty(int index)" method already exists.
it appears that method overloading is intended.
also, fixed spacing.
> Name of isDirrty method seems like typing mistake

- modules/library/main/src/main/java/org/geotools/data/DataUtilities.java
- modules/library/main/src/main/java/org/geotools/styling/DefaultResourceLocator.java
- modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
- modules/library/main/src/test/java/org/geotools/styling/DefaultResourceLocatorTest.java
See:
- https://osgeo-org.atlassian.net/browse/GEOT-5579
- https://osgeo-org.atlassian.net/browse/GEOS-7861
> Allow DataUtilities.urlToFile and DefaultResourceLocator to respect URL query [GEOT-5579]

- modules/library/coverage/src/main/java/org/geotools/resources/image/ExtendedImageParam.java
- modules/library/coverage/src/main/java/org/geotools/resources/image/ImageUtilities.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFResponse.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReader.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java
Reverts geotools/geotools#1393
> Revert "[GEOT-5580] Use imageio EnhancedImageReadParam instead of ExtendedImageParam (backport 16.x)"

- modules/library/coverage/src/main/java/org/geotools/resources/image/ExtendedImageParam.java
- modules/library/coverage/src/main/java/org/geotools/resources/image/ImageUtilities.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFResponse.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReader.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java
Reverts geotools/geotools#1392
> Revert "[GEOT-5580] Use imageio EnhancedImageReadParam instead of ExtendedImageParam"

- modules/library/coverage/src/main/java/org/geotools/resources/image/ExtendedImageParam.java
- modules/library/coverage/src/main/java/org/geotools/resources/image/ImageUtilities.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFResponse.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReader.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java
Reverts geotools/geotools#1399
> [GEOT-5580] Use imageio EnhancedImageReadParam instead of ExtendedImageParam (backport 16.x)

- modules/library/coverage/src/main/java/org/geotools/resources/image/ExtendedImageParam.java
- modules/library/coverage/src/main/java/org/geotools/resources/image/ImageUtilities.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFResponse.java
- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReader.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java
Reverts geotools/geotools#1400
> [GEOT-5580] Use imageio EnhancedImageReadParam instead of ExtendedImageParam

- modules/extension/xsd/xsd-core/pom.xml
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/Schemas.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xml/SchemasTest.java
- modules/extension/xsd/xsd-core/src/test/resources/org/geotools/xml/remoteSchemaLocation.xsd
Pull request for [GEOT-5568](https://osgeo-org.atlassian.net/browse/GEOT-5568)
> [GEOT-5568] Avoid deadlocks on schema loading

- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCTransactionStateTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5603
> [GEOT-5603] Intermittent build failure with UnfinishedStubbingException in JDBCTransactionStateTest (master)

- modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/geotiff/CRS2GeoTiffMetadataAdapter.java
- modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/geotiff/GeoTiffMetadata2CRSAdapter.java
- modules/library/referencing/src/main/java/org/geotools/referencing/operation/projection/AzimuthalEquidistant.java
- modules/library/referencing/src/test/java/org/geotools/referencing/operation/projection/AzimuthalEquidistantTest.java
- modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffWriterTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5595
Note that this PR depends on and incorporates the commit in https://github.com/geotools/geotools/pull/1421
> [GEOT-5595] Cannot read/write GeoTIFF with Azimuthal_Equidistant projection (master)

- modules/library/metadata/src/main/java/org/geotools/util/SoftValueHashMap.java
- modules/library/metadata/src/test/java/org/geotools/util/SoftValueHashMapTest.java
Reverts geotools/geotools#1424
> Revert "[GEOT-5602] Better concurrent SoftValueHashMap"

- modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java
- modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderTest.java
[Issue: GEOT-3318](https://osgeo-org.atlassian.net/browse/GEOT-3318)
> [GEOT-3318] Added support for reading from InputStream with GeoTiffReader.

- docs/src/main/java/org/geotools/tutorial/raster/ImageLab.java
While this fixes the reported problem, it would be good if the GeoTiff reader
could take care of this for itself.
> Fix for GEOT-5265 Some GeoTiffs don't open

- modules/plugin/imageio-ext-gdal/pom.xml
Backport of [this PR](https://github.com/geotools/geotools/pull/1469)
> [GEOT-5636] fixed imageio-ext-gdalgeotiff.jar classpath conflicts

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/JoiningJDBCFeatureSource.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCCallbackFactory.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStoreFactory.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureReader.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureSource.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureStore.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCInsertFeatureWriter.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCJNDIDataStoreFactory.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCJoiningFeatureReader.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCReaderCallback.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCUpdateFeatureWriter.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCUpdateInsertFeatureWriter.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCDataStoreTest.java
See https://github.com/geotools/geotools/wiki/JDBC-Callbacks
> GEOT-5639: Adding ability to plug in callback interfaces for JDBC classes.

- modules/library/xml/src/main/java/org/geotools/xml/filter/FilterCompliancePreProcessor.java
- modules/library/xml/src/test/java/org/geotools/xml/filter/FilterCompliancePreProcessorTest.java
Unit test and fix for GEOT-5537 added: pass NOT filtertype to createHighLevelLogicFilter() method instead of AND.
Backport for 16.x branch.
> [GEOT-5537] Backport for 16.x

- modules/library/referencing/src/main/java/org/geotools/referencing/operation/projection/Mollweide.java
- modules/library/referencing/src/test/java/org/geotools/referencing/operation/projection/MollweideProviderTest.java
- modules/library/referencing/src/test/resources/org/geotools/referencing/test-data/scripts/Mollweide.txt
[GEOT-5641] Mollweide projection misses parameter
> [GEOT-5641] Mollweide projection misses parameter

- modules/library/referencing/src/main/java/org/geotools/referencing/factory/URN_Parser.java
- modules/library/referencing/src/test/java/org/geotools/referencing/factory/URN_ParserTest.java
See https://osgeo-org.atlassian.net/browse/GEOT-1710 for details.
> [GEOT-1710] Urn parser update for new OGC codes

- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFPolyphemusTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5675
> GEOT-5675: Division by zero in NetCDFPolyphemusTest

- modules/library/main/src/main/java/org/geotools/data/collection/ListFeatureCollection.java
- modules/library/main/src/test/java/org/geotools/data/collection/ListFeatureCollectionTest.java
Ensure that correct bounding boxes are retained after deleting and adding a feature.
For more details:
- https://osgeo-org.atlassian.net/browse/GEOT-5684
> [GEOT-5684] List Feature collection bounding box fixes

- modules/library/data/src/main/java/org/geotools/data/memory/MemoryFeatureStore.java
- modules/library/data/src/main/java/org/geotools/data/memory/MemoryFeatureWriter.java
Reinstates ability to preserve feature ID's.
For more information - https://osgeo-org.atlassian.net/browse/GEOT-5683
> [GEOT-5683] fix MemoryFeature Store & Writer to preserve IDs

- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/PointStackerProcess.java
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/PointStackerProcessTest.java
For the gs:pointStacker I have supplimented the list of fileds sent as attribute with envBBOX(java representations of Envelope), jsonBBOX (json like type) and geomBBOX (Geometry type)
> [GEOT-5654] gs:PointStacker added an attribute that holds the bounding box of the clustered features

- modules/unsupported/geojson/src/main/java/org/geotools/geojson/geom/GeometryCollectionHandler.java
- modules/unsupported/geojson/src/test/java/org/geotools/geojson/FeatureJSONTest.java
- modules/unsupported/geojson/src/test/java/org/geotools/geojson/GeometryJSONTest.java
Fixed GeoJSON parsing problem for a GeometryCollection when a geometry in "geometries" has it's "type" value listed after "coordinates". See https://osgeo-org.atlassian.net/browse/GEOT-5687
> Fixed Jira issue GEOT-5687 - GeoJSON/GeometryCollection parsing issue

- modules/library/xml/src/main/java/org/geotools/xml/handlers/xsi/ElementTypeHandler.java
- modules/library/xml/src/test/java/org/geotools/xml/handlers/xsi/ElementTypeHandlerTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5703
> [GEOT-5703] Incorrect validation when parsing XML schema element declaration with ref attribute (master)

- modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_listMultiply.java
- modules/library/main/src/main/java/org/geotools/styling/visitor/RescaleStyleVisitor.java
- modules/library/main/src/main/java/org/geotools/styling/visitor/UomRescaleStyleVisitor.java
- modules/library/main/src/main/resources/META-INF/services/org.opengis.filter.expression.Function
- modules/library/main/src/test/java/org/geotools/filter/function/FilterFunction_listMultiplyTest.java
- modules/library/main/src/test/java/org/geotools/styling/SLDStyleTest.java
- modules/library/main/src/test/java/org/geotools/styling/visitor/RescaleStyleVisitorTest.java
- modules/library/main/src/test/java/org/geotools/styling/visitor/UomRescaleStyleVisitorTest.java
- modules/library/main/src/test/resources/org/geotools/styling/test-data/dasharray3_dynamic.sld
- modules/library/render/src/main/java/org/geotools/renderer/style/DynamicLineStyle2D.java
- modules/library/render/src/main/java/org/geotools/renderer/style/SLDStyleFactory.java
Hopefully I have adressed all complaints about the older pull request (#1467). 
Now the PR is against master.
I have removed all formatting issues (that was hard).
I have as far as I see it now a more general version.
> [GEOT-5623]: dynamic stroke-dasharray improvements

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSDataStoreFactory.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/WFSDataStoreFactoryTest.java
Pull request for [GEOT-5698](https://osgeo-org.atlassian.net/browse/GEOT-5698)
> [GEOT-5698] Forward gzip settings to HTTPClient

- modules/library/cql/src/main/java/org/geotools/filter/text/commons/ExpressionToText.java
- modules/library/cql/src/test/java/org/geotools/filter/text/ecql/ECQLTest.java
See https://osgeo-org.atlassian.net/browse/GEOT-5704
> Correct CQL encoding for color literals [GEOT-5704]

- modules/library/referencing/src/main/java/org/geotools/geometry/GeometryBuilder.java
- modules/unsupported/geometry/src/test/java/org/geotools/geometry/iso/primitive/CurveTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5571
> [GEOT-5571]createCurve method always makes cycle

- modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBFunction.java
- modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/parse/FunctionParseTest.java
- modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/parse/MBFunctionTest.java
- modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/parse/MBStyleTestUtils.java
- modules/unsupported/mbstyle/src/test/resources/org/geotools/mbstyle/functionParseTest.json
Tests and implements interval functions in Mapbox GL style language (Unsupported module).
> MBStyles, interval functions.

- docs/src/main/java/org/geotools/tutorial/style/StyleLab.java
- docs/user/artifacts/xml/pom2.xml
- docs/user/library/cql/faq.rst
- docs/user/library/data/export.rst
- docs/user/library/xml/internal/tutorial.rst
- docs/user/tutorial/datastore/source.rst
- docs/user/tutorial/feature/artifacts/pom.xml
- docs/user/tutorial/feature/csv2shp.rst
- docs/user/tutorial/filter/artifacts/pom.xml
- docs/user/tutorial/geometry/artifacts/pom.xml
- docs/user/tutorial/geometry/geometrycrs.rst
- docs/user/tutorial/map/artifacts/pom.xml
- docs/user/tutorial/map/style.rst
- docs/user/tutorial/quickstart/maven.rst
- docs/user/tutorial/raster/artifacts/pom.xml
I have added the repositories back into the tutorial poms **AGAIN** removing them breaks the docs and prevents new users making use of them. Please stop deleting them!!!!
> Docs fix so they build

- modules/extension/xsd/xsd-sld/src/test/java/org/geotools/sld/SLDTest.java
- modules/library/main/src/main/java/org/geotools/styling/SLDParser.java
- modules/library/main/src/test/java/org/geotools/styling/SLDTransformerTest.java
See https://osgeo-org.atlassian.net/browse/GEOT-5726
> [GEOT-5726] Parse an empty CSSParameter as an empty string instead of null

- modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_equalTo.java
Working at CalGIS code sprint learning pull requests.
> Filing in metadata for function equalsTo

- modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_contains.java
Adding code comments to "contains" function
> Adding comments for function 'Contains'

- docs/developer/conventions/code/url.rst
- docs/src/main/java/org/geotools/cql/DataExamples.java
- docs/src/main/java/org/geotools/data/DataExamples.java
- docs/user/library/data/internal.rst
- docs/user/library/main/data.rst
- docs/user/library/metadata/index.rst
- docs/user/library/metadata/urls.rst
- docs/user/library/xml/resolving.rst
- modules/library/main/src/main/java/org/geotools/data/DataUtilities.java
- modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
- modules/library/metadata/src/main/java/org/geotools/util/URLs.java
- modules/library/metadata/src/test/java/org/geotools/util/URLsTest.java
- modules/library/referencing/src/main/java/org/geotools/referencing/factory/gridshift/DataUtilities.java
https://osgeo-org.atlassian.net/browse/GEOT-5740
> [GEOT-5740] Move DataUtilities URL methods to new URLs class in gt-metadata (master)

- modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/layer/SymbolMBLayer.java
- modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/SymbolMBLayerTest.java
- modules/unsupported/mbstyle/src/test/resources/org/geotools/mbstyle/symbolTextLinePlacementTest.json
Add text max angle and test to mbstyles.
> Mbstyle max angle

- pom.xml
https://osgeo-org.atlassian.net/browse/GEOT-5741
Discussion: http://osgeo-org.1560.x6.nabble.com/upgrade-postgresql-JDBC-driver-to-42-1-1-full-binary-xfer-td5322195.html
> [GEOT-5741] Upgrade PostgreSQL JDBC driver to 42.1.1 (master)

- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
- https://osgeo-org.atlassian.net/browse/GEOT-5706
- https://osgeo-org.atlassian.net/browse/GEOT-5672
Some test cases were copied from this pull request: https://github.com/geotools/geotools/pull/1499
> [GEOT-5706] [GEOT-5672] Improve MongoDB literals handling

- modules/library/main/src/main/java/org/geotools/util/CommonsConverterFactory.java
- modules/library/main/src/main/java/org/geotools/util/DataUrlConnection.java
- modules/library/main/src/main/java/org/geotools/util/DataUrlHandler.java
- modules/library/main/src/test/java/org/geotools/util/CommonsConverterFactoryTest.java
- modules/library/main/src/test/java/org/geotools/util/DataUrlHandlerTest.java
I tried to use the generic jdk mechanism to support custom protocols, but that is unusable when working in a servlet environment with eg. Tomcat or Jetty.
> [GEOT-5754] Support data uris as external graphics

- modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/layer/SymbolMBLayer.java
- modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBFunction.java
- modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBObjectParser.java
- modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBObjectStops.java
- modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/SymbolMBLayerTest.java
- modules/unsupported/mbstyle/src/test/resources/org/geotools/mbstyle/textFontFamilyTest.json
added functions for font to MBfunction and MBObject parser
debugging new implementations of text-font
more testing
updated test file and removed extranious textExpression logic
Added initial testing
working tested text-font for first-font in array
> Implementing text-font interval stop functionality for MBSymbolLayer

- modules/library/main/src/main/java/org/geotools/filter/temporal/BinaryTemporalOperatorImpl.java
- modules/library/main/src/main/java/org/geotools/temporal/object/DefaultInstant.java
- modules/library/main/src/main/java/org/geotools/temporal/object/DefaultPeriod.java
- modules/library/main/src/main/java/org/geotools/temporal/object/DefaultPosition.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/AfterImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/BeforeImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/BeginsImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/BegunByImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/DuringImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/EndedByImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/EndsImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/MeetsImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/MetByImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/OverlappedByTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/TContainsImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/TEqualsImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/TOverlapsImplTest.java
backport https://github.com/geotools/geotools/pull/1628 to 16.x
> [GEOT-5232] Added a toString method for temporal filters. (16.x backport)

- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCNotBinding.java
- modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/FilterMockData.java
- modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/NotBindingTest.java
> [GEOT-5697] fix encoding the filter Not( is null ) as XML (17.x backport)

- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCNotBinding.java
- modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/FilterMockData.java
- modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/NotBindingTest.java
> [GEOT-5697] fix encoding the filter Not( is null ) as XML (16.x backport)

- modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/SymbolMBLayerTest.java
Testing for text-rotate and text-max-width
Cleaned up testing, removed unused test file.
> Testing for text-rotate and text-max-width

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AbstractMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccessFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingAttributeIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureCollection.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureIteratorFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/NestedAttributeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/XmlMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/DataAccessMap.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningNestedAttributeMapping.java
- modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/FeatureChainingTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5748
Backport to GeoTools 17.x (stable).
> [GEOT-5748] Improvements to App-Schema's connection usage

- modules/extension/xsd/xsd-fes/src/main/resources/org/geotools/filter/v2_0/filter.xsd
https://osgeo-org.atlassian.net/browse/GEOT-5343
Unit test coverage in https://github.com/geoserver/geoserver/pull/2476.
> [GEOT-5343] Support matchCase on PropertyIsLike in Filter 2.0

- docs/src/main/java/org/geotools/tutorial/style/StyleLab.java
- docs/user/library/cql/faq.rst
- docs/user/library/data/export.rst
- docs/user/library/xml/internal/tutorial.rst
- docs/user/tutorial/datastore/source.rst
- docs/user/tutorial/feature/csv2shp.rst
- docs/user/tutorial/filter/query.rst
- docs/user/tutorial/geometry/geometrycrs.rst
- docs/user/tutorial/map/style.rst
- docs/user/tutorial/quickstart/maven.rst
- docs/user/tutorial/raster/image.rst
Backport of doc fixes from Master and 17.x for release
> make docs compile!

- modules/library/main/src/main/java/org/geotools/filter/temporal/BinaryTemporalOperatorImpl.java
- modules/library/main/src/main/java/org/geotools/temporal/object/DefaultInstant.java
- modules/library/main/src/main/java/org/geotools/temporal/object/DefaultPeriod.java
- modules/library/main/src/main/java/org/geotools/temporal/object/DefaultPosition.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/AfterImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/BeforeImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/BeginsImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/BegunByImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/DuringImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/EndedByImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/EndsImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/MeetsImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/MetByImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/OverlappedByTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/TContainsImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/TEqualsImplTest.java
- modules/library/main/src/test/java/org/geotools/filter/temporal/TOverlapsImplTest.java
backport https://github.com/geotools/geotools/pull/1628 to 17.x
> [GEOT-5232] Added a toString method for temporal filters. (17.x backport)

- modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_equalTo.java
- modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_greaterEqualThan.java
- modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_greaterThan.java
Changes to metadata for filtering functions.
> Function metadata for equalTo, greaterEqualThan, greaterThan

- modules/extension/xsd/xsd-gml3/pom.xml
https://osgeo-org.atlassian.net/browse/GEOS-8239
Deploy gt-xsd-gml3 tests and test sources so that GeoServer gs-geofence-server tests can depend on gt-xsd-gml3 tests.
> GEOS-8239 Deploy xsd-gml3 tests jar

- modules/plugin/feature-pregeneralized/src/main/java/org/geotools/data/gen/PreGeneralizedFeatureSource.java
The code is logging at warn/info level messages that are debug support, should be at "fine" level instead
> [GEOT-5797] Pre-generalized data store spams the log with WARN messages when wrapping JDBC data store

- modules/unsupported/mongodb/pom.xml
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureStore.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceVisitorTest.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoTestSupport.java
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
* Sort and limit query to handle Min/Max Visitor. This will prevent both visitors
from looping the entire collection to find these values.
> [GEOT-5716] MongoFeatureSource to handle Min/Max Visitor

- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/crs/NetCDFProjection.java
NetCDF tests fail with NPE if run with fine logging turned on. 
[GEOT-5828](https://osgeo-org.atlassian.net/browse/GEOT-5828)
> GEOT-5828 fix NPE when fine logging on

- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/XsDateTimeFormat.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xml/impl/XsDateTimeFormatTest.java
This PR allows the XSDateTimeFormat to read dates that have been serialized using Date.toString().
> [GEOT-5848] Fix for GEOS-8150 and make WPS status cleaning work

- docs/user/library/referencing/compare.rst
fixed out of date example of how to compare without metadata
> updated ignore metadata compare

- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java
- modules/plugin/geopkg/src/main/resources/org/geotools/geopkg/gpkg_metadata.sql
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgSchemaTest.java
Should fix GeoServer CITE failures for GeoPackage (ETS-10).
@aaime should fix https://osgeo-org.atlassian.net/browse/GEOT-5546 which is the same as the tiles part of GEOT-5836.
> [GEOT-5836] Update GeoPackage table schemas to match spec.

- modules/library/data/src/main/java/org/geotools/data/memory/MemoryDataStore.java
- modules/library/data/src/test/java/org/geotools/data/memory/MemoryDataStoreTest.java
This should address https://osgeo-org.atlassian.net/browse/GEOT-5841.
> [GEOT-5841] Fix "addFeatures(FeatureCollection)" to iterate over features

- modules/library/main/src/main/java/org/geotools/util/CommonsConverterFactory.java
- modules/library/main/src/main/java/org/geotools/util/DataUrlConnection.java
- modules/library/main/src/main/java/org/geotools/util/DataUrlHandler.java
- modules/library/main/src/test/java/org/geotools/util/CommonsConverterFactoryTest.java
- modules/library/main/src/test/java/org/geotools/util/DataUrlHandlerTest.java
> [GEOT-5754] Support data uris as external graphics 

- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/DOMParser.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/Parser.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/ElementHandlerImpl.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/ParseExecutor.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/ParserHandler.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSAnyTypeBinding.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xml/FacetTest.java
- modules/extension/xsd/xsd-core/src/test/resources/org/geotools/xml/whitespace-cdata.xml
- modules/extension/xsd/xsd-wfs/src/test/resources/org/geotools/wfs/bindings/test-data/QueryTypeBindingTest.xml
- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/DescribeFeatureTypeResponseFactory.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/WFSClientTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/AbstractWfsDataStoreOnlineTest.java
Reverts geotools/geotools#1729 until issues in GeoServer can be solved
> Revert "[GEOS-8227] - improve whitespace handling in XML Parser"

- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCTransactionStateTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5869
> [GEOT-5869] Intermittent failure of JDBCTransactionStateTest caused by finalizer logging

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/UnmappingFilterVisitor.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/spi/CustomAttributeExpressionFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/spi/CustomImplementationsFinder.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/spi/CustomMappingFactory.java
- modules/unsupported/mongodb/pom.xml
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/AbstractCollectionMapper.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeature.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoInferredMapper.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/CollectionIdFunction.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/CollectionLinkFunction.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectAllFunction.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectFunction.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoCollectionFeature.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedAttributeExpressionFactory.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedMapping.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedMappingFactory.java
- modules/unsupported/mongodb/src/main/resources/META-INF/services/org.geotools.data.complex.spi.CustomAttributeExpressionFactory
- modules/unsupported/mongodb/src/main/resources/META-INF/services/org.geotools.data.complex.spi.CustomMappingFactory
- modules/unsupported/mongodb/src/main/resources/META-INF/services/org.geotools.filter.FunctionExpression
- modules/unsupported/mongodb/src/main/resources/META-INF/services/org.opengis.filter.expression.Function
- modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
- https://osgeo-org.atlassian.net/browse/GEOT-5690
- https://osgeo-org.atlassian.net/browse/GEOT-5706
- https://osgeo-org.atlassian.net/browse/GEOT-5672
Backport of this pull requests:
- https://github.com/geotools/geotools/pull/1546
- https://github.com/geotools/geotools/pull/1555
Mailing list discussion:
- https://sourceforge.net/p/geotools/mailman/message/36113756/
> Backport of MongoDB integration with App-Schema to 17.x

- modules/library/main/src/main/java/org/geotools/util/CommonsConverterFactory.java
- modules/library/main/src/test/java/org/geotools/util/CommonsConverterFactoryTest.java
It would be great to inject the date formats via Spring, but... is GeoTools using Spring at all?
> Added ISO-8601 dates to CommonsConverterFactory

- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/NestedCollectionLinkFunction.java
Backport of this PR: https://github.com/geotools/geotools/pull/1737
> [GEOT-5866] MongoDB integration with App-Schema nested mappings are not evaluated relatively (backport 17.x)

- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/CollectionIdFunction.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectFunction.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoCollectionFeature.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedAttributeExpressionFactory.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedMapping.java
- modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/NestedCollectionLinkFunction.java
- modules/unsupported/mongodb/src/main/resources/META-INF/services/org.geotools.filter.FunctionExpression
- modules/unsupported/mongodb/src/main/resources/META-INF/services/org.opengis.filter.expression.Function
Backport of this PR: https://github.com/geotools/geotools/pull/1737
> [GEOT-5866] MongoDB integration with App-Schema nested mappings are not evaluated relatively (backport 18.x)

- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReader.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFStationsTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5873
> [GEOT-5873]: Fix netcdf tests failures on Windows

- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/SchemaIndexImpl.java
Per Ben's note on https://github.com/geotools/geotools/pull/1756
> fix formatting

- modules/library/referencing/pom.xml
- modules/library/referencing/src/main/java/org/geotools/referencing/operation/matrix/GeneralMatrix.java
- modules/library/referencing/src/main/java/org/geotools/referencing/operation/matrix/Matrix2.java
- modules/library/referencing/src/main/java/org/geotools/referencing/operation/matrix/Matrix3.java
- pom.xml
Fix for https://osgeo-org.atlassian.net/browse/GEOT-5300
Upgrade to EJML 0.32
> [GEOT-5300] Upgrade to EJML 0.32

- docs/user/library/render/style.rst
This PR fixes the broken links to the GeoServer SLD cookbook.
> Fix broken links to GeoServer SLD cookbook

- modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/footprint/FootprintBehavior.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicFootprintsTest.java
Full local builds passing in both geotools and geoserver
> [GEOT-5912] Image mosaic: set ROI on blank responses when footprint management is on

- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/Encoder.java
- modules/extension/xsd/xsd-core/src/test/java/org/geotools/xml/EncoderTest.java
Pull request for [GEOT-5902](https://osgeo-org.atlassian.net/browse/GEOT-5902)
> [GEOT-5902] Fixed Encoder setters

- docs/developer/procedures/release.rst
Update the release guide to fix Jenkins URL, Jira instructions, and Blogger URL.
> Update the release guide

- docs/user/geotools.rst
- modules/library/main/src/main/java/org/geotools/feature/type/AnnotationFeatureType.java
One little part in docs, one bad logger entry.
> Remove legacy VPF entries.

- modules/library/render/src/main/java/org/geotools/renderer/label/LabelCacheImpl.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java
- modules/library/render/src/test/java/org/geotools/renderer/label/LabelCacheImplTest.java
painting behaviour (Backporting to 16.x)
> GEOT-5903: allow extending LabelCacheImpl to implement custom label

- modules/library/main/src/test/java/org/geotools/styling/SLDTransformerTest.java
Java 8 and Java 9 do pretty-print slightly differently (The XML is still functionally identical); this makes the SLDTranformer tests function at both language levels.
> Make SLDTransformer test compatible with Java <= 8 and Java 9

- pom.xml
This is needed to solve: https://github.com/geosolutions-it/jai-ext/issues/175
> GEOT-5925: updated jai-ext to 1.0.19

- modules/extension/wms/src/main/java/org/geotools/map/WMSCoverageReader.java
- modules/extension/wms/src/main/java/org/geotools/map/WMSLayer.java
- modules/extension/wms/src/test/java/org/geotools/map/WMSLayerTest.java
- modules/extension/wms/src/test/resources/org/geotools/map/caps110.xml
- modules/extension/wms/src/test/resources/org/geotools/map/caps130.xml
An improvement to allow WMSLayer objects have a specified style.
> GEOT-5926:Allow WMSLayers to have styles

- docs/user/unsupported/arcgis-rest.rst
- docs/user/unsupported/index.rst
- Added ArcGIS ReST API module documentation
> Added ArcGIS ReST API module documentation

- modules/extension/tile-client/src/main/java/org/geotools/tile/impl/osm/OSMTileFactory.java
- modules/extension/tile-client/src/test/java/org/geotools/tile/impl/osm/OSMTileFactoryTest.java
> GEOT-5938 OSMTileFactory can throw an exception when looking for the TopLeft tile

- modules/library/main/pom.xml
- modules/library/main/src/main/java/org/geotools/data/ows/ServiceExceptionParser.java
- modules/library/main/src/test/java/org/geotools/data/ows/ServiceExceptionParserTest.java
- modules/library/main/src/test/resources/org/geotools/data/ows/secret.txt
> Disable external entity expansion when parsing service exceptions, GEOT-5953 backport to 19.x

- modules/library/main/pom.xml
- modules/library/main/src/main/java/org/geotools/data/ows/ServiceExceptionParser.java
- modules/library/main/src/test/java/org/geotools/data/ows/ServiceExceptionParserTest.java
- modules/library/main/src/test/resources/org/geotools/data/ows/secret.txt
> Disable external entity expansion when parsing service exceptions, GEOT-5953 Backport to 18.x

- modules/library/main/src/main/java/org/geotools/filter/Capabilities.java
- modules/library/main/src/main/java/org/geotools/filter/capability/FilterCapabilitiesImpl.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/IsFullySupportedFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/IsSupportedFilterVisitor.java
- modules/library/main/src/test/java/org/geotools/filter/CapabilitiesTest.java
> GEOT-5931: Temporal operators in opengis FilterCapabilities implementation and wrapper - 19.x bkp

- modules/extension/tile-client/src/main/java/org/geotools/tile/util/TileLayer.java
- modules/extension/wmts/src/test/java/org/geotools/data/wmts/client/WMTSTransparentTileTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5814
Supersedes https://github.com/geotools/geotools/pull/1692
> Add transparency on tile rendered image - Fix JIRA #GEOT-5814 (new pull request)

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectFunction.java
https://osgeo-org.atlassian.net/browse/GEOT-6010
Integration Tests: https://github.com/geoserver/geoserver/pull/2873
> [GEOT-6010] WMS GetMapRequest fail againts MongoDB complex feature types (App-Schema)

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectFunction.java
Backport of this PR: https://github.com/geotools/geotools/pull/1879
> [GEOT-6010] WMS GetMapRequest fail againts MongoDB complex feature types (App-Schema) (backport 18.x)

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectFunction.java
Backport of this PR: https://github.com/geotools/geotools/pull/1879
> [GEOT-6010] WMS GetMapRequest fail againts MongoDB complex feature types (App-Schema) (backport 19.x)

- modules/library/main/src/main/java/org/geotools/filter/function/CategorizeFunction.java
- modules/library/main/src/main/java/org/geotools/filter/function/ClassificationFunction.java
- modules/library/main/src/main/java/org/geotools/filter/function/RecodeFunction.java
- modules/library/main/src/main/java/org/geotools/filter/function/StringTemplateFunction.java
- modules/library/main/src/main/java/org/geotools/filter/function/color/AbstractHSLFunction.java
- modules/library/main/src/main/java/org/geotools/filter/function/color/ConstrastFunction.java
- modules/library/main/src/main/java/org/geotools/filter/function/color/GrayscaleFunction.java
- modules/library/main/src/main/java/org/geotools/filter/function/math/ModuloFunction.java
- modules/library/main/src/test/java/org/geotools/filter/FunctionToStringTest.java
Missing filter function toString() methods implemented so that converting a filter to a string produces the correct result.
Created new unit test so that all filter function toString() methods are checked to see if they have been implemented.
> [GEOT-6033] Missing filter function toString() methods implemented.

- modules/extension/app-schema/app-schema/src/test/java/org/geotools/http/HttpStaticServer.java
- modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/footprint/SidecarFootprintProvider.java
- modules/library/metadata/src/test/java/org/geotools/util/URLsTest.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFAggregationTest.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFCRSTest.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFMosaicReaderTest.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFMultiDimTest.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFReaderTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/DefaultSubmosaicProducerSPITest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/GranuleTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/HeterogenousCRSTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicEgrTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicFootprintsTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicPostgisIndexOnlineTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/MultiResolutionTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/OverviewsControllerTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/RasterLayerRequestTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/RemoteTest.java
- pom.xml
Fixed build For Windows users.
Current Jenkins build is failing for a while now:
http://winbuild.geo-solutions.it/jenkins/view/GeoTools/job/GeoTools-Master/
> [GEOT-6007] Build on Windows not working due to failing tests

- modules/library/main/src/main/java/org/geotools/filter/function/Collection_CountFunction.java
- modules/library/main/src/test/java/org/geotools/filter/function/Collection_FunctionsTest.java
Updated Collection_CountFunction filter capabilities to match documentation/implementation.
Added unit test.
> [GEOT-6032] Corrected Collection_CountFunction filter capabilities.

- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCNativeFilterOnlineTest.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCNativeFilterTestSetup.java
- modules/library/main/src/main/java/org/geotools/filter/FilterFactoryImpl.java
- modules/library/main/src/main/java/org/geotools/filter/NativeFilterImpl.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/AbstractFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/AbstractFinderFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/AbstractSearchFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/CapabilitiesFilterSplitter.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/DefaultFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/DuplicatingFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/NullFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/OperatorNameFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/PostPreProcessFilterSplittingVisitor.java
- modules/library/main/src/test/java/org/geotools/filter/visitor/DuplicateFilterVisitorTest.java
- modules/library/opengis/src/main/java/org/opengis/filter/FilterFactory2.java
- modules/library/opengis/src/main/java/org/opengis/filter/FilterVisitor.java
- modules/library/opengis/src/main/java/org/opengis/filter/NativeFilter.java
- modules/library/xml/src/main/java/org/geotools/xml/filter/FilterCompliancePreProcessor.java
- modules/plugin/jdbc/jdbc-h2/src/main/java/org/geotools/data/h2/H2FilterToSQL.java
- modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2NativeFilterOnlineTest.java
- modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2NativeFilterTestSetup.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleNativeFilterOnlineTest.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleNativeFilterTestSetup.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisNativeFilterOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisNativeFilterTestSetup.java
https://osgeo-org.atlassian.net/browse/GEOT-5968
Associated mailing list:
https://sourceforge.net/p/geotools/mailman/message/36268473/
> [GEOT-5968] Add NativeFilter filter

- modules/extension/app-schema/app-schema/src/test/java/org/geotools/http/HttpConfigTest.java
https://osgeo-org.atlassian.net/browse/GEOT-6046
> [GEOT-6046] HttpConfigTest app-schema-cache path inconsistent and does not honour java.io.tmpdir

- modules/plugin/epsg-hsql/pom.xml
- modules/plugin/epsg-hsql/src/main/java/org/geotools/referencing/factory/epsg/ThreadedHsqlEpsgFactory.java
- modules/plugin/epsg-hsql/src/test/java/org/geotools/referencing/factory/epsg/ThreadedHsqlEpsgFactoryTest.java
https://osgeo-org.atlassian.net/browse/GEOT-6045
> [GEOT-6045] Unnecessary assert prevents EPSG HSQL database in path with spaces

- modules/unsupported/geojsonstore/pom.xml
- pom.xml
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-6055
> [GEOT-6055] Upgrade commons-io dependency to 2.6

- modules/plugin/epsg-hsql/src/main/java/org/geotools/referencing/factory/epsg/FactoryUsingHSQL.java
- modules/plugin/epsg-hsql/src/main/java/org/geotools/referencing/factory/epsg/ThreadedHsqlEpsgFactory.java
https://osgeo-org.atlassian.net/browse/GEOT-6056
> [GEOT-6056] EPSG lookup failures caused by concurrent database shutdown in FactoryUsingHSQL finalizer

- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/utilities/NetCDFUtilities.java
- modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/imageio/netcdf/NetCDFUtilitiesTest.java
Fix to address bug: https://osgeo-org.atlassian.net/browse/GEOT-6049
> GEOT-6049 - Update NetcdfUtilities.getArray to support 7 dims

- modules/library/referencing/src/main/java/org/geotools/referencing/factory/epsg/CartesianAuthorityFactory.java
- modules/library/referencing/src/main/java/org/geotools/referencing/wkt/Parser.java
- modules/library/referencing/src/test/java/org/geotools/referencing/wkt/ParserTest.java
Allows EPSG:404000 to be magic when read back from a WKT file.
> [GEOT-6061] Backport to 19.x

- modules/library/referencing/src/main/java/org/geotools/referencing/factory/epsg/CartesianAuthorityFactory.java
- modules/library/referencing/src/main/java/org/geotools/referencing/wkt/Parser.java
- modules/library/referencing/src/test/java/org/geotools/referencing/wkt/ParserTest.java
Allows EPSG:404000 to be magic when read in from a WKT file
> [GEOT-6061] Backport to 18.x

- dependency-check-suppression.xml
> Add another suppression for arc.

- modules/plugin/svg/src/main/java/org/geotools/renderer/style/RenderableSVGCache.java
Probably lost while applying a one year old patch recently
> Resurrect GEOT-5870 on master

- modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/ContourProcess.java
Parameter band is integer - band number, so this makes description more clear in my opinion.
> Parameter description update

- docs/user/library/data/arcsde.rst
This is so complicated, its almost certainly always going to be wrong. Should I just delete it instead?
> Update arcsde docs.

- modules/extension/xsd/xsd-wfs/src/main/java/org/geotools/wfs/v2_0/bindings/QueryExpressionTextTypeBinding.java
- modules/library/main/src/main/java/org/geotools/styling/SLDParser.java
GeoTools seems to be building fine on Windows now, these changes help GeoServer build too on Windows (more work to be done inside GeoServer to get there though).
See: https://github.com/geoserver/geoserver/pull/2983
> Help GeoServer build on Windows

- modules/library/coverage/pom.xml
- modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/ShadedRelief.java
- modules/library/coverage/src/main/resources/META-INF/services/org.opengis.coverage.processing.Operation
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/ShadedReliefTest.java
- modules/library/main/src/main/java/org/geotools/styling/SLDParser.java
- modules/library/render/src/main/java/org/geotools/renderer/i18n/Vocabulary.properties
- modules/library/render/src/main/java/org/geotools/renderer/i18n/VocabularyKeys.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/ColorMapNode.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/Compositing.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/ContrastEnhancementNode.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageRenderer.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/RasterSymbolizerHelper.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/ShadedReliefNode.java
- modules/library/render/src/test/resources/org/geotools/renderer/lite/gridcoverage2d/test-data/colormap.sld
- pom.xml
Ref: PR on master:
https://github.com/geotools/geotools/pull/1931
> [GEOT-5182] Backport ShadedRelief implementation on 19.x

- modules/library/metadata/src/main/java/org/geotools/util/logging/CommonsLoggerFactory.java
see https://osgeo-org.atlassian.net/browse/GEOT-6084
Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>
> [GEOT-6084] removes commons.logging.impl import

- modules/library/referencing/src/test/java/org/geotools/referencing/GeodeticCalculatorTest.java
These are a mix of issues that are resolved by the recent incorporation of 1.49,
and those can't be reproduced with either 1.44 or 1.49.
> [GEOT-4207/4604/6026/6077] Add tests for GeodeticCalculator problems.

- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgFilterToSQL.java
Fix for https://osgeo-org.atlassian.net/browse/GEOT-6107
> Add AttributeDescriptor to descriptors list to fix filtering of geopackages

- modules/extension/ysld/src/main/java/org/geotools/ysld/YamlObject.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/YamlUtil.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/encode/YsldEncoder.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/parse/YamlParser.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/validate/YsldValidator.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeCookbookTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/transform/sld/SldTransformerTest.java
19.x backport for https://github.com/geotools/geotools/pull/2023
> [19.x][GEOT-6109] Centralize SnakeYAML configuration

- modules/extension/ysld/src/main/java/org/geotools/ysld/YamlObject.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/YamlUtil.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/encode/YsldEncoder.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/parse/YamlParser.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/validate/YsldValidator.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeCookbookTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/transform/sld/SldTransformerTest.java
20.x backport for https://github.com/geotools/geotools/pull/2023
> [20.x][GEOT-6109] Centralize SnakeYAML configuration

- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDataStoreFactory.java
> fix possible NPE issue during MySQLVersion56 check

- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLDataStoreFactoryTest.java
test case added for #2033  fix in order to allow back-porting to geotools 19.x
> Add test to ensure fix of NPE during MySQL version check

- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDataStoreFactory.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLDataStoreFactoryTest.java
PR for backporting mysql NPE fix to branch 19.x (original PRs #2033, #2044)
> Backporting mysql NPE fix to geotools branch 19.x

- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDataStoreFactory.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLDataStoreFactoryTest.java
PR for backporting  mysql NPE fix to branch 20.x (original PRs #2033, #2044)
> Backporting mysql NPE fix to geotools branch 20.x

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AbstractMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AttributeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMappingFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AttributeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/JdbcMultipleValue.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/MultipleValue.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/XMLConfigDigester.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/XPath.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/spi/CustomSourceDataStore.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/JdbcMultipleValueEncoder.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/JoiningJDBCFeatureSource.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/NestedFilterToSQL.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/WrappedFilterToSql.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedAttributeExpressionFactory.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/complex/ComplexDataStoreFactory.java
- modules/unsupported/solr/src/main/java/org/geotools/data/solr/complex/SolrMultipleValue.java
- modules/unsupported/solr/src/test/java/org/geotools/data/solr/complex/ComplexFeaturesTest.java
- modules/unsupported/solr/src/test/resources/solr/complex/mappings.xml
https://osgeo-org.atlassian.net/browse/GEOT-6082
Integrations test for SQL and documentation:
https://github.com/geoserver/geoserver/pull/3040
> [GEOT-6082] Add support in App-Schema for JDBC and Solr mutivalued properties

- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCNativeFilterOnlineTest.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCNativeFilterTestSetup.java
- modules/library/main/src/main/java/org/geotools/filter/FilterFactoryImpl.java
- modules/library/main/src/main/java/org/geotools/filter/NativeFilterImpl.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/AbstractFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/AbstractFinderFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/AbstractSearchFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/CapabilitiesFilterSplitter.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/DefaultFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/DuplicatingFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/NullFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/OperatorNameFilterVisitor.java
- modules/library/main/src/main/java/org/geotools/filter/visitor/PostPreProcessFilterSplittingVisitor.java
- modules/library/main/src/test/java/org/geotools/filter/visitor/DuplicateFilterVisitorTest.java
- modules/library/opengis/src/main/java/org/opengis/filter/FilterFactory2.java
- modules/library/opengis/src/main/java/org/opengis/filter/FilterVisitor.java
- modules/library/opengis/src/main/java/org/opengis/filter/NativeFilter.java
- modules/library/xml/src/main/java/org/geotools/xml/filter/FilterCompliancePreProcessor.java
- modules/plugin/jdbc/jdbc-h2/src/main/java/org/geotools/data/h2/H2FilterToSQL.java
- modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2NativeFilterOnlineTest.java
- modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2NativeFilterTestSetup.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleNativeFilterOnlineTest.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleNativeFilterTestSetup.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisNativeFilterOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisNativeFilterTestSetup.java
Backport of pull request:  https://github.com/geotools/geotools/pull/1918
Backport discussion:
https://sourceforge.net/p/geotools/mailman/message/36429244/
> [GEOT-5968] Add NativeFilter filter (backport 19.x)

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/FeatureChainedAttributeVisitor.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/NestedFilterToSQL.java
**Depends on https://github.com/geotools/geotools/pull/2006**
Backport of PR: #1896
>  [GEOT-6014] Make App-Schema delegate spatial filters on nested properties to the relational database (backport 18.x)

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/FeatureChainedAttributeVisitor.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/NestedFilterToSQL.java
**Depends on https://github.com/geotools/geotools/pull/2007**
Backport of PR: https://github.com/geotools/geotools/pull/1896
> [GEOT-6014] Make App-Schema delegate spatial filters on nested properties to the relational database (backport 19.x)

- modules/unsupported/javafx/README.md
- modules/unsupported/javafx/pom.xml
- modules/unsupported/javafx/src/test/java/org/geotools/javafx/FXMapTest.java
Fix dependencies and generally update them.
> update JavaFX dependencies to build with JDK11

- modules/plugin/coverage-multidim/coverage-api/pom.xml
- modules/plugin/coverage-multidim/coverage-api/src/main/java/org/geotools/coverage/io/util/Utilities.java
- modules/plugin/imagemosaic/pom.xml
- pom.xml
Replace calls to OSInfo with commons-lang3 equivaltents and added a dependency to JAXB api as it is no longer shipped with JDK-11
> replace sun.awt.OSInfo and add JAXB jar

- modules/extension/app-schema/app-schema/src/main/resources/META-INF/services/org.geotools.util.ConverterFactory
- modules/extension/complex/src/main/resources/META-INF/services/org.geotools.util.ConverterFactory
- modules/library/main/src/main/resources/META-INF/services/org.geotools.util.ConverterFactory
move ComplexAttributeConverterFactory spi in right module, removing it from complex and app-schema
> move ComplexAttributeConverterFactory spi in right module

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/FeatureChainedAttributeVisitor.java
https://osgeo-org.atlassian.net/browse/GEOT-6167
Since this issue can only be reproduced with an SQL data source the integration tests where implemented in GeoServer:  https://github.com/geoserver/geoserver/pull/3224
> [GEOT-6167] Complex features nested attributes not correctly detected

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/FeatureChainedAttributeVisitor.java
Backport of: https://github.com/geotools/geotools/pull/2162
https://osgeo-org.atlassian.net/browse/GEOT-6167
> [GEOT-6167] Complex features nested attributes not correctly detected (backport 20.x)

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
Backport of PR: https://github.com/geotools/geotools/pull/2170
> [GEOT-6178] Invalid select bounds query generated for Oracle database (backport 19.x)

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
Backport of PR: https://github.com/geotools/geotools/pull/2170
> [GEOT-6178] Invalid select bounds query generated for Oracle database (backport 20.x)

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexDataSource.java
- modules/plugin/mongodb/src/main/resources/META-INF/services/org.geotools.data.complex.spi.CustomSourceDataStore
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-6184
Integration tests updated in GeoServer.
> [GEOT-6184] MongoDB complex store iterator enters in an infinite loop if no ID is defined

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureIteratorFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/spi/CustomSourceDataStore.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexDataSource.java
- modules/plugin/mongodb/src/main/resources/META-INF/services/org.geotools.data.complex.spi.CustomSourceDataStore
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-6184
Integration tests updated in GeoServer.
> [GEOT-6184] MongoDB complex store iterator enters in an infinite loop if no ID is defined (backport 19.x)

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexDataSource.java
- modules/plugin/mongodb/src/main/resources/META-INF/services/org.geotools.data.complex.spi.CustomSourceDataStore
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-6184
Integration tests updated in GeoServer.
> [GEOT-6184] MongoDB complex store iterator enters in an infinite loop if no ID is defined (backport 20.x)

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/granulecollector/BaseSubmosaicProducer.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/granulecollector/ReprojectingSubmosaicProducer.java
- pom.xml
Depends on https://github.com/geosolutions-it/jai-ext/pull/227 and a jai-ext release
> [GEOT-6198] Do not set ROIs in image mosaic when not strictly necessary

- modules/library/main/src/main/java/org/geotools/filter/spatial/ReprojectingFilterVisitor.java
- modules/library/main/src/test/java/org/geotools/filter/spatial/ReprojectingFilterVisitorTest.java
https://osgeo-org.atlassian.net/browse/GEOT-6200
> [GEOT-6200] Reproject fitler tries to reproject non geometry properties

- modules/library/coverage/src/main/java/org/geotools/resources/image/ImageUtilities.java
- modules/library/coverage/src/test/java/org/geotools/coverage/processing/MosaicTest.java
- modules/library/coverage/src/test/java/org/geotools/resources/image/ImageUtilitiesTest.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java
> GEOT-6207: Better disposal of inner images - backport to 19.x

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/spi/CustomSourceDataStore.java
- modules/extension/app-schema/app-schema/src/test/java/org/geotools/util/ComplexAttributeConverterFactoryTest.java
- modules/library/main/src/main/java/org/geotools/util/ComplexAttributeConverterFactory.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectAllFunction.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectFunction.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexDataSource.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedAttributeExpressionFactory.java
Backport of: https://github.com/geotools/geotools/pull/2231
> [GEOT-6212][GEOT-6213] Fix MongoDB complex feature nested properties usage in SLDs (backport 20.x)

- docs/user/unsupported/mbstyle/index.rst
- docs/user/unsupported/mbstyle/spec.rst
The (long-overdue) documentation for the improvements introduced by https://github.com/geotools/geotools/pull/1865
> Mapbox Styles expressions documentation

- modules/library/referencing/src/main/java/org/geotools/referencing/operation/builder/MapTriangulationFactory.java
Static analyzer: Unnecessary cast, expression type is a subtype of the cast type
> MapTriangulationFactory.java: Remove casts to MappedPosition

- modules/unsupported/s3-geotiff/readme.md
add instructions for using s3.properties file with GeoServer
> instructions for use with custom s3 provider

- modules/extension/ysld/src/main/java/org/geotools/ysld/encode/RuleEncoder.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/parse/RuleParser.java
- modules/extension/ysld/src/main/java/org/geotools/ysld/transform/sld/RulesHandler.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeCookbookTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/encode/YsldEncodeTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseCookbookTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/parse/YsldParseTest.java
- modules/extension/ysld/src/test/java/org/geotools/ysld/transform/sld/SldTransformerTest.java
- modules/extension/ysld/src/test/resources/org/geotools/ysld/sld/point/legend.sld
20.x backport for https://github.com/geotools/geotools/pull/2137
> [GEOT-5653][20.x] Added YSLD support for Rule LegendGraphic elements.

- modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/mosaic/GeoPackageReaderTest.java
See https://osgeo-org.atlassian.net/browse/GEOT-6225
> [GEOT-6225] Fixed regression that can lose the alpha channel when scaling images.

- modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/mosaic/GeoPackageReaderTest.java
21.x backport for https://github.com/geotools/geotools/pull/2243
> [GEOT-6225][21.x] Fixed regression that can lose the alpha channel when scaling images.

- modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/mosaic/GeoPackageReaderTest.java
20.x backport for https://github.com/geotools/geotools/pull/2243
> [GEOT-6225][20.x] Fixed regression that can lose the alpha channel when scaling images.

- modules/library/metadata/src/test/java/org/geotools/util/factory/GeoToolsTest.java
- pom.xml
Upgrade to [jts-1.16.1](https://github.com/locationtech/jts/releases/tag/jts-1.16.1) point release
> Update to JTS 1.16.1

- docs/user/library/data/shape.rst
See https://osgeo-org.atlassian.net/browse/GEOT-6258
> [GEOT-6258] remove ambiguity about date/time stores in shapefile plugin docs

- modules/extension/complex/src/main/java/org/geotools/data/complex/feature/type/FeatureTypeRegistry.java
https://osgeo-org.atlassian.net/browse/GEOS-9130
> GEOS-9130 support xlink in csw

- pom.xml
Backport of https://github.com/geotools/geotools/pull/2317 to 21.x.
> Quote highest-basedir property to fix build in a path with spaces (21.x)

- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleFeatureSourceOnlineTest.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleTestSetup.java
Reverts geotools/geotools#2303
> Revert "[GEOT-6038] Oracle JDBC dialect doesn't support binary_double - 21.x"

- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleFeatureSourceOnlineTest.java
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleTestSetup.java
Reverts geotools/geotools#2304
> Revert "[GEOT-6038] Oracle JDBC dialect doesn't support binary_double - 20.x"

- docs/developer/conventions/code/qa.rst
- modules/unsupported/edigeo/pom.xml
- pom.xml
I ran a spellchecker on the pom files :)
> Improved spelling

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/NestedFilterToSQL.java
No tests here, fixes online app-schema tests failure in GeoServer
> [GEOT-6273] Follow up to fix app-schema online tests in GeoServer

- modules/extension/graph/src/main/java/org/geotools/graph/util/ZipUtil.java
- modules/library/metadata/src/main/java/org/geotools/util/Utilities.java
- modules/library/metadata/src/test/java/org/geotools/util/UtilitiesTest.java
- modules/plugin/epsg-hsql/src/main/java/org/geotools/referencing/factory/epsg/hsql/ThreadedHsqlEpsgFactory.java
close #2266
supersedes / closes #2291
> [GEOT-6210] add a ZipSlip check to metadata Utilities and resolve potential ZipSlip vulnerabilities 

- modules/extension/graph/src/main/java/org/geotools/graph/util/ZipUtil.java
- modules/library/metadata/src/main/java/org/geotools/util/Utilities.java
- modules/library/metadata/src/test/java/org/geotools/util/UtilitiesTest.java
- modules/plugin/epsg-hsql/src/main/java/org/geotools/referencing/factory/epsg/hsql/ThreadedHsqlEpsgFactory.java
Backports #2319 to the 21.x branch
> [GEOT-6210][21.x] add a ZipSlip check to metadata Utilities and resolve potential ZipSlip vulnerabilities

- modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/ApplicationSchemaXSD.java
- modules/extension/xsd/xsd-gml2/src/test/java/org/geotools/gml2/ApplicationSchemaXSDTest.java
- modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/ApplicationSchemaXSD.java
- modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/ApplicationSchemaXSDTest.java
This solves the problem of using schema files with includes from jar files.
> [GEOT-6158] include of xml schema does not work from within jar files

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/IndexIdIterator.java
This PR has a fix for: App-schema indexes makes query without correct maxFeatures number on "rows" parameter to Apache Solr.
Now appschema-indexes builds its solr query with the correct "rows" value.
https://osgeo-org.atlassian.net/browse/GEOT-6274
> [GEOT-6274] Fix app-schema indexes max rows parameter on solr query

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/JoiningJDBCFeatureSource.java
Executing a WFS query with nested filter and multiple sortBy expressions throws an malformed SQL exception on App-schema and Postgresql.
This PR fix SQL nested filter building on multiple sortBy expressions scenario, also adds some method delegating refactoring due to a too big method doing all.
20.x backport.
https://osgeo-org.atlassian.net/browse/GEOT-6252
> [GEOT-6252] App-schema multiple sortBy support on SQL (20.x backport)

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/IndexIdIterator.java
This PR has a fix for: App-schema indexes makes query without correct maxFeatures number on "rows" parameter to Apache Solr.
Now appschema-indexes builds its solr query with the correct "rows" value.
https://osgeo-org.atlassian.net/browse/GEOT-6274
> [GEOT-6274] Fix app-schema indexes max rows parameter on solr query (21.x backport)

- modules/library/render/src/main/java/org/geotools/map/MapViewport.java
- modules/library/render/src/test/java/org/geotools/map/MapViewportTest.java
Allows user to choose how to handle viewport resize events.
> Backport [GEOT-6269] to  21.x

- modules/library/render/src/main/java/org/geotools/map/MapViewport.java
- modules/library/render/src/test/java/org/geotools/map/MapViewportTest.java
Allows user to choose how to handle viewport resize events.
> Backport [GEOT-6269] to 20.x

- modules/library/metadata/src/main/java/org/geotools/util/PreventLocalEntityResolver.java
- modules/library/metadata/src/test/java/org/geotools/util/PreventLocalEntityResolverTest.java
21.x backport for https://github.com/geotools/geotools/pull/2384.
> [21.x] Improved entity validation in external DTDs.

- modules/library/metadata/src/main/java/org/geotools/xml/PreventLocalEntityResolver.java
- modules/library/metadata/src/test/java/org/geotools/util/PreventLocalEntityResolverTest.java
- modules/library/metadata/src/test/java/org/geotools/xml/PreventLocalEntityResolverTest.java
20.x backport for https://github.com/geotools/geotools/pull/2384.
> [20.x] Improved entity validation in external DTDs.

- modules/library/main/src/main/java/org/geotools/data/DataUtilities.java
- modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
https://osgeo-org.atlassian.net/browse/GEOT-6272
> [GEOT-6272]- FeatureType without default geometry

- pom.xml
Backport to upgrade SQlite to 3.27.1.1
> [GEOT-6304] Upgrade xerial-SQLite version to 3.27.2.1 (backport to 20.x)

- modules/library/main/src/main/java/org/geotools/data/DataUtilities.java
- modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
https://github.com/geotools/geotools/pull/2386
> Backport [GEOT-6272] to 20.x - FeatureType without default geometry

- modules/library/main/src/main/java/org/geotools/data/DataUtilities.java
- modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
https://github.com/geotools/geotools/pull/2386
> Backport  [GEOT-6272] to 21.x

- modules/library/main/src/main/java/org/geotools/feature/type/DateUtil.java
- modules/library/main/src/test/java/org/geotools/feature/DateUtilTest.java
Resolves https://osgeo-org.atlassian.net/browse/GEOT-5353
> GEOT5353: Fix date formatting problem for non-leap year centuries.

- docs/user/welcome/faq.rst
https://osgeo-org.atlassian.net/browse/GEOT-5947
> [GEOT-5947] maven repo in FAQ page still pointing to opengeo

- modules/library/opengis/src/main/java/org/opengis/util/CodeList.java
- modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleFilterToSQL.java
- pom.xml
Did not try to build, failure expected, just want to see where it gets to :-D
> Upgrading to ErrorProne 2.3.3

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStoreFactory.java
- modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2DataStoreFactoryTest.java
> GEOT-3825 Fetch size defaults to 0 in JDBCDataStore

- modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBFilter.java
- modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/parse/MBFilterTest.java
https://osgeo-org.atlassian.net/browse/GEOT-6314
> [GEOT-6314] Fix swapped "has" and "not has" conditions

- modules/library/render/src/main/java/org/geotools/renderer/lite/RenderingTransformationHelper.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/RenderingTransformationTest.java
Fix for https://osgeo-org.atlassian.net/browse/GEOT-6313
The "CoverageCrop" in RenderingTransformationHelper was cropping out portions of the coverage that would show up on the other side of the dateline - this change makes it so the crop only happens if the CRS does not wrap the world or the rendering area is entirely inside the coverage bounds.
One edge case this does not handle is a raster to vector transform with a style that could cause features outside the map area to still be drawn inside it (e.g. very large points). I was not able to find a way to  handle that while still cropping the coverage, and not cropping the coverage where possible  during rendering transforms has a significant performance impact.
> [GEOT-6313] Support raster-to-vector rendering transforms across the dateline

- modules/unsupported/arcgis-rest/pom.xml
- modules/unsupported/arcgis-rest/src/main/java/org/geotools/data/arcgisrest/ArcGISRestDataStore.java
- modules/unsupported/arcgis-rest/src/main/java/org/geotools/data/arcgisrest/ArcGISRestFeatureSource.java
- modules/unsupported/arcgis-rest/src/test/java/org/geotools/data/arcgisrest/ArcGISRestDataStoreTest.java
- pom.xml
@lmorandini This is part of a larger upgrade (where we're trying to move on from commons-httpclient). I have it converted over, but the tests are so mock'd that it really needs something online. Can you take a look when you have a chance, and do whatever testing is needed?
> GEOT-5859: ArcGIS REST conversion to httpcomponents 4.x

- docs/developer/procedures/add.rst
- pom.xml
Working in conjunction with https://trac.osgeo.org/osgeo/ticket/2261
> change URL of webdav used for deploy

- modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/cache/CacheConfig.java
- modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/cache/CacheManagement.java
Current the s3-geotiff cache never expires. I want to make it possible to configure an expiry time.
> GEOT-6319 S3-geotiff: time-out properties

- modules/library/metadata/src/main/java/org/geotools/util/logging/LoggingImagingListener.java
- modules/library/metadata/src/test/java/org/geotools/util/logging/LoggingImagingListenerTest.java
Added also a test to ensure the behaviour
> GEOT-6331 not swallowing exceptions anymore

- modules/unsupported/swing/src/main/java/org/geotools/swing/JMapPane.java
- modules/unsupported/swing/src/test/java/org/geotools/swing/JMapPaneGraphicsTest.java
If you set the color of the JMapPane it only uses this color on the second rendering which causes an odd effect.
https://osgeo-org.atlassian.net/browse/GEOT-6342
> [GEOT-6342] use background color when first rendering map

- modules/extension/wms/src/main/java/org/geotools/ows/wms/map/WMSCoverageReader.java
- modules/extension/wms/src/main/java/org/geotools/ows/wms/map/WMSLayer.java
- modules/extension/wms/src/test/java/org/geotools/ows/wms/map/WMSLayerTest.java
- modules/extension/wms/src/test/resources/org/geotools/ows/wms/map/caps130.xml
WMSCoverageReader
added constructors that take preffered WMS image format for remote wms
service
https://osgeo-org.atlassian.net/browse/GEOT-6360
> [GEOT-6360] add preffered image format support in WMSLayer and

- modules/unsupported/csv/src/main/java/org/geotools/data/csv/parse/CSVLatLonStrategy.java
- modules/unsupported/csv/src/test/java/org/geotools/data/csv/CSVDataStoreTest.java
- modules/unsupported/csv/src/test/java/org/geotools/data/csv/CSVWriteTest.java
- modules/unsupported/csv/src/test/java/org/geotools/data/csv/parse/CSVLatLonStrategyTest.java
- modules/unsupported/csv/src/test/java/org/geotools/data/csv/parse/CSVWriteStrategyTest.java
Make the test for axis order do the right thing with lat/lon
> [GEOT-6387] fix axis order in LatLonStrategy and related tests

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AttributeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/XMLConfigDigester.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/FeatureChainedAttributeVisitor.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/XPath.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Encoder.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/BindingPropertyExtractor.java
This PR adds Cardinality 1..N support for unbounded anonymous sequence children elements, using ClientProperty tag.
https://osgeo-org.atlassian.net/browse/GEOT-6370
> [GEOT-6370] App-Schema Cardinality 1..N support for unbounded anonymous sequence

- modules/library/render/src/main/java/org/geotools/renderer/RenderListener.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/CompositingGroup.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java
Related Jiira Ticket: https://osgeo-org.atlassian.net/browse/GEOT-6398
> [GEOT-6398] RenderListener Extension

- modules/library/render/src/main/java/org/geotools/renderer/RenderListener.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/CompositingGroup.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java
Reverts geotools/geotools#2600
> Revert "[GEOT-6398] RenderListener Extension"

- modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/ColorMapEntryBuilder.java
- modules/extension/brewer/src/test/java/org/geotools/brewer/styling/builder/CookbookRasterTest.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
This pr has a related jira ticket: https://osgeo-org.atlassian.net/browse/GEOT-6400
> [GEOT-6400] Implement support for text labels in ColorMapEntry for CSS

- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/BindingPropertyExtractor.java
This PR makes XSD access thread safe , using the XSDParticle API instead DOM for the same result on the original PR.
> [GEOT-6370]  Thread safe XSD access API change.

- modules/library/main/src/main/java/org/geotools/data/DataUtilities.java
- modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
see also #2525 for the reason for this addition. Existing functionality is not affected. Additional comparison behavior is added.
> [GEOT-6397] provide extra comparison method for featureTypes in DataUtilities class

- modules/library/main/src/main/java/org/geotools/data/store/ContentFeatureSource.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreTest.java
Reverts geotools/geotools#2604
> Revert "[GEOT-6293] ContentFeatureStore.getReader(Query) returns incorrect results when canTransact() returns false."

- modules/extension/grid/src/main/java/org/geotools/grid/Grids.java
- modules/extension/grid/src/main/java/org/geotools/grid/oval/Oval.java
- modules/extension/grid/src/main/java/org/geotools/grid/oval/OvalBuilder.java
- modules/extension/grid/src/main/java/org/geotools/grid/oval/OvalImpl.java
- modules/extension/grid/src/main/java/org/geotools/grid/oval/Ovals.java
- modules/extension/grid/src/test/java/org/geotools/grid/GridsOvalTest.java
- modules/extension/grid/src/test/java/org/geotools/grid/oval/OvalGridBuilderTest.java
- modules/extension/grid/src/test/java/org/geotools/grid/oval/OvalTest.java
- modules/extension/grid/src/test/java/org/geotools/grid/oval/OvalsTest.java
https://osgeo-org.atlassian.net/browse/GEOT-6418
> Add oval vector grids

- modules/library/main/src/main/java/org/geotools/data/DiffFeatureReader.java
- modules/library/main/src/main/java/org/geotools/data/store/ContentFeatureSource.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreTest.java
recreation of #2604 PR to address issue with direct casting
> [GEOT-6293] ContentFeatureStore.getReader(Query) returns incorrect results when canTransact() returns false

- docs/user/library/metadata/convert.rst
- docs/user/library/opengis/filter.rst
- modules/library/cql/src/main/java/org/geotools/filter/text/commons/ExpressionToText.java
- modules/library/cql/src/test/java/org/geotools/filter/text/ecql/ECQLTemporalPredicateTest.java
- modules/library/main/src/main/java/org/geotools/data/util/TemporalConverterFactory.java
- modules/library/main/src/main/java/org/geotools/styling/ColorMapEntry.java
- modules/library/metadata/src/main/java/org/geotools/util/Converter.java
Adds support when converting an OGC Filter containing an Instant to ECQL.
~Sorry about the test. I couldn't get it to run locally so I just pushed it up as is for now. But will fix if this is the correct change.~
> [GEOT-6401] Support OGC Instant dates in ECQL

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AbstractMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/XPath.java
This PR refactors some string literals into documented constants.
> Refactor literal strings to constants in AppSchema mapping feature iterator

- modules/extension/brewer/pom.xml
- modules/extension/xsd/xsd-fes/pom.xml
- modules/library/cql/pom.xml
- modules/library/jdbc/pom.xml
- modules/library/sample-data/pom.xml
- modules/plugin/charts/pom.xml
- modules/plugin/epsg-wkt/pom.xml
- modules/plugin/epsg-wkt/src/test/java/org/geotools/referencing/epsg/wkt/CRSTest.java
- modules/plugin/feature-pregeneralized/pom.xml
- modules/unsupported/process-raster/pom.xml
Found a bunch of un-needed dependency arcs here and there, decided to give it a light clean up (more could be done by changing code I assume)
> Deps cleanup

- modules/library/main/src/main/java/org/geotools/filter/AttributeExpressionImpl.java
> [Backport 22.x][GEOT-6421] AttributeExpressionImpl.evaluate() performance degradatation under concurrency

- docs/user/library/main/data.rst
updated user docs related to DataUtilities class update
>  [GEOT-6397] updated user docs related to extra methods added in DataUtilities class

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AbstractMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AttributeMapping.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/XMLConfigDigester.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/FeatureChainedAttributeVisitor.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/XPath.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Encoder.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/impl/BindingPropertyExtractor.java
This PR adds Cardinality 1..N support for unbounded anonymous sequence children elements, using ClientProperty tag.
https://osgeo-org.atlassian.net/browse/GEOT-6370
> [22.x backport][GEOT-6370] App-Schema Cardinality 1..N support for unbounded anonymous sequence

- modules/unsupported/csv/src/main/java/org/geotools/data/csv/CSVDataStore.java
- modules/unsupported/csv/src/main/java/org/geotools/data/csv/CSVDataStoreFactory.java
- modules/unsupported/csv/src/test/java/org/geotools/data/csv/CSVDataStoreFactoryTest.java
- modules/unsupported/csv/src/test/java/org/geotools/data/csv/CSVWriteTest.java
Now if you create a datastore on a file that doesn't exist you can write to it.
> [GEOT-6196] allow writing to files that don't exist yet

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectFunction.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java
This pull request has a related Jira Ticket https://osgeo-org.atlassian.net/browse/GEOT-6463
> [GEOT-6463] Remove support for json path in MongoDB module

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/complex/MongoComplexUtilitiesTest.java
This pull request ha a related jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6466
> [GEOT-6466] MongoDbB appschema support fails when iterating over an empty collection

- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCFeatureSourceOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
backport of : https://github.com/geotools/geotools/pull/2690
> [Backport 21.x] [GEOT-6363]Error in SQL conversion when function uses a like expression

- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCFeatureSourceOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
backport of: https://github.com/geotools/geotools/pull/2690
> [Backport 22.x] [GEOT-6363]Error in SQL conversion when function uses a like expression

- modules/library/render/src/test/java/org/geotools/renderer/lite/MarkAlongLineTest.java
fix addressed build faliure occurred after merging https://github.com/geotools/geotools/pull/2680
Log:
https://build.geoserver.org/view/geotools/job/geotools-master/3501/console
> [Build Failure Fix][GEOT-6433] increase tolerance in image assertion

- modules/library/metadata/src/test/java/org/geotools/util/URLsTest.java
WIP, checking if the test with a windows share URL will work on Windows
> [GEOT-3300] Re-enable Windows share URL test, only on Windows

- docs/user/library/opengis/unit.rst
Tested these changes independently in a Java main method
> Fix unit.rst docs after javax.measure changes

- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGC.java
- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCBeyondBinding.java
- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCDWithinBinding.java
- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCDistanceBufferTypeBinding.java
- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCDistanceTypeBinding.java
- modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/BinarySpatialOpTypeBindingTest.java
- modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/FilterMockData.java
- modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/OGCFilterTest.java
- modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_1/OGCFilterTest.java
- modules/library/opengis/src/main/java/org/opengis/filter/spatial/DistanceBufferOperator.java
Reverts geotools/geotools#2723
> Revert "[GEOT-6444]: Add units to DistanceBufferOperator"

- modules/plugin/mongodb/pom.xml
This PR updates maintainers list with information about Nuno Oliveira and Fernando Miño.
> Add Nuno Oliveira and Fernando Mino as maintainers.

- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/DistanceUnits.java
- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGC.java
- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCBeyondBinding.java
- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCDWithinBinding.java
- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCDistanceBufferTypeBinding.java
- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCDistanceTypeBinding.java
- modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/BinarySpatialOpTypeBindingTest.java
- modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/FilterMockData.java
- modules/library/opengis/src/main/java/org/opengis/filter/spatial/DistanceBufferOperator.java
Most of the discussion on this issue can be found in:
https://github.com/geotools/geotools/pull/2731 - the revert of the original commit which explains why we can't use Quantity.
https://github.com/geotools/geotools/pull/2723 - The original commit.
> [GEOT-6444] Add Units to DistanceBufferOperator

- .github/workflows/macos.yml
- modules/library/render/src/test/java/org/geotools/renderer/lite/LabelDisplacementModeTest.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java
Interesting enough, GitHub provides a CI build for th OSX environment too... is it something we're interested into? Here is a PR to see how that goes.
> MacOS CI build from GitHub?

- modules/library/main/src/main/java/org/geotools/data/DataStore.java
> Fix missing paren in javadoc

- docs/user/build/maven/repositories.rst
- docs/user/build/maven/settings.rst
- pom.xml
As of January 15th all Maven Central requests must use HTTPS. See https://support.sonatype.com/hc/en-us/articles/360041287334.
> Use HTTPS Maven Central URL

- modules/library/cql/src/main/java/org/geotools/filter/text/ecql/ECQL.java
Fixed misspelled "Length" in docs".
> Fix docs typos

- modules/extension/wms/src/main/java/org/geotools/ows/wms/map/WMSCoverageReader.java
- modules/extension/wms/src/main/java/org/geotools/ows/wms/map/WMSLayer.java
- modules/extension/wms/src/test/java/org/geotools/ows/wms/map/WMSLayerTest.java
- modules/extension/wms/src/test/resources/org/geotools/ows/wms/map/caps130.xml
backport of https://github.com/geotools/geotools/pull/2531
> [GEOT-6360] add preffered image format support in WMSLayer (22.x backport)

- modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_toWKT.java
- modules/library/main/src/test/java/org/geotools/filter/function/FilterFunction_toWKTTest.java
> [GEOT-6502] Add Geometry.class as context in FilterFunction_toWKT

- modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/function/ExponentialFunction.java
- modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/function/MBFunctionFactoryTest.java
- modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/parse/MBFunctionTest.java
While the current approach looks legit, it does not provide the same results as Mapbox GL, and this results in visibly different map renderings, overly big or small roads and the like, depending on the zoom level (quite visible in the OpenMapTiles Dark Matter and Positron styles).
@jodygarnett  or @tbarsballe are you in a position to review? …
> [GEOT-6505] MBStyle exponential math is not a match for Mapbox GL one

- docs/user/library/coverage/mosaic.rst
- modules/library/metadata/src/main/java/org/geotools/util/DateTimeParser.java
- modules/library/metadata/src/test/java/org/geotools/util/DateTimeParserTest.java
- modules/plugin/imagemosaic/pom.xml
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/time/TimeParser.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/time/TimestampFileNameExtractor.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/time/TimestampFileNameExtractorSPI.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/properties/time/TimestampFileNameExtractorTest.java
> [22.x-backport][GEOT-6409]: TimeParser refactoring and improvement

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisSimplifiedGeometryPreparedTest.java
JIRA : https://osgeo-org.atlassian.net/browse/GEOT-6511
First reported at : https://osgeo-org.atlassian.net/browse/GEOS-9433
-added delegate call to canSimplifyPoints method
-added new online test PostgisSimplifiedGeometryPreparedTest
Submitting the PR does not require you to check all items, but …
> [GEOT-9511] PostGIS JDBC does not request Point geometry column in TWKB with prepared statements enabled

- modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/StyleBuilder.java
- modules/extension/brewer/src/test/java/org/geotools/brewer/styling/builder/StyleBuilderTest.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssParser.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
> [GEOT-6503] Extend background support to the CSS module

- pom.xml
I updated the HTTP Components version and built + tested GeoTools to ensure it still functions properly.
> Updated HTTPComponents version

- .github/PULL_REQUEST_TEMPLATE.md
Procedural update, the checklist does not really apply.
> Clarify tickets should be in the GeoTools project, they are used for the release notes.

- modules/library/jdbc/src/main/java/org/geotools/jdbc/KeysFetcher.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISUuidOnlineTest.java
Add unit test for generated UUID
Replaces https://github.com/geotools/geotools/pull/2810
> [GEOS-9135] Support WFS-T on tables with unique guid as primary key

- pom.xml
Backporting this change to 22.x per @aaime
I updated the HTTP Components version and built + tested GeoTools to ensure it still functions properly. Ran from clean branch to correct the previous PR.
> backporting the httpcomponents update to 22.x

- pom.xml
Updates the maven plugin to a version that works with the currect state of NIST data.
> Bump dependency-check-maven plugin to 5.3.0

- docs/developer/conventions/code/log.rst
needs a newline.
currently https://docs.geotools.org/latest/developer/conventions/code/log.html#logging-messages
looks like this:
> [docs] fix logging categories table markup in developer docs

- pom.xml
> Updating to jai-ext 1.1.14

- pom.xml
> Updating to jai-ext 1.1.14 - GT 23.x

- pom.xml
> Updating to jai-ext 1.1.14 - GT 22.x

- modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java
- modules/library/coverage/src/test/java/org/geotools/image/ImageWorkerTest.java
> [22.x backport][GEOT-6535] ImageWorker getHistogram return always the first histogram computed

- modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java
- modules/library/coverage/src/test/java/org/geotools/image/ImageWorkerTest.java
> [23.x backport][GEOT-6535] ImageWorker getHistogram return always the first histogram computed

- .travis.yml
- pom.xml
See https://github.com/geotools/geotools/wiki/Change-from-webdav-to-nexus-repository
Moved from repo.boundlessgeo.com to repo.osgeo.org.
> [GEOT-2425] Change from webdav to nexus repository

- pom.xml
Backport of https://github.com/geotools/geotools/pull/2863
> [GEOT-2425] Change from webdav to nexus repository (#2863)

- docs/user/build/maven/repositories.rst
- docs/user/library/xml/internal/tutorial.rst
- docs/user/tutorial/coverage/artifacts/pom.xml
- docs/user/tutorial/datastore/artifacts/pom.xml
- docs/user/tutorial/feature/artifacts/pom.xml
- docs/user/tutorial/filter/artifacts/pom.xml
- docs/user/tutorial/geometry/artifacts/pom.xml
- docs/user/tutorial/map/artifacts/pom.xml
- docs/user/tutorial/quickstart/artifacts/pom.xml
- docs/user/tutorial/raster/artifacts/pom.xml
- docs/user/welcome/faq.rst
- docs/user/welcome/upgrade.rst
Update the documentation references (pom.xml and RST files).
>  [GEOT-2425] update documentation repository references

- docs/user/build/maven/repositories.rst
- docs/user/library/xml/internal/tutorial.rst
- docs/user/tutorial/coverage/artifacts/pom.xml
- docs/user/tutorial/datastore/artifacts/pom.xml
- docs/user/tutorial/feature/artifacts/pom.xml
- docs/user/tutorial/filter/artifacts/pom.xml
- docs/user/tutorial/geometry/artifacts/pom.xml
- docs/user/tutorial/map/artifacts/pom.xml
- docs/user/tutorial/quickstart/artifacts/pom.xml
- docs/user/tutorial/raster/artifacts/pom.xml
- docs/user/welcome/faq.rst
- docs/user/welcome/upgrade.rst
Backport of https://github.com/geotools/geotools/pull/2864
>  [GEOT-2425] update documentation repository references (23.x backport)

- docs/user/build/maven/repositories.rst
- docs/user/library/xml/internal/tutorial.rst
- docs/user/tutorial/coverage/artifacts/pom.xml
- docs/user/tutorial/datastore/artifacts/pom.xml
- docs/user/tutorial/feature/artifacts/pom.xml
- docs/user/tutorial/filter/artifacts/pom.xml
- docs/user/tutorial/geometry/artifacts/pom.xml
- docs/user/tutorial/map/artifacts/pom.xml
- docs/user/tutorial/quickstart/artifacts/pom.xml
- docs/user/tutorial/raster/artifacts/pom.xml
- docs/user/welcome/faq.rst
- docs/user/welcome/upgrade.rst
Backport of https://github.com/geotools/geotools/pull/2864
>  [GEOT-2425] update documentation repository references (22.x backport)

- pom.xml
> [GEOT-2425] Review use of maven repositories and plugin repositories

- pom.xml
Backport of https://github.com/geotools/geotools/pull/2871
> [GEOT-2425] Review use of maven repositories and plugin repositories (23.x backport)

- pom.xml
Backport of https://github.com/geotools/geotools/pull/2871
> [GEOT-2425] Review use of maven repositories and plugin repositories (22.x backport)

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/ShapefileReader.java
> [GEOT 6546] ByteBuffer can't see some Buffer methods

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/ShapefileReader.java
> Backport of [GEOT 6546] ByteBuffer can't see some Buffer methods

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/ShapefileHeader.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/ShapefileReader.java
> [GEOT-6546] more fixes for Buffer issue

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/ShapefileHeader.java
> Backport of [GEOT-6546] more buffer fixes

- build/release/build_release.sh
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/ShapefileHeader.java
> Backport build fix to 23.x

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileHeader.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/IndexFile.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/ShapefileHeader.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/ShapefileReader.java
> [GEOT-6546] More buffer superclass issues

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileHeader.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/IndexFile.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/ShapefileHeader.java
> Backport of  [GEOT-6546] buffer superclass issues

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureStore.java
spelling fix in exception message: "Unknon" -> "Unknown"
> spelling fix in exception message

- modules/unsupported/geojsonstore/src/main/java/org/geotools/data/geojson/GeoJSONDataStore.java
> [GEOT-6569] GeoJSONDatastore can not read from URLs that do not end .json

- modules/unsupported/geojsonstore/src/main/java/org/geotools/data/geojson/GeoJSONDataStore.java
> [GEOT-6569] [Backport] GeoJSONDatastore can not read from URLs that do not end .json 

- modules/library/main/src/main/java/org/geotools/filter/MultiCompareFilterImpl.java
- modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_equalTo.java
- modules/library/main/src/main/java/org/geotools/filter/function/StaticGeometry.java
- modules/library/main/src/test/java/org/geotools/filter/function/FilterFunction_equalToTest.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisPSFilterToSql.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
An optional parameter for MatchAction (ANY, ONE or ALL) has been added to FilterFunction_equalTo.
This is particularly useful if arguments are arrays.
An optimization for the postgis jdbc driver is also introduced, so that the function is translated to the postgresql overlap (&&) operator when both arguments are arrays and the match action is ANY.
> [GEOT-6578] equalTo support for matchAction and postgis optimization

- modules/plugin/imagemosaic-jdbc/src/main/java/org/geotools/gce/imagemosaic/jdbc/ImageDecoderThread.java
- modules/plugin/imagemosaic-jdbc/src/main/java/org/geotools/gce/imagemosaic/jdbc/JDBCAccessBase.java
- modules/plugin/imagemosaic-jdbc/src/test/java/org/geotools/gce/imagemosaic/jdbc/AbstractTest.java
- modules/plugin/imagemosaic-jdbc/src/test/java/org/geotools/gce/imagemosaic/jdbc/DB2OnlineTest.java
- modules/plugin/imagemosaic-jdbc/src/test/java/org/geotools/gce/imagemosaic/jdbc/GeoRasterOnlineTest.java
- modules/plugin/imagemosaic-jdbc/src/test/java/org/geotools/gce/imagemosaic/jdbc/H2Test.java
- modules/plugin/imagemosaic-jdbc/src/test/java/org/geotools/gce/imagemosaic/jdbc/MySqlOnlineTest.java
- modules/plugin/imagemosaic-jdbc/src/test/java/org/geotools/gce/imagemosaic/jdbc/OracleOnlineTest.java
- modules/plugin/imagemosaic-jdbc/src/test/java/org/geotools/gce/imagemosaic/jdbc/PostGisOnlineTest.java
Fix [GEOT-5621](https://osgeo-org.atlassian.net/browse/GEOT-5621).
> Fix geot 5621

- modules/plugin/mongodb/pom.xml
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/FeatureTypeDBObject.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoSchemaFileStore.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoUtil.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FeatureTypeDBObjectTest.java
> [GEOT-6559] Updating mongo java driver to latest available version

- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCPropertyNameTypeBinding.java
- modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_1/PropertyNameTypeBindingTest.java
https://osgeo-org.atlassian.net/browse/GEOT-6551
> [GEOT-6551] SLD 1.1 doesn't support namespaces in OGC PropertyName

- modules/library/metadata/src/main/java/org/geotools/util/factory/GeoTools.java
> [23.x backport] [GEOT-6506] Unnecessary synchronization in GeoTools.scanForSystemHints() 

- modules/plugin/geopkg/src/main/resources/org/geotools/geopkg/gpkg_spatial_index.sql
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
> [23.x backport] [GEOT-6565] GeoPackage spatial index creation fails with particular feature type names

- modules/plugin/geopkg/src/main/resources/org/geotools/geopkg/gpkg_spatial_index.sql
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
> [22.x backport] [GEOT-6565] GeoPackage spatial index creation fails with particular feature type names

- modules/library/render/src/test/java/org/geotools/renderer/lite/LabelDisplacementModeTest.java
Backport of https://github.com/geotools/geotools/commit/a9ee9f7faf1355d8dc8bc3862d1a9ded34c9d5da for Java 11 build on new Jenkins
> Extra tolerance for java 11 font handling

- modules/plugin/mongodb/pom.xml
The "Module maintainer" roles are missing. This PR fixes the issue.
> Fix module maintainer roles on MondoDB module

- modules/plugin/mongodb/pom.xml
> {GEOT-6590] Update Mongo Java driver to v4

- pom.xml
I guess I no longer work at LISAsoft, any one else need an update?
> Update developer description

- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStore.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureWriter.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileHeader.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileReader.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapeFileDbaseHeaderCharsetTest.java
- modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dbase-cs/data_cn.xml
- modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dbase-cs/data_en.xml
- modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dbase-cs/data_ru.xml
Backport of #2912.
Cherry picked from #2931.
> [22.x backport] [GEOT-3377] Charset not used for DBF header

- modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/ColumnMetadata.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/EnumMapper.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureReader.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureSource.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCTestSetup.java
- modules/library/main/src/main/java/org/geotools/feature/AttributeTypeBuilder.java
- modules/library/main/src/main/java/org/geotools/feature/FeatureTypes.java
- modules/library/main/src/main/java/org/geotools/feature/simple/SimpleFeatureTypeBuilder.java
- modules/library/main/src/test/java/org/geotools/feature/FeatureTypesTest.java
- modules/library/main/src/test/java/org/geotools/feature/simple/SimpleFeatureBuilderTest.java
- modules/plugin/geopkg/pom.xml
- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/DataColumn.java
- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/DataColumnConstraint.java
- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java
- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgExtension.java
- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgSchemaExtension.java
- modules/plugin/geopkg/src/main/resources/org/geotools/geopkg/gpkg_data_column_constraints.sql
- modules/plugin/geopkg/src/main/resources/org/geotools/geopkg/gpkg_data_columns.sql
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDataStoreOnlineTest.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgEnumTest.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgTestSetup.java
@jodygarnett this is what we discussed on list some time ago, is it something you'd like to review?
> Support for an enumerating restriction, and for compact enumerations in GeoPackage

- docs/developer/conventions/test/online.rst
This fixes and updates the "Online Tests" document hosted at https://docs.geotools.org/latest/developer/conventions/test/online.html
Adding some instructions on running dockerized versions of SQL Server and Oracle XE databases.
Note that this assumes #2890 is merged as far as the oracle part is concerned.
Submitting the PR does not require you to check all items, but by …
> add some notes on setting up dockerized databases for online testing

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java
> [23.x backport][GEOT-6598] Ogc filter to mongo operator translation fails (#2941)

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java
> [22.x backport][GEOT-6598] Ogc filter to mongo operator translation fails (#2941)

- modules/library/main/src/main/java/org/geotools/data/ows/SimpleHttpClient.java
> [GEOT-6618] Add a better default header to SimpleHttpClient backport

- modules/plugin/mongodb/pom.xml
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/FeatureTypeDBObject.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoSchemaFileStore.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoUtil.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FeatureTypeDBObjectTest.java
> [23.x backport] [GEOT-6559] Updating mongo java driver to latest available version [GEOT-6590] Update Mongo Java driver to v4 

- modules/plugin/mongodb/pom.xml
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/FeatureTypeDBObject.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoSchemaFileStore.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoUtil.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FeatureTypeDBObjectTest.java
> [22.x backport] [GEOT-6559] Updating mongo java driver to latest available version [GEOT-6590] Update Mongo Java driver to v4 

- modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java
- modules/library/coverage/src/test/java/org/geotools/image/ImageWorkerTest.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterManager.java
See https://osgeo-org.atlassian.net/browse/GEOT-6624
> [GEOT-6624]: 16 Bit palette to RGBA fix

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterManager.java
a follow up on [GEOT-6624] due to a couple of files went by mistake on the PR
> Reverting files ended up by mistake on the [GEOT-6624] PR after the review

- modules/extension/graph/src/main/java/org/geotools/graph/path/AStarShortestPathFinder.java
- modules/extension/graph/src/main/java/org/geotools/graph/path/WrongPathException.java
For no apparent reason WrongPathException is a package protected subclass in AStarPathFinder. This prevents user code from catching the exception. 
> [GEOT-66280 WrongPathException is package protected preventing users catching it

- modules/extension/graph/src/main/java/org/geotools/graph/path/AStarShortestPathFinder.java
- modules/extension/graph/src/main/java/org/geotools/graph/path/WrongPathException.java
> [GEOT-6638] - break WrongPathException out to own class

- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISHStoreOnlineTest.java
> Fixing JDBC-PostGIS OnlineTests

- modules/extension/app-schema/app-schema-example/pom.xml
- modules/extension/app-schema/app-schema-packages/pom.xml
- modules/extension/app-schema/app-schema-resolver/pom.xml
- modules/extension/app-schema/app-schema/pom.xml
- modules/extension/app-schema/pom.xml
- modules/extension/app-schema/sample-data-access/pom.xml
Updates App-Schema modules maintainers, officializing _Nuno Oliveira_ and _Fernando Miño_ as the module maintainers.  
- [x ] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or …
> Update App-Schema modules maintainers

- pom.xml
> Upgrading to jai-ext 1.1.15

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISCompound3DOnlineTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISCompound3DTestSetup.java
> [GEOT-6600] getBounds fails for compound 3d crs in postgis jdbc store

- modules/extension/ysld/pom.xml
Upgrade SnakeYAML to 1.26 to address a security vulnerability.
https://osgeo-org.atlassian.net/browse/GEOT-6634
> [GEOT-6634] Upgrade SnakeYAML to 1.26

- modules/library/main/src/main/java/org/geotools/feature/collection/DecoratingFeatureCollection.java
- modules/library/main/src/test/java/org/geotools/feature/collection/DecoratingFeatureCollectionTest.java
As the title says. See also https://osgeo-org.atlassian.net/browse/GEOT-6640
> [GEOT-6640] DecoratingFeatureCollection does not allow delegating visitors down

- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgTestSetup.java
GeoPackage INT are actually longs in range.
See also https://osgeo-org.atlassian.net/browse/GEOT-6524
> [GEOT-6524] The GeoPackage Plugin does not support long integers

- modules/plugin/jdbc/jdbc-oracle/pom.xml
- modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OraclePrimaryKeyOnlineTest.java
- pom.xml
A new version of the Oracle JDBC driver was released recently.
Update com.oracle.database.jdbc:ojdbc8 19.6.0.0 ➜ 19.7.0.0
No backports of this because #2832 was not backported due to API changes (users can always update the driver in their own application if they want)
see:
- https://osgeo-org.atlassian.net/browse/GEOT-6642
Submitting the PR does not require you to check …
> [GEOT-6642] Upgrade Oracle JDBC driver to 19.7.0.0

- .gitignore
- modules/unsupported/geojsonstore/src/main/java/org/geotools/data/geojson/GeoJSONReader.java
- modules/unsupported/geojsonstore/src/test/java/org/geotools/data/geojson/GeoJSONReaderTest.java
See https://osgeo-org.atlassian.net/browse/GEOT-6243 for discussion of original issue.
> [GEOT-6243] Issue with reading GeoJSON feature with regular geometry attribute when geometry comes after properties

- modules/library/render/src/main/java/org/geotools/renderer/lite/MemoryFilterOptimizer.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/MemoryFilterOptimizerTest.java
This PR introduces a performance improvement on MemoryFilterOptimizer for in-memory features filter evaluation.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-6653
> [GEOT-6653] Add InFunction optimization to MemoryFilterOptimizer

- modules/library/main/src/main/java/org/geotools/geometry/jts/CircularRing.java
- modules/library/main/src/main/java/org/geotools/geometry/jts/CircularString.java
- modules/library/main/src/main/java/org/geotools/geometry/jts/CompoundCurve.java
- modules/library/main/src/main/java/org/geotools/geometry/jts/CompoundRing.java
- modules/library/main/src/test/java/org/geotools/geometry/jts/CurvedGeometryTest.java
- modules/library/metadata/src/test/java/org/geotools/util/factory/GeoToolsTest.java
- modules/library/render/src/main/java/org/geotools/renderer/label/LineStringCursor.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/SimpleGeometryFactory.java
- modules/ogc/net.opengis.csw/src/net/opengis/cat/csw20/impl/QueryTypeImpl.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoGeometryBuilder.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/shp/JTSUtilitiesTest.java
- modules/unsupported/flatgeobuf/pom.xml
- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/ClipProcess.java
- pom.xml
Signed-off-by: Jim Hughes <jnh5y@ccri.com>
The goal of this PR is to upgrade to the latest release of JTS, version 1.17.0. 
At present, this PR is a WIP until there's a release of JAI-EXT and JAITOOLS which leverage the new version.  (This is due to a small API change involving a method switching between LineStrings and LinearRings.)
Depending on:
Submitting the PR does …
> GEOT-6637  Upgrade to JTS Topology Suite 1.17.0

- modules/library/render/src/main/java/org/geotools/renderer/lite/MemoryFilterOptimizer.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/MemoryFilterOptimizerTest.java
This PR introduces a performance improvement on MemoryFilterOptimizer for in-memory features filter evaluation.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-6653
> [23.x backport][GEOT-6653] Add InFunction optimization to MemoryFilterOptimizer

- modules/library/main/src/main/java/org/geotools/data/util/CommonsConverterFactory.java
- modules/library/main/src/main/java/org/geotools/data/util/DataUrlConnection.java
- modules/library/main/src/test/java/org/geotools/data/util/DataUrlHandlerTest.java
This PR adds 'data:' schema validation for data protocol handling code on GeoTools URL converter.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-6657
> [GEOT-6657] Fix data URL protocol validation

- modules/library/main/src/main/java/org/geotools/data/util/CommonsConverterFactory.java
- modules/library/main/src/main/java/org/geotools/data/util/DataUrlConnection.java
- modules/library/main/src/test/java/org/geotools/data/util/DataUrlHandlerTest.java
This PR adds 'data:' schema validation for data protocol handling code on GeoTools URL converter.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-6657
> [23.x backport][GEOT-6657] Fix data URL protocol handling

- modules/library/main/src/main/java/org/geotools/data/PrjFileReader.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileHeader.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileReader.java
- modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/IndexFile.java
> [GEOT-6546] Buffer subclass/superclass issues

- modules/library/main/src/main/java/org/geotools/styling/PointPlacement.java
> Fix typos in PointPlacement

- modules/extension/xsd/xsd-core/pom.xml
- pom.xml
Signed-off-by: Jim Hughes <jnh5y@ccri.com>
> [GEOS-9700] Cleaning up use of Eclipse EMF depdencies.

- modules/library/main/src/main/java/org/geotools/styling/visitor/UomRescaleStyleVisitor.java
- modules/library/main/src/test/java/org/geotools/styling/visitor/UomRescaleStyleVisitorTest.java
- modules/library/xml/src/main/java/org/geotools/xml/styling/SLDParser.java
- modules/library/xml/src/test/java/org/geotools/xml/styling/SLDParserTest.java
> [GEOT-6389] SLD vendor option graphic-margin can't be empty

- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/ColumnSet.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/VPFCovFeatureSource.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/VPFCoverage.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/VPFDataBase.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/VPFDataStoreFactory.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/VPFFeatureClass.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/VPFFeatureReader.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/VPFFeatureSource.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/VPFFeatureType.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/VPFLibFeatureSource.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/VPFLibrary.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/io/VPFInputStream.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/readers/AreaGeometryFactory.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/util/EdgeData.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/util/PointData.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/util/PrimitiveDataFactory.java
- modules/unsupported/vpf/src/test/java/org/geotools/data/vpf/VPFTest.java
Contribute to unchecked warnings epic - VPF chapter.
> vpf: fix unchecked warnings, minor code quality cleanups

- modules/unsupported/geojson/src/main/java/org/geotools/geojson/DelegatingHandler.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/GeoJSONUtil.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/HandlerBase.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/ArrayHandler.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/CRSHandler.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/DefaultAttributeIO.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/FeatureCollectionHandler.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/FeatureHandler.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/FeatureJSON.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/FeatureTypeAttributeIO.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/FeatureTypeHandler.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/geom/GeometryCollectionHandler.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/geom/GeometryHandlerBase.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/geom/GeometryJSON.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/geom/LineHandler.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/geom/MultiLineHandler.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/geom/MultiPointHandler.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/geom/MultiPolygonHandler.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/geom/PointHandler.java
- modules/unsupported/geojson/src/main/java/org/geotools/geojson/geom/PolygonHandler.java
- modules/unsupported/geojson/src/test/java/org/geotools/geojson/FeatureJSONTest.java
Fixes unchecked warnings for the unsupported geojson module.
> geojson: fix unchecked warnings

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureReader.java
This PR fixes an issue on App-Schema not supporting jdbcMultipleValue mapping with Oracle database.  Testing is handled on GeoServer App-Schema tests modules.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6670
> [GEOT-6670] Add multivalue support for App-Schema Oracle

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureReader.java
This PR fixes an issue on App-Schema not supporting jdbcMultipleValue mapping with Oracle database. Testing is handled on GeoServer App-Schema tests modules.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6670
> [23.x backport][GEOT-6670] Add multivalue support for App-Schema Oracle

- .github/workflows/windows.yml
make sure that the stored cache name (`key`) matches the restored cache name (`restore-keys`) in the Windows Github workflow
> fix maven repo caching for GH Windows workflow

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureReader.java
Backport of https://github.com/geotools/geotools/pull/3084.
> [GEOT-6670] Add multivalue support for App-Schema Oracle (22.x Backport)

- docs/user/artifacts/function_list
- modules/library/main/src/main/java/org/geotools/filter/function/ClassificationFunction.java
- modules/library/main/src/main/java/org/geotools/filter/function/EqualIntervalFunction.java
- modules/library/main/src/main/java/org/geotools/filter/function/StandardDeviationFunction.java
- modules/library/main/src/test/java/org/geotools/filter/function/FunctionTestSupport.java
- modules/library/main/src/test/java/org/geotools/filter/function/StandardDeviationFunctionTest.java
This pull request adds percentages computation to the StandardDeviationFunction as for the others ClassificationFunctions.
Jista ticket https://osgeo-org.atlassian.net/browse/GEOT-6665
> [GEOT-6665] Add percentages computation for StandardDeviationClassificationFunction

- modules/extension/ysld/pom.xml
23.x backport for [GEOT-6634] Upgrade SnakeYAML to 1.26
> [23.x][GEOT-6634] Upgrade SnakeYAML to 1.26

- modules/extension/ysld/pom.xml
22.x backport for [GEOT-6634] Upgrade SnakeYAML to 1.26
> [22.x][GEOT-6634] Upgrade SnakeYAML to 1.26

- pom.xml
23.x backport for [GEOT-6635] Upgrade NetCDF to 4.6.15
> [23.x][GEOT-6635] Upgrade NetCDF to 4.6.15

- pom.xml
22.x backport for [GEOT-6635] Upgrade NetCDF to 4.6.15
> [22.x][GEOT-6635] Upgrade NetCDF to 4.6.15

- .travis.yml
- modules/unsupported/javafx/pom.xml
- modules/unsupported/javafx/src/main/java/org/geotools/javafx/FXMap.java
- modules/unsupported/javafx/src/test/java/org/geotools/javafx/FXMapJDK11Test.java
- modules/unsupported/pom.xml
- pom.xml
This fixes the unchecked warnings in javafx. That module is currently not in the `-Dall` build, but the fixes aren't complicated, except for a test (*the only test it has*) that has a JDK11 dependency.
To address that, I've added a profile setting (`jdk11test`) based on the existing `stress` and `online` profiles that turns on JDK11-only tests. The test only runs if that profile is enabled, and the profile is disabled by default. It is enabled in the Travis CI configuration for JDK11 though.
> javafx: fix build problems and unchecked warnings, re-add to build

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java
> [22.x backport][GEOT-6666] Add jsonSelect and jsonSelectAllFunctions to filter capabilities in Mongo plugin (#3081)

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WMTSSpecification.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WMTSSpecificationTest.java
> [GEOT-6677] WMTS should only uppercase known key words

- docs/user/artifacts/function_list
- modules/library/main/src/main/java/org/geotools/filter/function/ClassificationFunction.java
- modules/library/main/src/main/java/org/geotools/filter/function/EqualIntervalFunction.java
- modules/library/main/src/main/java/org/geotools/filter/function/StandardDeviationFunction.java
- modules/library/main/src/test/java/org/geotools/filter/function/FunctionTestSupport.java
- modules/library/main/src/test/java/org/geotools/filter/function/StandardDeviationFunctionTest.java
* [GEOT-6665] Add percentages computation for StandardDeviationClassificationFunction
* reviewer's feedback applied
* reviewer's suggestion applied #2
> [23.x backport][GEOT-6665] Add percentages computation for StandardDeviationClassificationFunction (#3078)

- modules/library/referencing/src/main/java/org/geotools/referencing/operation/projection/Polyconic.java
- modules/library/referencing/src/test/resources/org/geotools/referencing/test-data/scripts/Polyconic.txt
This PR addresses GEOT-6386 by incorporating Spherical cases into the Polyconic projection implementation.
> [GEOT-6386] Implement Polyconic spherical case

- .travis.yml
Taking over from @jnh5y https://github.com/geotools/geotools/pull/3125 PR, looking at upgrading distribution used to bionic and openjdk for testing.
> travis upgrade to bionic distribution

- docs/user/welcome/upgrade.rst
> added note about units change to upgrade page

- .travis.yml
- .travis/mysql.properties
- .travis/mysql_setup.sql
- .travis/setup-mysql.sh
- .travis/start-mysql.sh
- docs/developer/conventions/test/online.rst
- docs/user/library/jdbc/mysql.rst
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDataStoreFactory.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLTestSetup.java
- modules/unsupported/imagemosaic-jdbc/src/test/java/org/geotools/gce/imagemosaic/jdbc/MySqlOnlineTest.java
- pom.xml
Updates the MySQL driver to 8.0.21 and starts running a job on Travis to run MySQL online tests using MySQL 5.x (latest docker image) which will come in handy when [GEOT-6690](https://osgeo-org.atlassian.net/browse/GEOT-6690) is picked up.
Added a note about supported versions of MySQL (only 5.6/5.7, not 8.x) and some doc on running a docker container for test purposes.
fixes: [GEOT-6692](https://osgeo-org.atlassian.net/browse/GEOT-6692)
close #3028
The following are required only for core and …
> [GEOT-6692] Update MySQL jdbc driver to current version (8.0.x)

- .travis.yml
- .travis/mysql.properties
- .travis/mysql_setup.sql
- .travis/setup-mysql.sh
- .travis/start-mysql.sh
- docs/developer/conventions/test/online.rst
- docs/user/library/jdbc/mysql.rst
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDataStoreFactory.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLTestSetup.java
- modules/unsupported/imagemosaic-jdbc/src/test/java/org/geotools/gce/imagemosaic/jdbc/MySqlOnlineTest.java
- pom.xml
> [24.x backport][GEOT-6692] Update MySQL jdbc driver to current version (8.0.x) 

- modules/plugin/imagemosaic/pom.xml
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicConfigHandler.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicWalker.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java
> [GEOT-6694] ImageMosaic SuggestedFormat improvements

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicFormat.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicReader.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java
Details at https://osgeo-org.atlassian.net/browse/GEOT-6693
> GEOT-6693: ImageMosaic source check initializations improvements

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicReader.java
> [GEOT-6697]: Harvesting a single file - stop doing directory scan

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicReader.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/Utils.java
> [GEOT-6993]: more on source check improvement avoiding directory scan

- modules/plugin/imagemosaic/pom.xml
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicConfigHandler.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicWalker.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java
> 24.x backport - [GEOT-6694]: SuggestedFormat improvements

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/GeometryColumnEncoder.java
- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGIS3DOnlineTest.java
…Exception: An exception occurred while parsing WKB data" (#3140)
> [23.x backport] [GEOT-6373] Error in geoserver 2.16.0:  "org.geotools.data.DataSource Exception: An exception occurred while parsing WKB data"

- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/ImageMosaicReader.java
- modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/acceptors/HomogeneousCRSAcceptor.java
- modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicReaderTest.java
See https://osgeo-org.atlassian.net/browse/GEOT-6699 for details
> [GEOT-6699] Harvesting multiple files can fail due to CRS checks

- modules/extension/app-schema/app-schema/pom.xml
- modules/plugin/imagemosaic/pom.xml
- modules/unsupported/solr/pom.xml
- pom.xml
Upgrades commons-beanutils to current release (which includes a fix for CVE-2019-10086). This gets rid of the custom `noclassprop` version that fixed CVE-2019-10086 and gets us back on the mainstream release.
fixes [GEOT-6698](https://osgeo-org.atlassian.net/browse/GEOT-6698)
see also https://github.com/geoserver/geoserver/pull/4473
close #3004 …
> [GEOT-6698] Bump commons-beanutils from 1.9.2 to 1.9.4

- modules/extension/app-schema/app-schema/pom.xml
- modules/plugin/imagemosaic/pom.xml
- modules/unsupported/solr/pom.xml
- pom.xml
> [backport 24.x] [GEOT-6698] Bump commons-beanutils from 1.9.2 to 1.9.4

- modules/extension/app-schema/app-schema/pom.xml
- modules/plugin/imagemosaic/pom.xml
- modules/unsupported/solr/pom.xml
- pom.xml
> [backport 23.x] [GEOT-6698] Bump commons-beanutils from 1.9.2 to 1.9.4

- modules/unsupported/geojsonstore/src/main/java/org/geotools/data/geojson/GeoJSONDataStoreFactory.java
- modules/unsupported/geojsonstore/src/test/java/org/geotools/data/geojson/GeoJSONDataStoreFactoryTest.java
> [GEOT-6702] GeoJSONDataStore should handle URLs properly

- modules/unsupported/geojsonstore/src/main/java/org/geotools/data/geojson/GeoJSONDataStoreFactory.java
- modules/unsupported/geojsonstore/src/test/java/org/geotools/data/geojson/GeoJSONDataStoreFactoryTest.java
> [GEOT-6702] GeoJSONDatastore should handle URLs correctly (backport 24.x)

- modules/unsupported/geojsonstore/src/main/java/org/geotools/data/geojson/GeoJSONDataStoreFactory.java
- modules/unsupported/geojsonstore/src/test/java/org/geotools/data/geojson/GeoJSONDataStoreFactoryTest.java
> [GEOT-6702] GeoJSONDatastore should handle URLs correctly (backport 23.x)

- docs/developer/procedures/release.rst
> fix up release guide formatting

- modules/extension/xsd/xsd-wfs/src/main/java/org/geotools/wfs/v2_0/bindings/EnvelopePropertyTypeBinding.java
- modules/ogc/net.opengis.wfs/src/net/opengis/wfs20/impl/SimpleFeatureCollectionTypeImpl.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/WFSTestData.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/parsers/AbstractGetFeatureParserTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/parsers/PullParserTest.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/parsers/XmlSimpleFeatureParserTest.java
- modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/GeoServer_2.2.x/2.0.0/GetFeature_roads.xml
Pull request for [GEOT-6682](https://osgeo-org.atlassian.net/browse/GEOT-6682). 
> [GEOT-6682] WFS 2.0 GetFeature reponse parsing fails on "boundedBy"

- modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/FESConfiguration.java
- modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/MeasureTypeBinding.java
- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/DistanceUnits.java
- modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCDistanceTypeBinding.java
- modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_1/OGCFilterTest.java
- modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/bindings/GetFeatureTypeBindingTest.java
> [GEOT-6703] Dwithin old syntax no longer supported

- modules/library/referencing/src/main/java/org/geotools/referencing/factory/URN_Parser.java
- modules/library/referencing/src/test/java/org/geotools/referencing/factory/URN_ParserTest.java
JIRA : https://osgeo-org.atlassian.net/browse/GEOT-6714
- fixed URN parser
- empty version is treated as NULL
> [GEOT-6714] Invalid URN parsing of version less URN SRS (urn:ogc:def:crs:EPSG::4326)

- modules/library/referencing/src/main/java/org/geotools/referencing/factory/URN_Parser.java
- modules/library/referencing/src/test/java/org/geotools/referencing/factory/URN_ParserTest.java
backport of https://github.com/geotools/geotools/pull/3166
> [Backport 24.x][GEOT-6714] Invalid URN parsing of version less URN SRS (urn:ogc:def:crs:EPSG::4326) 

- modules/library/referencing/src/main/java/org/geotools/referencing/factory/URN_Parser.java
- modules/library/referencing/src/test/java/org/geotools/referencing/factory/URN_ParserTest.java
backport of : https://github.com/geotools/geotools/pull/3166
> [backport 23.x] [GEOT-6714] Invalid URN parsing of version less URN SRS (urn:ogc:def:crs:EPSG::4326)

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java
Fix for https://osgeo-org.atlassian.net/browse/GEOT-6678
> [GEOT-6678] Fix NPE when SortBy is NullSortBy

- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
- modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
> [24.x backport] [GEOT-6722] Fix lost precision bug when saving a Double to GeoPackage

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
Fix for https://osgeo-org.atlassian.net/browse/GEOT-6679
> [GEOT-6679] Not filter visitor doesn't map property name

- modules/library/coverage/pom.xml
- modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/MaskOverviewProvider.java
- modules/plugin/geotiff/pom.xml
- modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffFormat.java
- modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java
- modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderCogOnlineTest.java
- pom.xml
https://osgeo-org.atlassian.net/browse/GEOT-6715
Supporting ImageIO-EXT COG Streams into GeoTIFF reader.
Note that:
The PR contains a temporary pom.xml update to use imageio-ext snapshot.
The final PR will be updated to use a newly released imageio-ext 1.3.X version. …
> [GEOT-6715]: COG Support in GeoTIFF

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java
Back port fix for https://osgeo-org.atlassian.net/browse/GEOT-6678 to 24.x
> [GEOT-6678] WFS query with no sort throws NullPointerException

- modules/unsupported/cql-json/pom.xml
- modules/unsupported/cql-json/src/main/java/org/geotools/filter/text/cqljson/CQLJson.java
- modules/unsupported/cql-json/src/main/java/org/geotools/filter/text/cqljson/CQLJsonCompiler.java
- modules/unsupported/cql-json/src/main/java/org/geotools/filter/text/cqljson/CQLJsonCompilerFactory.java
- modules/unsupported/cql-json/src/main/java/org/geotools/filter/text/cqljson/CQLJsonFilterBuilder.java
- modules/unsupported/cql-json/src/main/java/org/geotools/filter/text/cqljson/MapToOpenGISGeomUtil.java
- modules/unsupported/cql-json/src/test/java/org/geotools/filter/text/cqljson/CQLJsonParsingTest.java
- modules/unsupported/cql-json/src/test/resources/cqlJsonTest.json
build check passing
fixed issue where value is interpreted as int not double
all tests passing
cleanup
- [ x] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
- [x ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
- [ x] The changes are not breaking the build in …
> checked conversion from object to Maps

- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCAggregateFunctionOnlineTest.java
- modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCTestSupport.java
- modules/library/main/src/main/java/org/geotools/feature/visitor/Aggregate.java
- modules/library/main/src/main/java/org/geotools/feature/visitor/AverageVisitor.java
- modules/library/main/src/main/java/org/geotools/feature/visitor/StandardDeviationVisitor.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDialect.java
See also: https://osgeo-org.atlassian.net/browse/GEOT-3322
> [GEOT-3322] Add native support for average and stddev aggregate functions in jdbc data stores

- docs/user/unsupported/process/process-feature.rst
- modules/library/main/src/main/java/org/geotools/feature/collection/PushBackFeatureIterator.java
- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/GroupCandidateSelectionProcess.java
- modules/unsupported/process-feature/src/main/resources/META-INF/services/org.geotools.process.vector.VectorProcess
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/GroupCandidateSelectionProcessTest.java
- modules/unsupported/process-feature/src/test/resources/org/geotools/process/vector/test-data/featuresToGroup.properties
[GEOT-6726] Add new FilteringVectorProcess
#3187
> [backport-24.x][GEOT-6726]Add new FilteringVectorProcess

- docs/user/unsupported/process/process-feature.rst
- modules/library/main/src/main/java/org/geotools/feature/collection/PushBackFeatureIterator.java
- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/GroupCandidateSelectionProcess.java
- modules/unsupported/process-feature/src/main/resources/META-INF/services/org.geotools.process.vector.VectorProcess
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/GroupCandidateSelectionProcessTest.java
- modules/unsupported/process-feature/src/test/resources/org/geotools/process/vector/test-data/featuresToGroup.properties
[GEOT-6726] Add new FilteringVectorProcess
#3187
> [backport-23.x][GEOT-6726]Add new FilteringVectorProcess 

- modules/unsupported/cql-json/pom.xml
- modules/unsupported/cql-json/src/main/java/org/geotools/filter/text/cqljson/CQLJson.java
- modules/unsupported/cql-json/src/main/java/org/geotools/filter/text/cqljson/CQLJsonCompiler.java
- modules/unsupported/cql-json/src/main/java/org/geotools/filter/text/cqljson/CQLJsonCompilerFactory.java
- modules/unsupported/cql-json/src/main/java/org/geotools/filter/text/cqljson/CQLJsonFilterBuilder.java
- modules/unsupported/cql-json/src/main/java/org/geotools/filter/text/cqljson/MapToOpenGISGeomUtil.java
- modules/unsupported/cql-json/src/test/java/org/geotools/filter/text/cqljson/CQLJsonParsingTest.java
- modules/unsupported/cql-json/src/test/resources/cqlJsonTest.json
- [x ] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md) 
- [ x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.
- [x ] The changes are not breaking the build in downstream projects using SNAPSHOT …
> converted to checked and JTS

- modules/plugin/jdbc/jdbc-sqlserver/pom.xml
- pom.xml
All of these have had some patch releases, so they should be upgraded.
```
com.oracle.database.jdbc:ojdbc8 ................. 19.7.0.0 -> 19.8.0.0
org.postgresql:postgresql ......................... 42.2.14 -> 42.2.18
com.microsoft.sqlserver:mssql-jdbc .......... 8.2.2.jre8 -> 8.4.1.jre8
```
also move SQL Server drivers into `dependencyManagement` section
resolves https://osgeo-org.atlassian.net/browse/GEOT-6737
The following are required only for core and extension modules (they are welcomed, but …
> [GEOT-6737] Update PostgreSQL (to 42.2.18), Oracle (to 19.8.0.0) and MS SQL Server (to 8.4.1.jre8) JDBC drivers

- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/GroupCandidateSelectionProcess.java
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/GroupCandidateSelectionProcessTest.java
- modules/unsupported/process-feature/src/test/resources/org/geotools/process/vector/test-data/featuresToGroupWithNullValues.properties
> [23.x backport][GEOT-6732] GroupCandidateSelection RT throws NPE if operation attribute return null

- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/GroupCandidateSelectionProcess.java
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/GroupCandidateSelectionProcessTest.java
- modules/unsupported/process-feature/src/test/resources/org/geotools/process/vector/test-data/featuresToGroupWithNullValues.properties
> [24.x backport][GEOT-6732] GroupCandidateSelection RT throws NPE if operation attribute return null

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeature.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedMapping.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/complex/MongoComplexUtilitiesTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoComplexUtilitiesTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6738
this pr fix a bug with MongoComplexFeatures not being reprojected.
> [GEOT-6738] Mongo ComplexFeatures are not reprojected

- pom.xml
Set up the [maven-enforcer-plugin](https://maven.apache.org/enforcer/index.html)  as part of the QA build.
as discussed in #3201 
1.  since the enforcer rules are processed before the build actually starts this could be a default option on all the build servers; that way these servers don't get bogged down by long builds (might not make friends with that)
Submitting the …
> Set-up of the maven-enforcer-plugin in the QA profile

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeature.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedMapping.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/complex/MongoComplexUtilitiesTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoComplexUtilitiesTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
> [23.x backport][GEOT-6738] Mongo ComplexFeatures are not reprojected

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeature.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java
- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedMapping.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/complex/MongoComplexUtilitiesTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoComplexUtilitiesTest.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
> [24.x backport][GEOT-6738] Mongo ComplexFeatures are not reprojected

- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/GroupCandidateSelectionProcess.java
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/GroupCandidateSelectionProcessTest.java
- modules/unsupported/process-feature/src/test/resources/org/geotools/process/vector/test-data/featuresToGroupWithGroupAllNull.properties
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6739
- This pr fix a problem with GroupCandidateSelection process, making it returning a feature aslso if in a defined group the operationValue is always NULL for all the members.
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or …
> [GEOT-6739] GroupCandidateSelectionProcess should return feature with null attribute

- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/GroupCandidateSelectionProcess.java
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/GroupCandidateSelectionProcessTest.java
- modules/unsupported/process-feature/src/test/resources/org/geotools/process/vector/test-data/featuresToGroupWithGroupAllNull.properties
> [24.x backport][GEOT-6739] GroupCandidateSelectionProcess should return feature with null attribute

- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/GroupCandidateSelectionProcess.java
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/GroupCandidateSelectionProcessTest.java
- modules/unsupported/process-feature/src/test/resources/org/geotools/process/vector/test-data/featuresToGroupWithGroupAllNull.properties
> [23.x backport][GEOT-6739] GroupCandidateSelectionProcess should return feature with null attribute

- .travis.yml
- .travis/setup-mysql.sh
- .travis/start-mysql.sh
- docs/developer/conventions/test/online.rst
- docs/user/library/jdbc/mysql.rst
- modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDataStoreFactory.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDialect.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDialectBasic.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDialectPrepared.java
- modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLFilterToSQL.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLAggregateTestSetup.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLDataStoreAPITestSetup.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLDataStoreAutoEnhandedSpatialSupportTest.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLDataStoreFactoryTest.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLDataStoreManualEnhandedSpatialSupportTest.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLEmptyTestSetup.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLJoinTestSetup.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLNoPrimaryKeyTestSetup.java
- modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLTestSetup.java
- pom.xml
Brings support for MySQL 8 (which now has some sort of Geography datatype)
- [GEOT-6690](https://osgeo-org.atlassian.net/browse/GEOT-6690) - support MySQL 8
- [GEOT-6692](https://osgeo-org.atlassian.net/browse/GEOT-6692) - upgrade driver
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or …
> [GEOT-6690] [GEOT-6692] MySQL 8 support + JDBC driver update

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WMTSSpecification.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/WebMapTileServer.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/model/WMTSCapabilities.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/model/WMTSLayer.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/GetTileRequest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java
- modules/extension/wmts/src/test/resources/test-data/linz.xml
> Backport to 24.x [GEOT-6741] WMTS requests can fail with a NPE if the getCapabilities

- modules/library/main/src/main/java/org/geotools/filter/visitor/PostPreProcessFilterSplittingVisitor.java
- modules/library/main/src/test/java/org/geotools/filter/visitor/PostPreProcessFilterSplittingVisitorTest.java
[GEOT-6746] PostPreProcessingFilter indexOutOfBoundsException
> [2.14.x backport][GEOT-6746] PostPreProcessingFilter indexOutOfBoundsException

- modules/library/main/src/main/java/org/geotools/filter/visitor/PostPreProcessFilterSplittingVisitor.java
- modules/library/main/src/test/java/org/geotools/filter/visitor/PostPreProcessFilterSplittingVisitorTest.java
[GEOT-6746] PostPreProcessingFilter indexOutOfBoundsException
> [23.x backport][GEOT-6746] PostPreProcessingFilter indexOutOfBoundsException

- pom.xml
Brings in an improved BufferedImageAdapter, with better scalability (for GWC/GS to use)
> Upgrading to jai-ext 1.1.18

- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Configuration.java
- modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Schemas.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/RendererUtilities.java
- modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java
Still a work in progress, may not pass the QA checks yet due to new generic types being added. Will fix before merge.
> Some type clarifications to assist the GeoServer unchecked warnings branch

- .github/workflows/geopkg_online.yml
- .github/workflows/mssql_online.yml
- .github/workflows/mysql_online.yml
- .github/workflows/oracle_online.yml
- .github/workflows/postgis_online.yml
and not just on the master branch.
> Make sure the online tests also run after a new branch is created

- modules/unsupported/mbtiles/src/main/java/org/geotools/mbtiles/MBTilesFeatureSource.java
- modules/unsupported/mbtiles/src/test/java/org/geotools/mbtiles/MBTilesFeatureSourceTest.java
See https://osgeo-org.atlassian.net/browse/GEOT-6751
This is to better support the use case of having vectort tiles as input to produce more vector tiles. It's a stepping stone, more changes are likely needed to get that going properly IMHO.
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not …
> [GEOT-6751] MBTilesFeatureSource should offer support for Hinsts.GEOMETRY_DISTANCE as well

- .gitignore
It's quite easy to setup and work with the documentation for Geotools within MS Visual Studio Code. But some files are created within the file structure that doesn't necessarily need to be a part of the repository.
No need for this I assume.
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not …
> Git ignore for docs work in MS Visual Studio Code

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISPartitionedTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISPartitionedTestSetup.java
See https://osgeo-org.atlassian.net/browse/GEOT-6743
> [GEOT-6743] Unable to obtain (PostGIS) parent PARTITION TABLE

- pom.xml
Batik has resolved CVE-2019-17566 (a SSRF vulnerability) in 1.13
resolves [GEOT-6765](https://osgeo-org.atlassian.net/browse/GEOT-6765)
> [GEOT-6765] Update Batik libraries from 1.10 to 1.13

- pom.xml
The sqlite-jdbc team fixed a number of vulnerabilitie in the native code parts (see https://github.com/xerial/sqlite-jdbc/issues/501) in version 3.32.3. Also support for the new Apple Silicon (M1) was added in 3.32.3.3 as wel as some Arm Cortex improvements
see also: https://github.com/xerial/sqlite-jdbc/blob/master/README.md#news
reolves [GEOT-6766](https://osgeo-org.atlassian.net/browse/GEOT-6766)
The following are required only for core and extension modules (they are welcomed, but not …
> [GEOT-6766] Update sqlite-jdbc from 3.31.1 to 3.34.0

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISPartitionedTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISPartitionedTestSetup.java
> [GEOT-6743] Unable to obtain (PostGIS) parent PARTITION TABLE (23.x backport)

- modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISPartitionedTest.java
- modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISPartitionedTestSetup.java
> [GEOT-6743] Unable to obtain (PostGIS) parent PARTITION TABLE (24.x backport)

- modules/unsupported/mbtiles/pom.xml
- pom.xml
In the Jackson project the following CVE was fixed:
- CVE-2020-25649
as well as various bugfixes in the use libs. See:
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10
resolves [GEOT-6767](https://osgeo-org.atlassian.net/browse/GEOT-6767) …
> [GEOT-6767] Update Jackson 2 libraries from 2.10.1 to 2.10.5 / 2.10.5.1

- modules/extension/brewer/src/main/java/org/geotools/brewer/styling/builder/ColorMapEntryBuilder.java
- modules/library/cql/src/main/java/org/geotools/filter/text/commons/ExpressionToText.java
- modules/library/cql/src/test/java/org/geotools/filter/text/cql2/CQLExpressionTest.java
- modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
- modules/unsupported/css/src/test/java/org/geotools/styling/css/ParserSyntheticTest.java
Supporting CQL Expressions in ColorMapEntries attributes on CSS so that they get preserved when translated to SLD
> [GEOT-6762]: CSS to SLD translation supporting ColorMapEntries with CQL Expression

- modules/library/coverage/pom.xml
- modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/MaskOverviewProvider.java
- modules/plugin/geotiff/pom.xml
- modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffFormat.java
- modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java
- modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderCogOnlineTest.java
- pom.xml
Backporting to 24.x COG GeoTIFF support
> [Backport 24.x][GEOT-6715]: COG Support in GeoTIFF 

- pom.xml
The Apache project has resolved CVE-2020-13956
resolves: https://osgeo-org.atlassian.net/browse/GEOT-6770
see also: https://github.com/geoserver/geoserver/pull/4615
> [GEOT-6770] Update Apache HTTP components to 4.5.13

- pom.xml
> [23.x backport][GEOT-6770] Update Apache HTTP components to 4.5.13

- pom.xml
> [24.x backport][GEOT-6770] Update Apache HTTP components to 4.5.13

- pom.xml
Guava fixed CVE-2020-8908 (a temp directory creation vulnerability)
resolves https://osgeo-org.atlassian.net/browse/GEOT-6771
> [GEOT-6771] Update Guava to 30.1-jre

- pom.xml
> [23.x backport][GEOT-6771] Update Guava to 30.1-jre

- pom.xml
> [24.x backport][GEOT-6771] Update Guava to 30.1-jre

- pom.xml
Updating to imageio-ext 1.3.5 to get in a minor bug fix on COG urls parsing.
> Updating to imageio-ext 1.3.5 version

- modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/utilities/NetCDFUtilities.java
Fixes just a minor typo which is shown if log-level is finer.
> fixes minor typo

- modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/Contours.java
Fixes minor PMD issue introduced in https://github.com/geotools/geotools/commit/47f37b5c0dca09db3e14a3c2aae6b82f481fd5c5#diff-82c9c554a657dc303ce9e370189ea176ec7c148f86ee7a7602bf8b3c26be67fdR72
- [N/A] There is an issue in [Jira](https://osgeo-org.atlassian.net/projects/GEOT) describing the bug/task/new feature (a notable exemptions is, changes not visible to end users). The ticket is for the GeoTools project, if the issue was found elsewhere it's a good practice to link to the origin ticket/issue.
- [N/A] Commit message(s) must be in the form "[GEOT-XYZW] Title of the Jira ticket"
- [N/A] New unit tests have been added covering the changes
- [N/A] Documentation …
> fix (process-feature): fix PMD diamond bracket issue

- modules/unsupported/elasticsearch/pom.xml
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticFeatureReader.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticParserUtil.java
- modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/FilterToElastic.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFilterTest.java
- modules/unsupported/elasticsearch/src/test/java/org/geotools/process/elasticsearch/NestedAggGeoHashGridTest.java
- pom.xml
Bump:
- elasticsearch from 7.4.0 to 7.5.10
- spring-security-core from 5.1.5.RELEASE to 5.1.13.RELEASE
in the unsupported elasticsearch module.
Elasticsearch resolved CVE-2020-7009, CVE-2020-7014, CVE-2020-7019, CVE-2020-7020
Spring resolved CVE-2020-5398, CVE-2020-5421, CVE-2020-5408
/cc @sjudeng 
Submitting the PR does not require you to check all items, but by the time …
> Update Elasticsearch libraries

- modules/library/main/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreTest.java
- pom.xml
Signed-off-by: Jim Hughes <jnh5y@ccri.com>
> [GEOT-6778] Upgrade to JTS Topology Suite 1.18.0

- docs/developer/procedures/build_server.rst
Small doc fix I noticed while reviewing the project procedures
> Update Linux Build server link to build.geoserver.org and remove deprecated links

- modules/plugin/imagemosaic/pom.xml
- modules/unsupported/solr/pom.xml
- pom.xml
Solr resolved CVE-2017-3164, CVE-2018-11802, CVE-2018-1308, CVE-2018-8010, CVE-2018-8026, CVE-2019-0193, CVE-2019-17558, CVE-2020-13941, CVE-2020-13957 and CVE-2019-0201 (from zookeeper).
This upgrade drags in a number of Jetty libs as transitve dependency, compare
https://search.maven.org/artifact/org.apache.solr/solr-solrj/8.7.0/jar
with 
https://search.maven.org/artifact/org.apache.solr/solr-solrj/7.2.1/jar
which raise some flags for known vulnerabilities (CVE-2019-17638, CVE-2020-27216, CVE-2020-27218 that appear only relevant for running jetty instances), not sure what the best way to handle that is?  
We could exclude or override with a current version, or leave as is and wait for solr to catch up with their jetty dependency
> Reviewing is a process done by project maintainers, …
> [GEOT-6787] Bump solrj from 7.2.1 to 8.7.0 in (unsupported) gt-solr

- modules/extension/tile-client/pom.xml
- modules/extension/tile-client/src/main/java/org/geotools/tile/Tile.java
- modules/extension/tile-client/src/main/java/org/geotools/tile/TileService.java
- modules/extension/tile-client/src/main/java/org/geotools/tile/impl/bing/BingTile.java
- modules/extension/tile-client/src/main/java/org/geotools/tile/impl/osm/OSMTile.java
- modules/extension/tile-client/src/test/java/org/geotools/tile/impl/osm/OSMServiceOnlineTest.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTile.java
Moved ImageLoading to TileService instead of Tile. And using HTTPClient to ensure we have an InputStream pointing to an image.
> GEOT-6757 : Tile client throwing exception while downloading

- docs/user/library/data/wfs-ng.rst
Simple typo fix in code example
> Fix typo and improve readability

- modules/extension/tile-client/pom.xml
- modules/extension/tile-client/src/main/java/org/geotools/tile/Tile.java
- modules/extension/tile-client/src/main/java/org/geotools/tile/TileService.java
- modules/extension/tile-client/src/main/java/org/geotools/tile/impl/bing/BingTile.java
- modules/extension/tile-client/src/main/java/org/geotools/tile/impl/osm/OSMTile.java
- modules/extension/tile-client/src/test/java/org/geotools/tile/impl/osm/OSMServiceOnlineTest.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTile.java
Fixing a bug in tile-client when url is pointing at something else than an image.
- [ X] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md)
- [X ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
Submitting the PR does …
> [GEOT-6757] Backporting to 24.x

- modules/extension/tile-client/pom.xml
- modules/extension/tile-client/src/main/java/org/geotools/tile/Tile.java
- modules/extension/tile-client/src/main/java/org/geotools/tile/TileService.java
- modules/extension/tile-client/src/main/java/org/geotools/tile/impl/bing/BingTile.java
- modules/extension/tile-client/src/main/java/org/geotools/tile/impl/osm/OSMTile.java
- modules/extension/tile-client/src/test/java/org/geotools/tile/impl/osm/OSMServiceOnlineTest.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/client/WMTSTile.java
GEOT-6757 : Tile client throwing exception while downloading
- [X ] Confirm you have read the [contribution guidelines](https://github.com/geotools/geotools/blob/master/CONTRIBUTING.md)
- [ X] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in documentation)
Submitting the PR does not require you to …
> [GEOT-6757] Backporting to 23.x

- pom.xml
Updating jai-ext to 1.1.19 to include this fix: https://github.com/geosolutions-it/jai-ext/issues/175
The fix is about transparent color encofing is paletted images (e.g. PNG8)
> [GEOT-6793]: updated jai-ext to 1.1.19

- pom.xml
The Elastic Search project resolved CVE-2021-22132 in 7.10.2
Resolves [GEOT-6795](https://osgeo-org.atlassian.net/browse/GEOT-6795)
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or not …
> [GEOT-6795] Update elasticsearch-rest-client to 7.10.2

- build/qa/dependency-check-suppression.xml
- pom.xml
update this Maven plugin to the currently supported release
> Bump org.owasp:dependency-check-maven plugin

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccessFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureCollection.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java
This pr 
- add the capability for AppSchema to count also when Filter with nested attributes are involved;
- provide a new store parameter for AppSchema to enable the count (disabled by default);
Jira ticket: https://osgeo-org.atlassian.net/browse/GEOT-6794
- online integration tests provided in this pr https://github.com/geoserver/geoserver/pull/4676
The following are required only for core and extension modules (they are welcomed, but not required, for …
> [GEOT-6794] AppSchema count works for filter with root attribute only

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccessFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureCollection.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java
* [GEOT-6794] AppSchema count works for filter with root attribute only
* review feedback applied
> [23.x backport][GEOT-6794] AppSchema count works for filter with root attribute only

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccessFactory.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureCollection.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java
* [GEOT-6794] AppSchema count works for filter with root attribute only
* review feedback applied
> [24.x backport][GEOT-6794] AppSchema count works for filter with root attribute only

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6803
This pr fix a bug occuring when querying trough a cql_filter an app-schema store that doesn't have in mappings IdExpression.
Online integration test are provided in a geoserver pr see https://osgeo-org.atlassian.net/browse/GEOS-9891
Submitting the PR does not require you to …
> [GEOT-6803] AppSchema queries fails when mappings has no IdExpression

- modules/library/referencing/src/main/java/org/geotools/referencing/crs/DefaultGeographicCRS.java
- modules/library/referencing/src/test/java/org/geotools/referencing/PredefinedObjectsTest.java
- modules/library/referencing/src/test/resources/org/geotools/referencing/factory/epsg/epsg.properties
- modules/plugin/epsg-hsql/src/test/java/org/geotools/referencing/factory/epsg/hsql/LongitudeFirstFactoryOverrideTest.java
- modules/plugin/epsg-hsql/src/test/resources/org/geotools/referencing/factory/epsg/epsg_operations.properties
See https://osgeo-org.atlassian.net/browse/GEOT-6806
> [GEOT-6806] Add identifier to DefaultGeographicCRS.WGS84

- pom.xml
keep this maven pugin up-to-date eventhough it is currently not used in any CI jobs
> Update dependency-check-maven plugin to 6.1.1

- modules/library/main/src/main/java/org/geotools/renderer/crs/ProjectionHandler.java
- modules/library/referencing/src/main/java/org/geotools/referencing/operation/transform/WarpBuilder.java
- modules/library/referencing/src/test/java/org/geotools/referencing/operation/transform/WarpBuilderTest.java
- modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java
See https://osgeo-org.atlassian.net/browse/GEOT-6807 for details
> [GEOT-6807] Enabling densification on reprojection can cause OOMs with large/complex geometries, and requests hitting small areas

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
Integration test on gs pr https://github.com/geoserver/geoserver/pull/4712
> [23.x backport][GEOT-6803] AppSchema queries fails when mappings has no IdExpression

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
Integration test on gs pr https://github.com/geoserver/geoserver/pull/4711
> [24.x backport] [GEOT-6803] AppSchema queries fails when mappings has no IdExpression

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
This pr fixes a bug caused by getFeature with startIndex param to fail when app-schema mappings doesn't have an IdExpression.
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6804
> [GEOT-6804] AppSchema fails when pagination occurs and mappings doesn't have IdExpression

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6794
Integration test geoserver side see: https://osgeo-org.atlassian.net/browse/GEOS-9913
> [GEOT-6813] AppSchema inconsistent count result when maxFeature is specified in the query

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
> [24.x backport][GEOT-6813] AppSchema inconsistent count result when maxFeature is specified in the query

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
> [23.x backport][GEOT-6813] AppSchema inconsistent count result when maxFeature is specified in the query

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6814
> [GEOT-6814] AppSchema count query joins wrong table with Binary Filter

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java
> [23.x backport][GEOT-6814] AppSchema count query joins wrong table with Binary Filter

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningQuery.java
> [24.x backport][GEOT-6814] AppSchema count query joins wrong table with Binary Filter

- docs/developer/conventions/test/online.rst
> Update online testing doc with a note about running a Db2 docker container

- pom.xml
Includes this fix: geosolutions-it/jai-ext#278
The fix is related to color encoding in paletted images
> [GEOT-6818] update jaiext to 1.1.20

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/map/WMTSCoverageReader.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/map/WMTSCoverageReaderTest.java
- modules/extension/wmts/src/test/resources/test-data/GetCapaJPEGOnly.xml
This pr fixes a bug causing getTiles requests to fail when getCapabilities doesn't have template request for image/png output format.
Jira ticket https://osgeo-org.atlassian.net/browse/GEOT-6820
> [GEOT-6820] WMTS REST regression for getCapabilities not having templates for image/png outputformat

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
> [24.x backport][GEOT-6804] AppSchema fails when pagination occurs and mappings doesn't have IdExpression

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java
> [23.x backport][GEOT-6804] AppSchema fails when pagination occurs and mappings doesn't have IdExpression 

- modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java
- modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
Fixes https://osgeo-org.atlassian.net/browse/GEOT-5908
Hookup a mongodb connection, verify at the world queries there are no longer errors returned
> [GEOT-5908] MongoDB plugin should handle Envelopes with coordinates out of MongoDB bounds

- pom.xml
Update PostgreSQL and Oracle and MS SQL Server JDBC drivers:
```
org.postgresql:postgresql .................. 42.2.18 -> 42.2.19
com.microsoft.sqlserver:mssql-jdbc ... 8.4.1.jre8 -> 9.2.0.jre8
com.oracle.database.jdbc:ojdbc8 ..........19.8.0.0 -> 19.10.0.0
```
Submitting the PR does not require you to check all items, but by the time it …
> [GEOT-6822][GEOT-6823][GEOT-6824] Update JDBC drivers: PostgreSQL (to 42.2.19), MS SQL Server (to 9.2.0.jre8), Oracle (to 19.10.0.0)

- pom.xml
Update PostgreSQL and Oracle and MS SQL Server JDBC drivers:
```
org.postgresql:postgresql .................. 42.2.18 -> 42.2.19
com.microsoft.sqlserver:mssql-jdbc ... 8.4.1.jre8 -> 9.2.0.jre8
com.oracle.database.jdbc:ojdbc8 ..........19.8.0.0 -> 19.10.0.0
```
backports #3371  to 24.x
see also https://github.com/geoserver/geoserver/pull/4793
The following are required only for core and extension modules (they are welcomed, but not required, for unsupported …
> [Backport 24.x][GEOT-6822][GEOT-6823][GEOT-6824] Update JDBC drivers: PostgreSQL (to 42.2.19), MS SQL Server (to 9.2.0.jre8), Oracle (to 19.10.0.0)

- modules/library/xml/pom.xml
- modules/library/xml/src/test/java/org/geotools/xml/DocumentFactoryTest.java
- modules/unsupported/wfs-ng/pom.xml
- pom.xml
Upgrade mockito from 2.23.0 (Oct, 2018) to 3.8.0 (Feb, 2021)
> [GEOT-6826] Upgrade mockito version to 3.8.0 and unify declarations

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSDataAccessFactory.java
> Fix typo and remove double semicolon

- modules/unsupported/geojsonstore/src/main/java/com/bedatadriven/jackson/datatype/jts/JtsModule.java
- modules/unsupported/geojsonstore/src/main/java/com/bedatadriven/jackson/datatype/jts/JtsModule3D.java
- modules/unsupported/geojsonstore/src/main/java/com/bedatadriven/jackson/datatype/jts/serialization/GeometrySerializer.java
- modules/unsupported/geojsonstore/src/main/java/org/geotools/data/geojson/GeoJSONWriter.java
- modules/unsupported/geojsonstore/src/test/java/com/bedatadriven/jackson/datatype/jts/BaseJtsModuleTest.java
- modules/unsupported/geojsonstore/src/test/java/com/bedatadriven/jackson/datatype/jts/D3DPointTest.java
- modules/unsupported/geojsonstore/src/test/java/com/bedatadriven/jackson/datatype/jts/GeometryCollectionParserTest.java
- modules/unsupported/geojsonstore/src/test/java/com/bedatadriven/jackson/datatype/jts/JtsModuleTest.java
- modules/unsupported/geojsonstore/src/test/java/com/bedatadriven/jackson/datatype/jts/MultiPointTest.java
- modules/unsupported/geojsonstore/src/test/java/com/bedatadriven/jackson/datatype/jts/PointTest.java
- modules/unsupported/geojsonstore/src/test/java/org/geotools/data/geojson/AxisOrderTest.java
- modules/unsupported/geojsonstore/src/test/java/org/geotools/data/geojson/GeoJSONWriteTest.java
> [GEOT-6650] Add limit on number of decimal places in coordinates

- modules/extension/xsd/xsd-gml2/src/test/java/org/geotools/gml2/bindings/GMLLinearRingTypeBindingTest.java
- modules/library/main/src/main/java/org/geotools/geometry/jts/WKBReader.java
- modules/library/main/src/test/java/org/geotools/renderer/crs/ProjectionHandlerTest.java
- modules/plugin/geopkg/src/main/java/org/geotools/geopkg/geom/GeoPkgGeomReader.java
- modules/plugin/jdbc/jdbc-db2/src/main/java/org/geotools/data/db2/DB2NGDataStoreFactory.java
- modules/plugin/jdbc/jdbc-db2/src/main/java/org/geotools/data/db2/DB2WKBReader.java
- modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/reader/SqlServerBinaryReader.java
- modules/plugin/jdbc/jdbc-teradata/src/main/java/org/geotools/data/teradata/WKBAttributeIO.java
- pom.xml
Signed-off-by: Jim Hughes <jhughes@ccri.com>
> [GEOT-6827] Upgrade to JTS Topology Suite 1.18.1

- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/map/WMTSCoverageReader.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java
- modules/extension/wmts/src/test/java/org/geotools/ows/wmts/map/WMTSCoverageReaderTest.java
- modules/extension/wmts/src/test/resources/test-data/GetCapaJPEGOnly.xml
> [24.x backport][GEOT-6820] WMTS REST regression for getCapabilities not having templates for image/png outputformat

- docs/spelling/local.dict
- docs/user/welcome/upgrade.rst
- modules/extension/app-schema/app-schema/src/test/resources/test-data/mappedPolygons.xml
- modules/library/main/src/test/java/org/geotools/data/util/TemporalConverterFactoryTest.java
- pom.xml
Remove remaining vestiges of the ArcSDE plugin
- `com.ibm.icu:icu4j` dependency declaratio in root pom
- mentions in the docs/ folder
- commented out XML snippet
- Mention in test case that's not really tied up to sde
Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied …
> [GEOT-6798] Remove remaining vestiges of the ArcSDE plugin

- build/qa/pmd-ruleset.xml
- modules/extension/mbstyle/src/test/java/org/geotools/mbstyle/MapboxTestUtils.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/model/WMTSService.java
- modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java
- modules/library/main/src/test/java/org/geotools/feature/simple/SimpleFeatureBuilderTest.java
- modules/library/xml/src/test/java/org/geotools/xml/styling/StyleFactoryImplTest.java
- modules/plugin/csv/src/main/java/org/geotools/data/csv/CSVFileState.java
- modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/metadata/MetadataImport.java
- modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/shp/ZMHandlersTest.java
- modules/unsupported/cql-json/src/main/java/org/geotools/filter/text/cqljson/CQLJsonCompiler.java
- modules/unsupported/geojsonstore/src/test/java/org/geotools/data/geojson/AxisOrderTest.java
- modules/unsupported/geojsonstore/src/test/java/org/geotools/data/geojson/GeoJSONReaderTest.java
- modules/unsupported/ogcapi-client/src/main/java/org/geotools/ogcapi/CollectionType.java
- modules/unsupported/ogcapi-client/src/test/java/org/geotools/ogcapi/LayerDialog.java
- modules/unsupported/ogcapi-client/src/test/java/org/geotools/ogcapi/QuickTileViewer.java
- modules/unsupported/process-feature/src/test/java/org/geotools/process/vector/ContourProcessTest.java
- modules/unsupported/swing/src/main/java/org/geotools/swing/locale/PropertiesFileFinder.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/VPFFeatureClass.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/VPFLibrary.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/file/VPFFile.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/file/VPFFileStore.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/io/TripletId.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/io/VPFDate.java
- modules/unsupported/vpf/src/main/java/org/geotools/data/vpf/util/PrimitiveDataFactory.java
- modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/WFSFeatureStoreTest.java
Adds a new rule to the QA checks to prevent use of `Exception#printStackTrace()`
> [GEOT-6831] Add a PMD ruleset to avoid Exception#PrintStackTrace() usage

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java
> [GEOT-6832] WFS-NG doesn't apply acrgis strategy for versions that are not 2.0.0

- modules/unsupported/flatgeobuf/pom.xml
- modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatgeobufDataStore.java
- modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatgeobufFeatureWriter.java
- modules/unsupported/flatgeobuf/src/main/java/org/geotools/data/flatgeobuf/FlatgeobufWriter.java
Upgrade flatgeobuf 3.4.0 -> 3.10.1, follow up to https://github.com/geoserver/geoserver/pull/4819
> Upgrade flatgeobuf 3.4.0 -> 3.10.1

- modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java
> Backport [GEOT-6832] WFS-NG doesn't apply acrgis strategy for versions that are not 2.0.0

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/integration.yml
- CONTRIBUTING.md
- build/release/build_release.sh
- build/release/functions
- build/release/properties
- docs/developer/conventions/test/online.rst
- docs/developer/procedures/contribute.rst
- docs/developer/procedures/git.rst
- docs/developer/procedures/pull_requests.rst
- docs/developer/procedures/release.rst
- docs/developer/procedures/stable.rst
- docs/user/build/git.rst
- docs/user/build/maven/snapshots.rst
- docs/user/build/source.rst
- docs/user/library/coverage/geotiff.rst
- docs/user/library/referencing/extension.rst
- docs/user/library/referencing/wkt.rst
- docs/user/tutorial/map/style.rst
- docs/user/welcome/application.rst
- docs/user/welcome/faq.rst
Replace references to the master branch by main. After renaming `master` to `main`, there are several references to the main branch as `master`, in docs and scripts.
Relates to https://github.com/geoserver/geoserver/pull/4826
--- …
> [GEOT-6834] Replace references to the master branch by main

- modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/XPath.java
- modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/filter/XPathTest.java
> GEOT-6812 App-schema feature chaining by xlink on nested property fails
