geotools/geotools

modules/unsupported/csv/src/main/java/org/geotools/data/csv/CSVFeatureSource.java, modules/unsupported/csv/src/test/java/org/geotools/data/csv/CSVDataStoreTest.java
When #654 was merged, the CSVDataStore tests were not included as that module had been changed recently. This adds these tests to the new CSV module.
Based on the new tests, fixed getCountInternal to use internal reader.
=> Added Limit and Offset tests to CSVDataStore

docs/src/main/java/org/geotools/tutorial/csv2/CSVDataStore.java, docs/src/main/java/org/geotools/tutorial/csv2/CSVDataStoreFactory.java, docs/src/main/java/org/geotools/tutorial/csv2/CSVFeatureReader.java, docs/src/main/java/org/geotools/tutorial/csv2/CSVFeatureSource.java, docs/src/main/java/org/geotools/tutorial/csv2/CSVFeatureStore.java, docs/src/main/java/org/geotools/tutorial/csv2/CSVFeatureWriter.java, docs/src/main/java/org/geotools/tutorial/csv2/CSVWriteTest.java, modules/library/api/src/main/java/org/geotools/data/AutoCommitTransaction.java, modules/library/api/src/main/java/org/geotools/data/Transaction.java, modules/library/data/.gitignore, modules/library/data/src/main/java/org/geotools/data/store/ContentDataStore.java, modules/library/data/src/main/java/org/geotools/data/store/ContentFeatureStore.java, modules/library/data/src/main/java/org/geotools/data/store/DiffContentFeatureWriter.java, modules/library/data/src/main/java/org/geotools/data/store/DiffTransactionState.java, modules/library/data/src/test/java/org/geotools/data/store/ContentFeatureSourceEventsTest.java
Added diffWriter method to provide wrapper for ContentFeatureStore writer.
Fixed misc bugs:
- Added transaction to store in DiffTransactionState.commit()
- Brought locking wrapper outside of if statement in ContentFeatureStore.getWriter()
- Tweaked ContentFeatureSourceEventsTest.java to match current results. It is now closer to expected behaviour (Although event handling still needs to be overhauled)
=> ContentFeatureStore writer flag for commit

modules/library/data/src/main/java/org/geotools/data/store/ContentFeatureSource.java, modules/library/main/src/main/java/org/geotools/feature/FeatureTypes.java, modules/library/main/src/test/java/org/geotools/feature/FeatureTypesTest.java
https://jira.codehaus.org/browse/GEOT-4978
ContentFeatureSource.getSchema() would sometimes give a different value for default geometry than reader.getFeatureType().
This only occurs if the data store contains multiple geometries, with no geometry explicitly defined as the default geometry. It appears that getSchema was somehow getting a differently ordered list of attributes than the reader.  Because this error does not occur predictably, I am not sure that a viable test case for this issue is possible.
=> Fix typing on retype, previously could get different defaultGeometry values

modules/library/data/src/main/java/org/geotools/data/store/ContentFeatureSource.java
Feature id is now obtained from the keySet so that it still works with deleted features.
=> Fix getBounds for diff containing deleted features

docs/user/library/main/data.rst, modules/library/data/src/main/java/org/geotools/data/store/ContentFeatureSource.java, modules/library/main/src/main/java/org/geotools/data/DataUtilities.java, modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
DataUtilities.mixQueries modified to simplify filters.
DataUtilities.simplifyFilter(Query) method added to simplify the filter contained by a query.
=> ContentFeatureSource simplifies all filters within all passed queries.

modules/unsupported/feature-aggregate/src/test/java/org/geotools/data/aggregate/AggregatingDataStoreTest.java
FeatureSource.getBounds is not guaranteed to return a result (eg. if a full feature scan is needed). Updated to use FeatureCollection.getBounds.
=> Updating bounds test for compatibility with PropertyFeatureSource (NG) and ContentFeatureSource

modules/extension/app-schema/app-schema/src/main/java/org/geotools/filter/NestedAttributeExpression.java
See GEOT-4891: NestedAttributeExpresionImpl is incompatible with DuplicatingFilterVisitor (https://jira.codehaus.org/browse/GEOT-4981)
Changes NestedAttributeExpression to overrides AttributeExpressionImpl.accept() and returen a copy of itself if visited by a DuplicatingFilterVisitor.
=> NestedAttributeExpresionImpl is incompatible with DuplicatingFilterVisitor (GEOT-4981)

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/AbstractWFSStrategy.java
wfs-ng module
There are unnecessary System.err.println calls in org.geotools.data.wfs.internal.AbstractWFSStrategy.java.  The text content being written to standard error is also being written out to log files.
I'm deploying GeoTools as a Jboss module and these calls cause the post contents of all WFS requests to be duplicated in the server.log file.  The first time it's recorded as INFO, but the second call (System.err.println) records it as ERROR.
These changes resolve GEOT-4914.
=> Remove unnecessary System.err.println calls

docs/src/main/java/org/geotools/tutorial/csv2/CSVFeatureWriter.java, modules/library/api/src/main/java/org/geotools/data/FeatureWriter.java, modules/library/data/src/main/java/org/geotools/data/memory/MemoryDataStore.java, modules/library/data/src/main/java/org/geotools/data/store/DiffContentFeatureWriter.java, modules/library/data/src/main/java/org/geotools/data/store/EventContentFeatureWriter.java, modules/library/data/src/test/java/org/geotools/data/memory/MemoryDataStoreTest.java, modules/library/main/src/main/java/org/geotools/data/DiffFeatureWriter.java, modules/library/main/src/main/java/org/geotools/data/FilteringFeatureWriter.java, modules/plugin/property/src/main/java/org/geotools/data/property/PropertyFeatureWriter.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureWriter.java, modules/unsupported/efeature/src/main/java/org/geotools/data/efeature/EFeatureWriter.java, modules/unsupported/property-old/src/main/java/org/geotools/data/property/old/PropertyFeatureWriter.java
QA consistency check:
* hasNext() returns false if the writer is closed
* next() throws an IOException if the writer is closed
A number of implementaitons set their internal reader/writer to null, then did not test this in next() or hasNext(), leading to NPEs. I have added checks for this.
Some other implementaitons would throw an IOException on hasNext() if the writer was closed. I have changed this to return false, for consistency.
The javadoc for the FeatureWriter interface has been updated to reflect these changes.
Test case(s) updated where applicable.
=> Fixed FeatureWriter next() and hasNext() implementations to conform to standard file handle behavior

modules/library/data/src/main/java/org/geotools/data/memory/MemoryDataStore.java, modules/library/data/src/main/java/org/geotools/data/memory/MemoryFeatureReader.java, modules/library/data/src/main/java/org/geotools/data/memory/MemoryFeatureSource.java, modules/library/data/src/main/java/org/geotools/data/memory/MemoryFeatureStore.java, modules/library/data/src/main/java/org/geotools/data/memory/MemoryFeatureWriter.java, modules/library/data/src/test/java/org/geotools/data/memory/MemoryDataStoreBoundsTest.java, modules/library/data/src/test/java/org/geotools/data/memory/MemoryDataStoreTest.java, modules/plugin/feature-pregeneralized/src/test/java/org/geotools/data/gen/AbstractPreGeneralizedFeatureSourceTest.java
Migrate MemoryDataStore to extend ContentDataStore. Seperated out FeatureSource and Reader/Writer as seperate files.
Updated tests to conform with new funtionality
Note: Events don't really work right now, event tests have been set to go against current behavior (This is a known issue of ContentDataStore)
Updated feature-pregeneralized tests to account for greater MemoryDataStore capabilities
=> Migrate MemoryDataStore to extend ContentDataStore

modules/unsupported/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java
This allows geopackage databases created by geotools to work with OGR and QGIS.
Closes issue #GEOT-4971.
=> Set a default extent in GeoPackage's gpkg_contents table

modules/extension/xsd/xsd-kml/src/main/java/org/geotools/kml/bindings/NameBinding.java, modules/extension/xsd/xsd-kml/src/test/java/org/geotools/kml/v22/KMLEncodingTest.java
Following the previous PR 604, this allows the kml:name for each placemark to be also dumped (if the featuretype of the features contains a name property) when generating KML 2.2 documents.
Testing: Unit tests adapted.
=> Adds kml:name element when dumping as KML 2.2

modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_numberFormat.java
Ensures server locale does not affect how numbers are converted to strings when evaluating CQL expressions.
=> Always use english DecimalFormatSymbols for CQL numberFormat() function

modules/library/api/src/main/java/org/geotools/data/Query.java, modules/library/data/pom.xml, modules/library/data/src/main/java/org/geotools/data/store/ContentFeatureSource.java, modules/library/data/src/test/java/org/geotools/data/memory/MemoryDataStoreBoundsTest.java, modules/library/data/src/test/java/org/geotools/data/memory/MemoryDataStoreTest.java
API Clarifications to Query javadoc.
Added forced CRS handling to ContentFeatureSource getBounds and getReader.
Added reprojection handling to getBounds.
Added test cases for forced CRS handling and reprojection to MemoryDataStore (the ContentFeatureSource test mocks are insufficient to test the changes to ContentFeatureSource). Also updated DataTestCase to use EPSG:4326 for the the river data set, to allow for testing tranformations and pre-assigned CRSs (Verified that this does not break any other test cases).
=> Added reprojection and forced CRS handling to ContentFeatureSource

modules/extension/graph/src/main/java/org/geotools/graph/traverse/standard/DijkstraIterator.java
Correct list of related edges when a directed graph is used (must use getOutRelated insted of getRelated)
=> Correction for bug on directed graphs

modules/library/data/src/main/java/org/geotools/data/store/ContentState.java, modules/library/data/src/test/java/org/geotools/data/memory/MemoryDataStoreTest.java, modules/library/data/src/test/java/org/geotools/data/store/ContentFeatureSourceEventsTest.java
Changed ContentState to issue events to only the current transaction on ROLLBACK, and only other transactions on COMMIT.
Fixed and improved ContentFeatureSourceEventsTest.java to test events properly. Added tests for CHANGED events and multiple changes in a batch event.
Fixed event tests for MemoryDataStore.
=> Fixed events implementation for ContentFeatureSource

modules/library/data/src/main/java/org/geotools/data/memory/MemoryDataStore.java
When updating MemoryDataStore to use ContentDataStore instead of AbstractDataStore, forgot to remove @Deprecated. Fixed here.
=> Remove @Deprecated from MemoryDataStore

modules/unsupported/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java
Solves issue #4996.
http://jira.codehaus.org/browse/GEOT-4996
GeoPackage encodes the SRID with the geometry, but currently it is not set on the Geometry with setSRID. 
Thanks,
Jared
=> GeoPackage should encode SRID with Geometry.

modules/unsupported/solr/src/main/java/org/geotools/data/solr/ExpressionToSolr.java, modules/unsupported/solr/src/main/java/org/geotools/data/solr/FilterToSolr.java, modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrAttribute.java, modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrDataStore.java, modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrFeatureReader.java, modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrFeatureSource.java, modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrSpatialStrategy.java, modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrUtils.java, modules/unsupported/solr/src/test/java/org/geotools/data/solr/SolrFeatureSourceTest.java, modules/unsupported/solr/src/test/java/org/geotools/data/solr/SolrGeometryTest.java, modules/unsupported/solr/src/test/java/org/geotools/data/solr/SolrSpatialStrategyTest.java, modules/unsupported/solr/src/test/resources/TestGeotoolsCore/conf/custom_schema.xml, modules/unsupported/solr/src/test/resources/TestGeotoolsCore/conf/schema.xml, modules/unsupported/solr/src/test/resources/wifiAccessPoint.xml
Includes introducing the abstraction called "SpatialStrategy" to encapsulate
the handling of different geometry types.
=> GEOT-4999: Adding support for bbox types to solr datastore.

modules/library/main/src/main/java/org/geotools/data/DataUtilities.java, modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java, modules/library/main/src/test/java/org/geotools/styling/DefaultResourceLocatorTest.java
DataUtilities.urlToFile now handles relative paths on Windows for the standard file:// prefix.
A test has been added that checks if the file exists at the absolute path. If not, the path is handled as relative in the same way as for the simple prefix and the standard prefix on other platforms.
=> [GEOT-4990] DataUtilities.urlToFile relative paths on Windows

pom.xml
Ensure geotools and geoserver are using the same version of commons-lang. Tested full build; no failures.
https://jira.codehaus.org/browse/GEOS-6868
See also: https://github.com/geoserver/geoserver/pull/914
=> (GEOS-6868) Upstream upgrade of commons-lang to 2.6 to support geoserver upgrade

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/sdo/SDO.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/sdo/SDOCreateTest.java
The issue involved malformed polygons containing either unclosed rings or rings with less than 4 points. Code in class `org.geotools.data.oracle.sdo.SDO` has been amended to make sure a `CoordinateSequence` forms a valid linear ring, before invoking `LinearRing`'s constructor.
=> [GEOT-4885] GeoTools stops rendering valid geometry elements after an invalid geometry element

modules/library/main/src/main/java/org/geotools/geometry/jts/WKTReader2.java, modules/library/main/src/test/java/org/geotools/geometry/jts/WKTReader2Test.java
For some reason readGeometryTaggedText in WKT2Reader used equals() instead of equalsIgnoreCase for evaluating "POINT". All other evaluations use equalsIgnoreCase ("LINESTRING", "LINEARRING", etc).
Added a simple test case to test case insensitivity in WKTReader2Test.
=> Resolved issue [GEOT-5021](https://jira.codehaus.org/browse/GEOT-5021);

docs/developer/procedures/release.rst
@jodygarnett garnett @aaime @jdeolive a quick sanity check. I updated the release guide branching instructions to reflect the process I followed. Updates for GeoServer to follow (it entirely lacks this section).
=> Improved release guide branching instructions

modules/plugin/shapefile/pom.xml, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/RecnoFilterToSQL.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/RecnoIndexManager.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStore.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStoreFactory.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureSource.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreTest.java
Manages the optional RECNO field index of the ShapefileDataStore to fast quering using some optional DBF ODBC provider.
Now it implements this improvement for two ODBC providers running in Windows. But it can offers this feature using other jodbc driver for Linux...
It fixes:
https://jira.codehaus.org/browse/GEOS-6842
https://jira.codehaus.org/browse/GEOT-4991
This PR replaces the https://github.com/geotools/geotools/pull/697
=> [GEOS-6842] Improve the dbase reader to filter WHERE clauses using an ODBC driver

modules/extension/xsd/xsd-core/pom.xml, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/HTTPURIHandler.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xml/impl/HTTPURIHandlerTest.java
Fix for http://jira.codehaus.org/browse/GEOT-5040
Added unit tests.  The XSD module didn't have any mocking libraries so I pulled in EasyMock from the root POM.  I can drop the unit tests if this is a problem.
I noticed an oddity in the POM, while adding EasyMock , the JUnit dependancy is a different version from the root POM and has a different scope (compile rather than test)
=> GEOT-5040 - Apply default timeouts to HTTPURIHandler

modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostGISFeatureStoreTestSetup.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisTransactionOnlineTest.java
This fixes the incorrect behaviour of the PostGIS feature store: when INSERT queries trigger more than one sequence increase, the returned feature ID could be incorrect.
=> PostGIS datastore returns the correct sequence value

modules/extension/xsd/xsd-core/pom.xml, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/HTTPURIHandler.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xml/impl/HTTPURIHandlerTest.java
Backport of #767
This is last minute but this should be in 13.0 as it prevents an indefinite wait in a critical section over a utility class. (Schemas)
=> GEOT-5040 - Apply default timeouts to HTTPURIHandler, Backport to 13.x

modules/plugin/jdbc/jdbc-oracle/pom.xml, pom.xml
As with #794 this is primarily intended to support online tests. However, a version update is probably a good idea anyways.
Also fixes some outdated documentation in the root pom. `-Djdbc.oracle` doesn't actually do anything, changed to `-Doracle` instead to match jdbc-oracle pom.
=> Updated Oracle JDBC version

modules/unsupported/csv/src/test/java/org/geotools/data/csv/CSVWriteTest.java
I don't know if my way of checking the OS is the correct way to go about it, but I believe this fixes it. We only care to change the test when the OS is Windows, in which case we need \r\n instead of just \n.
=> Fix test failure on Windows

modules/library/cql/src/main/java/org/geotools/filter/text/commons/ExpressionToText.java, modules/library/cql/src/test/java/org/geotools/filter/text/cql2/FilterToCQLTest.java
Fixes issues when properties have names like `point` or `hyphens-are-cool`.
Should produce correct output for names containing spaces or double quotes although the parser doesn't handle these going the other way. (see the ignored unit tests)
=> Delimit CQL idenifiers that are reserved words or contain reserved characters

modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerTestSetup.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/resources/org/geotools/data/sqlserver/db.properties, modules/plugin/jdbc/jdbc-sqlserver/src/test/resources/org/geotools/data/sqlserver/factory.properties
Changed from the previous, seemingly arbitrary, value of 4866.
=> Updated SQLServer example fixture to use the default port of 1433

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/AttributeEncodeExecutor.java, modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/bindings/GML2ParsingUtils.java, modules/library/api/src/main/java/org/geotools/data/Transaction.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSRemoteTransactionState.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/Loggers.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/AbstractIntegrationTest.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/integration/IntegrationTestWFSClient.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/v1_1/DataStoreTest.java
Reducing the logs during our unit tests:
* downgrade common xml binding warnings to level fine
* makes Transaction AutoClosable (GEOT-5129), and closes transactions used during unit testing
* Clean up use of System.err and System.out.
=> tone down wfs-ng use of system.err, warnings and info messages

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCDateOnlineTest.java, modules/library/main/src/main/java/org/geotools/util/TemporalConverterFactory.java, modules/library/main/src/test/java/org/geotools/util/TemporalConverterFactoryTest.java, modules/plugin/jdbc/jdbc-h2/src/main/java/org/geotools/data/h2/H2FilterToSQL.java, modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2DateTestSetup.java
This PR adds improved JDBC tests to make sure we can add and filter by dates regardless of the TimeZone we are in. It also modifies the temporal convertor to keep track of the TimeZone of the source object (if it has one) so that the GML code can continue to be fixed in GMT(at least in the tests).
=> Fix issues with dates being coerced into GMT [GEOT-5047]

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCDateOnlineTest.java
It seems that prepared statement construction code (in Postgresql at least) is caching the timezone so that when the JVM changes it's default it breaks the tests by continuing to add dates to the SQL in the old timezone.
=> add work round for prepared statements 

docs/user/library/jdbc/oracle.rst, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleNGDataStoreFactory.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleNGJNDIDataStoreFactory.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleNGOCIDataStoreFactory.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleFeatureSourceOnlineTest.java
As discussed about two years ago in the geotools users mailing list (see http://sourceforge.net/p/geotools/mailman/message/30415309/) this enables fast bounds calculation for oracle database layers containing a lot of data (assumption: the access to the SDO_GEOM_METADATA views is not slower than SDO.TUNE). We integrated this into our applications and would like to share it.
The pull request includes:
- updated source code: A switch, as Andrea suggested, to turn the behaviour on (off by default)
- a test case
- updated documentation
=> fast bounds using SDO_GEOM_METADATA

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCTemporalFilterOnlineTest.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCTimeZoneDateOnlineTest.java
reset the dates table to original timezone after timezone tests
removed static DateFormat from Temporal Tests
=> fix remaining timezone issues

modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java
getCount() returns -1 when a post-filter is present, so falling back to getFeatures().size().
=> Fixed check on count in testLikePostFilter()

modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java, modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java
A LIKE pattern is supposed to match the full string it is tested against (e.g. `'Central Park'` matches pattern `'Central%'` but NOT pattern `'tral%'`); the fix makes sure that LIKE filters translated to regular expressions by  the `FilterToMongo` class behave the same way.
=> Fixed: mongodb LIKE filter partial match

modules/library/api/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope.java, modules/library/api/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope3D.java, modules/library/api/src/test/java/org/geotools/geometry/jts/ReferencedEnvelopeTest.java
As discussed on the geotools-devel mailing list (topic "Envelope conversion loses emptyness"), this pull request tries to extend ReferencedEvenlope implementation, such that emptiness property survives the conversion between different envelope formats.
This pull request includes:
- the changed source code
- some minor fixes in source code (spelling mistakes, elimination of doubly defined methods, unused variables)
- a test
GeoTools and GeoServer build fine on my machine
=> Safe envelope conversion

modules/unsupported/mongodb/README.rst
Attribute names containing special characters should be enclosed in double quotes when used in CQL filters: made the docs explicit about this, since it's a common situation with nested properties and the default schema inference algorithm.
See [developer's ML](http://sourceforge.net/p/geotools/mailman/message/34269959/) for discussion.
=> [GEOT-5165] docs about  attribute names with special chars in CQL filters

modules/library/render/src/main/java/org/geotools/renderer/lite/StyledShapePainter.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StyledShapePainterTest.java
Attempting to backport this bug fix to 13.x.
[GEOT-5054] Fixed IllegalArgumentException painting a GraphicLegend with a negative scale.
=> [GEOT-5054] 13.x Fixed IllegalArgumentException painting a GraphicLegend with a negative scale.

modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java, modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java, modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java, modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java, modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoTestSetup.java, modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoTestSupport.java, modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
See [related discussion](http://osgeo-org.1560.x6.nabble.com/WMS-Date-filters-not-working-with-MongoDB-td5216793.html) on mailing list.
=> [GEOT-5172] Backport of fix for date comparison filters in MongoDB datastore

modules/library/jdbc/src/main/java/org/geotools/jdbc/MetadataTablePrimaryKeyFinder.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/EnsureAuthorizationTest.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java
Oracle JDBC DataStore has used SQL queries where parameter values are concatenated into the query. This approach is unsafe (consider strings containing control characters) and causes performance issues. The database needs to create a separate execution plan for each query with different values and in complex database setups, creating the execution plan might take multiple seconds. This patch has been proven to increase GeoServer startup time by a factory of 7x in a configuration where most features (~70 features) are backed by the Oracle JDBC DataStore.
=> Speed up initialization of Oracle DataStores

modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
https://osgeo-org.atlassian.net/browse/GEOT-5188
DB2 tests are working now. If the fix is ok I will  backport to 13.x.
=> GEOT-5188 SQLDialect ignores Schema for index (create statement)

docs/user/tutorial/quickstart/artifacts/pom.xml, docs/user/tutorial/quickstart/eclipse.rst, modules/library/render/src/main/java/org/geotools/map/MapContent.java, modules/unsupported/excel/.settings/org.eclipse.jdt.core.prefs
bumped the GeoTools version from 12-r1 to 13.2 and removed instructions about jars that no longer ship in the eclipse (no maven) instructions. 
Added a call to preDispose to the dispose method of MapContent to get rid of an annoying warning in Layer that predispose hadn't been called.
Tested both the Eclipse and Maven quickstarts
=> Docs update

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/Schemas.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xml/SchemasTest.java, modules/extension/xsd/xsd-core/src/test/resources/org/geotools/xml/importFacetsEmpty.xsd, modules/extension/xsd/xsd-core/src/test/resources/org/geotools/xml/importFacetsNotEmpty.xsd
Forces parsing of imported schemas (if any) when importing schema has no element / type declaration.
See [related JIRA ticket](https://osgeo-org.atlassian.net/browse/GEOT-5194) for a description of the issue fixed by this PR.
=> [GEOT-5194] types defined in imported schemas not found

modules/unsupported/wfs-ng/pom.xml, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSDataStore.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlFeatureParser.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/XmlSimpleFeatureParser.java
* Replace xpp3 dependency and replace by xpp3_min (and stop using XmlPullParserFactory).
xpp3 is unfortunately not compatibility with groovy! (LinkageError)
* implement getCapabilitiesURL so that geoscript-groovy can be ported without code changes
=> GEOS-7152: wfs-ng geoscript compatibility

modules/library/referencing/src/main/java/org/geotools/referencing/operation/projection/MeteosatSG.java, modules/library/referencing/src/main/resources/META-INF/services/org.geotools.referencing.operation.MathTransformProvider, modules/library/referencing/src/test/java/org/geotools/referencing/ScriptTest.java, modules/library/referencing/src/test/resources/org/geotools/referencing/test-data/scripts/MeteosatSG.txt
Conversion of image coordinates (pixel column and row) into the corresponding geographical coordinates of all Meteosat Second Generation (MSG) Satellites (Meteosat-8, Meteosat-9 and Meteosat-10) Level 1.5 VIS/IR data.
Example usage provided in annotated code.
=> Meteosat Second Generation imagery projection

pom.xml
lots of Maven warnings because of missing declared versions for javadoc and build-helper plugin:
* 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing.
* 'reporting.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing.
* 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing.
hiding interesting output on maven build. This patch fixes broken window effect..
=> [mvn] fixed javadoc & build-helper plugin version WARNINGS

docs/user/library/coverage/arcgrid.rst, modules/plugin/arcgrid/src/main/java/org/geotools/gce/arcgrid/ArcGridFormat.java
For [GEOT-5224](https://osgeo-org.atlassian.net/browse/GEOT-5224).
Update the ArcGrid format description and documentation to indicate that only the ARC/INFO ASCII GRID format is supported (not the binary format).
=> [GEOT-5224] ArcGrid extension only supports ASCII GRID

docs/user/library/coverage/arcgrid.rst, modules/plugin/arcgrid/src/main/java/org/geotools/gce/arcgrid/ArcGridFormat.java
It's breaking the build at the GeoServer level, making WCS capabliities document invalid.
=> Revert "[GEOT-5224] ArcGrid extension only supports ASCII GRID"

modules/library/referencing/src/main/java/org/geotools/geometry/GeometryBuilder.java, modules/unsupported/geometry/src/test/java/org/geotools/geometry/iso/aggregate/AggregateGeometryBuilderTest.java, modules/unsupported/geometry/src/test/java/org/geotools/geometry/iso/coordinate/DirectPositionTest.java, modules/unsupported/geometry/src/test/java/org/geotools/geometry/iso/operations/CentroidTest.java, modules/unsupported/geometry/src/test/java/org/geotools/geometry/iso/primitive/PrimitiveGeometryBuilderTest.java
Changes name, adds deprecation annotation and updates tests.
There are some documentation updates, which I'll provide as part of a larger cleanup.
=> [GEOT-5227]  GeometryBuilder setCoordianteReferenceSystem() should be setCoordinateReferenceSystem()

modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java
This duplicate bbox in the SQL query is harmless in most situations,
but not with Oracle. This DB seems to have a bug and don't use
the spacial index if there is two SDO_FILTERS in the where clause
that are fed using bound variables (reproduced in a small java
program that is uses only ojdbc).
From the Mailing list:
SELECT OSM_ID,NAME,TYPE,GEOM as GEOM FROM
WWW_DATA.BAHNEN_21781 WHERE  (SDO_FILTER(GEOM, :1 , 'mask=anyinteract querytype=WINDOW') = 'TRUE'  OR
SDO_FILTER(GEOM, :2 , 'mask=anyinteract querytype=WINDOW') = 'TRUE' )
:1 = MDSYS.SDO_GEOMETRY(2003,21781,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),MDSYS.SDO_ORDINATE_ARRAY(537749.900708669,151378.70118838394,537761.8306244375,151390.63110415262))
:2 = MDSYS.SDO_GEOMETRY(2003,21781,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,1003,3),MDSYS.SDO_ORDINA …
=> Remove duplicate bbox filter from GetFeatureInfo query

docs/user/artifacts/xml/pom.xml, docs/user/tutorial/datastore/artifacts/pom.xml, docs/user/tutorial/feature/artifacts/pom.xml, docs/user/tutorial/filter/artifacts/pom.xml, docs/user/tutorial/geometry/artifacts/pom.xml, docs/user/tutorial/map/artifacts/pom.xml, docs/user/tutorial/quickstart/artifacts/pom.xml, docs/user/tutorial/raster/artifacts/pom.xml, modules/plugin/coverage-multidim/pom.xml, modules/unsupported/coverage-multidim/geotiff/pom.xml, modules/unsupported/coverage-multidim/pom.xml, modules/unsupported/excel/pom.xml, pom.xml
To avoid duplication of code in sub-modules and miminize the risk to forget something, if configuration changes this pull request adresses the issue. Only unique entries of repositories are still present in sub-modules such as
* Unidata UCAR Libraries repository (https://artifacts.unidata.ucar.edu/content/repositories/unidata/)
* Restlet Maven Repository (http://maven.restlet.org)
* nativelibs4java-repo (http://nativelibs4java.sourceforge.net/maven)
In addition all boundless repository definitions (plugin-repository, repository, and distributionManagement) using the same url. 
A full build with an empty local repository finished successfully.
Maybe its worth to think about moving this to top-level root or remove all repository definitions and following maven guide-lines (e.g. …
=> Maven Repository management cleanup

docs/common.py, docs/developer/communication.rst, docs/developer/procedures/add.rst, docs/developer/procedures/check.rst, docs/developer/procedures/create.rst, docs/developer/procedures/proposal.rst, docs/developer/procedures/release.rst, docs/developer/roles/committee.rst, docs/developer/roles/maintainer.rst, docs/themes/geotools-web/page.html, docs/themes/geotools/page.html, docs/user/index.rst, docs/user/library/cql/ecql.rst, docs/user/library/referencing/faq.rst, docs/user/welcome/support.rst, docs/user/welcome/upgrade.rst, docs/web/about.rst, docs/web/getinvolved.rst
Since 13.x is a maintenance release the references to issue tracker should be up-to-date.
This is a backport of @jodygarnett's commit d43b1cd3ca8ec7ded994ded7238d0cd1e78964fb cherry-picked and merged.
=> 13.x backport of doc pages caused by codehaus shutdown

modules/library/data/src/main/java/org/geotools/data/memory/MemoryDataStore.java, modules/library/data/src/test/java/org/geotools/data/memory/MemoryDataStoreTest.java
To remove Schemas from MemoryDataStore removeSchema-methods should be overriden by impelemtations of ContenDataStore otherwise UnsupportedOperationException are thrown.
fixes https://osgeo-org.atlassian.net/browse/GEOT-5256
=> [GEOT-5256] added removeSchema Support for MemoryDataStore

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureSource.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreTest.java
Backport of PR 1025 fix for GEOT-5262 NPE when shapefilereader has an issue extracting the bbox form a filter.
=> backport of GEOT-5262 to 14.x

pom.xml
Pull request to check with Travis that the imageio-ext jars are properly deployed and reachable
=> [GEOT-5286] Reading JPEG compressed geotiffs under heavy load can lead to OOM

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSDataStoreFactory.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSDataAccessFactory.java
WFSConfig.timeoutMillis is applied to read timeout of HTTPClient, too.
See [GEOT-5296](https://osgeo-org.atlassian.net/browse/GEOT-5296)
=> GEOT-5296: Apply WFS timeout to read timeout

modules/library/main/src/main/java/org/geotools/feature/type/PropertyDescriptorImpl.java
When type is null, the code that throws NullPointerException is repeated.
=> remove dead code in PropertyDescriptorImpl

modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageRenderer.java, modules/library/render/src/test/java/org/geotools/renderer/lite/GridCoverageRendererTest.java
Added a null check in the GridCoverageRender when performing color model expansion. Shouldn't need to expand the color model if no background color was provided.
Includes unit test.
No doc changes needed.
=> [GEOT-5318] GridCoverageRenderer fails on indexed image with null background color

modules/plugin/arcsde/datastore/src/main/java/org/geotools/arcsde/filter/GeometryEncoderSDE.java, modules/plugin/arcsde/datastore/src/test/java/org/geotools/arcsde/data/ArcSDEQueryEmptyTableTest.java, modules/plugin/arcsde/datastore/src/test/java/org/geotools/arcsde/data/TestData.java, modules/plugin/arcsde/sde-dummy/src/main/java/com/esri/sde/sdk/client/SeExtent.java
Updated code to handle the case where a ArcSDE feature class has been created but contain no features and so has an invalid extent
=> [GEOT-5757] Handle ArcSDE invalid extents for empty feature classes

modules/extension/transform/src/main/java/org/geotools/data/transform/Transformer.java, modules/extension/transform/src/test/java/org/geotools/data/transform/TransformerTest.java
See [related JIRA issue](https://osgeo-org.atlassian.net/browse/GEOT-5330) for details.
=> [GEOT-5330] Transformer.transformQuery() does not preserve sortBy filter

modules/library/main/src/main/java/org/geotools/filter/FilterSAXParser.java, modules/library/main/src/test/java/org/geotools/filter/FilterFilterTest.java
WFS GetFeature request (version 1.0.0) does not support "matchCase" option. It throws an exception. And geoserver therefore throws it.
It fixes the issue:
https://osgeo-org.atlassian.net/browse/GEOT-5327
This feature was funded by: Tracasa (http://www.tracasa.es/en)
=> [GEOT-5327] Support for 'matchCase' in WFS GetFeature request (v1.0.0)

modules/library/main/src/main/java/org/geotools/filter/function/ClassificationFunction.java, modules/library/main/src/test/java/org/geotools/filter/function/ClassificationFunctionTest.java
Fixed by removing intermediate conversion to int. Removed uneccessary use of
Long wrapper class as well.
=> GEOT-5334, fixing overflow in ClassificationFunction.round.

modules/library/main/src/main/java/org/geotools/filter/LikeFilterImpl.java, modules/library/main/src/test/java/org/geotools/filter/FilterTest.java
This PR fixes the issue:
https://osgeo-org.atlassian.net/browse/GEOT-5346
This feature was funded by: Tracasa (http://www.tracasa.es/en)
=> [GEOT-5346] Fix LikeFilterImpl with unicode chars

modules/library/api/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope3D.java, modules/library/api/src/test/java/org/geotools/geometry/jts/ReferencedEnvelope3DTest.java
This PR fixes a bug with `ReferencedEnvelope3D.distance` which under certain circumstances will incorrectly calculate distance.
I've included a unit test that failed with the original code (but now passes). There was no existing test coverage for  `ReferencedEnvelope3D.distance` in this module and not great coverage of other methods  in `ReferencedEnvelope3D` and other classes in say the `org.geotools.geometry.jts` package. Once this PR is accepted I can have a look at some improvements in this area.
=> GEOT-5354: fix ReferencedEnvelope3D.distance bug

modules/unsupported/geopkg/src/main/java/org/geotools/geopkg/GeoPackage.java, modules/unsupported/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
The Format string has the MONTH (MM) and MINUTES (mm) keys swapped.
Correcting the format string and adding assertions to tests.
=> GEOT-5355 Correcting SimpleDateFormat String

modules/unsupported/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
Changed the test to capture dates before and after the entry setup
so the "last_change" parsed date can be compared.
=> GEOT-5355 Fixing bad test

modules/extension/xsd/xsd-core/pom.xml, pom.xml
We do not use any XML configuration with piccontainer (the XSD module configures dependency injection by hand).
=> ignore transitive dependency from picocontainer to xml-apis

modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrFeatureSource.java
- Uses Solr's  sort feature to only query for one result instead of the entire Solr core.
- Also supports a NearestVisitor for dates.
- Fixes slowness in geoserver's GetCapabilities call on a large Solr core.
=> [GEOT-5357] Add shortcut when querying for global min/max in Solr plugin.

modules/library/main/src/main/java/org/geotools/data/collection/SpatialIndexFeatureCollection.java, modules/library/main/src/test/java/org/geotools/data/collection/SpatialIndexFeatureCollectionTest.java
Implements subcollection to [GEOT-5310](https://osgeo-org.atlassian.net/browse/GEOT-5310). This allows users to cut and paste from the documentation and actually have it work. Also speeds up spatial queries.
=> implement subcollection for SpatialIndexFeatureCollection [GEOT-5310]

docs/user/tutorial/quickstart/artifacts/pom.xml, docs/user/tutorial/quickstart/artifacts/pom2.xml
The repos were missing from the pom.xml in the docs which was [confusing new users](https://stackoverflow.com/questions/35381422/geotools-quickstart-package-org-geotools-does-not-exist).
SInce this is not used for the actual build it was easy to miss this change.
=> added repos to pom.xml

modules/library/coverage/src/main/java/org/geotools/coverage/processing/OperationJAI.java
very trivial update on the code specifying the target array.
However, a test is added in the GeoServer's pull request for GEOS-7396 which involves the wrappedSampleDimension raising the classCastException reported by GEOS-7396.
https://github.com/geoserver/geoserver/pull/1501
=> [GEOT-5366]: ClassCastException fix

modules/extension/wms/src/main/java/org/geotools/data/wms/request/AbstractGetFeatureInfoRequest.java, modules/extension/wms/src/main/java/org/geotools/data/wms/request/AbstractGetMapRequest.java, modules/extension/wms/src/test/java/org/geotools/data/wms/test/AbstractGetMapRequestTest.java, modules/extension/wms/src/test/java/org/geotools/data/wms/test/WebMapServerOnlineTest.java
Since wms layer names with spaces are possible with ArcGIS Server, here is an update on how urls on the wms requests are built (see https://osgeo-org.atlassian.net/browse/GEOT-4317)
Signed-off-by: HendrikPeilke <Hendrik.Peilke@ibykus.de>
=> [GEOT-4317] url encoding of WMS layer name

modules/extension/xsd/pom.xml, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/Encoder.java, modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/GMLWriter.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/CurveEncoder.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/GeometryEncoderTestSupport.java, modules/extension/xsd/xsd-wfs/src/main/java/org/geotools/wfs/bindings/PropertyTypeBinding.java, modules/extension/xsd/xsd-wfs/src/main/java/org/geotools/wfs/v2_0/bindings/PropertyTypeBinding.java, modules/extension/xsd/xsd-wps/src/main/java/org/geotools/wps/bindings/ComplexDataTypeBinding.java, modules/extension/xsd/xsd-wps/src/test/java/org/geotools/wps/bindings/ComplexDataTypeBindingTest.java, modules/library/main/src/main/java/org/geotools/xml/XMLUtils.java, pom.xml
- Ensuring attributes returns empty string rather than null for no uri
- Using “xml” rather than “XML” for output method key value (mandated
but the spec)
=> GEOT-4909, fixing issues when saxon used as encoder transformer.

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java
For developing a datastore for SAP HANA, the `CREATE TABLE` statement needs to be changed to `CREATE COLUMN TABLE`.
=> Allow customization to the CREATE TABLE statement

modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/GMLWriter.java, modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/QualifiedName.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/CurveEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/EnvelopeEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GML32FeatureCollectionEncoderDelegate.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GML3FeatureCollectionEncoderDelegate.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GenericGeometryEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GeometryCollectionEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/LineStringEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/LinearRingEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiLineStringEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiPointEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiPolygonEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/PointEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/PolygonEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/RingEncoder.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/CurveEncoderTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/CurvePolygonEncoderTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/GeometryCollectionEncoderTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/MultiCurveEncoderTest.java
- Updated QualifiedName to accept a namespace uri
- Grabbing the namespace uri from the namespace context
=> Ensuring that gml 3.2 namespace used when encoding gml 3.2.

modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreAPIOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisDataStoreAPITestSetup.java
Fixes [GEOT-4737](https://osgeo-org.atlassian.net/browse/GEOT-4737).
Now that PostGIS has implemented a `preserveCollapsed` flag for `ST_Simplify` in PostGIS 2.2, GeoTools can set that flag to true when using PostGIS 2.2+.
Includes test case.
https://trac.osgeo.org/postgis/ticket/2093
http://postgis.net/docs/manual-2.2/ST_Simplify.html
Will backport to 14.x and 13.x when merged to master.
=> [GEOT-4737] Use of PostGIS ST_Simplify causes small polygons to disappear completely

modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
Fixes [GEOT-5378 Add check for functions deprecated in PostGIS 2.1.0](https://osgeo-org.atlassian.net/browse/GEOT-5378)
PostGISDialect was using deprecated functions ST_Force_2D and ST_Estimated_Extent, which were deprecated in 2.1.0 in favor of ST_Force2D and ST_EstimatedExtent, respectively. This commit checks the PostGIS version and returns the new versions of the function names when PostGIS 2.0+ is detected.
Please review the new `PostGISDialect.getVersion()` and `PostGISDialect.getVersionSafe()` methods, which were needed to detect the version without having access to an existing database connection.
I didn't add a new test case here because all of the changed methods are covered by existing tests. I tested against PostGIS 1.5 and 2.2.
Will backport to 14.x and 13.x when merged to …
=> [GEOT-5378] Add check for functions deprecated in PostGIS 2.1.0

modules/extension/app-schema/app-schema/pom.xml, modules/extension/xsd/xsd-core/pom.xml, pom.xml
* Prevent Java Serialization vulnerability of having cc 3.2.1 and earlier on the classpath
* https://commons.apache.org/proper/commons-collections/security-reports.html
Signed-off-by: Andrew Hulbert <andrew.hulbert@ccri.com>
=> Upgrade to commons-collections 3.2.2 to address CVE-2015-8103

modules/library/jdbc/src/main/java/org/geotools/jdbc/MetadataTablePrimaryKeyFinder.java
This provides a fix for [GEOT-5349](https://osgeo-org.atlassian.net/browse/GEOT-5349) by encoding the schema name.
=> [GEOT-5349] Use encodeSchemaName(...) while looking up GT_PK_METADATA

pom.xml
JAI-EXT's RasterClassifier op (used in ColorMap management) has a bug which may result in OOM when dealing with very big images.
geosolutions-it/jai-ext#125
This pull request updates the GT pom.xml to switch to the fixed version
=> [GEOT-5391]: Update GT to JAI-EXT 1.0.9 to avoid OOM with big oversampling

pom.xml
JAI-EXT's RasterClassifier op (used in ColorMap management) has a bug which may result in OOM when dealing with very big images.
https://github.com/geosolutions-it/jai-ext/issues/125
This pull request updates the GT pom.xml to switch to the fixed version
=> [GEOT-5391]: Update GT to JAI-EXT 1.0.9 to avoid OOM with big oversampling (backport)

modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/ClientPropertyIdentifierTest.java, modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/SweValuesTest.java, modules/extension/complex/src/main/java/org/geotools/feature/xpath/XmlAttributeNodePointer.java
Current code in `XmlAttributeNodePointer` assumes an XML attribute called `id` must be the feature identifier and tries to retrieve it calling `feature.getIdentifier()`; however, if the attribute is not mapped using `<idExpression>` but as a regular `<ClientProperty>`, it will not be used as the feature identifier, in which case `feature.getIdentifier()` will return null (the original code throws a NPE).
This PR solves the issue in the simplest way, falling back to normal attribute extraction when `feature.getIdentifier()` returns nothing.
See: https://osgeo-org.atlassian.net/browse/GEOT-5394
=> [GEOT-5394] XPath fails to retrieve gml:id if mapped as ClientProperty

modules/library/coverage/src/main/java/org/geotools/coverage/ColorModelFactory.java, modules/library/coverage/src/test/java/org/geotools/coverage/ColorModelFactoryTest.java
Fixed ColorModelFactory returning cached ColorModel objects with the wrong data type.
=> [GEOT-5390] Backport ColorModelFactory fix to 14.x.

modules/library/coverage/src/main/java/org/geotools/coverage/ColorModelFactory.java, modules/library/coverage/src/test/java/org/geotools/coverage/ColorModelFactoryTest.java
Fixed ColorModelFactory returning cached ColorModel objects with the wrong data type.
=> [GEOT-5390] Backport ColorModelFactory fix to 13.x.

modules/library/referencing/src/main/java/org/geotools/referencing/operation/projection/RotatedPole.java, modules/library/referencing/src/main/resources/META-INF/services/org.geotools.referencing.operation.MathTransformProvider, modules/library/referencing/src/test/java/org/geotools/referencing/ScriptTest.java, modules/library/referencing/src/test/resources/org/geotools/referencing/test-data/scripts/RotatedPole.txt
Add new transformation used often by Numerical Weather Forecasting community to support "Rotated Pole" coordinates. That transformation is also available in proj.4 as "+proj=ob_tran".
For initial idea of this pull request, see:
http://osgeo-org.1560.x6.nabble.com/Rotated-pole-coordinate-system-td5204800.html
This transformation is intended to replace a "GeneralOblique" one for two reasons:
- better self-descriptive name
- _latitudeOfOrigin_ parameter is consistent with its name (latitude of a new origin, not of a transformed Pole, as in proj.4).
For details, see:
http://osgeo-org.1560.x6.nabble.com/Problem-with-General-Oblique-transform-latitude-td5257089.html
And:
[GEOT-5396] Support Rotated Pole projection
https://osgeo-org.atlassian.net/browse/GEOT-5396
=> [GEOT-5396] Support Rotated Pole projection

modules/unsupported/pom.xml
I would like to include YSLD in the default build so it gets published to the Maven repository so projects using GeoTools (like GeoScript) can use YSLD.
https://osgeo-org.atlassian.net/browse/GEOT-5402
Thanks!
Jared
=> Include YSLD in the default build

modules/unsupported/swing/src/main/java/org/geotools/swing/JMapFrame.java, modules/unsupported/swing/src/main/java/org/geotools/swing/tool/ScrollWheelTool.java
Allow users to zoom in and out of Swing based GeoTools maps using their mouse scroll wheel.
See [[GEOT-5289]](https://osgeo-org.atlassian.net/browse/GEOT-5412)
=> add scroll wheel zoom in/out to JMapPanes and JMapFrames

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureReader.java
org.geotools.jdbc.JDBCFeatureReader$ResultSetFeature was
converting all attribute values in setAttribute() to String
just for a no-op log statement. This patch guards the log
call with a Logger.isLoggable(Level) to avoid building a
large String when not needed, which is especially a performance
hit for geometry values.
=> Guard log of value in ResultSetFeature.setAttribute

modules/library/main/src/main/java/org/geotools/feature/GeometryAttributeImpl.java
I removed unused, unnecessary getter/setter methods.
the interface returns Object not Geometry and nobody uses this "impl" class directly.
=> Removed accessor method that nobody uses in GeometryAttributeImpl

modules/library/api/src/main/java/org/geotools/data/FeatureSource.java, modules/library/data/src/main/java/org/geotools/data/memory/MemoryDataStore.java, modules/library/data/src/main/java/org/geotools/data/memory/MemoryEntry.java, modules/library/data/src/main/java/org/geotools/data/memory/MemoryFeatureReader.java, modules/library/data/src/main/java/org/geotools/data/memory/MemoryFeatureSource.java, modules/library/data/src/main/java/org/geotools/data/memory/MemoryFeatureStore.java, modules/library/data/src/main/java/org/geotools/data/memory/MemoryFeatureWriter.java, modules/library/data/src/main/java/org/geotools/data/memory/MemoryState.java, modules/library/data/src/main/java/org/geotools/data/store/ContentDataStore.java, modules/library/data/src/main/java/org/geotools/data/store/ContentEntry.java, modules/library/data/src/main/java/org/geotools/data/store/ContentFeatureSource.java, modules/library/data/src/main/java/org/geotools/data/store/ContentState.java, modules/library/data/src/test/java/org/geotools/data/memory/MemoryDataStoreTest.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureStore.java, modules/library/main/src/main/java/org/geotools/data/DataUtilities.java, modules/library/main/src/main/java/org/geotools/data/ReTypeFeatureReader.java, modules/library/main/src/main/java/org/geotools/feature/simple/SimpleFeatureTypeBuilder.java, modules/plugin/property/src/main/java/org/geotools/data/property/PropertyFeatureSource.java, modules/plugin/property/src/test/java/org/geotools/data/property/PropertyExamples.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureStore.java
The goal with ContentDataStore was to use objects, rather than Maps for organization. This refactor changes MemoryDataStore from Map<String,Map<String,Feature>> to a MemoryEntry managed by the ContentDataStore superclass.
Although this refactor is functionally identical changing to objects makes the logic easier to follow.
To enable this refactor ContentEntry is no longer a final class.
=> Store MemoryDataStore features in each MemoryEntry

modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/geotiff/CRS2GeoTiffMetadataAdapter.java, modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/geotiff/GeoTiffMetadata2CRSAdapter.java, modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Crop.java, modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Resampler2D.java, modules/library/coverage/src/main/java/org/geotools/image/GTWarpPropertyGenerator.java, modules/library/coverage/src/main/java/org/geotools/image/io/ImageIOExt.java, modules/library/coverage/src/main/java/org/geotools/resources/coverage/IntersectUtils.java, modules/library/coverage/src/main/java/org/geotools/resources/image/ImageUtilities.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1905 - Redundant casts should not be used.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1905
Please let me know if you have any questions.
George Kankava
=> squid:S1905 - Redundant casts should not be used

modules/library/main/src/main/java/org/geotools/data/DataUtilities.java, modules/library/main/src/test/java/org/geotools/data/collection/SortedFeatureCollectionTest.java
[GEOT-5416](https://osgeo-org.atlassian.net/browse/GEOT-5416) - Currently SortOrder.DESCENDING is handled in the same way as SortOrder.ASCENDING which is clearly wrong. This PR Fixes the issue.
=> [GEOT-5416] Fix so SortOrder.DESCENDING works

modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/AbstractGridCoverage2DReader.java, modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/FileSystemFileSetManager.java, modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/geotiff/GeoTiffIIOMetadataDecoder.java, modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/geotiff/GeoTiffIIOMetadataEncoder.java, modules/library/coverage/src/main/java/org/geotools/coverage/processing/BaseStatisticsOperationJAI.java, modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/GridCoverage2DRIA.java, modules/library/coverage/src/main/java/org/geotools/image/ImageWorker.java, modules/library/coverage/src/main/java/org/geotools/image/palette/ColorReduction.java, modules/library/coverage/src/main/java/org/geotools/image/palette/CustomPaletteBuilder.java, modules/library/coverage/src/main/java/org/geotools/image/palette/InverseColorMapOp.java, modules/library/coverage/src/main/java/org/geotools/image/palette/InverseColorMapRasterOp.java, modules/library/coverage/src/main/java/org/geotools/resources/coverage/FeatureUtilities.java, modules/library/coverage/src/main/java/org/geotools/resources/image/ImageUtilities.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1197 - Array designators "[]" should be on the type, not the variable.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1197
Please let me know if you have any questions.
George Kankava
=> squid:S1197 - Array designators "[]" should be on the type, not the variable

modules/library/cql/src/main/java/org/geotools/filter/text/commons/ExpressionToText.java, modules/library/cql/src/test/java/org/geotools/filter/text/ecql/ECQLIDPredicateTest.java
The ECQL parser still accepts the deprecated keyword ID. Thus property
names ID, iD, Id, id must be delimited, and hence will be delimited.
=> [GEOT-5398] ECQL: format property name ID as "ID"

docs/developer/procedures/release.rst
After doing the GeoTools 15-RC1 release, I found that the release guide was rather out-of-date. This intends to remedy the problems I found:
**Add manual JIRA release instructions**
The current release instructions rely on the `geotools-release-jira` job on the ares jenkins server. This job has not been working for about a yer. Until someone finds the time to fix the JIRA release scripts, the Release Guide should be updated with manual release steps.
**Indicate `geotools-release-publish` is also responsible for deploying artifacts to maven.**
This is not made clear anywhere in the existing release guide, and caused some confusion when trying to start the GeoWebCache release after the artifacts had been built by the `geotools-release` job.
**Remove deprecated news sites**
A number of the …
=> Improve GeoTools Release Guide

modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReaderSpi.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/imageio/netcdf/NetCDFImageReaderSpiTest.java
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5419
JAXB's unmarhsaller is not properly releasing the file when an error happens. 
To solve this I use an InputStream instead of a File so we can properly close it.
I create a test for this situation, although this seems to be only reproducible in Windows.
=> [GEOT-5419] Fix NetCDFImageReaderSpi file dispose

modules/library/main/src/main/java/org/geotools/feature/simple/SimpleFeatureTypeImpl.java, modules/library/main/src/test/java/org/geotools/feature/simple/SimpleFeatureTypeImplTest.java
* Avoids the chance of a second thread seeing a partially filled type list
I didn't add a unit test as thread safety is hard to test reliably, but it should be evident how the old code could result in a second thread seeing a non-null but empty or partially filled type list.
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>
=> Improving thread safety of SimpleFeatureTypeImpl.getTypes

docs/user/build/install/mvn.rst, docs/user/tutorial/datastore/intro.rst, docs/user/tutorial/quickstart/artifacts/pom.xml, docs/user/tutorial/quickstart/artifacts/pom2.xml, docs/user/tutorial/quickstart/eclipse.rst, docs/user/tutorial/quickstart/maven.rst, docs/user/tutorial/quickstart/netbeans.rst
- Updated a few references to JDK 7 in some documentation
- Removed warning about Maven and Apt-Get. Ubuntu repositories contain Maven 3 since at least 14. Added a reference to official maven install guide if user's would like the most up-to-date version.
=> Changed references to JDK 7 to be JDK 8

modules/library/main/src/main/java/org/geotools/geometry/jts/GeometryClipper.java, modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java, modules/library/render/src/test/java/org/geotools/renderer/lite/LineTest.java
[GEOT-5430]
Unfortunately I haven't been able create a test case for this due to the nature of the issue. I'm all ears for suggestions. The issue boils down to the following:
- StreamingRenderer clips a MultiPolygon that's actually out of the envelope bounds. This produces an empty polygon.
- Offset code then attempts to offset the vector, but fails since the geometry is empty
Except in most cases the code shouldn't even make it this far, since features outside the bounds should be filtered out anyway. I'm not sure why it doesn't happen in the case of the data in the ticket, it could have something to do with the projection?
In any case, this is a pretty innocuous null + empty check anyway, and test coverage is already pretty good there anyway, so maybe we could merge this without a …
=> GEOT-5430 Check for empty or null geometry before doing offset

docs/common.py, docs/user/library/data/index.rst, docs/user/library/data/mongodb.rst, docs/user/unsupported/index.rst
It would be useful to migrate the existing mongodb datastore module readme.rst into the user manual.
From: https://osgeo-org.atlassian.net/browse/GEOT-5431
=> [GEOT-5431] Migrate MongoDB DataStore docs to user manual.

modules/library/xml/src/main/java/org/geotools/xml/xsi/XSISimpleTypes.java, modules/library/xml/src/test/java/org/geotools/xml/xsi/XSISimpleTypesTest.java
For all types (eg. Double) a check is made on ```""``` and return null in this case. Apply similar approach to empty date/dateTime/time/duration types instead of throwing SAXException.
Let me know if this is relevant or not.
Related discussion http://osgeo-org.1560.x6.nabble.com/WFS-feature-with-empty-date-td5268563.html
=> Return null instead of throwing exception when parsing empty dates [GEOT-5435]

modules/plugin/coverage-multidim/grib/src/test/java/org/geotools/coverage/io/grib/GribTest.java, pom.xml
[GEOT-5434] Upgrade to NetCDF-Java 4.6.6
https://osgeo-org.atlassian.net/browse/GEOT-5434
[GEOT-5395] Build failure in gt-grib with -Dnetcdf.version=4.6.4 or later
https://osgeo-org.atlassian.net/browse/GEOT-5395
Must be merged at the same time as https://github.com/geoserver/geoserver/pull/1640
=> [GEOT-5434] Upgrade to NetCDF-Java 4.6.6

modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/ConvolveCoverageProcess.java, modules/unsupported/process-raster/src/main/java/org/geotools/process/raster/NormalizeCoverageProcess.java, modules/unsupported/process-raster/src/main/resources/META-INF/services/org.geotools.process.raster.RasterProcess, modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/ConvolveCoverageProcessTest.java, modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/NormalizeCoverageProcessTest.java
- Convolve process simply exposes the Convolve raster operation
- The normalize process takes a raster, computes its max value, and then involves the divide operation by the max to produce a raster with values between [0,1], "normalizing" the values within it
=> Added processes for convolve and normalizing a coverage

modules/unsupported/ysld/src/main/java/org/geotools/ysld/validate/ScalarValidator.java, modules/unsupported/ysld/src/test/java/org/geotools/ysld/validate/YsldValidateTest.java
PR for https://osgeo-org.atlassian.net/browse/GEOT-5445
While this is fix is an improvement,, there should really be some sort of validation for Aliases. However, this does not seem to be implemented anywhere in the YSLD validators currently and implementation appears to be nontrivial.
=> [GEOT-5445] Add alias handling to ScalarValidator

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDataStoreOnlineTest.java, pom.xml
Allow users to create tables in Oracle (10g) DB even if the CRS declares 0 dimensions.
=> Oracle will fail to create spatial metadata entry correctly for CRS that report 0 dimensions [GEOT-5455]

modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/GranuleCollectorSPITest.java
A workaround for the current failure on gt-master. Need some time to re-work the test, since it fails on certain environments due to the order in which granules are indexed.
=> Workaround for the granule collector test failure

docs/user/library/jts/dim9.rst
The dimension of Exterior x Exterior intersection was wrongly set to 1, whereas it should be 2 (see the figure before or the string relationship `String relationship = "212101212";` afterwards).
=> [DOCS] Fixed Typo in JTS Dimensions

docs/user/library/render/faq.rst, docs/user/library/render/svg.rst
In answering [this question](https://gis.stackexchange.com/questions/201282/externalgraphics-gray-squares-instead) I discovered it isn't obvious that you need to add the svg module to be able to render svg graphics. So this adds a note to that effect to the rendering faq.
=> [DOCS] added note about needing svg module to draw svg icons

modules/unsupported/mongodb/pom.xml, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureWriter.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoSchemaDBStore.java, modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java, modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/integration/MongoTestUtil.java
Fixes GEOT-5492 by:
-upgrade version of mongo-java-driver to 3.3.0 in pom.xml
-replacing usages of “ensureIndex” (deprecated) with “createIndex” in various classes
-UnknownHostException not explicitly thrown
Unit tests remain valid and functional tests pass in GeoServer
=> Upgrade to Mongo module to fix GEOT-5492

docs/user/unsupported/swing/faq.rst
Crossing my fingers this syntax for linking to other docs works (?). I borrowed it from another geotools rst example.
The link was sending the user here:
http://docs.geotools.org/library/main/collection
Instead of here:
http://docs.geotools.org/latest/userguide/library/main/collection.html
=> Fix link to FeatureCollection in swing faq

modules/unsupported/polylabel/src/main/resources/META-INF/services/org.geotools.filter.FunctionFactory, modules/unsupported/polylabel/src/test/java/org/geotools/polylabel/PolygonLabelFunctionFactoryTest.java
added factory test and fixed wrong class name in SPI Lookup
=> Pole of Inaccessibility/LabelPoint doesn't work as a function

modules/library/api/src/main/java/org/geotools/geometry/jts/CompoundCurve.java, modules/library/api/src/test/java/org/geotools/geometry/jts/CurvedGeometryTest.java
In this PR:
fixes [GEOT-5508](https://osgeo-org.atlassian.net/browse/GEOT-5508)
=> Fix possible NPE in CompoundCurve [GEOT-5508]

modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageRenderer.java, modules/library/render/src/test/java/org/geotools/renderer/lite/GridCoverageRendererTest.java
This fix the aliasing issue and extend test testBandSelectionSupportingReader to check raster symbolizer immutability between runs.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5520
=> [GEOT-5520] Make grid coverage renderer bands selection setup update a copy of the channels

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/SDO11OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/SDOOracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/sdo/GeometryConverter.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/sdo/SDO.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleGeometryOnlineTest.java
fixes "Oracle DataStore is unable to add empty geometries"
Applies patches for [GEOT-724](https://osgeo-org.atlassian.net/browse/GEOT-724) provided in #1228 to 15.x branch
=> [GEOT-724] backport for 15.x

pom.xml
https://osgeo-org.atlassian.net/browse/GEOT-5527
This pull request targets master.
=> [GEOT-5527] PostgreSQL 9.6 breaks ASC_OR_DESC for index

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/ColumnEncodingTest.java
I believe that this bug was fixed by [PR1183](https://github.com/geotools/geotools/pull/1183), this PR adds a test, just needs a working Oracle instance for testing.
=> added test for GEOT-5176 - white space in column names

modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java, modules/library/render/src/test/resources/org/geotools/renderer/lite/test-data/genericLines.properties, modules/library/render/src/test/resources/org/geotools/renderer/lite/test-data/genericLines.sld
https://osgeo-org.atlassian.net/browse/GEOT-5534
This pull request also adds a test case for this.
=> [GEOT-5534] Make streaming renderer map the default geometry attribute to the real geometry attribute name

modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java, modules/library/render/src/test/resources/org/geotools/renderer/lite/test-data/genericLines.properties, modules/library/render/src/test/resources/org/geotools/renderer/lite/test-data/genericLines.sld
https://osgeo-org.atlassian.net/browse/GEOT-5534
This pull request also adds a test case for this.
This is a backport of pull request:
https://github.com/geotools/geotools/pull/1329#issuecomment-250931619
=> [GEOT-5534] Make streaming renderer map the default geometry attribute to the real geometry attribute name (backport 15.x) 

modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_numberFormat.java, modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_numberFormat2.java, modules/library/main/src/test/java/org/geotools/filter/function/NumberFormatTest.java
Fix for [GEOT-5543](https://osgeo-org.atlassian.net/browse/GEOT-5543) takes current locale into account when formatting the number. This is more likely to be what the user is expecting.
=> modify numberFormat to take an optional language string (GEOT-5543)

modules/unsupported/swing/src/main/java/org/geotools/swing/DefaultRenderingExecutor.java, modules/unsupported/swing/src/test/java/org/geotools/swing/DefaultRenderingExecutorTest.java, modules/unsupported/swing/src/test/java/org/geotools/swing/testutils/MockRenderer.java
After a rendering failure on any layer, DefaultRenderingExecutor will not issue any more rendering requests, even if the offending layer is removed from the MapContent.  This is caused because the task counter is not decremented on a failure. 
DefaultRenderingExecutor modified to decrement the tasks latch on both fail and completion, thus clearing it's own internals and allow subsequent submissions to be rendered correctly.
=> [GEOT-5563] DefaultRenderingExecutor stops working after a layer fail

modules/library/main/src/main/java/org/geotools/data/DataUtilities.java, modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
When creating a sub type using DataUtilies if one of the provided properties doesn't map to an attribute descriptor a NULL attribute descriptor will be added to the new sub type attributes descriptors list.
Since the typical code assumes that the attributes descriptors of a feature type are not NULL this may provoke a NULL pointer exception. A situation like this happens for example when a provided property is valid but the corresponding attribute descriptor is hidden by a security rule (read only attributes for example).
This pull request fix this issue and adds a test case.
- https://osgeo-org.atlassian.net/browse/GEOT-5558
- https://osgeo-org.atlassian.net/browse/GEOS-7524
=> [GEOT-5558][GEOS-7524] Ignore no matching properties

modules/library/main/src/main/java/org/geotools/data/DataUtilities.java, modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
When creating a sub type using DataUtilies if one of the provided properties doesn't map to an attribute descriptor a NULL attribute descriptor will be added to the new sub type attributes descriptors list.
Since the typical code assumes that the attributes descriptors of a feature type are not NULL this may provoke a NULL pointer exception. A situation like this happens for example when a provided property is valid but the corresponding attribute descriptor is hidden by a security rule (read only attributes for example).
This pull request fix this issue and adds a test case.
- https://osgeo-org.atlassian.net/browse/GEOT-5558
- https://osgeo-org.atlassian.net/browse/GEOS-7524
This is a backport of this pull request: https://github.com/geotools/geotools/pull/1367
=> [GEOT-5558][GEOS-7524] Ignore no matching properties (backport 15.x)

modules/library/main/src/main/java/org/geotools/data/DataUtilities.java, modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
When creating a sub type using DataUtilies if one of the provided properties doesn't map to an attribute descriptor a NULL attribute descriptor will be added to the new sub type attributes descriptors list.
Since the typical code assumes that the attributes descriptors of a feature type are not NULL this may provoke a NULL pointer exception. A situation like this happens for example when a provided property is valid but the corresponding attribute descriptor is hidden by a security rule (read only attributes for example).
This pull request fix this issue and adds a test case.
- https://osgeo-org.atlassian.net/browse/GEOT-5558
- https://osgeo-org.atlassian.net/browse/GEOS-7524
This is a backport of this pull request: https://github.com/geotools/geotools/pull/1367
=> [GEOT-5558][GEOS-7524] Ignore no matching properties (backport 16.x)

docs/user/library/xml/internal/overview.rst, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/Encoder.java
https://osgeo-org.atlassian.net/browse/GEOT-5575
GeoServer side pull requests that add app-schema test case with complex features:
https://github.com/geoserver/geoserver/pull/1976
=> [GEOT-5575] Relax the XML encoder to be able to encode nested complex types that don't respect the GML object-property model

modules/plugin/arcgrid/src/main/java/org/geotools/gce/arcgrid/ArcGridReader.java, modules/plugin/imageio-ext-gdal/src/main/java/org/geotools/coverageio/gdal/BaseGDALGridCoverage2DReader.java
The DEFAULT_COORDINATE_REFERENCE_SYSTEM is explicitly provided and should not produce a WARNING when used correctly.
=> Remove warning associated with DEFAULT_COORDINATE_REFERENCE_SYSTEM use

modules/library/coverage/src/main/java/org/geotools/resources/image/ExtendedImageParam.java, modules/library/coverage/src/main/java/org/geotools/resources/image/ImageUtilities.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFResponse.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReader.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java
This pull request substitute the usage of ```EnhancedImageReadParam``` by by the new imageio```ExtendedImageParam```.
- https://osgeo-org.atlassian.net/browse/GEOT-5580
=> [GEOT-5580] Use imageio EnhancedImageReadParam instead of ExtendedImageParam

modules/library/coverage/src/main/java/org/geotools/resources/image/ExtendedImageParam.java, modules/library/coverage/src/main/java/org/geotools/resources/image/ImageUtilities.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFResponse.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/NetCDFImageReader.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java
Backport of pull request: https://github.com/geotools/geotools/pull/1392
This pull request substitute the usage of ```EnhancedImageReadParam``` by by the new imageio```ExtendedImageParam```.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5580
=> [GEOT-5580] Use imageio EnhancedImageReadParam instead of ExtendedImageParam (backport 16.x)

modules/library/referencing/src/main/java/org/geotools/referencing/operation/projection/AzimuthalEquidistant.java, modules/library/referencing/src/test/java/org/geotools/referencing/operation/projection/AzimuthalEquidistantTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5594
Replaces https://github.com/geotools/geotools/pull/1420 (branch name typo)
=> [GEOT-5594] AzimuthalEquidistant projection missing parameters (master)

modules/library/metadata/src/main/java/org/geotools/util/SoftValueHashMap.java, modules/library/metadata/src/test/java/org/geotools/util/SoftValueHashMapTest.java
SoftValueHashMap now supports concurrency better, using ConcurrentHashMap and ConcurrentLinkedQueue.
=> [GEOT-5602] Better concurrent SoftValueHashMap

modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/egr/Tile.java
The class imports the SoftValueHashMap in GT (not in imageio-ext)
=> [GEOT-5601] Import of SoftValueHashMap fixed

modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GML3FeatureCollectionEncoderDelegate.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GeometryCollectionEncoder.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/GeometryCollectionEncoderTest.java
Fixed invalid GML3 GeometryCollection encoding and updated the unit test.  Also applying the GEOT-5360 GeometryCollection encoding fix for GML 3.2 to GML 3.1.
https://osgeo-org.atlassian.net/browse/GEOT-5606
https://osgeo-org.atlassian.net/browse/GEOT-5360
This patch can be backported to 15.x and 16.x
=> [GEOT-5606] Fixed invalid GML3 GeometryCollection encoding.

modules/plugin/jdbc/jdbc-db2/src/main/java/org/geotools/data/db2/DB2FilterToSQL.java, modules/plugin/jdbc/jdbc-db2/src/test/java/org/geotools/data/db2/DB2SpatialFiltersOnlineTest.java
Fix DB2 SQL generation to use units like METER for DWITHIN and BEYOND. Previously, units were ignored and distance was treated as being in the coordinate system units.
Updated online testcase to correctly test DWITHIN and BEYOND.
=> DB2 updates

docs/user/unsupported/swing/jmappane.rst
Finally found out where users were finding the hint to roll your own scroll
wheel listener. I have replaced it with a note about ScrollWheelTool.
=> Removed erroneous documentation about mouse zoom wheels

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStore.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreTest.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileQuadTreeReadWriteTest.java
With the current code, shapefile columns can't be bigger than 9.999... In Qgis, columns are truncated and information is modified.
My proposition is to split the chars number to define the same length before and after the decimal point.
=> Numbers with decimals in ShapefileDataStore always less than 10

modules/library/render/src/main/java/org/geotools/renderer/lite/RendererUtilities.java, modules/library/render/src/test/java/org/geotools/renderer/lite/RenderUtilitiesTest.java
The code was miss calculating the quadrants to compare to when dealing with
diagaonals greater than 180 degrees.
=> Fixed GEOT-5336

modules/library/main/src/main/java/org/geotools/styling/SLDTransformer.java, modules/library/main/src/test/java/org/geotools/styling/SLDTransformerTest.java, modules/library/referencing/src/test/java/org/geotools/referencing/wkt/GeoToolsUnitFormatTest.java
Means that SI units weren't necessarily labeled correctly
extends and replaces https://github.com/geotools/geotools/pull/1427
=> Fix copy/paste error in GeoToolsUnitFormat.java

pom.xml
This one is a little selfish, but we have some conflicts internally with the version of EhCache used in GeoTools and the latest 2.x version. I figure this upgrade is fairly safe in that
- it's only used by ImageMosaic
- there are no code changes required to do the upgrade.
I'd consider upgrading even further, but EhCache 3.x is a significant departure both in API and capabilities.
=> Upgrade EhCache to latest 2.x version

docs/user/unsupported/mbstyle.rst
Add a stub mbstyle.rst file to support the new mapbox styles unsupported module.
=> [GEOT-5626] Add mbstyle.rst to fix docs build

modules/library/api/src/main/java/org/geotools/styling/StyleFactory.java, modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/FillMBLayer.java, modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/LineMBLayer.java, modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/MBFormatException.java, modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/MBLayer.java, modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/MBStyle.java, modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/RasterMBLayer.java, modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBObjectParser.java, modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBStyleParser.java, modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/transform/MBStyleTransformer.java, modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/transform/MapBoxStyleTest.java
MBObjectParser now has a naming convention to distingish between get methods for json access and  query methods which can transform into Expression and Filter as required.
Also a "quick" review of MBLayer implementations against geotools code conventions and the mapbox specificiation (mostly resulting in more javadocs).
=> refactor MBObjectParser into an object for reuse of factories

modules/plugin/jdbc/jdbc-db2/src/test/java/org/geotools/data/db2/DB2PrimaryKeyFinderTestSetup.java
In the testcase setup, the metadata table was being created as GEOTOOLS.GT_PK_METADATA so it wasn't found later when the JDBC code was looking for "geotools".GT_PK_METADATA. This caused a failure in DB2PrimaryKeyFinderOnlineTest.
Changed DB2PrimaryKeyFinderTestSetup to create and populate "geotools".GT_PK_METADATA. After this, the testcase ran successfully
=> Fix DB2 testcase setup

pom.xml
The issue GEOT-5629 has been split in two steps. First step: GEOT-5630 (this one) updates the pom to support JAI-EXT 1.0.13; second step: GEOT-5631 to fix the imports of ROIGeometry, ImageLayout2.
=> [GEOT-5630] add pom support to jaiext 1.0.13

modules/plugin/imageio-ext-gdal/pom.xml
The imageio-ext-gdalgeotiff.jar can cause classpath loading problems: only classes in imageio-ext-tiff.jar should be loaded.
See related issue on geoserver https://osgeo-org.atlassian.net/browse/GEOS-7981
=> [GEOT-5636] fixed imageio-ext-gdalgeotiff.jar classpath conflicts

modules/library/main/src/main/java/org/geotools/filter/FunctionImpl.java, modules/library/main/src/main/java/org/geotools/filter/function/InterpolateFunction.java, modules/library/main/src/test/java/org/geotools/filter/function/InterpolateFunctionTest.java
Javadocs and toString implementation based on StringBuilder. This implementation does not extend any base class, causing it to miss out on a default toString implementation.
=> Readability improvements to InterpolationFunction

modules/library/xml/src/main/java/org/geotools/xml/filter/FilterCompliancePreProcessor.java, modules/library/xml/src/test/java/org/geotools/xml/filter/FilterCompliancePreProcessorTest.java
Unit test and fix for GEOT-5537 added: pass NOT filtertype to createHighLevelLogicFilter() method instead of AND.
=> GEOT-5537: pass NOT instead of AND when creating NOT filters

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSClient.java
backport to 16.x to disable server based sorting for WFS 1.0.0 & 2.0.0 as neither currently supports it
=> [GEOT-5650] fix for sorting

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/sdo/SDO.java
The array with allowed ETypes contains the type `ETYPE.FACE_EXTERIOR` twice, which isn't usefull. This PR removes the redundant argument.
=> Fix redundant check argument

modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/bindings/GMLEncodingUtils.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/bindings/GML3EncodingUtilsTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/v3_2/bindings/GML32EncodingUtilsTest.java
GMLEncodingUtils will take in account GML 3.2 geometries types names when creating the XSD type for a feature type.
This PR also adds test cases for this.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5669
=> [GEOT-5669] Make GMLEncodingUtils take in account GML 3.2 geometries types names

modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/bindings/GMLEncodingUtils.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/bindings/GML3EncodingUtilsTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/v3_2/bindings/GML32EncodingUtilsTest.java
Backport of this PR: https://github.com/geotools/geotools/pull/1504
GMLEncodingUtils will take in account GML 3.2 geometries types names when creating the XSD type for a feature type.
This PR also adds test cases for this.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5669
=> [GEOT-5669] Make GMLEncodingUtils take in account GML 3.2 geometries types names (backport 16.x)

modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/bindings/GMLEncodingUtils.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/bindings/GML3EncodingUtilsTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/v3_2/bindings/GML32EncodingUtilsTest.java
Backport of this PR: https://github.com/geotools/geotools/pull/1504
GMLEncodingUtils will take in account GML 3.2 geometries types names when creating the XSD type for a feature type.
This PR also adds test cases for this.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5669
=> [GEOT-5669] Make GMLEncodingUtils take in account GML 3.2 geometries types names (backport 15.x)

modules/extension/xsd/xsd-core/pom.xml, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/Base64Binary.java
Now that functionality is public we can avoid use of sun.misc.BASE64Decoder / sun.misc.BASE64Encoder classes.
This avoids a compile failure in Java 1.8.0_102 and Eclipse 4.6.2
See https://osgeo-org.atlassian.net/browse/GEOT-5676
=> Use java 8 Base64 Encoder / Decoder [GEOT-5676]

modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/bindings/GMLEncodingUtils.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/bindings/GML3EncodingUtilsTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/v3_2/bindings/GML32EncodingUtilsTest.java
Backport of this PR: #1504
GMLEncodingUtils will take in account GML 3.2 geometries types names when creating the XSD type for a feature type.
This PR also adds test cases for this.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5669
=> [GEOT-5669] Make GMLEncodingUtils take in account GML 3.2 geometries types names (backport 17.x)

modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java, modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
* The And filter builder had this comment 'Expressions like ((A == 1) AND (B == 2)) are basically implied. So just build up all sub expressions'.
Which is true for an AND expressions with 2 different properties, however for an AND on the same property '((A > 1) AND (A <= 2))'
this expression will overwrite the first expression with the second since the key is the same.
IE { "A" : { "$lte" : 2 } }, rather than the correct expression { "$and" : [{ "A" : { "$gt" : "0" } }, { "A" : { "$lt" : "10" } }] }
=> [GEOT-5670] MongoDB Fix 'And' filter

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDumper.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDumperTest.java, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dumper/AllTypesWithNull.properties
This PR fix the dump of features to shapefiles that don't have a geometry type defined (they use the generic Geometry type) and have NULL geometries.
A test case was improved a new test case added.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5686
=> [GEOT-5686] Shapefile dumper throws a NPE on NULL geometry values

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDumper.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDumperTest.java, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dumper/AllTypesWithNull.properties
Backport of this PR: https://github.com/geotools/geotools/pull/1517
This PR fix the dump of features to shapefiles that don't have a geometry type defined (they use the generic Geometry type) and have NULL geometries.
A test case was improved a new test case added.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5686
=> [GEOT-5686] Shapefile dumper throws a NPE on NULL geometry values (backport 17.x)

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDumper.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDumperTest.java, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dumper/AllTypesWithNull.properties
Backport of this PR: https://github.com/geotools/geotools/pull/1517
This PR fix the dump of features to shapefiles that don't have a geometry type defined (they use the generic Geometry type) and have NULL geometries.
A test case was improved a new test case added.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5686
=> [GEOT-5686] Shapefile dumper throws a NPE on NULL geometry values (backport 16.x)

modules/library/main/src/main/java/org/geotools/data/crs/ReprojectFeatureReader.java, modules/library/main/src/test/java/org/geotools/data/crs/ReprojectFeatureReaderTest.java
Makes the reproject feature reader copy the user data from the original feature. A test case for this is also added.
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5692
=> [GEOT-5692] Reproject feature reader swallows feature user data

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMapping.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/UnmappingFilterVisitor.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/spi/CustomAttributeExpressionFactory.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/spi/CustomImplementationsFinder.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/spi/CustomMappingFactory.java, modules/unsupported/mongodb/pom.xml, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/AbstractCollectionMapper.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeature.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoInferredMapper.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/CollectionIdFunction.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/CollectionLinkFunction.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectAllFunction.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectFunction.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoCollectionFeature.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedAttributeExpressionFactory.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedMapping.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedMappingFactory.java, modules/unsupported/mongodb/src/main/resources/META-INF/services/org.geotools.data.complex.spi.CustomAttributeExpressionFactory, modules/unsupported/mongodb/src/main/resources/META-INF/services/org.geotools.data.complex.spi.CustomMappingFactory, modules/unsupported/mongodb/src/main/resources/META-INF/services/org.geotools.filter.FunctionExpression, modules/unsupported/mongodb/src/main/resources/META-INF/services/org.opengis.filter.expression.Function
This pull requests makes MongoDB usable with App-Schema. 
Two extensions points were created in App-Schema to allow extensions to contribute custom mappings for nested attributes. MongoDB data store was extended to be able to work in a complex mode.
Detailed documentation and online tests (integrations tests) are added by this pull request:
https://github.com/geoserver/geoserver/pull/2205
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5690
=> [GEOT-5690] Make MongoDB usable as a data store in app-schema

modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/MongoGeometryBuilder.java, modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java
Mongo recently added support for polygon queries that are bigger than a hemisphere:
https://docs.mongodb.com/manual/reference/operator/query/geometry/#op._S_geometry
Added code to support that feature.
=> [GEOT-5671] MongoDB Add support for polygon filter bigger than a hemisphere

docs/user/extension/ysld.rst, docs/user/library/render/style.rst, modules/library/api/src/main/java/org/geotools/styling/TextSymbolizer.java, modules/library/render/src/main/java/org/geotools/renderer/label/LabelSplitter.java, modules/library/render/src/main/java/org/geotools/renderer/style/SLDStyleFactory.java, modules/library/render/src/test/java/org/geotools/renderer/lite/PartialsTest.java, modules/library/render/src/test/java/org/geotools/renderer/style/SLDStyleFactoryTest.java, modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
https://osgeo-org.atlassian.net/browse/GEOT-5712
Mailing list discussion: http://osgeo-org.1560.x6.nabble.com/Adding-a-kerning-vendor-option-and-enable-it-by-default-td5314295.html
=> [GEOT-5712] Add a vendor option to enable kerning in text symbolizer (and have it on by default)

modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/LineMBLayer.java, modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBObjectParser.java, modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/MapboxTestUtils.java, modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/parse/MBFunctionTest.java, modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/parse/MBObjectParserTest.java, modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/transform/StyleTransformFunctionTest.java, modules/unsupported/mbstyle/src/test/resources/org/geotools/mbstyle/labelFunctionStyleTest.json
- Move "object" utility method from MBFunctionTest to MapboxTestUtils for reuse
- Update MBObjectParser to support function objects + test cases
- Fix "tranform" spelling error
=> MBObjectParser function support

modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/GridCoverage2DReader.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFResponse.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFReaderTest.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/granulecollector/BaseSubmosaicProducer.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/RasterLayerResponseTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5709
See also [GSIP 158 - NetCDF output support for variable attributes and extra variables](https://github.com/geoserver/geoserver/wiki/GSIP-158).
Depended on by https://github.com/geoserver/geoserver/pull/2281 ([GEOS-8099](https://osgeo-org.atlassian.net/browse/GEOS-8099)).
=> [GEOT-5709] Support coverage property SourceUrl

modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBObjectStops.java, modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/transform/MBStyleTransformer.java, modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/parse/MBStopsTest.java
Significant clean up of MBObjectsStops with methods being better named, data structures, and removal of dead code.  Refactor of MBStyleTransformer to take advantages of changes of changes to MBObjectsStops and make code easier to read.
=> code clean up for property zoom functions.

modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/parse/MBFilter.java, modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/parse/MBFilterTest.java
The code currently generates semantic type correctly; that is not used by the rendering engine to restrict content.
Looking at a default style in geoserver the ``dimension( geometry() )`` function is used to check for point, line or polygon content, along wiht ``isCoverage()``.
=> MBStyle - Support $type filters

modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/GridCoverage2DReader.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFResponse.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFReaderTest.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/RasterLayerResponse.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/granulecollector/BaseSubmosaicProducer.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/RasterLayerResponseTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5709
Backport to 17.x. Identical to changes on master.
Required by https://github.com/geoserver/geoserver/pull/2343.
=> [GEOT-5709] Support coverage property SourceUrl (17.x)

modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/layer/SymbolMBLayer.java, modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/transform/StyleTransformTest.java
Adds support for named system fonts to MBStyle (not using glyphs).
=> MBstyle - Supported named (ttf) fonts

docs/user/library/jts/operation.rst
that one linebreak which was supposed to separate the duplicate text was ignored according to markdown rules. No need for duplicate text here.
=> removed duplicate text.

modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/ReadResolutionCalculator.java, modules/library/coverage/src/test/java/org/geotools/coverage/grid/io/ReadResolutionCalculatorTest.java
Solution: compute separate x and y stretch factors
=> [GEOT-5735] ReadResolutionCalculator under-estimates the reading resolution in case one axis is stretched a lot more than the other

modules/library/metadata/src/main/java/org/geotools/util/URLs.java, modules/library/metadata/src/test/java/org/geotools/util/URLsTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5737
Replaces https://github.com/geotools/geotools/pull/1602: the duplication was addressed by [GEOT-5740](https://osgeo-org.atlassian.net/browse/GEOT-5740), and this PR adds the requested explanatory comment.
=> [GEOT-5737] URLs.fileToUrl does not percent-encode non-ASCII characters (master)

modules/unsupported/css/src/main/java/org/geotools/styling/css/CssParser.java, modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
- Usage of metrix prefixes (that's how SI calls them, because they normally come before the unit, while in CSS case they are suffix to the value because a scale is just a ratio, it's unitless)
- Allow using "@sd" instead of "@scale" in scale denominator rules
=> Css units related improvements

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AbstractMappingFeatureIterator.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccessFactory.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingAttributeIterator.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureCollection.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/MappingFeatureIteratorFactory.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/NestedAttributeMapping.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/XmlMappingFeatureIterator.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/DataAccessMap.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/joining/JoiningNestedAttributeMapping.java, modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/FeatureChainingTest.java
Implements what was suggested in this geoserver-user thread: [PostGIS Connections hanging under App Schema Plugin](http://osgeo-org.1560.x6.nabble.com/PostGIS-Connections-hanging-under-App-Schema-Plugin-td5319085.html#a5319171)
Connection re-use is limited to feature types belonging to the same App-Schema data store.
Further online unit tests will be added in a separate GeoServer PR.
=> [GEOT-5748] Improvements to App-Schema's connection usage

modules/library/main/src/main/java/org/geotools/filter/temporal/BinaryTemporalOperatorImpl.java, modules/library/main/src/main/java/org/geotools/temporal/object/DefaultInstant.java, modules/library/main/src/main/java/org/geotools/temporal/object/DefaultPeriod.java, modules/library/main/src/main/java/org/geotools/temporal/object/DefaultPosition.java, modules/library/main/src/test/java/org/geotools/filter/temporal/AfterImplTest.java, modules/library/main/src/test/java/org/geotools/filter/temporal/BeforeImplTest.java, modules/library/main/src/test/java/org/geotools/filter/temporal/BeginsImplTest.java, modules/library/main/src/test/java/org/geotools/filter/temporal/BegunByImplTest.java, modules/library/main/src/test/java/org/geotools/filter/temporal/DuringImplTest.java, modules/library/main/src/test/java/org/geotools/filter/temporal/EndedByImplTest.java, modules/library/main/src/test/java/org/geotools/filter/temporal/EndsImplTest.java, modules/library/main/src/test/java/org/geotools/filter/temporal/MeetsImplTest.java, modules/library/main/src/test/java/org/geotools/filter/temporal/MetByImplTest.java, modules/library/main/src/test/java/org/geotools/filter/temporal/OverlappedByTest.java, modules/library/main/src/test/java/org/geotools/filter/temporal/TContainsImplTest.java, modules/library/main/src/test/java/org/geotools/filter/temporal/TEqualsImplTest.java, modules/library/main/src/test/java/org/geotools/filter/temporal/TOverlapsImplTest.java
This pull request adds a toString method for temporal filters that is similar to what is currently used for other types of filters.  It also modifies the toString method for temporal objects that are used in the temporal filters to remove their newlines.  The newlines make the logs difficult to read, especially in some GeoServer requests where the filter string may be displayed multiple times per request.
Unit tests were added that simply checks that the default Object toString method is not being used.
The following CQL filter in a GeoServer request:
> issuetime DURING 2017-06-15T11:55:00.000Z/2017-06-15T15:15:00.000Z
instead of displaying a useless string like:
> org.geotools.filter.temporal.DuringImpl@e998726e
now displays the following in the logs:
> [ issuetime During …
=> [GEOT-5232] Added a toString method for temporal filters.

modules/library/coverage/src/main/java/org/geotools/coverage/processing/operation/Multiply.java, modules/unsupported/process-raster/src/test/java/org/geotools/process/raster/MultiplyProcessTest.java
* GEOT-5730 check if sources are supplied by 'Sources' parameter, which is what the WPS process, and possbily also other JAI-EXT code does. This makes switching between jai and jai-ext more transparant (for the multiply operation).
* GEOT-5730 unit test now uses and tests jai-ext behaviour, which should makes it work when running it on travis
* GEOT-5730 removed redundand jai-ext setup calls
* GEOT-5730 force jai reinit, to avoid unwanted changes from other unit tests
=> GEOT-5730 (backport) check if sources are supplied by 'Sources' parameter

modules/library/render/src/main/java/org/geotools/renderer/label/LabelCacheImpl.java, modules/library/render/src/main/java/org/geotools/renderer/lite/RendererUtilities.java, modules/library/render/src/test/java/org/geotools/renderer/lite/RenderUtilitiesTest.java
- Adds getGeometryCentroid method for “safe” centroid calculation for polygon
- Adds sampleForCentralPoint for finding “centroid” that lies within
the polygon
This change is in support of [GEOS-8033](https://osgeo-org.atlassian.net/browse/GEOS-8033) where the goal is to add some better placemark placement for polygons. The idea is to factor out some of the rendering code so it can be reused.
=> Factoring out some centroid code from label cache to RendererUtiliites.

modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCNotBinding.java, modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/FilterMockData.java, modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/NotBindingTest.java
=> [GEOT-5697] fix encoding the filter Not( is null ) as XML

modules/unsupported/javafx/NOTICE.txt, modules/unsupported/javafx/README.md, modules/unsupported/javafx/REVIEW.md, modules/unsupported/javafx/pom.xml, modules/unsupported/javafx/src/main/java/org/geotools/javafx/FXMap.java, modules/unsupported/javafx/src/main/java/org/geotools/javafx/MapStyles.java, modules/unsupported/javafx/src/test/java/org/geotools/javafx/FXMapTest.java, modules/unsupported/pom.xml
This commit creates the JavaFX map module.
=> Initial commit JavaFX map module

docs/user/library/data/ogr.rst, modules/plugin/ogr/ogr-core/src/test/java/org/geotools/data/ogr/OGRDataStoreTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5780
=> [GEOT-5780] OGR GeoJSON layer name changes with GDAL 2.2 or later, breaking BridjOGRDataStoreTest (master)

modules/library/render/src/main/java/org/geotools/renderer/label/LabelCacheImpl.java, modules/library/render/src/test/java/org/geotools/renderer/label/LabelCacheImplTest.java
Allows the call to `LabelPainter`'s constructor in `LabelCacheImpl` to be replaced with a `BiFunction`.
Injecting an extended `LabelPainter` allows downstream usage of the label placement code at a higher level (as in the GeoServer Vector Tiles module).  It should also be useful for more targeted unit tests.
=> Allow injecting different LabelPainters in LabelCacheImpl

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccessFactory.java, modules/extension/app-schema/sample-data-access/src/main/java/org/geotools/data/SampleDataAccessFactory.java, modules/library/jdbc/src/main/java/org/geotools/data/jdbc/datasource/DBCPDataSourceFactory.java, modules/library/jdbc/src/main/java/org/geotools/data/jdbc/datasource/JNDIDataSourceFactory.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStoreFactory.java, modules/plugin/arcsde/datastore/src/main/java/org/geotools/arcsde/ArcSDEDataStoreFactory.java, modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDataStoreFactory.java, modules/plugin/jdbc/jdbc-db2/src/main/java/org/geotools/data/db2/DB2NGDataStoreFactory.java, modules/plugin/jdbc/jdbc-h2/src/main/java/org/geotools/data/h2/H2DataStoreFactory.java, modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDataStoreFactory.java, modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleNGDataStoreFactory.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisNGDataStoreFactory.java, modules/plugin/jdbc/jdbc-spatialite/src/main/java/org/geotools/data/spatialite/SpatiaLiteDataStoreFactory.java, modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDataStoreFactory.java, modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/jtds/JTDSSqlServerDataStoreFactory.java, modules/plugin/jdbc/jdbc-teradata/src/main/java/org/geotools/data/teradata/TeradataDataStoreFactory.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStoreFactory.java, modules/unsupported/jdbc-ng/jdbc-ingres/src/main/java/org/geotools/data/ingres/IngresDataStoreFactory.java, modules/unsupported/mbtiles/src/main/java/org/geotools/mbtiles/MBTilesDataStoreFactory.java
See https://osgeo-org.atlassian.net/browse/GEOT-5790
Adds LEVEL="program" to DBTYPE / DSTYPE / FILETYPE parameters for all the various datastore implementations.
Ultimately intended to fix https://osgeo-org.atlassian.net/browse/GEOS-8010
=> [GEOT-5790] dbtype and filetype should be marked as 'program'-level parameters

modules/library/coverage/src/main/java/org/geotools/coverage/TypeMap.java, modules/library/render/src/main/java/org/geotools/renderer/lite/gridcoverage2d/GridCoverageRenderer.java, modules/library/render/src/test/java/org/geotools/renderer/lite/GridCoverageRendererTest.java
@dromagnoli 
This can occur with non-byte images. (Remote sensing images commonly use shorts as data type, both in netcdf and geotiff files.)
=> GEOT-5773 avoid NPE in GridCoverageRenderer when colormodel is null

modules/unsupported/csv/pom.xml, modules/unsupported/csv/src/main/java/org/geotools/data/csv/CSVDataStoreFactory.java, modules/unsupported/csv/src/main/java/org/geotools/data/csv/CSVFeatureStore.java, modules/unsupported/csv/src/main/java/org/geotools/data/csv/parse/CSVAttributesOnlyStrategy.java, modules/unsupported/csv/src/main/java/org/geotools/data/csv/parse/CSVLatLonStrategy.java, modules/unsupported/csv/src/test/java/org/geotools/data/csv/CSVDataStoreTest.java, modules/unsupported/csv/src/test/java/org/geotools/data/csv/CSVWriteTest.java, modules/unsupported/csv/src/test/java/org/geotools/data/csv/parse/CSVLatLonStrategyTest.java, modules/unsupported/csv/src/test/java/org/geotools/data/csv/parse/CSVWriteStrategyTest.java
See [GEOT-5796](https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-5796) for discussion.
Essentially a cleanup of CSVDataStoreFactory to make it easier to use and some fixes to the way geometries are handled in the various strategies.
=> [GEOT-5796] Fixes and improvements for CSVDataStoreWriters

modules/library/render/src/main/java/org/geotools/renderer/label/LabelCacheImpl.java, modules/library/render/src/main/java/org/geotools/renderer/lite/RendererUtilities.java, modules/library/render/src/test/java/org/geotools/renderer/lite/RenderUtilitiesTest.java
- Adds getGeometryCentroid method for “safe” centroid calculation for polygon
- Adds sampleForInternalPoint for finding “centroid” that lies within the polygon
(cherry picked from commit 9ea00c39659b3cd4cd057e06447d688d1f5e8b9c)
=> Factoring out some centroid code from label cache to RendererUtiliities (backport).

pom.xml
This change aligns GeoTools with GeoServer and allows GeoTools to be built with `MAVEN_OPTS=-Xmx512m` (full build but not javadocs). Once merged, I intend to backport to this change to all active branches and configure  `MAVEN_OPTS=-Xmx512m` on Travis.
=> Upgrade git-commit-id-plugin to 2.1.15 and port options from GeoServer

modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/SymbolMBLayerTest.java
The test result changed due to the removal of the icon field in the .json test file.  15 would be the desired result now.
=> fixed icon padding test

modules/extension/wms/src/main/java/org/geotools/data/wms/xml/ogcComplexTypes.java, modules/unsupported/wfs-ng/src/main/resources/META-INF/services/org.geotools.xml.schema.Schema
because this lists a non-existent class, also remove commented code that used this class.
see: https://osgeo-org.atlassian.net/browse/GEOT-5795
=> [GEOT-5795] remove services file org.geotools.xml.schema.Schema from wfs-ng

modules/extension/wms/src/main/java/org/geotools/data/wms/xml/ogcComplexTypes.java, modules/unsupported/wfs-ng/src/main/resources/META-INF/services/org.geotools.xml.schema.Schema
because this lists a non-existent class, also remove commented code that used this class.
see: 
- https://osgeo-org.atlassian.net/browse/GEOT-5795
-  #1667
=> [GEOT-5795] remove services file org.geotools.xml.schema.Schema from wfs-ng (17.x)

modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/transform/VisualTransformerTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5829
=> [GEOT-5829] Font antialiasing differences cause gt-mbstyle VisualTransformerTest failures on OpenJDK (master)

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDateOnlineTest.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDateTestSetup.java
We need to register a new type mapping to force java.sql.Timestamp to
be mapped to Oracle TIMESTAMP type (not DATE type) so time information
won't be lost when inserting features with java.sql.Timestamp attributes
(GeoTools maps DATE to java.sql.Date and strips time information before
inserting to database).
=> [GEOT-5823] Mapping java.sql.Timestamp to TIMESTAMP database type

modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/MBStyle.java, modules/unsupported/mbstyle/src/main/java/org/geotools/mbstyle/source/GeoJsonMBSource.java, modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/MapBoxStyleTest.java, modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/parse/MBStopsTest.java, modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/parse/StyleParseTests.java, modules/unsupported/mbstyle/src/test/java/org/geotools/mbstyle/transform/VisualTransformerTest.java, modules/unsupported/mbstyle/src/test/resources/org/geotools/mbstyle/groupStyleTest.json
* Adds support for the new "Style Group" functionality to MBStyle
* Uses world-spanning inline features for layers which have no geometry, i.e. background layers.
* GeoJSON layers now correctly extend MBSource rather than TileMBSource, in accordance with the MBStyle spec.
=> Use multiple 'NamedLayer's for seperate MBStyle 'source-layer's

modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java, modules/unsupported/mongodb/src/test/java/org/geotools/data/mongodb/MongoTestSetup.java
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-5717
=> [GEOT-5717] - MongoDB support optional milliseconds in ISO8601 date/time string

modules/extension/wmts/src/main/java/org/geotools/data/wmts/model/TileMatrixSet.java, modules/extension/wmts/src/main/java/org/geotools/data/wmts/model/WMTSCapabilities.java, modules/extension/wmts/src/test/java/org/geotools/data/wmts/model/WMTSCapabilitiesTest.java, modules/extension/wmts/src/test/resources/test-data/ol.getcapa.xml, modules/extension/xsd/xsd-wmts/src/main/java/org/geotools/wmts/bindings/ContentsTypeBinding.java, modules/extension/xsd/xsd-wmts/src/main/java/org/geotools/wmts/bindings/TileMatrixSetBinding.java
Using the capabilitites document at
https://openlayers.org/en/v4.3.4/examples/data/WMTSCapabilities.xml
an exception is thrown:
```
java.lang.RuntimeException: Parsing failed for TileMatrixSet: java.lang.ClassCastException: java.net.URI cannot be cast to java.lang.String
at org.geotools.wmts.bindings.TileMatrixSetBinding.parse(TileMatrixSetBinding.java:123)
...
=> [GEOT-5840] Fix handling WellKnownScaleSet in WMTS getCapabilities

modules/unsupported/geojson/src/main/java/org/geotools/geojson/GeoJSONUtil.java, modules/unsupported/geojson/src/main/java/org/geotools/geojson/geom/GeometryHandlerBase.java, modules/unsupported/geojson/src/test/java/org/geotools/geojson/GeometryJSONTest.java
If a GeoJSON object has only one ordinate the parser will now throw an exception instead of quietly assuming 0.
=> [GEOT-5845] GeoJSON now fails to read single ordinate coordinates.

docs/developer/procedures/release.rst
Minor updates to the release guide based on performing the 18-RC1 release. Mainly updating links from ares to build.geoserver.org.
=> Update release guide

modules/plugin/jdbc/jdbc-mysql/src/main/java/org/geotools/data/mysql/MySQLDialect.java
The pull request affects the behavior of some postCreate actions of MySQLDialect class. More specifically
- in encodePostColumnCreateTable() method it checks whether for the GeometryDescriptor column, NOT NULL is already specified
- in postCreateTable(...) the SQL statement used for inserting entries in the geometry_columns tables (which maintains meta data information about spatial columns in other tables) now includes the column names. This is pretty useful in the case the geometry_columns has been manually created and includes an extra PK autogenerated or any other extra columns.
The enhancement can be applied at least to all geotools versions for 14.x and onwards 
=> [GEOT-5751] MySQLdialect postCreate enhancements

modules/extension/wms/src/main/java/org/geotools/data/wms/request/AbstractGetMapRequest.java, modules/extension/wms/src/test/java/org/geotools/data/wms/test/Geot5777Test.java
Fix for [GEOT-5777](https://osgeo-org.atlassian.net/browse/GEOT-5777) where adding a bbox string with spaces in breaks the final url.
=> [GEOT-5777] prevent users from adding spaces to WMS urls via the bounding box

modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/CollectionIdFunction.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectFunction.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoCollectionFeature.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedAttributeExpressionFactory.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedMapping.java, modules/unsupported/mongodb/src/main/java/org/geotools/data/mongodb/complex/NestedCollectionLinkFunction.java, modules/unsupported/mongodb/src/main/resources/META-INF/services/org.geotools.filter.FunctionExpression, modules/unsupported/mongodb/src/main/resources/META-INF/services/org.opengis.filter.expression.Function
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5866
Integration tests where updated accordingly: https://github.com/geoserver/geoserver/pull/2632
Note that all the changes happen in ``org.geotools.data.mongodb.complex`` package.
Non recursive paths make MongoDB mappings very impossible to manage \ create mappings for a complex use case. But to avoid that someone who use the old full paths notation to be stuck on an upgrade a legacy compatibility mode was created.
=> [GEOT-5866] MongoDB integration with App-Schema nested mappings are not evaluated relatively

modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/FeatureCollectionEncoderDelegate.java, modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/GMLWriter.java, modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/GeometryEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/CurveEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GML32FeatureCollectionEncoderDelegate.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GenericGeometryEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GeometryCollectionEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/LineStringEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/LinearRingEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiLineStringEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiPointEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiPolygonEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/PointEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/PolygonEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/RingEncoder.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/CurveEncoderTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/GeometryCollectionEncoderTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/GeometryEncoderTestSupport.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/LineString3DTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/MultiCurveEncoderTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/MultiPointTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/MultiPolygonTest.java, modules/extension/xsd/xsd-wfs/src/main/java/org/geotools/wfs/v2_0/WFS20FeatureCollectionEncoderDelegate.java, modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/WFSFeatureCollectionEncodingTest.java
https://osgeo-org.atlassian.net/browse/GEOT-5885
=> [GEOT-5885] GML 3.2 encoding misses mandatory gml:id on geometry elements - fast path

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/SchemaIndexImpl.java
Destroy method could throw a NPE if there were no schemas,
=> GEOT-5889: Fix NPE in destroy method

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java, modules/library/jdbc/src/test/java/org/geotools/data/jdbc/FilterToSQLTest.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCInEncodingOnlineTest.java, modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_in10.java, modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_in2.java, modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_in3.java, modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_in4.java, modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_in5.java, modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_in6.java, modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_in7.java, modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_in8.java, modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_in9.java, modules/library/main/src/main/java/org/geotools/filter/function/InFunction.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgInEncodingOnlineTest.java, modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2InEncodingOnlineTest.java, modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLInEncodingOnlineTest.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleInEncodingOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisInEncodingOnlineTest.java, modules/plugin/jdbc/jdbc-sqlserver/src/test/java/org/geotools/data/sqlserver/SQLServerInEncodingOnlineTest.java
I had the doubt of whether to allow encoding of "in" functions in sqlserver and oracle since they don't accept them as expressions like other databases but... I don't think it's worth throwing away the good use case (in(att, v1, v2, v3)=true) because those database don't support the one that does not make sense (in(att, v1, v2, v3) > false),  even if evaluated in memory it actually works.
=> Encode in functions

build/maven/javadoc/pom.xml
I try to build GeoTools with Java 9. The first build failure is in Maven Javadoc module, as it relies on the existence of `tools.jar` in JDK directory. This is no longer true starting from JDK9, so the current profiles must be restricted to JDK8. The obsolete pre-JDK7 profile has been dropped.
=> Maven Javadoc module: Activate JDK8 profiles only with Java 8

modules/library/metadata/src/main/java/org/geotools/factory/FactoryRegistry.java
Follow up to review and downstream integration experience.
Placeholder deprecated lookupProviders methods added to FactoryRegistry in case any code had a static dependency on a method formally available from superclass ServiceRegistry.
Added a finalize method to deregister all factortories on object cleanup.
Signed-off-by: Jody Garnett <jody.garnett@gmail.com>
=> FactoryRegistry placeholder lookupProviders methods, and finalizer

modules/library/render/src/main/java/org/geotools/renderer/style/SLDStyleFactory.java, modules/library/render/src/test/java/org/geotools/renderer/style/SLDStyleFactoryTest.java
Adds a check to see if the size of the graphic * 3 will overflow MAX_INTEGER, prints a warning instead of a NegativeArraySizeException and Stacktrace.
=> [GEOT-5878] Very long symbols can cause an integer overflow when rendered

modules/unsupported/geobuf/pom.xml, modules/unsupported/geobuf/src/main/java/org/geotools/data/geobuf/Geobuf.java
The unsupported Geobuf module depends on an old version of Google's protobuf library. I would like to upgrade from 2.x to 3.x because the 3.x versions are binary compatible with all other 3.x versions. 
JIRA:
https://osgeo-org.atlassian.net/browse/GEOT-5901
=> Upgrade geobuf's protobuf dependency from 2 to 3

modules/unsupported/geobuf/pom.xml, modules/unsupported/geobuf/src/main/java/org/geotools/data/geobuf/Geobuf.java
The upgrade to protobuf 3.5.0 was causing problems for the Eclipse compiler. Downgrading to 3.4.0 works with maven and eclipse.
https://osgeo-org.atlassian.net/browse/GEOT-5910
=> Downgrade protobuf to 3.4.0 to fix eclipse compiling issues

modules/plugin/epsg-wkt/src/test/java/org/geotools/referencing/crs/CRSTest.java
Java 9 contains a new native math library that is faster and more precise, but not backwards compatible with results produces using Java 8 and older.
A tolerance allows us to continue supporting both language versions.
Refer to the mailing list discussion for more details.
=> Add tolerance to CRSTest coordinate comparaisons to support Java 9

modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDataStoreAPIOnlineTest.java
Some recent changes to geopackage added an unnecessary import which causes a compilation failure on OS X. 
Since the import does not appear to be being used, I have removed it.
=> Fix OS X Compile failure in GeoPkgDataStoreAPIOnlineTest

modules/extension/xsd/xsd-kml/src/main/java/org/geotools/kml/bindings/LookAtTypeBinding.java, modules/extension/xsd/xsd-kml/src/main/java/org/geotools/kml/bindings/PlacemarkTypeBinding.java, modules/extension/xsd/xsd-kml/src/test/java/org/geotools/kml/bindings/LookAtTypeBindingTest.java, modules/extension/xsd/xsd-kml/src/test/java/org/geotools/kml/v22/KMLPlacemarkLookAtTest.java, modules/extension/xsd/xsd-kml/src/test/resources/org/geotools/kml/v22/geot5666.kml
From https://osgeo-org.atlassian.net/browse/GEOT-5666  - fix LookAt coordinate order and avoid parsing LookAt as the placemark geometry.
=> [GEOT-5666] Avoid parsing the LookAt as the placemark geometry.

modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFReader.java
https://osgeo-org.atlassian.net/browse/GEOT-5923
NetCDFReader references a coverage list without checking for null, causing the access cleanup portion of dispose() to be skipped (line 696).
Move "coverages.clear()" into the conditional check that coverages is not null.
```sh
java.lang.NullPointerException
at org.geotools.coverage.io.netcdf.NetCDFReader.dispose(NetCDFReader.java:696)
...
```
=> NullPointerException clearing coverages in NetCDFReader.dispose

modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/cache/CacheConfig.java, modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/cache/CacheManagement.java
Simple improvements I've jotted down while having a look at the module:
- One typo fix
- Making the chunk size configurable (JPEG compressed geotiff files can be pretty small)
- Avoid NPE on open when the disk storage is disabled
Nothing major, use as you see fit.
=> Simple improvements to S3 cache

modules/extension/tile-client/pom.xml, modules/extension/tile-client/src/main/java/org/geotools/tile/impl/osm/OSMTileFactory.java, modules/extension/tile-client/src/test/java/org/geotools/tile/impl/osm/OSMTileFactoryTest.java
Fixes [GEOT-5938](https://osgeo-org.atlassian.net/browse/GEOT-5938) where sometimes rounding error caused the YTileIndex negative causing an exception to be thrown.
=> GEOT-5938 OSMTileFactory can throw an exception when looking for the TopLeft tile

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/DescribeFeatureTypeResponseFactory.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/parsers/GetFeatureResponseParserFactory.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/WFSClientTest.java, modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/ArcGIS/DescribeFeatureType.xsd, modules/unsupported/wfs-ng/src/test/resources/org/geotools/data/wfs/test-data/ArcGIS/GetCapabilities.xml
The addition of a new output format allow the execution of POST requests again an ArcGIS Server WFS data source. (GET does not work yet, since ArcGIS Server expects spaces to be encoded as "%20", but class URIs usea the Java URLEncoder, which converts spaces into "+".)
=> Improved support for ArcGIS WFS data source

docs/user/library/coverage/jdbc/faq.rst, docs/user/library/coverage/jdbc/index.rst, docs/user/library/coverage/jdbc/internal.rst, docs/user/library/coverage/mosaic.rst
Includes a few other trivial fixes in the same files.
=> fix(docs): Fix "Moasic" typo.

modules/extension/wms/src/main/java/org/geotools/data/wms/xml/WMSComplexTypes.java, modules/extension/wms/src/test/java/org/geotools/data/wms/xml/test/WMSComplexTypesTest.java, modules/extension/wms/src/test/resources/org/geotools/data/wms/xml/test/test-data/1.1.0CapabilitiesInvalid.xml
Fix for https://osgeo-org.atlassian.net/browse/GEOS-8477
(Bug was reported against GeoServer, but the actual fix is in GeoTools)
Modified _LegendURLType to support returning null values.
This is consistent with the behaviour of other Types in WMSComplexTypes, such as _OnlineResourceType.
Also tested manually in geoserver, to ensure the WMS store could be created.
=> [GEOS-8477] Support null values in WMSComplexTypes$_LegendURLType

modules/plugin/coverage-multidim/coverage-api/src/main/java/org/geotools/coverage/io/catalog/CoverageSlicesCatalog.java, modules/plugin/coverage-multidim/coverage-api/src/main/java/org/geotools/coverage/io/catalog/DataStoreConfiguration.java, modules/plugin/coverage-multidim/coverage-api/src/main/java/org/geotools/imageio/GeoSpatialImageReader.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/NetCDFAccess.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/AncillaryFileManager.java, modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/imageio/netcdf/utilities/NetCDFUtilities.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFBasicTest.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFMosaicReaderTest.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/GranuleDescriptor.java
The NetCDFImageReader initialization spends most of its time setting up the index datastore.
This pull request allows to use a repository provided datastore, thus allowing a pre-existing store to be used, thus dodging the expensive init. The machinery has been setup to that if available, it can use the GeoServer CatalogRepository already provided to the image mosaic for the image mosaic index. The
configuration parameter has the same name.
=> [GEOT-5822] Improve ImageMosaic's NetCDF performances

modules/library/main/src/main/java/org/geotools/filter/Capabilities.java, modules/library/main/src/main/java/org/geotools/filter/capability/FilterCapabilitiesImpl.java, modules/library/main/src/main/java/org/geotools/filter/visitor/IsFullySupportedFilterVisitor.java, modules/library/main/src/main/java/org/geotools/filter/visitor/IsSupportedFilterVisitor.java, modules/library/main/src/test/java/org/geotools/filter/CapabilitiesTest.java
Update opengis FilterCapabilities implementation and wrapper to support temporal operators. Also fix a bug with `BegunBy` in the IsSupportedFilterVisitors which would cause the operator to never be supported.
*CLA has been sent to OSGeo*
=> GEOT-5931: Temporal operators in opengis FilterCapabilities implementation and wrapper

modules/extension/complex/src/main/java/org/geotools/data/complex/ComplexFeatureConstants.java
Associated issue: https://osgeo-org.atlassian.net/browse/GEOT-5972
=> [GEOT-5972] App-Schema default geometry name should not be empty

pom.xml
MySql driver updated to version 5.1.40
The pull request addresses the improvement proposed in jira issue  [[GEOT-5973]](https://osgeo-org.atlassian.net/browse/GEOT-5973)
=> [GEOT-5973] update MySql jdbc driver to a newer version

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
https://osgeo-org.atlassian.net/browse/GEOT-5983
Related PR:
https://github.com/geotools/geotools/pull/1846#issuecomment-377697840
=> [GEOT-5983] App-Schema complex filter splitter doesn't take into account multiple nested attributes matches

modules/unsupported/process-feature/src/main/java/org/geotools/process/vector/SimplifyProcess.java
It seems that the two simplifiers in the `SimplifyProcess` class got mixed up. This commit fixes that.
I should note that I have just started working with your project and that therefore I did not know how to verify that `SimplifyProcess` really uses the wrong simplifier. I concluded that the simplifiers are mixed up only by reading the source code. So I *might* be wrong about this.
=> [GEOT-5986] SimplifyProcess: switch simplifiers

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDataStoreAPIOnlineTest.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDataStoreAPITestSetup.java
This will ignore oracle spatial index statistics tables which have the form of `MDXT_<nnnn>$BKTS` and `MDXT<nnnn>$_MBR` eg. `MDXT_F9E0E$_BKTS` and `MDXT_F9E0E$_MBR`
fixes [GEOT-5990](https://osgeo-org.atlassian.net/browse/GEOT-5990)
=> [GEOT-5990] Oracle: Ignore spatial index statistics tables

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDataStoreAPIOnlineTest.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleDataStoreAPITestSetup.java
This will ignore oracle spatial index statistics tables which have the form of `MDXT_<nnnn>$BKTS` and `MDXT<nnnn>$_MBR` eg. `MDXT_F9E0E$_BKTS` and `MDXT_F9E0E$_MBR`
fixes [GEOT-5990](https://osgeo-org.atlassian.net/browse/GEOT-5990)
see #1862
=> [GEOT-5990] Oracle: Ignore spatial index statistics tables (19.x backport)

modules/extension/wmts/src/main/java/org/geotools/data/wmts/client/WMTSTile.java
Concerning the class org.geotools.data.wmts.client.WMTSTile in the extesion gt-wmts:
This class sends a GetTile request as KVP to the WMTS server with request value 'getTile' instead of 'GetTile'.
The convention is to use 'GetTile'.
=> [GEOT-5999] gt-wmts WMTSTile GetTile request casing

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/test/XMLTestSupport.java, modules/extension/xsd/xsd-filter/src/main/java/org/geotools/filter/v1_0/OGCPropertyIsLikeTypeBinding.java, modules/extension/xsd/xsd-filter/src/main/resources/org/geotools/filter/v1_0/filter.xsd, modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/BinaryComparisonOpTypeBindingTest.java, modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/FilterMockData.java, modules/extension/xsd/xsd-filter/src/test/java/org/geotools/filter/v1_0/OGCPropertyIsLikeTypeBindingTest.java
Infact anything that encodes/decodes a Like filter with a LHS function will fail.
=> [GEOT-5920] WFSClient fails when a function is used in a query

modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCJNDIDataSourceOnlineTest.java, modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2DataStoreFactoryTest.java
An attempt to fix the inexplicable failure of `H2DataStoreFactoryTest` in [Jenkins geotools-master-online-postgis](https://build.geoserver.org/view/geotools/job/geotools-master-online-postgis/596/consoleText) when it passes everywhere else. Something strange going on with H2 and the finalizer thread? First: fix the DataStore leaks.
=> Fix DataStore leaks in H2 tests

modules/extension/wms/src/main/java/org/geotools/data/ows/StyleImpl.java, modules/extension/wmts/src/main/java/org/geotools/data/wmts/client/WMTSTileService.java, modules/extension/wmts/src/main/java/org/geotools/data/wmts/model/WMTSCapabilities.java, modules/extension/wmts/src/main/java/org/geotools/data/wmts/model/WMTSLayer.java, modules/extension/wmts/src/main/java/org/geotools/data/wmts/request/AbstractGetTileRequest.java, modules/extension/wmts/src/test/java/org/geotools/data/wmts/client/WMTSServiceTest.java
ESRI WMTS servers require the style to be named and throw an http 400 server exception if it is missing (but no other clue). Sadly the WMTS specification seems to agree so I've fixed it rather than just blame ESRI.
Fix for [GEOT-6017](https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-6017).
=> fix for missing style name in WMTS requests [GEOT-6017]

modules/plugin/mongodb/pom.xml
https://osgeo-org.atlassian.net/browse/GEOT-6019
=> [GEOT-6019] MongoDB plugin pom.xml has unsuported modules as parent pom.xml (19.x)

modules/plugin/mongodb/pom.xml
https://osgeo-org.atlassian.net/browse/GEOT-6019
=> [GEOT-6019] MongoDB plugin pom.xml has unsuported modules as parent pom.xml (18.x)

modules/extension/app-schema/app-schema/src/test/java/org/geotools/http/HttpStaticServer.java
https://osgeo-org.atlassian.net/browse/GEOT-6023
=> [GEOT-6023] app-schema HttpConfigTest fails if port 8080 is busy

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/VirtualTable.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCVirtualTableOnlineTest.java
https://osgeo-org.atlassian.net/browse/GEOT-6034
There is nod documentation about virtual tables in GeoTools, the relevant documentation for this use case is added in GeoServer documentation.
=> [GEOT-6034] Allow the usage of a place holder for the :where: clause created by GeoServer in virtual tables

modules/extension/tile-client/src/main/java/org/geotools/tile/impl/osm/OSMService.java
https://osgeo-org.atlassian.net/browse/GEOT-6052
This small change adds support for higher zoom levels on OSM or similar tile services.
=> [GEOT-6052] Extend scaleList for OSMServices

modules/plugin/epsg-hsql/src/main/java/org/geotools/referencing/factory/epsg/ThreadedHsqlEpsgFactory.java, modules/plugin/epsg-hsql/src/test/java/org/geotools/referencing/factory/epsg/ThreadedHsqlEpsgFactoryTest.java, pom.xml
https://osgeo-org.atlassian.net/browse/GEOT-6050
=> [GEOT-6050] Upgrade HSQLDB to 2.4.1

modules/unsupported/geojsonstore/pom.xml, pom.xml
Backport of https://github.com/geotools/geotools/pull/1952
=> [GEOT-6055] Upgrade commons-io dependency to 2.6 (backport 19.x)

modules/unsupported/geojsonstore/pom.xml, pom.xml
Backport of https://github.com/geotools/geotools/pull/1952
=> [GEOT-6055] Upgrade commons-io dependency to 2.6 (backport 18.x)

modules/plugin/jdbc/jdbc-h2/pom.xml
This change excludes a broken hatbox transitive dependency on a nonexistent jts-core 1.15.1-SNAPSHOT.
=> exclude jts-core transitive dependency

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/ParserHandler.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xml/impl/ValidatorHandler.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xml/ParserTest.java
This pull requests updates ValidatorHandler to handle XML entities in the same way as ParserHandler.  All of the ValidatorHandler changes were copied from ParserHandler.
This pull request can be backported to 18.x and 19.x.
=> Set the EntityResolver on the XML Validator.

modules/library/main/src/main/java/org/geotools/filter/function/EnvFunction.java, modules/library/main/src/test/java/org/geotools/filter/function/EnvFunctionTest.java
This change is not very interesting per se, but supports the fix in https://github.com/geoserver/geoserver/pull/3002
=> [GEOT-6063] Allow extracting EnvFunction local values as a read only map

modules/extension/xsd/xsd-kml/src/main/java/org/geotools/kml/bindings/LinearRingTypeBinding.java, modules/extension/xsd/xsd-kml/src/test/java/org/geotools/kml/bindings/LinearRingTypeBindingTest.java
If a KMLs polygon start point and end point are not the same it is considered invalid and JTS throws an exception saying it is not closed. Google earth and other KML viewers will still work with these invalid polygons and geoserver doesn't which is a problem.
So this commit rectifies it by closing unclosed linear rings by pushing a cloned start point to the end of the coordinate list if the polygon is unclosed.
=> [GEOT-6072] close KML LinearRings automatically if they are invalid and not closed

modules/unsupported/csv/src/main/java/org/geotools/data/csv/parse/CSVLatLonStrategy.java, modules/unsupported/csv/src/main/java/org/geotools/data/csv/parse/CSVSpecifiedWKTStrategy.java, modules/unsupported/csv/src/test/java/org/geotools/data/csv/parse/CSVLatLonStrategyTest.java, modules/unsupported/csv/src/test/java/org/geotools/data/csv/parse/CSVSpecifiedWKTStrategyTest.java
Other wise the feature type is regenerated with default Integer attribute
types.
=> GEOT-6071, CSV strategies should save the featureType in createSchema

modules/library/main/src/main/java/org/geotools/feature/simple/SimpleFeatureTypeBuilder.java, modules/library/main/src/test/java/org/geotools/feature/simple/SimpleTypeBuilderTest.java
See https://osgeo-org.atlassian.net/browse/GEOS-6070 and https://github.com/geoserver/geoserver/pull/3014
Changes
* Copy defaultGeometry from existing featureType
* Unset defaultGeometry if that attribute is removed
* Unset defaultGeometry if the FeatureType is retyped such that the geometry is no longer included (preserve it if it is merely renamed)
=> [GEOT-6070] Copy existing defaultGeometry on SimpleFeatureTypeBuilder.init(SimpleFeatureType)

docs/user/welcome/upgrade.rst
Introduced headings to seperate out different GeoTools 20 upgrade activities as was done for prior releases with more than one API change
=> provide jts 1.15 upgrade instructions

modules/library/xml/src/main/java/org/geotools/GML.java
It now throws an exception if version is not supported
=> [GEOT-6078] GML encoder silently fails when Version.GML3 is used

docs/user/tutorial/datastore/intro.rst
`archetype:create` does not work with recent maven plugins.
=> Update datastore tutorial maven archetype command

modules/library/metadata/src/main/java/org/geotools/util/logging/CommonsLoggerFactory.java
If uDig upgrades to 19.x (https://github.com/locationtech/udig-platform/pull/279) it requires to get this fix backported to 19.x branch
origin pull request was #1997 
Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>
=> Backport GEOT-6084 to 19.x

modules/library/referencing/pom.xml, modules/library/referencing/src/test/java/org/geotools/referencing/GeodeticCalculatorTest.java
The reason for the test change is that GeographicLib 1.48 (and a little in 1.47) has
a change in behaviour. From the release notes:
"The default range for longitude and azimuth is now (-180d, 180d],
instead of [-180d, 180d). This was already the case for the C++
library; now the change has been made to the other implementations
(C, Fortran, Java, JavaScript, Python, MATLAB, and Maxima)."
=> [GEOT-6102] Upgrade GeographicLib to 1.49

modules/library/referencing/src/main/java/org/geotools/referencing/operation/transform/ProjectiveTransform.java, pom.xml
The EJML inverse function was changed to return a MatrixDimensionException if the input is not square:
https://github.com/lessthanoptimal/ejml/commit/ca9f8d528dd4a460658d3223b626a494de297f73#diff-16e60a287b7af132b57bfc757a7c8dc6R682
I kept the old catch for IllegalArgumentException just in case that still gets used somewhere.
=> [GEOT-6103] Upgrade EJML to 0.34

pom.xml
These were added when geogit was added, and probably should have been removed as
part of commit 56f9bc507c76d05716e20fb.
=> Remove left-over geogit module dependencies

docs/user/welcome/upgrade.rst
Trivial fix for the 20.x migration docs
=> [docs] Add a missing double quote in the sed command

pom.xml
I did a full build of geoserver against the modified geotools, but I don't have an online test environment, and it really does need that kind of test.
@bencaradocdavies Can you run the tests?
=> [GEOT-6106] Upgrade postgresql JDBC driver to 42.2.5

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgFilterToSQL.java
Backport the GeoPackage filtering fix to 20.x.
Original pull request against master: https://github.com/geotools/geotools/pull/2024
JIRA: https://osgeo-org.atlassian.net/browse/GEOT-6107
Thanks!
Jared
=> Backport GEOT-6107 to 20.x: Add AttributeDescriptor to descriptors list to fix filtering of geopackages

modules/extension/xsd/xsd-wps/pom.xml, pom.xml
JTS doesn't depend on xerces anymore. Threre's no need to declare this exclusion any longer.
The xerces dependency was removed from the pom file in JTS version 1.13 and later.
This fixes GEOT-3942.
Details:
The 19.x branch of geotools uses the jts distibution from vividsolutions. The migration to JTS from locationtech removed this dependency. 
```
|    |    |    |    |    |    |    +--- org.geotools:gt-coverage:19.2
...
|    |    |    |    |    |    |    |    +--- com.vividsolutions:jts-example:1.14.0
|    |    |    |    |    |    |    |    |    +--- com.vividsolutions:jts-core:1.14.0
|    |    |    |    |    |    |    |    |    \--- com.vividsolutions:jts-io:1.14.0
|    |    |    |    |    |    |    |    |         +--- com.vividsolutions:jts-core:1.14.0
|    |    |    |    |    |    | …
```
=> GEOT-3942: version conflict on xerces is resolved

modules/library/main/src/main/java/org/geotools/data/DataUtilities.java, modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java, modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/tiff_rgba_extra/indexer.properties
Maps both org.locationtech.jts.geom and com.vividsolutions.jts.geom for backwards compatibility.
=> Additional type mappings for jts geometry types

modules/extension/xsd/xsd-kml/src/main/java/org/geotools/kml/v22/bindings/DataTypeBinding.java, modules/extension/xsd/xsd-kml/src/test/java/org/geotools/kml/v22/KMLEncodingTest.java
See [GEOT-6122](https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-6122) for detail. KML encoder could not export features with null attributes.
=> GEOT-6122: Fix for NPE in KML encoder

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/VirtualTable.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCVirtualTableOnlineTest.java
Backport of pull request:  https://github.com/geotools/geotools/pull/1919
Backport discussion:
https://sourceforge.net/p/geotools/mailman/message/36429244/
=> [GEOT-6034] Allow the usage of a place holder for the :where: clause created by GeoServer in virtual tables (backport 19.x)

modules/unsupported/ogr/ogr-jni/src/main/java/org/geotools/data/ogr/jni/JniOGRDataStoreFactory.java
See https://osgeo-org.atlassian.net/browse/GEOT-6131
This PR is based on https://github.com/geosolutions-it/imageio-ext/pull/170 (Since OGR does its own system call to load the libraries, I figured I'd fix it while I was at it)
=> [GEOT-6131] Support GDAL 2.3.0 JNI binding 'gdalalljni' for OGR

pom.xml
We have 4.6.11 in the osgeo maven repo. I assume there is no reason we can't upgrade to that both here and over in geoserver.
=> [GEOT-6142] Update netcdf to 4.6.11

modules/library/coverage/src/main/java/org/geotools/resources/coverage/FeatureUtilities.java, modules/library/coverage/src/test/java/org/geotools/resources/coverage/FeatureUtilitiesTest.java
This is in turn used by Crop, causing images with a negative origin to be cut "off by one" pixel from the intended position.
=> [GEOT-6150] FeatureUtilities.convertPolygonToPointArray fails to round correctly negative numbers

modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/GeometryEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/CurveEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GML3FeatureCollectionEncoderDelegate.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GenericGeometryEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GeometryCollectionEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/LineStringEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/LinearRingEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiLineStringEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiPointEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiPolygonEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/PointEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/PolygonEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/RingEncoder.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/MultiPointTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/MultiPolygonTest.java
Removing gml:id on geometry encoding for WFS 1.1.0 GML 3.1
=> Removing gml:id on geometry encoding, only for GML 3.1

modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/GeometryEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/CurveEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GML3FeatureCollectionEncoderDelegate.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GenericGeometryEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GeometryCollectionEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/LineStringEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/LinearRingEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiLineStringEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiPointEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiPolygonEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/PointEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/PolygonEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/RingEncoder.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/MultiPointTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/MultiPolygonTest.java
Remove gml:id on geometry encoding, GML 3.1 WFS 1.1.0 only. Backport 19.x
https://osgeo-org.atlassian.net/browse/GEOT-6160
=> [GEOT-6160] Remove gml:id on geometry encoding, GML 3.1 Backport 19.x

modules/extension/xsd/xsd-gml2/src/main/java/org/geotools/gml2/simple/GeometryEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/CurveEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GML3FeatureCollectionEncoderDelegate.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GenericGeometryEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/GeometryCollectionEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/LineStringEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/LinearRingEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiLineStringEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiPointEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/MultiPolygonEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/PointEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/PolygonEncoder.java, modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/simple/RingEncoder.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/MultiPointTest.java, modules/extension/xsd/xsd-gml3/src/test/java/org/geotools/gml3/simple/MultiPolygonTest.java
Removing gml:id on geometry encoding, GML 3.1 WFS 1.1.0 only. Backport 20.x
https://osgeo-org.atlassian.net/browse/GEOT-6160
=> [GEOT-6160] Removing gml:id on geometry encoding, GML 3.1 Backport 20.x

modules/library/main/src/test/java/org/geotools/util/CommonsConverterFactoryTest.java
The en_CA local only supports "a.m." and "p.m." while the format string assumes AM/PM
Fix to a known locale to avoid this issue.
This only appears to fail on Java 11, not Java 8
=> Fix locale for CommonsConverterFactoryTest

modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/remote/RemoteImageInputStreamSPI.java
FileImageInputStreamSpi is internal proprietary API and may be removed in a future release
=> Replace Sun FileImageInputStream usage with imageio-ext FileImageInputStreamExtImplSpi

modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java
org.w3c.dom.css.CSSRule is a jdk internal class, and was only included because of a javadoc import in the first place.
=> Remove reference to jdk internal CSSRule, and fixup javadoc errors

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/sdo/SDO.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/sdo/SDOCreateTest.java
Fix the inner curve multiple holes support on Polygon type for Oracle JDBC data source due to an arithmetic bug in inner rings iteration.
https://osgeo-org.atlassian.net/browse/GEOT-5438
=> [GEOT-5438] Curve support not complete for curved polygons with multiple

pom.xml
After trying to fix 100 tons of javadoc, noticed that the plugin now requires additionalJOption to be set to enable the doclint directive.
So just submitting the pom fix, since the javadoc is in an "interesting" state and quick fixes might hurt people's work.
=> add additionalJOption to enable doclint directive properly

modules/unsupported/pom.xml
remove swt from normal build since unsupported and gets warnings about swt jars accessing java.desktop for java 11
=> remove swt from normal build

modules/library/opengis/src/test/java/org/opengis/util/CodeListTest.java
This removes the check of capacity of arraylist, since it accesses an illegal field via reflection. 
My proposal here is to dump the test section, since there is no other way to get the capacity from the arraylist and the part doesn't seem relevant to the domain of the test (at least to me).
=> fix for CodeListTest illegal reflective access

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/sdo/SDO.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/sdo/SDOCreateTest.java
Fix the inner curve multiple holes support on Polygon type for Oracle JDBC data source due to an arithmetic bug in inner rings iteration.
https://osgeo-org.atlassian.net/browse/GEOT-5438
=> [GEOT-5438] Curve support not complete for curved polygons with multiple (backport 19.x)

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/sdo/SDO.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/sdo/SDOCreateTest.java
Fix the inner curve multiple holes support on Polygon type for Oracle JDBC data source due to an arithmetic bug in inner rings iteration.
https://osgeo-org.atlassian.net/browse/GEOT-5438
=> [GEOT-5438] Curve support not complete for curved polygons with multiple (backport 20.x)

modules/plugin/coverage-multidim/netcdf/src/main/java/org/geotools/coverage/io/netcdf/crs/NetCDFCRSAuthorityFactory.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFCRSTest.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFMosaicReaderTest.java, modules/plugin/coverage-multidim/netcdf/src/test/java/org/geotools/coverage/io/netcdf/NetCDFStationsTest.java
When running a full build the property file location of the custom NetCDF authority factory is looked up during the first test, that does not have the location of the custom property file set yet, which results in codes not being found quickly later, causing H2 postCreateTable to go though a full CRS scan in the EPSG database.
Since CRS factories are cached, there is no reason to keep the location of the property file there forever, just look it up every time needed instead (in a normal application, it will happen only a few times at startup).
=> Speed up NetCDF module build

modules/library/main/src/main/java/org/geotools/geometry/jts/ReferencedEnvelope3D.java, modules/library/main/src/test/java/org/geotools/geometry/jts/ReferencedEnvelope3DTest.java
Compiler complaint:
A binary expression where both operands are the same is usually incorrect;
the value of this expression is equivalent to `z > maxz`.
=> ReferencedEnvelope3D intersects: Fix z range check

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java
https://osgeo-org.atlassian.net/browse/GEOT-6178
This issue can only be reproduced with Oracle. The tests where already there and failing, note that some Oracle tests are still failing but its unrelated to this issue cause.
Before this PR:
After this PR:
=> [GEOT-6178] Invalid select bounds query generated for Oracle database

docs/user/tutorial/quickstart/artifacts/module-info.java, docs/user/tutorial/quickstart/artifacts/pom-jdk11.xml, docs/user/tutorial/quickstart/index.rst, docs/user/tutorial/quickstart/intellij.rst, docs/user/tutorial/quickstart/java11.rst, modules/library/metadata/src/main/java/org/geotools/util/factory/Hints.java
Basic Quickstart for running the Quickstart tutorial app on Java 11 under the module system. I've tested it out and it runs fine without the need for any additional runtime arguments.
Depends upon https://github.com/geotools/geotools/pull/2154 to run.
Also includes a fix to Hints that I discovered when running the tutorial - looks like this was missed during the refactor of ScreenMap
=> Java 11 quickstart

modules/unsupported/csv/src/main/java/org/geotools/data/csv/CSVFeatureWriter.java, modules/unsupported/csv/src/test/java/org/geotools/data/csv/CSVWriteTest.java
CSVWriter creates a temporary file when writing but never deletes it.
Also clean up the temp files in the tests in general.
=> [GEOT-6175] stop CSVWriter leaving temp files lying around

docs/user/build/maven/snapshots.rst, docs/user/build/maven/testing.rst, docs/user/extension/wms/wms.rst, docs/user/library/coverage/pyramid.rst, docs/user/library/cql/ecql.rst, docs/user/library/data/csv.rst, docs/user/library/data/datastore.rst, docs/user/library/main/collection.rst, docs/user/library/main/filter.rst, docs/user/library/main/repository.rst, docs/user/library/opengis/filter.rst, docs/user/library/referencing/extension.rst, docs/user/library/render/gtrenderer.rst, docs/user/library/render/map.rst, docs/user/library/xml/geometry.rst, docs/user/library/xml/internal/bindings.rst, docs/user/library/xml/internal/overview.rst, docs/user/library/xml/internal/tutorial.rst, docs/user/tutorial/datastore/strategy.rst, docs/user/tutorial/quickstart/eclipse.rst, docs/user/tutorial/quickstart/java11.rst, docs/user/unsupported/arcgis-rest.rst, docs/user/unsupported/process/process.rst, docs/user/unsupported/swt/rcp.rst, docs/user/welcome/geomajas.rst, docs/user/welcome/upgrade.rst
activites aquire archtype aslo availaible availble beacuse clas
conjuction controled defintion efficent extention heirarchy hierachy
indentical iwth occure seperate seperated slippy substract teh todays
unoffical
Found and fixed via codespell
=> Fix some spelling mistakes in docs/user.

docs/user/library/render/gtrenderer.rst
Fixes #2186 / c3e90a9a8fa29cfc2c5a166e6a012cff1b85c648
Found by @bradh
=> gtrenderer.rst: Revert "slippery" map back to "slippy" map

modules/library/main/src/main/java/org/geotools/filter/spatial/ReprojectingFilterVisitor.java, modules/library/main/src/test/java/org/geotools/filter/spatial/ReprojectingFilterVisitorTest.java
Backport of:
https://github.com/geotools/geotools/pull/2177
https://osgeo-org.atlassian.net/browse/GEOT-6182
=> [GEOT-6182] Add the possibility to specify the target CRS for the ReprojectingFilterVisitor (backport 20.x)

modules/library/main/src/main/java/org/geotools/data/DataUtilities.java, modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
DataUtilities.createType(String name, String spec)
was mapping full qualified MultiPoint class names
to MultiLineString instead of to MultiPoint.
=> Fix mapping of MultiLineString in DataUtilities

modules/library/main/src/main/java/org/geotools/filter/spatial/ReprojectingFilterVisitor.java, modules/library/main/src/test/java/org/geotools/filter/spatial/ReprojectingFilterVisitorTest.java
https://osgeo-org.atlassian.net/browse/GEOT-6200
Backport of: https://github.com/geotools/geotools/pull/2205
=> [GEOT-6200] Reproject fitler tries to reproject non geometry properties (backport 20.x)

modules/library/main/src/main/java/org/geotools/filter/spatial/ReprojectingFilterVisitor.java, modules/library/main/src/test/java/org/geotools/filter/spatial/ReprojectingFilterVisitorTest.java
https://osgeo-org.atlassian.net/browse/GEOT-6200
Backport of: https://github.com/geotools/geotools/pull/2205
=> [GEOT-6200] Reproject fitler tries to reproject non geometry properties (backport 19.x)

modules/unsupported/jdbc-ng/jdbc-hana/src/main/java/org/geotools/data/hana/HanaDialect.java, modules/unsupported/jdbc-ng/jdbc-hana/src/main/java/org/geotools/data/hana/HanaFilterToSQL.java, modules/unsupported/jdbc-ng/jdbc-hana/src/main/java/org/geotools/data/hana/HanaVersion.java, modules/unsupported/jdbc-ng/jdbc-hana/src/test/java/org/geotools/data/hana/HanaCompound3DTestSetup.java
Currently, the gt-jdbc-hana plugin supports HANA 2 only.
If used with a HANA 1 instance, some queries work, but many fail
because some functions are not available in HANA 1 yet.
With this change, gt-jdbc-hana supports the revisions of HANA 1 that
are still supported by SAP (120 and later). gt-jdbc-hana will reject
older revisions (< 120) immediately on establishing a connection.
=> [GEOT-6202] gt-jdbc-hana - Support for HANA 1

modules/library/xml/src/main/java/org/geotools/xml/filter/FilterTransformer.java, modules/library/xml/src/test/java/org/geotools/xml/filter/FilterTransformerTest.java
Prevented crash when SLD BBox function is encoded in XML.
=> [GEOT-6201] Fixed SLD encoding of BBox function

modules/library/main/src/main/java/org/geotools/filter/FilterTransformer.java, modules/library/main/src/test/java/org/geotools/filter/FilterTransformerTest.java
Prevented crash when SLD BBox function is encoded in XML.
=> [GEOT-6201] Fixed SLD encoding of BBox function, backport

modules/library/opengis/src/test/java/org/opengis/filter/identity/VersionTest.java
Found with refaster.  It wanted the following, but the extra parens do not appear to help anything.
`long decoded = Version.UNION_MASK & (encoded);`
=> opengis VersionTest.java: Remove unnecessary cast

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/NestedFilterToSQL.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java
Is known that OR queries are difficult to optimize for postgresql and are usually slow.
The fix for slow queries with OR involved is using UNION queries, so we need optimize certain complex subqueries. The slow appschema subquery involved is that generated by NestedFilterToSQL class so we need to change the use of OR clause in the root condition for UNION queries.
Since this performance issue affect postgresql, the fix should be isolated for this datasource only, and adding a system property for disable.
With UNION improvement enabled main binary operator on nested filter subquery will rebuild normal OR query like:
SELECT id, name FROM table WHERE name = "Morty" OR name = "Rick"
->
SELECT id, name FROM table WHERE name = "Morty" UNION SELECT id, name FROM table WHERE name = "Rick"
=> [GEOT-6209] App-schema Postgresql subquery: replace OR with UNION performance improvement

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/JoiningJDBCFeatureSource.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/NestedFilterToSQL.java
Is known that OR queries are difficult to optimize for postgresql and are usually slow.
The fix for slow queries with OR involved is using UNION queries, so we need optimize certain complex subqueries. The slow appschema subquery involved is that generated by NestedFilterToSQL class so we need to change the use of OR clause in the root condition for UNION queries.
Since this performance issue affect postgresql, the fix should be isolated for this datasource only, and adding a system property for disable.
With UNION improvement enabled main binary operator on nested filter subquery will rebuild normal OR query like:
SELECT id, name FROM table WHERE name = "Morty" OR name = "Rick"
->
SELECT id, name FROM table WHERE name = "Morty" UNION SELECT id, name FROM table WHERE name = "Rick" …
=> [GEOT-6209] App-schema Postgresql subquery: replace OR with UNION performance improvement (20.x backport)

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStoreFactory.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreFactoryTest.java
Fix for a NullPointerException issue on ShapefileDataStoreFactory and its canProcess method when a HTTP URL is provided (instead a Filesystem path).
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-6025
=> [GEOT-6025] NullPointerException fix on Shapefile http URL (20.x backport)

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStoreFactory.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreFactoryTest.java
Fix for a NullPointerException issue on ShapefileDataStoreFactory and its canProcess method when a HTTP URL is provided (instead a Filesystem path).
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-6025
=> [GEOT-6025] NullPointerException fix on Shapefile http URL

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/AppSchemaDataAccess.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/spi/CustomSourceDataStore.java, modules/extension/app-schema/app-schema/src/test/java/org/geotools/appschema/util/ComplexAttributeConverterFactoryTest.java, modules/library/main/src/main/java/org/geotools/data/util/ComplexAttributeConverterFactory.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectAllFunction.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/JsonSelectFunction.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexDataSource.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoNestedAttributeExpressionFactory.java
- https://osgeo-org.atlassian.net/browse/GEOT-6212
- https://osgeo-org.atlassian.net/browse/GEOT-6213
This pull requests fix several issue related with usage of MongoDB complex features nested properties in styling, more specifically:
- when using a filter in a rule, previously the filter was just ignored
- when using a complex feature property for labeling
Integration test for MongoDB, as usual, are implemented in GeoServer:  https://github.com/geoserver/geoserver/pull/3326
=> [GEOT-6212][GEOT-6213] Fix MongoDB complex feature nested properties usage in SLDs

pom.xml
Upgrade to imageio-ext 1.1.28:
https://github.com/geosolutions-it/imageio-ext/issues/181
=> ClientStreamAbortedException logged at SEVERE level, should be at lower level

modules/library/main/src/main/java/org/geotools/temporal/reference/DefaultCalendarEra.java
The cast in this equals method could throw a ClassCastException if a non-comparable type is passed in, which would violate the equals contract: it should just return false.
http://errorprone.info/bugpattern/EqualsUnsafeCast
=> DefaultCalendarEra.java equals(): Fix instanceof check before cast

modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/FESConfiguration.java, modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/MatchActionBinding.java, modules/extension/xsd/xsd-fes/src/test/java/org/geotools/filter/v2_0/bindings/TEqualsBindingTest.java
Encoding of the CQL "prop" = 'abc' as FES Filter results in invalid Filter:
```
<?xml version="1.0" encoding="UTF-8"?>
<fes:Filter xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:fes="http://www.opengis.net/fes/2.0"
xmlns:gml="http://www.opengis.net/gml/3.2">
<fes:PropertyIsEqualTo matchAction="ANY" matchCase="true">
<fes:ValueReference>prop</fes:ValueReference>
<fes:Literal>abc</fes:Literal>
</fes:PropertyIsEqualTo>
</fes:Filter>
```
Error is on 'matchAction="ANY"' attribute value, since it should be "Any".
This PR fixes [GEOT-6092], registering a match action binding to XSD FES 2.0 configuration, so now encoding result attribute is 'matchAction="Any"'.
https://osgeo-org.atlassian.net/browse/GEOT-6092
=> [GEOT-6092] Fix for Match action using uppercase names on encoding.

modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/FESConfiguration.java, modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/MatchActionBinding.java, modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/PropertyIsNullTypeBinding.java, modules/extension/xsd/xsd-fes/src/test/java/org/geotools/filter/v2_0/bindings/PropertyIsNullTypeBindingTest.java, modules/extension/xsd/xsd-fes/src/test/java/org/geotools/filter/v2_0/bindings/TEqualsBindingTest.java
Encoding a PropertyIsNull filter with FES 2.0 configuration, we are getting a bad output:
```java
FilterFactory2 ff = new FilterFactoryImpl();
Filter filter = ff.isNull(ff.property("prop"));
Configuration configuration = new org.geotools.filter.v2_0.FESConfiguration();
Encoder encoder = new Encoder(configuration);
encoder.setIndenting(true);
Document encodedDoc = encoder.encodeAsDOM(filter, FES.Filter);
```
Resulting document with error is:
```
<fes:Filter>
<fes:PropertyIsNull/>
</fes:Filter>
```
This PR fix PropertyIsNullTypeBinding class allowing to use the proper FES Qname on getting inner property name conditions:
```
<fes:Filter xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:gml="http://www.opengis.net/gml/3.2">
<fes:PropertyIsNull> …
```
=> [GEOT-6233] Fix for PropertyIsNull filter wrong FES 2.0 encoding

modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/FESConfiguration.java, modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/MatchActionBinding.java, modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/NotBinding.java, modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/PropertyIsNullTypeBinding.java, modules/extension/xsd/xsd-fes/src/test/java/org/geotools/filter/v2_0/bindings/NotBindingTest.java, modules/extension/xsd/xsd-fes/src/test/java/org/geotools/filter/v2_0/bindings/PropertyIsNullTypeBindingTest.java, modules/extension/xsd/xsd-fes/src/test/java/org/geotools/filter/v2_0/bindings/TEqualsBindingTest.java
ECQL encoding for "prop" NOT LIKE 'abc%' output is wrong:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<fes:Filter xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:fes="http://www.opengis.net/fes/2.0"
xmlns:gml="http://www.opengis.net/gml/3.2">
<fes:Not/>
</fes:Filter>
```
This PR fix Not encoding to:
```xml
<fes:Filter xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:gml="http://www.opengis.net/gml/3.2">
<fes:Not>
<fes:PropertyIsNull>
<fes:ValueReference>prop</fes:ValueReference>
</fes:PropertyIsNull>
</fes:Not>
</fes:Filter>
```
https://osgeo-org.atlassian.net/browse/GEOT-6234
=> [GEOT-6234] Fix for Encoding of Not operator in FES produces an invalid output

modules/unsupported/swing/src/main/java/org/geotools/swing/tool/PanTool.java
Without this change one has to create their own implementation of the `PanTool` class in order to extend `AbstractMapPane` class.
Credit to @MurrayMcDonald16
=> [GEOT-6235] (gt-swing) Remove unneeded JMapPane cast

modules/unsupported/swing/src/main/java/org/geotools/swing/AbstractMapPane.java
The JMapPane drawLayers() method implementation clears the images viewport rectangle and kicks off an asynchronous rendering task.  Calling "repaint()" immediately after this call pretty much guarantees one will get a "white flash" when the user stops  panning.  Furthermore the "onRenderingComplete()" method of AbstractMapPane  contains a call to "repaint()" already so this one is not required.
Credit to @MurrayMcDonald16
=> [GEOT-6236] (gt-swing) Remove white flash when pan/zooming map

modules/library/main/src/main/java/org/geotools/data/sort/SimpleFeatureIO.java, modules/library/main/src/test/java/org/geotools/data/sort/SimpleFeatureIOTest.java
Writing a String attribute with a big size (String bytes greater than 65535 bytes) on SimpleFeatureIO we got an exception:
```
java.io.UTFDataFormatException: encoded string too long: 71530 bytes
```
Seems like due to DataOutputStream.writeUTF String size limit, SimpleFeatureIO doesn't allow to write/read big String sizes on Simple Features attributes.
This PR adds support for big String sizes using a flag on FeatureType Attribute Descriptor (userMap):
```java
SimpleFeatureType type = typeBuilder.buildFeatureType();
type.getDescriptor(NAME_FIELD)
.getUserData()
.put(SimpleFeatureIO.BIG_STRING, Boolean.TRUE);
```
https://osgeo-org.atlassian.net/browse/GEOT-6237
=> [GEOT-6237] Support for big String (byte length > 65535) on SimpleFeatureIO (21.x backport)

modules/library/main/src/main/java/org/geotools/data/sort/SimpleFeatureIO.java, modules/library/main/src/test/java/org/geotools/data/sort/SimpleFeatureIOTest.java
Writing a String attribute with a big size (String bytes greater than 65535 bytes) on SimpleFeatureIO we got an exception:
```
java.io.UTFDataFormatException: encoded string too long: 71530 bytes
```
Seems like due to DataOutputStream.writeUTF String size limit, SimpleFeatureIO doesn't allow to write/read big String sizes on Simple Features attributes.
This PR adds support for big String sizes using a flag on FeatureType Attribute Descriptor (userMap):
```java
SimpleFeatureType type = typeBuilder.buildFeatureType();
type.getDescriptor(NAME_FIELD)
.getUserData()
.put(SimpleFeatureIO.BIG_STRING, Boolean.TRUE);
```
https://osgeo-org.atlassian.net/browse/GEOT-6237
=> [GEOT-6237] Support for big String (byte length > 65535) on SimpleFeatureIO

modules/library/main/src/main/java/org/geotools/data/sort/SimpleFeatureIO.java, modules/library/main/src/test/java/org/geotools/data/sort/SimpleFeatureIOTest.java
Writing a String attribute with a big size (String bytes greater than 65535 bytes) on SimpleFeatureIO we got an exception:
```
java.io.UTFDataFormatException: encoded string too long: 71530 bytes
```
Seems like due to DataOutputStream.writeUTF String size limit, SimpleFeatureIO doesn't allow to write/read big String sizes on Simple Features attributes.
This PR adds support for big String sizes using a flag on FeatureType Attribute Descriptor (userMap):
```java
SimpleFeatureType type = typeBuilder.buildFeatureType();
type.getDescriptor(NAME_FIELD)
.getUserData()
.put(SimpleFeatureIO.BIG_STRING, Boolean.TRUE);
```
https://osgeo-org.atlassian.net/browse/GEOT-6237
=> [GEOT-6237] Support for big String (byte length > 65535) on SimpleFeatureIO (20.x backport)

modules/library/main/src/main/java/org/geotools/data/sort/SimpleFeatureIO.java, modules/library/main/src/test/java/org/geotools/data/sort/SimpleFeatureIOTest.java
Writing a String attribute with a big size (String bytes greater than 65535 bytes) on SimpleFeatureIO we got an exception:
```
java.io.UTFDataFormatException: encoded string too long: 71530 bytes
```
Seems like due to DataOutputStream.writeUTF String size limit, SimpleFeatureIO doesn't allow to write/read big String sizes on Simple Features attributes.
This PR adds support for big String sizes using a flag on FeatureType Attribute Descriptor (userMap):
```java
SimpleFeatureType type = typeBuilder.buildFeatureType();
type.getDescriptor(NAME_FIELD)
.getUserData()
.put(SimpleFeatureIO.BIG_STRING, Boolean.TRUE);
```
https://osgeo-org.atlassian.net/browse/GEOT-6237
=> [GEOT-6237] Support for big String (byte length > 65535) on SimpleFeatureIO (19.x backport)

modules/library/referencing/src/main/java/org/geotools/measure/AngleFormat.java
A version of ErrorProne complains if all test cases are not covered, even if it is obvious to the reader that they are.  I think the idea being that if someone were to add another ROUND_*, you would want to check all the places where it might not be covered.
=> Add ROUND_HALF_EVEN case to AngleFormat.doRounding as an AssertionError

modules/unsupported/pom.xml, modules/unsupported/postgis-raster/README.md, modules/unsupported/postgis-raster/pom.xml, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/Mosaic.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/PGRasterConfig.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/PGRasterFactory.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/PGRasterFormat.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/PGRasterReader.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/RasterColumn.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/RasterOverview.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/ReadRequest.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/SQL.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/Tile.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/TileData.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/TileDecoder.java, modules/unsupported/postgis-raster/src/main/java/org/geotools/gce/pgraster/TimeColumn.java, modules/unsupported/postgis-raster/src/main/resources/META-INF/services/org.geotools.coverage.grid.io.GridFormatFactorySpi, modules/unsupported/postgis-raster/src/test/java/org/geotools/gce/pgraster/PGRasterTest.java
- A standalone reader, no dependencies on the core imagemosaic or imagemosaic-jdbc modules
- Supports time dimension, but not elevation
- Supports jndi connections or a direct connection pool, same as jdbc datastores
- Not a structured coverage reader in that it's not possible to read multiple coverages with one reader
=> Initial implementation of a coverage reader for PostGIS rasters.

modules/plugin/coverage-multidim/netcdf/pom.xml
net-cdf was depending on gt-jdbc twice (once explicitly and once as a transitive dependency)
=> Fix maven warning dependency must be unique warning

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleFeatureSourceOnlineTest.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleTestSetup.java
https://osgeo-org.atlassian.net/browse/GEOT-6038
added support for BINARY_DOUBLE and BINARY_FLOAT
=> [GEOT-6038] Oracle JDBC dialect doesn't support binary_double

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleFeatureSourceOnlineTest.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleTestSetup.java
=> [GEOT-6038] Oracle JDBC dialect doesn't support binary_double - 21.x

modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleDialect.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleFeatureSourceOnlineTest.java, modules/plugin/jdbc/jdbc-oracle/src/test/java/org/geotools/data/oracle/OracleTestSetup.java
=> [GEOT-6038] Oracle JDBC dialect doesn't support binary_double - 20.x

pom.xml
`geotoolsBaseDir` can contain spaces and so should be quoted. Without quotes, building in a path with spaces fails because surefire JVM invocation fails.
=> Quote highest-basedir property to fix build in a path with spaces

modules/unsupported/swing/src/main/java/org/geotools/swing/DefaultRenderingExecutor.java
The “currentTask.remove(info)” line needs to be moved up BEFORE the check of the countdown latch.
=> [GEOT-6267] Memory leak in DefaultRenderingExecutor

docs/developer/conventions/code/style.rst
Add modified google-java-format version jar download with 4 spaces indent on developer documentation.
=> Add to developer manual a modified google-java-format version plugin option.

modules/library/main/src/test/java/org/geotools/data/util/SubProgressListenerTest.java
There are some deprecated useage of  junit.framework.*
Fixed all cases of `junit.framework.Assert.assertEquals(float, float)`
See https://junit.org/junit4/javadoc/latest/org/junit/Assert.html#assertArrayEquals(float[],%20float[],%20float)
=> Improved JUnit assertions on floats

.gitignore, modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCFeatureReader.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCFeatureWriterOnlineTest.java, modules/plugin/jdbc/jdbc-mysql/src/test/java/org/geotools/data/mysql/MySQLFeatureWriterOnlineTest.java
@aaime
Here my next try. I switched off code-formatting etc. Changes now reduce to two lines in one file (plus two new unit-test files). Following contribution guidelines, "Talk first policy" does not apply to "easy bugfix with test".
See Jira GEOT-6264 for the Version of JDBCFeatureWriterOnlineTest.java which demonstrates the bug. The JDBC FeatureWriter implementation returns features whose attributes are fine in case obtained via getAttribute(int) but which are null in case obtained via getAttributes().
Please note also: I added .gradle to .gitignore.
=> [GEOT-6264] JDBC FeatureWriter-implementation returns null values in getAttributes()

modules/library/render/src/main/java/org/geotools/map/MapViewport.java, modules/library/render/src/test/java/org/geotools/map/MapViewportTest.java
As discussed in [GEOT-6269](https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-6269) this enhancement allows a resizing MapPane to keep it's bounds rather than its bounds. The behaviour defaults to the current practice of maintaining the scale and adjusting the bounds.
A call to `setFixedBoundsOnResize` with True will maintain the bounds and adjust the scale.
=> [GEOT-6269] Allow  MapViewports to retain scale or bounds on resize

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/IndexManager.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStore.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureSource.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureStore.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/fid/IndexedFidWriter.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/fid/FidQueryTest.java
See [GEOT-5830](https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-5830) for an explanation of the issue.
=> [GEOT-5830] Fids can become corrupted in ShapeFileReader when deletion occurs

modules/library/xml/src/main/java/org/geotools/gml/GMLFilterFeature.java, modules/library/xml/src/main/java/org/geotools/gml/SubHandlerPolygon.java, modules/library/xml/src/test/java/org/geotools/gml/GMLFilterFeatureTest.java
Easy bugfix with new test, This time clean, without sourcecode-formatting.
- GMLFilterFeature used to remove certain whitespace characters in feature attributes
- SubHandlerPolygon used to reverse CCW shell- and CW hole-LineStrings of Polygons
Both ways to tamper with input-data are demonstrated by the new test which will fail as long as the bugs are not fixed. The test creates two features, generates GML, parses the GML and compares attributes of the features.
=> [GEOT-6263] GMLFilterFeature/SubHandlerPolygon tamper with input data

docs/user/library/jdbc/hana.rst, modules/unsupported/jdbc-ng/jdbc-hana/src/main/java/org/geotools/data/hana/HanaConnectionParameters.java, modules/unsupported/jdbc-ng/jdbc-hana/src/main/java/org/geotools/data/hana/HanaDataStoreFactory.java, modules/unsupported/jdbc-ng/jdbc-hana/src/main/java/org/geotools/data/hana/metadata/CommandLineArguments.java, modules/unsupported/jdbc-ng/jdbc-hana/src/test/java/org/geotools/data/hana/HanaJNDIDataSourceOnlineTest.java, modules/unsupported/jdbc-ng/jdbc-hana/src/test/java/org/geotools/data/hana/HanaTestSetup.java, modules/unsupported/jdbc-ng/jdbc-hana/src/test/java/org/geotools/data/hana/metadata/CommandLineArgumentsTest.java
HANA connection parameters have been extended by port number and a
switch to enable encryption to support connections to HANA cloud
instances.
=> gt-jdbc-hana: Support connections to cloud instances

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/DescribeFeatureTypeResponse.java
No test as I can't find any evidence we have ever tested DescribeFeatureTypeResponse in GeoTools, GeoServer still works after this change.
=> [GEOT-6284] make sure tempfile prefix is longer than 3 chars

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/NestedFilterToSQL.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
Currently app-schema plugin detect two posible attributes with same xpath and delegate filter execution to JVM runtime. This fix delegates filter execution to database using all available join-fields.
https://osgeo-org.atlassian.net/browse/GEOT-6179
=> [GEOT-6179] Delegate filter execution matching multiple same-xpath feature chained attribute names to database

modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/AbstractGridCoverage2DReader.java, modules/library/coverage/src/test/java/org/geotools/coverage/grid/GridCoverageTest.java, modules/library/coverage/src/test/java/org/geotools/coverage/grid/MockAbstractGridCoverage2DReader.java
Resuming @imranrajjad work on the topic, but this time with a GeoServer fix that allows committing it.
See also: https://github.com/geoserver/geoserver/pull/3455
=> [GEOT-6088] - Subsampling enabled irrespective of OverViews for grids

modules/unsupported/swing/src/main/java/org/geotools/swing/locale/PropertiesFileFinder.java
see JIRA GEOT-6290: https://osgeo-org.atlassian.net/browse/GEOT-6290
The idea is to accept to load resources from bundle:// urls, which occur when geotools are started from an osgi-packaged application.
Uses the standard methods to solved this situation. 
Uses reflection is order not to add any mandatoru dependency to eclipse nor osgi frameworks. 
Tested under Linux and Windows; is anyway not platform dependent. I don't plan to submit any test case, as building unit tests in an osgi setting would be extremely difficult.
=> swing: find resources when started from an OSGI bundle (GEOT-6290)

modules/library/main/src/main/java/org/geotools/data/DataUtilities.java, modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
DataUtilities.createType(String name, String spec)
was mapping full qualified MultiPoint class names
to MultiLineString instead of to MultiPoint.
This is a forward port of #2200 that was not applied to master at its time
=> Fix mapping of MultiLineString in DataUtilities (21.x)

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDumper.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDumperTest.java
Reverts geotools/geotools#2261 as it breaks the GeoServer build. Sorry about that, did not notice during review.
Ah, @NielsCharlier , in case you're interested or can share information, I've also started a thread on the deve list to see if we can add a build check for this (e.g., to run a geoserver build off the geotools changes and get a firm result before merging a GeoTools PR)
=> Revert "GEOT-6238 shapefile dump with custom filename"

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
Executing a WFS query with nested filter and multiple sortBy expressions throws an malformed SQL exception on App-schema and Postgresql.
This PR fix SQL nested filter building on multiple sortBy expressions scenario, also adds some method delegating refactoring due to a too big method doing all.
21.x backport.
https://osgeo-org.atlassian.net/browse/GEOT-6252
=> [GEOT-6252] App-schema multiple sortBy support on SQL (21.x backport)

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java
Executing a WFS query with nested filter and multiple sortBy expressions throws an malformed SQL exception on App-schema and Postgresql.
This PR fix SQL nested filter building on multiple sortBy expressions scenario, also adds some method delegating refactoring due to a too big method doing all.
https://osgeo-org.atlassian.net/browse/GEOT-6252
=> [GEOT-6252] App-schema multiple sortBy support on SQL

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/IndexIdIterator.java
This PR has a fix for: App-schema indexes makes query without correct maxFeatures number on "rows" parameter to Apache Solr.
Now appschema-indexes builds its solr query with the correct "rows" value.
https://osgeo-org.atlassian.net/browse/GEOT-6274
=> [GEOT-6274] Fix app-schema indexes max rows parameter on solr query (20.x backport)

modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrFeatureReader.java
Adds complete request URL sent to Solr with its parameters including now Host and action path, for copy and use it on a browser easily.
Example:
```
http://localhost:8983/solr/stations/select?omitHeader=true&fl=id&q=*:*&rows=1000000&sort=id+asc&fq=common_name:/.{1,1}*/+
```
=> Make Solr store log its complete http request URL to Solr core

modules/library/metadata/src/main/java/org/geotools/util/PreventLocalEntityResolver.java, modules/library/metadata/src/test/java/org/geotools/util/PreventLocalEntityResolverTest.java
This pull request changes how the baseURI is used to determine whether or not to allow an entity defined in an external DTD.
=> Improved entity validation in external DTDs.

pom.xml
I was able to upgrade sqlite from 3.23.1 to 3.27.2.1 and successfully do a full build of geotools. 
I was uncertain how to do a full build of geowebcache and geoserver using this build to confirm no regressions or where to start on the interactive tests. 
Upgrading to the latest version provides access to performance upgrades and a plethora of other important fixes.
=> Upgraded sqlite-jdbc from 3.23.1 -> 3.27.2.1

modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrFeatureReader.java
Adds complete request URL sent to Solr with its parameters including now Host and action path, for copy and use it on a browser easily.
Example:
```
http://localhost:8983/solr/stations/select?omitHeader=true&fl=id&q=*:*&rows=1000000&sort=id+asc&fq=common_name:/.{1,1}*/+
```
=> Make Solr store log its complete http request URL to Solr core (21.x backport)

modules/unsupported/solr/src/main/java/org/geotools/data/solr/SolrFeatureReader.java
Adds complete request URL sent to Solr with its parameters including now Host and action path, for copy and use it on a browser easily.
Example:
```
http://localhost:8983/solr/stations/select?omitHeader=true&fl=id&q=*:*&rows=1000000&sort=id+asc&fq=common_name:/.{1,1}*/+
```
=> Make Solr store log its complete http request URL to Solr core (20.x backport)

pom.xml
Back port to upgrade sqlite-jdbc from 3.23.1 -> 3.27.2.1
=> [GEOT-6304] Upgrade xerial-SQLite version to 3.27.2.1 (backport to 21.x)

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/NestedFilterToSQL.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
This PR fixes some Geoserver App-Schema online tests failing after initial commit, due to:
- Parenthesis checking on generated SQL.
- Client properties chaining unsupported corner cases.
Tested on Geoserver App-Schema tests module PR:
https://github.com/geoserver/geoserver/pull/3239
https://osgeo-org.atlassian.net/browse/GEOT-6179
=> [GEOT-6179] Fix. Check for client properties on feature chaining.

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStoreFactory.java, modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2DataStoreFactoryTest.java
backport for GEOT-3825 Fetch size defaults to 0 in JDBCDataStore
=> 20.x  GEOT-3825 Fetch size defaults to 0 in JDBCDataStore

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStoreFactory.java, modules/plugin/jdbc/jdbc-h2/src/test/java/org/geotools/data/h2/H2DataStoreFactoryTest.java
21.x backport for GEOT-3825 Fetch size defaults to 0 in JDBCDataStore
=> 21.x GEOT-3825 Fetch size defaults to 0 in JDBCDataStore

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/NestedFilterToSQL.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java
Currently app-schema plugin detect two posible attributes with same xpath and delegate filter execution to JVM runtime. This fix delegates filter execution to database using all available join-fields.
https://osgeo-org.atlassian.net/browse/GEOT-6179
=> [GEOT-6179] Delegate filter execution matching multiple same-xpath feature chained attribute names to database (21.x backport)

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/ComplexFilterSplitter.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/jdbc/NestedFilterToSQL.java
Currently app-schema plugin detect two posible attributes with same xpath and delegate filter execution to JVM runtime. This fix delegates filter execution to database using all available join-fields.
https://osgeo-org.atlassian.net/browse/GEOT-6179
=> [GEOT-6179] Delegate filter execution matching multiple same-xpath feature chained attribute names to database (20.x backport)

modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
This PR fixes IsNull filter processing on MongoDB datastore, executing null attribute (or nonexistent attribute) on database search engine using the Null equality filter.
See:
https://docs.mongodb.com/manual/tutorial/query-for-null-fields/
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6316
=> [GEOT-6316] Fix MongoDB store isNull filter processing.

docs/user/library/data/mongodb.rst, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMapping.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMappingFactory.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStoreFactory.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoInferredMapper.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoSchemaInitParams.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
This PR enhances MongoDB schema generation with new initialization parameters for using multiple JSON objects from collection, and adds methods for cleaning already persisted schemas so they can be regenerated with new parameters on demand.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6317
=> [GEOT-6317] Enhance mongodb schema generation.

docs/user/library/data/mongodb.rst, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMapping.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMappingFactory.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStoreFactory.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoInferredMapper.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoSchemaInitParams.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
This PR enhances MongoDB schema generation with new initialization parameters for using multiple JSON objects from collection, and adds methods for cleaning already persisted schemas so they can be regenerated with new parameters on demand.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6317
=> (Backport 20.x) [GEOT-6317] Enhance mongodb schema generation.

docs/user/library/data/mongodb.rst, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMapping.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/FeatureTypeMappingFactory.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStoreFactory.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoFeatureSource.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoInferredMapper.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoSchemaInitParams.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
This PR enhances MongoDB schema generation with new initialization parameters for using multiple JSON objects from collection, and adds methods for cleaning already persisted schemas so they can be regenerated with new parameters on demand.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6317
=> (Backport 21.x) [GEOT-6317] Enhance mongodb schema generation.

modules/plugin/coverage-multidim/netcdf/pom.xml
https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/reference/httpservices.html indicated this was replaced with httpcomponent 4.x. inside the UCAR libraries as of 4.3 
The dependency:tree results are consistent with that.
=> GEOT-5859: Remove httpclient dependency.

modules/unsupported/s3-geotiff/src/main/java/org/geotools/s3/S3ImageInputStreamImpl.java
Small community module fix.
A URI may contain encoded characters (such as %20) but the S3 api want the "real" characters
=> S3-geotiff: decode URL escaped characters

modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffReader.java, modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffReaderTest.java
--bot backport failed, so  manual backport
=> Backport to 20.x [GEOT-6327] tolerate geotiff_coverage as the coverageName

modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoInferredMapper.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
This PR allows mongoDB store to use -1 value in "max_objs_schema" parameter for using all collection items in schema build process.  Also improves some schema build process logging.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6328
=> [GEOT-6328] Allow MongoDB data store schema builder to use all DB collection items

modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
This PR allows MongoDB schema inferrer to use all inner arrays items.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6329
=> [GEOT-6329] MongoDB schema inferrer only uses first item on inner arrays

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/XSUtils.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSDateBinding.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSDateTimeBinding.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/DateConversionTimezoneTest.java
This PR adds Local DateTime Handling system property support for XS DateTime data type, in the same way it is already supported on XS Date.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6330
=> [GEOT-6330] XS DateTime encoder doesn't support Local DateTime Handling

modules/extension/tile-client/pom.xml, modules/extension/wmts/pom.xml
This should prevent `gt-tile-client` from dragging in `gt-epsg-hsql`, see [GEOT-6341](https://osgeo-org.atlassian.net/browse/GEOT-6341)
=> [GEOT-6341] demote gt-epsg-hsql in gt-tile-client to test scope

modules/extension/tile-client/pom.xml, modules/extension/wmts/pom.xml
This should prevent `gt-tile-client` from dragging in `gt-epsg-hsql`, see [GEOT-6341](https://osgeo-org.atlassian.net/browse/GEOT-6341)
Backports #2487
=> [Backport 21.x] [GEOT-6341] demote gt-epsg-hsql in gt-tile-client to test scope

modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoInferredMapper.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
This PR allows mongoDB store to use -1 value in "max_objs_schema" parameter for using all collection items in schema build process. Also improves some schema build process logging.
21.x backport.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6328
=> [GEOT-6328] Allow MongoDB data store schema builder to user all DB collection items (21.x backport)

modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/complex/MongoComplexUtilities.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/geojson/GeoJSONMongoTestSetup.java
This PR allows MongoDB schema inferrer to use all inner arrays items.
21.x backport.
Requires:
https://github.com/geotools/geotools/pull/2485
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6329
=> [GEOT-6329] MongoDB schema inferrer only uses first item on inner arrays (21.x backport)

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/XSUtils.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSDateBinding.java, modules/extension/xsd/xsd-core/src/main/java/org/geotools/xs/bindings/XSDateTimeBinding.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/DateConversionTimezoneTest.java
This PR adds Local DateTime Handling system property support for XS DateTime data type, in the same way it is already supported on XS Date.
20.x backport.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6330
=> [Backport 20.x] [GEOT-6330] XS DateTime encoder doesn't support Local DateTime Handling

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStoreFactory.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/GeometryColumnEncoder.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisNGDataStoreFactory.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/TWKBAttributeIO.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/WKBAttributeIO.java
This also involves proper delegation setup for the prepared statement dialect, which was faulty and did not end up enabling TWKB. (the prepared statement path is the only one that can enjoy true binary transfer, as that kicks in only after a statement got prepared).
=> [GEOT-6222] Avoid unnecessary base64 encoding when fetching geometry from PostGIS

modules/extension/xsd/xsd-kml/src/main/java/org/geotools/kml/v22/KMLConfiguration.java, modules/extension/xsd/xsd-kml/src/test/java/org/geotools/kml/v22/RegionTypeBindingTest.java
Add explicit binding for `LatLonAltBoxType` in KML 2.2
`Configuration`. Otherwise parsing a `Region` with a
`LatLonAltBox` child element throws a `ClassCastException`
because it wasn't parsed to a JTS `Envelope`.
Reason being that in KML 2.1 `LatLonAltBoxType` is a subtype
of `LatLonBoxType`, but in KML 2.2 it is not, both being
derived from `AbstractLatLonBoxType` instead.
=> [GEOT-6358] xsd-kml: Fix LatLonAltBox parsing for KML 2.2

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java, modules/library/jdbc/src/main/java/org/geotools/jdbc/SQLDialect.java, modules/library/jdbc/src/test/java/org/geotools/data/jdbc/FilterToSQLTest.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCEscapingOnlineTest.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCEscapingTestSetup.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaEscapingOnlineTest.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaEscapingTestSetup.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaTestUtil.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisEscapingOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisEscapingTestSetup.java, modules/plugin/jdbc/jdbc-sqlserver/src/main/java/org/geotools/data/sqlserver/SQLServerDialect.java
SQL identifiers (column names, table names, schema names) are usually
quoted using double quotes. Furthermore, identifiers can contain double
quotes themselves. These are usually escaped using two double quotes,
e.g. a"b is quoted as "a""b".
Identifiers with double quotes are not properly escaped by
FilterToSQL#escapeName, e.g. a"b would become "a"b" resulting in an
invalid SQL statement.
Additionally, there are dozens of locations in the JDBC-plugins
themselves where the identifier quoting is done manually with patterns
like
String sql = "ALTER TABLE \"" + schemaName + "\".\"" + tableName + "\""...
This change fixes the FilterToSQL#escapeName method and adapts locations
where the escaping was done manually.
=> [GEOT-6352] FilterToSQL#escapeName does not escape escape character

docs/user/library/data/mongodb.rst, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStoreFactory.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java
MongoDB store does not register OR operation into filter capabilities and due to this OR operations are not executes on native search engine leading to wrong queries results with or involved.
This seems related to older MongoDB versions unable to mix $or operations with spatial indexes, but it is already supported since 2.6.0 version.
This PR add native OR support by default and adds a store parameter for deactivate it if needed for older MongoDB versions.
See:
https://github.com/geotools/geotools/blob/master/modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java#L214-L218
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6345
=> [GEOT-6345] MongoDB OR filters are not executed on native search engine

docs/user/library/metadata/geotools.rst, modules/library/metadata/src/main/java/org/geotools/util/factory/GeoTools.java, modules/library/metadata/src/main/java/org/geotools/util/factory/Hints.java, modules/library/xml/src/main/java/org/geotools/gml/producer/FeatureTransformer.java, modules/library/xml/src/test/java/org/geotools/gml/producer/FeatureTransformerTest.java
This PR enables temporal data formatting on GML 2 encoder, using same strategy as GML 3.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6336
=> [GEOT-6336] GML 2 temporal data is not being format like GML 3 encoding.

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Parser.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/ParserTest.java, modules/extension/xsd/xsd-core/src/test/resources/org/geotools/xsd/entityExpansionLimit.xml
Currently GeoTools XML parser (org.geotools.xsd.Parser) doesn't allow to set a custom entity expansion limit on the embedded SAX Parser. Since the default can be too big for some use cases (64000) it could be useful to can configure the limit using the Geotools Parser API, so it can be easily used, as example, by Geoserver WFS and more.
See Entity Expansion limit on documentation:
https://docs.oracle.com/javase/tutorial/jaxp/limits/using.html
This PR adds a entityExpansionLimit attribute to Geotools XML Parser.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6318
=> [Backport 21.x][GEOT-6318] Allow setting entity expansion limit on GeoTools XML parser.

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Parser.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/ParserTest.java, modules/extension/xsd/xsd-core/src/test/resources/org/geotools/xsd/entityExpansionLimit.xml
Currently GeoTools XML parser (org.geotools.xsd.Parser) doesn't allow to set a custom entity expansion limit on the embedded SAX Parser. Since the default can be too big for some use cases (64000) it could be useful to can configure the limit using the Geotools Parser API, so it can be easily used, as example, by Geoserver WFS and more.
See Entity Expansion limit on documentation:
https://docs.oracle.com/javase/tutorial/jaxp/limits/using.html
This PR adds a entityExpansionLimit attribute to Geotools XML Parser.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6318
=> [Backport 22.x][GEOT-6318] Allow setting entity expansion limit on GeoTools XML parser.

modules/library/xml/src/main/java/org/geotools/xml/resolver/SchemaCache.java, modules/library/xml/src/test/java/org/geotools/xml/resolver/SchemaCacheTest.java
This PR fixes the Schema cache autoconfiguration bug relaxing the directory schema checking in a simpler approach, ensuring mainly the workspaces directory and its default.xml file for detecting the geoserver root folder and creating the app-schema-cache folder.
Also a warning logging line was added on not found valid directory event.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-5729
=> [Backport 21.x][GEOT-5729] Schema cache autoconfiguration fails for empty GeoServer data directory

modules/library/xml/src/main/java/org/geotools/xml/resolver/SchemaCache.java, modules/library/xml/src/test/java/org/geotools/xml/resolver/SchemaCacheTest.java
This PR fixes the Schema cache autoconfiguration bug relaxing the directory schema checking in a simpler approach, ensuring mainly the workspaces directory and its default.xml file for detecting the geoserver root folder and creating the app-schema-cache folder.
Also a warning logging line was added on not found valid directory event.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-5729
=> [Backport 22.x][GEOT-5729] Schema cache autoconfiguration fails for empty GeoServer data directory

docs/user/library/metadata/geotools.rst, modules/library/metadata/src/main/java/org/geotools/util/factory/GeoTools.java, modules/library/metadata/src/main/java/org/geotools/util/factory/Hints.java, modules/library/xml/src/main/java/org/geotools/gml/producer/FeatureTransformer.java, modules/library/xml/src/test/java/org/geotools/gml/producer/FeatureTransformerTest.java
This PR enables temporal data formatting on GML 2 encoder, using same strategy as GML 3.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6336
=> [Backport 21.x][GEOT-6336] GML 2 temporal data is not being format like GML 3 encoding.

docs/user/library/metadata/geotools.rst, modules/library/metadata/src/main/java/org/geotools/util/factory/GeoTools.java, modules/library/metadata/src/main/java/org/geotools/util/factory/Hints.java, modules/library/xml/src/main/java/org/geotools/gml/producer/FeatureTransformer.java, modules/library/xml/src/test/java/org/geotools/gml/producer/FeatureTransformerTest.java
This PR enables temporal data formatting on GML 2 encoder, using same strategy as GML 3.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6336
=> [Backport 22.x][GEOT-6336] GML 2 temporal data is not being format like GML 3 encoding.

docs/user/library/data/mongodb.rst, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStoreFactory.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java
MongoDB store does not register OR operation into filter capabilities and due to this OR operations are not executes on native search engine leading to wrong queries results with or involved.
This seems related to older MongoDB versions unable to mix $or operations with spatial indexes, but it is already supported since 2.6.0 version.
This PR add native OR support by default and adds a store parameter for deactivate it if needed for older MongoDB versions.
See:
https://github.com/geotools/geotools/blob/master/modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java#L214-L218
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6345
=> [Backport 21.x][GEOT-6345] MongoDB OR filters are not executed on native search engine

docs/user/library/data/mongodb.rst, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java, modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStoreFactory.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoFeatureSourceTest.java
MongoDB store does not register OR operation into filter capabilities and due to this OR operations are not executes on native search engine leading to wrong queries results with or involved.
This seems related to older MongoDB versions unable to mix $or operations with spatial indexes, but it is already supported since 2.6.0 version.
This PR add native OR support by default and adds a store parameter for deactivate it if needed for older MongoDB versions.
See:
https://github.com/geotools/geotools/blob/master/modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoDataStore.java#L214-L218
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6345
=> [Backport 22.x][GEOT-6345] MongoDB OR filters are not executed on native search engine

modules/library/xml/src/main/java/org/geotools/xml/resolver/SchemaCache.java, modules/library/xml/src/test/java/org/geotools/xml/resolver/SchemaCacheTest.java
This PR fixes the Schema cache autoconfiguration bug relaxing the directory schema checking in a simpler approach, ensuring mainly the workspaces directory and its default.xml file for detecting the geoserver root folder and creating the app-schema-cache folder.
Also a warning logging line was added on not found valid directory event.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-5729
=> [GEOT-5729] Schema cache autoconfiguration fails for empty GeoServer data directory

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Parser.java, modules/extension/xsd/xsd-core/src/test/java/org/geotools/xsd/ParserTest.java, modules/extension/xsd/xsd-core/src/test/resources/org/geotools/xsd/entityExpansionLimit.xml
Currently GeoTools XML parser (org.geotools.xsd.Parser) doesn't allow to set a custom entity expansion limit on the embedded SAX Parser. Since the default can be too big for some use cases (64000) it could be useful to can configure the limit using the Geotools Parser API, so it can be easily used, as example, by Geoserver WFS and more.
See Entity Expansion limit on documentation:
https://docs.oracle.com/javase/tutorial/jaxp/limits/using.html
This PR adds a entityExpansionLimit attribute to Geotools XML Parser.
Issue:
https://osgeo-org.atlassian.net/browse/GEOT-6318
=> [GEOT-6318] Allow setting entity expansion limit on GeoTools XML parser.

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Parser.java
This PR adds exception handling for corner cases having an outdated XercesImpl version on classpath not supporting entity expansion limit property.
=> [GEOT-6318] Exception handling on SAX parser entity expansion limit.

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Parser.java
This PR adds exception handling for corner cases having an outdated XercesImpl version on classpath not supporting entity expansion limit property.
=> [Backport 22.x][GEOT-6318] Exception handling on SAX parser entity expansion limit.

modules/extension/xsd/xsd-core/src/main/java/org/geotools/xsd/Parser.java
This PR adds exception handling for corner cases having an outdated XercesImpl version on classpath not supporting entity expansion limit property.
=> [Backport 21.x][GEOT-6318] Exception handling on SAX parser entity expansion limit.

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/MultithreadedHttpClient.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/WFSDataStoreFactory.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/impl/WFSDataAccessFactory.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/WFSConfig.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/internal/WFSConfigTest.java
This enables you to configure the max connection pool size by configuring
the `WFSDataStoreFactory:MAX_CONNECTION_POOL_SIZE` parameter. The
default values were far too small to scale effectively.
=> [GEOT-6350] Enable configuration of the max connection pool size

modules/unsupported/solr/src/main/java/org/geotools/data/solr/ExpressionToSolr.java, modules/unsupported/solr/src/test/java/org/geotools/data/solr/ExpressionToSolrTest.java
This PR adds support for Envelope BBox filter on Solr datastore.
https://osgeo-org.atlassian.net/browse/GEOT-6374
=> [GEOT-6374] Wrong expression encoding for BBOX filters on Solr datastore

modules/unsupported/solr/src/test/java/org/geotools/data/solr/SolrFeatureSourceTest.java, modules/unsupported/solr/src/test/java/org/geotools/data/solr/SolrGeometryTest.java
This PR fixes some Solr online tests failing due to outdated checks on their data setup.
https://osgeo-org.atlassian.net/browse/GEOT-6376
=> [GEOT-6376] Solr datastore online tests failing due to updated data setup

modules/unsupported/solr/src/main/java/org/geotools/data/solr/ExpressionToSolr.java, modules/unsupported/solr/src/test/java/org/geotools/data/solr/ExpressionToSolrTest.java
This PR adds support for Envelope BBox filter on Solr datastore.
https://osgeo-org.atlassian.net/browse/GEOT-6374
=> [22.x backport][GEOT-6374] Add support for Envelope BBox filter on Solr datastore

modules/unsupported/solr/src/main/java/org/geotools/data/solr/ExpressionToSolr.java, modules/unsupported/solr/src/test/java/org/geotools/data/solr/ExpressionToSolrTest.java
This PR adds support for Envelope BBox filter on Solr datastore.
https://osgeo-org.atlassian.net/browse/GEOT-6374
=> [21.x backport][GEOT-6374] Add support for Envelope BBox filter on Solr datastore

modules/library/jdbc/src/main/java/org/geotools/jdbc/JDBCDataStore.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISDialect.java
Actual Reported Issue
https://osgeo-org.atlassian.net/browse/GEOS-7533?oldIssueView=true
Geotools JIRA
https://osgeo-org.atlassian.net/browse/GEOT-6347
I propose to put commonly used sqltypes inside overrides map and have the behavior inside JDBCDataStore controllable through some param, that if all sqlTypeName have been found through dialect, it should not bother the driver for querying for datatypes inside underlying Database.
=> [GEOT-6347] Layer creation using REST API very slow in a PostGIS database with thousands of tables

modules/unsupported/solr/src/test/java/org/geotools/data/solr/SolrFeatureSourceTest.java, modules/unsupported/solr/src/test/java/org/geotools/data/solr/SolrGeometryTest.java
This PR fixes some Solr online tests failing due to outdated checks on their data setup.
https://osgeo-org.atlassian.net/browse/GEOT-6376
=> [22.x backport][GEOT-6376] Solr datastore online tests failing due to updated data setup

modules/extension/app-schema/app-schema/pom.xml, modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/imageio/geotiff/GeoTiffIIOMetadataEncoder.java, modules/library/main/pom.xml, modules/library/main/src/main/java/org/geotools/data/ows/Response.java, modules/library/main/src/main/java/org/geotools/data/ows/ServiceExceptionParser.java, modules/library/main/src/test/java/org/geotools/data/ows/ServiceExceptionParserTest.java, modules/plugin/coverage-multidim/netcdf/pom.xml, modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffWriter.java, modules/plugin/shapefile/pom.xml, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/shp/xml/ShpXmlFileReader.java, pom.xml
there's a direct dependency on the jdom library
from main and shapefile, which adds nothing that
can't be done with official XML API's, hence
drawing the dependency unnnecessary.
This patch removes such dependency and replaces the
XML parsing done with it by the StAX API which is
faster and is part of the default Java library.
For instance, the following classes have been adapted:
* org.geotools.data.ows.ServiceExceptionParser
* org.geotools.data.shapefile.shp.xml.ShpXmlFileReader
=> [GEOT-6378] Remove jdom dependency from main and shapefile modules

modules/plugin/imagemosaic/src/test/resources/org/geotools/gce/imagemosaic/test-data/hetero_utm/indexer.properties
Set AbsolutePath property of the Indexer to true. That will help to pass unit test when the code is buld and run from D-drive.  
Default relative path behaviour does not work with different drives (Temporary directory with test data is copied to C: drive).
forum message:
https://sourceforge.net/p/geotools/mailman/message/36771990/
=> gt-imagemosaic/testHarvestHeteroUTM unit test fails

modules/library/main/src/main/java/org/geotools/data/DataUtilities.java, modules/library/main/src/test/java/org/geotools/data/DataUtilitiesTest.java
* Current DataUtilities isMatch implementation compares the class of the
attribute descriptor, not the type binding
Signed-off-by: Emilio Lahr-Vivaz <elahrvivaz@ccri.com>
=> [GEOT-4931] Fix comparison of attribute bindings in DataUtilities

modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/v3_2/GML.java
@nmco can you have a look?
Removing this eager loading speeds up single test runs in the IDE by over a second (reference, GetMapIntegrationTest, since WMS unfortunately depends on WFS which in turn loads this), and I could not get a single test to fail, not even in app-schema integration. 
So... maybe the original motivation for this code is just outdated?
=> [GEOT-6396] Avoid preloading GML schema on GML object construction

modules/extension/xsd/xsd-gml3/src/main/java/org/geotools/gml3/v3_2/GML.java
Reverts geotools/geotools#2571
Seeing random build failures in a concurrent GetFeature test in GeoServer, this seems to be the most likely cause, reverting to verify.
=> Revert "[GEOT-6396] Avoid preloading GML schema on GML object construction"

docs/developer/procedures/release.rst
* Updated path to `org/geotools/util/factory/GeoTools.java`
* Added step to create release series folder in sourceforge (SF doesn't let us do this via ssh anymore)
* Added sed commands for updating stable/latest links in readme/docs
These changes are really only applicable for RC releases, so will next be relevant for the 23-RC.
=> Updates to the release guide based on 22-RC release

modules/extension/app-schema/app-schema/src/test/java/org/geotools/appschema/filter/ArithmeticFilterTest.java, modules/extension/app-schema/app-schema/src/test/resources/test-data/MappedFeatureAsOccurrence.xml, modules/library/main/src/main/java/org/geotools/filter/MathExpressionImpl.java, modules/library/main/src/main/java/org/geotools/filter/expression/AddImpl.java, modules/library/main/src/main/java/org/geotools/filter/expression/DivideImpl.java, modules/library/main/src/main/java/org/geotools/filter/expression/MultiplyImpl.java, modules/library/main/src/main/java/org/geotools/filter/expression/SubtractImpl.java, modules/library/main/src/test/java/org/geotools/filter/ExpressionTest.java
-backport 22.x
-added support for xpath numerical attributes for arithmetic operators
-integration tests added in app_schema
backport of https://github.com/geotools/geotools/pull/2602
=> 22.x Backport [GEOT-6399] Arithmetic operations not supported with Complex Attributes

modules/library/main/src/main/java/org/geotools/data/store/ContentFeatureSource.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapefileDataStoreTest.java
fix related to https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-6293 with a test case
(see also https://github.com/locationtech/udig-platform/issues/348)
=> [GEOT-6293] ContentFeatureStore.getReader(Query) returns incorrect results when canTransact() returns false.

modules/unsupported/swt/pom.xml
`crossProjectIntegrationTests ` failing, but `Details` tab doesn't offer any further details.
=> Introduce new module maintainer (me)

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/filter/XPath.java
Repeated values causes omitting elements on AppSchema anonymous unbounded sequences, this PR fix them and testing added on Geoserver app-schema online tests.
=> [GEOT-6370] Repeated value omiting on AppSchema anonymous unbounded sequences

modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/MongoUtil.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoUtilTest.java
Fixes an issue with filename extract from path method for MongoDB HTTP(S) schema support.
=> [GEOT-6394] Mongodb datastore HTTP(s) schema: Fix name extractor from URL

modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/HanaFilterToSQL.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaSpatialFilterOnViewOnlineTest.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaSpatialFilterOnViewTestSetup.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaTestSetup.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/HanaTestSetupBase.java
If the SRID of a column is not known (e.g. the column is part of a
view), a malformed SQL query is generated. In particular, the geometry
string literal does not have the second enclosing apostrophe.
=> [GEOT-6419] gt-jdbc-hana - Missing apostrophe in query generation

modules/library/main/src/main/java/org/geotools/filter/AttributeExpressionImpl.java
Improve the concurrency performance of `AttributeExpressionImpl.evaluate()` by replacing `synchronized` getter and setter by a `volatile` modifier on the `lastAccessor` instance variable.
A synthetic JMH benchmark has been used to assess the performance of the method under different concurrency pressure, with the following results:
| Threads | Baseline | dc80b58e | 3a8386cd|
| -----------: | -----------: | -------------: | -------------: |
|   1 | 8.31 | 8.41 | 8.65 |
|   4 | 1.38 | 24.06 | 34.05 |
|  16 | 2.71 | 96.08 | 114.42 |
|  64 | 2.72 | 86.80 | 90.97 |
| 256 | 2.41 | 64.20 | 63.89 |
Note the peak performance is, expectedly, provided at 16 concurrent threads, which is the number of cores in the machine where the tests were performed.
=> [GEOT-6421] AttributeExpressionImpl.evaluate() performance degradatation under concurrency

docs/user/library/coverage/mosaic.rst, modules/library/metadata/src/main/java/org/geotools/util/DateTimeParser.java, modules/library/metadata/src/test/java/org/geotools/util/DateTimeParserTest.java, modules/plugin/imagemosaic/pom.xml, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/time/TimeParser.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/time/TimestampFileNameExtractor.java, modules/plugin/imagemosaic/src/main/java/org/geotools/gce/imagemosaic/properties/time/TimestampFileNameExtractorSPI.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/properties/time/TimestampFileNameExtractorTest.java
New PR addressing all changes requested in previous https://github.com/geotools/geotools/pull/2648
- Updated GT Doc with links to new ImageMosaic documentation
- ImageMosaic TimeParser class get deprecated (old tests still run properly using deprecated class, new tests use new class on its module)
- Ticket updated with more details on the fuzzy date support
- inclusive flag has been renamed to useHighTime
=> [GEOT-6409]: TimeParser refactoring and improvement

modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/GetFeatureRequest.java, modules/unsupported/wfs-ng/src/main/java/org/geotools/data/wfs/internal/v2_0/StrictWFS_2_0_Strategy.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/AbstractWfsDataStoreOnlineTest.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/GeoServerWFSOnlineTest.java, modules/unsupported/wfs-ng/src/test/java/org/geotools/data/wfs/online/v2_0/GeoServerOnlineTest.java
Looking at an axis order issue encountered by GeoNetwork when updating to GeoTools 21.x:
Reference:
* https://github.com/geonetwork/core-geonetwork/pull/3886
* https://github.com/geoserver/geoserver/pull/3674
=> WFS-NG Check

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java, modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/GeoSciMLTest.java, modules/library/main/src/main/java/org/geotools/feature/type/Types.java
App-Schema WFS GetFeature GML 3.1 and 3.2 reponses include namespaces from all workspaces on isolated workspace (virtual service) request. This PR adds the namespaces map support for the fix to this issue tested on Geoserver.
https://osgeo-org.atlassian.net/browse/GEOT-6425
=> [GEOT-6425] App-Schema WFS GetFeature includes namespaces for all workspaces on isolated workspace

docs/user/library/render/style.rst
fixed in master branch. 
Should be corrected also in other branches.
=> [GEOT-6426] correct goodnessOfFit information in user docs

modules/library/jdbc/src/main/java/org/geotools/data/jdbc/FilterToSQL.java, modules/library/jdbc/src/test/java/org/geotools/jdbc/JDBCFeatureSourceOnlineTest.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
JIRA:https://osgeo-org.atlassian.net/browse/GEOT-6363
Fixed issue related to using String functions on database fields through CQL filters.
E.g the below CQL filter was failing on PostGIS feature sources 
`strToLowerCase("state_name") LIKE '%texa%'`
=> [GEOT-6363]Error in SQL conversion when function uses a like expression

docs/user/library/render/style.rst
=> [Backport 21.x] [GEOT-6426] correct goodnessOfFit information in user docs

docs/user/library/render/style.rst
=> [Backport 22.x] [GEOT-6426] correct goodnessOfFit information in user docs

modules/library/metadata/src/test/java/org/geotools/util/URLsTest.java
[GEOT-6380] URLsTest fails on recent JDK versions (both Java 11 and Java 8)
=> Backport URLsTest fails on recent JDK versions fix to 22.x [GEOT-6380]

docs/user/library/data/mongodb.rst
MongoDB uses top level headings throughout which show up in the TOC.
=> fix headings in mongodb docs

modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/config/AppSchemaDataAccessConfigurator.java, modules/extension/app-schema/app-schema/src/test/java/org/geotools/data/complex/GeoSciMLTest.java, modules/library/main/src/main/java/org/geotools/feature/type/Types.java
App-Schema WFS GetFeature GML 3.1 and 3.2 reponses include namespaces from all workspaces on isolated workspace (virtual service) request. This PR adds the namespaces map support for the fix to this issue tested on Geoserver.
https://osgeo-org.atlassian.net/browse/GEOT-6425
Submitting the PR does not require you to check all items, but by the time it gets merged, they …
=> [22.x backport][GEOT-6425] App-Schema WFS GetFeature includes namespaces for all workspaces on isolated workspace

modules/library/main/src/main/java/org/geotools/feature/simple/SimpleFeatureTypeBuilder.java
I figured no docstring is better than an incomplete one. I'm not comfortable explaining the function, so if someone wants to contribute a docstring, that would be great!
=> Fix typos, remove incomplete docstring

docs/user/library/main/data.rst
Just found a few typos in the docs.
=> Fix documentation typos in method names

modules/library/cql/src/main/java/org/geotools/filter/text/ecql/ECQL.java, modules/library/main/src/main/java/org/geotools/data/store/ContentFeatureStore.java, modules/library/main/src/main/java/org/geotools/feature/simple/SimpleFeatureBuilder.java
The `@param`s might be overkill, but I think the main description would be helpful. Reading the docs, I defaulted to assuming `setUserData` could mean "set feature data".
=> Docstring and typos

modules/library/render/src/test/java/org/geotools/renderer/lite/LabelSpacingTest.java, modules/library/render/src/test/java/org/geotools/renderer/lite/LabelWrapTest.java
See if we can make the N platforms and M versions of Java happy again....
=> Relaxing a bit more the test tolerances, as the main build server is not happy with them (Travis, Appveyor and Github apparently are though)

modules/library/render/src/main/java/org/geotools/renderer/RenderListener.java, modules/library/render/src/main/java/org/geotools/renderer/lite/CompositingGroup.java, modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java
=> [22.x backport][GEOT-6398] RenderListener Extension (#2600)

.github/workflows/integration.yml, modules/library/referencing/src/test/java/org/geotools/referencing/GeodeticCalculatorTest.java, modules/unsupported/swing/src/test/java/org/geotools/swing/RenderingExecutorTestBase.java
This builds downstream projects, to spot unintended incompatible changed (the build will fail if the incompatible change is intended, but that's ok).
=> Downstream integration build

modules/library/jdbc/src/test/java/org/geotools/data/jdbc/SQLFilterTestSupport.java, modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_arrayAnyMatch.java, modules/library/main/src/main/resources/META-INF/services/org.opengis.filter.expression.Function, modules/library/main/src/test/java/org/geotools/filter/function/FilterFunction_arrayAnyMatchTest.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisPSFilterToSql.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
=> [GEOT-6377]: added new filter function arrayAnyMatch and a PostGIS encoding using its ANY function (Backport to 22.x)

modules/library/jdbc/src/test/java/org/geotools/data/jdbc/SQLFilterTestSupport.java, modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_arrayAnyMatch.java, modules/library/main/src/main/resources/META-INF/services/org.opengis.filter.expression.Function, modules/library/main/src/test/java/org/geotools/filter/function/FilterFunction_arrayAnyMatchTest.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/FilterToSqlHelper.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisFilterToSQL.java, modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostgisPSFilterToSql.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisFilterToSQLTest.java
=> [GEOT-6377]: added new filter function arrayAnyMatch and a PostGIS encoding using its ANY function (Backport to 21.x)

modules/library/main/src/main/java/org/geotools/filter/function/FilterFunction_toWKT.java, modules/library/main/src/test/java/org/geotools/filter/function/FilterFunction_toWKTTest.java
=> [GEOT-6502] Add Geometry.class as context in FilterFunction_toWKT (22.x backport)

modules/extension/wms/src/main/java/org/geotools/ows/wms/map/WMSCoverageReader.java, modules/extension/wms/src/test/java/org/geotools/ows/wms/map/WMSLayerTest.java, modules/extension/wms/src/test/resources/org/geotools/ows/wms/map/caps130_jpeg_only.xml
JIRA : https://osgeo-org.atlassian.net/browse/GEOT-6508
-fixed WMSCoverageReader format handling
-added new unit test and sample capability doc
=> [GEOT-6805] WMSCoverage Reader does not default to remote format when requested with an unknown format

modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/wkb/HanaWKBParser.java, modules/plugin/jdbc/jdbc-hana/src/main/java/org/geotools/data/hana/wkb/HanaWKBWriter.java, modules/plugin/jdbc/jdbc-hana/src/test/java/org/geotools/data/hana/wkb/HanaWKBTest.java
MultiPoint WKBs are not parsed properly by gt-jdbc-hana's WKB parser.
Instead of parsing each member of the multi-point as an independent
point, the parser interprets the following data as raw coordinates.
=> [GEOT-6509] gt-jdbc-hana - MultiPoint WKBs not parsed properly

modules/library/cql/ECQL.md
The CQL EBNF document appears to have a typo. It says "parent" instead of "paren".
=> Fix "parent" (should be "paren" for parenthesis)

modules/unsupported/css/src/main/java/org/geotools/styling/css/CssTranslator.java, modules/unsupported/css/src/test/java/org/geotools/styling/css/TranslatorSyntheticTest.java
Follow up on "[GEOT-6446] Allow to place a text symbolizer Graphic at an offset vs its own label"
=> Css shield placement support

modules/plugin/jdbc/jdbc-postgis/src/main/java/org/geotools/data/postgis/PostGISPSDialect.java, modules/plugin/jdbc/jdbc-postgis/src/test/java/org/geotools/data/postgis/PostgisSimplifiedGeometryPreparedTest.java
backport of https://github.com/geotools/geotools/pull/2797
=> [Backport 22.x][GEOT-6511] PostGIS JDBC does not request Point geometry column in TWKB with prepared statements enabled

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java
App-schema is getting "IllegalArgumentException: Could not find working property accessor for attribute" when it gets an empty collection on a 1..n cardinality attribute (jdbc multivalue).
This issue is replicated using Postgresql and a jdbc configuration following same steps and mappings as Geoserver documentation, but having no items for a root feature multivalue declared element:
https://docs.geoserver.org/stable/en/user/data/app-schema/mapping-file.html#attributes-with-cardinality-1-n
This PR fixes the issue and end to end testing is being added on Geoserver App-Schema tests.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-6507
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if …
=> [GEOT-6507] App-Schema IllegalArgumentException when getting an empty collection on a jdbc multivalue join attribute

modules/extension/app-schema/app-schema/src/main/java/org/geotools/appschema/jdbc/JoiningJDBCFeatureSource.java, modules/extension/app-schema/app-schema/src/main/java/org/geotools/data/complex/DataAccessMappingFeatureIterator.java
App-schema is getting "IllegalArgumentException: Could not find working property accessor for attribute" when it gets an empty collection on a 1..n cardinality attribute (jdbc multivalue).
This issue is replicated using Postgresql and a jdbc configuration following same steps and mappings as Geoserver documentation, but having no items for a root feature multivalue declared element:
https://docs.geoserver.org/stable/en/user/data/app-schema/mapping-file.html#attributes-with-cardinality-1-n
This PR fixes the issue and end to end testing is being added on Geoserver App-Schema tests.
JIRA issue:
https://osgeo-org.atlassian.net/browse/GEOT-6507
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if …
=> [22.x backport][GEOT-6507] App-Schema IllegalArgumentException when getting an empty collection on a jdbc multivalue join attribute

.github/PULL_REQUEST_TEMPLATE.md
@ianturton do you think this change to the checklist would help reviewing PRs?
@jodygarnett also eager to hear your opinion.
=> Avoid mixed/confusing changes in PRs

modules/library/cql/ECQL.md
The grammar indicates comments are supported, they are not.
=> remove comment from grammar

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgDialect.java, modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgFilterToSQL.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDatetimeTest.java
When testing andrea's PR (https://github.com/geotools/geotools/pull/2822 - with a TIME dimension enabled geopkg in WMS getcap), I noticed a few problems, and made some fixes;
a) GeoPkgDialect.java -- it was using sql.Date instead of util.Date to determine if needed to do a conversion
b) I added timestamp-related test cases to GeoPkgDatetimeTest.java
c) When looking at the date test cases in a timezone that is negative (i.e. GMT-8 PST) that I was getting incorrect results.  In GMT or a +ive offset timezone (europe) it works.  This had to so with how geotools/sql lite interpret dates local-timezone vs UTC
* use "utc" instead of "localtime" in GeoPkgFilterToSQL.java (sql lite "datetime" function)   
d) When adding testBetween_timestamp() test case, I noticed that sql lite was not doing "as …
=> GEOT-6520 - fix geopkg filter and aggregates

modules/plugin/geopkg/src/main/java/org/geotools/geopkg/GeoPkgFilterToSQL.java, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPkgDatetimeTest.java
The date columns were being handles a bit incorrectly - it has to do with how Java and geopkg deal with dates and local timezones.
The fix was to NOT convert the dates (no changes for timestamps);
old old method: SELECT ... datetime(date,'localtime')
old method:  SELECT ... datetime(date,'utc')
new method: SELECT ... datetime(date) -- no conversion info
I also put in a timezone test that messes with the java timezone to help make sure this problem doesn't come back.
covered by GEOCAT CLA
The …
=> [GEOT-6520] better handling of timezones in geopkg date columns

modules/unsupported/geojson/src/main/java/org/geotools/geojson/GeoJSONUtil.java, modules/unsupported/geojson/src/test/java/org/geotools/geojson/FeatureJSONTest.java
Signed-off-by: Jim Hughes <jnh5y@ccri.com>
This PR adds a wrapper around OutputStreamWriters so that they are not closed.  This allows clients to manage their own writers better.
=> [GEOT-6538] GeoJson module closes input writers

modules/extension/wmts/src/main/java/org/geotools/ows/wmts/model/WMTSCapabilities.java, modules/extension/wmts/src/main/java/org/geotools/ows/wmts/request/AbstractGetTileRequest.java, modules/extension/wmts/src/test/java/org/geotools/ows/wmts/WebMapTileServerTest.java, modules/library/referencing/src/main/java/org/geotools/referencing/AbstractIdentifiedObject.java, modules/library/referencing/src/main/java/org/geotools/referencing/factory/epsg/DirectEpsgFactory.java, modules/library/render/src/main/java/org/geotools/renderer/lite/RendererUtilities.java
- Changed the way in which the source matrixset is selected so that it compares the request SRS and the matrixset SRS names rather than comparing the whole CRS. This will reduce the amount of transformation that will be needed when the tiles are returned
- Added unit tests to verify that the changes work as expected
- Some spelling corrections …
=> [GEOT-6533] Selection of source matrixset when cascading WMTS layers does not take into account Longitudefirst CRSs

build/maven/jar-collector/src/main/java/org/geotools/maven/JarCollector.java
Signed-off-by: Jody Garnett <jody.garnett@gmail.com>
Fix jarCollector warning
=> fix jarCollector warning

build/release/build_release.sh
=> Change build_release to carefully build maven plugins single threaded

modules/library/render/src/main/java/org/geotools/renderer/lite/StreamingRenderer.java, modules/library/render/src/test/java/org/geotools/renderer/lite/StreamingRendererTest.java
=> [GEOT-6553] NPE in StreamingRenderer if dynamic densification is enabled on a projection without ProjectionHandler

modules/library/metadata/src/test/java/org/geotools/util/URLsTest.java
This is just a backport cherry-pick of commits made on master but not in 22.x. The build of 22.x version on Windows fails as in the ticket otherwise.
=> [22.x backport] [GEOT-6380] Fix URLsTest on Windows

modules/plugin/geotiff/src/main/java/org/geotools/gce/geotiff/GeoTiffFormat.java, modules/plugin/geotiff/src/test/java/org/geotools/gce/geotiff/GeoTiffWriterTest.java
`GeoTiffWriterTest`'s `setFinalStaticField()` was using reflection to
change the value of the statically initialized `GeoTiffFormat.DEFAULT_WRITE_NODATA`
boolean, to no effect.
The idea being to change the default value of
`GeoTiffFormat.WRITE_NODATA` parameter default value was futil, since
`DEFAULT_WRITE_NODATA` is passed by value and hence the use of
reflection to change it had no effect.
This patch makes `DEFAULT_WRITE_NODATA` default value's dynamic by
returning the current value of the `geotiff.writenodata` System property
(still defaulting to `true`), and fixes the test expectations.
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as …
=> Fix GeoTiffWriterTest, make default "write no data" value dynamic

modules/library/metadata/src/main/java/org/geotools/util/factory/GeoTools.java
`GeoTools.scanForSystemHints()` synchronizes on its static
`BINDINGS` variable, which is only modified during the class'
static initialization. The method is side-effect free and
only mutates the argument object, hence there's no need
to synchronize on this field. …
=> [GEOT-6506] Unnecessary synchronization in GeoTools.scanForSystemHints()

modules/plugin/geopkg/src/main/resources/org/geotools/geopkg/gpkg_spatial_index.sql, modules/plugin/geopkg/src/test/java/org/geotools/geopkg/GeoPackageTest.java
Fixes [GEOT-6565](https://osgeo-org.atlassian.net/browse/GEOT-6565) bug. 
Identifiers in SQL queries for spatial index creation has been quoted to allow more names to be used for feature types.
The bug has been discovered while trying to create a spatial index for GeoPackage with a feature type named "all".
=> [GEOT-6565] GeoPackage spatial index creation fails with particular feature type names

docs/user/welcome/upgrade.rst, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStore.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureWriter.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileHeader.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileReader.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapeFileDbaseHeaderCharsetTest.java, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dbase-cs/data_cn.xml, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dbase-cs/data_en.xml, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dbase-cs/data_ru.xml
Changes proposed are to make use of charset when read / write DBF header field's names, not only the data.
This also applies to the following tickets:
- [GEOT-3357] DBF header parsing does not use the provided charset
- [GEOT-3093] can't support Chinese fields in shpfiles
- [GEOT-2135] Could shapefile supports coding with DBF header
Some of the above are closed already but in fact the issue is still there. In particular this PR fixes reading in a "memory mapped" case and adds an ability to write field's names according to provided charset.
IMPORTANT NOTE: PR removes **public** method  `DbaseFileHeader.readHeader(ReadableByteChannel, Charset)` in favor of using the constructor to pass a charset. Though the method is public it should not be used widely. Keeping it will complicate the code …
=> [GEOT-3377] Charset not used for DBF header

modules/library/main/src/main/java/org/geotools/geometry/jts/GeometryClipper.java, modules/library/main/src/test/java/org/geotools/geometry/jts/GeometryClipperTest.java
I noticed an issue with vector tiles - polygons kept "disappearing."
Root cause - when GeometryClipper clips a polygon-polyon, the result might be multipolygon. Unfortunately, filterCollection() will remove this.
Fix - flattenCollection() before the filter. …
=> [GEOT-6586] GeometryClipper - doesn't handle polygon x polygon when result is multipolygon

modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/FESConfiguration.java, modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/SortByTypeBinding.java, modules/extension/xsd/xsd-fes/src/main/java/org/geotools/filter/v2_0/bindings/SortPropertyTypeBinding.java, modules/extension/xsd/xsd-fes/src/test/java/org/geotools/filter/v2_0/bindings/SortByTypeBindingTest.java, modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/bindings/WfsQueryTypeTest.java
Fix for [GEOT-6558](https://osgeo-org.atlassian.net/browse/GEOT-6588) . Element SortBy is not encoded in getFeature request (WFS 2.0)
=> [GEOT-6588] : SortBy element not encoded with FESConfiguration

modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileDataStore.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/ShapefileFeatureWriter.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileHeader.java, modules/plugin/shapefile/src/main/java/org/geotools/data/shapefile/dbf/DbaseFileReader.java, modules/plugin/shapefile/src/test/java/org/geotools/data/shapefile/ShapeFileDbaseHeaderCharsetTest.java, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dbase-cs/data_cn.xml, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dbase-cs/data_en.xml, modules/plugin/shapefile/src/test/resources/org/geotools/data/shapefile/test-data/dbase-cs/data_ru.xml
Backport of #2912.
If this PR will be applied, in some rare cases of when `DbaseFileHeader` is used directly there can be **wrong results**. Consider such a piece of code:
```
DbaseFileHeader header = new DbaseFileHeader(); // default charset
header.readHeader(inChannel, ANOTHER_NON_ENG_CHARSET);
header.addColumn("NON_ENG_COL_NAME", 'C', 100, 0);
writer = new DbaseFileWriter(header, outChannel, ANOTHER_NON_ENG_CHARSET);
writer.write(new Object[] { ... some data ... });
writer.close();
```
Here the `header` will use default charset on write stage, not `ANOTHER_NON_ENG_CHARSET` as could expect an inattentive end-user.
If header is used indirectly, e.g. via `DbaseFileReader` or `ShapefileDataStore` - everything must be fine.
Please let me know how this can be enhanced or perhaps documented …
=> [23.x backport] [GEOT-3377] Charset not used for DBF header

modules/plugin/mongodb/src/main/java/org/geotools/data/mongodb/FilterToMongo.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/FilterToMongoTest.java, modules/plugin/mongodb/src/test/java/org/geotools/data/mongodb/MongoDataStoreTest.java
JIRA ticket https://osgeo-org.atlassian.net/browse/GEOT-6598
This pull request fixes the translation mechanism from Not filter to $not operator for mongodb,
by using it as a top level operator only if no property name is specified in the child condition. …
=> [GEOT-6598] Ogc filter to mongo operator translation fails

modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticAttribute.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticDataStore.java, modules/unsupported/elasticsearch/src/main/java/org/geotools/data/elasticsearch/ElasticFeatureTypeBuilder.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticAttributeTest.java, modules/unsupported/elasticsearch/src/test/java/org/geotools/data/elasticsearch/ElasticFeatureFilterIT.java
Fixes [GEOT-6575](https://osgeo-org.atlassian.net/browse/GEOT-6575).
Short names are an outdated elasticsearch concept, deprecated in 2.0: https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_20_mapping_changes.html#_fields_cannot_be_referenced_by_short_name
Thus, I have removed the functionality. The display name was updated, now only reflecting the name. In addition, I've updated the documentation to be more clear about the use of aliases - they must be defined in your elasticsearch index in order for the plugin to properly use the alias. It will not generate one for you.
Coincides with GeoServer PR: https://github.com/geoserver/geoserver/pull/4256
> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as …
=> [GEOT-6575] Removing short name functionality and clarifying alias functionality

modules/extension/tile-client/src/main/java/org/geotools/tile/Tile.java, modules/extension/tile-client/src/test/java/org/geotools/tile/impl/osm/OSMTileTest.java
=> [GEOT-6608] Fix user-agent for OSM tiles

modules/library/coverage/src/main/java/org/geotools/coverage/grid/io/footprint/WKBLoaderSPI.java, modules/plugin/imagemosaic/src/test/java/org/geotools/gce/imagemosaic/ImageMosaicFootprintsTest.java
WKB FootprintLoader messup when concurrently loading since it was using a shared WKBReader instance which is not thread-safe 
=> [GEOT-6614]: WKB FootprintLoader messup when concurrently loading

modules/library/main/src/main/java/org/geotools/data/ows/SimpleHttpClient.java
Increasingly services such as OSM (see https://osgeo-org.atlassian.net/browse/GEOT-6608 for example) are refusing connections for requests with a default user agent string. 
See https://osgeo-org.atlassian.net/browse/GEOT-6618
=> [GEOT-6618] Add a better default header to SimpleHttpClient

modules/extension/xsd/xsd-wfs/src/main/java/org/geotools/wfs/v2_0/bindings/FeatureTypeTypeBinding.java, modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/bindings/FeatureTypeTypeBindingTest.java
Issue : https://osgeo-org.atlassian.net/browse/GEOT-6620
-duplicate entries in Other SRS list of a feature type described in WFS
2.0.0 document removed.
=> [GEOT-6620] OTHER_SRS list has duplicate entries for WFS 2.0.0

modules/library/referencing/src/main/java/org/geotools/referencing/CRS.java, modules/library/referencing/src/test/java/org/geotools/referencing/CrsTest.java
=> [GEOT-6595] CRS can't get axis order from compound CRS

modules/extension/xsd/xsd-wfs/src/main/java/org/geotools/wfs/v2_0/bindings/FeatureTypeTypeBinding.java, modules/extension/xsd/xsd-wfs/src/test/java/org/geotools/wfs/v2_0/bindings/FeatureTypeTypeBindingTest.java
Backport of https://github.com/geotools/geotools/pull/2973
-duplicate entries in Other SRS list of a feature type described in WFS
2.0.0 document removed.
=> [Backport-23.x][GEOT-6620] OTHER_SRS list has duplicate entries for WFS 2.0.0
